### ISSUE TITLE
Google Too Many Requests Exception

### ISSUE THREAD

**Issue by jasonstone20** [searxng/searxng#1001]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2022.03.13-cd92a7ea

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

Engine stats - google
Engine name	Scores	Result count	Response time	Reliability
google	31259.9	9
0.7	100
Errors and exceptions
Message	timeout	Percentage	0
Filename	searx/search/processors/abstract.py:102
Function	handle_exception
Code	count_error(self.engine_name, exception_or_message)
Exception	httpx.TimeoutException	Percentage	0
Filename	searx/search/processors/online.py:96
Function	_send_http_request
Code	response = req(params['url'], **request_args)
Exception	searx.exceptions.SearxEngineTooManyRequestsException	Percentage	0
Parameter	Too many request
Filename	searx/search/processors/online.py:96
Function	_send_http_request
Code	response = req(params['url'], **request_args)
Submit a new issue on Github including the above information
Powered by searxng - 2022.03.13-cd92a7ea — a privacy-respecting, hackable metasearch engine
Source code | Issue tracker | Engine stats | Public instances
**Additional context**

**Comment by return42** [comment]
See https://github.com/searxng/searxng/issues/531
