### ISSUE TITLE
Discussion: change category order / engine categories

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#101]
### Category order
Change the default category order to something more usual:
1. General
1. Images
1. Videos
1. News
1. Map
1. Music
1. IT
1. Science
1. Files
1. Social media

### Application category

Perhaps create an application category:
* apk mirror
* fdroid
* google play apps
* openrepos

Currently, these engines are in the Files category.

### Video category

Remove bittorrent engines:
* 1337x
* btdigg
* kickass
* nyaa
* piratebay
* tokyotoshokan
* torrentz
* yggtorrent

### Music category

Remove bittorrent engines:
* btdigg
* kickass
* nyaa
* piratebay
* tokyotoshokan
* torrentz
* yggtorrent

**Comment by return42** [comment]
Do we need "Social media"? .. The only engine I have (that works) is reddit and personally I would prefer reddit in category "general".

**Comment by dalf** [comment]
I close the issue "category order".

There are still some engine with the `social` category: digg, gpodder, reddit.

If there are no engine using the `social` category, this category won't be displayed.

**Comment by githubjsorg** [comment]
I also would like the ability to reorder the categories in the search results.
