### ISSUE TITLE
Option to disable categories

### ISSUE THREAD

**Issue by mskf1383** [searxng/searxng#1019]
There are a lot of categories and I don't want all of theme. There must be an option to disable unusable categories.

**Comment by return42** [comment]
See https://docs.searxng.org/admin/engines/settings.html#categories-as-tabs

**Comment by mskf1383** [comment]
I mean an options for users, not admins.

**Comment by return42** [comment]
IMO serving categories is up to the instance.

> There are a lot of categories and I don't want all of theme. 

If there are no good reasons for your request I have not thought of yet, I vote to close this issue.

----

In general I hesitate to personalize the UI more and more / personalization always goes hand in hand with the loss of privacy and makes the UI and the implementation more complex.

We have a lot of preferences a user can set right now, while I assume only 1% of the user base personalize their preferences.

**Comment by aleex5** [comment]
searx already had this feature, when you deactivate all the engines of a category, this category disappeared, but searxng in some of the updates lost this function.

**Comment by return42** [comment]
@aleex5 it isn't really what the opener asks for. What you point out is an issue, to not to mix issues and new features I opened https://github.com/searxng/searxng/issues/1020 / thanks for pointing out :+1:
