### ISSUE TITLE
Don't show categories if there is not active engine in

### ISSUE THREAD

**Issue by return42** [searxng/searxng#1020]
I assume since #634 has been merged (may be here in the [template](https://github.com/searxng/searxng/pull/634/files#diff-06c0427b8785e4a06887686469c17f130f2644af8f7827120252ab44f8fd50c1)) all categories (listed in setting `categories_as_tabs `) are selectable in the UI no matter if there is an engine active in the category or not.

Reported-by: @aleex5 https://github.com/searxng/searxng/issues/1019#issuecomment-1079907510

**Comment by mrpaulblack** [comment]
Also:
Removing default categories from settings.yml will not remove them from the webui... Maybe it uses the default from default settings?

**Comment by return42** [comment]
OK, now I see its caused by the [use_default_settings: true](https://docs.searxng.org/admin/engines/settings.html?#use-default-settings).  The value `categories_as_tabs` is a dictionary type (a4c2cfb837a) and dictionary types are merged additive.

**Comment by witchent** [comment]
Any update here? It seems like the corresponding PR was closed? But the categories_as_tabs is still ignored if you use the default_settings.
Or is there an easy workaround to remove some categories shown?

**Comment by return42** [comment]
> Any update here? It seems like the corresponding PR was closed?

@witchent sorry for the delay on this issue, today I send 

- https://github.com/searxng/searxng/pull/2311

would you give it a try / thanks!

**Comment by return42** [comment]
> Also: Removing default categories from settings.yml will not remove them from the webui... Maybe it uses the default from default settings?

@mrpaulblack yes, to fix I send 

- https://github.com/searxng/searxng/pull/2312

would you give it a try / thanks!

**Comment by return42** [comment]
Closed by

- https://github.com/searxng/searxng/pull/2311
- https://github.com/searxng/searxng/pull/2312
