### ISSUE TITLE
Add donation option

### ISSUE THREAD

**Issue by MontyQI** [searxng/searxng#1025]
Add some form of donation to maintainers of searxng. It compensate work done to searxng, and maybe help the project itself.
**Describe the solution you'd like**
On results page or maybe index page add link to donation. (Maybe something like this #931?)
The donation should also be possible to make with crypto, (the best monero) to maximise privacy.
**Describe alternatives you've considered**
Add link on github.

**Additional context**

**Comment by mrpaulblack** [comment]
This is impl. in https://github.com/searxng/searxng/pull/1404; Closing.
