### ISSUE TITLE
Total time on preview video with simple theme

### ISSUE THREAD

**Issue by caywin25** [searxng/searxng#1027]
Hello, 

Is it possible to implement on the video preview images the total time of the videos with the simple theme please?
It's already in place with the oscar theme.

On the file video1.png you can't see the length (simple theme) while on the file video2.png you can see the length of the video (oscar theme).

![video1](https://user-images.githubusercontent.com/55273439/160833699-34de2543-a101-4238-b1d3-f9992d706f51.png)
![video2](https://user-images.githubusercontent.com/55273439/160833689-837f1c01-d8e1-4741-8fd4-c221fa177688.png)

Thank you very much.

**Comment by mrpaulblack** [comment]
just FYI: this should be part when reworking the videos category to behave like the current image category. We could either add this to the dtails modal or underneath the thumbnail for example IMO
