### ISSUE TITLE
[discussion] about yaml files: syntax, indentation, lint ...

### ISSUE THREAD

**Issue by return42** [searxng/searxng#104]
**indentation**

The suggested syntax for YAML files is to use 2 spaces for indentation. We use sometimes 2 and sometimes 4 spaces, even in the same file. 

- For the future I would suggest to normalize YAML files to have 2 spaces for indentation. 

**markup**

We use [PyYAML](https://pypi.org/project/PyYAML/) which supports [YAML 1.1](https://yaml.org/spec/1.1/) syntax [refcard](https://yaml.org/refcard.html) 

**lint**

It might be worth to have a look at a lint tool for our CI?

- https://github.com/adrienverge/yamllint

**Comment by return42** [comment]
>  It might be worth to have a look at a lint tool for our CI?

Implemented a draft in  https://github.com/searxng/searxng/pull/105

**Comment by dalf** [comment]
Is there a way to format the .yml file automatically ?

**Comment by return42** [comment]
I don't know .. but I think I can do it in less than 20min ,, should I give it a try in #105 ?

**update**: done see commits in https://github.com/searxng/searxng/pull/105/commits

For future convenience: yamllint can be integrated in IDEs https://yamllint.readthedocs.io/en/stable/text_editors.html

**Comment by return42** [comment]
I close this issue (discussion), since we have #105 merged. 

PR #105 includes a [`make test.yamllint`](https://github.com/searxng/searxng/pull/105/commits/393c06f) / CI covers what we discussed here.
