### ISSUE TITLE
Make the about page translatable

### ISSUE THREAD

**Issue by Linerly** [searxng/searxng#1045]
Currently, the about page is only in English, it would be nice if the about page can be translated in Weblate

**Comment by dalf** [comment]
The about page ( & search syntax page) can be translated on git without weblate:
* `en` in the [searxng/searx/infopage/en/](https://github.com/searxng/searxng/tree/master/searx/infopage/en) directory stand for English like in `translations` directory.
* Send a PR with your translation in `searxng/searx/infopage/id` (or whatever language code you want). You don't have to translate all the pages.

**Comment by return42** [comment]
The plan was to translate the info pages ("search syntax", "about" and may be other upcoming pages).  SearXNG can handle translations but it is not yet clear how the translation process would be (at least not to me). May be @dalf can tell more about the thought process.

Personally I think we should revise the "about page" before we translate.  I haven't had time for but I think there is some content in the about page that is not so important and may be other important information is still missing .. suggestions are welcome.

----

Oops me & @dalf posted in the same minute :-)

**Comment by dalf** [comment]
> Personally I think we should revise the "about page" before we translate. 

do we have rolling release or not? :-)

I suggest this: @Linerly, give a try, we will see how is it going.
The content of the about page may change in future, but for sure, not everything.

**Comment by return42** [comment]
> do we have rolling release or not? :-)

Yes but not "rolling translations" :-)

But it is OK for me to translate what we have .. since I can't say when I have time to revise .. and we have _this_ about page since a long period without users asked to modify.  So yes, lets start with the translations.

**Comment by return42** [comment]
@Linerly I close this issue / again thanks for your translation in PR #1242
