### ISSUE TITLE
Bug: Searx.be duckduckgo engine

### ISSUE THREAD

**Issue by simpvn** [searxng/searxng#1053]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.03

**How did you install SearXNG?**

Using public instance searx.be

**What happened?**

DuckDuckGo cannot retrieve results

**How To Reproduce**

Enable search engine DDG -> Search anything -> Recieve error: "Engines cannot retrieve results: duckduckgo (Suspended: access denied)"

**Expected behavior**

Get DDG search results

**Screenshots & Logs**

<img width="1416" alt="Screen Shot 2022-04-04 at 10 45 13" src="https://user-images.githubusercontent.com/78357927/161470423-712c733b-b456-41f2-9b12-13d5cb8ad7bf.png">

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by simpvn** [comment]
DDG works normally for now

**Comment by simpvn** [comment]
Happening again

**Comment by mrpaulblack** [comment]
Hi @vncrack ,
Idk what instance you are using, but there is no official SearXNG instance. The instance you are using is probably IP blocked by duckduckgo, because of its many search requests. There is nothing really we can do upstream about this... For that reason I will close this issue; Closing.
