### ISSUE TITLE
Icons seems broken

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#1057]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

latest commit

**Problem**

All the icons seems broken, invidious and openstreetmap icons don't load:
- https://searx.be/static/img/icons/photon.png
- https://paulgo.io/static/img/icons/photon.png
- https://searx.be/static/img/icons/invidious.png
- https://paulgo.io/static/img/icons/invidious.png

**Comment by mrpaulblack** [comment]
Only a problem in oscar tho, since these icons are not used in simple...

**Comment by unixfox** [comment]
Should we remove the icons from oscar like on simple theme then?

**Comment by tiekoetter** [comment]
This is the correct path:


https://searx.be/static/themes/oscar/img/icons/photon.png
https://searx.be/static/themes/oscar/img/icons/invidious.png

**Comment by mrpaulblack** [comment]
The fix should be easy...?:
https://github.com/searxng/searxng/blob/fcb626dedd3965de4fa6c95c47a34fdd14348afd/searx/templates/oscar/macros.html#L8
