### ISSUE TITLE
English (India) en-IN : Local Indian search in English

### ISSUE THREAD

**Issue by debpalash** [searxng/searxng#1074]
I've searched with some keywords but couldn't find posts asking similar but i fthere's already let me know. So here it goes..

There's currently hi-IN present which pull local results in Hindi language, where in India there are majority of people use English as their internet language. So local search in english is actually more important than hi-IN.

**Is your feature request related to a problem? Please describe.**
 I have to ditch searx/ng when i need a keyword to pull local results. Because i dont read Hindi.

**Describe the solution you'd like**
Suggesting "English (India) en-IN" local search to be added or modified to work.

**Describe alternatives you've considered**
Whoogle and DDG has predefined selection but those are not true Searx alternatives.

**Comment by return42** [comment]
> Whoogle and DDG has predefined selection but those are not true Searx alternatives.

We just think about a rework of the language/region topic in SearXNG .. ATM we have an algorithm that filters out the top most language- & region- tags the engines do support.

I don't know if it is better to have a static list of predefined selection, we have not finalized our analyse yet .. we need more time for a decision  .. but `en-IN` was one language tag I missed these days when I worked on this topic.

thanks for pointing out .. and .. sorry that I can't do more for you ATM.

-----

For reference whoogle's [language-tags](https://github.com/benbusby/whoogle-search/blob/main/app/static/settings/languages.json) and [region-tags](https://github.com/benbusby/whoogle-search/blob/main/app/static/settings/countries.json)

![grafik](https://user-images.githubusercontent.com/554536/162915020-574d4896-13e0-4294-8d32-a81a36a17e0b.png)

**Comment by debpalash** [comment]
> I don't know if it is better to have a static list of predefined selection, we have not finalized our analyse yet .. we need more time for a decision .. but `en-IN` was one language tag I missed these days when I worked on this topic.

It's okay, I'm just pointing this out for future. I can't believe a metasearch engine could be as fast as ddg or google when i see a keyword pulls a search on my own instance. And Image search on simple theme is like crazy fast with some providers i was like heck searx image search never looks so dynamic; how this magic is working lol

> thanks for pointing out .. and .. sorry that I can't do more for you ATM.

Hey.. don't be sorry man :) thank you for working on Searxng 👍

**Comment by return42** [comment]
> We just think about a rework of the language/region topic in SearXNG .. 

Today we merged our rework:

- https://github.com/searxng/searxng/pull/2269

Not all engines do support `en-IN` but if you decidedly select the google engine (`!go`) you get local results (India) in the English language:

![grafik](https://user-images.githubusercontent.com/554536/228577521-1dc6d810-72c5-445e-bf95-575daf2afb25.png)
