### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1077]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.08

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @jason88fr ,

Thanks for creating the bug report. Since the template is not filled out and the error is an HTTP 403 (which means the instance is blocked by mojeek) there is nothing we can really do about this; Closing.
