### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1080]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.08

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 50
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 0
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/qwant.py:110`
  * Function: `response`
  * Code: `search_results = loads(resp.text)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @jason88fr ,
The errors looks like there are sometimes request timeouts. I get the same on my instance sometimes. Since the percentage for those errors are really low and the template is not filled out I will close this for now; Closing.
