### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by micael-jerry** [searxng/searxng#1083]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.09-27f8fa6f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by mrpaulblack** [comment]
Hi @mick-j-06 ,
Thank you fir opening an issue. Your bug template is empty tho and there is not even any error in it, so I will close it. Feel free to add a comment with further info :+1: ; Closing.
