### ISSUE TITLE
Bug: qwant videos engine

### ISSUE THREAD

**Issue by osushioisii** [searxng/searxng#1098]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.09-27f8fa6f-dirty

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: AttributeError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/qwant.py:159`
  * Function: `response`
  * Code: `title = item.get('title', None)`

**Comment by mrpaulblack** [comment]
Hi @osushioisii ,
I cannot repro this exception log on my instance... Can you please fill out the form so we have more info about the issue please?
