### ISSUE TITLE
can't find info of golang version: go1.17.2

### ISSUE THREAD

**Issue by Stratos-Crimson** [searxng/searxng#1100]
version: #1071
**How did you install SearXNG?**
 I used the install scripts.
**What happened?**
The filtron and morty scripts errored out at the go installation.

**How To Reproduce**
Run the filtron or morty scripts after running the searxng script.

**Expected behavior**
install go.

**Screenshots & Logs**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
ERROR: /searxng/searxng/utils/lib_go.sh: line 137: can't find info of golang version: go1.17.2

**Additional context**
I did install go manually following the instructions from the searxng wiki after I got this error but it was still showing me the error. Perhaps it's due to some export things that don't persist?

**Comment by return42** [comment]
To check which version will be installed in the HOME folder of the filtron service account, use:

    ./utils/filtron.sh --getenv GO_VERSION
    INFO:  ..
    go1.17.2

To get into the environment of the filtron service, open a bash:

    sudo -H ./utils/filtron.sh shell

In this environment you can see if go has been installed:

    [filtron@example.org ~]$ which go
    /usr/local/filtron/local/go/bin/go

If go is installed check version number:

    [filtron@example.org ~]$ go version
    go version go1.17.2 linux/amd64

otherwise look at the environment :

```
[filtron@example.org ~]$ env
  ..
HOME=/usr/local/filtron
  ..
USER=filtron
  ...
PATH=/usr/local/filtron/local/go/bin:/usr/local/filtron/go-apps/bin:...
  ...
GOPATH=/usr/local/filtron/go-apps
```

**Comment by Stratos-Crimson** [comment]
Should I do this after manually installing go?

**Comment by return42** [comment]
If you have installed filtron by [this command](https://docs.searxng.org/utils/filtron.sh.html):

    sudo -H ./utils/filtron.sh install all

go should be installed in the HOME of the filtron user, if not something went wrong. Use the commands from above to check if go has been installed and check the environment.

**Comment by Stratos-Crimson** [comment]
okay but I know that it wasn't installed because it would show that it's downloading go's installation archive but instead of that it just error-ed out. I will do what you have said after I try to install searxng again and report back. Thanks.

**Comment by Stratos-Crimson** [comment]
I have done what you have told me and yes I did try to install filtron with that command but I am pretty sure that it isn't installed because if it was I would get more output and go isn't installed so something went wrong, I suppose?

**Comment by Stratos-Crimson** [comment]
But the weird part is that even when I have manually installed go following the step by step guide, It gives me errors.

**Comment by xnghu** [comment]
I have the exact same problem. 

I followed the basic install instructions via scripts on a VPS running Debian stable, first script installed with success, then I get this error when running the filtron script.

Running the suggested commands above, go is not installed and
`
GOPATH=/usr/local/filtron/go-apps `
is not listed in the output of 
`[filtron@example.org ~]$ env`

should I try manually installing it?

**Comment by Stratos-Crimson** [comment]
I did try to install it manually and the script still failed with the exact same error. Which VPS provider were you using if you don't mind sharing?

**Comment by return42** [comment]
Seems script has problem to get golang bin on your hosts .. 

Try the following commands: `./manage go.os` and `./manage go.arch`

the replace the output in this command:

```
go.ver_info "go1.17.2" archive "<go.os>" "$<go.arch>" filename sha256 size
```

**Comment by Stratos-Crimson** [comment]
I don't get what you mean, I have executed the ./manage go.os and ./manage go.arch commands but I don't understand what you mean by replace the output in this command

**Comment by dalf** [comment]
@return42, why @Stratos-Crimson couldn't skip the filtron install and enable the limiter plugin?

**Comment by Stratos-Crimson** [comment]
@dalf It also shows me the same error on morty.sh so....

**Comment by xnghu** [comment]
@return42 if i have understood correctly, i ran:
`
./manage go.ver_info "go1.17.2" archive "linux" "amd64" filename sha256 size`
which returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

**Comment by xnghu** [comment]
> I did try to install it manually and the script still failed with the exact same error. Which VPS provider were you using if you don't mind sharing?
https://1984.hosting/

**Comment by xnghu** [comment]
@return42 i had a few minutes so i dug into the script, it seems that in utils/lib_go.sh, in the function: `go.ver_info() ` even though it imports `requests` on line 74, line 75 is throwing the ModuleNotFoundError: No Module named requests 

Then this spills over in the function:` go.golang()`, on line 133, so that if statement on line 136 is true, causing the ERROR at the step "Install Go in filtron's HOME" in the filtron install script. 

I haven't really looked at things enough to know what's up with requests not being imported/ im rusty on my coding.. & I have other work to get to now, but thought I would at least share this

**Comment by Stratos-Crimson** [comment]
Oh okay

**Comment by Stratos-Crimson** [comment]
> @return42 if i have understood correctly, i ran: ` ./manage go.ver_info "go1.17.2" archive "linux" "amd64" filename sha256 size` which returns:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'requests'
> ```

I get this when I run it.
go1.17.2.linux-amd64.tar.gz
f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676
134803982

**Comment by return42** [comment]
> @return42 if i have understood correctly, i ran: ` ./manage go.ver_info "go1.17.2" archive "linux" "amd64" filename sha256 size` which returns:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'requests'
> ```

Seems your python misses a module named "requests" .. why?

> @return42, why @Stratos-Crimson couldn't skip the filtron install and enable the limiter plugin?

he could ..

**Comment by Stratos-Crimson** [comment]
> > @return42 if i have understood correctly, i ran: ` ./manage go.ver_info "go1.17.2" archive "linux" "amd64" filename sha256 size` which returns:
> > ```
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > ModuleNotFoundError: No module named 'requests'
> > ```
> 
> Seems your python misses a module named "requests" .. why?
> 
> > @return42, why @Stratos-Crimson couldn't skip the filtron install and enable the limiter plugin?
> 
> he could ..

I have the same error, can I get the module named "requests" somehow?

**Comment by return42** [comment]
I just wondering that it is not installed on your OS .. what distro do you use?  .. did you installed any micro distro?

**Comment by Stratos-Crimson** [comment]
> I just wondering that it is not installed on your OS .. what distro do you use? .. did you installed any micro distro?

Debian 11 but I am pretty sure that it is stripped of a lot of things because of the ram usage.

**Comment by Stratos-Crimson** [comment]
But I do have the package called python3-requests

**Comment by Stratos-Crimson** [comment]
Okay so I just did the same command and it's working....
Maybe I didn't have that package installed before and it was pulled as a dependency for something.
This is weird.

**Comment by return42** [comment]
> Debian 11 but I am pretty sure that it is stripped of a lot of things because of the ram usage.

The scripts are tested on common distros: bash, git and some basic python packages are needed to be installed.

@xnghu could you please install `python3-requests` by your package manager and test the script again / thanks!

**Comment by Stratos-Crimson** [comment]
> > Debian 11 but I am pretty sure that it is stripped of a lot of things because of the ram usage.
> 
> The scripts are tested on common distros: bash, git and some basic python packages are needed to be installed.
> 
> @xnghu could you please install `python3-requests` by your package manager and test the script again / thanks!

The scripts have ran without errors now but I still don't see searxng on example.org/searxng or example.org
Am I missing something?

**Comment by return42** [comment]
Are you looking for `example.org` or is it just a placeholder in your comment?  Did you installed a HTTP server?

**Comment by Stratos-Crimson** [comment]
It's a placeholder, hahaha.
Yes, I have nginx installed.
I don't understand why there is uwgsi tho.

**Comment by Stratos-Crimson** [comment]
I also have morty.conf and searxng.conf in /etc/nginx/default.apps-avaliable as well as an empty searxng file in /etc/nginx/sites-avaliable which is symbolically linked to /etc/nginx/sites-enabled

**Comment by return42** [comment]
> I don't understand why there is uwgsi tho.

SearXNG is installed as a uwsgi app https://docs.searxng.org/admin/architecture.html

> Yes, I have nginx installed.

I am sorry, I can't really help with HTTP setup .. since your installation procedure had have issues the only thing I would recommend is to [de-install all](https://github.com/searxng/searxng/issues/1110#issuecomment-1100915763) and retry a complete new installation (if you not have tried this already).

**Comment by Stratos-Crimson** [comment]
> > I don't understand why there is uwgsi tho.
> 
> SearXNG is installed as a uwsgi app https://docs.searxng.org/admin/architecture.html
> 
> > Yes, I have nginx installed.
> 
> I am sorry, I can't really help with HTTP setup .. since your installation procedure had have issues the only thing I would recommend is to [de-install all](https://github.com/searxng/searxng/issues/1110#issuecomment-1100915763) and retry a complete new installation (if you not have tried this already).

Oh okay, are you sure that we are supposed to have an empty nginx config tho? Because the searxng file is empty....
Thanks.

**Comment by return42** [comment]
I am going to close this issue since the initial issue  _"can't find info of golang version: go1.17.2"_ is solved .. if you have questions about HTTP setup or any other issue, come and join our [Matrix group](https://matrix.to/#/#searxng:matrix.org) or have a look at the [https://github.com/searxng/searxng/discussions](discussions).

**Comment by xnghu** [comment]
@return42 installing python3-requests fixed the error for me.
