### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by Remember2fart** [searxng/searxng#1104]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.11

**How did you install SearXNG?**
manually
**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Did you use a public instance or install SearXNG yourself?

Without filling out the rest of the form we can't really help you.

**Comment by tiekoetter** [comment]
Closing due to lack of replies
