### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by Remember2fart** [searxng/searxng#1105]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.11

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 100
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/gigablast.py:96`
  * Function: `response`
  * Code: `response_json = loads(resp.text)`

**Comment by tiekoetter** [comment]
Did you use a public instance or install SearXNG yourself?

Without filling out the rest of the form we can't really help you.

**Comment by tiekoetter** [comment]
Closing due to lack of replies
