### ISSUE TITLE
[question] if i self host what's the point ?

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1107]
Actually this is a real question.

If i self host it and i'm the only one using it.
What prevent the upstream search engine (like google) to use my ipv6 & 4 to link all my request to a shadow profile ?
(Since self hosted, my ip mean me).

If you have a good "protection" against that (if it's possible) who can easily deployed i take it.

Edit:note: do not propose me a VPN since i clearly do not trust them more than my isp.

Thanks

**Comment by ghost** [comment]
Additional info: i know that there is morty, but where do i point it, is this even exist "public" morty instance ?

**Comment by TheFrenchGhosty** [comment]
> What prevent the upstream search engine (like google) to use my ipv6 & 4 to link all my request to a shadow profile ?

Nothing.

**Comment by ghost** [comment]
> > What prevent the upstream search engine (like google) to use my ipv6 & 4 to link all my request to a shadow profile ?
> 
> Nothing.

So it's better to use a public instance than self host it for 1 person.
Thanks for the answer :)

**Comment by TheFrenchGhosty** [comment]
>So it's better to use a public instance than self host it for 1 person.

If you don't want the search results to be tied to a shadow profile yes, however, using a selfhosted SearX is still better than using the engines directly.

**Comment by ghost** [comment]
> > So it's better to use a public instance than self host it for 1 person.
> 
> If you don't want the search results to be tied to a shadow profile yes, however, using a selfhosted SearX is still better than using the engines directly.

Yes, just wanted to be sure, i used to use 60% duck and 40% searx, but now that duck start to do the thinking police (blocking torrent and so on) i will migrate faster to 100% searxng

**Comment by TheFrenchGhosty** [comment]
>but now that duck start to do the thinking police (blocking torrent and so on) i will migrate faster to 100% searxng

... yeah.

I was doing 90% search - 10% DDG, and I plan to replace DDG with Yandex (not really private - but then again DDG wasn't really private either - but actually a good search engine).

**Comment by ghost** [comment]
> again DDG wasn't really private either

For that i prefer to say that duck and other like him are "less worse" than google & co.

**Comment by ghost** [comment]
> > but now that duck start to do the thinking police (blocking torrent and so on) i will migrate faster to 100% searxng
> 
> ... yeah.
> 
> I was doing 90% search - 10% DDG, and I plan to replace DDG with Yandex (not really private - but then again DDG wasn't really private either - but actually a good search engine).

yeah yandex is a heaven when you search an un-drm-ed version of a file who the "copy private" technically allow us to use.

**Comment by TheFrenchGhosty** [comment]
I never used a "generic" search engine for that, there's better things to use.

I just want a *good* generic search engine that doesn't filter/biases its result, and as pointed out by #961 ... Yandex is the only one.

**Comment by ghost** [comment]
> I never used a "generic" search engine for that, there's better things to use.
> 
> I just want a _good_ generic search engine that doesn't filter/biases its result, and as pointed out by #961 ... Yandex is the only one.

yeah at least not filtered if you search for thing who do not involve politics, because in politics (i think) it's even worse than our.

**Comment by unixfox** [comment]
> Actually this is a real question.
> 
> If i self host it and i'm the only one using it.
> What prevent the upstream search engine (like google) to use my ipv6 & 4 to link all my request to a shadow profile ?
> (Since self hosted, my ip mean me).
> 
> If you have a good "protection" against that (if it's possible) who can easily deployed i take it.
> 
> Edit:note: do not propose me a VPN since i clearly do not trust them more than my isp.
> 
> Thanks

Your question is answered in the documentation: https://docs.searxng.org/own-instance.html
