### ISSUE TITLE
[question] qwant engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1108]
I am getting results of a different language with qwant, how can i fix that?
![image](https://user-images.githubusercontent.com/103880869/163715471-c178465c-ad0f-4ce3-8ec4-fa00e42a75e8.png)

i have tried public instances, but with them, i get english results.

**Comment by tiekoetter** [comment]
This happens when Qwant shadow bans you.

Had the same thing happen some time ago.
https://www.reddit.com/r/Searx/comments/s34zea/strange_results_from_qwant ([Libreddit](https://libreddit.tiekoetter.com/r/Searx/comments/s34zea/strange_results_from_qwant))

**Comment by ghost** [comment]
> This happens when Qwant shadow bans you.
> 
> Had the same thing happen some time ago. https://www.reddit.com/r/Searx/comments/s34zea/strange_results_from_qwant ([Libreddit](https://libreddit.tiekoetter.com/r/Searx/comments/s34zea/strange_results_from_qwant))

Is there any way i can fix this?
or the ban is permanent?

**Comment by tiekoetter** [comment]
I have multiple proxies behind my instance. I just rotated the banned one out for a few days. What also helps is accessing Qwant through the banned IP; I did this by setting it as a proxy in Firefox and browsing a bit.

**Comment by ghost** [comment]
thanks for the insight!

**Comment by tiekoetter** [comment]
Reopen if you still need help or have any further questions.
