### ISSUE TITLE
Uninstall everything the scripts have done

### ISSUE THREAD

**Issue by DokStook** [searxng/searxng#1110]
**How did you install SearXNG?**
I have used the scripts mentioned in the install page
**What happened?**
I have tried to setup an instance of searx and it have failed both on my machine and my remote  VPS and I want to remove everything those scripts have done. The reason is that it didn't work and I don't have the time to bother with it and fix it so I want to remove all the changes (config files and others that were not installed packages from package manager). 

**How To Reproduce**
Run the scripts from [here](https://docs.searxng.org/admin/installation.html)

**Expected behavior**
Working searx instance

---

I don't want to bother you with log files. I just want to "undo" the scripts.

Thanks in advance!

**Comment by tiekoetter** [comment]
```
sudo -H ./utils/searx.sh remove all
sudo -H ./utils/filtron.sh remove all
sudo -H ./utils/morty.sh remove all
```

Will remove everything

**Comment by DokStook** [comment]
I get the message
** Don't forgett to remove your public site! (http://**my user name**) **
How to do it?

**Comment by tiekoetter** [comment]
This message is a reminder to remove the instance from the webserver config.

**Comment by DokStook** [comment]
How do I do that? 
Sorry, I am learning...

**Comment by tiekoetter** [comment]
What webserver software are you using?

**Comment by DokStook** [comment]
Nginx

**Comment by tiekoetter** [comment]
Remove
``/etc/nginx/sites-enabled/searxng``

**Comment by DokStook** [comment]
I don't have such location...

**Comment by tiekoetter** [comment]
Please paste the output of ``ls -l /etc/nginx/sites-enabled/``

**Comment by DokStook** [comment]
`lrwxrwxrwx 1 root root 34 Mar 29 17:55 default -> /etc/nginx/sites-available/default

lrwxrwxrwx 1 root root 31 Mar 29 18:27 mail -> /etc/nginx/sites-available/mail

lrwxrwxrwx 1 root root 38 Mar 29 18:27 maxservices -> /etc/nginx/sites-available/_my site_

lrwxrwxrwx 1 root root 36 Mar 30 08:41 nextcloud -> /etc/nginx/sites-available/nextcloud
`

**Comment by tiekoetter** [comment]
You either already removed SearXNG from your nginx config or have it in one of these files.

**Comment by DokStook** [comment]
So I want to remove searx because when I try to reload nginx I get error
`● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-03-30 08:58:48 UTC; 2 weeks 4 days ago
       Docs: man:nginx(8)
    Process: 173908 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=1/FAILURE)
   Main PID: 720 (nginx)
      Tasks: 3 (limit: 1150)
     Memory: 11.7M
        CPU: 20.283s
     CGroup: /system.slice/nginx.service
             ├─ 720 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─5292 nginx: worker process
             └─5293 nginx: worker process

Apr 17 17:37:13 mail systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 17 17:37:13 mail systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
Apr 17 18:18:45 mail systemd[1]: Reloading A high performance web server and a reverse proxy server.
Apr 17 18:18:45 mail systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 17 18:18:46 mail nginx[172812]: nginx: [emerg] open() "/etc/nginx/default.d/searxng.conf" failed (2: No such file or directory) >
Apr 17 18:18:45 mail systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
Apr 17 18:52:39 mail systemd[1]: Reloading A high performance web server and a reverse proxy server.
Apr 17 18:52:39 mail nginx[173908]: nginx: [emerg] open() "/etc/nginx/default.d/searxng.conf" failed (2: No such file or directory) >
Apr 17 18:52:39 mail systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 17 18:52:39 mail systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
`
and searx is the reason for that error

**Comment by tiekoetter** [comment]
What is the content of ``/etc/nginx/nginx.conf``

This is not a default SearXNG installation so I can't guarantee you a solution.

**Comment by DokStook** [comment]
Hmm this is strange. I don't remember changing anything

**Comment by tiekoetter** [comment]
``nginx: [emerg] open() "/etc/nginx/default.d/searxng.conf" failed (2: No such file or directory)`` means there is a ``include /etc/nginx/default.d/searxng.conf;`` somewhere in your nginx config. This again is not the default behavior of SearXNG.

**Comment by tiekoetter** [comment]
You can try running ``nginx -t`` to see if you can find where it is.

**Comment by catfluoride** [comment]
Look at the "include" directives in nginx.conf. That would call external .conf files.
Probably one of these directives points to an non-existing searxng.conf file.

**Comment by return42** [comment]
> open() "/etc/nginx/default.d/searxng.conf" failed (2: No such file or directory)

@catfluoride is right, there seems to be a leftover in your nginx conf .. delete the directive and the issue is solved.

**Comment by DokStook** [comment]
> `nginx: [emerg] open() "/etc/nginx/default.d/searxng.conf" failed (2: No such file or directory)` means there is a `include /etc/nginx/default.d/searxng.conf;` somewhere in your nginx config. This again is not the default behavior of SearXNG.

This was the fix. Thanks to everyone who helped!
