### ISSUE TITLE
[Cloudflare] Category buttons not working with Simple theme

### ISSUE THREAD

**Issue by Deon-Trevor** [searxng/searxng#1113]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
```Version:  2022.04.17-e22dc2ba-dirty```  Forked from master. Here's my fork: https://github.com/Sync-Pundit/SearXNG

**How did you install SearXNG?**
Installation scripts

**What happened?**
When using Simple theme the buttons to view other results categories do not work. When clicked they only highlight but are not responsive.

If using using oscar theme the UI works without any issues. When I switch to the Simple theme the category buttons no longer respond. When I add ```&categories=images``` on the query string I get results from the images categories but the categories buttons on the UI stay unresponsive. 
**How To Reproduce**

Click on any result category on the Simple theme
**Expected behavior**
 
When the buttons are clicked they are supposed to take me to the desired result category 

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/39409222/163806477-2e0d2146-f45a-4f6a-84c3-016a0ae8bd33.png)
![image](https://user-images.githubusercontent.com/39409222/163806582-52821251-18ee-4365-813b-9480b51432df.png)
![image](https://user-images.githubusercontent.com/39409222/163806651-99950a3c-a780-472e-8fbf-50af8dc0c45e.png)
![image](https://user-images.githubusercontent.com/39409222/163806707-bcb5ceb5-d940-4a39-a683-b278148ba1d6.png)

**Additional context**

**Comment by return42** [comment]
Did you checked preference "search on category select"?

![image](https://user-images.githubusercontent.com/554536/163807339-3aaae952-bdf8-4824-a150-f14226b1ee5d.png)

**Comment by Deon-Trevor** [comment]
Yes I did

![image](https://user-images.githubusercontent.com/39409222/163807573-8b1f2772-950b-4804-86ff-72f03b7d5cb4.png)

**Comment by tiekoetter** [comment]
I think the Cloudflare rocket-loader.js broke your instance.

**Comment by Deon-Trevor** [comment]
> I think the Cloudflare rocket-loader.js broke your instance.

I'm not familiar, would you mind showing me a few docs i can read to get caught up on it and how i can resolve this

**Comment by tiekoetter** [comment]
You need to disable this in your Cloudflare dashboard. We do not recommend using Cloudflare in front of SearXNG instances.

**Comment by Deon-Trevor** [comment]
> You need to disable this in your Cloudflare dashboard. We do not recommend using Cloudflare in front of SearXNG instances.

I'll disable it, on the Cloudflare issue. I generally don't like having any self-hosted solution bare without some sort of proxy. Is Cloudflare specifically the problem or these types of proxies altogether? I guess my question is whether you have an alternative you can recommend?

**Comment by tiekoetter** [comment]
Cloudflare can read everything (because they MITM your https connection). It is your preference if you think you need a reverse proxy or not.

**Comment by Deon-Trevor** [comment]
Disabling rocket-loader.js worked! Thanks mate.
