### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by liuruifeng560** [searxng/searxng#1129]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.20-7f2185ce

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by return42** [comment]
Thank you for opening an issue. Your bug template is empty tho and there is not even any error in it, so I will close it. Feel free to add a comment with further info :+1: ; Closing.
