### ISSUE TITLE
[question] Morty: 'Error: invalid "mortyhash" parameter' when entering proxified websites

### ISSUE THREAD

**Issue by rywng** [searxng/searxng#1130]
Hello,
### background
I have switched from searx to searxNG according to the steps described in [this tutorial](https://docs.searxng.org/admin/installation-switch2ng.html)

### the error
But after I installed morty and configured the nginx server, when I try to access an proxified website, it shows a error page like this:
![2204212147](https://user-images.githubusercontent.com/72336775/164471974-165a0e8e-7368-4f55-8ea0-d1f8ee93bcf8.png)

### how I tried to fix and failed
I have checked my config files in ```/etc/searxng/settings.yml``` and ```/usr/local/searx/searx-src/searx/setings.yml```, and rebuilt the env using ```make buildenv``` following ```systemctl restart uwsgi``` and ```systemctl restart morty```.
And I tried generating the key files using ```utils/morty.sh``` and ```openssl rand -base64 33```.
Also I tried reinstalling, both manually and by using script, all with no luck.
It seems to work only when the key validation of morty is set to off
I also tried workaround from [this](https://github.com/searx/searx/discussions/2964#discussioncomment-1607700), with no success
And from this issue #834, the author closed the issue without leaving any useful information, I wonder if he has fixed the mortyhash issue

### my question
So, can anyone confirm, whether this is caused by a bug or is my misconfiguration? And if it is caused by me, can anyone help with my problem?

**Comment by return42** [comment]
I assume the morty key is not set to the same value in morty and settings.yml you can repair it by:

    sudo -H ./utils/morty.sh option new-key

TBH we do no longer recommend to use morty .. you can uninstall morty .. we have a buildin image proxy you can enable in the settings.  In the `server:` section set `image_proxy: true` / see https://docs.searxng.org/admin/engines/settings.html#server

**Comment by rywng** [comment]
Thank you sir.
