### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by monster-liu** [searxng/searxng#1146]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.24-d502e7d4

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by vojkovic** [comment]
Have you tried` use_mobile_ui `?

```
- name: google
  use_mobile_ui: true
```

**Comment by tiekoetter** [comment]
@monster-liu Did you install SearXNG yourself or did you use a public instance?

Please fill out the rest of the form.

**Comment by return42** [comment]
Closing due to lack of replies
