### ISSUE TITLE
RARBG

### ISSUE THREAD

**Issue by julianfairfax** [searxng/searxng#1152]
**Working URL to the engine**
https://rarbgmirror.org/torrents.php

**Why do you want to add this engine?**
I feel its advertising is less invasive than other torrent search engines, and since it has its own release group, torrents may appear on it faster.

**Features of this engine**
Less invasive advertising with faster releases.

**How can SearXNG fetch the information from this engine?**
The url for searches is `https://rarbgmirror.org/torrents.php?search=` with your query after the equal sign, if that helps.

**Applicable category of this engine**
Files.

**Additional context**
We only have two torrent search engines right now, since BTDigg has never worked for me. There are also metasearch engines, but the point of searching a metasearch engine through a metasearch engine is kind of lost on me, unless maybe they offer better privacy like DuckDuckGo and Startpage. If anyone's interested in those, check out snowfl.com and knaben.eu. You can probably better decide if those should or shouldn't be added than me.

**Comment by unixfox** [comment]
I'm interested into this engine. I might implement it.

**Comment by julianfairfax** [comment]
It should also have a button with a direct magnet link, if possible. The Pirate Bay and Nyaa both have that and it's nice. 1337x doesn't.

**Comment by caywin25** [comment]
Yes if possible with the magnet link, it would be perfect
Thank you very much

**Comment by unixfox** [comment]
Rarbg is pretty much wall guarded by an antibot defense that can't be bypassed with SearXNG. Even on a clean IP address after a couple of requests I'm redirected to `threat_defence.php` antibot page.

@return42 you can safely close this issue as it's not feasible to implement rarbg into SearXNG.
