### ISSUE TITLE
Make "leave file unchanged" the default when updating SearXNG through updates script

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#1160]
When updating SearXNG through `searxh.sh` script, the following dialog is shown:

```
INFO:  install (eval=0): /etc/searxng/settings.yml
INFO:  different file /etc/searxng/settings.yml already exists on this host
Menu::
  1.) replace file [default]
  2.) leave file unchanged
  3.) interactive shell
  4.) diff files
```
I think that having option 2 (i.e., leave `setting.yml` unchanged) as the default would be better, with maybe a timeout to continue the update without user intervention. This would allow for unattended or scheduled updates and for the update to be integrated in scripts.

As an alternative, an optional flag (let's call it `-l`  could be added to the script (i.e., `searxh.sh update -l searx`) to allow option 2 to be chosen without asking the user any further).

Thanks!
 
EDIT: Actually, a better course of action would be the addition of 4 flags (`-r, -l, -i, -d` for replace, leave, interctive shell, diff respectively).

**Comment by return42** [comment]
Thanks for your suggestion .. FYI in my [searxng-install](https://github.com/return42/searxng/tree/searxng-install) branch I am working on a new installation script, my intention is to drop filtron.sh and morty.sh which are no longer needed .. however in this branch I set the `DEFAULT_SELECT=2` to *leave file unchanged* by default:

https://github.com/return42/searxng/blob/e5be2149a3bd432d3c915b29fa1f912dbd1486f9/utils/searxng.sh#L349-L353

**Comment by return42** [comment]
In the new [`utils/searxng.sh`](https://docs.searxng.org/utils/searxng.sh.html) script is *"leave file unchanged"* the default.
