### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Sairenity** [searxng/searxng#1164]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.01-8a79eb4d

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 25
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by vojkovic** [comment]
Please fill out the entirety of the form.

**Comment by Sairenity** [comment]
this was made by accident and I cannot figure out how to delete it... my bad.
