### ISSUE TITLE
Suggestion for a Setting to center Searchresults like example

### ISSUE THREAD

**Issue by solisinvictum** [searxng/searxng#1175]
Hey Folks,

you can't believe how much i jumped for joy when i discovered searxng.

i have known searx for a very long time, but have always avoided using it because (no offense intended) it is/was just incredibly ugly and just not clear to read.

Periodically I have watched the development of searx to see if one thing or another has been improved. And now searxng is here. Great!

I have only one suggestion:

A setting to center the search results, like duckduckgo.com. 

The reason is because I own a 4k 43" monitor, and then the search results are on the far left, which not only looks "weird" but is also "hard to read". 

See screenshot:

<img width="1919" alt="2022-05-05_08-30" src="https://user-images.githubusercontent.com/94938946/166872789-2fd298fe-3953-4fe5-98a9-426d5fc32c24.png">
<img width="1920" alt="2022-05-05_08-30_1" src="https://user-images.githubusercontent.com/94938946/166872792-0664ac2a-4748-4b65-a559-925dfef02869.png">

Translated with www.DeepL.com/Translator (free version)

**Comment by return42** [comment]
I close this in favor of

- https://github.com/searxng/searxng/issues/1169

**Comment by solisinvictum** [comment]
Today, i revisited searxng to look if something changed.

And wow! Now i can use searxng with pure joy!

Big thanks to the devs, and especially to the person, who implemented the center view!

<3
