### ISSUE TITLE
oscar theme back?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [searxng/searxng#1180]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
re-add oscar theme

**Describe alternatives you've considered**
using simple theme

**Additional context**
I switched from searx to searxng because it's more advanced but while I used searx I got attached to their UI (oscar) and now just removing it, searxng feels weird to me so any chances to get oscar back?

**Comment by mrpaulblack** [comment]
Hi @EsmailELBoBDev2 ,
We are not going to add back oscar sry... But there is an ongoing effort for an oscar nostagia style for simple here: https://github.com/searxng/searxng/issues/1169 (But thats a future effort)

**Comment by EsmailELBoBDev2** [comment]
@mrpaulblack oscar nostagia seems nice..good luck and thanks for reply

**Comment by dalf** [comment]
@EsmailELBoBDev2 can you describe why do you prefer the oscar theme, or at least the most important point?

**Comment by EsmailELBoBDev2** [comment]
@dalf sure Obama pic face! (joking no offense)

oscar feels old school yes but I feel it's more clean. I'm not used to see search results in center of screen, I'm used to see it from left to right (or even right to left, Arabic speaker here) and I feel like there are a lot of noise in search page (home page looks perfect) in search results itself (like wiki info in simple are on same place like search results but in oscan it's on right side so it's easy to see search results) and there are more helpful info in oscar search theme that are not shown in simple theme like search URL for example

I know it's confusing I can't really explain it but I hope you get my idea 
___
@mrpaulblack I'm just curious if you plan to add replacement for oscar why did not you wait to add it first? or why did you remove oscan in first place? I loved it :(

**Comment by dalf** [comment]
The simple theme switches to the tablet mode according to [the screen resolution](https://github.com/searxng/searxng/blob/31521f3a465fa2beb7e3fd7ed47621262a28f554/searx/static/themes/simple/src/less/definitions.less#L249-L254). In the tablet mode, the result are centered and the infoboxes are on the top of the result instead of the right side.

If you zoom out the page, the simple theme will switch back to what you expect.

> I'm just curious if you plan to add replacement for oscar why did not you wait to add it first? or why did you remove oscan in first place? I loved it :(

The team is not big enough to maintain more than one theme.

See https://github.com/searxng/searxng/discussions/1167

**Comment by mrpaulblack** [comment]
@EsmailELBoBDev2 please watch your language and edit your comment to remove the offensive joke, thanks :D (I know you dont mean it, but it is still offensive and not the right place in an OSS project IMO)

About your oscar remarks:
* Search URL is only displayed when your search method is set to POST (when set to GET you can just copy the URL from the Browser).
* simple has RTL support, just set the interface language to an RTL one in preferences...

> I'm just curious if you plan to add replacement for oscar why did not you wait to add it first? or why did you remove oscan in first place? I loved it :(

You can read our post about removing oscar here: https://github.com/searxng/searxng/discussions/1167 . The nostalgia oscar theme idea evolved after removing oscar as an idea...

**Comment by EsmailELBoBDev2** [comment]
> If you zoom out the page, the simple theme will switch back to what you expect.

Oh...I have been using it for months and never knew that, thanks for the tip!

> The team is not big enough to maintain more than one theme.
See https://github.com/searxng/searxng/discussions/1167

Yes but if I'm right, oscar theme made by searx itself (or at least used in there). searxng is fork of searx so like searx maintain oscar and searxng maintain simple? 
___
> please watch your language and edit your comment to remove the offensive joke, thanks :D

Yes, I did not curse anyone and seems the guy himself did not talk about. it was pure joke because first time I got into searx his picture gave me the vibe of obama. I do not mean to offend anyone (yet, I'm sorry @dalf if you felt bad about it, I can remove it if you want) it just gave me that vibe and yeah I wanted to share my thoughts and you can joke about my profile picture all day

> Search URL is only displayed when your search method is set to POST (when set to GET you can just copy the URL from the Browser).

> simple has RTL support, just set the interface language to an RTL one in preferences...

No I know this yes, but I was giving an example that search results are on left to right not in center. Did not know that I was in tablet mode all along
___
And to get back on the topic now seems I like simple a little more but the icons seems little messy -- no proper spacing or borders around them to make them stand out (I'm picky now xd)
![image](https://user-images.githubusercontent.com/28893833/167111319-de4391e8-3e44-45be-9667-1681efd09985.png)

**Comment by craftyguy** [comment]
not to mention the alignment is really terrible with the 'default' theme:

![2022-05-06-124033_grim](https://user-images.githubusercontent.com/1474209/167206351-c5e133a3-1312-4cc3-8fa1-596ac8a8feae.png)

**Comment by dalf** [comment]
@craftyguy can you put some arrows / circles / lines / boxes to show where the alignment is terrible? or just describe more precisely what do you mean?

**Comment by craftyguy** [comment]
@dalf with oscar, the results were centered and wider on a large display. with "simple" they are pushed to the left of the screen and with a much narrower width
