### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by peeter-dot-com** [searxng/searxng#1187]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.03-31521f3a

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 50
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 50
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Hi @peeter-dot-com,
Did you install SearXNG yourself or did you use a public instance?
Please fill out the rest of the form.

**Comment by tiekoetter** [comment]
Closing due to lack of replies.
