### ISSUE TITLE
Create a bug issue template

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#1189]
Currently, the `Submit a new issue on Github including the above information` button fills an issue on GitHub, and often the users just submit the form without answering the question.

The discussed idea is to add some additional steps on the SearXNG instance to check if the similar issue already exists.

An additional idea is to create an issue template, so the users will have to answer the question ( for reference : https://github.com/searxng/searx-instances/blob/master/.github/ISSUE_TEMPLATE/add-instance.yaml )

**Comment by return42** [comment]
This issue has been fixed in eb489c45ea7

- https://github.com/searxng/searxng/pull/1478
