### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by mariushosting** [searxng/searxng#1199]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.11-459b9c18

Everytime I try to do a search I receive the following error message

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Hi @mariushosting,

Are you using a public instance or do you self-host?

If you self-host have you tried setting `use_mobile_ui: true` in `settings.yml` under the google engine?

**Comment by mariushosting** [comment]
> Hi @mariushosting,
> 
> Are you using a public instance or do you self-host?
> 
> If you self-host have you tried setting `use_mobile_ui: true` in `settings.yml` under the google engine?

I self host with docker on a Synology NAS. Same error. I don't have this error when I use the SearX image. Only with SearXNG image.

**Comment by tiekoetter** [comment]
@mariushosting Have your tried setting `use_mobile_ui: true`?

**Comment by mariushosting** [comment]
> @mariushosting Have your tried setting `use_mobile_ui: true`?

Yes. Same error after cache deleted.

**Comment by tiekoetter** [comment]
If you change something like `instance_name` in settings.yml does this reflect on your instance?

Is your instance accessible from the outside?

**Comment by mariushosting** [comment]
Yes instance is accessible with reverse proxy without any problem. The search is correctly displayed but this error message appears on the right side.

**Comment by tiekoetter** [comment]
No I mean could I access it (via the internet)?

If you change something different in settings.yml does this reflect on your instance?

**Comment by return42** [comment]
@mariushosting I close this issue in lack of response / if your problem resits, please answer the questions from https://github.com/searxng/searxng/issues/1199#issuecomment-1126895637 and we can reopen the issue.
