### ISSUE TITLE
Add Sepia Search (PeerTube search engine)

### ISSUE THREAD

**Issue by Talkless** [searxng/searxng#1203]
**Working URL to the engine**
https://search.joinpeertube.org/

**Why do you want to add this engine?**
To find videos videos on PeerTube instances - on a federated, FOSS-based ActivityPub-compatible video hosting platforms.

**Features of this engine**
Useful to navigate through PeerTube federation. There's no single "tube".

**How can SearXNG fetch the information from this engine?**
IDK.

**Applicable category of this engine**
videos

**Additional context**
N/A

**Comment by dalf** [comment]
There is already a sepiaengine which search on https://sepiasearch.org
See https://github.com/searxng/searxng/blob/master/searx/engines/sepiasearch.py

**Comment by Talkless** [comment]
Ohhh.. sorry, I had to switch to "video" tab to find that engine. Sorry for the noise!
