### ISSUE TITLE
No searx module

### ISSUE THREAD

**Issue by baxterdmutt** [searxng/searxng#1205]
After a fresh install I keep getting an error at line 54 of webapp.py. "No searx module" on import. I did run the requirements.txt package installation and didn't notice any orders.  I switched to SEARX and the issue did not occur there. I did have searx installed before but I had deactivated the virtual environments, and deleted everything in the searxng directory. Any ideas?

**Comment by dalf** [comment]
I discover this issue. Most probably the answer is to use `python -m searx.webapp` instead of `python searx/webapp.py`.
