### ISSUE TITLE
[question] Redirect to HTTP website

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1210]
I am currently self-hosting SearxNG, Libreddit, and Invidious on my local server. I want Searx to redirect the respective links to my local instances using **http** links rather than **https** (my instances are on my LAN so I don't intend to setup https).

I messed around with the Regex settings for the `hostname_replace` plugin and found that there was no way to replace the "https://" part of the URL with "http://"

For example, 
I can change "https://www.youtube.com/watch?" to "https://10.0.0.1:3000/watch?" but not ""http://10.0.0.1:3000/watch?".

This is what my hostname_replace section in the `settings.yml` file looks like right now.
```
# Configuration of the "Hostname replace" plugin:
#
hostname_replace:
   '(.*\.)?youtube\.com$': '10.0.0.1:3000'
   '(.*\.)?youtu\.be$': '10.0.0.1:3000'
#  '(.*\.)?youtube-noocookie\.com$': 'yotter.example.com'
   '(.*\.)?reddit\.com$': '10.0.0.1:8181'
   '(.*\.)?redd\.it$': '10.0.0.1:8181'
```

Any help would be appreciated. I have been trying different Regex filters for a while now, haven't been able to shake the https.

**Comment by tiekoetter** [comment]
`https` is the protocol and therefore not part of the hostname. If the site, you intend replacing the hostname of, uses https then it will be carried over.

Why don't you setup a local CA?

**Comment by ghost** [comment]
Thanks, I made it work with a local CA
