### ISSUE TITLE
Bug: gentoo engine

### ISSUE THREAD

**Issue by jayferret** [searxng/searxng#1212]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.15-f814ac70

**How did you install SearXNG?**
In unraid 
**What happened?**

just searching for web hosting

**How To Reproduce**
On the General tab under Default Categories click General, Videos, IT

**Comment by tiekoetter** [comment]
Hi @jayferret,
I don't understand what error you have reported.
Could you please explain what happened with the gentoo engine?

**Comment by jayferret** [comment]
How did you install SearXNG?
In unraid
What happened?

just searching for web hosting

How To Reproduce
On the General tab under Default Categories click General, Videos, IT

But now got no error message at all, so must have fixed it self

**Comment by tiekoetter** [comment]
Please close the issue if you don't get the error anymore.

**Comment by return42** [comment]
I close this issue in lack of response and needed information.
