### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by plamkas** [searxng/searxng#1218]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.20-61535a4c

**How did you install SearXNG?**
Installed via Docker on a Raspberry Pi 4.

**What happened?**
Received a mojeek parsing error: "Error! Engines cannot retrieve results: mojeek ( parsing error). It happened the first time two days ago. Before that it was working fine. At that time I had version 2022.05.15. After upgrade to 2022.05.20 error remained. No other changes were made.

**How To Reproduce**
Don't know.

**Expected behavior**
No error.

**Screenshots & Logs**
[Image](https://postimg.cc/SJC5hG6x)

**Additional context**
None.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('./h2/a/@href', 'len(xpath_str) < 1')`
  * File name: `searx/engines/xpath.py:192`
  * Function: `response`
  * Code: `url = extract_url(eval_xpath_list(result, url_xpath, min_len=1), search_url)`

**Comment by goshawk22** [comment]
I am also having this issue, error is the same.

**Comment by danielyrovas** [comment]
Same error here

**Comment by danielyrovas** [comment]
I tried the fix in  #1250 and it seems working for me.
