### ISSUE TITLE
Wikimedia Commons

### ISSUE THREAD

**Issue by julianfairfax** [searxng/searxng#1221]
**Working URL to the engine**
https://commons.wikimedia.org

**Why do you want to add this engine?**
Out of all of the Wikimedia projects, Wikimedia Commons is one of only two to not appear in any engine category in SearXNG, with the other being Wikispecies.

**Features of this engine**
It has a collection of [82,886,704](https://commons.wikimedia.org/wiki/Special:Statistics) [freely usable](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia) media files.

**How can SearXNG fetch the information from this engine?**
`https://commons.wikimedia.org/w/index.php?search=%s` with `%s` being what you want to search.

**Applicable category of this engine**
General, files, images, music, videos.

**Comment by dalf** [comment]
There are various categories: Images, Audio, Video, Other media, Categories and pages.

So I guess we need an engine per category (and most probably one Python module).

---

* commons.wikimedia.org has a SPARQL endpoint but it requires a login
* the result page `https://commons.wikimedia.org/w/index.php?search=time&title=Special:MediaSearch&go=Go&type=image` make a XHR request to display the second page `https://commons.wikimedia.org/w/api.php?action=query&format=json&uselang=en&generator=search&gsrsearch=filetype:bitmap|drawing -fileres:0 time&gsrlimit=40&gsroffset=40&gsrinfo=totalhits|suggestion&gsrprop=size|wordcount|timestamp|snippet&prop=info|imageinfo|entityterms&inprop=url&gsrnamespace=6&iiprop=url|size|mime&iiurlheight=180&wbetterms=label`.
