### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by rasos** [searxng/searxng#1225]
When following the instructions on https://docs.searxng.org/admin/installation-docker.html#installation-docker I get the following docker build error:

```
DOCKER    Building image searxng/searxng:
invalid argument "searxng/searxng:%cs.61535a4c" for "-t, --tag" flag: invalid reference format
```

**Comment by mrpaulblack** [comment]
Hi @rasos ,
When using `make docker.build` the following generates the tag: https://github.com/searxng/searxng/blob/61535a4c206aa247a6fa87697b70668048086e27/manage#L500 . This is just a guess, but are you on windows? Looks like your version string did not get parsed into a date...

**Comment by rasos** [comment]
I was trying to build on Debian buster. Yes, it seems the version string is not parsed into a date.

The build works when replacing that line with 

                      -t "${SEARXNG_IMAGE_NAME}:latest" -t "${SEARXNG_IMAGE_NAME}:20220524" .

**Comment by dalf** [comment]
Can you post the content (*) of `./manage pyenv.cmd python -m searx.version` ?

By content I mean the lines similar to
```
VERSION_STRING="1.0.0-1475-977e9a43"
VERSION_TAG="1.0.0"
GIT_URL="https://github.com/searxng/searxng"
GIT_BRANCH="master"
```

**Comment by rasos** [comment]
I did a fresh git clone yesterday:

```
./manage pyenv.cmd python -m searx.version

VERSION_STRING="%cs.61535a4c"
VERSION_TAG="%cs.61535a4c"
GIT_URL="https://github.com/searxng/searxng"
GIT_BRANCH="master"
```

**Comment by dalf** [comment]
So I guess `git show -s --format='%cs-%h'` returns `%cs.61535a4c`.
What about:
* `git show -s --format='%cd-%h'`
* `git log -1`
?

According to the [git show documentation](https://git-scm.com/docs/git-show), `%cs` should works.

**Comment by return42** [comment]
Closed by https://github.com/searxng/searxng/pull/1282
