### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1226]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.04

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 85
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpcore.PoolTimeout
  * Percentage: 5
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpcore.ReadTimeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ProxyError
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by dalf** [comment]
@jason88fr Please answer the questions: How did you install SearXNG or Which SearXNG instance do you use ? What happened? How To Reproduce, and all other questions, add any other information that might help us to fix the issue.

This comment is also valid for all the other issues you have opened from the SearXNG instance(s).

**Comment by dalf** [comment]
TimeoutException shows there is a slow response time, and timeout should be increase on your instance.
See https://docs.searxng.org/admin/engines/settings.html?highlight=timeout#outgoing , the `request_timeout` field.

Without feedback, I close the issue.
