### ISSUE TITLE
Bug: ddg definitions engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1227]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.04

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 0
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/duckduckgo_definitions.py:73`
  * Function: `response`
  * Code: `search_res = json.loads(resp.text)`

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/issues/1226#issuecomment-1134924263
