### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1229]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.04

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 35
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 35
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/startpage.py:87`
  * Function: `get_sc_code`
  * Code: `resp = get(base_url, headers=headers)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 25
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('413', 'Request Entity Too Large', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ProxyError
  * Percentage: 0
  * Parameters: `(None, None, 'startpage.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: httpcore.PoolTimeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/engines/startpage.py:87`
  * Function: `get_sc_code`
  * Code: `resp = get(base_url, headers=headers)`

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/issues/1226#issuecomment-1134924263
