### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1231]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.04

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 65
  * Parameters: `('./h2/a/@href', 'len(xpath_str) < 1')`
  * File name: `searx/engines/xpath.py:192`
  * Function: `response`
  * Code: `url = extract_url(eval_xpath_list(result, url_xpath, min_len=1), search_url)`

Error
  * Error: httpx.ProxyError
  * Percentage: 20
  * Parameters: `(None, None, 'www.mojeek.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/issues/1226#issuecomment-1134924263
