### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1232]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.04

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 100
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/gigablast.py:96`
  * Function: `response`
  * Code: `response_json = loads(resp.text)`

Error
  * Error: httpx.ConnectError
  * Percentage: 0
  * Parameters: `(None, None, 'gigablast.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: ssl.SSLError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/issues/1226#issuecomment-1134924263
