### ISSUE TITLE
[limiter] Rate limiting does not work

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#1237]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```
Leons instance: 2022.05.24-fddbc5ed (39077fc0)
ALso my instance: 2022.05.08-85c1c14f 
``` 

**How did you install SearXNG?**

Using the scripts as well as with docker.

**What happened?**

The limiter plugin does not rate limit requests and uses the `X-Forwarded-For` header which could be easily set by a client request.

**How To Reproduce**
Make 15 `/search` requests in 20sec to trigger rate limiting.
Make another `search` request, which is going to get blocked with a HTTP 429 response.
Make another `/search` request which is going to get not blocked again.

**Expected behavior**
The IP should get blocked for a specific amount of time with a timeout value for example. So a offending host could get blocked for like 2 hours for example.

**Screenshots & Logs**

**Additional context**
Another problem is that the IP is read from a header. In a improper setup the IP could maybe not be in that header or a client could abuse this and set the header themselves. The IP should be gotten from a trusted source... (Maube the request lib has something to get the IP?)

**Comment by mrpaulblack** [comment]
for vis: @dalf @return42 @tiekoetter

**Comment by tiekoetter** [comment]
Tested on my instance :

IPv4:
- Refresh about 15 times -> 429
- Wait about 10 seconds -> 200
- Refresh about once a second after getting blocked initially -> 429

IPv6:
- Refresh about 15 times -> 429
- Wait about 10 seconds -> 200
- Refresh about once a second after getting blocked initially -> 429

**Comment by dalf** [comment]
> Another problem is that the IP is read from a header.

* Caddy: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults
* Traefik: https://doc.traefik.io/traefik/v2.1/routing/entrypoints/#forwarded-header

**Comment by return42** [comment]
> **How To Reproduce**
> Make 15 `/search` requests in 20sec to trigger rate limiting.
> Make another `search` request, which is going to get blocked with a HTTP 429 response.
> Make another `/search` request which is going to get not blocked again.

"is going to get not blocked again." .. I can't reproduce this behaviour .. in my tests, the *sliding window* works and blocks the following request  .. @paul, can you please verify your test.

**Comment by mrpaulblack** [comment]
well yeah can you try with my instance? https://paulgo.io it happens there for me like this... (Tho I did not update my instance for over 2 weeks => so searxng container and redis is running for over 2 weeks now)

**Comment by return42** [comment]
About nginx -- from https://nginx.org/en/docs/http/ngx_http_proxy_module.html#variables

```
 $proxy_add_x_forwarded_for
    the “X-Forwarded-For” client request header field with the $remote_addr variable
    appended to it, separated by a comma. If the “X-Forwarded-For” field is not present
    in the client request header, the $proxy_add_x_forwarded_for variable is equal to
    the $remote_addr variable.
```

Does it mean the client can overwrite “X-Forwarded-For” ?

**Comment by return42** [comment]
> well yeah can you try with my instance? https://paulgo.io/ it happens there for me like this...

I tested your instance and for me it works like @tiekoetter described ["Refresh about once a second after getting blocked initially -> 429"](https://github.com/searxng/searxng/issues/1237#issuecomment-1138329079) .. what I mean; the *sliding window* works and blocks the following requests .. the limiter itself is IMO not buggy.

---

The issue might be that the limiter identifies the request origin by the entire string of:

https://github.com/searxng/searxng/blob/de0c4d7cd8bf598d8ec69834f806a3dc80326ad6/searx/plugins/limiter.py#L42

If the client set a “X-Forwarded-For” and change the value with each request, the entire string changes by each request.

**Comment by return42** [comment]
The leak is described here :-) .. 

[Any security-related use of `X-Forwarded-For` -- such as for rate limiting or IP-based access control -- must only use IP addresses added by a trusted proxy. Using untrustworthy values can result in rate-limiter avoidance, access-control bypass, memory exhaustion, or other negative security or availability consequences.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)

**Comment by ononoki1** [comment]
> If the client set a “X-Forwarded-For” and change the value with each request, the entire string changes by each request.

I think it should be handled by web server like nginx, not backend application like searxng. For example, using `set_real_ip_from` directive properly or simply using `$remote_addr` as `X-Forwarded-For` header are both solutions.

---

It should be the web server's (or reverse proxy's) responsibility that the `X-Forwarded-For` header passed to backend application is reliable. SearXNG cannot and should not verify it.

**Comment by return42** [comment]
> It should be the web server's (or reverse proxy's) responsibility that the `X-Forwarded-For` header passed to backend application is reliable. SearXNG cannot and should not verify it.

That is absolutely true .. but what when the proxy in front of the app is just one proxy in a chain of proxies .. at its best the first incoming HTTP server should fix (reset) the `X-Forwarded-For` header .. in most HTTP setups we will find something like this:

https://github.com/searxng/searxng/blob/ea0cddba0b9366326eaebc0a3a55502a17e5baf4/utils/templates/etc/nginx/default.apps-available/searxng.conf:filtron#L8-L9

We (the developer) do not know how many proxies in front of the app so I thought it might be better we add a configuration option to select what position in the `X-Forwarded-For` identifies the IP of the request (client).

**Comment by ononoki1** [comment]
Why not use `X-Real-IP` to replace `X-Forwarded-For`?

If there is a chain of proxies, only the first incoming one needs to set `X-Real-IP` to `$remote_addr`, and other proxies simply keep that header as-is. So SearXNG knows the client IP is just what `X-Real-IP` shows.

**Comment by return42** [comment]
> If there is a chain of proxies, only the first incoming one needs to set `X-Real-IP` 

Thats true .. but what if the SearXNG admin does not have the permissions to modify the setup of the first incoming proxy? .. `X-Forwarded-For` is set by default in most setups: [The X-Forwarded-For (XFF) request header is a de-facto standard header for identifying the originating IP address of a client connecting to a web server through a proxy server.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)

    X-Forwarded-For: <client>, <proxy1>, <proxy2>

BTW we have the same issue in the self-info plugin, where we select the first item (https://github.com/searxng/searxng/issues/1237#issuecomment-1139696169):

https://github.com/searxng/searxng/blob/ea0cddba0b9366326eaebc0a3a55502a17e5baf4/searx/plugins/self_info.py#L37-L40

**Comment by return42** [comment]
1. [The X-Forwarded-For (XFF) request header is a de-facto standard header for identifying the originating IP address of ... ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)

2. [the limiter must trust the header `X-Forwarded-For` given to it by a proxy](https://github.com/searxng/searxng/issues/1237#issuecomment-1139696169)

The setup of the proxy must pass a correct `The X-Forwarded-For` to the client.

I don't know what we can do more .. I think this issue can now be closed (if not ask to reopen:
