### ISSUE TITLE
[question] How to set locale to Hong Kong in the settings.yaml?

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searxng#1238]
Hi, 

In the preference on the page there is a Hong Kong option. How can set this as default using the settings?

https://docs.searxng.org/src/searx.locales.html#searx.locales.LOCALE_NAMES

It seems that the locale name is not in the doc. Thank you!

**Comment by dalf** [comment]
In the search section:

https://github.com/searxng/searxng/blob/866030611828c26a9c8c63686715eb5e96f54019/searx/settings.yml#L25

Set the value "zh-HK"

**Comment by extremelyonline** [comment]
Thank you!
