### ISSUE TITLE
[engine] add petal search

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#1247]
**Working URL to the engine**
https://petalsearch.com/

**Why do you want to add this engine?**
Its apparently the default search engine in the huawai browser?

**Features of this engine**
Its fast, the design is pretty similar to google, optimized for mobile devices and it has a lot of "normal" results and not so many instant answers. The all and news category are the most important IMO.

**How can SearXNG fetch the information from this engine?**
I did not see an API from a quick check. Tho they return the results in a GET request, so they can be parsed from the HTML.

**Applicable category of this engine**
General and news as separate engines.

**Additional context**
Requested in Matrix by `omlet`.

**Comment by mrpaulblack** [comment]
there is already a PR from Allen: https://github.com/searx/searx/pull/2897

Latest version in SearX: https://github.com/searx/searx/blame/master/searx/settings.yml#L1472-L1490

**Comment by tiekoetter** [comment]
Possible implementation: https://github.com/tiekoetter/searxng/commit/8ec993c5e7286a7b62f538f2daf392850206152f
