### ISSUE TITLE
remove of bashisms from shell scripts

### ISSUE THREAD

**Issue by return42** [searxng/searxng#125]
Most of our shell scripts are written for bash.

I would suggest to write your scripts on dash shell [2]. Dash is mostly compliant to POSIX standard and pre installed on tiny (docker) images (d6c321b830).

I add this issue to monitor the _"remove of bashisms"_, comments and remarks are welcome.  Further read:

- "How to make bash scripts work in dash" [1]
- "Dash shell Vs Bash shell" [2]
- "POSIX Shell Command Language" [3]

https://github.com/searxng/searxng/blob/e0af67f0afbef6887a9dfb0546cd150b9f9f0c1a/Makefile#L56-L68

[1] https://mywiki.wooledge.org/Bashism
[2] https://raviminnikantitechie.wordpress.com/2018/06/07/dash-shell-and-differences-with-bash/
[3] https://raviminnikantitechie.wordpress.com/2018/05/03/posix-shell-command-language/

**Comment by return42** [comment]
> I add this issue to monitor the "remove of bashisms", comments and remarks are welcome.

I tried to move the shell scripts from bash to dash but the disadvantages outweigh the advantages. To name just some cons of dash (POSIX):

- POSIX does not support arrays / there are tricks using awk but calling external tools is much slower than bash and needs additional installations.
- POSIX does not support slices `${var:n:m}` and `${var/foo/bar}`/ there are tricks but using external tools .. 
- POSIX does not support dots in function names (e.g. `docs.html` or `pyenv.install`).  Redefining the naming scheme is not an option.

**Comment by dalf** [comment]
( I was clueless about the subject. )
