### ISSUE TITLE
Kubernetes Helm Chart for SearxNG

### ISSUE THREAD

**Issue by ApolloDS** [searxng/searxng#1256]
**Is your feature request related to a problem? Please describe.**

I'm using the Kubernetes Helm Chart from here: https://github.com/k8s-at-home/charts/tree/master/charts/stable/searx
searxNG was not usable with this chart by only changing the image to searxng/searxng.

**Describe the solution you'd like**

A Kubernetes Helm Chart for SearxNG woud be great :-)

**Describe alternatives you've considered**

Use a Kubernetes Deployment

**Additional context**

@unixfox according to the chat in #searxng:matrix.org I should ping you :-)

**Comment by unixfox** [comment]
@mrpaulblack It's not related to the project searxng-docker. This issue should be in searxng/searxng repo.

**Comment by mrpaulblack** [comment]
ok, sorry.

@ApolloDS ,
thanks for the issue ticket. I personally dont have a lot of experience with k8s and cannot really help with this, but I know that @unixfox has a running SearXNG instance with k8s... Maybe you can share your config here?

**Comment by unixfox** [comment]
> ok, sorry.
> 
> @ApolloDS , thanks for the issue ticket. I personally dont have a lot of experience with k8s and cannot really help with this, but I know that @unixfox has a running SearXNG instance with k8s... Maybe you can share your config here?

My config is too customized for my own needs that I don't really want to share it.

But I plan to redo it with k8s-at-home common chart as a good base.

**Comment by unixfox** [comment]
@ApolloDS Can you test the helm chart: https://github.com/searxng/searxng-helm-chart/tree/main/searxng?

**Comment by ApolloDS** [comment]
Hi @unixfox ,
Thank you very much for this helm chart, I appreciate it very much!
Sorry for the delay, I had now the time to test it.
And sorry, there is one small problem with this cert-error:
"Get "https://charts.searxng.org/index.yaml": x509: certificate is valid for *.github.com, www.github.com, github.io, github.com, *.github.io, githubusercontent.com, *.githubusercontent.com, not charts.searxng.org"

So it seems tha certificate is not valid and terraform will not accept it.
I will try to ignore the cert-check and try again for now and let you know here again...

**Comment by unixfox** [comment]
Sorry GitHub pages have issues generating the TLS certificate... I'll let you know once it's fixed.

**Comment by ApolloDS** [comment]
Hello @unixfox ,
So, I could now test the whole config with a workaround "insecure: yes" with terraform.
Now everything runs smoothly, perfect!

Thank you very much for your work, absolutely great to have now a helm chart, cool!

**Comment by unixfox** [comment]
HTTPs certificate issue is now fixed

**Comment by tavrez** [comment]
What happened to helm chart repository? The url does not exists anymore https://charts.searxng.org
