### ISSUE TITLE
Petal Search - Images/Videos/Science

### ISSUE THREAD

**Issue by TheFrenchGhosty** [searxng/searxng#1257]
**Working URL to the engine**

https://petalsearch.com/

**Why do you want to add this engine?**

Independent indexer.

**Features of this engine**

See previous point.

**Applicable category of this engine**

Images/Videos/Science

**Additional context**

Follow up to #1254 currently only General/News are supported, I'm asking for the other 3 categories.

**Comment by allendema** [comment]
Could you test the one for images?

If it works then I will open a merge request.
https://github.com/allendema/searxng/tree/petal-images

**Comment by tiekoetter** [comment]
@allendema I can test it when I am home.

**Comment by TheFrenchGhosty** [comment]
@allendema I don't personally have a good way to test PRs sadly, I use the docker image.

**Comment by TheFrenchGhosty** [comment]
@allendema @tiekoetter Thanks to both of you :)

**Comment by tiekoetter** [comment]
@allendema Could you create the PR?

**Comment by tiekoetter** [comment]
Update on the implementation of the video and academic engine:

Video:
Currently not possible because the URL of the videos is only accessible when the page is parsed with JS enabled.

Academic:
Not accessible to all users (I don't have the option to search the academic category because the option/category is missing)

**Comment by allendema** [comment]
> Could you create the PR?

Yes

**Comment by TheFrenchGhosty** [comment]
@tiekoetter 

Not having video isn't really a problem for me personally.

Academic would be nice to have, but again, not really a problem.

So, now that the image category is added (thanks a lot by the way), I guess this issue can be closed (unless you want to try to get the others working).

**Comment by return42** [comment]
> I guess this issue can be closed 

Let it open .. petal search is a good and fast engine .. there are a lot of things we can improve with (e.g. language support) .. when I have time I will come back to this issue / thanks :+1:

**Comment by Bnyro** [comment]
Since Petal Search was removed in #2614, this can be closed too I think.
