### ISSUE TITLE
Block certain results by using keywords (blacklist on options)

### ISSUE THREAD

**Issue by masterofobzene** [searxng/searxng#1258]
This is no critical feature:

Implement an option to remove certain results from searches by using phrases or keywords.
I'm actually using the [SearchBlocklist extension that I modified to work with SEARX (firefox only)](https://github.com/masterofobzene/SearchBlocklist), and I know the "-" option in the search field to remove certain words but doing this takes more time when searching than simply searching for the intended words/phrase. Also ublacklist needs specific URLs to work so I would have to repeat the blocking on every bad result (that are probably auto-generated using search keywords so this wold be infinite).

WHY?
I'm really... really... REALLY tired of "toplists"; results like "5 Ways to....", "10 best softwares to...", "3 things..." etc etc.
Recently those websites started to pop-up like a virus on the net.

IDEA(?): An option that auto-concatenates certain "negative words" (i.e "-10 best") that the user can configure via settings so when searching, those options will be automatically appended to the search i.e "cut mp3 -"10 best" "

If this is not possible, its ok no problem.

**Comment by amalgame21** [comment]
Good idea
also I would like to see an option to block results from some domain.

**Comment by masterofobzene** [comment]
> Good idea also I would like to see an option to block results from some domain.

You can do that with my modified ublacklist (renamed "SearchBlocklist"). The extension has an option to automatically create a blocking rule for entire domains.

**Comment by ghost** [comment]
> Good idea also I would like to see an option to block results from some domain.

You can already block results from specific domains by enabling the hostname_replace plugin in your settings.yml file:
```
enabled_plugins:
...
  - 'Hostname replace'
```
```
hostname_replace:
  'www\.domain1\.com': false
  'www\.domain2\.com': false
```
(replace _domain1, domain2_ with whatever website you want to block)

But I agree, seeing a keyword/phrase based blocker would be a nice addition.

**Comment by slashformotion** [comment]
Blocking domain is the key here. It should be a built is feature, having a private search engine is great, but having non bloated results is better.

**Comment by return42** [comment]
> Blocking domain is the key here.

FYI, we discuss blocking of domains in https://github.com/searxng/searxng/discussions/970

**Comment by masterofobzene** [comment]
> Blocking domain is the key here. It should be a built is feature, having a private search engine is great, but having non bloated results is better.

I don't agree with that. Blocking domains is possible with an extension like ublacklist (once they add searx support) or my modified ublacklist extension for firefox [SearchBlocklist ](https://github.com/masterofobzene/SearchBlocklist) (I know that other people are developing SEARX support for ublacklist official extension too). Problem with that, is that there are too many trash sites with different domains that use common words. You would spend your life blocking nonsense domains. Besides that, you would manage your OWN instance blocking what YOU WANT to block, but users like me who doesn't run a private instance are left forgotten or are forced to use prefiltered domains by who-knows-what-criteria.
Automatic preconfigured negative words would filter these random sites without much more work involved and could be modified / disabled by users to their liking. Domain blocking can be done with [SearchBlocklist](https://github.com/masterofobzene/SearchBlocklist) already. I think negative words have the priority.

**Comment by sjehuda** [comment]
I think we should listen to @masterofobzene and I tend to agree with him.

**Comment by masterofobzene** [comment]
@sjehuda Forget it my friend, these people are not going to listen.  I've stopped using searxng since the public instances are trash (bad times, works 1 out of 4 times, constant blocking by the search engines) so I just stopped overcomplicating my life and started using startpage which seems to have a good privacy policy and I can use "negative words" like in google and uBlacklist supports it too so I can block entire domains. 

It comes a time when you finally realize there is no point on arguing when people don't want to listen, and I think I solved my problems by using startpage that is less prone to fail in general, and the risk privacy wise is low. When exceptionalism takes the scene, its better to leave them alone and search alternatives.

If it makes some sense to you to keep using this, you can still use negative words if you  use the google engine, since it accepts them, ddg and the others doesn't (you have to enter them manually though) and make sure __only google is selected__, otherwise you will still get a lot of trash results. 

I will close this since I don't have any interest or relation to searx.
Also uBlacklist now officially supports searx instances if you want to use it, no need for my extension anymore. 



Good luck
