### ISSUE TITLE
[question] How to launch Searx with the new way?

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#126]
I used to be able to do `python searx/webapp.py` but now it doesn't work anymore:
```
Traceback (most recent call last):
  File "/tmp/searxng/searx/webapp.py", line 58, in <module>
    from searx import logger
ModuleNotFoundError: No module named 'searx'
```

How do I launch it with the new way?

**Comment by dalf** [comment]
```python -m searx.webapp```

**Comment by virtadpt** [comment]
You might want to update the documentation to reflect this.  [The step by step instructions](https://docs.searxng.org/admin/installation-searxng.html) still reflect the old way that doesn't work anymore.

**Comment by return42** [comment]
@virtadpt thanks for pointing out, fix is on the way:

- https://github.com/searxng/searxng/pull/6078

----

BTW: `python -m searx.webapp` starts a instance by `Flask.run`:

[Do not use run() in a production setting. It is not intended to meet security and performance requirements for a production server. Instead see "Deploying to Production" for WSGI server recommendations.](https://flask.palletsprojects.com/en/stable/api/#flask.Flask.run)
