### ISSUE TITLE
Add environment variable for setting redis and contact URL, limiter and statistics enabling/disabling

### ISSUE THREAD

**Issue by dmigis** [searxng/searxng#1284]
**Is your feature request related to a problem? Please describe.**
From the viewpoint of deployment automation, it is not convenient to set Redis URL directly in SearxNG configuration file when using Docker. Same for secret key, limiter and statistics enabling/disabling, contact URL.

**Describe the solution you'd like**
I propose to add possibility to set mentioned values using environment variables. As alternative, it would be good to allow to set all fields of settings.yml as environment variables.

**Describe alternatives you've considered**
I considered to use envsubst command, but setting environment variables looks cleaner.

**Comment by return42** [comment]
> From the viewpoint of deployment automation, it is not convenient to set Redis URL directly in SearxNG configuration file when using Docker. 

why is it not convenient? 

> I propose to add possibility to set mentioned values using environment variables. As alternative, it would be good to allow to set all fields of settings.yml as environment variables.

We had this discussion already (sry can't remember where) / thats not possible without getting into mess: in settings we have complex data types like dicts .. these types can't be serialized into environment variables .. and its hard to maintain when the settings.yml changes the names and or data types.

> Same for secret key, limiter and statistics enabling/disabling, contact URL.

We have selected ones .. e.g.

https://github.com/searxng/searxng/blob/0ce9d9e893b37f8341d61564975b36b8af25e247/searx/settings_defaults.py#L167

IMO environment variables are most often not a good solution .. e.g. its make it harder to help other admins without knowing what there environment is .. A single point of definition avoids a mess.

We have a better alternative --> [use_default_settings](https://docs.searxng.org/admin/engines/settings.html#use-default-settings)

**Comment by return42** [comment]
Closing due to lack of response.
