### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by yancyzq** [searxng/searxng#1292]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.04-0ce9d9e8

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 100
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/gigablast.py:96`
  * Function: `response`
  * Code: `response_json = loads(resp.text)`

**Comment by return42** [comment]
Can't reproduce the issue.  Give us an example to reproduce and we can reopen this issue.
