### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Doug1kr** [searxng/searxng#1299]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.06-ea0cddba

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Zackptg5** [comment]
Works fine for me. Either google currently blocked you for too may requests and/or you don't have filtron setup properly. I'd read more of the documentation and search around searx reddit for the numerous people with similar questions/issues

**Comment by Doug1kr** [comment]
Hey thanks. I'm new to all this and learning. Thanks for helping.

**Comment by return42** [comment]
> Hey thanks. I'm new to all this and learning. Thanks for helping.

Hi @Doug1kr feel welcome :+1: ... however, I have a request for you; before adding a new issue please first look out if there is already one with your problem and a solution .. and there are a lot ;-) .. to name just a few:

- https://github.com/searxng/searxng/issues/779
- https://github.com/searxng/searxng/issues/531
- https://github.com/searxng/searxng/issues/771
- https://github.com/searxng/searxng/issues/1146
- https://github.com/searxng/searxng/issues/1199
- https://github.com/searxng/searxng/issues/1146

The solution is most often the same: try to activate `use_mobile_ui` ..

```yaml
- name: google
  ...
  use_mobile_ui: true
```

- https://github.com/searxng/searxng/issues/774

I close this issue now .. if you have questions about SearXNG, I recommend to join us on [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) we have a very active and dedicated community with a lot of *helping hands* .. :+1:

**Comment by Doug1kr** [comment]
Thanks! I try my best
