### ISSUE TITLE
Bug: Chinese language header problem

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searxng#1303]
**How did you install SearXNG?**
I'm using a public instance. All instances behaves the same way.

If you visit searxng in Hong Kong, the interface language defaults to Chinese Simplified, whereas HK people usually use Chinese Traditional or just English.

**Expected behavior**
Interface should be Chinese Traditional or just English (Generally it's ok to use the Taiwan version of the translation for Hong Kong.)

**Screenshots & Logs**
My browser's Accept-Language header is zh-HK,zh-Hant;q=0.9

Reference: https://github.com/searxng/searxng/issues/540#issuecomment-1152106517

**Comment by return42** [comment]
@extremelyonline I implemented a patch https://github.com/searxng/searxng/pull/1306 .. can you give it a tray / thanks!

**Comment by extremelyonline** [comment]
Yes it works!

**Comment by return42** [comment]
> Yes it works!

Thanks a lot for taking the time to test #1306 :+1:

---

I reopen this issue .. 

FYI: it's just a formality; as long there is no solution in the master branch, issues should be stay open. The issue will be closed, when the PR is merged into master branch.

**Comment by extremelyonline** [comment]
@return42  sorry to bother you again. The interface is correct after the last pull request was merged.

However, it seems that most search results under zh-HK 🇭🇰 are seemingly from China (in Simplified Chinese), and the results under zh-TW 🇹🇼 are actually more accurate for HK users.

For instance, to look up "https://www.price.com.hk/" with the search term "price+hk", the first result under zh-HK 🇭🇰 is a site from China, whereas the first result under 🇹🇼 is actually the correct result.

![HK](https://user-images.githubusercontent.com/100532901/173271627-091c4b2d-e371-4f80-8f9e-87bfc90fa45f.png)
![TW](https://user-images.githubusercontent.com/100532901/173271633-e9602d0b-ce5f-4f70-b0db-2ed88a6aa91b.png)

I'm not sure if this is a Searx issue...can this be fixed somehow?
