### ISSUE TITLE
Clone fails in Windows because some file names contain ":"

### ISSUE THREAD

**Issue by nexryai** [searxng/searxng#1310]
**How To Reproduce**
Clone this repository in Windows.

**Expected behavior**
The clone will be successful.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/61890205/173180722-ea30f425-5ec0-4919-b827-4d60bf50ddf8.png)

**Comment by dalf** [comment]
SearXNG doesn't officially work on Windows.
You can use WSL2 or the docker image.

**Comment by nexryai** [comment]
Thanks for the reply! I will use WSL on Windows.
