### ISSUE TITLE
Simple theme has inverted checkboxes

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1316]
I have noticed that when I check a box in the settings, the option is actually disabled, while blank boxes are taken as enabled options. This is also happening in the engines selection page. Is this the expected behavior? Thanks.

**Comment by dalf** [comment]
This is a legally from a long time.
It requires to break the preferences to fix the issue as far I remember.
It has to be fix.

(I have updated the issue #818 which was describing this issue among others)

**Comment by ghost** [comment]
@dalf thanks for the quick reply, so I will be waiting for the fix 👍

**Comment by return42** [comment]
I close this issue, the topic is covered by:

- https://github.com/searxng/searxng/issues/818
- https://github.com/searxng/searxng/issues/1440
