### ISSUE TITLE
advice: open a new window but not use the original window

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#1317]
Usually, the engine will open a new window to jump to other site.
(For example, if I search 'github' on google and click the result, I will have 2 window: 'result page' and 'github.)
but in SearXNG , I found it covered the 'result page'.

![Screenshot_20220613_062255_com.microsoft.emmx.png](https://user-images.githubusercontent.com/88757735/173256062-903ce8d3-814f-4b73-9a89-9747aa2b9004.png)
usually, the users wants more like this

![Screenshot_20220613_062517_com.microsoft.emmx.png](https://user-images.githubusercontent.com/88757735/173256089-839dd43d-851d-4ffa-9e04-5389cc8e3282.png)
instead of only this.

**Comment by mrpaulblack** [comment]
You can enable that feature in the preferences...

https://searx.tiekoetter.com/preferences -> Go to User Interface and set Results on new tab to true. After that press the save button.

Is that the feature that you described in this issue?
