### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by phine-wood** [searxng/searxng#1331]
**Working URL to the engine**

**Why do you want to add this engine?**

**Features of this engine**

**How can SearXNG fetch the information from this engine?**

**Additional context**

**Comment by return42** [comment]
Sorry @SkywalkHer; we do not know for the life of us what you want to tell us ... Formulate your request, then we can open this topic again.

**Comment by phine-wood** [comment]
i am a complete squid, newbie, goon. i really want to learn github with my little spare time i have....
Would any of you know of a good source with video instructions step by every little to help me...or perhaps i would pay for someone one on one

**Comment by Solirs** [comment]
> i am a complete squid, newbie, goon. i really want to learn github with my little spare time i have.... Would any of you know of a good source with video instructions step by every little to help me...or perhaps i would pay for someone one on one

Fireship has a video about it and hes really good at explaining.
https://m.youtube.com/watch?v=HkdAHXoRtos
Could be a good start for you
