### ISSUE TITLE
Code highlighter is not suitable for the dark theme

### ISSUE THREAD

**Issue by return42** [searxng/searxng#1354]
The code highlighter should support dark & light theme of the UI:

![grafik](https://user-images.githubusercontent.com/554536/174655375-a4040ffb-1f56-48e2-9334-88c7a6f93317.png)

---- 

remark from @dalf on Matrix: the result width / font size ratio is also an issue (IMO).

- First screenshot: Oscar.
- Second screenshot: Simple

![grafik](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/IeQAhaEBzNRtHrGovKBmCBdn)

![grafik](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/WsysZWmReDHDVkkDsSPXsqrb)

**Comment by dalf** [comment]
Screenshots in various configurations of the query `!scc grep` : https://dev.searxng.org/screenshots.html#config=Firefox+1920+-+dark+mode&test_case=search_code
