### ISSUE TITLE
Google video: the length is actually the date

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#1359]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

 2022.06.18-189df7db (same issue on searx.be ).

**How did you install SearXNG?**

searxng-docker 

**How To Reproduce**

`!google_videos time` (or anything else)

**Expected behavior**

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/1594191/174992279-9ab4e529-e4d9-4ad7-8315-7f1db6a23b79.png)

The "length" field is a date instead a duration.

**Additional context**
N/A

**Comment by return42** [comment]
We can remove the `lenght` but I haven't found a solution to cast the type of the published date from `str` to a `datetime.datetime` object.

The format of the string google returns  depends on the selected language, by example when I select en-GB the string is like `12 Jul 2019`

I tried to use [babel.dates](https://babel.pocoo.org/en/latest/dates.html) but without luck

```python

>>> from babel.dates import parse_date
>>> parse_date('12 Jul 2019', locale='en_GB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/site-packages/babel/dates.py", line 1213, in parse_date
    year = numbers[indexes['Y']]
IndexError: list index out of range
```

Any suggestions? .. if not, we should simply remove the length.

**Comment by Milad-Laly** [comment]
@return42 Hi, is it only supposed to show duration of the video (24 mins) or the duration and when it was uploaded?

**Comment by return42** [comment]
Issue is solved by:

- https://github.com/searxng/searxng/pull/2269

You can test it here: [!gov :en time](https://darmarit.org/searx/search?q=%21gov+%3Aen+time)
