### ISSUE TITLE
Static files: build process

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#137]
Result of `make themes` is a mess to deal with: it creates conflicts on all pull requests, if the master branch modified the built files. So two or more pull requests about the themes will create git conflicts.

A solution:
* commit only the source code.
* ask the administrators to build the themes, but it requires a lot of more dependencies

Another solution can a submodule with the built files, but I expect difficulties to synchronize everything especially when there are different branches.

Here a proposal based on the principale used in the previous pull requests: 
* the last commit in a branch contains the built files
* add some scripts to manage this commit

Note: "source files" and "build files" refer to the static files only.

#### `static`

build static files (may be rename "themes")

* call searx_extra/update/update_pygments.py
* call "themes"

#### `static.clean`

It is actually "git restore", but as if the built files are not commited, so "git clean" (and in the same way than "make clean")

* git restore [built files]

#### `static.git.drop.commit`

* drop the last commit if it is made by "static.git.commit"

#### `static.git.branch.check`

Check the current branch:

* exit code 0 if there is neither commit with a built file, neither a commit with modified source file.
* exit code 1 if one of the commits of branch contains a mix of static built file and source file.
* exit code 2 if there is modified source file.
* exit code 3 if there are some uncommited built file.

#### `static.git.commit`

build & commit static files (update commit or new commit)

* call "static.git.branch.check"
* if exit code is 0 or 1: stop
* if exit code is 3:
    * call "static.clean"
* if exit code is 2 or 3:
	* call "static.git.commit.drop"
	* call "static"
	* commit built files (only built files nothing else)

#### `static.git.restore`

after "git add", make sure there is not a mix a built & source files

* check if the staged files contains a mixed of source files and built files
* if yes
	* git restore --staged [built files]
	* display a warning to the user to call "make static.git.commit"

#### `make static.git.resolve.conflict`

* it should be the only files to conflict (no other files), otherwise stop the hook.
* git checkout --theirs [built files] (keep our built files in the branch, it will dropped anyway).
* git add [built files]
* git rebase --continue

					
## Git hooks

Enabled by default, can be disabled globally with a configuration file.

				
#### `post-rebase hook`

if some built files conflict:
* call "make static.git.resolve.conflict"
* ask the user to call "make static.commit" (that will drop the built commit).

#### `pre-commit hook`

* call "static.git.restore"
* display a warning to call "make static.commit"

#### With git hooks

* Commit change in the source files (static files):
```sh
git add .  # all files including built files
git commit  # the commit actually ignore the built files with a warning
make static.commit  # build and commit the built files
```

* Rebase with change of the built files in master
```sh
git pull --rebase origin master  # the last 
make static.commit
```

#### Without git hooks

* Commit change in the source files (static files):
```sh
git add .
make static.git.restore  # The CI will fail without it
git commit
make static.commit
```

* Rebase with change of the built files in master
```sh
git pull --rebase origin master
make static.git.resolve.conflict
make static.commit
```

### CI

Fail if there are some modified source files without the built files?

---

Related to https://github.com/searxng/searxng/wiki/Milestones#milestone-19---data-upgrade--build-process

**Comment by return42** [comment]
My 2cent ...

In first order we should separate source code from the `./searx/static` folder.  That we mix source files and static files is what me confuse all the time and makes it hard to to manage with git / e.g. a simple `git add -all ./searx/static` should add only static files and not the sources (vice versa). 

The problem with the commits that mixes patches of source files and static files can first be solved organizationally by defining simple rules, e.g: 

  _"separate `./searx/static` into a single commit at the end of your patch series"_

ATM we do not have many contributors and if a PR mixes both (static & source) into one commit, we (the maintainers) have write access to the branch of the PR and we can split and reorder the commits in a rebase.

Later we can add some cleverness to `./manage`  and `Makefile` .. I think.

**update**: while we are on the way of _static files_ we should also cover the `./searx/data` files.

**Comment by dalf** [comment]
See #141

**Comment by dalf** [comment]
In the PR #157, I use https://gist.github.com/dalf/c73c59f96972ee7cf904a7861f9b0cb5 to manage the "Build Static" commit.
