### ISSUE TITLE
Make search results more relevant by more precise keyword matching 

### ISSUE THREAD

**Issue by ralphrmartin** [searxng/searxng#1371]
**Is your feature request related to a problem? Please describe.**
Many searches return too many irrelevant results. It would be useful to be able to exclude result pages containing one or more irrelevant keywords. For example, this can be done in Google searches using "-keyword". Other search engines may also provide such an option, but perhaps using different syntax e.g. "NOT keyword".

**Describe the solution you'd like**
Searxng could define and use some syntax for this purpose in its searches, internally converting them into the appropriate syntax for each search engine consulted.

**Describe alternatives you've considered**
An alternative would be to filter results returned by the search engines to exclude ones containing unwanted keywords, but that would put much more load on searxng.

**Additional context**
A related feature, which would also be extremely useful, would be to only include results which **explicitly** contain searched for keywords (not near matches). This used to be possible with Google using "+keyword", but alas no longer, so this probably would need postfiltering in searxng.

**Comment by intrepidsilence** [comment]
Is this being considered for addition? This is a very important feature to make this engine usable.
