### ISSUE TITLE
Nothing rendering

### ISSUE THREAD

**Issue by ZackeryBayle** [searxng/searxng#1398]
This is my first setup. I am getting nothing rendered to the page. the only error I have from the console is  `Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')`

Linux, Ubuntu LTS 20.XX
current Docker install
current searxng install

please let me know if their is any other info I can provide.

**Comment by mrpaulblack** [comment]
Closing as dupe of https://github.com/searxng/searxng-docker/issues/50; Closing.
