### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by linuxtyp** [searxng/searxng#1405]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.15-36184b2f

**How did you install SearXNG?**
searxng-docker on a raspberry pi 3

**What happened?**
error occurs when i search something

**How To Reproduce**

**Expected behavior**
I don't think the error has consequences, but it bothers me...

**Screenshots & Logs**
Error! Engines cannot retrieve results:
google ( [Suspended: too many requests](https://notgoogle.live/stats?engine=google) )

**Additional context**
I tried to fix this Problem with a solution for this error but it still throws the error.
ui:
  use_mobile_ui: true
  static_use_hash: true

i added the use_mobile_ui: true line in the settings.yml

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
@linuxtyp Which AS is your servers IP(s) on?

**Comment by linuxtyp** [comment]
Thank you for your quick reply, but i don't understand what you mean by AS.

**Comment by tiekoetter** [comment]
https://en.wikipedia.org/wiki/Autonomous_system_(Internet)

Basically what ISP it uses.

**Comment by linuxtyp** [comment]
No it is just in my Local Network. From my home ip address.

**Comment by tiekoetter** [comment]
Ok that is strange. I suppose you can use Google normally on your network? Is there anything you do on your network which could let google believe that you are a "bot"?

**Comment by linuxtyp** [comment]
Yes i can use google normally. On the same Raspberry pi runs Pihole it could be that that blocks the requests. Thank you for your help, much appreciated. I will look at the query log and whitelist the safebrowsing url. If i have any more problems i will post again.

**Comment by Razuuu** [comment]
This error is on notgoogle.live too and on my own searxng.

**Comment by tiekoetter** [comment]
@Razuuu Same question for you: What AS is the IP(s) of your instance on?

The notgoogle.live instance was probably flooded and therefore blocked by google. Most top public instances at https://searx.space don't have this issue.

**Comment by Razuuu** [comment]
Its Deutsche Telekom AG

**Comment by tiekoetter** [comment]
@Razuuu Strange I run my local test instance with no problems on my home internet connection (Vodafone/Unitymedia). Even on my public instance I only had to enable `use_mobile_ui` (I use multiple proxies to distribute the load).

Could you check what happens if you curl some google search page from your server?

**Comment by Razuuu** [comment]
```curl -v "https://www.google.com/search?q=Razuuu" -o googlesearch.txt```

```<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DRazuuu&amp;q=EhAgAQjYGACFggAAAAAAAAACGIvpgpYGIhDsCRW8rzN76wgY4Fq8yo1KMgFy">here</A>.
</BODY></HTML>```

**Comment by Razuuu** [comment]
![J 6oLhF](https://user-images.githubusercontent.com/40471551/177016317-6aa56b11-a346-4680-b921-14bcb0efe4a0.png)

This is the link.

**Comment by tiekoetter** [comment]
@Razuuu I honestly don't know why google would ever block an IP from a residential ISP (I assume you don't have like 1000 users on your network who hammer google with queries) but you are now the second one this has happened to. I don't think this is an error SearXNG can fix.

**Comment by Razuuu** [comment]
I'm the only one tbh

**Comment by tiekoetter** [comment]
@Razuuu The author of this issue has the same problem.

**Comment by Razuuu** [comment]
I will disable google then

**Comment by Razuuu** [comment]
@linuxtyp do this in your config too:

```
...
engines:

    - name: google
      disabled: true

...
```

**Comment by silvio2402** [comment]
Hey guys, I think I had the same issue with a different engine I was trying to add. I’m still trying to remember, but I think I fixed it by using the correct headers (to be precise, the User-Agent header) in the request. It’s weird that this issue doesn’t occur with other instances, but I thought this might help if someone wanted to take a deeper look into the problem.

**Comment by demoslotid** [comment]
> Ok that is strange. I suppose you can use Google normally on your network? Is there anything you do on your network which could let google believe that you are a "bot"?

must the ip address recognized as bot ip address?

**Comment by erliughiwehf** [comment]
> > Ok that is strange. I suppose you can use Google normally on your network? Is there anything you do on your network which could let google believe that you are a "bot"?
> 
> must the ip address recognized as bot ip address?

Seems like it. When I run this on my VPS, I have never gotten a search through. Works on my home net.

**Comment by unixfox** [comment]
You have to add `use_mobile_ui: true` for the google engine like this:
```yaml
 - name: google
   engine: google
   shortcut: go
   use_mobile_ui: true
```

The original user did set `use_mobile_ui: true` in the ui section.

Issue safe to close @return42, it's a mistake from the original author. The functionality works.
