### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by PopC0rnwalk** [searxng/searxng#1406]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.15-36184b2f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Taxick** [comment]
Hi :)

I have the same problem! I have followed this guide to setup searxng : [https://docs.searxng.org/admin/installation-searxng.html](https://docs.searxng.org/admin/installation-searxng.html)

And this to setup nginx: [https://docs.searxng.org/admin/installation-nginx.html](https://docs.searxng.org/admin/installation-nginx.html)

My test site is: [https://wub10.futurenode.dk](https://wub10.futurenode.dk)

The error comes when I try to search!

**Comment by return42** [comment]
Use use_mobile_ui: true
See https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

Past open issues: https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+is%3Aclosed

**Comment by Taxick** [comment]
Hi.

Sorry for opening this report again!

I cant get Videos, Music, and Files to work.

I have read all the bug reports about this error (https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+is%3Aclosed)

I have also read this page: https://docs.searxng.org/src/searx.utils.html#searx.utils.match_language

`engines:

  - name: google
    engine: google
    use_mobile_ui: true

  - name: google images
    engine: google_images
    use_mobile_ui: true

  - name: google news
    engine: google_news
    use_mobile_ui: true

  - name: google videos
    engine: google_videos
    use_mobile_ui: true

  - name: google scholar
    engine: google_scholar
    use_mobile_ui: true

  - name: google play apps
    engine: google_play_apps
    use_mobile_ui: true

  - name: google play movies
    engine: xpath
    use_mobile_ui: true
    search_url: https://play.google.com/store/search?q={query}&c=movies
    results_xpath: '//div[@class="ImZGtf mpg5gc"]'
    title_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a'
    url_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a/@href'
    content_xpath: './/div[@class="kCSSQe"]'
    thumbnail_xpath: './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories: videos
    shortcut: gpm
    disabled: true
    about:
      website: https://play.google.com/
      wikidata_id: Q79576
      official_api_documentation:
      use_official_api: false
      require_api_key: false
      results: HTML`

**What a I'm doing wrong?**
