### ISSUE TITLE
Add search query to tab title to find some open search tab

### ISSUE THREAD

**Issue by firstdorsal** [searxng/searxng#1410]
**Is your feature request related to a problem? Please describe.**

With multiple open tabs i can't find out what searxng tab is the one im searching for.
![image](https://user-images.githubusercontent.com/10563452/177006762-bc536225-50aa-45fb-a2f9-d5a7f46c5bf5.png)

**Describe the solution you'd like**

Something like this:
![image](https://user-images.githubusercontent.com/10563452/177006799-d0e0c539-7cbc-47f8-91e4-741adf792ff2.png)

**Comment by tiekoetter** [comment]
There already is this option. It is called "Query in the page's title". You can enabled it under preferences -> privacy -> Query in the page's title

Or in your settings.yml 
https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings.yml#L91
