### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by gabrielgonzalezcastellvi** [searxng/searxng#1415]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.15-36184b2f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com.au')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

**Comment by return42** [comment]
Please provide more information on your setup and reopen if the error persists.

----
Or use use_mobile_ui: true
See https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

Past open issues: https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+is%3Aclosed
