### ISSUE TITLE
Bug: btdigg engine

### ISSUE THREAD

**Issue by Hadiasemi** [searxng/searxng#1417]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by unixfox** [comment]
Issue safe to close @return42. btdigg just don't like searxng.

One can avoid the rate limit error by using the onion url of btdigg on searxng: `btdigggink2pdqzqrik3blmqemsbntpzwxottujilcdjfz56jumzfsyd.onion`

**Comment by return42** [comment]
I looked at the same time .. on my public instance the issue is cause by a captcha from btdigg.

> One can avoid the rate limit error by using the onion url of btdigg on searxng: 
> `btdigggink2pdqzqrik3blmqemsbntpzwxottujilcdjfz56jumzfsyd.onion`

Thanks for the hint .. I haven't onion on my server right now .. May its time to setup onion :-)
