### ISSUE TITLE
Bug: z-library engine

### ISSUE THREAD

**Issue by NorthKentRPC** [searxng/searxng#1426]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 100
  * Parameters: `(None, None, '')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Closed in favorite of https://github.com/searxng/searxng/issues/1435

Fixed in https://github.com/searxng/searxng/pull/1457
