### ISSUE TITLE
please document differences to searx

### ISSUE THREAD

**Issue by josch** [searxng/searxng#1430]
Hi,

in https://github.com/searx/searx/issues/3269 I was told of some more differences of searxng and searx, namely:

 - no releases ("rolling releases") and thus downstream distributions should just pick git commits to package
 - different level of privacy due to engine metrics (please explain what they are, what they send and so on)
 - UI requires javascript

Commit https://github.com/searx/searx/commit/f51bc5c64821fd60b430609629811774fb2bb2fd documents these differences in searx. In this issue I'm asking you to document them in searxng as well. It would probably be best to put them into the ***Differences to searx*** section in the searxng `Readme.rst`.

**Comment by unixfox** [comment]
The UI doesn't require javascript, it has been corrected in https://github.com/searx/searx/commit/a2c7cf4b8a7cafca0a429dd23bbb9a92558f17e6 and talked in https://github.com/searx/searx/commit/f51bc5c64821fd60b430609629811774fb2bb2fd#r77591731

Rolling release is explained in the FAQ: https://github.com/searxng/searxng/discussions/1451

About the privacy of the metrics, we explained how to disable them: https://github.com/searxng/searxng#user-experience. dalf is preparing a document explaining that the metrics don't hurt the privacy. I guess that's the last part to do.

**Comment by mrpaulblack** [comment]
Oh I forgot to answer this, thanks Unixfox. We explained our stand on the the differences in the FAQ -> https://github.com/searxng/searxng/discussions/1451; Closing.

**Comment by josch** [comment]
Thank you for the pointer to the FAQ. Maybe you can reword the answer to "Is SearXNG worse then SearX in keeping the users privacy intact?" or rephrase the question? I don't think it makes sense to have a FAQ entry without an answer. Either the question is answered in the FAQ or it isn't and then you do not need to put the question in. Also your statements in https://github.com/searx/searx/issues/3269 were pretty clear in terms of how searxng and searx compare in terms of privacy. Maybe what was said there can be copied to that FAQ entry? Thanks!
