### ISSUE TITLE
Possibility to limit high RAM usage due to many uwsgi workers being active?

### ISSUE THREAD

**Issue by soerenOsisa** [searxng/searxng#1431]
I used the docker instance of searxng and noticed the usage of about 2.5 GB of RAM. When I checked out top I saw that there are a lot of uwsgi workers running and taking up that much memory. So first why are there so many and is there a way to limit them to reduce RAM usage?

Thanks in advance

**Comment by mrpaulblack** [comment]
Hi @soerenOsisa ,
By default there are as many workers spawned as you have CPU cores in your system. For each worker there are 4 threads spawned as described here: https://github.com/searxng/searxng/blob/master/dockerfiles/uwsgi.ini#L7= . Each worker takes up around 500MB of RAM. This decission was made with public instance in mind that can have a high amount of traffic so its good to have a big enough amount of works and threads to handle the workload (for example we have an image proxy feature and if a user opens up the image page there is a request for each image to the backend...)

You can change this by going into the `searxng/` directory and changing this value to something smaller: https://github.com/searxng/searxng/blob/master/dockerfiles/uwsgi.ini#L7= with a value of 2 it should take up around 1GB.

Does this solve your issue?

**Comment by soerenOsisa** [comment]
@mrpaulblack 
Yes it does. My intention is to deploy a searxng instance on every machine to use it. Therefore it isn't necessary to have that many. Hence I would suggest to put that information somewhere to easily find (eg the readme under limit ram usage for low traffic instances). Because that way more people could be aware of that.
But I will close this request as you kindly answered my question. Thanks a lot
