### ISSUE TITLE
Bug: google images engine

### ISSUE THREAD

**Issue by userdignity** [searxng/searxng#1432]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**
I installed SearXNG using docker.

**What happened?**
As soon as i search something the results show as normal but i can't open the Images tab and there are no images shown on the right side.

**How To Reproduce**
I'm not pretty sure since i just installed it. I changed the language and changed the default categories to "General, Images and Map"

**Expected behavior**
I expected to search for something and have images pop up on the right side instead of `Error! Engines cannot retrieve results:
google images`

**Screenshots & Logs**
(https://gyazo.com/287fc3763f54fe48e90e0332d8f139a0)

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 100
  * Parameters: `('200', 'OK', 'consent.google.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('//script[contains(., "AF_initDataCallback({key: ")]', 'index 1 not found')`
  * File name: `searx/engines/google_images.py:107`
  * Function: `parse_urls_img_from_js`
  * Code: `img_src_script = eval_xpath_getindex(dom, '//script[contains(., "AF_initDataCallback({key: ")]', 1).text`

**Comment by unixfox** [comment]
Can you access google images from the same IP address as your searxng instance? Do you run searxng on a server located in a datacenter?

**Comment by akr2002** [comment]
Interesting that you mention it. I run mine on a VPS so I curl'd an image search and got cookie consent form
![image](https://user-images.githubusercontent.com/21287366/178105225-e1a820f4-9bb0-4b24-b140-33087c64725a.png)

**Comment by akr2002** [comment]
As for Bing, it did not retrieve images

https://user-images.githubusercontent.com/21287366/178105483-18c335ca-499d-45e9-9f61-f6c9fe70ab5c.png

**Comment by akr2002** [comment]
duckduckgo returns an empty page
https://user-images.githubusercontent.com/21287366/178105648-fb451a26-3586-4833-930b-2c68086658fe.png

**Comment by unixfox** [comment]
@GNUxeava
In which country is hosted your VPS?

**Comment by userdignity** [comment]
> Can you access google images from the same IP address as your searxng instance? Do you run searxng on a server located in a datacenter?

I run mine on a server located in a Datacenter in Germany. If I use a VPN running over that server I can access Google Images. The only image which gets shown is on the embedded Wikipedia page.

**Comment by akr2002** [comment]
> @GNUxeava In which country is hosted your VPS?

Singapore

**Comment by dalf** [comment]
There is the same issue on `paulgo.io`, `searx.tiekoetter.com`, `searxng.tordenskjold.de` and my personal instance (see the engines tab of searx.space).

**Comment by unixfox** [comment]
> There is the same issue on `paulgo.io`, `searx.tiekoetter.com`, `searxng.tordenskjold.de` and my personal instance (see the engines tab of searx.space).

@mrpaulblack @tiekoetter @dalf can we get an HTML result from your server?

**Comment by tiekoetter** [comment]
From one proxy (`curl -i "https://www.google.com/search?q=time&tbm=isch" -A "Mozilla/5.0 (X11; Linux i686; rv:102.0) Gecko/20100101 Firefox/102.0"`):

```
HTTP/2 302 
content-type: application/binary
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: Mon, 01 Jan 1990 00:00:00 GMT
date: Sat, 09 Jul 2022 16:35:45 GMT
location: https://consent.google.com/m?continue=https://www.google.com/search?q%3Dtime%26tbm%3Disch&gl=DE&m=0&pc=irp&uxe=eomtm&hl=en-US&src=1
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
content-security-policy: script-src 'nonce-HvGCCFAu_Ie-rxdMJGcOQw' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/VisualFrontendUi/cspreport;worker-src 'self'
content-security-policy: script-src 'nonce-HvGCCFAu_Ie-rxdMJGcOQw' 'self' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com https://graphviz.corp.google.com https://static.corp.google.com https://www.googleapis.com/appsmarket/v2/installedApps/;report-uri /_/VisualFrontendUi/cspreport
content-security-policy: require-trusted-types-for 'script';report-uri /_/VisualFrontendUi/cspreport
content-security-policy-report-only: script-src 'unsafe-inline' 'self' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com https://graphviz.corp.google.com https://static.corp.google.com https://www.googleapis.com/appsmarket/v2/installedApps/;report-uri /_/VisualFrontendUi/cspreport/allowlist
permissions-policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-platform=*, ch-ua-platform-version=*
accept-ch: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
cross-origin-opener-policy: unsafe-none
server: ESF
content-length: 0
x-xss-protection: 0
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
set-cookie: __Secure-ENID=6.SE=C5EJVefXsdC0ylJVCW7wm2nDdmw3deeWiSqzkkIXDnT0OwX57OK5eZCrvi8P51su28dvrxMrKWq_QLk3UZvcKbgneqkQNNoW7wCHiPHb02Iao0q8G6O0IKojmrKwzPZ8DtQmR4igeH7COh1vIYvOxRaDdNaIJKRYgquF84QWCIc; expires=Wed, 09-Aug-2023 08:54:03 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: AEC=AakniGMYqHnOl3YOADfsGLeV4pJZ8sggjoMSmSrM1CwCBwmT2IhSAS1tr7U=; Domain=.google.com; Expires=Thu, 05-Jan-2023 16:35:45 GMT; Path=/; Secure; HttpOnly; SameSite=lax
set-cookie: CONSENT=PENDING+510; expires=Mon, 08-Jul-2024 16:35:45 GMT; path=/; domain=.google.com; Secure
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

**Comment by akr2002** [comment]
Spoof user agent. Google does not like being curl'd

**Comment by tiekoetter** [comment]
@GNUxeava Yeah I also just realized that 😂

**Comment by tiekoetter** [comment]
I noticed now that I can make exactly one search after which it fails to parse (it shows the consent again). If I restart SearXNG it works again. It worked yesterday so I am not sure why it happens.

  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 50
  * Parameters: `('//script[contains(., "AF_initDataCallback({key: ")]', 'index 1 not found')`
  * File name: `searx/engines/google_images.py:107`
  * Function: `parse_urls_img_from_js`
  * Code: `img_src_script = eval_xpath_getindex(dom, '//script[contains(., "AF_initDataCallback({key: ")]', 1).text`

**Comment by unixfox** [comment]
> I noticed now that I can make exactly one search after which it fails to parse (it shows the consent again). If I restart SearXNG it works again. It worked yesterday so I am not sure why it happens.
> 

I'll investigate more when at home but I think google still want a cookie with `CONSENT=PENDING+`. Related to https://github.com/iv-org/invidious/pull/2207

**Comment by mrpaulblack** [comment]
Yeah here is an issue about this from my instance: https://github.com/paulgoio/searxng/issues/41 (Actually its from before the PR and I just updated to the latest version sorry)
