### ISSUE TITLE
Preferences options aren't consistent.

### ISSUE THREAD

**Issue by MontyQI** [searxng/searxng#1440]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.07.04-7a9beb4f 
**How did you install SearXNG?**

Used https://searx.tiekoetter.com/ instance
**What happened?**
Some options have checkboxes, some- "On" "Off" selection menus, while others have "Disabled" "Enabled".

**How To Reproduce**

Go to options page, settings have these three types of the same type of setting (On or Off).
**Expected behavior**

Settings should have the same representation of the same type of option.
**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/79922836/177176728-eb7cfc4e-a61e-4bcb-bf96-5f09db284384.png)
![image](https://user-images.githubusercontent.com/79922836/177176756-0cb961ff-d0fd-4f5b-ae2c-f9807d143019.png)

**Additional context**

**Comment by return42** [comment]
Send https://github.com/searxng/searxng/pull/1540 .. if you have time, please give it a try / thanks!
