### ISSUE TITLE
no search results displayed

### ISSUE THREAD

**Issue by GarthVG** [searxng/searxng#1441]
**How did you install SearXNG?**
sudo git clone https://github.com/searxng/searxng-docker.git

Powered by [searxng] - 2022.07.04-7a9beb4f

**What happened?**
Entered a search for coffee and got back a blank page.  I looked at the output code, nothing was returned.

**Additional context**
I enable the debug mode in the settings.yml, ran docker-compose up.  the only errors that i could see was this:

searxng    | INFO    searx                         : version: 2022.07.04-7a9beb4f
searxng    | INFO    searx                         : version: 2022.07.04-7a9beb4f
searxng    | ERROR   searx.shared                  : uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng    | ERROR   searx.shared                  : uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng    | ERROR   searx.shared                  : uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng    | ERROR   searx.shared                  : uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng    | DEBUG   searx.webapp                  : static directory is /usr/local/searxng/searx/static
searxng    | DEBUG   searx.webapp                  : static directory is /usr/local/searxng/searx/static

**Comment by mrpaulblack** [comment]
Hi @GarthVG ,
There was a similar issue posted here: https://github.com/searxng/searxng-docker/issues/31

Does this fix your issue?: https://github.com/searxng/searxng-docker/issues/31#issuecomment-1174067415

**Comment by GarthVG** [comment]
> Hi @GarthVG , There was a similar issue posted here: [searxng/searxng-docker#31](https://github.com/searxng/searxng-docker/issues/31)
> 
> Does this fix your issue?: [searxng/searxng-docker#31 (comment)](https://github.com/searxng/searxng-docker/issues/31#issuecomment-1174067415)

Hey @mrpaulblack
thanks for the help.  unfortunately that gave me an "internal server error".  it's strange.  the page comes up,  i can set the preferences, suto fill works but when I initiate a search...blank screen.

**Comment by mrpaulblack** [comment]
Ok in that case open up the dev tools of your browser by pressing F12. reload the page in check if there is any HTTP 429. I suspect the built in limiter plugin blocks your request. You can disable it by setting `limiter: false` in your `settings.yml`: https://github.com/searxng/searxng/blob/5c1c0817c3996c5670a545d05831d234d21e6217/searx/settings.yml#L59

does that help?

**Comment by GarthVG** [comment]
> limiter: false # rate limit the number of request on the instance, block some bots

That DID IT!!!  Awesome!  Thank you very much.  I put that entry in the server section in the settings.yml.  thanks again.

**Comment by mrpaulblack** [comment]
Glad I could help; Closing.
