### ISSUE TITLE
Issue: where git is saying unsafe repo

### ISSUE THREAD

**Issue by LogicFlame-Dev** [searxng/searxng#1450]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?** through the installation scripts on  the wiki

**What happened?** when trying to run make buildenv git is saying there's an unsafe repo and xx is owned by something else

**How To Reproduce**

By running the make buildenv a couple of times as I have been trying to update the base_url
**Expected behavior**

the first time it will work but bug where the line doesn't work then if you run it again it will show bellow
**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/47160230/177311408-70254389-84c5-4341-92a6-16f3cb834c03.png)

**Additional context**

**Comment by return42** [comment]
Does https://github.com/searxng/searxng/issues/1251 help?

**Comment by LogicFlame-Dev** [comment]
No unfortunately i just reran the install script as the whole site broke when I restarted the server.

but how do I get rid of this part as the base URL didn't affect it 
![image](https://user-images.githubusercontent.com/47160230/177323540-8e8949bd-44a8-40bc-90ee-bedae3b6f785.png)

as I would it like example.com/search?q=query 

but currently its example.com/searx/search which I don't fancy

**Comment by return42** [comment]
> but how do I get rid of this part as the base URL didn't affect it

You need to modify your HTTP setup manually (not supported by the script installation procedure).

**Comment by LogicFlame-Dev** [comment]
Ah ok, as in the nginx i have set the location to these 
![image](https://user-images.githubusercontent.com/47160230/177327064-c245785e-e5bf-4bde-bab7-ac9b3a6329a6.png)

It works for the main section but when doing a search request it then jumps back to the /searx/search

**Comment by return42** [comment]
>  jumps back to the /searx/search

You need to modify the `X-Script-Name` header also.

**Comment by LogicFlame-Dev** [comment]
thanks that worked, also quick question as I have tried looking for it how do you restart the whole of searxng without restarting the server

**Comment by return42** [comment]
> how do you restart the whole of searxng 

To restart SearXNG I use [utils/searx.sh](https://docs.searxng.org/utils/searx.sh.html) `deactivate service` and `activate service`.

For more please visit [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) and ask your questions.

Lets come back to the topic (title) of this issue: **"Issue: where git is saying unsafe repo"**

Is this problem solved for you? .. can we close this issue?

**Comment by LogicFlame-Dev** [comment]
Yes thanks its solved my issue thanks for your help.


The Fix by the way is to reinstall using the script again and it patches it.
