### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by YuukiSystems** [searxng/searxng#1454]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.14-e67ed894

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 40
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/gigablast.py:96`
  * Function: `response`
  * Code: `response_json = loads(resp.text)`

**Comment by return42** [comment]
I can't reproduce the issue, if you give an example how to reproduce the issue we can continue. Until then I will close the ticket.

**Comment by bonswouar** [comment]
Same on my instance (with about the same %!)
And I've just tried on a public instance, it also seems to happen, for example : https://search.unlocked.link/search?q=%21gb+plop&category_general=on&language=en-US&time_range=&safesearch=0&theme=simple

**Comment by thealphabonanza** [comment]
Same here for the past few weeks
Even just after updating to latest version today


Exception | json.decoder.JSONDecodeError | Percentage | 100
Expecting value
searx/engines/gigablast.py:96
response
response_json = loads(resp.text)

**Comment by return42** [comment]
The engine itself did not have an issue, you can test it locally on your desktop by running a `make run`.

Gigablast's API does block unauthorized request (after a while):

[You must always supply `&userid=<User ID>&code=<Feed Code>` in your access URL so you do not get permission denied errors](https://gigablast.com/searchfeed.html)

- https://github.com/searxng/searxng/pull/2293
