### ISSUE TITLE
Bug: wikidata engine

### ISSUE THREAD

**Issue by AntoniooDEV** [searxng/searxng#1459]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.05-7fec286f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 50
  * Parameters: `(None, None, 'query.wikidata.org')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by unixfox** [comment]
Something is off with the searx instance that you are using. Please choose another one on https://searx.space
