### ISSUE TITLE
OLED/blackout dark mode?

### ISSUE THREAD

**Issue by Apacelus** [searxng/searxng#1461]
**Is your feature request related to a problem? Please describe.**
The current dark mode is rather a grey mode. Would be cool to have an extra black/oled option

**Describe the solution you'd like**
A theme that uses black(rgb code: #000000) as its background

**Describe alternatives you've considered**

**Additional context**

**Comment by obfuscated-loop** [comment]
Due to the simplicity of a theme like this, have you considered an extension like [Stylus](https://github.com/openstyles/stylus/) to change CSS on the fly? This is, of course, only for usage within a computer browser.
