### ISSUE TITLE
Bug: genius engine

### ISSUE THREAD

**Issue by hanger281** [searxng/searxng#1464]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.06-be2f782c

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by unixfox** [comment]
@return42 safe to close

**Comment by MandiYang** [comment]
Can I ask how is this issue a duplicate? I also got the same issue.

**Comment by return42** [comment]
This issue is from 2022 .. things might change over the time and your bug is not related to genius in 2022 .. please open a new bug report if you have issues nowerdays.
