### ISSUE TITLE
blank page on both external hostname and private ip

### ISSUE THREAD

**Issue by l0r-e** [searxng/searxng#1466]
Hi, i installed Searxng on docker, but i get a blank page on both GET and POST request. 

Raspberry pi4 4gb

Docker ver 20.10.17

**Comment by apfatzgo** [comment]
I have the same problem. I get this HTML:

`<html><head><link rel="stylesheet" href="resource://content-accessible/plaintext.css"></head><body><pre></pre></body></html>`

**Comment by return42** [comment]
Just want to link 

- https://github.com/searxng/searxng/issues/1399
- https://github.com/searxng/searxng-docker/issues/27

**Comment by l0r-e** [comment]
i tried several times, still getting blank page. now it forces to use https and my browser says that is not a valid response. Idk what else i can do

**Comment by return42** [comment]
> Idk what else i can do

Sorry that I can't help .. we left this issue open in the hope that someone comes around having a hint for us .. in the meantime I recommend to ask about your issue to a wider audience: please visit our [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) chat, there are a lot more users listen on.

**Comment by l0r-e** [comment]
ok thanks

**Comment by return42** [comment]
@loryciar I would like to bundle the "blank page" requests in one place .. I'm going to close this thread / lets continue in https://github.com/searxng/searxng-docker/issues/50
