### ISSUE TITLE
When hostname URL has `searxng` present searching fails with 502

### ISSUE THREAD

**Issue by tucker19** [searxng/searxng#1468]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Docker 2022.07.06-c5ec8db6

**How did you install SearXNG?**
Docker compose

**How To Reproduce**
Have `searxng` within url. My instance was `searxng.mydomain.com` and when I try to do a search I end with a HTTP 502 Bad Gateway.

**Expected behavior**
No HTTP 502

**Screenshots & Logs**
```
today at 8:42:12 AM2022-07-06 13:42:12,043 WARNING:searx.engines.mojeek: ErrorContext('searx/engines/xpath.py', 193, 'title = extract_text(eval_xpath_list(result, title_xpath, min_len=1))', 'searx.exceptions.SearxEngineXPathException', None, ('./h2', 'len(xpath_str) < 1')) False
today at 8:42:12 AM2022-07-06 13:42:12,043 ERROR:searx.engines.mojeek: exception : ./h2 len(xpath_str) < 1
today at 8:42:12 AMTraceback (most recent call last):
today at 8:42:12 AM  File "/usr/local/searxng/searx/search/processors/online.py", line 143, in search
today at 8:42:12 AM    search_results = self._search_basic(query, params)
today at 8:42:12 AM  File "/usr/local/searxng/searx/search/processors/online.py", line 131, in _search_basic
today at 8:42:12 AM    return self.engine.response(response)
today at 8:42:12 AM  File "/usr/local/searxng/searx/engines/xpath.py", line 193, in response
today at 8:42:12 AM    title = extract_text(eval_xpath_list(result, title_xpath, min_len=1))
today at 8:42:12 AM  File "/usr/local/searxng/searx/utils.py", line 593, in eval_xpath_list
today at 8:42:12 AM    raise SearxEngineXPathException(xpath_spec, 'len(xpath_str) < ' + str(min_len))
today at 8:42:12 AMsearx.exceptions.SearxEngineXPathException: ./h2 len(xpath_str) < 1
today at 8:42:12 AM2022-07-06 13:42:12,185 WARNING:searx.engines.pypi: ErrorContext('searx/search/processors/online.py', 105, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'pypi.org')) True
today at 8:42:13 AM2022-07-06 13:42:13,377 WARNING:searx.engines.solidtorrents: ErrorContext('searx/search/processors/online.py', 105, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'solidtorrents.to')) True
today at 8:42:14 AM2022-07-06 13:42:14,385 WARNING:searx.engines.startpage: ErrorContext('searx/search/processors/online.py', 105, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'www.startpage.com')) True
today at 8:42:15 AM2022-07-06 13:42:15,538 ERROR:searx.engines.gentoo: engine timeout
today at 8:42:15 AM2022-07-06 13:42:15,799 WARNING:searx.engines.gentoo: ErrorContext('searx/search/processors/online.py', 96, "response = req(params['url'], **request_args)", 'httpx.TimeoutException', None, (None, None, None)) False
today at 8:42:15 AM2022-07-06 13:42:15,804 ERROR:searx.engines.gentoo: HTTP requests timeout (search duration : 6.2660797433927655 s, timeout: 6.0 s) : TimeoutException
```

**Additional context**
Fix: change my subdomain to just `search` so my full hostname is now `search.mydomain.com` and able to search now. From looking at the logs seems the code is stripping out `searxng` from hostname and maybe causing a mismatch.

**Comment by return42** [comment]
> From looking at the logs seems the code is stripping out searxng from hostname and maybe causing a mismatch.

can't see in the log what you mean / in the logs are all essages are comming from `searx.engines.<enigen-name>`.

**Comment by tucker19** [comment]
Seeing "SearxEngineXPathException" is what is leading me to my theory. Since the oath is getting messed up I would assume the hostname is changing.

**Comment by return42** [comment]
Its a XPath exception that comes from parsing the results from mojeek ..

   ERROR:searx.engines.mojeek: exception : ./h2 len(xpath_str) < 1

These exceptions are catched and logged (what we see in your log).

> Have searxng within url. My instance was searxng.mydomain.com and when I try to do a search I end with a HTTP 502 Bad Gateway.

Your [502 Bad Gateway](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors) issue is not related to the log from above.

Without any further info and looking at the log above I can only guess your 502 is related to some connection issues (there are a lot of timeout issues in the log when SearXNG send its queries to the engines).

**Comment by return42** [comment]
> Fix: change my subdomain to just search so my full hostname is now search.mydomain.com and able to search now. 

Sorry seen this to late .. so your issue is fixed .. I'm going to close this issue.

**Comment by unixfox** [comment]
I think something is off with your setup because there are plenty of other searxng instances that start with searxng.X and works fine: https://searx.space/
