### ISSUE TITLE
Optional address whitelisting for personal instances?

### ISSUE THREAD

**Issue by Solirs** [searxng/searxng#1471]
**Is your feature request related to a problem? Please describe.**

My feature idea is not related to a specific problem but i do think it would be a good feature and would be useful for people who host personal instances like me.
I would like to only allow specific addresses to access my instance.

**Describe the solution you'd like**

I propose adding an (optional) whitelisting feature.
It would run before every request (in @app.before_request possibly?) and would check if the requesters IP address is in the whitelist (maybe specified in settings.yml?). If it is the request would go trough as usual but if its not the app would return 401 unauthorized.

**Describe alternatives you've considered**

It might be possible to do this trough some WSGI server's settings but  it would be much simpler and consistent to add an option to do so in searxng itself, hence this feature request.

**Additional context**

I'm open to implementing this myself and commiting the code but i want to make sure this feature idea is welcome before i start work on it, please share your thoughts and opinions on this.

**Comment by return42** [comment]
> please share your thoughts and opinions on this.

A IP based access control is IMO not helpful, most often end users have dynamic IPs and companies have static IPs. 

We have [Private Engines (tokens)](https://docs.searxng.org/admin/engines/private-engines.html) what might fits better for a kind of access control ..

**Comment by return42** [comment]
@Solirs I see you gave my comment a thumbs up ... I assume my proposal fits to your needs and I'm going to close this issue.   If you think there is more needed, add a comment describing the needs and we can reopen this issue .. thanks for participate :+1:
