### ISSUE TITLE
Engine per Locations

### ISSUE THREAD

**Issue by dp466** [searxng/searxng#1474]
Google.ca
google.fr
etc...

**Why do you want to add this engine?**
Because of speed and results based on country

it work the same as google.com but servers are closer in my case, I get less latency from google.ca vs google.com

**Comment by return42** [comment]
https://github.com/searxng/searxng/blob/cf01f9e603ebbf3997212dde1daff7510d2d7118/searx/engines/google.py#L52-L104

**Comment by unixfox** [comment]
Google IP addresses are anycast, so I don't think it's possible to have less latency on google.ca than google.com.

Anycast mean the IP address will pick from a big list of servers, a server that is close to you.

Anyway, you can solve your initial issue by selecting English (Canada) as the language used but that will filter your results to only this language.
