### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by deepeee** [searxng/searxng#1480]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.07-cf01f9e6

**How did you install SearXNG?**
searxng-docker

**What happened?**
any search triggers a google error saying Error! Engines cannot retrieve results:
google ( [Suspended: too many requests])

**How To Reproduce**
search anything

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Did you try enabling `use_mobile_ui`?

Reference: https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

**Comment by deepeee** [comment]
use_default_settings: true
server:
  secret_key: "ultrasecretkey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
  engines:
    -  name: google
       use_mobile_ui: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0

**Comment by deepeee** [comment]
I have fixed this using https://github.com/searxng/searxng/blob/master/searx/settings.yml

I needed to create :engines and put the code below it.

:engines
- name : google
    engine : google
    use_mobile_ui : true
