### ISSUE TITLE
In images add searching by file type in the dropdown

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1490]
**Is your feature request related to a problem? Please describe.**

I often need to search specifically by file type e.g. JPG, PNG, GIF etc, sadly this is not possible from the UI in SearXNG 

**Describe the solution you'd like**

I would like to see file formats such as PNG, JPG, GIF etc be added in a new drop down/selector in the UI after searching, similar to the one Startpage has, thank you!

Startpage image type selector for reference:
![ITS](https://user-images.githubusercontent.com/91751074/178156288-8f97418c-9d9a-4272-ae5a-4af3ec8f8a82.png)

**Comment by return42** [comment]
This issue has been added up under the issue https://github.com/searxng/searxng/issues/1587
