### ISSUE TITLE
limiter plugin http error Too Many Requests and debug log shows searx.plugins.limiter: got connection=close when using via uwsgi Unix Domain Socket

### ISSUE THREAD

**Issue by ravermeister** [searxng/searxng#1492]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
```
git log -1
commit 641e39b0df38ec84f77362c070b5974b31c81a6c (HEAD -> master, origin/master, origin/HEAD)
Merge: 7e695c66 84e2a3bd
Author: Alexandre Flament <alex@al-f.net>
Date:   Sat Jul 9 21:18:56 2022 +0200

    Merge pull request #1486 from vojkovic/master
    
    Add infinite scroll as a setting in settings.yml
```

**How did you install SearXNG?**
I installed via the official [Step by Step](https://docs.searxng.org/admin/installation-searxng.html) Guide
and using nginx as described [here](https://docs.searxng.org/admin/installation-nginx.html)

**What happened?**
When I enabled the limiter Plugin I can't execute any search. neither with [Brave](https://brave.com/) nor with [Waterfox](https://www.waterfox.net/)

**How To Reproduce**

1. enable redis
```
redis:
  url: unix:///path/to/redis/sock?db=1

```
2. enable limiter plugin 
```
server:
...
  # monitor rate limits and protect privacy
  limiter: true
...
```
3. Configure [uwsgi](https://docs.searxng.org/admin/installation-nginx.html) (proxy or uwsgi) and nginx to use Unix Domain Socket:
uwsgi conf:
```
....
#
# using unix-sockets:
#
# On some distributions you need to create the app folder for the sockets::
#
#   mkdir -p /run/uwsgi/app/searxng
#   chown -R ${SERVICE_USER}:${SERVICE_GROUP} ${SEARX_UWSGI_SOCKET}
#
# socket = ${SEARX_UWSGI_SOCKET}
socket = /path/to/socketfile/searx.uwsgi.sock
```

nginx conf:
```
http {
    include	  mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    server_tokens off;

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    uwsgi_socket_keepalive on;

    set_real_ip_from  127.0.0.1;
    set_real_ip_from  ::1;
    real_ip_header    X-Forwarded-For;

    #gzip  on;
    server {
	listen       8080;
        server_name  localhost;

        access_log  /logs/searx.rimkus.it.access.log  main;
        error_log   /logs/searx.rimkus.it.error.log   warn;

        location / {
            include uwsgi_params;
            uwsgi_pass unix:/path/to/socketfile/searx.uwsgi.sock;
        }
        root /path/to//searx-src/searx;
        location /static { }
    }
}
```

**Expected behavior**
Searching is possible with the above Browsers

**Screenshots & Logs**

**Additional context**

I already tried to set 
```
so-keepalive=true
http-keepalive=1
add-header=Connection: Keep-Alive
``` 
to the uwsgi config, 
and tried to apply the header via `uwsgi_param` in the nginx config without suceess.

**Comment by return42** [comment]
In https://github.com/searxng/searxng/pull/1332 I tried uWSGI & socket communication and had lot of trouble.

I can't say if the following is related to your issue but to point out a few things I have found out:

Here are the https://github.com/return42/searxng/tree/searxng-install/utils/templates/etc/uwsgi setups I have used (look out for a `searxng.ini:socket` that fits to you distro).

And here is the nginx setup: https://github.com/return42/searxng/blob/searxng-install/utils/templates/etc/nginx/default.apps-available/searxng.conf:socket

Both files are templates; don't forget to replace the `${...}` placeholder.

BTW: what distro do you use? ..

---

**OT not related to your issue:** uWSGI & socket communication has its quirks ...

> 1. enable redis
> ```
> redis:
>   url: unix:///path/to/redis/sock?db=1
> 
> ```

Seems your SearXNG get connected to the socket .. for those having problem with:

Check how your distro installs uWSGI, by example Fedora (RHEL) install uWSGI in tyrant mode .. [Pitfalls of the Tyrant mode](https://github.com/return42/searxng/blob/searxng-install/docs/admin/installation-uwsgi.rst#pitfalls-of-the-tyrant-mode)]

**Comment by ravermeister** [comment]
Thanks, it is working with this [nginx config](https://github.com/return42/searxng/blob/searxng-install/utils/templates/etc/nginx/default.apps-available/searxng.conf:socket).
But I'm unsure what to set for `uwsgi_param    HTTP_X_SCRIPT_NAME    ${SEARXNG_URL_PATH};` 
And the generated search url which is shown in the result view on the right side contains an '\\'. (if I remove the '\\' on the HTTP_HOST setting it works). 

below is my nginx config:

```
        location / {
            uwsgi_pass unix:///home/raver7/run/searx.uwsgi.sock;
            include uwsgi_params;

            uwsgi_param    HTTP_HOST             \$host;
            uwsgi_param    HTTP_CONNECTION	 \$http_connection;

            # see flaskfix.py
            uwsgi_param    HTTP_X_SCHEME         \$scheme;
#            uwsgi_param    HTTP_X_SCRIPT_NAME    /;

            # see limiter.py
            uwsgi_param    HTTP_X_REAL_IP        \$remote_addr;
            uwsgi_param    HTTP_X_FORWARDED_FOR  \$proxy_add_x_forwarded_for;

        }
```

**Comment by return42** [comment]
> If I remove the '\' on the HTTP_HOST setting it works)

Sorry forgot to say .. in this template the `\` is to quote the `$`.

To fix your setup replace (e.g.) `\$host;` --> `$host;` .. please do this for all `\`.

For the script name activate the line:

      uwsgi_param    HTTP_X_SCRIPT_NAME    /;

**Comment by ravermeister** [comment]
Thanks, it works. Just one little thing I don't understand. if I set 
`uwsgi_param    HTTP_CONNECTION	 $http_connection;`
The error again occurs.  but setting it to
`uwsgi_param    HTTP_CONNECTION	 '';`
works. should I leave it blank? (as it was mentioned for the http proxy?)

Update: setting `uwsgi_param    HTTP_X_SCRIPT_NAME    /;` results in 'too many redirects' ...

**Comment by return42** [comment]
> The error again occurs. but setting it to

You mean you get an 429 page with just a message ..

https://github.com/searxng/searxng/blob/b6d59decda2be89a9b96e29b7a12538ba4af2c5c/searx/plugins/limiter.py#L86-L89

As you can see this message comes from the limiter .. 

    uwsgi_param HTTP_CONNECTION $http_connection;

passes the `Connection` header to SearXNG and the limiter sees a `close` value and thinks you are a bot:

https://github.com/searxng/searxng/blob/b6d59decda2be89a9b96e29b7a12538ba4af2c5c/searx/plugins/limiter.py#L65-L67

This means, your client (WEB-browser) sends a `Connection=close` HTTTP header .. or did you used a command line tool like `curl` to test (theses tools send a `close`, like bots do).

----

> Update: setting `uwsgi_param HTTP_X_SCRIPT_NAME /;` results in 'too many redirects' ...

OK, this might be the case in your setup .. I can't say why but if it works for you without a `/` it is OK to drop this line.

**Comment by ravermeister** [comment]
indeed, there comes an `Connection: close`. Unfortunately I can't turn it off because it's the Configuration of my hoster as mentioned [here](https://github.com/searxng/searxng/issues/1289#issuecomment-1153004382). 
I assume the equivalent part for the uwsgi socket *is* to set `uwsgi_param HTTP_CONNECTION '';`

anyway with this nginx config:

```
        location / {
            uwsgi_pass unix:///path/to/uwsgi_sock/searx.uwsgi.sock;
            include uwsgi_params;
            uwsgi_socket_keepalive on;

            uwsgi_param    HTTP_HOST             $host;
            uwsgi_param    HTTP_CONNECTION       '';
            # see flaskfix.py
            uwsgi_param    HTTP_X_SCHEME         $scheme;
#            uwsgi_param    HTTP_X_SCRIPT_NAME    /;
            # see limiter.py
            uwsgi_param    HTTP_X_REAL_IP        $remote_addr;
            uwsgi_param    HTTP_X_FORWARDED_FOR  $proxy_add_x_forwarded_for;
        }
```

it is working with the limiter plugin enabled. Thank you very much for your great help!
Kind regards
Jonny

**Comment by return42** [comment]
> Unfortunately I can't turn it off because it's the Configuration of my hoster 

Sad ... then the limiter can't use this criterion and you actually have to *unset*:

> I assume the equivalent part for the uwsgi socket *is* to set `uwsgi_param HTTP_CONNECTION '';`
