### ISSUE TITLE
 took too long to respond.

### ISSUE THREAD

**Issue by Ragemalik** [searxng/searxng#1495]
when i try to go to my search engine i get https://u.rehanm.me/l/Gss error

i did 
git clone https://github.com/searxng/searxng-docker.git
then i edited the .env to add my email and domain name
ran the docker compose

**Comment by return42** [comment]
Not clear to me what you mean .. can you please edit your comment in a way we can understand what you want and how it is related to the title "took too long to respond.".

**Comment by Ragemalik** [comment]
i ran it in docker so should i make a new issue in the docker section and close this?

**Comment by return42** [comment]
There is a vital community at [searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org).

I close this issue ...
