### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1501]
**Version of SearXNG - Docker**
2022.07.10-b6d59dec

**How did you install SearXNG?**
Installed it with the help of the wiki (Docker version)

**What happened?**
I added cloudflare to my site (SSL/TSL set to FULL) and everything works fine until I want to search something... Then a white screen appears with the message: Too Many Requests

**How To Reproduce**
Got to https://search.mark6712.com/ and search anything

**Expected behavior**
I expected to search things

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/30297895/178740134-5f1c5c29-d107-4c2e-980f-6542a1831dad.png)

**Comment by netgamadkr** [comment]
hi, im having the same issue, just deploy searxng on docker, how was this solved, please advice, thanks

**Comment by ghost** [comment]
> hi, im having the same issue, just deploy searxng on docker, how was this solved, please advice, thanks

I just disabled the limiter for public instances in settings.yml

**Comment by return42** [comment]
FYI: https://github.com/searxng/searxng/issues/1492#issuecomment-1180495040

**Comment by netgamadkr** [comment]
thanks appreciate your help
