### ISSUE TITLE
Bug: 1337x engine

### ISSUE THREAD

**Issue by demorsick** [searxng/searxng#1504]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.10-b6d59dec

**the 1337 engine doesn't work**

you should try to change it to 1337xx.to
how can i add/edit an engine?
I installed it as a docker image https://github.com/searxng/searxng-docker

**Comment by unixfox** [comment]
What's not working? Please give the error message.

**Comment by 1ilir0lika** [comment]
well i never receive the result from 1337x because it doesn't ping,they changed the domain,is there any way to manually modify or add an engine?

**Comment by return42** [comment]
@demorsick sorry for late feedback ..

> you should try to change it to 1337xx.to

its already :-) ..

https://github.com/searxng/searxng/blob/50d714d82952417f3db837a176b751d3845c0cc8/searx/engines/1337x.py#L20

> the 1337 engine doesn't work

I can't reproduce the issue 

https://darmarit.org/searx/search?q=%211337x%20foo

> well i never receive the result from 1337x because it doesn't ping,

@1ilir0lika: 1337x.to does not echo  a ping / but this does not mean the domain does not response to a HTTP request .. compare `ping 1337x.to` to `curl https://1337x.to` to see the difference. 

I'm going to close the issue .. if you have some more hints for us we can reopen and continue.
