### ISSUE TITLE
Hope to be able to customize the hyperlink in the home footer through settings.yml

### ISSUE THREAD

**Issue by miaowmint** [searxng/searxng#1515]
**Is your feature request related to a problem? Please describe.**

Hope to be able to customize the hyperlink in the home footer through settings.yml

_Currently, searxng can only set links to items such as "Source code | Issue tracker | Engine stats | Public instances" through settings such as "brand". I want to be able to add defined text and links through other settings_

**Describe the solution you'd like**

_By adding settings similar to the following_
```
hyperlink:
  text1: My Website
  url1: https://example1.com
  text2: Website123456
  url2: https://example2.com
  ...
```

_Achieve the following effect in the footer of the home page and each text is pointed to the correct link._
`Source code | Issue tracker | Engine stats | Public instances | My Website | Website123456 | ...`

**Additional context**

The original footer looks like this.
![image](https://user-images.githubusercontent.com/58991169/179384412-bbc1e87d-cc29-439d-8b85-f7ce1c1ee55c.png)

The footer after the function I proposed is added is like this.
![image](https://user-images.githubusercontent.com/58991169/179384453-57fc27b4-90ad-49ee-8619-591d92028cea.png)

I wouldn't actually do that, but by adding enough "text", it even looks like this.
![image](https://user-images.githubusercontent.com/58991169/179384537-f088b0b4-90c5-4d6b-8fbf-25503ee0891c.png)

And this.
![image](https://user-images.githubusercontent.com/58991169/179384582-02a84c06-db24-4c63-b28b-cc9efd09b5bb.png)

**Comment by return42** [comment]
Instead of links and text in the footer, I want suggest the *info-pages*.

Since https://github.com/searxng/searxng/pull/930 you can add a new (info) page that will be shown online next to the "About" page.

Add a new [CommonMark](https://en.wikipedia.org/wiki/Markdown) (Markdown) file to folder [searx/infopage/en](https://github.com/searxng/searxng/tree/master/searx/infopage/en).

```
# Title name

Lorem ipsum ..
```

Does this meets to your needs? .. can we close the issue or do you have some hints for us why it not meets to your needs / thanks!

**Comment by miaowmint** [comment]
> Instead of links and text in the footer, I want suggest the _info-pages_.
> 
> Since #930 you can add a new (info) page that will be shown online next to the "About" page.
> 
> Add a new [CommonMark](https://en.wikipedia.org/wiki/Markdown) (Markdown) file to folder [searx/infopage/en](https://github.com/searxng/searxng/tree/master/searx/infopage/en).
> 
> ```
> # Title name
> 
> Lorem ipsum ..
> ```
> 
> Does this meets to your needs? .. can we close the issue or do you have some hints for us why it not meets to your needs / thanks!

I tried your advice, and I have to say it's a good feature, but....
In fact, if the site is deployed to Chinese mainland's server, it will be required to put on record, and a hyperlink to the filing management system needs to be placed in the footer of the home page of the site, and it must be placed in the footer, not at the top of the page or anywhere else.This is my actual need.
I know this is a very niche requirement, so if you are not going to implement this function, can I achieve this effect by simply modifying the source code? that is, whether I can modify the footer information directly by modifying the code?

**Comment by return42** [comment]
> can I achieve this effect by simply modifying the source code? 

sure, this is what "open source" stands for :-) .. create a (github) fork and modify it to your needs .. if you think its worth to merged upstream into the SearXNG master branch send us a PR.

We always happy to see contribution .. even if we can't merge everything, every PR is also a valuable inspiration for new ideas :+1:  go on and feel welcome .. 

I have a link you should put under your pillow, the [Development Quickstart](https://docs.searxng.org/dev/quickstart.html).

The footer is build in the jinja template `base.html` ..

https://github.com/searxng/searxng/blob/7bf4e8d12d1d0ee53bf71f7c3a4010ef936f25d9/searx/templates/simple/base.html#L64-L76

**Comment by miaowmint** [comment]
You're right about this is what "open source" stands for. Although my technical skills are not enough to support me to add to this great open source project, this issue also makes sense. I hope that if someone has the same needs as me, he can find this issue. Thank you very much for taking the time to help me answer my questions, and then I will close this issue.
Thank you very much.
