### ISSUE TITLE
SEARX_SETTINGS_PATH fallback is ignored for uwsgi

### ISSUE THREAD

**Issue by SuperSandro2000** [searxng/searxng#1519]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

7bf4e8d12d1d0ee53bf71f7c3a4010ef936f25d9
**How did you install SearXNG?**

NixOS module
**What happened?**

``SEARX_SETTINGS_PATH`` is being ignored when running via uwsgi vessel and the default config is being used. Using SEARXNG_SETTINGS_PATH instead works.
**How To Reproduce**

Run searx via uwsgi and supply the config only via SEARXNG_SETTINGS_PATH.
**Expected behavior**

**Screenshots & Logs**

```
Jul 17 21:18:12 hydrogen uwsgi[4009531]: DAMN ! worker 1 (pid: 42032) died :( trying respawn ...
Jul 17 21:18:12 hydrogen uwsgi[4009531]: worker respawning too fast !!! i have to sleep a bit (2 seconds)...
Jul 17 21:18:14 hydrogen uwsgi[4009531]: Respawned uWSGI worker 1 (new pid: 43476)
Jul 17 21:18:14 hydrogen uwsgi[43476]: SEARXNG_SETTINGS_PATH uses value from SEARX_SETTINGS_PATH
Jul 17 21:18:14 hydrogen uwsgi[43476]: 2022-07-17 21:18:14,905 ERROR:searx: git is not found, fallback to the default version
Jul 17 21:18:14 hydrogen uwsgi[43476]: 2022-07-17 21:18:14,991 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
Jul 17 21:18:14 hydrogen uwsgi[43476]: cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
Jul 17 21:18:14 hydrogen uwsgi[43476]: 2022-07-17 21:18:14,994 ERROR:searx.webapp: server.secret_key is not changed. Please use something else instead of ultrasecretkey.
Jul 17 21:18:15 hydrogen uwsgi[4009531]: DAMN ! worker 1 (pid: 43476) died :( trying respawn ...
Jul 17 21:18:15 hydrogen uwsgi[4009531]: Respawned uWSGI worker 1 (new pid: 43615)
Jul 17 21:18:15 hydrogen uwsgi[43615]: SEARXNG_SETTINGS_PATH uses value from SEARX_SETTINGS_PATH
Jul 17 21:18:15 hydrogen uwsgi[43615]: 2022-07-17 21:18:15,928 ERROR:searx: git is not found, fallback to the default version
Jul 17 21:18:15 hydrogen systemd[1]: Stopping uwsgi.service...
``` 

**Additional context**

**Comment by dalf** [comment]
Is there a NixOS package for SearXNG? or did you use the [searx package](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/servers/web-apps/searx/default.nix#L71)?

---

Reading the code, it seems the issue can be fixed by moving this code
https://github.com/searxng/searxng/blob/a983db022954b302f12640c7b3f5c3a6ce697101/searx/settings_defaults.py#L230-L234
in this function:
https://github.com/searxng/searxng/blob/a983db022954b302f12640c7b3f5c3a6ce697101/searx/settings_loader.py#L123

**Comment by SuperSandro2000** [comment]
> Is there a NixOS package for SearXNG? or did you use the [searx package](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/servers/web-apps/searx/default.nix?rgh-link-date=2022-07-19T21%3A57%3A47Z#L71)?

Yes, I am using it https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/web-apps/searxng/default.nix

**Comment by return42** [comment]
> Reading the code, it seems the issue can be fixed by moving this code

@dalf to me the origin of the issue and the suggested bugfix is not 100% clear .. if you have time could you  implement a PR with the bugfix / thanks!
