### ISSUE TITLE
Bug: google news engine

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#154]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

7ef33c91e057defde55cc90d4123f284910723d9

**How did you install SearXNG?**
docker

**How To Reproduce**
`!google_news time` crashes whatever the search language is

**Technical report**

Error
  * Error: KeyError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/google_news.py:97`
  * Function: `request`
  * Code: `if lang_info['hl'] == 'en':`

Checker
  * simple: `KeyError `,
  * lang_fr: `KeyError `,
  * lang_en: `KeyError `,

**Comment by return42** [comment]
I will have a look ...
