### ISSUE TITLE
`lang` Parameter is ignored during search

### ISSUE THREAD

**Issue by rad4day** [searxng/searxng#1541]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.07.23-3ff576ea

**How did you install SearXNG?**
Official Docker Image

**What happened?**
The [documentation](https://docs.searxng.org/dev/search_api.html) states that the query parameter `lang` adjusts the language setting of the search, which it doesn't. The correct parameter (after intercepting a post request to figure that out) seems to be `language`. This currently affects not only my private instance but also public instances like https://searx.tiekoetter.com.

**How To Reproduce**
Append a &lang=de GET query parameter, POST hasn't been tested but will likely be handled in the same way.

**Expected behavior**
?q=test&lang=de should set the search language to German. Which it doesn't.

**Screenshots & Logs**

Example search which doesn't work as of 2022-07-23: https://searx.tiekoetter.com/search?q=test&lang=de 
Example search which does work as of 2022-07-23 but is contrary to the documentation: https://searx.tiekoetter.com/search?q=test&language=de

**Additional context**

I suspect this to just be a documentation error. I ran into this as we were developing a searxng integration for a discord bot, and relied on the documentation to be correct. This makes it rather hard for me to decide what the fix should be, otherwise this would have been a PR.

**Comment by return42** [comment]
@rad4day thanks for pointing out .. I updated the docs in 

- https://github.com/searxng/searxng/pull/1548
