### ISSUE TITLE
Bug: woxikon.de synonyme engine

### ISSUE THREAD

**Issue by return42** [searxng/searxng#1543]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: current master

**How did you install SearXNG?**

    make run

**What happened?**

```
ERROR   searx.engines.woxikon.de synon: requests exception (search duration : 0.4816262270014704 s, timeout: 5.0 s) : Client error '404 Not Found' for url 'https://synonyme.woxikon.de/synonyme/foo.php'
For more information check: https://httpstatuses.com/404
Traceback (most recent call last):
  File "searx/search/processors/online.py", line 143, in search
    search_results = self._search_basic(query, params)
  File "searx/search/processors/online.py", line 127, in _search_basic
    response = self._send_http_request(params)
  File "searx/search/processors/online.py", line 96, in _send_http_request
    response = req(params['url'], **request_args)
  File "searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "searx/network/network.py", line 287, in call_client
    raise e
  File "searx/network/network.py", line 274, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
  File "SearXNG/searx/network/network.py", line 247, in patch_response
    raise_for_httperror(response)
  File "searx/network/raise_for_httperror.py", line 72, in raise_for_httperror
    resp.raise_for_status()
  File "local/py3/lib/python3.8/site-packages/httpx/_models.py", line 1508, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://synonyme.woxikon.de/synonyme/foo.php'
```

**How To Reproduce**

query: ``!woxikon.de_synonyme foo``

**Expected behavior**

The URL https://synonyme.woxikon.de/synonyme/foo.php seems valid

**Additional context**

@allendema could you have a look about the issue? / I cherry picked the engine from your branch in https://github.com/searxng/searxng/pull/197

**Technical report**

```
Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('404', 'Not Found', 'synonyme.woxikon.de')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`
```

**Comment by allendema** [comment]
The site expects a word in German, so with your query "foo" the site finds nothing.
Same goes for Duden engine ```!duden amazing```.


Try them with: ```!woxi !duden super```  and they returns results.


So using ```raise_for_httperror``` from https://docs.searxng.org/dev/engine_overview.html#id21 would be an alternative.

**Comment by return42** [comment]
Hi @allendema, thanks a lot for your hints!

> So using ```raise_for_httperror``` from https://docs.searxng.org/dev/engine_overview.html#id21 would be an alternative.

Do you like to send a PR? .. otherwise I can do it.

**Comment by allendema** [comment]
Hi @return42, would appreciate it if you would do that.

**Comment by return42** [comment]
@allendema I fixed issue in #1681 .. would you give it a try and give your feedback to the PR / thanks!

**Comment by return42** [comment]
@allendema I'm in a  run :smile_cat: .. same with PR #1682 that fixes German duden.

**Comment by allendema** [comment]
They lgtm! Thanks
