### ISSUE TITLE
Bug: google images engine

### ISSUE THREAD

**Issue by DavidNativ** [searxng/searxng#1551]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.25

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by return42** [comment]
Without filling the form we do not know what you want to tell us .. closing, its duplicate https://github.com/searxng/searxng/search?q=%22Bug%3A+google+images+engine%22&type=issues
