### ISSUE TITLE
Preffered laguage seemingly acts as a filter instead of a preference

### ISSUE THREAD

**Issue by Lalarian** [searxng/searxng#1557]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

I installed searxng-docker

**What happened?**

My searched find very few results and often don't have any results. The only configured search engine for 'general searches' is Google. But while Google itself (from their own site) finds a lot, there's very little and often nothing at all in my personal Searxng interface: '

Entschuldigung!

Es konnten keine Suchergebnisse gefunden werden. Bitte nutze einen anderen Suchbegriff, oder suche das gewünschte in einer anderen Kategorie.
"
I noticed, that this is very dependent ind the configured preferred 'search language'.

**How To Reproduce**

Example1: Search for 'kootenays'. There will be no result found, unless I set language to "Englisch (Canada)".
Example2: Search for 'searxng github' There will be no result found, unless I set language to "German (Austria)".

**Expected behavior**

All matching results should always be found, and not only after setting some specific language, of which I don't evenknow it would be the right one before finally finding something. The language settings is about 'preference', so it should effect the order of matches, but not the visibility.

**Screenshots & Logs**

Searching for Kootenays with preferred language set to 'English' = no result
![kootenays-englisch](https://user-images.githubusercontent.com/5146616/180883855-875fa60d-28ab-4098-aa00-66a3dcc9f082.jpg)

Searching for Kootenays with preferred language set to 'German' = no result
![kootenays-deutsch](https://user-images.githubusercontent.com/5146616/180883925-378854a6-f731-437a-bd99-4557ad469e81.jpg)

Searching for Kootenays with preferred language set to 'English(Canada)' = working!
![kootenays-englisch(Kanada)](https://user-images.githubusercontent.com/5146616/180883963-e92840fe-e437-4e2d-94ea-b1dc034fd3c0.jpg)

I mean this is not how a search engine is supposed to work!? I cannot always know which language the potentially matching sites are written in.

Log:

> docker-compose logs -f
Attaching to searxng, caddy, redis
caddy      | {"level":"info","ts":1658788421.716923,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy      | {"level":"warn","ts":1658788421.7372067,"logger":"caddyfile","msg":"Unnecessary header_up X-Forwarded-Proto: the reverse proxy's default behavior is to pass headers to the upstream"}
caddy      | {"level":"warn","ts":1658788421.7574654,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
caddy      | {"level":"warn","ts":1658788421.780989,"logger":"admin","msg":"admin endpoint disabled"}
caddy      | {"level":"info","ts":1658788421.7842596,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x39c5f40"}
caddy      | {"level":"info","ts":1658788421.7856617,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
caddy      | {"level":"info","ts":1658788421.786327,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
caddy      | {"level":"info","ts":1658788421.8036768,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["myip"]}
caddy      | {"level":"info","ts":1658788421.8066714,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
caddy      | {"level":"info","ts":1658788421.8392107,"logger":"tls","msg":"finished cleaning storage units"}
caddy      | {"level":"info","ts":1658788421.8440053,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
caddy      | {"level":"info","ts":1658788421.847099,"msg":"serving initial configuration"}
searxng    | SearXNG version 2022.07.19-a983db02
searxng    | Use existing /etc/searxng/uwsgi.ini
searxng    | Use existing /etc/searxng/settings.yml
searxng    | Listen on 0.0.0.0:8080
searxng    | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng    | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng    | *** Starting uWSGI 2.0.20 (32bit) on [Mon Jul 25 22:33:48 2022] ***
searxng    | compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
searxng    | os: Linux-5.10.60-sunxi #21.08.2 SMP Tue Sep 14 16:28:44 UTC 2021
searxng    | nodename: 0888d86177a0
searxng    | machine: armv7l
searxng    | clock source: unix
searxng    | pcre jit disabled
searxng    | detected number of CPU cores: 4
searxng    | current working directory: /usr/local/searxng
searxng    | detected binary path: /usr/sbin/uwsgi
searxng    | chdir() to /usr/local/searxng/searx/
searxng    | your memory page size is 4096 bytes
searxng    | detected max file descriptor number: 1048576
searxng    | building mime-types dictionary from file /etc/mime.types...1323 entry found
searxng    | lock engine: pthread robust mutexes
searxng    | thunder lock: disabled (you can enable it with --thunder-lock)
searxng    | *** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
searxng    | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
searxng    | Python version: 3.10.4 (main, Apr 30 2022, 16:49:16) [GCC 11.2.1 20220219]
searxng    | Python main interpreter initialized at 0xb697e000
searxng    | python threads support enabled
searxng    | your server socket listen backlog is limited to 100 connections
searxng    | your mercy for graceful operations on workers is 60 seconds
searxng    | mapped 523040 bytes (510 KB) for 16 cores
searxng    | *** Operational MODE: preforking+threaded ***
searxng    | added /usr/local/searxng/ to pythonpath.
searxng    | spawned uWSGI master process (pid: 7)
searxng    | spawned uWSGI worker 1 (pid: 10, cores: 4)
searxng    | spawned uWSGI worker 2 (pid: 11, cores: 4)
searxng    | spawned 4 offload threads for uWSGI worker 1
searxng    | spawned uWSGI worker 3 (pid: 16, cores: 4)
searxng    | spawned uWSGI worker 4 (pid: 21, cores: 4)
searxng    | spawned 4 offload threads for uWSGI worker 2
searxng    | cache sweeper thread enabled
searxng    | spawned 4 offload threads for uWSGI worker 3
searxng    | spawned 4 offload threads for uWSGI worker 4
searxng    | 2022-07-25 22:34:01,803 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
redis      | 1:C 25 Jul 2022 22:33:43.712 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
searxng    | 2022-07-25 22:34:01,803 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
redis      | 1:C 25 Jul 2022 22:33:43.712 # Redis version=7.0.4, bits=32, commit=00000000, modified=0, pid=1, just started
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
redis      | 1:C 25 Jul 2022 22:33:43.712 # Configuration loaded
searxng    | 2022-07-25 22:34:01,803 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
redis      | 1:M 25 Jul 2022 22:33:43.723 * monotonic clock: POSIX clock_gettime
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
redis      | 1:M 25 Jul 2022 22:33:43.725 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
searxng    | 2022-07-25 22:34:01,812 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
redis      | 1:M 25 Jul 2022 22:33:43.732 * Running mode=standalone, port=6379.
searxng    | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
redis      | 1:M 25 Jul 2022 22:33:43.732 # Server initialized
searxng    | WSGI app 0 (mountpoint='') ready in 24 seconds on interpreter 0xb697e000 pid: 21 (default app)
redis      | 1:M 25 Jul 2022 22:33:43.733 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
searxng    | WSGI app 0 (mountpoint='') ready in 24 seconds on interpreter 0xb697e000 pid: 11 (default app)
redis      | 1:M 25 Jul 2022 22:33:43.737 * Ready to accept connections
searxng    | WSGI app 0 (mountpoint='') ready in 24 seconds on interpreter 0xb697e000 pid: 10 (default app)
searxng    | WSGI app 0 (mountpoint='') ready in 25 seconds on interpreter 0xb697e000 pid: 16 (default app)
searxng    | 2022-07-25 22:34:15,828 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError
searxng    | 
searxng    | The above exception was the direct cause of the following exception:
searxng    | 
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng    |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng    |     guest_client_id = get_client_id()
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng    |     response = http_get(app_js_url)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout
searxng    | 2022-07-25 22:34:15,942 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError
searxng    | 
searxng    | The above exception was the direct cause of the following exception:
searxng    | 
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng    |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng    |     guest_client_id = get_client_id()
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng    |     response = http_get(app_js_url)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout
searxng    | 2022-07-25 22:34:15,939 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError
searxng    | 
searxng    | The above exception was the direct cause of the following exception:
searxng    | 
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng    |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng    |     guest_client_id = get_client_id()
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng    |     response = http_get(app_js_url)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout
searxng    | 2022-07-25 22:34:16,253 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError
searxng    | 
searxng    | The above exception was the direct cause of the following exception:
searxng    | 
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng    |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng    |     guest_client_id = get_client_id()
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng    |     response = http_get(app_js_url)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout

**Additional context**

Thank you! :)

**Comment by tiekoetter** [comment]
@Lalarian Could you check if the error is on https://searx.tiekoetter.com ?

If it isn't than this is fixed in https://github.com/searxng/searxng/pull/1556

**Comment by Lalarian** [comment]
Hello! I just tried, with mixed results (which overall where better than mine, as there always where results and it was much faster than my search):
First time i was searching for 'kooteneyas' in German, there only where two results. After searching repeatedly it went up to three. Ir was same for 'general english', while using 'Englisch(Canada) had three results from the beginning.

I don't really know what to make of this ... Maybe it's related to this? Possibly there are race conditions, because of the original search engines' response time? It was very obvious that my search was extremely slow compared to your's and I noticed the soundcloud timeout issue in the logs (despite I am not using soundcloud). But I think it should throw an 'timeout error' in the web interface too..

**Comment by tiekoetter** [comment]
Normally this shouldn't affect another engine. You can remove the soundcloud engine from your settings.yml if you don't want it to be loaded at all.

Hopefully when my PR is merged you can pull the new docker image and use the google engine normally.

**Comment by Lalarian** [comment]
I just did:
'docker-compose pull
docker-compose down
docker-compose up'

Could not see if there already was a newer version or not, but it didn't change the behaviour of my search, yet.
Looking forward to your patch, thank you :)
Edit: Will try removing soundcloud now.

**Comment by tiekoetter** [comment]
You can check if you run the newest version by looking at the newest commit hash in the SearXNG repository (currently 747cf1a246df587aeb3b6b175c315ef0b9612dc4) and checking your instances footer (there should be something like `2022.07.25-747cf1a2` in it)

**Comment by Lalarian** [comment]
OK.
I just noticed there where two settings files in /usr/local/searxng-docker/searxn suddenly .. I did not edit settings.yml manually, yet.
From the creation date it seems, that the 'docker-compose pull' update I did right now, downloaded a new settings file and named it settings.yml.new:

> -rw-r--r-- 1 root root   471 22. Jul 10:04 settings.yml
> -rw-r--r-- 1 root root 52007 26. Jul 00:54 settings.yml.new
 
No I wonder which is being used .. will it even be utilized with the name as 'settings.yml.new' on container creation?

**Comment by tiekoetter** [comment]
No only the file `settings.yml` will be read.

**Comment by Lalarian** [comment]
OK, thank you again. I think I will rename the files and try the new one, as it already has a lot of engine specific configuration examples in there.

**Comment by Lalarian** [comment]
Well, this didn't work out. Trying to start with the renamed settings.yml.new, the webinterface wasn't even reachable.

So I just added some lines to the original settings.yml, still trying to completely disable the error provoking soundcloud-search:
 

> 
  - name: soundcloud
    engine: soundcloud
    disabled: true

The containers start, but trying to search just gives:
"Internal Server Error" now... this is my full settings.yml:

```
 # see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "mykey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0

  - name: soundcloud
    shorcut: sc
    engine: soundcloud
    disabled: true
```

When commenting out the 4 lowest lines, it's running, but with that comes the soundcloud timeout error.

**Comment by return42** [comment]
> When commenting out the 4 lowest lines, it's running, but with that comes the soundcloud timeout error.

You placed the soundcloud setup in the `redis:` section, you need add a `engines:` section 

https://github.com/searxng/searxng/blob/747cf1a246df587aeb3b6b175c315ef0b9612dc4/searx/settings.yml#L264

this should do ..

```yaml

engines:

  - name: soundcloud
    disabled: true
```

> Well, this didn't work out. Trying to start with the renamed settings.yml.new, the webinterface wasn't even reachable.

.. and always be careful with the indentation in YAML files, in this YAML file one indentation-level  consists always of two spaces / don't mix with three or one space indentations!

**Comment by Lalarian** [comment]
Thank you! It's starting like this!
Strangely it doesn't seem to have an effect on the soundcloud  timeout error:

>  WSGI app 0 (mountpoint='') ready in 24 seconds on interpreter 0xb69439e0 pid: 21 (default app)
searxng    | 2022-07-26 06:06:54,881 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError
searxng    | 
searxng    | The above exception was the direct cause of the following exception:
searxng    | 
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng    |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng    |     guest_client_id = get_client_id()
searxng    |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng    |     response = http_get(app_js_url)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout
searxng    | 2022-07-26 06:06:54,989 ERROR:searx.engines.soundcloud: Fail to initialize
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng    |     raise TimeoutError()
searxng    | concurrent.futures._base.TimeoutError

And this repeats four times.
(Of course I still don't know for sure if this soundcloud error even is related to the searching issues I have using Google, as in topic.)

**Comment by return42** [comment]
> Of course I still don't know for sure if this soundcloud error even is related to the searching issues I have using Google, as in topic.

No it isn't .. 

> `2022-07-26 06:06:54,881 ERROR:searx.engines.soundcloud: Fail to initialize`

.. this is the initialization of soundcloud:

https://github.com/searxng/searxng/blob/50ec821e8c5b099947d657722b1879fc8c03bcfa/searx/engines/soundcloud.py#L66-L69

The init function is called, even if you disable the engine by default; when the user activates the engine e.g. by typing `!soundcloud Maceo Parker` the search request goes to soundcloud.

**Comment by return42** [comment]
@Lalarian back to the topic you asked for ..

@tiekoetter fixed a google issue in https://github.com/searxng/searxng/pull/1556 .. from your [comment above](https://github.com/searxng/searxng/issues/1557#issuecomment-1194733806):

> First time i was searching for 'kooteneyas' in German, there only where two results. After searching repeatedly it went up to three. Ir was same for 'general english', while using 'Englisch(Canada) had three results from the beginning.

This is normal in google results, the first page includes a lot of advertising, I tried to explain it in this https://github.com/searxng/searxng/pull/1556#issuecomment-1195016214 (read the "About XPath" section).

Tip: to test explicit the google engine use the [!bang syntax](https://docs.searxng.org/user/index.html#search-syntax) to select the google engine (see "Shortcuts" [here](https://docs.searxng.org/admin/engines/configured_engines.html)):

    !go kootenays

I merged the PR in master and updated my instance, try it:

- https://darmarit.org/searx/search?q=%21go%20kootenays&language=de-DE
- https://searx.tiekoetter.com/search?q=%21go+kootenays&language=de-DE

From my point of view the topic of this issue is solved .. right?

**Comment by Lalarian** [comment]
Just pulled the recent version.
It seems to be working better now, besides some timeouts, but that's another topic.
Thank you all! :)
