### ISSUE TITLE
Add a option to sort files by seed , files size etc

### ISSUE THREAD

**Issue by BigDogg99** [searxng/searxng#1558]
**Is your feature request related to a problem? Please describe.**
when I search for files results are newest added files with less seeds

**Describe the solution you'd like**
add a option to sort search by  no of seeder , file size and time 

**Describe alternatives you've considered**
no alternative just have open website search again then sort then download

**Additional context**
thanks for your work

**Comment by julianfairfax** [comment]
This would be nice
