### ISSUE TITLE
i cant search for anything

### ISSUE THREAD

**Issue by MaJoRX0** [searxng/searxng#1561]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.26-50ec821e
**How did you install SearXNG?**

install:  searxng-docker
**What happened?**

it tooks about 5min to launch idk if that a normal thing or not but after that I cant search for anything it just shows me the error
Error! Engines cannot retrieve results.
brave ( [timeout](https://192.168.100.102/stats?engine=brave) )
duckduckgo ( [timeout](https://192.168.100.102/stats?engine=duckduckgo) )
google ( [timeout](https://192.168.100.102/stats?engine=google) )
qwant ( [timeout](https://192.168.100.102/stats?engine=qwant) )
wikidata ( [timeout](https://192.168.100.102/stats?engine=wikidata) )
wikipedia ( [timeout](https://192.168.100.102/stats?engine=wikipedia) )
Please, try again later or find another SearXNG instance. ([Public instances](https://searx.space/))
**Expected behavior**
im trying to search in searxng but it shows me nothing and with the error Error! Engines cannot retrieve results.
**Screenshots & Logs**
[photo for the search result](https://prnt.sc/lzsxo9k49na5)
[photo for the debug1](https://prnt.sc/9lYScw3Zx5ro)
[photo for the debug1](https://prnt.sc/ZnjzF7k5cBW3)

**Comment by return42** [comment]
> install: searxng-docker

Seems your container has no outgoing internet connection .. did you see this issue https://github.com/searxng/searxng-docker/issues/29#issuecomment-1186406721 in the searxng-docker project?

**Comment by dalf** [comment]
Also, can you check your DNS configuration?

**Comment by wickedyoda** [comment]
Sounds like you have problems with your docker and network setup. I was reviewing your issue https://github.com/SelfhostedPro/Yacht/issues/505 as well. You are saying you can't reach Yacht from a lan assigned IP but can reach it using 127.0.0.1 which leads me to think of a misconfiguration of your network, container, or host system in some way. Otherwise, maybe a firewall blocking it, Ubuntu? Maybe the built-in firewall?

**Comment by MaJoRX0** [comment]
> Sounds like you have problems with your docker and network setup. I was reviewing your issue [SelfhostedPro/Yacht#505](https://github.com/SelfhostedPro/Yacht/issues/505) as well. You are saying you can't reach Yacht from a lan assigned IP but can reach it using 127.0.0.1 which leads me to think of a misconfiguration of your network, container, or host system in some way. Otherwise, maybe a firewall blocking it, Ubuntu? Maybe the built-in firewall?


I'm using ubuntu server OS I don't think there an built in firewall I'm not sure, but both mineos and cockpit are working fine with me I can reach them fine no problems, I tested my network in the server side its working fine I really don't know what wrong
![image](https://user-images.githubusercontent.com/45786523/181188317-9b4edfd2-83b6-4d00-b666-3e32cb3494b1.png)

> Seem

**Comment by MaJoRX0** [comment]
> Also, can you check your DNS configuration?

which side ?

**Comment by MaJoRX0** [comment]
well i just double check my firewall even when I type `ufw status` it shows me its inactive but I typed `ufw disable` to make sure and it working fine :) thanks guys
