### ISSUE TITLE
Searxng search timeout after installing pi-hole

### ISSUE THREAD

**Issue by MaJoRX0** [searxng/searxng#1563]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Repository: https://github.com/searxng/searxng-docker
Branch: master
Version: 2022.07.26-50ec821e
**How did you install SearXNG?**

install:  searxng-docker
**What happened?**

**Expected behavior**
Hi guys so i installed searxng in my local server and its working fine but after i installed pi-hole i had to stop resolved service and set custom DNS in resolve.conf file, after that searxng search wont work everytime i try to seatch for anything it just shows me

Error Engines cannot retrieve results

How i can fix this? + how I can change the caddy port? 
**Screenshots & Logs**
[photo for the search result](https://prnt.sc/lzsxo9k49na5)
[log](https://prnt.sc/iNE3jXYMBdrq)

**Comment by TahaDuman** [comment]
how did you fixed it
