### ISSUE TITLE
Ignore autocomplete_min on queries that start with !

### ISSUE THREAD

**Issue by alpe12** [searxng/searxng#1566]
**Is your feature request related to a problem? Please describe.**
If I start a search with ! and some letter, I expect it to suggest autocomplete options like !imdb. It doesn't. Apparently it respect autocomplete_min.

**Describe the solution you'd like**
An option to make queries that start with ! ignore autocomplete_min. Or to make it default.

**Describe alternatives you've considered**
Reducing autocomplete_min.

Thanks anyway. 👍

**Comment by return42** [comment]
> If I start a search with ! and some letter, I expect it to suggest autocomplete options like !imdb.

FYI: As workaround; you can type the bang behind your search term

![grafik](https://user-images.githubusercontent.com/554536/230930922-11d53ab6-8cd5-4e09-8c18-84e7feb5e397.png)
