### ISSUE TITLE
Bing news returns results in English when language set to Italian

### ISSUE THREAD

**Issue by ononoki1** [searxng/searxng#1567]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.07.26-50ec821e

**How did you install SearXNG?**
install SearXNG using the official wiki

**What happened?**
Bing news from SearXNG returns results in English and German when it is supposed to return them in Italian according to setting.

**How To Reproduce**
Bing news from SearXNG returns results in English: https://search.ononoki.org/search?q=!bin+meloni&category_news=on&language=it-IT
Official Bing news returns results in Italian: https://www.bing.com/news/search?q=meloni&setlang=it

**Expected behavior**
Bing news from SearXNG returns results in Italian.

**Comment by return42** [comment]
Hi @ononoki1 AFAIK PR #1560 should fix the issue, would you give it a try / thanks!

-  https://github.com/searxng/searxng/pull/1560

**Comment by ononoki1** [comment]
> Hi @ononoki1 AFAIK PR https://github.com/searxng/searxng/pull/1560 should fix the issue, would you give it a try / thanks!

Yes it solved this issue.
