### ISSUE TITLE
SearXNG not searching Google for responses 

### ISSUE THREAD

**Issue by gromans35614** [searxng/searxng#1600]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.19-a983db02-dirty

SearXNG not getting results from google when performing a search. The Google search engine is selected as part as the engines to use.

**Comment by return42** [comment]
Use use_mobile_ui: true
See https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

Past open issues: https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+is%3Aclosed

**Comment by gromans35614** [comment]
Thank you Return42. I've done what you suggested, changed the use_mobile_ui: true with NO JOY. 
use_mobile_ui: (default: false)
Enables to use mobile endpoint to bypass the google blocking (see [#159](https://github.com/searxng/searxng/issues/159)). On the mobile UI of Google Search, the button More results is not affected by Google rate limiting and we can still do requests while actively blocked by the original Google search. By activate use_mobile_ui this behavior is simulated by adding the parameter

engine: google
    shortcut: go
    # see https://docs.searxng.org/src/searx.engines.google.html#module-searx.e>
    use_mobile_ui: true
    # additional_tests:
    #   android: *test_android

  # - name: google italian
  #   engine: google
  #   shortcut: goit
  #   use_mobile_ui: false
  #   language: it

 - name: google mobile ui
   engine: google
   shortcut: gomui
   use_mobile_ui: true

**Comment by return42** [comment]
>  with NO JOY.

TBH its not a joy to read your information-less and miss-formatted comment ..  sorry, my glass ball is currently in the repair / can't help.

**Comment by gromans35614** [comment]
Not sure what happened with the format of the post, but thank you for your reply. Hope you get your crystal ball out of the shop soon. 

I have the following set,

**engine: google
shortcut: go
use_mobile_ui: true


name: google mobile ui
engine: google
shortcut: gomui
use_mobile_ui: true

**Comment by dualfade** [comment]
This seams to be working for me. 

```yaml
engine:
  google:
    use_mobile_ui: true
```

    !go site:github.com search_query
