### ISSUE TITLE
DuckDuckGo Videos/News/Maps

### ISSUE THREAD

**Issue by emendoza2** [searxng/searxng#1602]
**Working URL to the engine**

https://duckduckgo.com/?q=news&t=h_&iar=news&ia=news -- a search for "news"
https://duckduckgo.com/?q=videos&t=h_&iax=videos&ia=videos -- a search for "videos"
https://duckduckgo.com/?q=maps&t=h_&ia=web&iaxm=maps -- a search for "maps"

**Why do you want to add this engine?**

It's DuckDuckGo and this specific news category of it is not yet implemented in SearX.

**Features of this engine**

DuckDuckGo supposedly doesn't track its users and the news category is fairly reliable in my experience with another library (linked below).

**How can SearXNG fetch the information from this engine?**

news, map, videos

**Additional context**

It would be great to be able to expand the number of news search engines SearX supports. At the very least, it would be nice to have news. I would love to submit a PR myself, but I wouldn't know how to implement or test it. Could someone point me in the right direction for something like a template for creating new engines?

**Comment by emendoza2** [comment]
Whoops, forgot to link to the library that does the searching:
https://pypi.org/project/duckduckgo-search/ 

Lines 323-625 in the [source](https://github.com/deedy5/duckduckgo_search/blob/main/duckduckgo_search.py) cover the scraping process. Is this breakage-prone? If so, does SearX allow simply importing the lib and using the results from there?

**Comment by julianfairfax** [comment]
This would be nice.

**Comment by julianfairfax** [comment]
Can something similar be done for Startpage Images/Videos/News?

**Comment by return42** [comment]
> Can something similar be done for Startpage Images/Videos/News?

Its on my ToDo list since a long time .. but before we need to fix startpage (the fix is on the way https://github.com/searxng/searxng/pull/1667/commits/964d24134d8f589a278584f6d175905232a18486)

**Comment by julianfairfax** [comment]
> > Can something similar be done for Startpage Images/Videos/News?
> 
> Its on my ToDo list since a long time .. but before we need to fix startpage (the fix is on the way [964d241](https://github.com/searxng/searxng/commit/964d24134d8f589a278584f6d175905232a18486))

That's great! I know it doesn't really make a difference when using SearXNG, but I still want to stick to private engines. But if I do that I only have DDG and Qwant in images and only Qwant in both videos and news (excluding Wikinews). So I'm looking forward to this!

PS: I don't have any issues with Startpage, but Brave on the other hand...

I actually got it to work yesterday, maybe once. It's reliability is consistently low, and it usually just returns `Error! Engines cannot retrieve results: brave ( [Suspended: too many requests](https://searx.namejeff.xyz/searx/stats?engine=brave) )`. This is on a public instance though.

**Comment by asenov** [comment]
FYI the API works very well, the only downside is that there is no paging option.
https://github.com/deedy5/duckduckgo_search/blob/main/duckduckgo_search/ddg_images.py#L15

Supports up to 1000 results https://github.com/deedy5/duckduckgo_search/blob/main/duckduckgo_search/ddg_images.py#L48

**Comment by julianfairfax** [comment]
Has there been any progress on this? DuckDuckGo Videos/News/Maps and Startpage Images/Videos/News would be very welcome

**Comment by return42** [comment]
> Has there been any progress on this? 

No, sorry, I haven't had time yet for .. but pull requests are welcome :-) 

> Can something similar be done for Startpage Images/Videos/News?

Its the same with startpage .. first we need to solve the CAPTCHA issue https://github.com/searxng/searxng/issues/1081 .. I have tried a lot but I have not found a solution for it yet.

**Comment by julianfairfax** [comment]
> > Has there been any progress on this?
> 
> No, sorry, I haven't had time yet for .. but pull requests are welcome :-)

I might look into that at some point. If it's something I can manage.
> 
> > Can something similar be done for Startpage Images/Videos/News?
> 
> Its the same with startpage .. first we need to solve the CAPTCHA issue #1081 .. I have tried a lot but I have not found a solution for it yet.

Oh, that's unfortunate.

What about Brave? They also have images/videos/news

**Comment by return42** [comment]
> What about Brave? They also have images/videos/news

so many opportunities, so little time .. we are a small team, SearXNG thrives on the support of the community .. contributions are welcome :+1:

**Comment by Bnyro** [comment]
@julianfairfax For Brave, you can test https://github.com/searxng/searxng/pull/2599
