### ISSUE TITLE
Bug: alexandria engine

### ISSUE THREAD

**Issue by DeAlde** [searxng/searxng#1603]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.26

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 35
  * Parameters: `('500', 'Internal Server Error', 'api.alexandria.org')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
We can not reproduce the error, please answer the questions from the form.
