### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by vlape** [searxng/searxng#1606]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.01-7c9c1124

**How did you install SearXNG?**
searxng.sh install all
**What happened?**
Qwant engine indicates timeout randomly.

**How To Reproduce**
Perform searches

**Expected behavior**
No timeout

**Screenshots & Logs**
n/a

**Additional context**
Hosted on ubuntu on Amazon EC2. 

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 5
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Qwant engine indicates timeout randomly.

Seems not very often ..

> Percentage: 5

If you want to get rid, increase the `timeout` setting in the qwant engines / https://docs.searxng.org/admin/engines/settings.html?highlight=timeout#engine-settings
