### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Pratyay360** [searxng/searxng#1610]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.31-1fbb514a

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 20
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
This issue has reported many times: https://github.com/searxng/searxng/search?q=%22Bug%3A+google+engine%22&type=issues

The solution is always the same: `use_mobile_ui: true`
See https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

**Comment by atuleu** [comment]
Should not then just be enabled by default ?
