### ISSUE TITLE
Brave now allows multiple page searches, SearXNG should add this new feature immediately

### ISSUE THREAD

**Issue by Krando** [searxng/searxng#1612]
**Is your feature request related to a problem? Please describe.**
Brave is a great engine which combines the results from other engines as well as from it's own crawler which is large enough. Before, there was no pagination on Brave, e.g: if you searched for "football", you would get only one page. Now, Brave has added pagination and there is now more than one page of search results, you can go to the next one.

**Describe the solution you'd like**
The solution is very easy and is similar to that of Google and DuckDuckGO. The next page can be reached with the offset parameter. For example:

First page: here is the first page for the word "football" on brave: https://search.brave.com/search?q=football&source=web

Here is the second page: https://search.brave.com/search?q=football&offset=1&spellcheck=0

Here is the third page: https://search.brave.com/search?q=football&offset=2&spellcheck=0

You see what I am doing here? This 'offset' parameter is totally new and Brave has added it just recently. SearXNG should add it immediately without any delays, it should be very simple.

**Describe alternatives you've considered**
Nothing.

**Additional context**

![bravenextpage](https://user-images.githubusercontent.com/12466600/182831854-f4dd8849-f297-4994-8ff6-d8b4e6a169bb.png)

**Comment by Krando** [comment]
This feature is already available upon checking.

**Comment by return42** [comment]
> This feature is already available upon checking.

yes :-) was added in https://github.com/searxng/searxng/pull/1144
