### ISSUE TITLE
[Android][Results page][Search text box]: Enter/Next button on keyboard doesn't trigger search

### ISSUE THREAD

**Issue by PetbkA** [searxng/searxng#1613]
**OS:** LineageOS 17.1 (Android 10)
**Keyboards:**
1. [Jbak2](https://jbak2.ucoz.net/) 2.37;
2. AOSP 10.

**WebView:** [Bromite](https://www.bromite.org/system_web_view) 103.0.5060.140

**Browsers:**
1. [Berry](https://play.google.com/store/apps/details?id=jp.ejimax.berrybrowser&hl=en&gl=US) 3.61.42;
2. [Chrome](https://play.google.com/store/apps/details?id=com.android.chrome&gl=US) 104.0.5112.69.

**SearxNG instances:**
1. [PaulGO](https://paulgo.io/) (2022.07.26-50ec821e);
2. [Ononoki](https://search.ononoki.org/) (2022.08.01-7c9c1124).

New search doesn't start from the results page when called via keyboard's Enter/Next button. Here's the [video](https://user-images.githubusercontent.com/22843816/183000308-287c2b5b-6d51-4ce2-9a68-825057f07c53.mp4).

The problem is on Chromium-based browsers - everything's OK on e.g. Fennec 103.1.0

**Comment by catfluoride** [comment]
Can confirm on Brave as well.

**Comment by PetbkA** [comment]
**2022.08.13-00431906** - was this fixed? Seems that keyboard's _Next_ button has changed to _Go_, and it's OK now in Berry 3.62.10.2.

**Upd:** found out that I've accidentally downgraded WebView to Android 100.0.4896.127. That's why Berry has started to work OK. Issue still persists In Bromite 104.0.5112.63

**Comment by PetbkA** [comment]
**Android System WebView 103.0.5060.129 (from Google Play)** - reproduced. Guess something has been broken between this and 100.0.4896.127 (integrated in LineageOS 17.1)

**Comment by return42** [comment]
@PetbkA @catfluoride as far I can say this issue should be fixed by now / if not, please leaf a note to reopen the issue.
