### ISSUE TITLE
Marginalia

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1620]
**Working URL to the engine**

https://search.marginalia.nu/

**Why do you want to add this engine?**

It's a search engine that prioritizes non-commercial websites.

**Features of this engine**

Its good for discovering sites that you didn't know about and no SEO spam.

**How can SearXNG fetch the information from this engine?**

https://memex.marginalia.nu/projects/edge/api.gmi
The above page has all the details.

**Applicable category of this engine**

general

**Additional context**

Some Posts about marginalia on HN:
https://hn.algolia.com/?q=marginalia

**Comment by allendema** [comment]
Can you check if this works for you? https://github.com/allendema/searxng/commit/d1ee203a3608691e3a336b4f3a6b461c1a82db64

Changing index like "experimental", "blogs" etc. is also possible.

>  The 'index' parameter selects the search index, corresponding to the drop down next to the search field in the main GUI.

**Comment by ghost** [comment]
> Can you check if this works for you? [allendema@d1ee203](https://github.com/allendema/searxng/commit/d1ee203a3608691e3a336b4f3a6b461c1a82db64)
> 
> Changing index like "experimental", "blogs" etc. is also possible.
> 
> > The 'index' parameter selects the search index, corresponding to the drop down next to the search field in the main GUI.

I actually don't have a dev environment right now, so I can't check :(

**Comment by return42** [comment]
@allendema just send a PR and we all can have a look at your addition .. if you don't want to merge the addition right now, you can mark the PR as DRAFT.

**Comment by allendema** [comment]
@return42 I've now created a merge request.
