### ISSUE TITLE
sudo -H ./utils/searxng.sh install all {script errors out}

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#1622]
ERROR: linuxmint-20.3: nginx not yet implemented
ERROR: linuxmint-20.3: apache not yet implemented
ERROR: linuxmint-20.3: uWSGI not yet implemented
ERROR: linuxmint-20.3: pkg_install LXC_BASE_PACKAGES not yet implemented

```
Test SearXNG instance localy
----------------------------

Activate debug mode, start a minimal SearXNG service and debug a HTTP
request/response cycle.

WARN:  Do not enable debug in a production environment!
INFO:  try to enable debug mode ...
cd /usr/local/searxng/searxng-src
sed -i -e "s/debug: false/debug: true/g" "/etc/searxng/settings.yml"
INFO:  restart uWSGI service
ERROR: linuxmint-20.3: uWSGI not yet implemented
export SEARXNG_SETTINGS_PATH="/etc/searxng/settings.yml"
cd /usr/local/searxng/searxng-src
timeout 10 python searx/webapp.py &
sleep 3

****************************

INFO:  try to disable debug mode ...
cd /usr/local/searxng/searxng-src
sed -i -e "s/debug: true/debug: false/g" "/etc/searxng/settings.yml"
INFO:  restart uWSGI service
ERROR: linuxmint-20.3: uWSGI not yet implemented

*******************************************************

Should packages be installed? [YES/no] 
Yes

Install searxng.ini using socket at: /usr/local/searxng/run/socket
mkdir: cannot create directory ‘’: No such file or directory
INFO:  install (eval=1): /searxng.ini
INFO:  variant --> :socket
ERROR: /home/x/Downloads/searxng/utils/templates/searxng.ini:socket does not exists
ERROR: ... can't install /searxng.ini

******************************************


Install searxng.ini using socket at: /usr/local/searxng/run/socket
mkdir: cannot create directory ‘’: No such file or directory
INFO:  install (eval=1): /searxng.ini
INFO:  variant --> :socket
ERROR: /home/x/Downloads/searxng/utils/templates/searxng.ini:socket does not exists
ERROR: ... can't install /searxng.ini
** press any [KEY] to continue **
ERROR: linuxmint-20.3: uWSGI not yet implemented
INFO:  restart uWSGI service
ERROR: linuxmint-20.3: uWSGI not yet implemented
INFO:  uWSGI app: searxng.ini is installed
ERROR: uWSGI socket not available at: /usr/local/searxng/run/socket

*****************************************

Install Apache site searxng.conf
================================

This installs SearXNG's uWSGI app as apache site.  The apache site is
located at: /searxng.conf.

To install uWSGI use::

    searxng.sh install uwsgi

ERROR: ./utils/searxng.sh: line 684: SearXNG's uWSGI app not available
```

Linux Mint 20.3 responds to 

systemctl restart uwsgi
and
systemctl restart apache2

**Comment by return42** [comment]
These messages: 

```
ERROR: linuxmint-20.3: nginx not yet implemented
ERROR: linuxmint-20.3: apache not yet implemented
ERROR: linuxmint-20.3: uWSGI not yet implemented
```

are from the script; the script does not support linuxmint distribution.

The script only supports the distributions described in the [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html) guide.

FYI: we regulary test the script with this distributions:

https://github.com/searxng/searxng/blob/cee586029cd2afa54cf0f47db13b35702aa45d8d/utils/lxc-searxng.env#L16-L27

The versions will be upgraded from time to time.

**Comment by Immortality-IMT** [comment]
I want to use it locally on Linux Mint 20.3

**Comment by return42** [comment]
> I want to use it locally on Linux Mint 20.3

Sorry, we can't offer installation methods for every OS & distribution on planet earth.

**Comment by Immortality-IMT** [comment]
> > I want to use it locally on Linux Mint 20.3
> 
> Sorry, we can't offer installation methods for every OS & distribution on planet earth.

Linux Mint uses the same paths as Debian and Ubuntu, to get it working you have to add...

ubuntu-*|debian-*|linuxmint-*)

grep -R "not yet implemented"


lib.sh 


Let me know how it goes...

**Comment by return42** [comment]
For an official support we have to test regularly, for this we need a container from https://images.linuxcontainers.org :

https://github.com/searxng/searxng/blob/cee586029cd2afa54cf0f47db13b35702aa45d8d/utils/lxc-searxng.env#L12-L27

Ubuntu & debian share the same package names / I assume it is the same with linuxmint?:

https://github.com/searxng/searxng/blob/cee586029cd2afa54cf0f47db13b35702aa45d8d/utils/searxng.sh#L59-L68

Older versions might need additional packages:

https://github.com/searxng/searxng/blob/cee586029cd2afa54cf0f47db13b35702aa45d8d/utils/searxng.sh#L93-L106

More or less all `case` statements needs do be modified & tested:

```
$ grep -R 'debian-\*' utils/
utils/searxng.sh:    ubuntu-*|debian-*)
utils/searxng.sh:        ubuntu-*|debian-*)
utils/searxng.sh:            ubuntu-*|debian-*) tail -f "/var/log/uwsgi/app/${SERVICE_NAME%.*}.log" ;;
utils/searxng.sh:    # normaly debian-* and ubuntu-* are most the same.
utils/searxng.sh:                ubuntu-*|debian-*)  cat <<EOF
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*) (command -v apachectl) &>/dev/null;;
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
utils/lib.sh:        ubuntu-*|debian-*)
```

And we need to amend the documentation in  [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html) guide.

**Comment by Immortality-IMT** [comment]
I am running searxng on linux mint 20.3 by editing 

More or less, all case statements needs to be modified & tested:

ubuntu-*|debian-*)

to

ubuntu-*|debian-*|linuxmint-*)

And also adding linuxmint only where OR statements exist having only ubuntu|debian and adding...

ubuntu|debian|linuxmint

I am attempting to find...

Finalize installation
=====================

Do you want to run some checks? [YES/no] 
Yes
INFO:  wrapper:  utils/searxng.sh instance _call searxng.check
ERROR: linuxmint-20.3: nginx not yet implemented
ERROR: linuxmint-20.3: apache not yet implemented
ERROR: linuxmint-20.3: uWSGI not yet implemented
ERROR: linuxmint-20.3: pkg_install LXC_BASE_PACKAGES not yet implemented

It must be in another file.

**Comment by return42** [comment]
@Immortality-IMT even it looks trivial to add a new (debian) distribution .. it isn't.  And as I said in my comment above; for an official support we have to maintain the script and we need test scenarios (we use linux containers to build tests).

The installation script just exists for convenience and to test SearXNG on distributions that differ in their package manager. We already maintain two distributions that using apt (debian & ubuntu) .. and I'm sorry, but I don't have time to maintain a third apt distro (their is no progress for the SearXNG in).

To install SearXNG on distros not supported by the installation script we have the [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html) tutorial.  The advantage of the tutorial is that you also get to know your distribution and SearXNG better.

For those who do not want to have to much insights about the installation it is recommended to use our well maintained [docker container](https://github.com/searxng/searxng-docker).
