### ISSUE TITLE
Neeva

### ISSUE THREAD

**Issue by Krando** [searxng/searxng#1630]
**Working URL to the engine**
https://neeva.com/index

**Why do you want to add this engine?**
There are a few things which make Neeva special, one of them is that it has a capable crawler which has been indexing the web at a rapid rate and secondly that it also sources a portion of it's results from Apple (not sure how). It also uses Bing ofcourse **but it's own independent index is very large.** Recently, Neeva announced this:

_In our efforts to build our own search index, so far we have:_
🌟**1 trillion URLs discovered**
🌟**200M URLs fetched per day, 60B URLs fetched total**
🌟**Index refreshed weekly**

They announced that they are on track to hit **a billion pages per day** soon. More information on their engine is available on this thread: https://twitter.com/Neeva/status/1536448063346204672

**Features of this engine**
1) It has a very large independent index and highly capable crawler that has yielded impressive results, 2) It has great potential as it is on track to hit a billion pages a day soon, 3) It sources some of it's results from Apple.

**How can SearXNG fetch the information from this engine?**
Search results can be attained from a link as follows:

https://neeva.com/search?q=cat [this is the first page]

Pagination is possible as follows:

https://neeva.com/search?q=cats&c=All&src=Pagination&page=2
https://neeva.com/search?q=cats&c=All&src=Pagination&page=3
https://neeva.com/search?q=cats&c=All&src=Pagination&page=4

**Applicable category of this engine**
We should add it to general search as soon as possible. It has an image search facility too but mostly it seems to be sourced from Bing, although occasionally unique results pop up for certain queries.

**Additional context**

**Comment by Krando** [comment]
Can @allendema, @return42 or @liimee give their opinion on this?

**Comment by liimee** [comment]
this would be a nice addition to searxng of course :)

if you want, you can try adding  it yourself using the xpath engine like the mojeek engine:
https://github.com/searxng/searxng/blob/2bfb269f0a2a2c35d3e4752cb839c38ddcaf805d/searx/settings.yml#L1629-L1649

**Comment by return42** [comment]
@Krando we are open for additions / if you or @liimee send us your PR we can review & merge.

**Comment by Krando** [comment]
> @Krando we are open for additions / if you or @liimee send us your PR we can review & merge.

If you get the time, you should consider adding this to searxng. 

The first page is: https://neeva.com/search?q=%22searxng%20is%22&c=All&src=typedquery

Pagination is possible through: https://neeva.com/search?q=%22searxng%20is%22&c=All&src=Pagination&page=2

**Comment by return42** [comment]
> If you get the time

That is the problem, we are a small team and we have a lot on our "todos" .. SearXNG is nothing without its community and we encourage everyone to contribute. ...  [Development Quickstart](https://docs.searxng.org/dev/quickstart.html)  :+1:

**Comment by liimee** [comment]
@Krando hi, I'm currently working on it :)
