### ISSUE TITLE
Hacker News

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1632]
**Working URL to the engine**

https://hn.algolia.com/
**Why do you want to add this engine?**

it's a link aggregator.
**Features of this engine**

it often has some useful content.
**How can SearXNG fetch the information from this engine?**

https://hn.algolia.com/api
**Applicable category of this engine**

IT or social media
**Additional context**

**Comment by allendema** [comment]
https://github.com/searx/searx/issues/1456#issuecomment-466778239

**Comment by return42** [comment]
Implemented by 

- https://github.com/searxng/searxng/pull/2899
