### ISSUE TITLE
Clicking on a suggestion in simple theme should search directly

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1636]
**Is your feature request related to a problem? Please describe.**

When you click on a suggestion (the autocomplete) it fills it in the search bar but doesn't actually search, you have to click on the search icon to search (on mobile atleast).

**Describe the solution you'd like**

either clicking on the suggestion should take you to the results page or add a button to fill in the suggestion like other search engines:
![Screenshot_2022-08-09-14-31-56-46_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/107424175/183609467-72c67dce-1c1a-42af-90e2-8546b8ec9bb8.jpg).

**Describe alternatives you've considered**

already described above.

**Additional context**

already described above.

**Comment by return42** [comment]
Related issues and discussions:

- https://github.com/searxng/searxng/discussions/1472
- https://github.com/searxng/searxng/issues/1613

**Comment by return42** [comment]
Closed by https://github.com/searxng/searxng/pull/2331
