### ISSUE TITLE
"Error! Engines cannot retrieve results. ( Suspended: access denied )" error when using the ddg definitions search engine

### ISSUE THREAD

**Issue by bbaster** [searxng/searxng#1637]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.08.09-3d6b098a

**How did you install SearXNG?**

I'm using the serx.ml instance, also reproducible with searx.be and search.ononoki.org

**What happened?**

When attempting to search something with ddg definitions, an error appears.

**How To Reproduce**

1. Search using the "!ddd linux" query
2. The mentioned error appears

**Expected behavior**

The ddg definitions seach engine gives results

**Screenshots & Logs**

![Screenshot_20220809_154731](https://user-images.githubusercontent.com/67292925/183665906-e54805cb-3fd4-4c80-b786-2189bb5f8094.png)

![Screenshot_20220809_154825](https://user-images.githubusercontent.com/67292925/183666053-ad5d2ef8-866b-4312-82e4-a1a8417fc217.png)

**Additional context**

I'm certain it's not an issue with retrieving results from DuckDuckGo in general, the DuckDuckGo search engine works perfectly fine.

**Comment by return42** [comment]
> I'm using the serx.ml instance, also reproducible with searx.be and search.ononoki.org

Works on all three instances [!ddg_definitions paris](https://searx.be/search?q=%21ddg_definitions%20paris&categories=none)

May be an temporary issue.

**Comment by bbaster** [comment]
I can't reproduce it anymore either

**Comment by Mau-Bomani** [comment]
![Screenshot_20221022_165704](https://user-images.githubusercontent.com/116457487/197365358-e5f0497e-709c-43c3-8968-f2e69e8e337b.jpg)

Turning it off and on again solved this issue for me.
