### ISSUE TITLE
Add ability to disable or enable safesearch on Qwant web & image search

### ISSUE THREAD

**Issue by Krando** [searxng/searxng#1640]
**Is your feature request related to a problem? Please describe.**
Searxng has so far not implemented safesearch on it's Qwant module yet but this can be easily done using the 's' parameter.

**Describe the solution you'd like**
For any search on it's web or image section, simply attach &s=0 to disable safesearch, &s=1 to enable moderate safesearch or &s=2 to enable strict safesearch.

This is with strict safesearch: 

https://www.qwant.com/?s=2&q=dead+lion&t=images&s=2

This is with no safesearch:

https://www.qwant.com/?s=2&q=dead+lion&t=images&s=0

**Describe alternatives you've considered**

**Additional context**

**Comment by return42** [comment]
@Krando thanks for pointing out / I send https://github.com/searxng/searxng/pull/1652 would you give it a try?

FWIW: we use the API https://api.qwant.com/v3 .. the safesearch argument in the API is:   `&safesearch=`
