### ISSUE TITLE
Google images internal API with JSON results

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#1641]
Warning: I discovered two internal API for Google images, this one and another one in #1642!

----

Is it known that Google images has a pagination issue on SearXNG: https://github.com/searxng/searxng/issues/175

I just found an internal API in the [Google Go android](https://play.google.com/store/apps/details?id=com.google.android.apps.searchlite) application where you can search on Google API and have a JSON result returned! And it support the pagination with just a `start=` parameter.

Here is how to do the requests.

You need to send a GET request to this URL: `https://www.google.com/search?q=ok&hl=fr&start=0&asearch=isch&tbm=isch&async=_fmt:json,p:1` and with the header `accept: */*`.

If you want more results in one page, you need to use this user-agent: `NSTN/3.58.464445598.release Dalvik/2.1.0 (Linux; U; Android 12; US) gzip`. It's a modified one from the stock in order to avoid any special fingerprinting: `NSTN/3.58.464445598.release Dalvik/2.1.0 (Linux; U; Android 10; SM-G930F) Mobile`

Here is an explanation of the parameters:
- `asearch=isch` to images "category"
- `tbm=isch` optional but related to images "category"
- `q=ok` the search query, similar parameter to the one used in the google engine
- `hl=fr` the language, similar parameter to the one used in the google engine
- `async=_fmt:json,p:1,ijn:1`:
  - `_fmt:json`: ask Google for JSON results, if you set `_fmt:pb` you get the results in protobuf
  - `p:1`: no idea what is this parameter but if you remove it the final JSON is encoded inside a JSON object called `results`, I don't recommend removing it
  - `ijn:1`: that's the page number, increment it for each next page

All the other parameters used in the google engine should work too: gl, ie, oe and so on.

**Comment by Krando** [comment]
Wonderful. Hopefully this gets added soon, is this method compatible with safesearch?

**Comment by unixfox** [comment]
> is this method compatible with safesearch?

Yes all the parameters used in the current google images implementation work.

**Comment by Krando** [comment]
> > is this method compatible with safesearch?
> 
> Yes all the parameters used in the current google images implementation work.

Does this method work for videos as well? Pagination for Google videos hasn't been implemented on searxng either. It would be great if pagination is enabled for both image & videos with this method.

**Comment by unixfox** [comment]
> Does this method work for videos as well? Pagination for Google videos hasn't been implemented on searxng either. It would be great if pagination is enabled for both image & videos with this method.

Yes please see #1642
