### ISSUE TITLE
Google search internal API with JSON results

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#1642]
After reverse engineering the `Google images for Google go` internal API in #1641, I had a better understanding of the undocumented parameters used by Google.

So I looked again at the issue #159, and I found that if you add the parameter `_fmt:json` in the query string `async=` you basically get the Google search results in JSON.

Here is how to do the request, it's very similar to #159, only the parameter `_fmt:json` need to be added:

You need to send a GET request to: `https://www.google.com/search?q=yeah&start=0&asearch=arc&async=use_ac:true,amw:true,_fmt:json` and with the headers:
- user-agent: `Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0`
- accept: `*/*`

Need to understand the meaning of `amw:true`

Then you get a bunch of JSON objects all over the place, mainly what we are interested is in the object `arcResponse => search_results => result_list`. I've taken an example object of the interesting data for one result:
```json
"payload":{
   "encrypted_docid":"PuQ9p5ome90J",
   "has_snippet":true,
   "has_video":false,
   "is_first_result_in_group":false,
   "is_first_result_in_whole_page_cluster":false,
   "is_leaf_result":false,
   "is_video_result":false,
   "primary_link":{
      "is_clickable":true,
      "news_result_signals":{
         "host_newsiness":0
      },
      "should_truncate_title":true,
      "title":"\u003cb\u003eJSON\u003c\/b\u003e.parse() - \u003cb\u003eJavaScript\u003c\/b\u003e - MDN Web Docs",
      "url":"https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse",
      "volt_result_data":{
         "is_volt":true
      }
   }
}
```

Other parameters in the query strings can be used too, all the ones from the current google engine implementation.

More services from Google like Google videos, Google News and Google images could be used on this API:

- Google videos, add `tbm=vid`
- Google News: `tbm=nws`
- Google images: `tbm=isch`

Additional note: Getting the results in JSON result in increase latency, maybe we could look into integrating protobuf so that we can process the results in protobuf format in order to decrease the latency by around 300-400ms. We don't have the [proto files](https://developers.google.com/protocol-buffers/docs/proto3), but we can reconstruct them from the JSON results.

-----

Question to the SearXNG maintainers @searxng/internal, do we create an entirely new engine for this new API or do we drop all the code from the current google engine, and we rewrite it with this new internal API?

I mean the current implementation in the google engine code works, but we need to fix it from time to time which is annoying.

Now that I think again based on my experience in Invidious, I think it's fine to use this internal API as default in SearXNG. Google is progressively going to transition its web pages to dynamic web pages anyway, with REST API and JavaScript updating the content on the screen "on the fly".

This would mean the end of the `use_mobile_ui` and the `Too many requests` errors (for the moment, until Google decide to do something about it).

**Comment by anyone00** [comment]
Thank you for working on this and doing the research.

I like the idea of switching to the new API but I'm not aware that it's been battle tested as the current method, I would suggest adding it as a new way or testing it in a couple of instances to discover potential rate-limiting before completely switch to the new API.

**Comment by unixfox** [comment]
> I would suggest adding it as a new way or testing it in a couple of instances to discover potential rate-limiting before completely switch to the new API.

We already know that it is not rate limited, we are using this API but in the "wrong way". Here I'm documenting how to use it properly, by parsing the JSON fields and so on.

It hasn't produced any rate limits since we implemented it around one year ago.

**Comment by Krando** [comment]
We should shift to the new API as suggested by @unixfox as soon as possible, this way of handling Google searches seems to be cleaner and also less vulnerable to running into issues. The fact that pagination for google images/videos is also made available is also great.

**Comment by return42** [comment]
> and also less vulnerable to running into issues.

this has yet to be proven, google always smells .. :laughing: 

But "yes" we should give it a try / I also expect the API to be a bit more stable :+1:

----

@unixfox I have some questions ..

> Then you get a bunch of JSON objects all over the place, mainly what we are interested is in the object `arcResponse => search_results => result_list`.

When I send:

```
curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0' \
     -H 'Accept: */*' \
     'https://www.google.com/search?q=yeah&start=0&asearch=arc&async=use_ac:true,_fmt:json' \
     > google_response.json
```

I get a file of 1MB size that starts with:

```
)]}'
{"arcResponse":
```

do you have prototyped code to extract a valid JSON from this file?

About the size of 1MB .. is this the reason why you suggest to integrate protobuf?

----

Thanks to @dalf's https://github.com/searxng/searxng/issues/1642#issuecomment-1210308466 I use:

```
curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0' \
     -H 'Accept: */*' \
     'https://www.google.com/search?q=yeah&start=0&asearch=arc&async=use_ac:true,_fmt:json' \
     | tail -n +2 | jq  > google_response.json
```

Note: I had to install `jq` by (apt: debian/ubuntu): `sudo apt install jq`

**Comment by unixfox** [comment]
> I get a file of 1MB size that starts with:
> 
> ```
> )]}'
> {"arcResponse":
> ```
> 
> About the size of 1MB .. is this the reason why you suggest to integrate protobuf?

Yes that too, it would decrease the latency (it's less computational for google servers to send protobuf data instead of JSON) and would decrease the size of the data received. As basically for protobuf all the fields are replaced with integers.

> do you have prototyped code to extract a valid JSON from this file?

That's the fun part, we have to build it (the proto files) ourselves based on the JSON fields.

**Comment by mrpaulblack** [comment]
@unixfox after reading the thread: I think the new impl. for the engine should replace the current one. If we would add it as a new option it would just add confusion about what google engine to use for instance maintainers IMO and also it would mean that we would need to maintain multiple google implementations... For that reason I am for replacing the current google engine code :+1:

**Comment by dalf** [comment]
@return42  `curl "https://www.google.com/search?q=auvers%20sur%20oise&hl=fr&start=0&asearch=isch&tbm=isch&async=_fmt:json,p:1" | tail -n +2 | jq .`

**Comment by return42** [comment]
> For that reason I am for replacing the current google engine code +1

No need to replace .. to be open for various implementation, we can implement a python module named `searx/engines/google_json.py` and in the `settings.yml` we can replace (the default) ..

https://github.com/searxng/searxng/blob/07342899e5412d5ba03195f1ebbb7cb5ea525556/searx/settings.yml#L692-L698

by ...

```yaml
  - name: google 
    engine: google_json
    shortcut: go
```

By this we can switch between the implementations.

----

Additionally: Since the API scales good, we can implement all new google engines in one module (`searx/engines/google_json.py`) by adding a new preference ..

```yaml
  - name: google videos 
    engine: google_json
    google_categ: videos
    shortcut: go
```

.. the `google_json.py` knows that search goes too google-videos.  We do similar in the qwant engine ..

**Comment by Krando** [comment]
Any idea when the implementation of this will begin?

**Comment by return42** [comment]
> Any idea when the implementation of this will begin?

As soon as someone has time for it :-) 

SearXNG is an open source project that lives from the contributions of the community.  We don't buy programming services and therefore can't plan projects with dates and deadlines. But I am also sure that there are already some "tinkering" in the background ... let's wait and see who asks first for a PR .. :+1:

**Comment by dit7ya** [comment]
@unixfox Do you know what is the request format for the protobuf response?

**Comment by unixfox** [comment]
> @unixfox Do you know what is the request format for the protobuf response?

You mean you want the proto files? I don't have it, we have to recreate them based on the JSON fields.

**Comment by unixfox** [comment]
Closing as google doesn't allow the usage of this API anymore.
