### ISSUE TITLE
seekr

### ISSUE THREAD

**Issue by somedevreally** [searxng/searxng#1644]
**Working URL to the engine**
https://www.seekr.com

**Why do you want to add this engine?**
Seekr is a transparent and independent search engine

**Features of this engine**
includes a Seekr Score of High, Medium, or Low with each result

**Applicable category of this engine**
General, news, images, videos, maps

**Comment by LencoDigitexer** [comment]
https://api.seekr.com/engine/advise?apiKey=srh1-22fb-sekr&v=web&query={query}&limit=10&offset=0

**Comment by Milad-Laly** [comment]
I'll be working on this so seekr is added to the engine.

**Comment by Milad-Laly** [comment]
@return42 Hi, I looked at seekr they have a `More Results` button. But, in the URL address there isnt a page number parameter to use.

Do you have any suggestions on this or if another engine has a similar button

**Comment by return42** [comment]
If there is no API, then you have to reverse engineer the requests from the HTTP client.  I tried to have a look the last days, but whenever I go to https://www.seekr.com/ I got a dialogue that says "Seekr is down" ..

![grafik](https://user-images.githubusercontent.com/554536/211598015-edb3618e-f15a-4da2-ba8f-5fd0b2f4b4d8.png)

> I looked at seekr they have a `More Results` button. 

Is it only me getting the "Seekr is down"?  .. From where do you know that there is a `More Results` button?

**Comment by mrpaulblack** [comment]
Seekr is working for me correctly: https://www.seekr.com/search?query=time ... Try clearing your cookies for that site (They are setting quite a few, maybe they have a cookie set on your PC setting s specific server on BE that is down?)

**Comment by return42** [comment]
Seems seekr does not like FFox .. 

@Milad-Laly to answer your question: seems there is an async API with JSON response .. by example try:

https://api.seekr.com/engine/experts/web-search/x3rIazr/v1/webc?Req=d321796b-009b-49b4-a49e-6dab964e649b&ApiKey=srh1-22fb-sekr&Lang=en&Limit=10&Offset=20&AdsQuery=foo&query=foo&originalQuery=foo&mq=False&ulat=53.144700&ulong=8.900300&cbr=1673424746741&dt=true&req=d321796b-009b-49b4-a49e-6dab964e649b&tz=-60&v=true&apiKey=srh1-22fb-sekr

The request is the request of the 3. page of search term `foo`:

![image](https://user-images.githubusercontent.com/554536/211753756-c153b8b2-f6b2-414b-99bb-e3e3b000a18f.png)
