### ISSUE TITLE
UnicodeEncodeError for preferences url

### ISSUE THREAD

**Issue by rany2** [searxng/searxng#166]
**Version of Searx**
```
$ git log -1
commit f3e56836d6481f9807ac232b71c584c0535de783 (HEAD -> master, origin/master, origin/HEAD)
Merge: f4da4baf 0ef6aa51
Author: Alexandre Flament <alex@al-f.net>
Date:   Mon Jun 21 20:12:07 2021 +0200

    Merge pull request #165 from return42/patch-google
    
    improve & document google engine
``` 

**How did you install Searx?**
Executing the python file without docker.

**What happened?**
I tried to use the preferences url but it didn't work.

**How To Reproduce**
Visiting [url](https://searx.be/?preferences=eJxtVVFv3DYM_jXxi5FibTdsffBDkaFogQEZlnSvBi3RPtaS6EqyL86vH3W2c1KyhztANEl9_D6SUhBxYE8YmgEdejCVATfMMGCD7vb7Q2VYgUmHCubIiu1kMGIzMA8GK7Li2U6en9bm0c9YWYwn1s3f9w-PVYAeA4JXp-aXKp7QYsNBga88htnE0LJrHZ7bCF3zBUzASjO18pHNgr5hkOM79kN1iboNcRUghgdSrHGpQC_gFOp2v2NPQQE6I1Z0AzmpqzekRt-2F6jh5sPdhOjj3GHbLqSRk8nP3TqgDeIV5Zjyd-iH_ThQNNDth3UYInuPLrZtT-aSsSMnvjuBco48rhw5nHgEd3VLKGnBmkLurIHMajmSsHFFhJ7PpHO_XntOliPbpkA9GVhry4tIWBRkhYTMcKaRNETIM4YIPk5JwMwojgkK-PWVlRZeX_ka6rw41skSyqp6T24kUBnvAw2iDISY-3nUmmLmtYmZFKjT38764XYNJAdZeZoGUSCwIjC1RU2Q4HEXIr7zh6zT3MkncVOE0jhisatFy1JB9OCCkWEoKE-61huyDCFP6DxOHMoGqDcwGahdoTd24V2NLC3eGz7v2H6ewRX1YZSmcEZauEQUu1mNGPcwtwJcYaxwYs7dLf9AHItu00OtsSdHSeVCsguEt-UGtGInVQd1YgM-52-Q7JEsHgxrUvGZS8ibNDLnRxtK4YFi0V4wjbUl79lfi1Fqm-AMip41uoKOuGU_Yk4gDZn-Dnome8xwNi0wTZl2WvhMv4Hf1n5mrx0VBM4uSJJwyr2kqI55LNhUSt3GJR_JvYVfNWkKTuS8UPT-qaj4AFf2BrMpbgs4EWyjkzcaPjuw5Rx36_-N33537xHrwH08g8dak0cly249Vh_P2960cyCV6AXRMk_34lHsnZ8zx6Il3n_8-PvTVYFFOoizmN6DhbRbjunfF-5zJhouJF0p--uVDoFnr4rLws3dbzd_fOCzCFn_uLn79ebTp-d1hHoSDkfCjNoKXfl2XF-TycxiCs29DH_7WXozhPbP-2_yWp09xTQL39xlqlDGw7NJN_9L9tbQiO2J44hreEl_JHvYBJPFr7Z3eJW3zAjnEvyApm8lJ3sLl1EV29fUd1uwnB69rBHh__s_fwkMmxZKJS8PSuL_AA338nI=&q=%s) should work without 500-ing.

**Expected behavior**
Using the preferences URL from https://searx.be/preferences should work

**Screenshots & Logs**
```
uwsgi[3504]: ERROR:searx.webapp:Exception on / [GET]
uwsgi[3504]: Traceback (most recent call last):
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
uwsgi[3504]:     response = self.full_dispatch_request()
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
uwsgi[3504]:     rv = self.handle_user_exception(e)
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
uwsgi[3504]:     reraise(exc_type, exc_value, tb)
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
uwsgi[3504]:     raise value
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/app.py", line 1948, in full_dispatch_request
uwsgi[3504]:     rv = self.preprocess_request()
uwsgi[3504]:   File "/usr/local/searx/searx-pyenv/lib/python3.9/site-packages/flask/app.py", line 2242, in preprocess_request
uwsgi[3504]:     rv = func()
uwsgi[3504]:   File "/usr/local/searx/searx-src/searx/webapp.py", line 541, in pre_request
uwsgi[3504]:     preferences.parse_encoded_data(request.form['preferences'])
uwsgi[3504]:   File "/usr/local/searx/searx-src/searx/preferences.py", line 442, in parse_encoded_data
uwsgi[3504]:     for x, y in parse_qs(decoded_data).items():
uwsgi[3504]:   File "/usr/lib/python3.9/urllib/parse.py", line 701, in parse_qs
uwsgi[3504]:     pairs = parse_qsl(qs, keep_blank_values, strict_parsing,
uwsgi[3504]:   File "/usr/lib/python3.9/urllib/parse.py", line 775, in parse_qsl
uwsgi[3504]:     value = _coerce_result(value)
uwsgi[3504]:   File "/usr/lib/python3.9/urllib/parse.py", line 108, in _encode_result
uwsgi[3504]:     return obj.encode(encoding, errors)
uwsgi[3504]: UnicodeEncodeError: 'ascii' codec can't encode character '\u0142' in position 1045: ordinal not in range(128)
```

**Additional context**
I don't own searx.be but actually hosted my own private SearxNG instance. However the issue is present in searx.be as well

**Comment by rany2** [comment]
Small update, i tried to switch to SearX to see if it works there but I'm hit with the same issue. This isn't SearXNG specific

**Comment by return42** [comment]
Thanks for the issue, I guess it is related to the name of the sjp engine ..

https://github.com/searxng/searxng/blob/f3e56836d6481f9807ac232b71c584c0535de783/searx/settings.yml#L1459-L1465

I will prepare a patch.

**Comment by rany2** [comment]
I can confirm that this is fixed. Thanks a lot!

**Comment by unixfox** [comment]
Thank you for reporting this bug @rany2. I just updated searx.be to the latest version of searxng.

**Comment by return42** [comment]
@rany2 in PR #180 I fixed the decoding of saved preferences in the URL / if you want to give it a try.

**Comment by rany2** [comment]
Does SearxNG send its patches for bugs like this to the original SearX project?

**Comment by unixfox** [comment]
> Does SearxNG send its patches for bugs like this to the original SearX project?

It's up to the maintainers of the SearX to merge the commits from the SearXNG project. You can expect a huge delay because SearX hasn't been updated for almost one month.

You can read a bit about the differences between SearXNG and SearX from the active contributors in the SearX community: https://github.com/searxng/searxng/issues/46
