### ISSUE TITLE
query_in_title not showing the query as expected.

### ISSUE THREAD

**Issue by plague-doctor** [searxng/searxng#1662]
Version: 2022.08.13-e81c4581 docker
```
query_in_title: true
```
No query on result page’s titles. Tested on Firefox and Chromium (Linux)
However it works as expected in Brave... 
Firefox displays the query but momentarily it is replaced with the instance name.

**Comment by return42** [comment]
Is it limited to your instance?  I use FFox & Chrome ..

https://darmarit.org/searx/search?q=john+doe&safesearch=2&theme=simple 

and I see john doe in the tab ..

![grafik](https://user-images.githubusercontent.com/554536/184528253-6f40f91b-b96a-427a-97b8-3a86cfd45959.png)

**Comment by plague-doctor** [comment]
Indeed. It works fine on [https://darmarit.org](https://darmarit.org) instance...
Any idea on what I am missing?
```
use_default_settings: true

general:
  debug: false
  instance_name: "searxng"
  contact_url: false
  donation_url: false
  enable_metrics: false

server:
  port: 8888
  bind_address: "127.0.0.1"
  secret_key: "e1...cb"
  base_url: https://searx.mydomain.myd/
  limiter: true
  image_proxy: true
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  autocomplete_min: 4
  default_lang: "en-AU"
  languages:
    - en
    - en-AU
    - en-US
    - pl-PL
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html

redis:
  url: redis://redis:6379/0

ui:
  static_use_hash: true
  infinite_scroll: true
  query_in_title: true

result_proxy:
  url: https://searx.mydomain.myd/morty/
  key: !!binary "b...7+"
  proxify_results: true

outgoing:
  request_timeout: 3.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

[...]
```

**Comment by return42** [comment]
> However it works as expected in Brave...
> Firefox displays the query but momentarily it is replaced with the instance name.
..
> Any idea on what I am missing?

I assume its related to youe FFox .. did you reset your SearXNG Settings (may be there is an old cookie).

**Comment by plague-doctor** [comment]
Spot on, @return42
Thanks a lot!
