### ISSUE TITLE
ERROR: ./utils/searxng.sh: line 436: user 'searxng' missed read permission: /home/kim/_searxng-20220814/searxng

### ISSUE THREAD

**Issue by sean1138** [searxng/searxng#1669]
i have a fresh xubuntu 22.04.1 install in virtualbox, /home directory on a second virtual hdd, have tried making a different folder than /downloads/ and get the same error.

https://docs.searxng.org/admin/installation-scripts.html#installation-scripts - ran the commands listed there
`sudo -H ./utils/searxng.sh install all`
ends up with
```
ls: cannot access '/home/kim/Downloads/searxng': Permission denied
		ERROR: ./utils/searxng.sh: line 436: user 'searxng' missed read permission: /home/kim/Downloads/searxng
```
tried making another folder under the user, same thing
```
ls: cannot access '/home/kim/_searxng-20220814/searxng': Permission denied
		ERROR: ./utils/searxng.sh: line 436: user 'searxng' missed read permission: /home/kim/_searxng-20220814/searxng
```

been trying to find a clue as to what i need to do to fix this but so far nothing i find seems to fit, it worked fine under xubuntu 20.04 vm 6 months ago.

https://www.omgubuntu.co.uk/2021/01/private-home-directory-in-ubuntu-21-04 - no idea if this could be related.

**Comment by return42** [comment]
The user `searxng` needs permission access `/home/kim/Downloads/searxng` ..

> tried making another folder under the user, same thing

Maybe you have a modified umask / no mater what folder you use below `/home/kim/Downloads` will have the same issue.

can you please post the output of:

    ls -ld /home
    ls -ld /home/kim
    ls -ld /home/kim/Downloads

**Comment by sean1138** [comment]
```
$ ls -ld /home
drwxr-xr-x 6 root 774 4096 Aug 13 06:10 /home
$ ls -ld /home/kim
drwxr-x--- 17 kim 774 4096 Aug 14 18:33 /home/kim
$ ls -ld /home/kim/Downloads
drwxr-xr-x 3 kim 774 4096 Aug 14 13:31 /home/kim/Downloads
$ ls -ld /home/kim/_searxng-20220814/
drwxrwxrwx 3 kim kim 4096 Aug 14 18:34 /home/kim/_searxng-20220814/
```

**Comment by return42** [comment]
The problem is the /home/kim folder:

    drwxr-x--- 17 kim 774 4096 Aug 14 18:33 /home/kim

You need to set `x` for *other* ..

    chmod o+x /home/kim

In all distros I know this `x` is set for user's HOME folder .. did you changed it? .. or is it related to the xubuntu 22.04 distro?

**Comment by sean1138** [comment]
I don't think i changed it.  The only weird thing i've done in 22.04.1 involves the second vhd for the /home directory.  I used the same vhd as a second drive for the /home/ dir in a xubuntu 20.04 virtual machine as well but the single user had a different name there.  I copied the docs, pics, and videos folders from the older /home/old-user/ to /home/kim/.  I had to do some permissions changing before firefox and chrome could save files to the /home/kim/Pictures/ and /home/kim/Documents/ path but don't think i did anything that should have changed the /home/kim/Downloads/ path.

i don't intend on using both 20.04 and 22.04 virtual machines sharing the 2nd vhd, if that makes sense, i just set it up that way to hopefully be able to reformat if/when i need to without losing anything i saved in the /home/ path more easily.

thanks to your help i got past the permission problem but haven't gotten the localhost:8888 to work yet, used the /home/kim/_searxng-20220814/ path just because i was already there with a terminal window... i probably should have just stuck with the recommended /home/user/Downloads/ path, can/should i just delete the /_searxng-20220814/ folder and start over?

ran `sudo -H ./utils/searxng.sh instance inspect` and don't think i noticed anything really bad but i also don't 100% know what i'm doing ;)

![2022 08 15_115915](https://user-images.githubusercontent.com/6720184/184671184-533847fc-0540-4a02-9f4a-d0b1660f5b98.jpg)

**Comment by sean1138** [comment]
https://docs.searxng.org/admin/installation-apache.html#installation-apache - ran thru this page, looks like i have it working now :D

![Screenshot_2022-08-15_12-33-24](https://user-images.githubusercontent.com/6720184/184676696-81eacaae-b177-4231-9128-d5532e941282.png)

**Comment by Miguel-404** [comment]
```
git clone https://github.com/searxng/searxng.git /tmp/searxng
cd /tmp/searxng/
sudo mkdir -p /cache/etc/uwsgi/apps-available/
sudo mkdir -p /cache/etc/apache2/sites-available/
sudo chown -R searxng:searxng cache/
sudo -H ./utils/searxng.sh install all
```
