### ISSUE TITLE
RARBG API

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1671]
**Working URL to the engine**

http://torrentapi.org/apidocs_v2.txt?app_id=searx

**Why do you want to add this engine?**

This is an API for RARBG (unofficial I think).

**Features of this engine**

RARBG is a torrent site, previously it wasn't added to [searxng because of antibot](https://github.com/searxng/searxng/issues/1152) but with this API it can be implemented in searxng.

**How can SearXNG fetch the information from this engine?**

the docs are [here](http://torrentapi.org/apidocs_v2.txt?app_id=searx), every request to the API has to have the app_id parameter it doesn't work without it (doesn't matter what it is), here is a python wrapper for it: https://github.com/verybada/rarbgapi it should help with the code.

**Applicable category of this engine**

files

**Additional context**

sadly it has a rate limit of 1 request / 2 secs but I'm hoping it'll still be helpful, maybe someone can figure out a workaround too

**Comment by unixfox** [comment]
Mmh I'm not sure if it's really worth to add given that it's just 1 request per 2 seconds.

This engine will never work on public instances given the very low amount of requests that can be done.

**Comment by ghost** [comment]
> Mmh I'm not sure if it's really worth to add given that it's just 1 request per 2 seconds.
> 
> This engine will never work on public instances given the very low amount of requests that can be done.

how many requests do engines usually need to work well ?

**Comment by unixfox** [comment]
> > Mmh I'm not sure if it's really worth to add given that it's just 1 request per 2 seconds.
> > This engine will never work on public instances given the very low amount of requests that can be done.
> 
> how many requests do engines usually need to work well ?

I don't think there is a rule for that, but 1 request per 2 seconds is not a good candidate for a new engine in SearXNG.

I mean, we (the SearXNG team) won't spend our time developing a new engine that won't really be usable. But if you submit a PR with a working code for this new engine, we may consider adding it.

**Comment by return42** [comment]
Seems there is no longer an interest in .. nor is there a way to bypass the limits.

I'm going to close this issue / if someone think different, please ask to reopen
