### ISSUE TITLE
Make SearXNG default search in Firefox

### ISSUE THREAD

**Issue by slashgob** [searxng/searxng#1680]
Version: 
SearXNG 2022.08.19-6f28a69f
Firefox 103.0

**How did you install SearXNG?**
Installed using Docker image provided by xthursdayx on UNRAID. Self hosted using NGINX as proxy. https://search.slashgob.com/

**What happened?**
I cannot make SearXNG the default search engine in Firefox. Reading Firefox documentation, I should be able to click on the URL and add SearXNG to the list of search engines if it supports Opensearch

**How To Reproduce**
navigate to SearXNG search page and click on URL in Firefox

**Expected behavior**
Clicking on URL should allow you to add SearXNG to the list of search engines in Firefox

**Comment by return42** [comment]
Seems Cloudflare adds some crap to your side

![grafik](https://user-images.githubusercontent.com/554536/185621116-dea7adfe-6c37-4d22-aa66-4fc5f82f86d5.png)

Beside this, Cloudflare can read everything (because they MITM your https connection) what is a disaster for the privacy of the user .. don't use Cloudflare!

**Comment by dalf** [comment]
@return42 are you sure this is not related to https://github.com/searxng/searxng/pull/1655 ?

**Comment by return42** [comment]
No it isn't / #1655 works by example on my instance and on @tiekoetter and @unixfox instances

But the first I get when I open https://search.slashgob.com/ is a CSP violation 

---

EDIT IDK why all guys think they need Cloudflare .. they do MITM and are the culprit of dozens of issues . IMO we should no longer give any support to Cludlfare users.

**Comment by LalleSX** [comment]
If you already have a SearxNG in your search engine list on Firefox you can either remove that or change the name of your instance in the `/etc/searxng/settings.yml`.

**Comment by LalleSX** [comment]
Just looked at your site its definitely the title, but its the lack of one. 
If you look at the tab it just says the URL _search.slashgob.com_ where for example [tiekoetter](https://searx.tiekoetter.com/) has a title _SearXNG @ searx.tiekoetter.com_

So edit `/etc/searxng/settings.yml`
And make it look something like this:
![pic-selected-221028-1658-52](https://user-images.githubusercontent.com/29478339/198664195-f1d8f267-1014-4920-afe4-56327019f22e.png)

**Comment by mrx23dot** [comment]
Please provide a way to accept **queries in URL string**, so it could by added to any browser by substituting that string **/%s**.

https ensurer that MITM is not seeing searches. But it would still show in history, for that you can just open searxng and search there.

**Comment by unixfox** [comment]
that's already possible: `http://localhost/search?q=%s`

Locking the conversation because this bug is definitively fixed.
