### ISSUE TITLE
Italian translation of the category name "onions"

### ISSUE THREAD

**Issue by gandbg** [searxng/searxng#1683]
I proposed the Italian translation for the category name "onions" suggesting "onion" without the "s", but it was rejected telling me to open an issue here to discuss it, so here i am 😄.

In Italian, every foreign word (like "onions") uses the singular form in both singular and plural contexts.
You can read more about this on [Accademia della Crusca's website](https://accademiadellacrusca.it/it/consulenza/plurale-dei-forestierismi-non-adattati/8).

> [Accademia della Crusca] is one of the most important research institutions of the Italian language, as well as the oldest linguistic academy in the world
> Source: [Wikipedia](https://en.wikipedia.org/wiki/Accademia_della_Crusca)

Side note: I'm [contentcard](https://weblate.bubu1.eu/user/contentcard/) from Weblate

**Comment by return42** [comment]
Hi @gandbg thanks a lot for your help on translation :+1:

> I proposed the Italian translation for the category name "onions" suggesting "onion" without the "s", but it was rejected telling me to open an issue here to discuss it, so here I am 😄.

Yes it was me 

> In Italian, every foreign word (like "onions") uses the singular form in both singular and plural contexts.

Ooops I am sorry, I didn't know that .. 7 month ago there was a comment from [genghis](https://weblate.bubu1.eu/user/genghis/) saying: [I think, just "onion", without the letter "s", is enough](https://weblate.bubu1.eu/translate/searxng/searxng/it/?offset=1&q=onions)

And I thought you and [genghis](https://weblate.bubu1.eu/user/genghis/) want to change the origin (english) from plural to singular.  I fixed the Italian translation / excuse the misunderstanding on my part.
