### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by WebbiiiCC** [searxng/searxng#1684]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.20-0ceb2563

**How did you install SearXNG?**
Installed via official wiki using docker pull.

**What happened?**
The qwant engine unexpectedly crashed.

**How To Reproduce**
1. Set the search language to default language.
2. Search anything (i searched "test")

**Expected behavior**
The qwant engine should not crash and get some results

**Technical report**

Error
  * Error: IndexError
  * Percentage: 60
  * Parameters: `()`
  * File name: `searx/engines/qwant.py:98`
  * Function: `request`
  * Code: `q_locale = get_engine_locale(params['language'], supported_languages, default='en_US')`

**Comment by return42** [comment]
Its fixed in https://github.com/searxng/searxng/pull/1666 .. I'm going to merge (without a review).
