### ISSUE TITLE
Image Filters

### ISSUE THREAD

**Issue by maverick74** [searxng/searxng#1690]
**Is your feature request related to a problem? Please describe.**
Currently neither SearX neither SearXNG has capabilities to apply Image Filters
E.G.: options such as (by order of importance):

Type (eg: Photos, Animated images such as gif, apng, webp)
size
color
format
license
...

**Describe the solution you'd like**
Would be great to have these options on the Image Queries and it could shrink and help queries a lot!

**Comment by Apacelus** [comment]
Is this related to https://www.youtube.com/watch?v=x9q3qPxrTqg

**Comment by return42** [comment]
duplicate of https://github.com/searxng/searxng/issues/1490

**Comment by maverick74** [comment]
@return42 let me explain my POV :)

Either #1490 or #1587 are not complete solutions / duplicates for this bug. 

This bug includes: Type, size, color, format and license.

These 5 types of filters are all present in the other engines.

It could be seen as more of a meta-bug... but i could also create the other 3 independent bugs (for Type, size and color) if you prefer

**Comment by return42** [comment]
Hi @maverick74 .. 

> These 5 types of filters are all present in the other engines.

we should not fragment this requirement over several issues / I have extended 1587 accordingly

**Comment by maverick74** [comment]
Yes, i've noticed it.

thank you :)
