### ISSUE TITLE
Internal server error after changing UI language settings

### ISSUE THREAD

**Issue by asenov** [searxng/searxng#1692]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
current master branch

**How did you install SearXNG?**
No installation dependencies

**What happened?**
Internal Server Error

**How To Reproduce**
- Go to https://searx.be/preferences
- Navigate to tab User Interface
- Change Interface language to Bulgarian
- Save the changes
- Try to click again on Preferences link

**Expected behavior**
To access the preferences menu without backend crash

**Comment by return42** [comment]
Hi @asenov thanks for pointing out :+1: 

Seems issue was added 8 month ago, when BG translation was added / see [history at weblate](https://weblate.bubu1.eu/translate/searxng/searxng/bg/?&offset=49#history) .. I fixed the issue at weblate.

BTW: we will be glad to receive further suggestions for BG translation --> https://weblate.bubu1.eu/projects/searxng/searxng/bg/
