### ISSUE TITLE
Some symbols are not kept on externals bangs & autocomplete

### ISSUE THREAD

**Issue by LoicBersier** [searxng/searxng#1695]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
4dc70b08 

**How did you install SearXNG?**
searxng-docker

**What happened?**
When searching something that contain a special symbol (Only tried with & # +) and use an external bang or on autocomplete the symbol will be lost

**How To Reproduce**
Search "1+1 !!g", it will show "1 1" in google
Search for "1+1 !" and the autocomplete will show up missing the plus symbol

**Expected behavior**
Show "1+1" in google & in the autocomplete

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/36051669/186251182-e54e4ea3-2e2c-4737-91d1-649ecc1741f3.png)

**Additional context**
I think the issue comes from the query not being url encoded.

**Comment by dalf** [comment]
I confirm the bugs:
* autocompletion of `1+1 !` is `1 1 !images`. The bug exists only with the POST method, not the GET method.
* `1+1 !!g` actually search `1 1` on Google. 

---
Technical notes

First point:
   https://github.com/searxng/searxng/blob/5284de9137c43c2a343958c5c3fccf97b72d65a3/searx/webapp.py#L899
   `request.form.get('q', '')` does not contains the `+`

Second point:
   https://github.com/searxng/searxng/blob/5284de9137c43c2a343958c5c3fccf97b72d65a3/searx/external_bang.py#L42

```patch
diff --git a/searx/external_bang.py b/searx/external_bang.py
index a56737c7..d24ba34f 100644
--- a/searx/external_bang.py
+++ b/searx/external_bang.py
@@ -1,5 +1,6 @@
 # SPDX-License-Identifier: AGPL-3.0-or-later
 
+from urllib.parse import quote_plus
 from searx.data import EXTERNAL_BANGS
 
 LEAF_KEY = chr(16)
@@ -39,7 +40,11 @@ def get_bang_definition_and_ac(external_bangs_db, bang):
 
 def resolve_bang_definition(bang_definition, query):
     url, rank = bang_definition.split(chr(1))
-    url = url.replace(chr(2), query)
+    chr2_pos = url.find(chr(2))
+    if url.find('?') < chr2_pos or url.find('#') < chr2_pos:
+        url = url.replace(chr(2), quote_plus(query))
+    else:
+        url = url.replace(chr(2), query)
     if url.startswith('//'):
         url = 'https:' + url
     rank = int(rank) if len(rank) > 0 else 0
```

**Comment by dalf** [comment]
> Search "1+1 !!g", it will show "1 1" in google

Should be fixed by https://github.com/searxng/searxng/pull/1707

> Search for "1+1 !" and the autocomplete will show up missing the plus symbol

https://github.com/searxng/searxng/pull/1706 is going to fix that.
However in some cases the backend (Google autocompletion or whatever you have chosen) removes the special characters.
For example if you search for `"test" +`, the suggestions don't include the quotes.

The fix is not trivial: it requires to parse the query and the suggestions, find what the suggestions are actually doing (add a word, reordering the query, something else), and then patch them to keep the user query.
