### ISSUE TITLE
Engines cannot retrieve results issue...

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1697]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

![Screenshot (15)](https://user-images.githubusercontent.com/111273048/186328516-f457fe83-8386-4ee0-bd5b-6f33c0c790da.png)

**Comment by unixfox** [comment]
The instance that you are using is having some issues, please switch to another searxng instance on https://searx.space/
