### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by Ytachi1000** [searxng/searxng#1710]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.14-e67ed894

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadError
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 0
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Please [look out for existing issues](https://github.com/searxng/searxng/search?q=Bug%3A+brave+engine&type=issues) and fill in the form.  Without information we can not help you. Since percentage is by zero I think these are temporary error messages.
