### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by Mandeezo** [searxng/searxng#1711]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.15-7bf4e8d1

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('./h2', 'len(xpath_str) < 1')`
  * File name: `searx/engines/xpath.py:193`
  * Function: `response`
  * Code: `title = extract_text(eval_xpath_list(result, title_xpath, min_len=1))`

**Comment by return42** [comment]
Please [look out for existing issues](https://github.com/searxng/searxng/search?q=Bug%3A+mojeek+engine&type=issues) and fill in the form.  Without information we can not help you. If you are using a public instance, please give the URL.

**Comment by cicai1631** [comment]
me too

**Comment by return42** [comment]
@cicai1631 @Mandeezo how often need way say: please give us more information (answer the questions in the form), without we can't reproduce the issue and we can't help .. I reopen the  issue as soon we have all infos.
