### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by nicfab** [searxng/searxng#1726]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.29-242db531

**How did you install SearXNG?**
I installed SearXNG using searxng-docker

**What happened?**
After launching a search I receive the error you can see in the image I attached.

**Screenshots & Logs**
See the image I attached

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response 
  
![CleanShot 2022-08-31 at 08 53 05](https://user-images.githubusercontent.com/24752671/187613088-65c2268b-2fe1-4e70-8ed2-1600070f9f44.png)
= req(params['url'], **request_args)`

**Comment by unixfox** [comment]
Duplicate of https://github.com/searxng/searxng/issues/1651

**Comment by return42** [comment]
Hi @nicfab the "too many requests" come from the origin https://search.brave.com/ there is not much we can do.

~You enabled the brave engine by default (in your `settings.yml`) that means whenever a search query (in category "general") is done a request is send to brave.com --> with the result brave.com will block you very often.~

Sorry, my fail .. we should disable brave by default:

- https://github.com/searxng/searxng/pull/1729

IMO [the brave engine we have](https://github.com/searxng/searxng/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fsearxng%2Fsearxng%2Fblob%2F242db5311817c1f8b9ab6b428060e3eb2a4aea76%2Fsearx%2Fsettings.yml%23L1837-L1860) is not a very good search engine to be enabled by default .. it does by example do not support languages .. this and the limit of queries we can send before been blocked are also reasons why we diced not to enable this engine in SearXNG's default settings.

For any further discussion lets use #1651

**Comment by nicfab** [comment]
Thank you.
Is there a setting for the settings.yaml to set by default to avoid brave?

**Comment by return42** [comment]
Use `disabled: true` to disable a engine by default ([doc](https://docs.searxng.org/admin/engines/settings.html#engine-settings)).

Yesterday we merged:

- https://github.com/searxng/searxng/pull/1729

.. when you update our SearXNG instance brave is disabled by default.

**Comment by nicfab** [comment]
Thank you.
To update my instance, I will run the commands that I find here: [https://github.com/searxng/searxng-docker#how-to-update-](https://github.com/searxng/searxng-docker#how-to-update-) and precisely:
```
- docker compose pull
- docker compose down
- docker compose up -d
```
My settings related to the engine (including disabling brave) in the `settings.yaml` file under the folder `/usr/local/searxng-docker/searxng` are:

```
engines:
  - name: google
    use_mobile_ui: true

  - name: brave
    disabled: true

  - name: bing
    disable: false
```
I disabled brave, but I continue seeing it in Preferences -> tab Engines
Is everything correct?

**Comment by unixfox** [comment]
Disable it on the preferences then.

**Comment by nicfab** [comment]
> Disable it on the preferences then.

Yes, of course.
I meant that if I disable brave from the file `settings.yaml`, however, I continue seeing it in the Preferences -> tab Engines

**Comment by unixfox** [comment]
Sometimes it's just because you previously saved the preferences, so searxng won't touch your personal settings in case you modified the parameters from the system.

By the way, we are getting a bit off-topic. Would prefer if you open a discussion here: https://github.com/searxng/searxng/discussions if you want to talk more about it.
