### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by nicfab** [searxng/searxng#1727]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.29-242db531

**How did you install SearXNG?**
I installed SearXNG using searxng-docker

**What happened?**
After having launched a search I receive that error. 

**Screenshots & Logs**
See the screenshot attached.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

![CleanShot 2022-08-31 at 08 53 05](https://user-images.githubusercontent.com/24752671/187613806-5eaf8bff-565e-438e-8e09-f8a3d5bfe9ed.png)

**Comment by unixfox** [comment]
Please see https://github.com/searxng/searxng/issues/1429#issuecomment-1173161759

**Comment by nicfab** [comment]
Thank you. I see.
However, I installed searxng with docker.
How can I add a proxy server?
