### ISSUE TITLE
[Suggestion] Improve "General" view

### ISSUE THREAD

**Issue by Ridhubharan** [searxng/searxng#1731]
The "General" view in the SearXNG is lacking features such as,

- Show more images
- Show on map (for places)
- Detailed info from Wikipedia

## Comparing with DuckDuckGo
![Screenshot from 2022-09-01 11-45-04](https://user-images.githubusercontent.com/41824719/187845213-192d8c27-54cd-42cc-9138-fab514c9894e.png)

![Screenshot from 2022-09-01 11-07-55](https://user-images.githubusercontent.com/41824719/187845086-339e3edb-5c29-4844-b36a-cf4ed71cc6c1.png)

## How Wiki data is handled in DuckDuckGo
![Screenshot from 2022-09-01 11-45-35](https://user-images.githubusercontent.com/41824719/187845347-35de7a52-42a0-440f-99ff-37bf901a80ce.png)

**Comment by return42** [comment]
Except "Show more images" SearXNG gives the links you asked for ..

![grafik](https://user-images.githubusercontent.com/554536/228551913-07098089-de79-4111-a86b-e3ae9999cc5b.png)

For "Show more images"  click on the image category.
