### ISSUE TITLE
[Suggestion] Improve "Videos" tab

### ISSUE THREAD

**Issue by Ridhubharan** [searxng/searxng#1732]
The videos in SearXNG are shown in a list view, which is not ideal for viewing videos. It will be much better if the videos are shown in a grid.

## Comparing to DuckDuckGo
![Screenshot from 2022-09-01 11-10-13](https://user-images.githubusercontent.com/41824719/187846592-96cd49f2-6499-4570-93ff-f47cd4ad6e1b.png)
![Screenshot from 2022-09-01 11-09-54](https://user-images.githubusercontent.com/41824719/187846739-b8fc9f8b-8457-4b2d-a358-a90f5deb2e6c.png)

**Comment by return42** [comment]
We show more meta data about the video, we got from engines like qwant.

We prefer this result-list layout over a gallery style .. in the future we will improve video layout slightly but it is not planed to have a video gallery .. PRs are welcome but I will close this request.

![image](https://user-images.githubusercontent.com/554536/187873778-7a3e4641-3ea2-4f7d-861a-a21a464c38e4.png)
