### ISSUE TITLE
[Suggestion] Add a good map view provider

### ISSUE THREAD

**Issue by Ridhubharan** [searxng/searxng#1733]
The current maps view provides a list of link from openstreetmaps, rather than opening it directly in the map. Eg: DuckDuckGo incorporates Apple maps.

## Comparing with DuckDuckGo
![Screenshot from 2022-09-01 11-08-49](https://user-images.githubusercontent.com/41824719/187847710-3e130dfb-5103-476b-8588-ba9d28209542.png)
![Screenshot from 2022-09-01 11-08-23](https://user-images.githubusercontent.com/41824719/187847735-20df5580-ccbc-4f77-9022-5e0cdc3a2432.png)

**Comment by return42** [comment]
You can use the show map / hide map link ..

![image](https://user-images.githubusercontent.com/554536/187872025-0dbc976f-8c34-42b0-88e5-23b4a5aa23ee.png)

**Comment by Ridhubharan** [comment]
Sure. But don't you think showing all results in a single map view is easier to use, rather than showing results in a list of options?

**Comment by return42** [comment]
> showing all results in a single map view 

SearXNG shows results from multiple engines.

**Comment by dalf** [comment]
Actually, this is https://github.com/searxng/searxng/issues/1261
I don't see technical limitation to do that:
* The results from the various engines can be shown on the left, the map on the right.
* There are some CSS rules to display the full size images on the right (for results of the type `image.html`). May be some of them can be use to display a big map.

But same as usual, it requires time to implement such feature.
