### ISSUE TITLE
[Suggestion] Use "meaning" as a special search term

### ISSUE THREAD

**Issue by Ridhubharan** [searxng/searxng#1734]
## Comparing with Google
![Screenshot from 2022-09-01 12-08-49](https://user-images.githubusercontent.com/41824719/187848278-e9112147-23a6-42fb-a881-a7bae1d14979.png)
![Screenshot from 2022-09-01 12-08-31](https://user-images.githubusercontent.com/41824719/187848299-59204c42-13d9-42d0-b032-93cb40ff7748.png)

**Comment by dalf** [comment]
It is difficult to parse all Google result types: weather, unit conversion, map and meaning in this case ( technically https://github.com/searxng/searxng/issues/1642 provides a way to get all of the data, but the UI for each cases have to be implemented).

This is also related to https://github.com/searxng/searxng/issues/56 where the idea is to trigger some engines with the prefix `define:`.

However, right now, you can use `!dictionaries demeanor`
![image](https://user-images.githubusercontent.com/1594191/188070053-12abb361-f039-4f73-b663-39412b30781a.png)

(I'm aware that the result is not as straightforward as the one the google one)

**Comment by return42** [comment]
> Use "meaning" as a special search term 

Closed as not planned.

------

> However, right now, you can use `!dictionaries demeanor`

additional tip: don't use "default" language ...

![grafik](https://user-images.githubusercontent.com/554536/228549777-879ad591-ca07-417b-95d3-765208bc0d46.png)

Use the language or locale you are looking for ..

![grafik](https://user-images.githubusercontent.com/554536/228549683-e3f77787-9e43-4425-99ad-da241ebd5e69.png)
