### ISSUE TITLE
Startpage EU server search

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#1751]
**Working URL to the engine**
https://eu.startpage.com/

**Why do you want to add this engine?**
https://support.startpage.com/hc/en-us/articles/4521239495828

Avoids queries being handled inside the US.

**Additional context**
It's Startpage but without using their US servers.

Slower if the instance is closer to the US than the EU.

**Comment by unixfox** [comment]
Should note that this won't decrease the latency because startpage already route to the closest server.

Forcing to a specific server will only make sure that the requests goes to a European or US server.

**Comment by return42** [comment]
We do not need to add a new engine / update your SearXNG instance and .. 

In your settings set:

```yaml
  - name: startpage
    base_url: https://eu.startpage.com
    search_url: https://eu.startpage.com/sp/search

```

Then the requests will send to eu.startpage.com:

```
DEBUG   searx.engines.startpage       : data: {'query': 'foo', 'cat': 'web', 't': 'device', 'sc': 'dIKZ38yDNPOD20', 'with_date': '', 'language': 'deutsch', 'lui': 'deutsch', 'abp': '1'}
DEBUG   searx.network.default         : HTTP Request: POST https://eu.startpage.com/sp/search "HTTP/1.1 200 OK" (text/html; charset=utf-8)
```
