### ISSUE TITLE
Error Installing SearXNG with the "Installation Script"

### ISSUE THREAD

**Issue by emrakyz** [searxng/searxng#1752]
I am using Arch Linux, freshly updated with "pacman -Syu". I can run SearX by using the script but not SearXNG. After installation I get errors and then "127.0.0.1:8888" gives no results. I have removed everything with scrips before trying.

I am using a high end desktop with ethernet gigabit connection.

Screenshot of the errors:
![photo_2022-09-08_11-56-22](https://user-images.githubusercontent.com/89175311/189084949-0f5e9d77-6fe1-4232-93e5-b5ba760d9d18.jpg)

**Comment by return42** [comment]
> I can run SearX by using the script but not SearXNG.

Thanks for the information, but do not compare the installation procedures of SearX with SearXNG / they do install completely different services (SearXNG does not need morty and filtron by example, instead it has solutions based on a redis installation).

>  am using a high end desktop with ethernet gigabit connection.

FYI: You can run SearXNG on a low budget system.

About your errors from the screenshot .. to comment the errors it is easier when you C&P the messages .. for now I try to comment the screenshot ..

> I have removed everything with scrips before trying.

Seems you had already installed a `searxng-redis` user .. (second line) .. for whatever reason `searxng-redis` group does not exists.

I can also see some commands that ends with a "Permission denied" .. I assume the $HOME folder of `searxng-redis` does not exists.

I recommend to remove the entire installation and try it again.

To remove leftovers from SearX read: https://docs.searxng.org/admin/update-searxng.html#remove-obsolete-services

To remove the broken SearXNG installation:

    sudo -H ./utils/searxng.sh remove all

Before you reinstall SearXNG read https://docs.searxng.org/admin/installation-scripts.html#installation-scripts carefully.

The Script is tested on archlinux and it worked 100 times, I assume the issues you have are specific to your method or environment ...

When installing, read the messages from the script carefully .. if you see some issues stop installation and come back here and ask your questions.

**Comment by emrakyz** [comment]
I have removed everything for SearX and SearXNG with their respective scripts and I also checked manually. I give read, write, execute permissions for all users, for the folder I use for installation. Then I updated the system, clone SearXNG and installed with the script. This time I get no errors but still, "127.0.0.1:8888" gives no results.

I have tried: `sudo -H ./utils/searxng.sh instance update`
                    `sudo -H ./utils/searxng.sh instance inspect`
                    `sudo -H ./utils/searxng.sh instance check`

```
SearXNG checks
--------------
INFO:  [OK] (old) account 'searx' does not exists
INFO:  [OK] (old) account 'filtron' does not exists
INFO:  [OK] (old) account 'morty' does not exists
INFO    searx                         : merge the default settings ( /usr/local/searxng/searxng-src/searx/settings.yml ) and the user setttings ( /etc/searxng/settings.yml )
INFO    searx                         : max_request_timeout=None
INFO    searx.shared                  : Use shared_simple implementation
INFO    searx.shared.redis            : connected redis DB --> default

Inspect SearXNG instance
========================

INFO:  wrapper:  utils/searxng.sh instance _call _searxng.instance.inspect
/usr/local/searxng/searxng-src/utils/lib.sh: line 15: hostname: command not found
uWSGI:
  SEARXNG_UWSGI_SOCKET : /usr/local/searxng/run/socket
environment /usr/local/searxng/searxng-src/utils/brand.env:
  GIT_URL              : https://github.com/searxng/searxng
  GIT_BRANCH           : master
  SEARXNG_URL          : http://username/searxng
  SEARXNG_PORT         : 8888
  SEARXNG_BIND_ADDRESS : 127.0.0.1
INFO:  uWSGI socket is located at: /usr/local/searxng/run/socket
ERROR: Public service at http://username/searxng is not available!
```

**Comment by return42** [comment]
Installation works .. SearXNG listens on socket https://docs.searxng.org/admin/architecture.html (not TCP)

Now you need to connect your reverse proxy to the socket .. we have scripts for nginx or apache https://docs.searxng.org/admin/installation-scripts.html#installation-scripts

**Comment by emrakyz** [comment]
Thanks for the response. I still can't access it. Here is the output I get after: `sudo -H ./utils/searxng.sh install nginx`

```
Install nginx site searxng.conf
===============================

This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
located at: /etc/nginx/default.apps-available/searxng.conf and requires
a uWSGI.
INFO:  uWSGI socket is located at: /usr/local/searxng/run/socket
INFO:  Nginx packages are installed [OK]
INFO:  checking existence: 'include /etc/nginx/default.d/*.conf;' in file /etc/nginx/nginx.conf
        include /etc/nginx/default.d/*.conf;
INFO:  OK, already exists.
INFO:  install (eval=1): /etc/nginx/default.apps-available/searxng.conf
INFO:  variant --> :socket
INFO:  BUILD /home/emre/searxng/cache/etc/nginx/default.apps-available/searxng.conf:socket
INFO:  BUILD using template /home/emre/searxng/utils/templates/etc/nginx/default.apps-available/searxng.conf:socket
INFO:  file /etc/nginx/default.apps-available/searxng.conf already installed
INFO:  enable nginx app: searxng.conf
INFO:  reload nginx ..

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
INFO:  installed nginx app: searxng.conf
INFO:  got 502 from http://emre/searxng
```

**Comment by return42** [comment]
Is `emre` the hostname / what does `ping emre` say?

**Comment by emrakyz** [comment]
It's a newly built Arch Linux with not much of a special configuration.
![image](https://user-images.githubusercontent.com/89175311/189321837-b5b17897-0b47-4f56-969d-8d3cce35d474.png)

**Comment by return42** [comment]
OK name and name resolution works .. what says:

    curl -v http://127.0.0.1/searxng

**Comment by emrakyz** [comment]
```
[emre@emre ~]$ curl -v http://127.0.0.1/searxng
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /searxng HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.85.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.21.6
< Date: Fri, 09 Sep 2022 10:47:35 GMT
< Content-Type: text/html
< Content-Length: 497
< Connection: keep-alive
< ETag: "6203a95b-1f1"
<
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the error log for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by emrakyz** [comment]
Any idea on how to proceed? Let me explain what I completely did:

Firstly, I have removed everything related with SearX and SearXNG as it's explained in the manuals. Then:

```
$ sudo chmod ugo+rwx ~/Downloads
$ cd ~/Downloads
$ git clone https://github.com/searxng/searxng.git searxng
$ cd searxng
$ sudo -H ./utils/searxng.sh install all
$ sudo -H ./utils/searxng.sh install nginx
```
They all finish with no errors. But I still can't access the site. Can the problem occur because of my internet connection? My service provider uses a system called IP Pool, so I don't have a static IP and I can't even open ports. Even port numbers such as 80 give no results. On SearX we don't need to use services such as NginX, I guess that's why I can run it and not SearXNG. What do you think about it?

**Comment by return42** [comment]
> Can the problem occur because of my internet connection? My service provider uses a system called IP Pool, so I don't have a static IP and I can't even open ports. 

Now I'am a little bit confused.  Do you want to reach the SearXNG server from the internet or from your intranet? I assumed you are installing a SearXNG instance somewhere in your intranet.

> On SearX we don't need to use services such as NginX, I guess that's why I can run it and not SearXNG. What do you think about it?

The installation scripts are made to install this [architecture based on a uWSGI service](https://docs.searxng.org/admin/architecture.html).

**Comment by emrakyz** [comment]
I want to reach SearXNG locally, from my computer. I won't make it a public instance. I want to access it from 127.0.0.1:8888. My problem is that I can access SearX just by running the one installation scriptl; then I can access it locally. But for SearXNG; I run the installation script + nginx installation script. They all finish with no errors but 127.0.0.1:8888 gives nothing. For now, I use public instances but I would like to install it on my machine though. Thanks, anyways.
