### ISSUE TITLE
Simple theme tasks

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#176]
From:
* issue 1025 in searx
* https://github.com/searxng/searxng/issues/162

### General : UI
- [x] replace LESS variables by CSS variables, so the user can choose the line height, dark / light easily (?)
- [x] footer at the botton of the page: see https://github.com/dalf/searxng/commit/df0914e3b5298585015467abb0f9edd01e48dfea
- [x] center or move the results to the right.
- [x] redo color theme and just overall bigger UI elements; round corners and so on (right now its a little blunt)
- [x] add dark and black theme

see https://joe-crick.github.io/pure-css-components/

### General : UX
- [x] infinite_scroll plugin settings
- [x] opening pages in a new tab settings
- [x] do the RTL style 
- [x] engine crash warning : add a close button
- [ ] infoboxes : some properties value should be a link to another search ( ```Programming language :Python```  --> be able to click on ```Python``` to search that on searx)

###  Search
- [x] update HTML input attributes: see https://github.com/benbusby/whoogle-search/blob/main/app/templates/search.html
- [x] add safe search right to Language combobox and Time combobox
- [x] apply #1226 to Simple theme ( https://github.com/searx/searx/pull/1226 )

### On mobile
- [x] do not set the focus on the search input text : the keyboard hides the results.
- [x] make the search input smaller when without focus to give space for the logo and the preferences button. With focus, make it full width wide as now.
- [ ] embedded videos on mobile : too large, outside the screen
- [ ] selected category on mobile : scroll to the first selected category.

### Image category
- [x] give the user the choice to view the page a image is from instead of the actual image source

### Reduce the network usage
- [ ] create a small bandwidth version using javascript (use JS to add languages choices, cached links, categories)

**Comment by return42** [comment]
### On mobile
- [x] add a link to the preference menu
- [x] add link to _about_ section

**Comment by mrpaulblack** [comment]
I dont understand this one:

> add link to about section (On mobile)

There is also the about section link in the footer on mobile? @return42

**Comment by return42** [comment]
I miss a clear link to the [about page](https://darmarit.org/searx/about)

ATM we have a link _more or less hidden_ in the footer under the word "searxng"

![grafik](https://user-images.githubusercontent.com/554536/148656192-5c58c34e-e027-41cf-9d81-a16cf5bcb711.png)

I think we need the "about" link at a more visible place.

---

The about page has some hints which might have a value for the users (e.g. browser integration, see below) 


![grafik](https://user-images.githubusercontent.com/554536/148656324-5ac46d19-a51f-462f-88ab-443ada172f6b.png)

**Comment by return42** [comment]
We have already implemented 15 out of 19 of the requirements; the four requirements shown below remain.  In my opinion, these are new features and should (if interested) also be created as such issues --> they will not attract any attention here in this issue

-------------

### General : UX
- infoboxes : some properties value should be a link to another search ( ```Programming language :Python```  --> be able to click on ```Python``` to search that on searx)

### On mobile
preferences button. With focus, make it full width wide as now.
- embedded videos on mobile : too large, outside the screen
- selected category on mobile : scroll to the first selected category.

### Reduce the network usage
- create a small bandwidth version using javascript (use JS to add languages choices, cached links, categories)
