### ISSUE TITLE
Bing engine gives invalid "rebates" result URLs

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1764]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.09.04-691c0ed6
**How did you install SearXNG?**
searxng-docker
**What happened?**
I'm getting these URLs on some queries.
![image](https://user-images.githubusercontent.com/49014564/189696831-57cda7d7-1ab3-4426-a2a3-3524e68bdd6f.png)
![image](https://user-images.githubusercontent.com/49014564/189696274-9300fa86-2ff3-404c-bc1d-c35af359a972.png)
**How To Reproduce**
You can get it by searching "Bookworm Adventures Gift". Using **!bi** doesn't make it popup, needs to be with other engines.
**Expected behavior**
Either not include these in results or have a valid URL.

**Comment by return42** [comment]
Sorry, can't reproduce the issue you reported .. is your instance public, can I try it on your instance?

**Comment by ghost** [comment]
Instance isn't public but I will send you an email with the URL in a moment.

Edit: Sent

**Comment by return42** [comment]
> Edit: Sent

Thanks!

I can reproduce the issue on your instance .. when I search on https://www.bing.com/ the correct item is:

![image](https://user-images.githubusercontent.com/554536/189705627-63123ccf-d8fb-4dc9-acdb-b7f2d58e8b70.png)

Very strange.

**Comment by dalf** [comment]
bing.py fetches the URL with two different methods:
1. first it tries to the displayed URL if it is not truncated
1. second, it follow the HTTP redirect `https://www.bing.com/ck/a?`.

Perhaps the [truncated detection URL](https://github.com/searxng/searxng/blob/eb3d185e66dea1add88ef8d3a3c6bb74b8a3b166/searx/engines/bing.py#L99-L102) doesn't work for this result.

**Comment by AlyoshaVasilieva** [comment]
In brief testing, this fixed it:
```python
        if url.startswith('/rebates/welcome?'):
            url = parse_qs(urlparse(url).query)["url"][0]
```

I don't know Python though and don't know if this needs error handling, how reliable it is, etc.

Rebates results also seem to have slightly different layout judging by the way searx doesn't read descriptions from them.

edit: To repro, `!bi vmware` on a US-based instance

**Comment by return42** [comment]
Issue can't be reproduced, see https://github.com/searxng/searxng/pull/2171#pullrequestreview-1376734283
