### ISSUE TITLE
Results based on location

### ISSUE THREAD

**Issue by bphd** [searxng/searxng#1766]
SearXNG is a wrapper for our browser to send request to multiple search engines or is a standalone search engine who makes request himself into the instance where it's running and returning us the result?

I ask that because I get result depending on my location with Qwant and DuckDuckGo. I thought that the S.E. was meant partly to protect my privacy by not leaking my data, but here, when DDG and QW doesn't know what to reply, it replies with news and ads from my location, in my country language

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.09.09-eb3d185e 

**How did you install SearXNG?**

Just using an instance

**What happened?**

Results based on my data (language and location)

**How To Reproduce**

Select at least DuckDuckGo and Qwant and make research without many results (to not get a 404 but not getting relevant results too)

**Expected behavior**

Results only in the selected language on the SearXNG engine (other languages are not a problem if they're based on the request and not the locale of our computer. For example, asking about “karambolage” should normally return a result in German even if SearXNG is in English, and it's okay here)

And ideally without any results based on the location (because irrelevant, we want anonymous results). At worst based on the location of the instance, not of the user of the S.E.

**Screenshots & Logs**

**Additional context**

**Comment by return42** [comment]
> I ask that because I get result depending on my location with Qwant and DuckDuckGo. 

Do you use a public SearXNG or do you have a local instance running on your Desktop (Laptop)?

SearXNG does not send any data from its users to the origin engine (qwant, google ..).

But the origin engine sees the IP of the SearXNG server when the SearXNG server sends the request to the origin search engine .. some search engines (may be quant) return results based on this IP (the IP based geolocation of the SearXNG server).

**Comment by bphd** [comment]
Not an instance on my computer. Otherwise, it should be more natural to get results depending on my computer locale (“At worst based on the location of the instance”)

Okay, if it's based on the instance, then it's okay, it's not my data. Maybe the instance is near from me, so I get results from my location, or near it

So maybe anonymize the results from the instance view? I know it's difficult because the origin engine does what he wants with the IP asking him, but this problematic should be considered anyway

**Comment by return42** [comment]
> So maybe anonymize the results from the instance view?

That is not possible there must be a SearXNG server that sends the request to the origin search engine .. you can't hide the IP of the request / except: some SearXNG engines use a tor network to connect to the origin search engine.

**Comment by bphd** [comment]
Tor seems to be the way for this problematic, shuffle each time the circuit, making the result each time different on this point. For that, searching for a paranoid instance or making it ourselves

Anyway, it doesn't use user locale or location, so it's okay
