### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chiragnahata** [searxng/searxng#1782]
Searxng is not working on my docker please help asap ? It is installed but not starting

**Comment by return42** [comment]
First, this is not searxng-docker. Second, its not a SearXNG bug. Third; when asking questions with the hint "ASAP" its better to visit the Matrix room [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org). Fourth,  if you want to get help, "not working" is not enough
