### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by Targren** [searxng/searxng#1788]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.09.19-f98ef718

**How did you install SearXNG?**

Searxng-docker

**What happened?**

Search results show brave failing with "Unexpected Crash"

**How To Reproduce**

Enable brave engine
Perform any web search 

**Expected behavior**

Not crash, unexpectedly or otherwise

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by dalf** [comment]
https://github.com/searxng/searxng/pull/1787 was supposed to fix this issue (httpx.DecodingError), it seems it is not the case.

**Comment by Rolzzz** [comment]
same issue here

Errors and exceptions
Exception	httpx.DecodingError	Percentage	100
Parameter	NoneNonesearch.brave.com
Filename	searx/search/processors/online.py:107
Function	_send_http_request
Code	response = req(params['url'], **request_args)

**Comment by OverthinkingTech** [comment]
I'm getting the same error. I'm using searxng-docker, I just checked and I'm on the newest version.

**Comment by AlyoshaVasilieva** [comment]
I recently set up a new (private) instance via the installation script, I'm on f98ef718, and Brave is working fine. (Maybe Brave is doing something weird if it decides SearXNG is a bot? Maybe I'm just lucky?)

**Comment by CypherDragon** [comment]
Running searxng version 2022.09.21-b1699f18 from searxng-docker, and still having the same issue after recreating the container with the latest image.

Exception | httpx.DecodingError | Percentage | 100
None None search.brave.com
searx/search/processors/online.py:107
_send_http_request
response = req(params['url'], **request_args)

**Comment by dalf** [comment]
For the record : https://github.com/encode/httpx/discussions/2374

**Comment by unixfox** [comment]
Can't you force gzip only compression using the HTTP headers?

**Comment by dalf** [comment]
> Can't you force gzip only compression using the HTTP headers?

PR #1787 is supposed to do that. It fixes the issue on my laptop and on my instance.

**Comment by OverthinkingTech** [comment]
For anyone else looking at this, when I pulled the new version it used my old settings.yml file. A new file called settings.new.yml was generated. If you replace the section defining Brave searches in your old file with the section for brave searches in the new file, then it works.

Ultimately this approach worked well as it kept my current settings and if the URL had been changed in the settings file nothing would have worked through my reverse proxy.

**Comment by CypherDragon** [comment]
> For anyone else looking at this, when I pulled the new version it used my old settings.yml file. A new file called settings.new.yml was generated. If you replace the section defining Brave searches in your old file with the section for brave searches in the new file, then it works.
> 
> Ultimately this approach worked well as it kept my current settings and if the URL had been changed in the settings file nothing would have worked through my reverse proxy.

Can confirm, this fixed the issue on my instance as well. The settings.yml just needed the following added in the brave engine config:

`headers:
      Accept-Encoding: gzip, deflate`

Add that, restart the container, and Brave works as expected

**Comment by Rolzzz** [comment]
> Can confirm, this fixed the issue on my instance as well. The settings.yml just needed the following added in the brave engine config:
> 
> `headers: Accept-Encoding: gzip, deflate`
> 
> Add that, restart the container, and Brave works as expected

can u share full syntax please as I tried various attempts but still mine fails.

**Comment by CypherDragon** [comment]
> can u share full syntax please as I tried various attempts but still mine fails.

Sure, make sure that /etc/searxng/settings.yml looks like this for the brave section:
![image](https://user-images.githubusercontent.com/45954806/192122307-3c6c9545-ddce-4ca5-9e51-028709415805.png)

**Comment by Rolzzz** [comment]
> > can u share full syntax please as I tried various attempts but still mine fails.
> 
> Sure, make sure that /etc/searxng/settings.yml looks like this for the brave section: 

cool that worked for me too... interesting that my settings.yml was very very basic... I had no engine details in it...
got an example here so I didn't have to copy paste and it already had the line in it.

https://github.com/searxng/searxng/blob/master/searx/settings.yml

**Comment by return42** [comment]
> I had no engine details in it...

You have a [`use_default_settings: true`](https://docs.searxng.org/admin/engines/settings.html#use-default-settings) line in your `/etc/searxng/settings.yml` what means all the (default) settings from the SearXNG instance (the file you linked) are used.

In [PR-1787](https://github.com/searxng/searxng/pull/1787/files) the [`Accept-Encoding: gzip, deflate`](https://github.com/searxng/searxng/blob/94c4cc126b16d4cd1653c410df63af4bc0a4e998/searx/settings.yml#L1861-L1862) was merged --> To get the fix, you just need to update your SearXNG instance .. there should no need to modify the brave settings in your local `/etc/searxng/settings.yml`.

**Comment by Rolzzz** [comment]
> > I had no engine details in it...
> 
> You have a [`use_default_settings: true`](https://docs.searxng.org/admin/engines/settings.html#use-default-settings) line in your `/etc/searxng/settings.yml` what means all the (default) settings from the SearXNG instance (the file you linked) are used.
> 
> In [PR-1787](https://github.com/searxng/searxng/pull/1787/files) the [`Accept-Encoding: gzip, deflate`](https://github.com/searxng/searxng/blob/94c4cc126b16d4cd1653c410df63af4bc0a4e998/searx/settings.yml#L1861-L1862) was merged --> To get the fix, you just need to update your SearXNG instance .. there should no need to modify the brave settings in your local `/etc/searxng/settings.yml`.

I thought running "docker-compose down" and then "docker-compose up -d" should pull down latest version of the docker instance of searxng? 

anyway, I decided to stop the docker instance, rename the settings.yml and then started the docker instance back up and saw it generated a new settings.yml file... this time is was quite a bit larger than my old one... but again was missing the "headers: Accept-Encoding: gzip, deflate" part. 

So I added that line back in and all is good... so for me that workaround is working, whilst it sounds like something with the docker image might need updating and will probably be done in time :)

**Comment by CypherDragon** [comment]
> In [PR-1787](https://github.com/searxng/searxng/pull/1787/files) the [`Accept-Encoding: gzip, deflate`](https://github.com/searxng/searxng/blob/94c4cc126b16d4cd1653c410df63af4bc0a4e998/searx/settings.yml#L1861-L1862) was merged --> To get the fix, you just need to update your SearXNG instance .. there should no need to modify the brave settings in your local `/etc/searxng/settings.yml`.

I've been updating mine regularly (even a couple times a day sometimes) because of this issue, and had to put it in manually to fix it. I'm using portainer to manage and recreate the container, so could be an issue with the portainer recreate process? I'd be more than willing to troubleshoot further, if there's a decent process you could provide...

**Comment by return42** [comment]
> I thought running "docker-compose down" and then "docker-compose up -d" should pull down latest version of the docker instance of searxng?
..
> I'm using portainer to manage and recreate the container, so could be an issue with the portainer recreate process?

@CypherDragon, @Rolzzz Sorry I can't help with docker / if you have problems with updating a docker instance, please move to the https://github.com/searxng/searxng-docker repository.

Since the origin issue is fixed in https://github.com/searxng/searxng/pull/1787 I am going to cloes this issue.
