### ISSUE TITLE
Google News results have broken description

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#1790]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
f98ef718de5638f2f1a610d472438c80b51cc139

**How did you install SearXNG?**
Installation script, also occurs on public instances
**What happened?**
Google News articles have broken descriptions
**How To Reproduce**
Search news with Google News engine enabled

**Expected behavior**
Descriptions to exist, since Google provides them

**Screenshots & Logs**
![broken description](https://user-images.githubusercontent.com/1284317/191242976-29a450e2-8ba1-481a-b16d-6f8ad71045d8.png)

**Comment by return42** [comment]
@AlyoshaVasilieva thanks for reporting the issue / I send PR #1791 .. could you please give it a try / thanks!
