### ISSUE TITLE
Option to disable User-Agent randomization

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#1793]
**Is your feature request related to a problem? Please describe.**
Recently Startpage began presenting a captcha to my private instance. I proxied through the VPS and looked at Startpage.com and the captcha page specifically asked me if I was purposefully changing my User-Agent.

**Describe the solution you'd like**
An option for the instance to just present itself with a static User-Agent, like 'latest Firefox on Linux', instead of randomly changing claimed version/OS.

**Describe alternatives you've considered**
Alternatively, don't do this.

**Additional context**
I'm not sure if random User-Agents have any benefit to instances that aren't using proxies or have a lot of IPs. For instances that do, I think locking IPs/proxies to specific user-agents might make them more believable as a real browser.

**Comment by return42** [comment]
> I think locking IPs/proxies to specific user-agents might make them more believable as a real browser.

I don't think so .. for all request from the various devices of a subnet (company or your subnet at home) startpage sees the same IP.

**Comment by dalf** [comment]
Multiple browsers means the IP address is shared between several devices or ... browsers: it changes the fingerprint, so all queries are less likely to be grouped together.

However, you implement what you wish on your own instance.

Change 
https://github.com/searxng/searxng/blob/master/searx/data/useragents.json

to something like this:

```json
{
    "versions": [
        "104.0",
    ],
    "os": [
        "Windows NT 10.0; Win64; x64",
    ],
    "ua": "Mozilla/5.0 ({os}; rv:{version}) Gecko/20100101 Firefox/{version}"
}
```

so there is only one version and one OS.

**Comment by return42** [comment]
> Recently Startpage began presenting a captcha to my private instance. 

An "Option to disable User-Agent randomization" would not help to avoid Startpage's CAPTCHA. 

--> Close as not planed.

----

These PRs have improved the situation but do not solve the CAPTCHA problem we have with Startpage entirely: 

- https://github.com/searxng/searxng/pull/2269
- https://github.com/searxng/searxng/pull/2266

and see my https://github.com/searxng/searxng/issues/1081#issuecomment-1488162918

We should discuss any further CAPTCHA from Starpage in a new issue.
