### ISSUE TITLE
Google result broken, missing most of the URL

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#1794]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
f98ef718
**How did you install SearXNG?**
Happens on multiple instances.
**What happened?**
Search is missing the hostname/path, URL is broken

**How To Reproduce**
`!go mizkif`

The result URL is `http://search/?lr=lang_en&tbs=lr:lang_1en&source=univ&tbm=isch&q=mizkif&hl=en&fir=aQ1ie7SCjSYz0M%252C41y_7ULhHPQDpM%252C_%253BJaheLPsu0itTgM%252C4FyxlM_4LRayJM%252C_%253B-lgeSY5nJmpNHM%252Cf1iK_SaqyloYVM%252C_%253BbZT4PewNy6CzBM%252CHC0EEflPUXyxDM%252C_&usg=AI4_-kQ7XZ97He9bLUZO4-QTghBdHe4IqQ&sa=X&ved=2ahUKEwjdm9TImqX6AhXtSvEDHfCqDMMQiR56BAgiEAI`

Occurs on my private instance, search.ononoki.org, searx.be, searx.tiekoetter.com, probably others

**Expected behavior**
Result has working URL

**Screenshots & Logs**
![mizkif](https://user-images.githubusercontent.com/1284317/191426134-16501ad6-3a16-47fb-a961-92ff59ccecb5.png)

**Additional context**
I *think* the result is a Twitch profile.

**Comment by return42** [comment]
I can't reproduce the issue in a `make run` nor on my instance / here is what I tested 

- https://darmarit.org/searx/search?q=!go+mizkif --> OK (my instance)
- https://search.ononoki.org/search?q=!go+mizkif --> broken
- https://searx.be/search?q=%21go%20mizkif --> OK  (seems not the google engine from master)
- https://searx.tiekoetter.com/search?q=!go+mizkif --> broken
- https://paulgo.io/search --> OK

@ononoki, @tiekoetter .. do you have a clue why google has this issue on your engines?

Or is it just again google, rolling out a new release/design of the HTML result page? .. then it will hit all other instances in the near future.

related? .. https://github.com/searxng/searxng/pull/1648

**Comment by AlyoshaVasilieva** [comment]
It was broken on searx.be for me:

![searx.be](https://user-images.githubusercontent.com/1284317/191435179-9810adf9-772c-4d81-b867-82ad3b93a349.png)

note `http:///search?` URL. Redoing the search again 5 minutes later while writing this comment and it was no longer broken. Redoing the search 1-2 minutes later and it was broken again. This seems to me like Google A/B testing.

Tested additional instances, first try broken also on `trydex.tk`, `searx.priv.pw`, `searxng.zackptg5.com`, `search.rabbit-company.com`, `search.bus-hit.me`.

**Comment by shindouj** [comment]
My instance is affected as well: ![image](https://user-images.githubusercontent.com/4504156/191602934-e1c0638a-a374-436b-839e-036fa0ca19f1.png)

I'm running 2022.09.21-1a7b6872 on Docker.

**Comment by jordemort** [comment]
Also ran into this on some.shady.website

**Comment by austinhuang0131** [comment]
replicable, search.bus-hit.me

**Comment by OverthinkingTech** [comment]
I'm now experience the same issue on my searxng install. Any suggestions or fixes?

**Comment by Shituation** [comment]
Take my friendly advice. Move on to other search engines. These people censores you.
