### ISSUE TITLE
Bug report: Duckduckgo

### ISSUE THREAD

**Issue by bencinium** [searxng/searxng#1812]
**How did you install SearXNG?**
Using the official wiki, no docker.

**What happened?**
When searching, randomly i got time out errors. Sometimes google, sometimes duckduckgo, sometimes qwant, sometimes wikidata.

**How To Reproduce**
Search any term, and you will get a timeout error.

**Expected behavior**
There would be no errors and the search engines results would be shown.
![image](https://user-images.githubusercontent.com/101190404/192159269-3fc6dc90-051c-41eb-bf82-a9c926e7f152.png)

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 20
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:122`
  * Function: `response`
  * Code: `get(url_ping, headers=headers_ping)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 5
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by VrindaGoel06** [comment]
DId you try with a different host under a different ISP and router? did this work before?
Edit: I'm checking on my local instance

**Comment by bencinium** [comment]
> DId you try with a different host under a different ISP and router? did this work before? Edit: I'm checking on my local instance

Yes, I tried other instances and they didnt work. It is something wrong with my instance

**Comment by VrindaGoel06** [comment]
> > DId you try with a different host under a different ISP and router? did this work before? Edit: I'm checking on my local instance
> 
> Yes, I tried other instances and they didnt work. It is something wrong with my instance

If its something wrong with your instance then lets debug that. What version are you on? if you're not on the latest have you tried updating to the latest one?

**Comment by bencinium** [comment]
> > > DId you try with a different host under a different ISP and router? did this work before? Edit: I'm checking on my local instance
> > 
> > 
> > Yes, I tried other instances and they didnt work. It is something wrong with my instance
> 
> If its something wrong with your instance then lets debug that. What version are you on? if you're not on the latest have you tried updating to the latest one?

Im on the latest one, dont know what version that is exactly but i know im on the latest one since i installed it a few days ago.

**Comment by return42** [comment]
> Im on the latest one, dont know what version that is exactly but i know im on the latest one since i installed it a few days ago.

just take a look at the footer .. a screenshot from my instance ..

![grafik](https://user-images.githubusercontent.com/554536/192554083-4a6edcda-3b05-4f74-8b15-f5377b351ec7.png)

last updated at 25. this month .. behind the date, you see the commit hash.

**Comment by bencinium** [comment]
Hm, i ran the update script, but it doesnt seem to have worked. Im still on 2022.9.24. I restarted uwsgi, is there any more i need to do to make this take effect?

**Comment by Shituation** [comment]
Take my friendly advice. Move on to other search engines. These people censores you.

**Comment by return42** [comment]
@bencinium sorry for the late response .. does your update problem resist?

**Comment by return42** [comment]
Closed in lack of feedback
