### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by Mobot13** [searxng/searxng#1815]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
already fixed

**Comment by bufanda** [comment]
> already fixed

@return42 could you elaborate in which commit or Version it is fixed. I currently run  2022.10.14-1a5b0965 and get nearly the same issue here

```


Exception | httpx.DecodingError | Percentage | 100
-- | -- | -- | --
Parameter: None None search.brave.com
Filename: searx/search/processors/online.py:113
Function: _send_http_request
Code: response = req(params['url'], **request_args)

```

**Comment by return42** [comment]
As far I remember it was 33b43763b .. in https://github.com/searxng/searxng/pull/1787

@dalf: May be it was mistake of mine to close this issue and it is not related to https://github.com/searxng/searxng/pull/1787 ?

**Comment by dalf** [comment]
@return42 yes this is exactly this issue.

@bufanda : can you check the definition of the brave engine in your settings.yml?

Is there `use_default_settings: true` at the top of the file? If no, can you add these two lines:
https://github.com/searxng/searxng/blob/1a5b0965789d100a33fad69cf6779b23e6595ef4/searx/settings.yml#L1866-L1867

**Comment by bufanda** [comment]
> @return42 yes this is exactly this issue.
> 
> @bufanda : can you check the definition of the brave engine in your settings.yml?
> 
> Is there `use_default_settings: true` at the top of the file? If no, can you add these two lines:
> 
> https://github.com/searxng/searxng/blob/1a5b0965789d100a33fad69cf6779b23e6595ef4/searx/settings.yml#L1866-L1867

Awsome that works. Thanks very much. You guys rock.
