### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by oc013** [searxng/searxng#1835]
I am currently using the docker image and see there are regular updates which is nice. 

**Is your feature request related to a problem? Please describe.**
When I view either the https://github.com/searxng/searxng or https://github.com/searxng/searxng-docker repos, I do not see releases/tags or any changelog to review what is being changed.

**Describe the solution you'd like**
There should be a changelog to easily review changes made between versions.

**Comment by dalf** [comment]
SearXNG uses the rolling release model.
That's why you see at the bottom of the page some like "2022.10.01-901143f0" instead of "2.1.3" for example.

However, a few days (weeks?) ago, we internally discussed a public changelog that might not be comprehensive but at least better than the long list of commits.

**Comment by ngosang** [comment]
Even if the development is "rolling release" you could publish releases from time to time when there are important fixes (or weekly, monthly).
I know there are tools like Watchtower to auto-update Docker images but I prefer to update manually when I have sparse time. Usually I subscribe to the new releases in GitHub RSS, I read the changelog and I only update if there is something important.
In this project I just run the container until it stops working because there aren't releases.

**Comment by return42** [comment]
> Even if the development is "rolling release" you could publish releases from time to time when there are important fixes (or weekly, monthly).

Its a rolling release .. What "important fixes" are depends on the user, by example if google-Web engine needs a simple patch on its XPaths expressions to scrap results, most users would say its important .. but what would users say when google-News needs the same patch, or yahoo or a niche search engine.

Long story told short:

1. There is no criteria to classify a release with "important fixes".
2. A CHANGELOG would not be more than a list of the [commit messages](https://github.com/searxng/searxng/commits/master)

Closed as not planed.

**Comment by oc013** [comment]
Github even provides "Auto-generate release notes" to provide exactly the long list of commit messages you mentioned. 

There's utility even in that versus reading the entire commit history and trying to figure out from where I last updated. Not to mention the utility of setting up alerts based on when releases are tagged/released.

**Comment by return42** [comment]
> Github even provides "Auto-generate release notes"

A CHANGLOG that is useful for its reader can't be generated by a tool / [Using commit log diffs as changelogs is a bad idea: they're full of noise ... The purpose of a commit is to document a step in the evolution of the source code.  ... The purpose of a changelog entry is to document the noteworthy difference, often across multiple commits, to communicate them clearly to end users. ](https://keepachangelog.com)

.. A useful changelog is a summary of significant changes, new features, announcements, etc. that are summarized in a release.  In a rolling release, each commit to the master branch is a release, so the entries in the CHANGELOG would never be more than the commit messages themselves.

> There's utility even in that versus reading the entire commit history and trying to figure out from where I last updated.

git is the tool for deployment .. when you rebase the branch of your productive instance you see *from where you come and where you will go*.

> Not to mention the utility of setting up alerts based on when releases are tagged/released.

We have a rolling release, we do not set tags .. what should we tag?

**Comment by oc013** [comment]
So we're in agreement then, reading the commit history of the repo is _useless_ and a summary of significant changes would be _useful_ to users.  

To cut a release I've generally tagged a commit then marked that tag as a release.. Maybe you know another way. _My bad._
