### ISSUE TITLE
python setup.py egg_info did not run successfully

### ISSUE THREAD

**Issue by AmyMoriyama** [searxng/searxng#1837]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
https://pastebin.com/raw/hYZNj34A

**How did you install SearXNG?**

git clone then ./utils/searxng.sh install all

**What happened?**

I really don't know.

**How To Reproduce**

I didn't do much other than the above on a "Debian GNU/Linux 11 (bullseye)" headless server.

**Expected behavior**

No error?

**Screenshots & Logs**

https://pastebin.com/raw/kST2Y7LG
Full https://pastebin.com/raw/VHwnwQnY

**Additional context**

I'm entirely new to searxng and python

**Comment by return42** [comment]
```
  |searxng|         File "/usr/local/searxng/searxng-src/searx/settings_loader.py", line 30, in load_yaml
  |searxng|           raise SearxSettingsException(e, file_name) from e
  |searxng|       searx.exceptions.SearxSettingsException: while parsing a block mapping
  |searxng|         in "/etc/searxng/settings.yml", line 50, column 5
  |searxng|       expected <block end>, but found '<block mapping start>'
  |searxng|         in "/etc/searxng/settings.yml", line 65, column 6
```

Do you have a leftover `/etc/searxng/settings.yml` from an old installation? .. delete or fix the file.

**Comment by AmyMoriyama** [comment]
This has been fixed thank you.
