### ISSUE TITLE
searxng fails to install

### ISSUE THREAD

**Issue by droidus** [searxng/searxng#1839]
```
commit 901143f056f784e2f04fc852d667ccfb00962cf4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 14d0fb2c 8d5653e6
Author: Alexandre Flament <alex@al-f.net>
Date:   Sat Oct 1 09:59:07 2022 +0200

    Merge pull request #1830 from MohamedElashri/master
    
    Use official sci-hub mirrors
``` 

**How did you install SearXNG?**
Script

**What happened?**
ls: cannot access '/home/<user>/searxng': Permission denied
ERROR: ./utils/searxng.sh: line 436: user 'searxng' missed read permission: /home/<user>/searxng
Directory (searxng) permissions: drwxrwxrwx

**Additional context**
Running a ubuntu lxc container.

**Comment by return42** [comment]
duplicate: https://github.com/searxng/searxng/issues/1669
