### ISSUE TITLE
simple template points to wrong location for css and js?

### ISSUE THREAD

**Issue by AmyMoriyama** [searxng/searxng#1840]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
https://pastebin.com/raw/ZApiYGhL

**How did you install SearXNG?**
git clone then ./utils/searxng.sh install all

**What happened?**
Well, I was poking around /usr/local/searxng trying my hand at a custom theme/template and noticed that the simple theme has links to js and CSS that don't exist. When corrected, CSS and js works and everything looks nicer. It points to static/blah/blah but should be static/themes/simple/blah

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Comment by dalf** [comment]
> noticed that the simple theme has links to js and CSS that don't exist.

How do you see that? In the devtools of Firefox / Chrome, if yes, which URL do you see?
Which files did you changed related to the themes?

> When corrected, CSS and js works and everything looks nicer. It points to static/blah/blah but should be static/themes/simple/blah

Where do you correct the path?

**Comment by AmyMoriyama** [comment]
https://pastebin.com/raw/CXKyeqXm
in base.html under templates/ folder

The above paste is what I have now which works. I noticed when I was poking around the templates and themes folders.
