### ISSUE TITLE
Bug: yahoo engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1841]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.01-5672f5ad

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 100
  * Parameters: `(None, None, 'nz.search.yahoo.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Can't reproduce this issue .. please update and open a new issue if your problem is not solved.
