### ISSUE TITLE
500 internal sever error

### ISSUE THREAD

**Issue by ElliotBadinger** [searxng/searxng#1843]
Version of SearXNG: 2022.10.05 I am using the master branch I access SearXNG using the websites URL

**What happened?**
I typed in a search query on the website searx.be and as I clicked on the Science field (at the top where the toolbar is) I encountered a 500 internal server error

**How To Reproduce**
Type in any search query and click the science field and you will encounter the error

**Expected behavior**
I should have instead seen search results that show scientific journals, articles and the like after clicking the option

**Additional context**
This problem is only unique to the science section of the toolbar

**Comment by unixfox** [comment]
Invalid because searx.be is using an unsupported theme.

**Comment by ElliotBadinger** [comment]
Could you elaborate further as to what you mean by "unsupported theme"?
