### ISSUE TITLE
after preference setting change and save action i get a invalid response. ERR_INVALID_REDIRECT

### ISSUE THREAD

**Issue by treeby** [searxng/searxng#1852]
I have installed searcxng on trebus.com  
Zoekmachine [searxng](https://trebus.com/info/en/about) - 2022.10.07-666cd1f6
set up according [- NetworkChuck](https://learn.networkchuck.com/courses/take/ad-free-youtube-videos/lessons/36442494-ditch-google-build-your-own-private-search-engine)
on linode server ( docker container )

domain is well set in  .env file

after each setting modifcation and safe action  I will get this response :  invalid response. ERR_INVALID_REDIRECT

I am using latest edge browser
Microsoft Edge
Version 106.0.1370.34 (Official build) (64-bit)

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Comment by AlyoshaVasilieva** [comment]
The `Location` header in the redirect is `https://trebus.com 172.104.227.71/` which is definitely wrong but I don't know where that value is sourced from

**Comment by yenoromm** [comment]
I was experiencing this issue. It was fixed by changing the following in my docker compose file:
`SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}`
to
`SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME}`

However, I am using nginx proxy manager instead of caddy so your mileage may vary.

**Comment by return42** [comment]
Closed due lack of feedback.
