### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by aHqeem94** [searxng/searxng#1874]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.14-1a5b0965

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 15
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by swordapi** [comment]
Jepp same problem

**Comment by atuleu** [comment]
Have the same issue in #1871, someone suggested turn off / turn on again google engine, but it doesn't change anything in my case.

Issues happened after turning completion on for google. Maybe related ?

**Comment by return42** [comment]
did you tried `use_mobile_ui` ... https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

```yaml
- name: google
  ...
  use_mobile_ui: true
```

Duplicate of https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+use_mobile_ui

**Comment by atuleu** [comment]
@return42 Should not then just be enabled by default ?

**Comment by return42** [comment]
We had a internal discussion about, I can't remember why .. but @unixfox has had good reasons not to enable `use_mobile_ui`  by default ..

**Comment by unixfox** [comment]
> @return42 Should not then just be enabled by default ?
> 

See https://github.com/searxng/searxng/issues/774
