### ISSUE TITLE
Bug: duckduckgo images engine

### ISSUE THREAD

**Issue by Koognod** [searxng/searxng#1878]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.17

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1854

**Comment by atma-love** [comment]
Engine name | Scores | Result count | Response time | Reliability
-- | -- | -- | -- | --
duckduckgo | 0.8 | 28 | 0.7 | 95

<form action="https://github.com/searxng/searxng/issues/new" method="GET"><input type="checkbox" id="step1" style="font-family: inherit; font-size: 14.4px; line-height: 1.15; margin: 0px; overflow: visible; box-sizing: border-box; padding: 0px; appearance: none; width: 20px; height: 20px; cursor: pointer; position: relative; top: 0px; left: 0px; border: 2px solid var(--color-toolkit-checkbox-input-border); border-radius: 0.3em;"><span> </span><label for="step1" style="margin: 1rem 1rem 1rem 0px;">Start submiting a new issue on GitHub</label></form></div>Engine name	Scores	Result count	Response time	Reliability
[duckduckgo](https://search.sapti.me/stats?engine=duckduckgo)	0.8	28
0.7	95
Errors and exceptions
Exception	searx.exceptions.SearxEngineAccessDeniedException	Percentage	5
Parameter	HTTP error 403
Filename	searx/search/processors/online.py:113
Function	_send_http_request
Code	response = req(params['url'], **request_args)
 Start submiting a new issue on GitHub

**Comment by ghost** [comment]
again as i said in https://github.com/searxng/searxng/issues/2048

same issue here

**Comment by KawaKode** [comment]
Hello,
I have the exact same issue, I'm on the latest version of SearXNG
![image](https://user-images.githubusercontent.com/75862028/215998927-2cd6f45a-146f-45a4-83eb-ab8aed032bc6.png)

**Comment by ronttidev** [comment]
I have the same exact issue as above. Searx-docker public VPS instance 2023.2.1+d9ab8364, commit e76656a162c40c04ecc4b119d2a28ec2104c5275 (HEAD -> master, origin/master, origin/HEAD)

After fresh install it works for a bit but very soon DDG access is denied.

![image](https://user-images.githubusercontent.com/50660598/216671836-5c1ebaed-b461-45ba-a3f9-b9057f7ac935.png)

**Comment by return42** [comment]
> After fresh install ..

what does it mean, do have updated or just re-installed the old version (2023.2.1)?

**Comment by ronttidev** [comment]
> 

Ignore me. I thought I had pulled the LATEST image but I had not. Update fixed this. Sorry!
