### ISSUE TITLE
Bug: flickr engine

### ISSUE THREAD

**Issue by Koognod** [searxng/searxng#1879]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.17

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: ValueError
  * Percentage: 70
  * Parameters: `()`
  * File name: `searx/engines/flickr_noapi.py:79`
  * Function: `response`
  * Code: `photo = model_export['main'][index[0]][int(index[1])][index[2]][index[3]][int(index[4])]`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Just to remember myself, `Error: ValueError` still exists:

```
Error
  * Error: ValueError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/flickr_noapi.py:79`
  * Function: `response`
  * Code: `photo = model_export['main'][index[0]][int(index[1])][index[2]][index[3]][int(index[4])]`
```
