### ISSUE TITLE
Bug: unsplash engine

### ISSUE THREAD

**Issue by Koognod** [searxng/searxng#1880]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.17

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by jason-eu** [comment]
Same issue here

**Comment by return42** [comment]
Can't reproduce this issue any longer, I assume it might be fixed by:

- https://github.com/searxng/searxng/pull/2266
