### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1884]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.20-7f2185ce

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: TypeError
  * Percentage: 95
  * Parameters: `('SearxEngineResponseException() takes no keyword arguments',)`
  * File name: `searx/engines/startpage.py:96`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineResponseException(`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 5
  * Parameters: `(None, None, 'startpage.com')`
  * File name: `searx/engines/startpage.py:87`
  * Function: `get_sc_code`
  * Code: `resp = get(base_url, headers=headers)`

**Comment by return42** [comment]
FYI: detailed traceback is reported in https://github.com/searxng/searxng/issues/1913#issue-1428439511

```
searxng | 2022-10-29 20:09:32,219 ERROR:searx.engines.startpage: exception : 
          SearxEngineResponseException() takes no keyword arguments
searxng | Traceback (most recent call last):
searxng | File "/usr/local/searxng/searx/engines/startpage.py", line 93, in get_sc_code
searxng | href = eval_xpath(dom, '//a[@Class="footer-home__logo"]')[0].get('href')
searxng | IndexError: list index out of range
searxng |
searxng | During handling of the above exception, another exception occurred:
searxng |
searxng | Traceback (most recent call last):
searxng | File "/usr/local/searxng/searx/search/processors/online.py", line 154, in search
searxng | search_results = self._search_basic(query, params)
searxng | File "/usr/local/searxng/searx/search/processors/online.py", line 128, in _search_basic
searxng | self.engine.request(query, params)
searxng | File "/usr/local/searxng/searx/engines/startpage.py", line 124, in request
searxng | 'sc': get_sc_code(params['headers']),
searxng | File "/usr/local/searxng/searx/engines/startpage.py", line 96, in get_sc_code
searxng | raise SearxEngineResponseException(
searxng | TypeError: SearxEngineResponseException() takes no keyword arguments
searxng | 2022-10-29 20:10:14,132 WARNING:searx.engines.startpage:  
          ErrorContext('searx/engines/startpage.py', 96, 
          'raise SearxEngineResponseException(','TypeError', None,
          ('SearxEngineResponseException() takes no keyword arguments',)) False
```

The `SearxEngineResponseException() takes no keyword arguments` exception comes from this code:

https://github.com/searxng/searxng/blob/fc9986de0a21b01c1c8e342a9c4c8c6b96cc7ea2/searx/engines/startpage.py#L91-L98

**Comment by return42** [comment]
AFAIK this issue still exists in SearXNG's master

**Comment by ghost** [comment]
> AFAIK this issue still exists in SearXNG's master

my bad, sorry!

**Comment by return42** [comment]
```
searxng | TypeError: SearxEngineResponseException() takes no keyword arguments
searxng | 2022-10-29 20:10:14,132 WARNING:searx.engines.startpage:  
          ErrorContext('searx/engines/startpage.py', 96, 
          'raise SearxEngineResponseException(','TypeError', None,
          ('SearxEngineResponseException() takes no keyword arguments',)) False
```

This issue is fixed by https://github.com/searxng/searxng/pull/2132
