### ISSUE TITLE
Cycle through countries when pressing the key of the first letter

### ISSUE THREAD

**Issue by VasilisThePikachu** [searxng/searxng#1885]
**Is your feature request related to a problem? Please describe.**

Nearly all websites i visit allow me to press the first letter of what i'm looking for in the dropout and jump to it. I frequently need to change between English and Swedish results and having to use the scroll wheal to find and change the country search location is annoying
**Describe the solution you'd like**

As an example when you have the country search dropdown on, pressing S will jump to countries in that list starting with S, containing to press S scrolls down the list until the desired country is highlighted
**Describe alternatives you've considered**

Using google since they search by the language your type in or brave search where they have a search box to find a country easier (does not in brave too but they have a search bar at least)
**Additional context**

[Screen recording 2022-10-25 10.41.20 AM.webm](https://user-images.githubusercontent.com/34938708/197726965-51bebea8-2f3b-4cbc-bd14-0817567081dc.webm)
An example in another unrelated project uptime kuma, pressing the first letter cycles through those options. Optionally would allow you to select a language if you are hovering your mouse over the dropdown

**Comment by Tiritibambix** [comment]
Was coming here to post this. This is indeed quit needed :)

**Comment by Tiritibambix** [comment]
If I knew how to code, I'd PR this. I bet it's dead simple to implement...

**Comment by Solirs** [comment]
Taking note of this. Ill try to PR it when i get some time

**Comment by Tiritibambix** [comment]
Seeing this come to life would be a blessing.
It is so deeply rooted in my habits that I still try to hit the right key for the languages I use in searxng. Then, I sadly scroll down.

**Comment by return42** [comment]
> Then, I sadly scroll down.

As a workaround you can use the [Search Syntax](https://docs.searxng.org/user/search-syntax.html) / that is what I use.  Like in the menu, you can select the language `:en` (English) or the region `:zh-tw` (Taiwan).

**Comment by Tiritibambix** [comment]
That is a workaround I will use, still hoping that this will be an implemented feature :)
Thanks.

**Comment by Bnyro** [comment]
Well, apparently none of the popular desktop browsers allow us to capture keyboard events while a `select` element is opened.

So we would need to implement our own `select` dropdown menu, which I don't consider a good idea honestly.

**Comment by Tiritibambix** [comment]
I can't express how grateful I am for this.

Thank you.
