### ISSUE TITLE
save perference will be return 502

### ISSUE THREAD

**Issue by bosshuman** [searxng/searxng#1893]
my server add is http://170.178.197.3:9080
the log show nonthing
<img width="539" alt="CleanShot 2022-10-26 at 19 59 56@2x" src="https://user-images.githubusercontent.com/107166483/198020684-26bb7a89-4ff8-4370-b0ab-26465afa8b09.png">

**Comment by return42** [comment]
Did work but is not HTTPS ..

![grafik](https://user-images.githubusercontent.com/554536/198021511-fbcca2e5-faf1-4267-bd54-71f56bf03ec2.png)

**Comment by bosshuman** [comment]
no, if you try to do this http://170.178.197.3:9080/preferences,and click save button ,will return 502

**Comment by bosshuman** [comment]
can you  defined this？

**Comment by return42** [comment]
http://170.178.197.3:9080/preferences works for me.

**Comment by return42** [comment]
Your "save" links to 127.0.0.1:8888 .. check your installation setup.

**Comment by bosshuman** [comment]
ok i changed the settings.yml now,and see if or not work
