### ISSUE TITLE
[Istance] Add mine pls

### ISSUE THREAD

**Issue by hxvy0** [searxng/searxng#1897]
Hi, I'm Enes from Turkey. Can you add my istance?

Url: www.futureddit.gq 

Cloudflare: Yes 

Server location: Italy 

I won't tell you why I use Cloudflare because it's a secret, I hope that you appreciate.

**Comment by return42** [comment]
This *here* (searxng/searxng) is the wrong place .. please go to [searxng/searx-instances](https://github.com/searxng/searx-instances) and read the README.md
