### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Universalizer** [searxng/searxng#1899]
![chrome_screenshot_Oct 28, 2022 10_57_00 AM GMT+05_30](https://user-images.githubusercontent.com/116723165/198510982-114e2033-e850-4f8b-9112-def48ca9cf5a.png)
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.25-affd8f75

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1854 and several others https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+duckduckgo+engine%22
