### ISSUE TITLE
Is this dead code in wikidata.get_label_for_entity(..)

### ISSUE THREAD

**Issue by return42** [searxng/searxng#1912]
If I am not wrong, the code from line 131 to line 136:

https://github.com/searxng/searxng/blob/fc9986de0a21b01c1c8e342a9c4c8c6b96cc7ea2/searx/engines/wikidata.py#L129-L139

does not have any effect. `(entity_id, ...)` is a `tuple` type and in `WIKIDATA_PROPERTIES` there are only keys of type `str`. 

https://github.com/searxng/searxng/blob/fc9986de0a21b01c1c8e342a9c4c8c6b96cc7ea2/searx/engines/wikidata.py#L36-L47

The dead code is there since it initial commit 95bd6033f.

**Comment by dalf** [comment]
When the server starts, a SPARQL query get the labels for the different the properties.
See the last line of the `init` function: 

https://github.com/searxng/searxng/blob/fc9986de0a21b01c1c8e342a9c4c8c6b96cc7ea2/searx/engines/wikidata.py#L742-L758

It works as expect. For example if I search for `:de berlin !wd`, the labels of the properties are in German:
![image](https://user-images.githubusercontent.com/1594191/208140260-18c5022d-147d-461f-abb7-b4de9eeb8f26.png)

**Comment by return42** [comment]
@dalf thanks for your explanation but I am unsure it answer my question.

Please have a close look to the code ..


```python
def get_label_for_entity(entity_id, language):
     
     # here the argument to the get method is a string, the value of variable entity_id 
     name = WIKIDATA_PROPERTIES.get(entity_id)
     if name is None: 
         # here the argument is a tuple consists of two strings (entity_id, language)
         name = WIKIDATA_PROPERTIES.get((entity_id, language))
     ...

WIKIDATA_PROPERTIES = { 
     # here, the key is a string .. not a tuple of two string
     'P434': 'MusicBrainz', 
```

so my conclusion, the function can be replaced by

```python
def get_label_for_entity(entity_id, language): 
     return WIKIDATA_PROPERTIES.get(entity_id) 
```

The rest of the function is *dead code* .. since the rest of the code will always return `None`.

Do you see what I mean?

**Comment by dalf** [comment]
If this is dead code, then the translations of the label would not work.

The keys & values of `WIKIDATA_PROPERTIES` are set in two different ways:
* static initialization as you noticed
* dynamic reading the labels from the wikidata.org:
https://github.com/searxng/searxng/blob/fc9986de0a21b01c1c8e342a9c4c8c6b96cc7ea2/searx/engines/wikidata.py#L758

**Comment by return42** [comment]
> See the last line of the init function:

Argh .. I didn't scrolled the code window to the last line :facepalm:  .. I am idiot /sorry
