### ISSUE TITLE
Can't get searxng to work on Oracle Cloud Compute VM

### ISSUE THREAD

**Issue by Catakang** [searxng/searxng#1916]

**Comment by AlyoshaVasilieva** [comment]
You need to open the ports in the security list of your Virtual Cloud Network (`Networking > Virtual Cloud Networks > YOUR VCN HERE > Security List Details`, for example

Stateless: Yes  
Source: 0.0.0.0/0  
IP Protocol: TCP  
Source Port Range: All  
Destination Port Range: 443 (or whatever the reverse proxy is listening on, or searxng's port)  

If you're using ports 80/443 you also need to open them in the instance itself, Oracle's commands for this are:

`sudo firewall-cmd --add-service=https --permanent`  
`sudo firewall-cmd --reload`

but it might differ by OS.

**Comment by Catakang** [comment]
It would be pretty cool if you could delete this issue from existence.

**Comment by return42** [comment]
Issues can't be deleted.
