### ISSUE TITLE
[BUG] Result languages preference doesn't do anything.

### ISSUE THREAD

**Issue by Shituation** [searxng/searxng#1931]
**What happened?**
Changing languages preferences for search doesn't affect shown results in undesired languages. I'm getting a lot of german and french results despite changing the setting to only show in english.

**How To Reproduce** (click to watch GIF)
https://fs-01.cyberdrop.to/1-k9hHJlh6.gif

**Expected behavior**
To be able to filter search results by language.

**Screenshots & Logs**

**Additional context**
Not hosting my SEARX instance, using a public one.

**Comment by return42** [comment]
Thanks for your issue report ..

> Not hosting my SEARX instance, using a public one.

which one do you use .. can you give us the URL / thanks!

**Comment by Shituation** [comment]
Using:
https://search.sapti.me
https://searx.be/search
https://searx.tiekoetter.com/

All suffer from the same bug.

Thanks

**Comment by return42** [comment]
BTW: now I see; you in your gif: you change from "default language" to "en" .. since the default language of nearly all engines is "en" I would not expect much difference in the result list.

**Comment by Shituation** [comment]
The option is not being honored, I expect the engine to only show the selected languages like any other search engine does.
I don't understand why you say that. For instance, in DDG you change the country and the results are shown based on that option.

**Comment by return42** [comment]
> I'm getting a lot of german and french results despite changing the setting to only show in english.

Some engines in SearXNG do not support languages or regions, other engines (e.g. yahoo) have a poor language match .. take into mind, that SearXNG is a metasearch instance.

But I agree, the quality of the language support of the engines in SearXNG can be improved ... we do that continuously, but that is an elaborate and lengthy process, not just one place where we can fix something.

**Comment by Shituation** [comment]
OK I see, there's nothing to do on searx's side since it pulls results from those engines. The question now is, why is there a languages option in searx? I mean if searx only pulls results, why am I being able to tell it to search for results in an specific language? does it send a command to the search engines when selecting an specific language?

**Comment by return42** [comment]
Side note: This is SearXNG (not searx) ..

>  The question now is, why is there a languages option in searx? I mean if searx only pulls results, 

Not all engines support languages / see column 'language' https://docs.searxng.org/admin/engines/configured_engines.html

Even if a engine supports languages it does not say much about the quality, my example was yahoo: this engine supports languages but the results are (IMO) poor or better say "improvable".

If you look in your video, you will see that yahoo insterst the "bad" results ..

![grafik](https://user-images.githubusercontent.com/554536/200032442-3af8546d-a1cb-4f57-aede-603e0cae5ae7.png)

What you see in the result is the mix of the results from the different engines that had been active .. yahoo is active and it mixed in these non English results.

The language support in SearXNG works, if you try other engines with different languages.

**Comment by Shituation** [comment]
Closing this issue since searxng is incapable of the most needed features for searching the internet today where bots make thousands of dumb pages and brainless bloggers insist with useless random guides for everything.

These features are negative words (aka word filter e.g "-best") and basic language 
support.
One cannot search for a software because it will get thousands of pages offering online services instead of offline software.
One cannot search for a guide to do something without stumbling with engrish guides telling basic stuff.
And finally, there's wordpress making our lifes miserable.

I also have to add that the results shown on searxng are 3% of the real results shown by the "real" search engines. Don't even get started on the "images search" where the results are even worse and there is no way to search by size.

**Comment by Shituation** [comment]
If anyone ends here for some reason, there are two ways to deal with this language problems:
1- Google engine SUPPORTS NEGATIVE WORDS sent into the search field from searx, that means you can filter results if using google as your main engine.

2- Get [SearchBlocklist](https://addons.mozilla.org/en-US/firefox/addon/searchblocklist/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension and add this rule to block german or dutch webpages (change it to swit your needs):
```
/\.(de)/
/\.(nl)/
```
Those will filter domains ending with .de or .nl. 
You can figure the rest.

**Comment by return42** [comment]
Can't recommend [SearchBlocklist](https://addons.mozilla.org/en-US/firefox/addon/searchblocklist/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension .. it has never been updated https://addons.mozilla.org/en-US/firefox/addon/searchblocklist/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org

**Comment by Shituation** [comment]
> Can't recommend [SearchBlocklist](https://addons.mozilla.org/en-US/firefox/addon/searchblocklist/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension .. it has never been updated https://addons.mozilla.org/en-US/firefox/addon/searchblocklist/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org

And what needs to be updated? I'm using it, no problems at all. There is some kind of mania now, code has to be changed, at least a comma and then pretend there is a new version. Nonsense. And your claim doesn't have any real arguments. In fact most software uses """"updates"""" to pull data from users (you can't firewall the updates if you want them, so we are using them to suck your data) or to restrain them (we FIXED something that was not broken so you cannot do it anymore). 🤷‍♂️
Let users decide what to do.

EDIT: it seems [Ublacklist ](https://github.com/iorate/ublacklist/issues/143)now supports searx

**Comment by return42** [comment]
I don't now the details may be I'm wrong, but SearchBlocklist extension says ..

> A fork of "uBlacklist" with added SEARX privacy engine support.

When I hear "fork" I expect regularly rebase on the origin or merges from origin.  The origin has been released n-times and a major update has been since the fork was created ..

- https://addons.mozilla.org/en-US/firefox/addon/ublacklist/
- https://github.com/iorate/ublacklist/commits/master

The other point is the list of searx instances .. an actual list of instances is at searx.space and these list has been changed since first (and) last release of SearchBlocklist extension 

> Let users decide what to do.

Thats what I do .. Everyone can do what they want, but I wouldn't rely on software that has never been updated.  Thats why I do not **recommend** .. hope it is OK for you that I give recommends.
