### ISSUE TITLE
[BUG] "negative words" are not taken into account on search.

### ISSUE THREAD

**Issue by Shituation** [searxng/searxng#1932]
**How To Reproduce**
Search crop video -online and check the results. 40% will be online services having that word in the description or name.

**Expected behavior**
To be able to tell the engines what words should be excluded from search.

**Screenshots & Logs**
![sshot-001](https://user-images.githubusercontent.com/43975882/200025418-5cfdbf56-bf96-46bb-bdd6-e7acb517e952.png)

**Additional context**
Using:
https://searx.be/
https://search.sapti.me/
https://searx.tiekoetter.com/

**Comment by return42** [comment]
Where did you read that SearXNG supports such syntax?

The search syntax that is supported by SearXNG is documented in the "about" page https://searx.be/info/en/search-syntax

**Comment by Shituation** [comment]
Thanks for clarifying, if searxng cannot process any kind of negative words or filters then I will stop using it since its basically useless taking into account the actual state of internet and search engines.

**Comment by return42** [comment]
>  since its basically useless taking into account the actual state of internet and search engines.

The main intention of SearXNG and all the efforts from the community is to protect your privacy, if this has no value for you SearXNG is not the right search tool for you.

![grafik](https://user-images.githubusercontent.com/554536/200037030-ba346240-69ab-4411-a7e6-10248ecc5f12.png)

**Comment by Shituation** [comment]
Thanks, protecting my privacy would be doing no search at all too. That is not an argument.
Instead, taking "the risk" of searching to not get results or bad results, its senseless.
If I'm going to "risk" sending my searches over the net to `<who knows>`, at least it would be nice to get a good experience. And be worth the "risk".

**Comment by return42** [comment]
> Thanks, protecting my privacy would be doing no search at all too. 

If you don't like all this, just don't use it.  But you don't have to pour out your displeasure about this project here.  You may not realize it, but many people invest their free time here and there are enough users for whom this project has a real benefit.  Just move on without insulting the community / thanks!

**Comment by Shituation** [comment]
Why not? what is that censoring all of a sudden?
I'm a user, I have the right to tell what I think and I haven't insulted anyone.
