### ISSUE TITLE
Bug: yahoo engine

### ISSUE THREAD

**Issue by WoefulWrecker** [searxng/searxng#1933]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.14-1a5b0965

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

Error! Engines cannot retrieve results:

yahoo ( [unexpected crash](http://raspberrypi:9017/stats?engine=yahoo) )
**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 100
  * Parameters: `(None, None, 'au.search.yahoo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate: https://github.com/searxng/searxng/issues/1841

**Comment by Shituation** [comment]
Take my friendly advice. Move on to other search engines. These people censores you.

**Comment by return42** [comment]
@Shituation can you please stop posting crap .. this issue is an duplicate and it makes absolutely no sense to have open two issue reports for the same task. Please go!
