### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by StiveBuch** [searxng/searxng#1935]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.31

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 5
  * Parameters: `('500', 'Internal Server Error', 'www.google.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.com.ua')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.se')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.cz')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.nl')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.be')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.pl')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.es')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.com.br')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.ca')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.co.jp')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.co.uk')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.de')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.fr')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.ru')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Error 500 given by Google on some specific search terms. Also reproducible on other instances.

Search terms (examples):
```
melanie griffith
twitter joe rogan
ed snowden twitter
David Axmark children
```

**Comment by repparw** [comment]
It seems to only happen with names? At least in my case.
George Washington gets the error, Washington DC does not.
Joe Rogan also gets the error for me, even when followed by twitter or podcast
Joe podcast Rogan or Joe twitter Rogan seems to work?

**Comment by tiekoetter** [comment]
@unixfox If you don't want to be assigned to this issue would you be ok with keeping this as the general issue? Or do you have more information regarding this issue?

**Comment by unixfox** [comment]
I removed the assignation because it doesn't only apply to my instance. That's it.

We can keep the issue like this. I haven't had the time to look at these google errors lately..

**Comment by aaronliu0130** [comment]
Now i get this in Tiekoetter's instance with any term.

**Comment by signed-log** [comment]
Getting it in https://search.unlocked.link all the time

**Comment by StiveBuch** [comment]
Thank you, guys.

пятница, 11 ноября 2022 г. пользователь signed-log ***@***.***>
написал:
