### ISSUE TITLE
Initialization errors when z-library is enabled

### ISSUE THREAD

**Issue by GlenC289** [searxng/searxng#1936]
The domain has been seized so, the engine should be disabled by default or removed.

**Comment by ghost** [comment]
As a temporary patch, I had to add
 `engines: 
    remove:
      - z-library`
  to settings.yml

**Comment by BoxingOctopus** [comment]
I've submitted a PR for this which implements @JAAnon 's patch: #1937

**Comment by return42** [comment]
closed by https://github.com/searxng/searxng/pull/1937
