### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by johnnysax** [searxng/searxng#1946]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.06-ae54c7d5

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/search?q=%22Bug%3A+duckduckgo+engine%22&type=issues

**Comment by johnnysax** [comment]
Duplicated where?  Which number?  Or is it solved?

**Comment by return42** [comment]
The `Error: searx.exceptions.SearxEngineAccessDeniedException` is reported in https://github.com/searxng/searxng/issues/1854
