### ISSUE TITLE
[Feature] Raise error when the engine doesn't exist

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#1951]
Raise an error when an engine doesn't exist and there is for example an old parameter that disabled a now removed engine.

See https://github.com/searxng/searxng/issues/1951#issuecomment-1324872496 for more info.

-----

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Commit https://github.com/searxng/searxng/commit/3a765113eefc7ac0b1ee94e9a0ac0db8069ec336

**How did you install SearXNG?**
1. Git clone
2. pip install -r requirements.txt
3. `python -m searx.webapp`

**How To Reproduce**
Run searxng with this configuration:
```yaml
engines:
  - name: duckduckgo
    disabled: true
general:
  debug: true
server:
  secret_key: secret
use_default_settings: true
```

And you will get this error:
```
Traceback (most recent call last):
  File "/opt/python/latest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python/latest/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/searx-custom/searxng2/searx/webapp.py", line 1390, in <module>
    search_initialize(enable_checker=True, check_network=True, enable_metrics=settings['general']['enable_metrics'])
  File "/workspaces/searx-custom/searxng2/searx/search/__init__.py", line 30, in initialize
    load_engines(settings_engines)
  File "/workspaces/searx-custom/searxng2/searx/engines/__init__.py", line 298, in load_engines
    engine = load_engine(engine_data)
  File "/workspaces/searx-custom/searxng2/searx/engines/__init__.py", line 121, in load_engine
    engine_module = engine_data['engine']
KeyError: 'engine'
```

**Expected behavior**
Searxng should work fine.

**Screenshots & Logs**

**Additional context**

**Comment by unixfox** [comment]
Closing and maybe reopening later because it's probably an issue on my side.

**Comment by unixfox** [comment]
Found the issue, it was due to:
```yaml
engines:
- disabled: true
  name: z-library
```

**Comment by return42** [comment]
> Found the issue, it was due to:

Argh, that's a real pity and hard to trace issue .. z-library has been removed here:

https://github.com/searxng/searxng/pull/1937/files

but users will still have the engine entry in their `/etc/searxng/settings.yml`.

@dalf what do you think: is there way we parse the a [`use-default-settings`](https://docs.searxng.org/admin/engines/settings.html#use-default-settings) and raise warnings for engines not exists.

**Comment by unixfox** [comment]
Renamed the title of the issue and switch this issue to a feature request. Reopening.
