### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1957]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.05-d764d94a

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

It pops this issue up whenever I use the web address bar to do any type of google search. this popped up when I typed in "failed to load module "appmenu-gtk-module" electron" in the web address box and hit enter to search for an error I'm having with a program I'm writing. When I clicked the error, it had a screen to report it here, so I thought I would share. Thanks

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1854
