### ISSUE TITLE
Google News engine gives bad URLs

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#1959]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.11.11-3a765113
**How did you install SearXNG?**
Script, also occurs in public instances
**What happened?**
Google News URLs encodes URLs, SearXNG does not decode them

**How To Reproduce**
1. Search news "Here's how ranked choice voting will decide Alaska's Senate race"
2. Look at result URLs for the ABC News article

Bing, Qwant give URL:  
`https://abcnews.go.com/Politics/ranked-choice-voting-decide-alaskas-senate-race/story?id=93063277`  
Google News gives URL:  
`https://abcnews.go.com/Politics/ranked-choice-voting-decide-alaskas-senate-race/story?id\\u003d93063277`

The Google URL does not work.

Repro 2:
Search "McConnell dismisses Scott's GOP leadership challenge"

Qwant gives URL:  
`https://abcnews.go.com/Politics/mcconnell-dismisses-scotts-gop-leadership-challenge-votes/story?id=93354279`  
Google gives URL:  
`https://abcnews.go.com/Politics/mcconnell-dismisses-scotts-gop-leadership-challenge-votes/story/x1aY/x17/x1dL/x0c/x0c/xd9/x0eL/xcc/xcdM/x0c/x8d/xceH/x97'`

**Expected behavior**
URL is decoded properly

**Comment by return42** [comment]
For reference / I addressed this issue in my rework of locales & languages: [`[mod] Google: reversed engineered & upgrade to data_type: traits_v1 `](https://github.com/return42/searxng/commits/master)

**Comment by return42** [comment]
- https://github.com/searxng/searxng/pull/2269

has been merged, but this problem still needs to be investigated / issue still exists --> [:en !gon abcnews](https://darmarit.org/searx/search?q=%3Aen+%21gon+abcnews)

**Comment by return42** [comment]
@AlyoshaVasilieva sorry for the late response on your issue report .. now I have implemented #2306 that fixes the issue you reported / would you like to test #2306 / thanks :+1:

**Comment by AlyoshaVasilieva** [comment]
The PR fixed every news source I can find (thanks!), except one: Des Moines Register.

1. Search Des Moines Register in news section
2. `href` URLs look like: `http:///https://www.desmoinesregister.com/story/weather/2023/04/01/tornado-sightings-damage-reports-from-severe-storms-in-iowa-friday/70071149007/`

The URL after  (U+0001?) seems valid.

**Comment by return42** [comment]
@AlyoshaVasilieva thanks for your elaborate tests :+1: ... helps me to make the URL decoding more robust .. I fixed the issue:

- [!gon :en Des Moines Register](https://darmarit.org/searx/search?q=%21gon+%3Aen+Des+Moines+Register)
- [!gon :en McConnell dismisses Scott's GOP leadership challenge](https://darmarit.org/searx/search?q=%21gon+%3Aen+McConnell+dismisses+Scott%27s+GOP+leadership+challenge)

If you see other issues, please let me know / thanks.
