### ISSUE TITLE
Error determining qwant search engine support Chinese

### ISSUE THREAD

**Issue by Zpcin** [searxng/searxng#1965]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
searxng- 2022.11.18-1cdadf4b

**How did you install SearXNG?**
SearXNG docker

**What happened?**
Error determining qwant search engine support Chinese, default preference
under Chinese search results contain non-Chinese results

**How To Reproduce**
Search in Chinese under default preferences

**Expected behavior**
Set qwant to not support Chinese, do not enable it under default preferences

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/62590508/203048412-9a515d0a-5d92-4225-b044-834464d23c25.png)
![image](https://user-images.githubusercontent.com/62590508/203048859-e479bc17-59dc-4149-97e4-d8c50f734bbb.png)

**Additional context**
The above is translated from Chinese to English using machine translation

**Comment by return42** [comment]
Can you test my instance: https://darmarit.org/searx/

In my [master branch](https://github.com/return42/searxng/commits/master) I experiment with a different language handling in SearXNG .. this branch runs on https://darmarit.org/searx/

I haven't finished my work on this, but qwant should be improved.

Tip: to test a dedicated engine you can use the [search syntax](https://darmarit.org/searx/info/en/search-syntax), by example you can use [`!qwant 日`](https://darmarit.org/searx/search?q=%21qwant+%E6%97%A5&language=zh-TW).

Hint: not all engines do support all languages/regions (e.g. zh, zh-HK, zh-TW or zh-CN) and scripts (traditional/simplified) / [here](https://github.com/return42/searxng/blob/master/searx/data/engine_traits.json#L2899) you can see what (region) codes supported by qwant and other engines.  SearXNG tries to map the user selected language or region code to the languages supported by the engine and make the best compromise.

I don't know Chinese, so in my tests it's already hard for me to distinguish between traditional and simplified.

----

I haven't finished my work on the language & region handling in SearXNG, ATM I have ported the following engines:

- `!wikipedia`

```
    # '!wikipedia 日 :zh-TW' --> https://zh-classical.wikipedia.org/
    # '!wikipedia 日 :zh' --> https://zh.wikipedia.org/
```

- `!wikidata`

```
    # wikidata does not support zh-classical (zh_Hans) / zh-TW, zh-HK (and zh-CN) are mapped to zh
```

- `!startpage`

```
  zh-CN_CN --> zh_Hans_CN
  zh-TW_TW --> zh_Hant_TW
  zh-TW_HK --> zh_Hant_HK
```

- all bing engine: `!bing_news`, `!bing_images`, `!bing_videos` and `!bing` (web)

```
      "zh-CN": "zh-CN",
      "zh-HK": "zh-HK",
      "zh-TW": "zh-TW"
```

Bing has so called "market codes" .. bing news has a reduced set of "market codes" compared to the other engines like bing-web, bing-videos or bing-images.

- `!yahoo`

```
      "zh_Hans": "zh_chs",
      "zh_Hant": "zh_cht"
```

- `!qwant` (see above)

```
      "zh-CN": "zh_CN",
      "zh-HK": "zh_HK"
```

- `!peertube`

```
      "zh": "zh"
```

**Comment by zhang2333-Myself** [comment]
> Can you test my instance: https://darmarit.org/searx/
> 
> In my [master branch](https://github.com/return42/searxng/commits/master) I experiment with a different language handling in SearXNG .. this branch runs on https://darmarit.org/searx/
> 
> I haven't finished my work on this, but qwant should be improved.
> 
> Tip: to test a dedicated engine you can use the [search syntax](https://darmarit.org/searx/info/en/search-syntax), by example you can use [`!qwant 日`](https://darmarit.org/searx/search?q=%21qwant+%E6%97%A5&language=zh-TW).
> 
> Hint: not all engines do support all languages/regions (e.g. zh, zh-HK, zh-TW or zh-CN) and scripts (traditional/simplified) / [here](https://github.com/return42/searxng/blob/master/searx/data/engine_traits.json#L2899) you can see what (region) codes supported by qwant and other engines. SearXNG tries to map the user selected language or region code to the languages supported by the engine and make the best compromise.
> 
> I don't know Chinese, so in my tests it's already hard for me to distinguish between traditional and simplified.
> 
> I haven't finished my work on the language & region handling in SearXNG, ATM I have ported the following engines:
> 
> * `!wikipedia`
> 
> ```
>     # '!wikipedia 日 :zh-TW' --> https://zh-classical.wikipedia.org/
>     # '!wikipedia 日 :zh' --> https://zh.wikipedia.org/
> ```
> 
> * `!wikidata`
> 
> ```
>     # wikidata does not support zh-classical (zh_Hans) / zh-TW, zh-HK (and zh-CN) are mapped to zh
> ```
> 
> * `!startpage`
> 
> ```
>   zh-CN_CN --> zh_Hans_CN
>   zh-TW_TW --> zh_Hant_TW
>   zh-TW_HK --> zh_Hant_HK
> ```
> 
> * all bing engine: , ,  and  (web)`!bing_news``!bing_images``!bing_videos``!bing`
> 
> ```
>       "zh-CN": "zh-CN",
>       "zh-HK": "zh-HK",
>       "zh-TW": "zh-TW"
> ```
> 
> Bing has so called "market codes" .. bing news has a reduced set of "market codes" compared to the other engines like bing-web, bing-videos or bing-images.
> 
> * `!yahoo`
> 
> ```
>       "zh_Hans": "zh_chs",
>       "zh_Hant": "zh_cht"
> ```
> 
> * `!qwant` (see above)
> 
> ```
>       "zh-CN": "zh_CN",
>       "zh-HK": "zh_HK"
> ```
> 
> * `!peertube`
> 
> ```
>       "zh": "zh"
> ```

It's great, and the search results are basically Chinese content. A big part of my examples are basically non-Chinese content.

**Comment by Zpcin** [comment]
@return42 It's great, the search results are basically Chinese content. Even if you turn off qwnt my instance of the search results are basically a large part of the non-Chinese

**Comment by Zpcin** [comment]
@return42 I'm a newbie, it would be great if I could use your branch via docker

**Comment by 9Ninety** [comment]
It looks like Qwant will return fake data for some reason, here is what I got on one of my server, it's obviously not English nor human language...

**Screenshot:**
<img width="577" alt="qwant_fake_data" src="https://user-images.githubusercontent.com/38161479/223063480-dcc9a668-d440-4419-8375-c3f7a7465d1e.png">

**Comment by return42** [comment]
> It looks like Qwant will return fake data for some reason, here is what I got on one of my server ..

@9Ninety where is your server located? .. and from where did you copied this URL:

![grafik](https://user-images.githubusercontent.com/554536/223070455-34589618-2527-48df-8b4a-8b8c38df6387.png)

The current master branch assembles this URL:

https://api.qwant.com/v3/search/web?q=test&count=10&offset=40&locale=en_US&safesearch=0

**Comment by return42** [comment]
> @return42 It's great, the search results are basically Chinese content ..
> @return42 I'm a newbie, it would be great if I could use your branch via docker ..

Sorry for my late response .. in the meantime, my work is complete and I am in a final testing phase.  When this is finished, the revision of the languages & locales from my branch will be merged into the master branch .. at least that's my plan :-)

**Comment by 9Ninety** [comment]
@return42 The server was located in unsupported country, I am not sure those fake data was caused by unsupported country or blacklisted IP address. Solved by use proxy in my case.

This address was copied from: https://github.com/searxng/searxng/blob/master/searx/engines/qwant.py#L69

**Comment by return42** [comment]
> Solved by use proxy in my case.

@9Ninety thanks for info .. 

> This address was copied from ..

Ah, OK .. but the URL assembled (and used) by the qwant engine is different .. the `offset` is 40 and there is an option `safesearch` (see the URL I posted above).

**Comment by 9Ninety** [comment]
@return42 Tested with `safesearch` parameter, got similar fake data o_O, Isn't the `offset` parameter start from 0 and up to 40?

**Comment by return42** [comment]
> Isn't the `offset` parameter start from 0 and up to 40? 

Can't remember why, but this is what I have implemented in [PR-204](https://github.com/searxng/searxng/pull/204) ...

https://github.com/searxng/searxng/blob/abd2d8605eae4f73b9e3f6445aa8f34dbd4ce38c/searx/engines/qwant.py#L85-L88

**Comment by return42** [comment]
> @return42 It's great, the search results are basically Chinese content. Even if you turn off qwnt my instance of the search results are basically a large part of the non-Chinese

- https://github.com/searxng/searxng/pull/2269

has been merged / I think we can now close this issue .. if not leaf a note here / thanks :+1:
