### ISSUE TITLE
Bug: google engine - too many requests

### ISSUE THREAD

**Issue by nicfab** [searxng/searxng#1966]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.19-b5371b7a

**How did you install SearXNG?**
I installed SearXNG using the official wiki (no docker).
**What happened?**
After launching a search, I receive the error below.

**How To Reproduce**
See before.

**Expected behavior**
No errors.

**Screenshots & Logs**
![sshot_2022-11-21_16 24 10](https://user-images.githubusercontent.com/24752671/203093020-ff79747c-9610-46cc-9430-7a0e315cc6cf.png)

**Additional context**
None

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Check https://github.com/tiekoetter/searxng/commit/464fc76a0df620b0af0bbb78afdfb0eab7250993

This fixed it for me (especially the change in raise_for_httperror.py).

**Comment by nicfab** [comment]
> Check [tiekoetter@464fc76](https://github.com/tiekoetter/searxng/commit/464fc76a0df620b0af0bbb78afdfb0eab7250993)
> 
> This fixed it for me (especially the change in raise_for_httperror.py).

Thank you.
I did as you suggested, and I restarted SearXNG.
However, I don't see the Google error but the DDG one, as you can see from the attached screenshot.

![sshot_2022-11-21_16 44 02](https://user-images.githubusercontent.com/24752671/203097506-25319772-5a21-4932-861b-7e5bacf9b98b.png)

However, my question is: what's happened once I run an update? Does the update overwrite those files?

**Comment by tiekoetter** [comment]
You mean the changes to the engine suspended_time? Yes they will be overwritten if you don't "secure" (e.g. through git) them.

DDG really blocks you (same for me) although they only seem to block for a short period of time. You can't really do anything without doing load balancing to prevent this.

Please keep in mind that this issue is about the google engine. I think your question is answered in this regard.

**Comment by return42** [comment]
> but the DDG one, as you can see from the attached screenshot.

This is a [different issue](https://github.com/searxng/searxng/issues/1854) and not related to this google issue.

> I think your question is answered in this regard.

@tiekoetter do you like to send a PR with your fix?

**Comment by nicfab** [comment]
> You mean the changes to the engine suspended_time? Yes they will be overwritten if you don't "secure" (e.g. through git) them.
> 
> DDG really blocks you (same for me) although they only seem to block for a short period of time. You can't really do anything without doing load balancing to prevent this.
> 
> Please keep in mind that this issue is about the google engine. I think your question is answered in this regard.

Thank you

**Comment by tiekoetter** [comment]
@return42 This fix is originally from @unixfox

If you would like to see a PR for this I would like to implement it the way unixfox suggested. So with a setting in settings.yml instead of hard coding it.

**Comment by return42** [comment]
> So with a setting in settings.yml instead of hard coding it.

Ah, OK now I see: its in `network/raise_for_httperror.py` .. we should make it more flexible .. I would be interested in your settings.yml solution .. it would be great if you prepare a PR / thanks!

**Comment by tiekoetter** [comment]
@return42 I will do it this evening.

**Comment by return42** [comment]
> @return42 I will do it this evening.

don't hurry .. :smoking:

**Comment by nicfab** [comment]
I am sorry, but I continue having the same error on google as the image below.

![sshot_2022-11-21_19 06 34](https://user-images.githubusercontent.com/24752671/203128557-fa413ed4-c64b-4ddc-b15d-d57375ea32b3.png)

Any suggestion?

**Comment by tiekoetter** [comment]
You need to check if Google really blocked you. If that's the case you need to proxy your requests via a different IP.

**Comment by nicfab** [comment]
> You need to check if Google really blocked you. If that's the case you need to proxy your requests via a different IP.

I tried with a VPN right now, and the error exists.

**Comment by return42** [comment]
> I tried with a VPN right now, and the error exists.

Seems a temporary issue (ATM https://searxng.nicfab.eu/ does not have issues with google or ddg) ... having configurable suspend times as suggest in PR #1967 seems a good solution to me.

**Comment by nicfab** [comment]
> > I tried with a VPN right now, and the error exists.
> 
> Seems a temporary issue (ATM https://searxng.nicfab.eu/ does not have issues with google or ddg) ... having configurable suspend times as suggest in PR #1967 seems a good solution to me.

Thank you.
How can I set the values in [PR #1967](https://github.com/searxng/searxng/pull/1967)? 
What kind of value for the following rows?
```
SearxEngineAccessDenied_suspended_time
SearxEngineCaptcha_suspended_time
SearxEngineTooManyRequests_suspended_time
cf_SearxEngineCaptcha_suspended_time
cf_SearxEngineAccessDenied_suspended_time
recaptcha_SearxEngineCaptcha_suspended_time
```
Can I put those lines, as they are, into `settings.yml`, or should I set them in another file?

**Comment by return42** [comment]
Please wait, the PR is a DRAFT, needs a review and some more discussion what final solution gets merged.  Nothing that is available in current SearXNG.

I just pointed out, that your issue is temporary and its a good solution to set suspend times in the configuration / but nothing we have today.

**Comment by nicfab** [comment]
> Please wait, the PR is a DRAFT, needs a review and some more discussion what final solution gets merged. Nothing that is available in current SearXNG.
> 
> I just pointed out, that your issue is temporary and its a good solution to set suspend times in the configuration / but nothing we have today.

Ok, thank you.

**Comment by samsapti** [comment]
Just to add to this, I'm having the same issue on [my instance](https://search.sapti.me), despite `use_mobile_ui: true`.

**Comment by samsapti** [comment]
It seems to come and go randomly.

**Comment by unixfox** [comment]
Reopening as modifying the suspend time may not entirely solve the issue.

Will have to investigate because when it's blocked (too many requests) strangely enough I'm able to still do some requests to google servers on the same IP.

**Comment by hmcclurg** [comment]
My instance and the vast majority of public instances seem to be affected by this at the moment. I am using `use_mobile_ui: true`

**Comment by Kncuk** [comment]
searx.work is also having this issue, every instanced I've tried so far worked a few times and blocked out since then

**Comment by unixfox** [comment]
Please don't post if the content is not relevant for going to fix this issue.

**Comment by unixfox** [comment]
It's possible that google may do some TLS fingerprinting here as using CURL seems to work with the same IP address.

Introducing HTTP3 support in searxng could also be a good way to circumvent these request limits as google is known to whitelist HTTP3 clients due to this protocol mostly only used in browsers.

**Comment by return42** [comment]
FYI: in my master branch I did a rework of the language & region handling in SearXNG and a rework of the google engine (and other engines that do support lang) based on the new language & region handling.  With this new implementation I see less [google issues](https://darmarit.org/searx/stats?engine=google) and and the improvement of languages and regions is already significant

- https://paulgo.io/search?q=%21google%20chris%20evans%20%3Azh&language=zh  
- https://searx.tiekoetter.com/search?q=%21google%20chris%20evans%20%3Azh&language=zh 

... corresponds to what we have in SearXNG's master.

- https://darmarit.org/searx/search?q=%21google%20chris%20evans%20%3Azh&language=zh 

.. corresponds to the revision of the languages and regions in my master branch.

If you change from `:zh` to `zh-TW` and then to `zh-CN` then you see that the distinction between _traditional_ and _simplified_ also works.

**Comment by unixfox** [comment]
> FYI: in my master branch I did a rework of the language & region handling in SearXNG and a rework of the google engine (and other engines that do support lang) based on the new language & region handling. With this new implementation I see less [google issues](https://darmarit.org/searx/stats?engine=google) and and the improvement of languages and regions is already significant

This issue is about the rate limit from Google servers and not the issue about having less results than normal google.

Based on the changes that I read from your own fork, I don't see anything that will allow solving this rate limit issue.

**Comment by return42** [comment]
Issue should be fixed by PR:

- https://github.com/searxng/searxng/pull/2269

I tested this over a long period and get `searx.exceptions.SearxEngineAccessDeniedException` really rare.

I am going to close this issue ..

If we have problems with google `searx.exceptions.SearxEngineAccessDeniedException`  again, we should open a new issue, because the code base has changed a lot in the meantime and can't be compared to what we had when this issue was opened.
