### ISSUE TITLE
Bug: nyaa engine

### ISSUE THREAD

**Issue by GitTimeraider** [searxng/searxng#1970]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.19-b5371b7a

**How did you install SearXNG?**
searxng docker
**What happened?**
Nyaa engine stops giving results and shows below error

**How To Reproduce**
Enable Nyaa engine and search for something

**Expected behavior**
A list of URLs

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: ssl.SSLError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

![2022-11-23 13_15_40-Greenshot](https://user-images.githubusercontent.com/57343973/203544650-b059edf2-8709-48b0-97b4-1c0ca0dc530e.png)

**Comment by return42** [comment]
Strange, I can't reproduce this issue (on my instance) https://darmarit.org/searx/search?q=%21nyaa+foo

What instance do you use?

**Comment by GitTimeraider** [comment]
> 

https://search.powershellder.com/

**Comment by return42** [comment]
https://search.powershellder.com/search?q=!nyaa+bar

results in ..

![grafik](https://user-images.githubusercontent.com/554536/203553630-d6e65229-3c0b-4527-a0e9-263046098a8e.png)

UPDATE: strange, now it works.

**Comment by GitTimeraider** [comment]
> 

Yeah, I wanted to try something out. Turns out its due to the Netherlands for some reason... when I redirect the instancelocation with  VPN to a different country (in this case UK) it does work.
Will test a few more things but seems to error is not related to the instance itself.
