### ISSUE TITLE
Turning on auto-completion doesn't work

### ISSUE THREAD

**Issue by Zpcin** [searxng/searxng#1973]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.11.18-1cdadf4b

**How did you install SearXNG?**
searxng-docker

**What happened?**
Turning on auto-completion doesn't work

**How To Reproduce**
Turn on the auto-completion to search

**Expected behavior**
Fix this bug

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/62590508/203732647-7698dca6-79c6-4df3-b60d-f4e9ac7ddbb5.png)
![image](https://user-images.githubusercontent.com/62590508/203732739-236563ef-17fe-4885-ab6b-82b148f5f749.png)

**Additional context**
The above is translated from Chinese to English using machine translation

**Comment by return42** [comment]
@zhang2333-Myself does this issue still exist?

**Comment by return42** [comment]
Closed in lack of feedback / ask to reopen if the issue still remains on your side.
