### ISSUE TITLE
Option to remove referral in links

### ISSUE THREAD

**Issue by JReming85** [searxng/searxng#1993]
**Is your feature request related to a problem? Please describe.**
Could we get an option to srub the referral info from links?

Generally when visiting sites, it will include what site you came from.  There are methods to "srub" this data if wanted like how [Anonymizer.info](https://www.anonymizer.info/), [href.li](https://href.li/), or [DeReferrer.Me](https://dereferer.me/) does it. 

**Describe the solution you'd like**
Could have a redirect page that will scrub the referral automatically

e.g. if I click a link, it will then goto `<myfqdn>/noreferal?go=<link>` or something
Can be an external dereferrer or one built in, plenty of example repos https://github.com/topics/dereferrer

**Comment by JReming85** [comment]
example of one I am running https://defer.jremi.com

Just use https://defer.jremi.com?https://github.com/searxng/searxng/issues/1993

**Comment by allendema** [comment]
If specific referers are unwanted just add them to the searxNG plugin here: 
https://github.com/searxng/searxng/blob/0361f8366a62552b275a3ab0d77382c069aa7c1e/searx/plugins/tracker_url_remover.py#L22-L27

This will make sure results are clean.

**Comment by JReming85** [comment]
That will remove http headers?

The referrer will always be the hosting site, e.g. if your site is example.com and you click a link, the new website will see you came from example.com

Looks like it already does this, but could we get a toggle as well?

**Comment by allendema** [comment]
The above plugin "tracker_url_remover.py" will remove given regexes from the url parameters, domain will stay the same.
Example from https://github.com/searxng/searxng/commit/2ca0aa4f29c20f21cce7337b851481bdfaea9a67:  
[stackexchange question](https://meta.stackexchange.com/questions/263392/what-are-these-very-long-parameters-in-so-careers-feedback-always-welcome-url)

This means if there is a result with ```__hstc``` in url, the ```__hstc``` part will be removed.

https://meta.stackexchange.com/?__hstc=104275039.d804df69846ddd42e6beb809e499e579.1438824980727.1439163429713.1439166480698.21

gets changed to

https://meta.stackexchange.com/?

If you mean to change domains from domain.org to example.org, see the plugin [hostname_replace.py](https://github.com/searxng/searxng/blob/master/searx/plugins/hostname_replace.py) and the configuration https://github.com/searxng/searxng/blob/0361f8366a62552b275a3ab0d77382c069aa7c1e/searx/settings.yml#L200-L210

**Comment by mo-rijndael** [comment]
> The referrer will always be the hosting site

Searx adds `rel="noreferrer"` to results. This tells browser to not send `Referrer` header ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer))

**Comment by dalf** [comment]
> Could have a redirect page that will scrub the referral automatically

We can tell the browser not to send the referrer with `rel="noreferrer"`

> Searx adds `rel="noreferrer"` to results. This tells browser to not send `Referrer` header ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer))

SearXNG does the same:
* https://github.com/searxng/searxng/blob/647a0aa98bd1d2000eb1ca5270e017d85d5c3463/searx/templates/simple/base.html#L8
* https://github.com/searxng/searxng/blob/647a0aa98bd1d2000eb1ca5270e017d85d5c3463/searx/templates/simple/macros.html#L9

**Comment by return42** [comment]
Since SearXNG already adds `rel="noreferrer"` to results we can close this issue I think.
