### ISSUE TITLE
[Feature request] Remove unwanted languages, language favourites

### ISSUE THREAD

**Issue by optimist555** [searxng/searxng#2002]
People generally only use the search languages that they can read and speak, which is most of the times only a few.
For example I mostly switch between my native language and English. It just happens to be that every other time I perform a search I want to get results in English and the other time in my native language. It is always a pain to have to scroll through the long list of unwanted languages that I never use to get my prefferred language.

The list of languages could be arranged with select favourites on top of the list with a divider in between, or a quick toggle like DuckduckGo have.

A list of languages in the config file and/or settings menu, with flags to turn them on/off.
In the config file there could also be a "favourite" flag to make that language move to the top of the list.

**Comment by optimist555** [comment]
This was already implemented in new version. Sorry. Thanks, team!

**Comment by return42** [comment]
>  It is always a pain to have to scroll through the long list of unwanted languages that I never use to get my prefferred language.

In my use cases the native language is the language send in the ``Accept-Language`` header (from web browser's defaults).

To switch language (e.g. to english) I use the [search syntax](https://return42.github.io/searxng/user/index.html#select-language), by example I add `:en` to the search term.  If I want regional based language and content I use a region code, by example `:zh-TW` to get content from Taiwan and/or select Chinese (TW --> traditional) language.
