### ISSUE TITLE
Discrepancy with 'Some static files have been modified including Javascript files'

### ISSUE THREAD

**Issue by stephenhodgkiss** [searxng/searxng#2003]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

https://github.com/stephenhodgkiss/searxng-master/commit/d7a3f65e0bdfafec4196ac8a6390e889256d5df7

Forked from master branch to:-
https://github.com/stephenhodgkiss/searxng-master.git

**How did you install SearXNG?**

https://docs.searxng.org/admin/installation-searxng.html#installation-basic
**What happened?**
Installed fine

**How To Reproduce**

**PUBLIC INSTANCE**
https://www.safesearch.center/

Grade js? showing for the HTTP grade when no changes have been made to any of the JS files. 
searxng.head.min.js
searxng.min.js

Unloaded Javascript	
Git URL	script	https://www.safesearch.center/static/themes/simple/js/searxng.head.min.js?20e3306580fcabadf100ed3b88304a00c47e2efe	
script	https://www.safesearch.center/static/themes/simple/js/searxng.min.js?35952b09f314bcafca463675f8ff0a996430454c	
link	https://www.safesearch.center/static/themes/simple/css/searxng.min.css?602132f4766fcc801ef1da3e8bcf5ac2a834e4ee	
other	https://www.safesearch.center/static/themes/simple/img/favicon.png?5967c01292c708951c9df4c54fc0d03cfb2c2582	
img	https://www.safesearch.center/static/themes/simple/img/banner1_728x180.jpg?a2fb24345ec0925d1846b00cbce0bfcf71ab98d8	
img	https://www.safesearch.center/static/themes/simple/img/safezone.png

**Expected behavior**

Grade C for the HTTP grade column

**Screenshots & Logs**

**Additional context**

**Comment by stephenhodgkiss** [comment]
I have declared fixed URL's for both the 2 failing Javascript files. Now there is no suffix of the query parameter, so on the next scan it should be fine.

**Comment by return42** [comment]
Sure your issue is right here / I remember https://github.com/searxng/searxng/issues/1994#issuecomment-1333409487


Your "fork" is just a copy of a unknown commit with a lot of modification .. and your instance ships advertising (links to tracking pages) to SearXNG users .. sorry but we will not support this kind of usage.

**Comment by stephenhodgkiss** [comment]
**(links to tracking pages)** - that is simply not true.

The issue you refer to has already been fixed and are now Grade A+

**Comment by stephenhodgkiss** [comment]
> Sure your issue is right here / I remember [#1994 (comment)](https://github.com/searxng/searxng/issues/1994#issuecomment-1333409487)
> 
> Your "fork" is just a copy of a unknown commit with a lot of modification .. and your instance ships advertising (links to tracking pages) to SearXNG users .. sorry but we will not support this kind of usage.

**(links to tracking pages)** - that is simply not true.

The issue you refer to has already been fixed and are now Grade A+

**Comment by return42** [comment]
> The issue you refer to has already been fixed and are now Grade A+

The link to [#1994 (comment)](https://github.com/searxng/searxng/issues/1994#issuecomment-1333409487) says ..

> Hi @stephenhodgkiss this is the project of the SearXNG server implementation.  Your topic is related to https://github.com/searxng/searx-space/ project.

Asking for a grade on searx.space here in the issue tracker of SearXNG development is just the  wrong place.

**Comment by stephenhodgkiss** [comment]
My mistake, well you have closed the issue already now and tagged it.
