### ISSUE TITLE
Bug: Neeva broken - 405: Method Not Allowed

### ISSUE THREAD

**Issue by TheFrenchGhosty** [searxng/searxng#2007]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.02-ffb72dfd

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('405', 'Method Not Allowed', 'neeva.com')`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by dalf** [comment]
https://github.com/searxng/searxng/blob/ffb72dfdf7c364fa85e6814b9952703d65b1c274/searx/settings.yml#L997

The URL seems to have changed, may be it works with:
`search_url: https://neeva.com/search?q={query}&c=All&src=typedquery&page={pageno}{time_range}`

**Comment by return42** [comment]
@allendema could you have a look at this issue?

For me both URL do work, but on some search terms (e.g. `!nv foo`) I got a `searx.exceptions.SearxEngineXPathException` / while the opener reports a `httpx.HTTPStatusError`.

**Comment by allendema** [comment]
Testing a ```engines/neeva.py``` version using json from the dom.

**Comment by ngosang** [comment]
Any update?

**Comment by allendema** [comment]
There was some kind of captcha for pagination.

**Comment by return42** [comment]
> There was some kind of captcha for pagination.

@allendema do you see a chance to fix this .. or should we remove the engine?

> Testing a engines/neeva.py version using json from the dom.

Do you like to send a RFC .. can we have a look?

**Comment by allendema** [comment]
It is a demo python file outside of searxng but I don't think it is worth the time for further checks because
of captcha being activated on (some) queries and pagination.

So I suggest to remove engine for the time being.
