### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by samsapti** [searxng/searxng#2011]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.05-67eea86b
Instance: https://search.sapti.me

**How did you install SearXNG?**

Custom `docker-compose.yml` file (based on the one from searxng-docker).

**What happened?**

Qwant cannot retrieve results, and gives the following error:

```
qwant ( server API error )
```

**How To Reproduce**

Search for something like `!qwant test`.

**Expected behavior**

Qwant should return results.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/26819407/206529858-6d51153f-6dfd-440b-aac8-dc47ec4b24f8.png)

```
searxng  | 2022-12-08 18:03:18,047 WARNING:searx.engines.qwant: ErrorContext('searx/engines/qwant.py', 128, "raise SearxEngineAPIException('API error::' + msg)", 'searx.exceptions.SearxEngineAPIException', None, ('API error::unknown',)) False
searxng  | 2022-12-08 18:03:18,047 ERROR:searx.engines.qwant: exception : API error::unknown
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/online.py", line 160, in search
searxng  |     search_results = self._search_basic(query, params)
searxng  |   File "/usr/local/searxng/searx/search/processors/online.py", line 148, in _search_basic
searxng  |     return self.engine.response(response)
searxng  |   File "/usr/local/searxng/searx/engines/qwant.py", line 128, in response
searxng  |     raise SearxEngineAPIException('API error::' + msg)
searxng  | searx.exceptions.SearxEngineAPIException: API error::unknown
```

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:128`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by return42** [comment]
FYI: I can't reproduce the issue on my instance [`!qwant test`](https://darmarit.org/searx/search?q=%21qwant+test), but I can see the same error in my [stats](https://darmarit.org/searx/stats?engine=qwant) .. compared to your 100% my percentage is somewhere by 0%:

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 0
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

I also tested https://searx.tiekoetter.com/search?q=%21qwant+test and searx.be .. both do not have this issue.

- Do you have something modified about the quant engine in your `/etc/searxng/settings.yml`? .. I assume not.

Can you debug this code and have a look what the value of `search_results` is?

https://github.com/searxng/searxng/blob/67eea86b35a1f5b9f5f17e0438332f15e852a22e/searx/engines/qwant.py#L116-L128
-

**Comment by samsapti** [comment]
@return42 the contents of `search_results` look like this:

```py
{'status': 'error', 'data': {'error_code': 24}}
```

**Comment by meaz** [comment]
I can reproduce this on this instance: https://search.disroot.org/search

**Comment by samsapti** [comment]
@return42 the error seems to be gone on my instance.

**Comment by return42** [comment]
> @return42 the error seems to be gone on my instance.

Thanks for your feedback!

> I can reproduce this on this instance: https://search.disroot.org/search

Strange disroot.org now also works .. :thinking:  

Should we close this issue? .. or wait a wile to see if issue returns?

**Comment by samsapti** [comment]
Let's wait a day or two. I can see in my Docker logs, that Watchtower upgraded my SearXNG today at around 3 PM CET, maybe the latest commit fixed it (d75ae7c8e64c1e59e8fe32f06f0e0aa1ed8dbbd7) somehow, although it seems unrelated...

**Comment by return42** [comment]
OK when your instance has been update, it has been restarted --> IMO its just a question of time when qwant is blocked again  .. keep us informed / thanks!

**Comment by samsapti** [comment]
@return42 it seems to be gone for good. I'll close this, but if it pops up again we can always reopen.

**Comment by samsapti** [comment]
@return42 it's back: https://search.sapti.me/stats?engine=qwant

**Comment by samsapti** [comment]
It seems to come and go, now it's gone again.

**Comment by return42** [comment]
> @return42 it's back: https://search.sapti.me/stats?engine=qwant

Percentage is somewhere by zero ..

> It seems to come and go, now it's gone again.

I see similar with Google-Web searches on my instance .. :confused:

**Comment by samsapti** [comment]
> I see similar with Google-Web searches on my instance .. :confused:

Yup, me too.

**Comment by return42** [comment]
But the reasons might be different; 

- on Google-Web I see a `searx.exceptions.SearxEngineTooManyRequestsException` from time to time
- in https://github.com/searxng/searxng/issues/1966#issuecomment-1367421303 @nicfab reported a `searx.exceptions.SearxEngineAccessDeniedException` and 
- here in this issue you reported a `searx.exceptions.SearxEngineAPIException`

may it is better we do not mix it all in one ..

**Comment by samsapti** [comment]
My Google issue seems to be the one described in #1966, the access denied one. I agree, let's focus this issue on Qwant.

**Comment by signed-log** [comment]
I've seen it pop up a lot lately on https://search.unlocked.link/stats?engine=qwant


```
Exception | searx.exceptions.SearxEngineAPIException | Percentage | 65
-- | -- | -- | --
API error::unknown
searx/engines/qwant.py:128
response
raise SearxEngineAPIException('API error::' + msg)
```

**Comment by nicfab** [comment]
Same error on my instance.
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.17+54389a29


Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 20
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:128`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

![sshot_2023-02-18_08 24 25](https://user-images.githubusercontent.com/24752671/219847731-ad9ba899-b1e3-4b21-a131-fe234b9cffec.png)

I seem that error is also on other SearXNG instances.

**Comment by ahmad-alkadri** [comment]
Does anybody still have problems with their Qwant engine? Mine has been running consistently well the past week; maybe the API error has been resolved (from their side), perhaps?

**Comment by samsapti** [comment]
Yup, I'm still having issues.

**Comment by rowie** [comment]
same here!

google ( [Ausgesetzt: zu viele Anfragen](https://search.rowie.at/stats?engine=google) )

qwant ( [Server-API-Fehler](https://search.rowie.at/stats?engine=qwant) )

**Comment by return42** [comment]
Please test https://github.com/searxng/searxng/pull/2269

**Comment by rowie** [comment]
How could i test this?

**Comment by return42** [comment]
Issue should be solved by https://github.com/searxng/searxng/pull/2269 .. otherwise leaf a not here / thanks :+1:

**Comment by nicfab** [comment]
After today's latest update, I have the error again.

***

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Branch: master
Version: 2023.3.29+d179b62c

**How did you install SearXNG?**
I installed SearXNG via scripts (no docker).

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 5
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

![sshot_2023-03-29_15 09 07](https://user-images.githubusercontent.com/24752671/228546235-8e802e6c-8882-470c-a8d2-5f059bc394e9.png)

**Comment by return42** [comment]
The situation is fuzzy, we have instances with very different fail rates:

- The fail rate of the engine from the opener @samsapti is currently at 100% --> https://search.sapti.me/stats?engine=qwant
- my engine's fail rate is at 10% --> https://darmarit.org/searx/stats?engine=qwant
- @nicfab's fail rate by 100% --> https://searxng.nicfab.eu/stats?engine=qwant
- @mrpaulblack's fail rate is by 15% --> https://paulgo.io/stats?engine=qwant
- @unixfox's fail rate is by 0% --> https://searx.be/stats?engine=qwant

**Comment by unixfox** [comment]
just a notice my instance (searx.be) is using HTTP1 for the HTTP client in searxng and it is restarted every day. and the requests gets rotated between 4 different servers/IPs.

**Comment by nicfab** [comment]
> just a notice my instance (searx.be) is using HTTP1 for the HTTP client in searxng and it is restarted every day. and the requests gets rotated between 4 different servers/IPs.

I value you and have been following `searx.be` for a long time.
I am not competing with anyone because I am not a developer, and my technical knowledge might be limited. 
Still, I would like to make my SearXNG instance available to everyone so that it is really powerful and functional. 
In that way, I will be satisfied to provide a service to all.
So, I would love to know the details of your configuration so I can try to implement it if I will be able to do it.

> it is restarted every day

Do you set `cron` to run `sudo -H service uwsgi restart searxng` every day?

**Comment by return42** [comment]
>  using HTTP1 for the HTTP client ..

@unixfox did you set ...

```yaml
outgoing:
  enable_http2: false
```

**Comment by unixfox** [comment]
> > using HTTP1 for the HTTP client ..
> 
> @unixfox did you set ...
> 
> ```yaml
> outgoing:
>   enable_http2: false
> ```

That's correct, my settings.yml is available here: https://github.com/unixfox/k8s/blob/master/releases/searx/searx/values.yaml#L80

I feel like the HTTP1 client is faster than HTTP2 when not using uwsgi.

-----------------

> > just a notice my instance (searx.be) is using HTTP1 for the HTTP client in searxng and it is restarted every day. and the requests gets rotated between 4 different servers/IPs.
> 
> I value you and have been following `searx.be` for a long time. I am not competing with anyone because I am not a developer, and my technical knowledge might be limited. Still, I would like to make my SearXNG instance available to everyone so that it is really powerful and functional. In that way, I will be satisfied to provide a service to all. So, I would love to know the details of your configuration so I can try to implement it if I will be able to do it.
> 

Offtopic:

My infrastructure is very complex, it is using [Kubernetes](https://kubernetes.io/) across multiple servers. It's not easy to setup at all, it took me several years to achieve to this stage.
But everything is freely available for everyone here: https://github.com/unixfox/k8s. Minus the documentation.

Do note that I also host other popular services like https://yewtu.be and https://nitter.unixfox.eu so that's why I've a complex setup.

I would prefer to discuss it on matrix :). Let's keep this issue on topic.

> > it is restarted every day
> 
> Do you set `cron` to run `sudo -H service uwsgi restart searxng` every day?

Something like that yes, I don't use the normal cron, but yes you can achieve the same goal with your command.

**Comment by samsapti** [comment]
I tried setting `enable_http2: false`, didn't help. I'm currently having a fail rate of ~95% on my instance, even after restarting.

**Comment by samsapti** [comment]
@return42 I've been able to get a 95% reliability for Qwant by setting all `suspended_times.*` to `0`. This also fixes a lot of other search engines, such as Google and Bing, but not Brave.

https://search.sapti.me/stats

**Comment by nicfab** [comment]
> suspended_times.*

As suggested by @samsapti, I did some tests with the following values in the file `settings.yml`:

```
suspended_times:
    SearxEngineAccessDenied: 0
    SearxEngineCaptcha: 0
    SearxEngineTooManyRequests: 0
    cf_SearxEngineCaptcha: 0
    cf_SearxEngineAccessDenied: 0
    recaptcha_SearxEngineCaptcha: 0
```
After some stress tests, I do not have errors till now, except for Brave (_**Suspended: too many requests**_).

**Comment by return42** [comment]
@samsapti , @nicfab : thanks a lot for sharing your experience .. :+1:

The defaults we use as suspend time are from earlier days, and they are applied equally to almost all engines.

We need to gather long term experience to see which engines might block us. I have reduced them to one hour for me and have also had quite good experiences so far.

May be we need lower defaults or individual suspend time for each engine .. but first we need more practical experience .. if you share your experience here, it will help us to make decisions later on.

---

Brave is an XPath engine that will always cause problems unless we implement a python module for it that emulates the requests better "to fly under the bot radar";

- https://github.com/searxng/searxng/issues/2294

**Comment by nicfab** [comment]
Startpage returns the error "**Suspended: CAPTCHA**", and I disabled it on my browser by which I am doing tests.

**Comment by samsapti** [comment]
I'll try to increase mine to an hour and test that at some point. Right now everything other than Brave (too many requests) and Startpage (CAPTCHA) works fine.

**Comment by nicfab** [comment]
Leaving 0 as a value, now I have an error from DDG (Suspended: access denied).

**Comment by return42** [comment]
> Startpage returns the error "Suspended: CAPTCHA", and I disabled it on my browser by which I am doing tests.

> Leaving 0 as a value, now I have an error from DDG (Suspended: access denied).

Now your IP is blocked by DDG (&Startpage) .. most often this is caused by a bot that passes our limiter .. 
that is why we have the "suspend" time, to pause a engine for a while .. so that the IP is taken off the block list again.

If your IP continuously sends "bot like" requests (when suspend time is 0) to e.g. DDG or startpage, then the IP is permanently set to a CAPTCHA or blocked by the origin search page.

The rest periods (suspend time) are to avoid that SearXNG's IP is evaluated as a real bot and is permanently blocked.

I have good experience with ~1-2 hour~ 20min suspend time on AccessDenied:

```yaml

search:
  suspended_times:
    # Engine suspension time after error (in seconds; set to 0 to disable)
    # For error "Access denied" and "HTTP error [402, 403]"
    SearxEngineAccessDenied: 1200
```

Please note that the behaviour is not deterministic, it depends on how often a bot manages to pass the limiter of SearXNG / how frequent such bot requests are and how the bot defence mechanisms of the search engine (DDG, Startpage, ...) are implemented ...and we do not know that, we can only speculate about it. Therefore, we can only find ideal values from practical experience.

**Comment by unixfox** [comment]
Can we get back on topic about qwant? If you are running into issues with other engines please open separate issues or comment existing issues related to the engine.

It makes things difficult to read later on when looking again at this issue for further troubleshooting of the error.

No need to reply just add an :eye: reaction.

**Comment by samsapti** [comment]
The Qwant server API error is back on my instance, and it seems to be consistent. I'll try with one hour.

**Comment by samsapti** [comment]
> I have good experience with 1-2 hour suspend time on AccessDenied:
> ```yaml
> search:
>   suspended_times:
>     # Engine suspension time after error (in seconds; set to 0 to disable)
>     # For error "Access denied" and "HTTP error [402, 403]"
>     SearxEngineAccessDenied: 1200
> ```

@return42 isn't that 20 minutes?

**Comment by return42** [comment]
Oops .. yes it is 20min :facepalm: 

> Can we get back on topic about qwant? If you are running into issues with other engines please open separate issues or comment existing issues related to the engine.

We should open a discussion "suspended_times: practical experience / best values?

**Comment by Monotone4964** [comment]
Having this issue today on my searxng page.... I tried to add the suspended settings and got an error about my version in docker-compose being 3.7??

**Comment by samsapti** [comment]
@Monotone4964 the suspended settings should go in `settings.yml`, i.e. SearXNG settings file, not `docker-compose.yml`.

**Comment by dsmith2001** [comment]
EDIT by admin:  you should also read https://docs.searxng.org/admin/answer-captcha.html

----

Hey guys, there's a good chance your IP is being blocked by Qwant due to the high number of requests. I was able to fix it this way:

**Step 1:** Create a local SOCKS proxy (SSH tunnel)
ssh -D 8080 -q -N yourusername@yourserver.com
**Step 2:** Set up the proxy in Firefox (SOCKS5, 127.0.0.1:8080)
**Step 3:** Visit Qwant and do a search query. You will be greeted with this CAPTCHA.
![image](https://github.com/searxng/searxng/assets/129474298/4273b456-1290-4ec7-af1a-81394484b12a)
**Step 4:** Solve the CAPTCHA. Qwant now works in searxNG again.
![image](https://github.com/searxng/searxng/assets/129474298/9b31ab2f-3620-4505-8243-d37d33f2c848)

**Comment by hiiamboris** [comment]
Just visited qwant.com normally and passed captcha and it fixed it in the SearXNG. Thanks @dsmith2001

**Comment by samsapti** [comment]
@dsmith2001 does that solve the problem permanently, or only temporarily?

**Comment by dsmith2001** [comment]
> @dsmith2001 does that solve the problem permanently, or only temporarily?

I'm sure you could get CAPTCHAs again in the future, but I haven't had to do it again since.

**Comment by return42** [comment]
> I'm sure you could get CAPTCHAs again in the future, but I haven't had to do it again since.

Thanks a lot / good to know :+1: .. how long is it ago?

**Comment by dsmith2001** [comment]
> Thanks a lot / good to know 👍 .. how long is it ago?

It's been a day so far. I'm hoping it'll last a few days or until my instance hits an undisclosed search limit from Qwant again...

**Comment by jboucher614** [comment]
> Just visited qwant.com normally and passed captcha and it fixed it in the SearXNG. Thanks @dsmith2001 

This worked for me, too. I believe your SearXNG instance has to be coming from your same IP, otherwise you need the proxy method mentioned above.

**Comment by return42** [comment]
I think we can close this issue, the answer is given by @dsmith2001 in https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619. In addition I added a description to the docs: [Answer CAPTCHA from server’s IP](https://docs.searxng.org/admin/answer-captcha.html).

**Comment by nicfab** [comment]
I have the same error again:

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 70
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by return42** [comment]
Hi @nicfab .. did you tried what @dsmith2001 suggested https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619

Alternatively here is a description https://docs.searxng.org/admin/answer-captcha.html

**Comment by nicfab** [comment]
> Hi @nicfab .. did you tried what @dsmith2001 suggested [#2011 (comment)](https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619)
> 
> Alternatively here is a description https://docs.searxng.org/admin/answer-captcha.html

I tried but from the shell I receive the following error:

`curl: (7) Failed to connect to 127.0.0.1 port 8080 after 6 ms: Couldn't connect to server`

**Comment by return42** [comment]
Not sure what goes wrong ... step by step:

On your local desktop open a terminal and type ... replace `<user>` with your account name on the remote::

    ssh -q -N -D 8080 <user>@nicfab.eu

Open another terminal on your local desktop and test the (ssh) proxy 

    $ curl -x socks://127.0.0.1:8080 http://ipecho.net/plain

This should return ``15.161.40.80``.  Did it worked until here? .. if so, then open your firefox browser on your local desktop and setup a proxy in firefox like shown here in the screenshot

- https://docs.searxng.org/admin/answer-captcha.html

In firefox open http://ipecho.net/plain .. you should see ``15.161.40.80`` .. if it works until here, then open https://www.qwant.com/ in this firefox and answer the captcha.

If all is done, don't forget to unset the proxy in firefox and stop the ssh command from above (CTRL-C).

Now your qwant engine on nicfab.eu should work again --> https://searxng.nicfab.eu/searxng/search?q=%21qwant%20mace%20parker

**Comment by nicfab** [comment]
Thank you @return42 

> Not sure what goes wrong ... step by step:
> 
> On your local desktop open a terminal and type ... replace `<user>` with your account name on the remote::
> 
> ```
> ssh -q -N -D 8080 <user>@nicfab.eu
> ```
I did it.
> 
> Open another terminal on your local desktop and test the (ssh) proxy
> 
> ```
> $ curl -x socks://127.0.0.1:8080 http://ipecho.net/plain
> ```
> 
> This should return `15.161.40.80`. Did it worked until here? .. if so, then open your firefox browser on your local desktop and setup a proxy in firefox like shown here in the screenshot
> 

Unfortunately, I see the same error:

`curl: (7) Failed to connect to 127.0.0.1 port 8080 after 5 ms: Couldn't connect to server`

I don't know.

**Comment by unixfox** [comment]
Please continue the discussion on Matrix.

**Comment by unixfox** [comment]
Solved through matrix.

**Comment by notkudu** [comment]
> EDIT by admin: you should also read https://docs.searxng.org/admin/answer-captcha.html
> 
> Hey guys, there's a good chance your IP is being blocked by Qwant due to the high number of requests. I was able to fix it this way:
> 
> **Step 1:** Create a local SOCKS proxy (SSH tunnel) ssh -D 8080 -q -N [yourusername@yourserver.com](mailto:yourusername@yourserver.com) **Step 2:** Set up the proxy in Firefox (SOCKS5, 127.0.0.1:8080) **Step 3:** Visit Qwant and do a search query. You will be greeted with this CAPTCHA. ![image](https://private-user-images.githubusercontent.com/129474298/239300623-4273b456-1290-4ec7-af1a-81394484b12a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjQwMzQsIm5iZiI6MTcyOTM2MzczNCwicGF0aCI6Ii8xMjk0NzQyOTgvMjM5MzAwNjIzLTQyNzNiNDU2LTEyOTAtNGVjNy1hZjFhLTgxMzk0NDg0YjEyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxODQ4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2JhMjRlYzI2OTg0YmViOWMzMzZkZDA5ZTQ1MzM4YmY2YzRhYjQ1OWMyMDMzNWVmYjhhOGUyMTc3MjhlMTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eiV1kMBUtOcfbNyzwSf8KsODGiKyRALuASqwoHfSCGE) **Step 4:** Solve the CAPTCHA. Qwant now works in searxNG again. ![image](https://private-user-images.githubusercontent.com/129474298/239300962-9b31ab2f-3620-4505-8243-d37d33f2c848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjQwMzQsIm5iZiI6MTcyOTM2MzczNCwicGF0aCI6Ii8xMjk0NzQyOTgvMjM5MzAwOTYyLTliMzFhYjJmLTM2MjAtNDUwNS04MjQzLWQzN2QzM2YyYzg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxODQ4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjYyZGQwZWIwZjhiMmZlZTc5YzljNDQ5NDZjZjZlZjJmYjhhOWM5OGY3N2E0NTkwNDk0ODM2Yzg0MmRlYzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K10cq5wM9m1Ur8RcVB7-IUbDiD3416otnqOiKfMpnmQ)

I tried this, but qwant won't give me the captcha when using the browser for some reason, and I yes I did make sure that the ip address is the server's ip

**Comment by return42** [comment]
> I tried this, but qwant won't give me the captcha when using the browser for some reason, and I yes I did make sure that the ip address is the server's ip

- https://github.com/searxng/searxng/issues/3929
