### ISSUE TITLE
Bug: dogpile engine

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#202]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

* https://darmarit.org/searx
* https://searx.zackptg5.com/  commit a8988885 

**How did you install SearXNG?**
N/A

**What happened?**
![image](https://user-images.githubusercontent.com/1594191/125407990-b846c500-e3ba-11eb-9e05-2d809e5da7eb.png)

**How To Reproduce**
See above.

**Expected behavior**
To get the result or disable the engine.

**Additional context**

According to the logs it seems the engine redirects to http://omblockedips.com (not https). It shows the Recaptcha challenge.
So I suggest to add `omblockedips.com` to https://github.com/searxng/searxng/blob/4f09c7ba0c16965db6f502060be0d94d8d105ceb/searx/network/raise_for_httperror.py#L54

**Technical report**

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 100
  * Parameters: `(None, None, 'omblockedips.com')`
  * File name: `searx/search/processors/online.py:99`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Checker
  * simple: `httpx.UnsupportedProtocol `,
  * paging: `httpx.UnsupportedProtocol `,

**Comment by return42** [comment]
> To get the result or disable the engine.

@dalf I decided to remove the dogpile engine / about details see commit message in #203

If you think it is OK to remove, you can merge #203.
