### ISSUE TITLE
Bug: google engine in Garuda instance

### ISSUE THREAD

**Issue by ameyjoshi3068** [searxng/searxng#2022]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.14-9e9f57e4

**How did you install SearXNG?**
It came preinstalled with garuda linux firedragon browser.
**What happened?**
Everytime I search something google results are not loaded

**How To Reproduce**
Just open firegragon and search

**Screenshots & Logs**

**Additional context**
I use garudalinux instance which is public I think

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Duplicate of https://github.com/searxng/searxng/issues/1735#issuecomment-1234096653

> It came preinstalled with garuda linux firedragon browser.
> I use garudalinux instance which is public I think

Its not clear to me which instance (URL) you are using --> The option can only be set by the instance maintainer.  If you are not the maintainer, please contact the maintainer.
