### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by Elendil211** [searxng/searxng#2026]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-0dac581c

**How did you install SearXNG?**
searxng-docker

**What happened?**
brave always fails to return results

**Additional context**
settings.yml is updated

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1815#issuecomment-1282220775

**Comment by Elendil211** [comment]
No, because the fix from that bug report does not work. It's a different issue. My instance is up to date, and uses the up to date settings.yml that contains the mentioned lines.

**Comment by return42** [comment]
> My instance is up to date, and uses the up to date settings.yml that contains the mentioned lines.

Do you have a `/etc/searxng/settings.yml`?  .. can you post its content here or a pastebin just to verify.

**Comment by Elendil211** [comment]
I edited the wrong file. The fix indeed works as it is supposed to work. My fault, sorry.
