### ISSUE TITLE
pip can't install fasttext-wheel

### ISSUE THREAD

**Issue by johnklos** [searxng/searxng#2028]
Version of SearXNG is 18-December-2022.
commit b92748219504e67b18771b9831ffcebe76cca62f, not forked.
Installed manually.

Dependencies are installed until this error:
Collecting markdown-it-py==2.1.0
  Using cached markdown_it_py-2.1.0-py3-none-any.whl (84 kB)
Collecting typing_extensions==4.4.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
ERROR: Could not find a version that satisfies the requirement fasttext-wheel==0.9.2 (from searxng) (from versions: none)
ERROR: No matching distribution found for fasttext-wheel==0.9.2

Reproduce by running:
git clone https://github.com/searxng/searxng.git
cd searxng
pip install -e .

System is NetBSD-current, 9.99.99, aarch64.

Expected behavior is for fasttext-wheel to be installed via pip.

fasttext requires numpy, pybind11 and more, which is rather heavy. Is there any easy way to skip fasttext and use langdetect?

**Comment by return42** [comment]
Instead of `fasttext-wheel` install `fasttext` .. but before ..

> fasttext requires numpy

install numpy from your package manager.

> pip install -e .

IDK what you want to do with SearXNG's modules installed by, but this installation method is not recommended (never install SearXNG modules in your local python, use a virtuealenv at least).

> System is NetBSD-current, 9.99.99

We recommend to install as described here, where you can also see what distribution we support (and test): https://docs.searxng.org/admin/installation-searxng.html

> aarch64

It often happens that wheels are compiled only for common PC architectures and for the glibc library.  For other architectures or other libraries (e.g. musl libc) you have to compile it yourself --> instead of the wheel you have to install the module without wheel.

Compare [Built Distributions](https://pypi.org/project/fasttext-wheel/#files)

>  Is there any easy way to skip fasttext and use langdetect?

langdetect is less precise / see discussion in PR https://github.com/searxng/searxng/pull/1969

In PR https://github.com/searxng/searxng/pull/2019 we removed it.

**Comment by dalf** [comment]
@johnklos, can you try to install fasttext instead of fasttext-wheel ?

**Comment by johnklos** [comment]
> Instead of fasttext-wheel install fasttext

Tried. See below.

> install numpy from your package manager.

py310-numpy-1.23.5 is installed.

> use a virtuealenv at least).

This was a previously working searxng install and the recommended installation method from https://docs.searxng.org/admin/installation-searxng.html was followed, including creating virtualenv. "pip install -e " is part of those instructions.

> you have to compile it yourself

fasttext claims to only support Linux and macOS. I hope this is not truly the case and is just a case of the authors being a bit lazy.

When attempting to compile it for python, it fails to find numpy (ModuleNotFoundError: No module named 'numpy'), amongst other issues, which I will raise with them.

Until those issues are fixed by fasttext, what's the simplest way to get a git clone of searxng from before the fasttext move?

**Comment by johnklos** [comment]
Or how does one skip the fasttext requirement if one simply doesn't want to do language autodetection?

**Comment by dalf** [comment]
You can apply this patch to make fasttext optional:
```patch
diff --git a/requirements.txt b/requirements.txt
index 5c45fff6b..dde4727a7 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -15,4 +15,3 @@ setproctitle==1.3.2
 redis==4.4.0
 markdown-it-py==2.1.0
 typing_extensions==4.4.0
-fasttext-wheel==0.9.2
diff --git a/searx/utils.py b/searx/utils.py
index 2157a4ce0..f9ad8e63a 100644
--- a/searx/utils.py
+++ b/searx/utils.py
@@ -15,7 +15,6 @@ from os.path import splitext, join
 from random import choice
 from html.parser import HTMLParser
 from urllib.parse import urljoin, urlparse
-import fasttext
 
 from lxml import html
 from lxml.etree import ElementBase, XPath, XPathError, XPathSyntaxError, _ElementStringResult, _ElementUnicodeResult
@@ -51,12 +50,9 @@ _STORAGE_UNIT_VALUE: Dict[str, int] = {
 _XPATH_CACHE: Dict[str, XPath] = {}
 _LANG_TO_LC_CACHE: Dict[str, Dict[str, str]] = {}
 
-_FASTTEXT_MODEL: Optional[fasttext.FastText._FastText] = None
+_FASTTEXT_MODEL: Optional["fasttext.FastText._FastText"] = None
 """fasttext model to predict laguage of a search term"""
 
-# Monkey patch: prevent fasttext from showing a (useless) warning when loading a model.
-fasttext.FastText.eprint = lambda x: None
-
 
 class _NotSetClass:  # pylint: disable=too-few-public-methods
     """Internal class for this module, do not create instance of this class.
@@ -630,7 +626,10 @@ def eval_xpath_getindex(elements: ElementBase, xpath_spec: XPathSpecType, index:
     return default
 
 
-def _get_fasttext_model() -> fasttext.FastText._FastText:
+def _get_fasttext_model() -> "fasttext.FastText._FastText":
+    import fasttext
+    # Monkey patch: prevent fasttext from showing a (useless) warning when loading a model.
+    fasttext.FastText.eprint = lambda x: None
     global _FASTTEXT_MODEL  # pylint: disable=global-statement
     if _FASTTEXT_MODEL is None:
         _FASTTEXT_MODEL = fasttext.load_model(str(data_dir / 'lid.176.ftz'))
```

---

I've started https://github.com/dalf/fasttext-predict/ which won't require numpy (this is experimental)
Published here for now: https://test.pypi.org/project/fasttext-predict/

You can try to compile it by replacing `fasttext-predict` by:
```
fasttext-predict @ git+https://github.com/dalf/fasttext-predict@master#egg=fasttext-predict
```

**Comment by johnklos** [comment]
Those patches work.

Also, fasttext-predict compiles without any issues on NetBSD/aarch64, and on other architectures on NetBSD.

Thank you!

**Comment by dalf** [comment]
I close this issue: the PR 2047 has been merged and fasttext-predict can be compiled on NetBSD/aarch64 and FreeBSD/amd64 (according to my test).
