### ISSUE TITLE
Bug: library of congress engine

### ISSUE THREAD

**Issue by aming-r** [searxng/searxng#2029]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('503', 'Service Unavailable', 'loc.gov')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
@aming-r I can't reproduce this issue / by example --> [!loc foo](https://darmarit.org/searx/search?q=%21loc+foo) 

Can you give is more informations? .. `('503', 'Service Unavailable', 'loc.gov')` --> may be library of congress was temporary not online?

**Comment by return42** [comment]
Library of congress engine does work in current master ..

Close in lack of feedback.
