### ISSUE TITLE
Increase in image size and use of resources

### ISSUE THREAD

**Issue by ngosang** [searxng/searxng#2033]
In recent PR the langdetect library was changes with fasttest for language detection. https://github.com/searxng/searxng/commit/9925a209503cc41e37a1c032548a5fd8fd8ea362 & https://github.com/searxng/searxng/commit/ed901ab18edddcfd566ac37ddb1b429969ccc2ad

I pretty sure that library is a bit better in many ways but it increases the image size because it uses several data scientist libraries. 
* 22 MB compressed: 62.26 MB => 84.94 MB https://hub.docker.com/r/searxng/searxng/tags
* 103 MB uncompressed: 168 MB => 271 MB

The memory usage of searxng is almost the same but I also notice more CPU usage in each search.

I believe that this increase in resources is not justified. It would be necessary to know how much better that model is. I have used langdetect for many years and it works very very well. Other libraries could also be evaluated.

**Comment by dalf** [comment]
Here an experimental drop-in replacement without the numpy dependency:
* https://github.com/dalf/fasttext-predict 
* there are wheels for various architectures which avoid to deal with two packages fasttext-wheel and fasttext.
* published for now here: https://test.pypi.org/project/fasttext-predict/

**Comment by jamesoff** [comment]
numpy seems to be hard to build on Raspbian (https://github.com/numpy/numpy/issues/21038) and the version being pulled in isn't on piwheels for Python 3.7, so I'm in favour of this. Instead of going down the rabbit hole of upgrading/building Python on my Pi, I just pulled out the `fasttext` changes enough for the install to complete and the service to work - for my personal instance I don't need search language detection since I'm about the only user, and I only search in one language ;)

Or, could this be expressed as an "extra" for pip so that those who don't need it don't have it pulled in? If that's acceptable, happy to look at the changes.

If anyone else ends up here looking for it, this was my hack (although I probably could have just `git revert`ed the two commits in the initial post:

```diff
diff --git a/requirements.txt b/requirements.txt
index 5c45fff6..dde4727a 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -15,4 +15,3 @@ setproctitle==1.3.2
 redis==4.4.0
 markdown-it-py==2.1.0
 typing_extensions==4.4.0
-fasttext-wheel==0.9.2
diff --git a/searx/utils.py b/searx/utils.py
index 2157a4ce..df96106f 100644
--- a/searx/utils.py
+++ b/searx/utils.py
@@ -15,7 +15,6 @@ from os.path import splitext, join
 from random import choice
 from html.parser import HTMLParser
 from urllib.parse import urljoin, urlparse
-import fasttext

 from lxml import html
 from lxml.etree import ElementBase, XPath, XPathError, XPathSyntaxError, _ElementStringResult, _ElementUnicodeResult
@@ -51,11 +50,6 @@ _STORAGE_UNIT_VALUE: Dict[str, int] = {
 _XPATH_CACHE: Dict[str, XPath] = {}
 _LANG_TO_LC_CACHE: Dict[str, Dict[str, str]] = {}

-_FASTTEXT_MODEL: Optional[fasttext.FastText._FastText] = None
-"""fasttext model to predict laguage of a search term"""
-
-# Monkey patch: prevent fasttext from showing a (useless) warning when loading a model.
-fasttext.FastText.eprint = lambda x: None


 class _NotSetClass:  # pylint: disable=too-few-public-methods
@@ -630,11 +624,8 @@ def eval_xpath_getindex(elements: ElementBase, xpath_spec: XPathSpecType, index:
     return default


-def _get_fasttext_model() -> fasttext.FastText._FastText:
-    global _FASTTEXT_MODEL  # pylint: disable=global-statement
-    if _FASTTEXT_MODEL is None:
-        _FASTTEXT_MODEL = fasttext.load_model(str(data_dir / 'lid.176.ftz'))
-    return _FASTTEXT_MODEL
+def _get_fasttext_model() -> None:
+    return None
```

**Comment by return42** [comment]
> numpy seems to be hard to build on Raspbian
> Or, could this be expressed as an "extra" for pip s

You could try https://github.com/dalf/fasttext-predict / see https://github.com/searxng/searxng/issues/2033#issuecomment-1362119388 above.

fasttext-predict does not need numpy / fasttext-predict is in an experimental state but it will be the solution we take for SearXNG.

**Comment by ngosang** [comment]
It's good enough. Thank you!
