### ISSUE TITLE
Route over tor

### ISSUE THREAD

**Issue by zlElo** [searxng/searxng#2038]
**Describe the solution you'd like**
A option to route the requests over tor (only a easy check button or switch button in the settings). This function is already implemented in whoogle search.

**Comment by danktankk** [comment]
tor is only as secret as its endpoint.  lol  funny that people dont get that...  haha  if you really think you have done something by using tor to hide yourself, you are truly a fool.

**Comment by zlElo** [comment]
Hi, too bad you can't speak to one normally here.  But whatever.  If you only had the endpoint/exitnode then that would of course be insecure or pointless.  Built for this case there is also the entry node and the middle relay.  Means the exit node only knows that the request comes from the middle relay and that it only comes from the entry node.  everything is encrypted up to the exit node.  Of course, the exit node is the point where the hoster knows what was called, but he doesn't know who called it.  To what extent it now makes sense to only use Tor when searching remains to be seen, but I think you should also try to offer features that other alternatives offer in order to stand up to the competition... (Whoogle has the feature)

Greets

**Comment by mo-rijndael** [comment]
But how this will affect user? User already talks only with Searx server. If you need to hide your IP, you can connect to SearX via Tor. But way how SearX instance connects to engines is server administrator business

**Comment by zlElo** [comment]
Good point.  The question is rather how Whoogle then uses that.  I didn't think about it at all, I have to say, thank you for your comment :) But how about making the feature available for the admins of the servers?  So that the server asks the individual search engines via Tor?  Does this make sense?!  xD
