### ISSUE TITLE
btdigg's search results are basically adult content

### ISSUE THREAD

**Issue by Zpcin** [searxng/searxng#2041]
Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG
searxng- 2022.12.02-ffb72dfd

How did you install SearXNG?
SearXNG docker

What happened?
btdigg's search results are basically adult content, even when the safe search is set to HIGH

How To Reproduce
Search with !btdigg

Expected behavior
Keeping search results free of adult content

Screenshots & Logs
![image](https://user-images.githubusercontent.com/62590508/209342121-d8e1184c-0697-4691-a3cc-b3ab9de8715f.png)

Additional context
The above is translated from Chinese to English using machine translation

**Comment by NV6bxpYSKb9h9O8uDIm6hw86EDg7HnbcQXOovhw** [comment]
btdigg does not support safe search.

**Comment by return42** [comment]
Torrent and safesearch is a contradiction in terms ;-)
