### ISSUE TITLE
Search result engine listing layout shift

### ISSUE THREAD

**Issue by MorsMortium** [searxng/searxng#2043]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.12.23-e8f72d70-dirty

**How did you install SearXNG?**
Searxng-git AUR package, built today.

**What happened?**
Too many engines appeared in a single line, for a search result.

**How To Reproduce**
Search something, that is first result for most engines.

**Expected behavior**
The line listing the engines breaks earlier, to keep width the same as the result itself.

**Screenshots & Logs**
![Screenshot_20221223_202818](https://user-images.githubusercontent.com/44305161/209399256-90921dca-2d03-4d1d-85fb-6abc76ed3541.png)

**Additional context**

**Comment by ahmad-alkadri** [comment]
Reproduced this bug on SearxNG built on Docker (branch `master`, latest commit [9b31976](https://github.com/searxng/searxng/commit/9b31976cf3fe4d7e33c39b93e79ef88eae295444). I think this is just a CSS problem. Simply putting the list of engines into a flex element and flex-wrap them seems to be enough. I'll try to work on this.
