### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by aming-r** [searxng/searxng#2044]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('./h2', 'len(xpath_str) < 1')`
  * File name: `searx/engines/xpath.py:209`
  * Function: `response`
  * Code: `title = extract_text(eval_xpath_list(result, title_xpath, min_len=1))`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1429#issuecomment-1173161759
