### ISSUE TITLE
Bug: mojeek engine (parsing error)

### ISSUE THREAD

**Issue by stef204** [searxng/searxng#2046]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.23-e8f72d70-dirty

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('./h2', 'len(xpath_str) < 1')`
  * File name: `searx/engines/xpath.py:209`
  * Function: `response`
  * Code: `title = extract_text(eval_xpath_list(result, title_xpath, min_len=1))`

**Comment by return42** [comment]
@tiekoetter you fixed the XPath of title in https://github.com/searxng/searxng/pull/1341 .. it seems mojeek has changed its layout another time .. if you have time, could you have a look again / thanks!
