### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by samsapti** [searxng/searxng#2049]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.26-0d489617
Instance: https://search.sapti.me

**How did you install SearXNG?**

searxng-docker

**What happened?**

Google engine returns "Suspended: access denied".

**How To Reproduce**

Search for "!go test".

**Expected behavior**

Google should return results.

**Screenshots & Logs**

**Additional context**

This happens despite `use_mobile_ui: true`.

**Technical report**

UPDATED by @return42 / copied from https://search.sapti.me/stats?engine=google

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Google engine returns "Suspended: access denied".

Hi @samsapti the issue has already reported by @nicfab in https://github.com/searxng/searxng/issues/1966

I close this issue .. if I missed something we can reopen.
