### ISSUE TITLE
RHEL (and RHEL-based distros) support in installation scripts

### ISSUE THREAD

**Issue by EricZhang456** [searxng/searxng#2062]
**Is your feature request related to a problem? Please describe.**
Right now the installation scripts only recognize CentOS 7 among all the Red Hat forks. However CentOS is essentially gone and CentOS 7 is reaching EOL. The installation scripts are currently broken on RHEL and RHEL forks like Rocky Linux. Here is the output of running the `searxng.sh` script on Rocky Linux 9.1.
```
ERROR: rocky-9.1: nginx not yet implemented
ERROR: rocky-9.1: apache not yet implemented
ERROR: rocky-9.1: uWSGI not yet implemented
ERROR: rocky-9.1: pkg_install LXC_BASE_PACKAGES not yet implemented
```

**Describe the solution you'd like**
- In RHEL-based distros, `ID_LIKE` in `/etc/os-release` contains `rhel`, indicating that it is a RHEL-based distro (see below). I haven't tested this in mainline RHEL yet. The [official documentation](https://www.freedesktop.org/software/systemd/man/os-release.html#Examples) in freedesktop.org demonstrated a way to read `ID_LIKE`.
- Most of the Fedora packages in `searxng.sh` works in RHEL, however RHEL doesn't have `@development-tools` (alternative is a package group called "Development Tools") and some packages required for SearXNG (like ShellCheck) are in the EPEL repository, which isn't enabled by default on a standard install. A way to detect if EPEL is enabled is by looking for the `epel-release` package. RHEL runs uWSGI in emperor-tyrant mode as well.
- `yum` mentions in `lib.sh` can be removed since RHEL started using `dnf` starting in version 8.

**Describe alternatives you've considered**
None 

**Additional context**
`/etc/os-release` of Rocky Linux 9.1
```bash
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

**Comment by return42** [comment]
> Right now the installation scripts only recognize CentOS 7 among all the Red Hat forks. 
> The installation scripts are currently broken on RHEL and RHEL forks like Rocky Linux. 

That is not fully correct; RHEL is based on fedora and fedora is supported by the [installation scripts](https://docs.searxng.org/admin/installation-scripts.html#installation-scripts) and documented in the [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html).

BTW click on the **Fedora / RHEL** tab ..

![grafik](https://user-images.githubusercontent.com/554536/218140512-9ead924c-595b-4efc-a86e-5abea17d2717.png)

Add and maintain a new distro in the installation scripts is a lot of work, there are a lot of distro specific quirks (you pointed out some already) .. I am very sorry but I don't see a chance to add niche distros like rocky-linux on the ToDo stack of the SearXNG team.

I hope the [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html) is an alternative.  On the other hand: we are always happy when new developers join the team and take on tasks like this.

I'm sorry that I can't do more for you.
