### ISSUE TITLE
Displayable, Editable page number, during pagination.

### ISSUE THREAD

**Issue by llmII** [searxng/searxng#2067]
**Is your feature request related to a problem? Please describe.**

A clear, visible, editable way of changing the page number instead of just prev/next is needed.

**Describe the solution you'd like**

The easiest solution I know of is to change the input for page number, which is currently set to hidden style, to number style, add a bit of CSS to say, give it a width of 6ch, and right align the inner text.

**Describe alternatives you've considered**

Not entirely certain of other alternatives, this might would need discussion. The aforementioned solution is something I hacked together on my instance but I don't know or CSS preprocessors so it's most certainly a hack in search of a better solution if it the method by which I went were to be included.

**Additional context**

The entire reason I finally decided "I'm going to run my own meta-search engine" was because google made a (in my opinion) bad design decision. Infinite scroll in a mobile device tends to make sense, and their "More Results" button at the end was good. They decided to apply the same approach to desktop and I found this unacceptable. Furthermore I believe their new method and ad blockers don't necessarily work well together. On more than one occasion I saw that the results of the search at google repeated themselves after so much scrolling and/or clicking the more results button which in essence makes one lose their place. There are several other reasons that are hard to put words to as to why I like regular pagination for desktop in a search scenario, but one easily described reason is that I prefer to be able to go back and forward and manipulate my search terms based upon lack of results or quick deterioration of results relevancy and infinite scroll does not do this well unless one is mentally counting each result and/or filtering out ad/sponsored result sets. With google's position untenable I was looking for another solution and quickly decided not to end up locked to another company that may decide "google did it, it's good, we'll do it too" and ended up at SearXNG.

SearXNG's ability to disable infinite scroll in favor of pagination is a boon, but lacking visibility into "which page number am I on in the results now" bothered me, along with page number jumps being limited to incremental by +/-1. I fixed it for my local instance so that I now can jump variably to any page number, and it shows what page number is next so you know what location you're at (which is always the currently displayed number, minus one).

I believe others might benefit from such visibility as to their page number. An example of how it looks in my case after edits is below, though I also figure mine is function over form and it could be made to be far prettier probably.
![image](https://user-images.githubusercontent.com/40866124/210184159-c8b6f4eb-dc61-46f5-8ca4-13cda8f0c53e.png)

**Comment by llmII** [comment]
Just realized the project is AGPL3 which means that despite the modifications I made being junk and unfit for a direct merge I need to share them. Attached is the result of git diff (will need to rename to *.diff, is uploaded as text to allow github to put it in the comment).

[searxng.diff](https://github.com/searxng/searxng/files/10331142/searxng.txt)

**Comment by return42** [comment]
@llmII thank you for paying attention to the license :+1:

> Attached is the result of git diff 

A link to your public branch makes things a lot easier, especially when you continue with modifications.

> I believe others might benefit from such visibility as to their page number. An example of how it looks in my case after edits is below, though I also figure mine is function over form and it could be made to be far prettier probably.

Is your instance public, can we see your patch in action?

**Comment by llmII** [comment]
> @llmII thank you for paying attention to the license +1

Sure thing, part of the reason behind attaching in the comment was to remain compliant, making sure I don't lose the license to utilize this project myself.

> A link to your public branch makes things a lot easier, especially when you continue with modifications.

Honestly, the scope of the change was so limited that I didn't consider creating my own branch anywhere. If it would help I can do so, but I'm not entirely certain how helpful it would be to do so for what amounts to a 3 line change and one of those changes being directly to a minified CSS file. I am ignorant as to how CSS preprocessing works or how to make the changes in a manner that'd be beneficial to the project aside from a quick dirty hack to reference for someone with the knowledge to turn such into something usable from a general standpoint.

> Is your instance public, can we see your patch in action?

I'd not like for the instance to make it onto any lists, but can see it in action at `search dot amlegion dot org` (yes, slightly ridiculously obfuscated).

Main concerns with public listing is if there were any liabilities for myself and possibility of load being beyond capability to handle.

**Comment by llmII** [comment]
Tried my changes under mobile... it really ruins mobile experience.

**Comment by return42** [comment]
> Tried my changes under mobile... it really ruins mobile experience.
> I am ignorant as to how CSS preprocessing works

Its very simple, read https://docs.searxng.org/dev/quickstart.html

**Comment by llmII** [comment]
@return42 am trying to follow that guide, but something depends on jpeg-recompress and that simply is an unbuildable artifact here (unless I want to lose my desktop, it depends on mozjpeg, which conflicts jpeg-turbo, and even trying to build it after redoing system to use mozjpeg for a moment the binary fails to build). That said, I'm just hoping, and trying to run the `gmake themes.all` command and see what I come up with (this means anything I commit likely will need to have that redone if there are jpeg compressions going on or something). I do not have any linux machines, and am working on this under FreeBSD. 

Now I'm at the point of giving up trying:
```
BUILDENV  PYENV     [virtualenv] requirements.sha256 failed
BUILDENV            [virtualenv] - 5a79c9a1a8b947661a6d8bc4bbb821b56f8c782efd4c7cfad2bf161b126c8fcf  /usr/home/llmII/workspace/projects/contributing/searxng/requirements-dev.txt
BUILDENV            [virtualenv] - 8b2b4e320c29090725a22c3e294100b49ea6c67a4bf1001e06ff0620bc1f033a  /usr/home/llmII/workspace/projects/contributing/searxng/requirements.txt
BUILDENV  PYENV     [virtualenv] installing /usr/home/llmII/workspace/projects/contributing/searxng/requirements*.txt into local/py3
```

Not entirely sure where to go from there, to make it worse it just loops and you see "BUILDENV BUILDENV BUILDENV" lines (it gets longer).

**EDIT 2**:
My current awful workaround for this is disabling the error check in `pyenv.install` (`gmake run` worked), now to make sure I undo that before commits...

**EDIT 3**:
FreeBSD's sha256sum, `/sbin/sha256sum` is not a GNU sha256sum, and does not support the same command line options. The solution is a symlink like as created below:
```
cd ~/.local/bin
ln -s /usr/local/bin/gsha256sum gsha256sum
```

Not sure if this should be documented, or scripts modified to say "hey, we don't have GNU's version, bug user to get it and let's use that" or check the output of `sha256sum --help | grep version` since that's so far guaranteed to fail under FreeBSD unless gsha256sum is linked in path.
