### ISSUE TITLE
Accessing home page works but not in code with Docker local instance

### ISSUE THREAD

**Issue by AnErrupTion** [searxng/searxng#2070]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.12.30-647a0aa9

**How did you install SearXNG?**
Using searxng-docker

**What happened?**

I can access the home page (at ``http://localhost:8080/``) just fine and I can even search. However, when I try to make the HTTP request in C#, I get a "Forbidden" status code.
**How To Reproduce**

I used exactly the steps at https://docs.searxng.org/admin/installation-docker.html.
**Expected behavior**

I should be able to use the search API just fine in code just like in a web browser (however I do intend on using my instance only in code).
**Screenshots & Logs**

**Additional context**

I've tried adding the ``Accept`` and ``Accept-Encoding`` headers, but that doesn't change anything.
Additionally, here's a simple request that fails in code but works in the browser: ``http://localhost:8080/search?q=test``
Finally, I've tried the potential fix in #1162, which is to not mount the files when using ``docker run``. However, that doesn't change anything for me. The other one (which is to separate the formats into multiple lines) is not applicable for me because I'm using the default settings.

**Comment by ahmad-alkadri** [comment]
Hi @AnErrupTion. Can you share here your C# code that you used to call the endpoint? I'd like to see if I can reproduce this Issue on my machine. Thanks.

**Comment by mrpaulblack** [comment]
Just as a quick idea you could get a hTTP 429 from the searxng limiter plugin, it will match user agents which it thinks are bots and answer those requests with a HTTP 429 and also do some basic rate limiting. If it is your personal local instance you can disable the limiter plugin without any consequences in your `searxng/settings.yml` file like so: https://github.com/searxng/searxng/blob/aba969ccf02071cf81d7b11e3c89dffc7b111d1a/searx/settings.yml#L59

**Comment by AnErrupTion** [comment]
After some investigation I saw that I was using proxies, and I don't know how I didn't think of this earlier, but yeah it's not going to work when trying to access localhost... So yeah, the issue is fixed!
