### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by MarvinMynx** [searxng/searxng#2091]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.26-0d489617

**How did you install SearXNG?**
I Installed SearXNG using the official wiki. It was a one Liner Installation Skript without Docker.

**What happened?**
One day these Messages about duckduckgo just appeared.

**How To Reproduce**
Honestly, I don't know.

**Expected behavior**
Getting Search Results from duckduckgo too/again?

**Screenshots & Logs**
Not applicable.

**Additional context**
There is no additional Context. It just started to appear and is since not gone away anymore, for days now.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate of https://github.com/searxng/searxng/issues/2080 fixed by https://github.com/searxng/searxng/issues/2081

> Version: 2022.12.26-0d489617

You need to update your instance.

**Comment by MarvinMynx** [comment]
How to Update if not APT Update && APT Upgrade?

**Comment by MarvinMynx** [comment]
How to Update if not APT Update && APT Upgrade?

**Comment by return42** [comment]
Depends how you installed SearXNG ..

> I Installed SearXNG using the official wiki. It was a one Liner Installation Skript without Docker.

I assume you followed [Installation Script instruction](https://docs.searxng.org/admin/installation-scripts.html#installation-scripts)  .. in the right bottom you see a link pointing to "further read" [How to update](https://docs.searxng.org/admin/update-searxng.html#update-searxng)

**Comment by MarvinMynx** [comment]
Thank you very much, didn't quite see it the first time. This helped :)
