### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by carlric** [searxng/searxng#2092]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.29-fc9986de

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Version: 2022.10.29-fc9986de

Please update your instance / or ask the maintainer of the instance to update.

duplicate, see https://github.com/searxng/searxng/issues/2091#issuecomment-1375288105
