### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by keithdanielll** [searxng/searxng#2093]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.30-647a0aa9

!
**How did you install SearXNG?**

Docker
**What happened?**

DuckDuckgo says access denied
**How To Reproduce**

any search
**Expected behavior**

no access denied
**Screenshots & Logs**

**Additional context**

I don't think that my instance has that much visitors to be of any importance, not much is happening there in terms of CPU usage and traffic
Duckduckgo is set for search suggestions
**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Version: 2022.12.30-647a0aa9

Please update your instance / or ask the maintainer of the instance to update.

duplicate, see https://github.com/searxng/searxng/issues/2091#issuecomment-1375288105
