### ISSUE TITLE
Override uWSGI worker count from env

### ISSUE THREAD

**Issue by immanuelfodor** [searxng/searxng#2096]
**Is your feature request related to a problem? Please describe.**
The [current worker count setting is `%k`](https://github.com/searxng/searxng/blob/master/dockerfiles/uwsgi.ini), which is the amount of cores detected, but since uWSGI workers consume about 150-200M of RAM, a system with lots of cores can explode in RAM consumption. 

**Describe the solution you'd like**
Please make worker count overridable through an environment variable: 
- https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables
- https://stackoverflow.com/questions/53283263/is-it-possible-to-override-uwsgi-ini-file-with-environment-variables
- https://stackoverflow.com/questions/47091122/uwsgi-set-configuration-depending-on-environment-variable

**Describe alternatives you've considered**
I understand that I can supply a whole `uwsg.ini` file but I don't want to do that, I have no problem with the other default settings. Maybe `workers` and `threads` could be configurable both but `workers` is a must. I don't want to use ConfigMap in k8s, a simple env setting should suffice.

**Additional context**
There is already a logic to override searxng `settings.yml` values with env vars, maybe this can be applied too, should the `patch_uwsgi_settings` function contain more logic as `patch_searxng_settings` does: https://github.com/searxng/searxng/blob/master/dockerfiles/docker-entrypoint.sh

Memory consumption on a 6 core k8s node run from the container shell (`rss` is the non-paged pyhsical memory, resident set size):

```
/usr/local/searxng # ps -o pid,user,vsz,rss,comm,args
PID   USER     VSZ  RSS  COMMAND          COMMAND
    1 root      816    4 tini             /sbin/tini -- /usr/local/searxng/dockerfiles/docker-entrypoint.sh
    7 searxng   28m  14m uwsgi            {uwsgi} uWSGI master
   14 searxng  200m 139m Thread-4 (initi  {Thread-4 (initi} uWSGI worker 1
   16 searxng  209m 149m 4103b35d-3dae-4  {4103b35d-3dae-4} uWSGI worker 2
   22 searxng  205m 146m fb0c5ef1-207c-4  {fb0c5ef1-207c-4} uWSGI worker 3
   32 searxng  215m 155m Thread-4 (initi  {Thread-4 (initi} uWSGI worker 4
   36 searxng  200m 140m Thread-4 (initi  {Thread-4 (initi} uWSGI worker 5
   42 searxng  200m 139m Thread-4 (initi  {Thread-4 (initi} uWSGI worker 6
  139 root     1692 1124 sh               sh
  156 root     1616 1012 ps               ps -o pid,user,vsz,rss,comm,args
```

![image](https://user-images.githubusercontent.com/21174107/211810922-af142e63-7234-4d11-954a-63cbf69512fd.png)

**Comment by immanuelfodor** [comment]
Overriding this value could also solve https://github.com/searxng/searxng/issues/447

**Comment by dalf** [comment]
You can mount the `/etc/searx/uwsgi.ini` file to provide your own uwsgi configuration.

The base configuration is https://github.com/searxng/searxng/blob/master/dockerfiles/uwsgi.ini

**Comment by immanuelfodor** [comment]
Yes, I understand but as I said in the description, I don't want to keep a copy of the file. In case the defaults are changed, I would need to update those manually. I just want to override the most problematic setting.

A `sed` here for `UWSGI_WORKERS` and `UWSGI_THREADS`: https://github.com/searxng/searxng/blob/master/dockerfiles/docker-entrypoint.sh#L62
Like this one: https://github.com/searxng/searxng/blob/master/dockerfiles/docker-entrypoint.sh#L73
It could do the trick.

**Comment by immanuelfodor** [comment]
Here is a PR for that, we've already talked about it too much but it's easy: https://github.com/searxng/searxng/pull/2097
