### ISSUE TITLE
Bug: duckduckgo engine (Error: httpx.ConnectTimeout behind VPN)

### ISSUE THREAD

**Issue by mrwestside12** [searxng/searxng#2098]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.01.09-afd71a6c

**How did you install SearXNG?** 
Docker 
 
Docker
**What happened?** 
  
suspended timeout on ddg and yahoo

**How To Reproduce**
 
don't search for a little bit 

**Expected behavior**

for it to search without timeout or suspended timeout

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 30
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Your internet connection seems sometimes a little bit slow .. increment timeout.

**Comment by mrwestside12** [comment]
I switched from windows to ubuntu on searxng and it's been perfect ever since. I truly think it was because it was behind a vpn on windows.
