### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by mrwestside12** [searxng/searxng#2099]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.01.09-afd71a6c

**How did you install SearXNG?**
Docker

searxng-docker

**What happened?**

Too many request brave

**How To Reproduce**

Search with searxng

**Expected behavior**

For it to not mess up

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 10
  * Parameters: `('Too many request',)`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1651
