### ISSUE TITLE
searxng git version not updating, AttributeError: module 'searx.version_frozen' has no attribute 'DOCKER_TAG'

### ISSUE THREAD

**Issue by technonerd33** [searxng/searxng#2125]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
commit 522ba9a14b7872d95e3ae61bc3a652b50100cc3d
Powered by searxng- 2022.08.10-2bfb269f

**How did you install SearXNG?**
git clone 
make docker.build

**What happened?**
```
% make docker.build
ERROR: gentoo-2.9: nginx not yet implemented
ERROR: gentoo-2.9: apache not yet implemented
ERROR: gentoo-2.9: uWSGI not yet implemented
ERROR: gentoo-2.9: pkg_install LXC_BASE_PACKAGES not yet implemented
PYENV     [install] pip install -e 'searx[test]'
Obtaining file:///home/techno/code/searxng
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/techno/code/searxng/setup.py", line 7, in <module>
          from searx.version import VERSION_TAG, GIT_URL
        File "/home/techno/code/searxng/searx/version.py", line 82, in <module>
          vf.DOCKER_TAG,
      AttributeError: module 'searx.version_frozen' has no attribute 'DOCKER_TAG'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ERROR: ./manage: line 643: error while pip install (local/py3/bin)
make: *** [Makefile:96: docker.build] Error 42
```

**How To Reproduce**

**Expected behavior**
docker image built and tagged with correct/current git commit

**Screenshots & Logs**

**Additional context**
2022.08.10-2bfb269f is the initial git clone, git pull and make docker.build would work and updates would apply but version wouldnt update until now

**Comment by return42** [comment]
Interim we had some mess with the version numbers (pip applied rules it hasn't before) / this issue is fixed by https://github.com/searxng/searxng/pull/2122 

@dalf [posted on Matrix](https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$soxi6IM1d2jsXgknb8kiDzEhxbRxwaEXGJBL0Zd7Hp8?via=libera.chat&via=matrix.org&via=tchncs.de)

> --> quick fix (pick one)
> * either add DOCKER_TAG  to searx/version_frozen.py if you want to keep the same displayed version
> * or call `python -m searx.version freeze` to update searx/version_frozen.py
