### ISSUE TITLE
Bug: petalsearch engine

### ISSUE THREAD

**Issue by Octothorn** [searxng/searxng#2128]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.1.23+522ba9a1

**How did you install SearXNG?**
Docker

**What happened?**

**How To Reproduce**

    !petalsearch jane and john doe

**Expected behavior**
Success for petalsearch

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('412', 'Precondition Failed', 'petalsearch.com')`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by Octothorn** [comment]
Confirmed here as still an issue with 2023.1.29+9d102fb0 

Error (copypasted from current revision output)
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('412', 'Precondition Failed', 'petalsearch.com')`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by dalf** [comment]
The website has changed, the engine needs to be updated or delete if it can't be fixed.

**Comment by return42** [comment]
@ahmad-alkadri @allendema do you see a chance to fix petalsearch .. otherwise I tend to remove it .. suggestions welcome .. thanks :+1:

**Comment by ahmad-alkadri** [comment]
> @ahmad-alkadri @allendema do you see a chance to fix petalsearch .. otherwise I tend to remove it .. suggestions welcome .. thanks 👍

I don't know a lot about petalsearch, but a I did a quick glance at its xpath definitions

https://github.com/searxng/searxng/blob/2cf1425e8bc5d3143b6e001e82a034a794e8a206/searx/settings.yml#L1871-L1888

and it seems that the xpaths are no longer correct; even the title's path is left empty. Surprising; I wonder how it could work before.

I'll try to look into this thanks.

**Comment by ahmad-alkadri** [comment]
I think I found a solution, but I'm not sure if the approach is the best one or if there's any other better options.

Hence I made the PR as a draft here: #2188. I'm open to discussions on this approach.

cc: @return42

**Comment by Octothorn** [comment]
@ahmad-alkadri 

After updating and config changes, that seems to be working for me again.  Nice work!
