### ISSUE TITLE
[Feature] disable search term suggestions

### ISSUE THREAD

**Issue by marcelmindemann** [searxng/searxng#2140]
Hello, 
I do not find the search term suggestions very useful, and on mobile they take up a lot of space which could be used better for search results.
I couldn't find any way to disable search suggestions, so I would like to propose a setting in settings.yml that disables them.
If you know of any theme that already provides this, I'd be happy to receive links.

**Comment by keithdanielll** [comment]
searxng/settings.yml

[https://docs.searxng.org/admin/engines/settings.html#use-default-settings](url)

**Comment by JulienSambre** [comment]
Hi!
Just switched from SearX to SearXNG and this is the "main" difference that is an issue. A setting to disable that would be wonderful ;).
