### ISSUE TITLE
Error updating searxng

### ISSUE THREAD

**Issue by CustardFlan** [searxng/searxng#2145]
Well, the next error came up when trying updating searx to the last commit:

`(searx-pyenv) searxng@chocoserver:~/searxng-src$ pip install -U -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///usr/local/searxng/searxng-src
  Preparing metadata (setup.py) ... done
Requirement already satisfied: certifi==2022.12.7 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2022.12.7)
Requirement already satisfied: babel==2.11.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2.11.0)
Requirement already satisfied: flask-babel==3.0.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (3.0.0)
Requirement already satisfied: flask==2.2.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2.2.2)
Requirement already satisfied: jinja2==3.1.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (3.1.2)
Requirement already satisfied: lxml==4.9.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (4.9.2)
Requirement already satisfied: pygments==2.14.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2.14.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2.8.2)
Requirement already satisfied: pyyaml==6.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (6.0)
Requirement already satisfied: httpx[http2]==0.21.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (0.21.2)
Requirement already satisfied: Brotli==1.0.9 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (1.0.9)
Requirement already satisfied: uvloop==0.17.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (0.17.0)
Requirement already satisfied: httpx-socks[asyncio]==0.7.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (0.7.2)
Requirement already satisfied: setproctitle==1.3.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (1.3.2)
Requirement already satisfied: redis==4.4.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (4.4.2)
Requirement already satisfied: markdown-it-py==2.1.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (2.1.0)
Requirement already satisfied: typing_extensions==4.4.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (4.4.0)
Requirement already satisfied: fasttext-predict==0.9.2.1 in /usr/local/searxng/.local/lib/python3.10/site-packages (from searxng==2023.1.29+9d102fb08) (0.9.2.1)
Requirement already satisfied: pytz>=2015.7 in /usr/local/searxng/.local/lib/python3.10/site-packages (from babel==2.11.0->searxng==2023.1.29+9d102fb08) (2022.7.1)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/searxng/.local/lib/python3.10/site-packages (from flask==2.2.2->searxng==2023.1.29+9d102fb08) (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from flask==2.2.2->searxng==2023.1.29+9d102fb08) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from flask==2.2.2->searxng==2023.1.29+9d102fb08) (8.1.3)
Requirement already satisfied: httpcore<0.15.0,>=0.14.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (0.14.7)
Requirement already satisfied: python-socks>=2.0.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (2.1.1)
Requirement already satisfied: async-timeout>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (4.0.2)
Requirement already satisfied: sniffio in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (1.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.10/dist-packages (from httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (2.1.1)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (1.5.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from jinja2==3.1.2->searxng==2023.1.29+9d102fb08) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/searxng/.local/lib/python3.10/site-packages (from markdown-it-py==2.1.0->searxng==2023.1.29+9d102fb08) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil==2.8.2->searxng==2023.1.29+9d102fb08) (1.16.0)
Requirement already satisfied: hpack<5,>=4.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from h2<5,>=3->httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (4.0.0)
Requirement already satisfied: hyperframe<7,>=6.0 in /usr/local/searxng/.local/lib/python3.10/site-packages (from h2<5,>=3->httpx[http2]==0.21.2->searxng==2023.1.29+9d102fb08) (6.0.1)
Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpcore<0.15.0,>=0.14.0->httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (0.12.0)
Requirement already satisfied: anyio==3.* in /usr/local/searxng/.local/lib/python3.10/site-packages (from httpcore<0.15.0,>=0.14.0->httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (3.6.2)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.0->httpx-socks[asyncio]==0.7.2->searxng==2023.1.29+9d102fb08) (3.3)
Installing collected packages: searxng
  Running setup.py develop for searxng
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [39 lines of output]
        2023-01-29 19:51:55,570 INFO:root: running develop
        /usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/usr/local/searxng/searxng-src/setup.py", line 19, in <module>
            setup(
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
            return distutils.core.setup(**attrs)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
            super().run_command(command)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
            cmd_obj.ensure_finalized()
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
            self.finalize_options()
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 52, in finalize_options
            easy_install.finalize_options(self)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
            self.local_index = Environment(self.shadow_path + sys.path)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
            self.scan(search_path)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
            self.add(dist)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
            dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
            self.parsed_version,
          File "/usr/local/searxng/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
            raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
        pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

**Comment by CustardFlan** [comment]
And, using: sudo -H ./utils/searxng.sh instance update

fetch from https://github.com/searxng/searxng and reset to origin/master
cd /usr/local/searxng/searxng-src
git fetch origin "master"
git reset --hard "origin/master"
  |searxng| From https://github.com/searxng/searxng
  |searxng|  * branch              master     -> FETCH_HEAD
  |searxng| HEAD is now at 9d102fb0 Merge pull request #2132 from dalf/update_pr_1967
pip install -U pip
pip install -U setuptools
  |searxng| Requirement already satisfied: pip in /usr/local/searxng/searx-pyenv/lib/python3.10/site-packages (22.3.1)
pip install -U wheel
pip install -U pyyaml
pip install -U -e .
  |searxng| Requirement already satisfied: setuptools in /usr/local/searxng/searx-pyenv/lib/python3.10/site-packages (67.0.0)
  |searxng| Requirement already satisfied: wheel in /usr/local/searxng/searx-pyenv/lib/python3.10/site-packages (0.38.4)
  |searxng| Requirement already satisfied: pyyaml in /usr/local/searxng/searx-pyenv/lib/python3.10/site-packages (6.0)
  |searxng| Obtaining file:///usr/local/searxng/searxng-src
  |searxng|   Preparing metadata (setup.py): started
  |searxng|   Preparing metadata (setup.py): finished with status 'done'
  |searxng| ERROR: Exception:
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
  |searxng|     status = run_func(*args)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
  |searxng|     return func(self, options, args)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
  |searxng|     requirement_set = resolver.resolve(
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
  |searxng|     collected = self.factory.collect_root_requirements(root_reqs)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
  |searxng|     req = self._make_requirement_from_install_req(
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
  |searxng|     cand = self._make_candidate_from_link(
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
  |searxng|     self._editable_candidate_cache[link] = EditableCandidate(
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 322, in __init__
  |searxng|     super().__init__(
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
  |searxng|     self.dist = self._prepare()
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
  |searxng|     dist = self._prepare_distribution()
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 332, in _prepare_distribution
  |searxng|     return self._factory.preparer.prepare_editable_requirement(self._ireq)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 641, in prepare_editable_requirement
  |searxng|     req.check_if_exists(self.use_user_site)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 402, in check_if_exists
  |searxng|     existing_dist = get_default_environment().get_distribution(self.req.name)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 267, in get_distribution
  |searxng|     self._ws.require(name)
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
  |searxng|     needed = self.resolve(parse_requirements(requirements))
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
  |searxng|     raise VersionConflict(dist, req).with_context(dependent_req)
  |searxng| pip._vendor.pkg_resources.ContextualVersionConflict: (redis 4.4.2 (/usr/local/searxng/searx-pyenv/lib/python3.10/site-packages), Requirement.parse('redis==4.4.0'), {'searxng'})

**Comment by return42** [comment]
See https://github.com/searxng/searxng/discussions/2120#discussioncomment-4749860 .. if it does not help, please reinstall SearXNG.
