### ISSUE TITLE
autocomplete is not user-friendly

### ISSUE THREAD

**Issue by flaotte** [searxng/searxng#2149]
2023.01.20+316fcd5e

**How did you install SearXNG?**
Kubernates inside trueNAS

**What happened?**
When autocomplete is selected with mouse then I need to click for search button or enter to start the search.
Autocomplete source is google.

**How To Reproduce**
Start typing, when autocomplete suggestions shows up, choose any with left mouse button. Search is not initiated until enter is pressed or search icon pressed with mouse.

**Expected behavior**
when I click on autocomplete suggestion, I get results.

**Screenshots & Logs**
N/A

**Additional context**
N/A

**Comment by Solirs** [comment]
Opened a PR about a setting for fixing that

**Comment by return42** [comment]
Closed by https://github.com/searxng/searxng/pull/2331
