### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by caiojares** [searxng/searxng#215]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**
no
**What happened?**
ddg engine isn't working

**How To Reproduce**
any search

**Expected behavior**
error message

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:93`
  * Function: `response`
  * Code: `get(url_ping, headers=headers_ping)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:99`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'html.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:99`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:99`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
DDG works e.g. here https://darmarit.org/searx/search?q=%21ddg%20foo&categories=none&language=de-DE

May be you are using an old not updated engine / you have to answer the questions:

> Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG
> How did you install SearXNG?
> How To Reproduce?

**Comment by unixfox** [comment]
@return42 this error most probably come from https://searx.be/stats?engine=duckduckgo because the errors are the same.

I think it's just that sometimes duckduckgo doesn't respond in time, I'll add more timeout.

You may safely close this issue.

**Comment by return42** [comment]
@unixfox thanks for additional informations ..

> I think it's just that sometimes duckduckgo doesn't respond in time, I'll add more timeout.

In my instance ddg has the default timeout (3sec) and I observed some "ReadTimeout" .. https://darmarit.org/searx/stats?engine=duckduckgo

> You may safely close this issue.

I will close this issue, if someone comes here and think this problem resists, please ask to reopen the issue.
