### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by sabag** [searxng/searxng#2151]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.1+d9ab8364

**How did you install SearXNG?**
searxng-docker

**What happened?**

search for any term and you get an error on the side panel

**How To Reproduce**
search for any term

**Expected behavior**
no error

**Screenshots & Logs**

N/A

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/2146
