### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by nicfab** [searxng/searxng#2152]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.1+d9ab8364

**How did you install SearXNG?**
Installed manually and not with docker

**What happened?**
After launching a query search, I receive the error.

**How To Reproduce**
After launching a query search, I receive the error.

**Expected behavior**
No errors.

**Screenshots & Logs**

![sshot_2023-02-02_10 45 39](https://user-images.githubusercontent.com/24752671/216290911-f32e2dcc-5bf0-41dc-b67e-04e4055fdf2f.png)

**Additional context**
None.

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 95
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:122`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 5
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:122`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 0
  * Parameters: `(None, None, 'localhost')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by nicfab** [comment]
After some tests, the error above related only to Startpage does not appear anymore.
I continue having errors on DDG, but I commented on an already-opened issue.
However, I will continue monitoring the issue.

**Comment by return42** [comment]
```
Error

    Error: 2 redirects, maximum: 0
    Percentage: 95
```

The redirects shown in the error above are redirects to CAPTCHA --> 

- https://github.com/searxng/searxng/issues/1081#issuecomment-1099214986

![sshot_2023-02-02_10 45 39](https://user-images.githubusercontent.com/24752671/216290911-f32e2dcc-5bf0-41dc-b67e-04e4055fdf2f.png)

The *access denied* issue from duckduckgo is tracked in -->

- https://github.com/searxng/searxng/issues/2146

I'm going to close this issue / both issues are already tracked in the issue tracker.

> However, I will continue monitoring the issue.

@nicfab: if you have more related, please report to the dedicated issue / thanks :+1:

**Comment by nicfab** [comment]
I see the error again.
