### ISSUE TITLE
[Feature request] Allow exposing metrics in Prometheus/OpenMetrics format

### ISSUE THREAD

**Issue by theS1LV3R** [searxng/searxng#2154]
**Is your feature request related to a problem? Please describe.**
Many self-hosters may use some form of monitoring or metrics gathering. A common format for this is to use prometheus-style metrics. For example:

```
api_http_requests_total{method="POST", handler="/messages"} 20591
```

This metric could have different tags, depending on (in this case) the method and handler, and the amount of entries matching those tags.

**Describe the solution you'd like**
An endpoint at `/metrics` exposing the metrics found at `/stats` (and ideally even more, like instance version, uptime, etc).

**Describe alternatives you've considered**
Parsing the HTML returned from `/stats` could be possible, but doesn't seem like the best solution, and is likely to break easily.

**Additional context**
- <https://prometheus.io/docs/concepts/data_model/>
- <https://prometheus.io/docs/practices/naming/>
- <https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md> - The OpenMetrics spec
- <https://play.grafana-zabbix.org/metrics> - Example metrics from zabbix's demo grafana instance

**Comment by Solirs** [comment]
Dont know what maintainers think but im definitely on board with this! I think its a good idea that could make searxng much more appealing for self hosting and even more feature-rich.

**Comment by Bnyro** [comment]
If anyone is still following up on this thread, please try out https://github.com/searxng/searxng/pull/3835.
