### ISSUE TITLE
[Feature Request] Site Icons

### ISSUE THREAD

**Issue by seniorm0ment** [searxng/searxng#2162]
It would be very nice to be able to fetch site icons next to search results.
DuckDuckGo does this very nicely.

**Comment by return42** [comment]
@seniorm0ment thanks for pointing out, but we had this topic in the past without finding an acceptable solution:

- https://github.com/searxng/searxng/pull/441
- https://github.com/searxng/searxng/issues/1014

Before we start a third thread about this topic I suggest to continue the discussions in the existing threads.

**Comment by seniorm0ment** [comment]
I will look in those, my bad I searched but I failed to use the proper term "favicon" haha.
Thanks.
