### ISSUE TITLE
Bug: alexandria engine

### ISSUE THREAD

**Issue by olidiaks** [searxng/searxng#2164]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.4+7320b0c7

**How did you install SearXNG?**

searcng-dcoker
**What happened?**

**How To Reproduce**

possible

**Expected behavior**

alexandra thro http error

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('500', 'Internal Server Error', 'api.alexandria.org')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
The the search form on https://www.alexandria.org/ is dead .. www.alexandria.org itself is broken / don't use it.

I leaf this issue open just as reminder to check if www.alexandria.org will work in a few days .. otherwise we should drop this search engine from settings.yml file.

**Comment by olidiaks** [comment]
Thank you for information. But yesterday it was working.

**Comment by return42** [comment]
And its now working again .. https://darmarit.org/searx/search?q=%21alexandria+foo :+1:
