### ISSUE TITLE
Add page support to Wiby

### ISSUE THREAD

**Issue by wibyweb** [searxng/searxng#2170]
If I'm reading the settings file correctly, this is all that would need to be updated:

search_url : https://wiby.me/json/?q={query}
changed to
search_url : https://wiby.me/json/?q={query}&p={pageno}

**Comment by return42** [comment]
Thanks :+1: .. I merged your PR from searx in https://github.com/searxng/searxng/pull/2175

**Comment by wibyweb** [comment]
Awesome, thank you! :)
