### ISSUE TITLE
Bug: flickr engine

### ISSUE THREAD

**Issue by AlFcl** [searxng/searxng#2179]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.10+2cf1425e

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng/issues/1879
