### ISSUE TITLE
No Connection over URL Cloudflare Tunnel ERROR: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Baumart** [searxng/searxng#2180]
v: 2023.2.10+2cf1425e

docker

ERR_TOO_MANY_REDIRECTS

Open over URL (CloudFlare tunnel)

no Connection

![image](https://user-images.githubusercontent.com/89712869/218197996-12e74d0d-a516-4fe5-9afb-1e1fc7b42c4a.png)
![image](https://user-images.githubusercontent.com/89712869/218198063-5806f10c-6254-4ea4-a303-4348bf405d9e.png)
![image](https://user-images.githubusercontent.com/89712869/218198096-75a20b74-8bf3-43a7-96f5-53860cea2e3b.png)

**Comment by return42** [comment]
Sorry we do not support (issues with) cloudflare.

**Comment by Baumart** [comment]
okok but what it can be?
