### ISSUE TITLE
Improve documentation on opensearch protocol

### ISSUE THREAD

**Issue by Jeidnx** [searxng/searxng#2190]
**Is your feature request related to a problem? Please describe.**

If i add my searxng instance in firefox via opensearch, it uses http to connect by default. This request is upgraded, but initial connection is still http.

**Describe the solution you'd like**

Make it more obvious to the user that this is the case and how to change it. Maybe include the `base_url`parameter in the default config with a short message about this.

**Describe alternatives you've considered**

Detect the used protocol and use that in the opensearch response

**Additional context**

my current solution is to set the `base_url` parameter to `https://search.example.com`. This overwrites the opensearch response with https.

**Comment by return42** [comment]
The `base_url` is described in the server section of the setup [doc](https://docs.searxng.org/admin/engines/settings.html#server)

https://github.com/searxng/searxng/blob/295c87a926c3deb1e438234550a9d8fbbaad17fa/docs/admin/engines/settings.rst#L224-L227

> Improve documentation on opensearch protocol

The `base_url`  is *"Used to create correct inbound links"*

Its not only opensearch that fails when you didn't set this URL

@Jeidnx what do you suggest where we should point out to set `base_url` / what do you think is more eye-catching?

> Detect the used protocol and use that in the opensearch response

That's not possible .. in most architectures SearXNG is *behind* a reverse proxy, the SearXNG process do not know what the URL of the reverse proxy is .. thats why `base_url` is one of the mandatory settings.

**Comment by Jeidnx** [comment]
Hearing that the `base_url` setting is mandatory is really surprising to me. After following the complete step-by-step installation instructions i haven't even heard of it. These instructions point you to the  [default config](https://github.com/searxng/searxng/blob/52f6bc745bfff4f0cb523098fae624656e54c82e/utils/templates/etc/searxng/settings.yml) where there is no mention of `base_url` in the server context.

In my opinion the `base_url` setting should be included in this file with a comment to let you know about it's importance, something like this:
```
# Enter the full public url of your instance here, to ensure proper compatability
# base_url: "http://example.com"
```

**Comment by return42** [comment]
@Jeidnx I have tried to improve the documentation, could you please do a review of 

- https://github.com/searxng/searxng/pull/2201 

thanks!

**Comment by Jeidnx** [comment]
#2201 is exactly what I had in mind. Thank you for implementing this so quickly!

You can go ahead and merge + close this in my opinion.
