### ISSUE TITLE
Build in Calculator

### ISSUE THREAD

**Issue by WreckingBANG2** [searxng/searxng#2191]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A Calculator like most search-engines like google and brave have. You type in your calculation and when you press enter a small calulator gets displayed.
![grafik](https://user-images.githubusercontent.com/117087198/218485130-90992f45-7bc6-4a59-b263-efe5be1aff64.png)

**Describe alternatives you've considered**
Answer in autocomplete

**Additional context**
None

**Comment by return42** [comment]
duplicate: https://github.com/searxng/searxng/pull/1022
