### ISSUE TITLE
Bug: bing engine (IPv4/IPv6 redirects)

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2193]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/return42/searxng
Branch: darmarit.org
Version: 2023.2.11+bd1b5619

**How did you install SearXNG?**

[Installation scripts](https://docs.searxng.org/admin/installation-scripts.html)

**What happened?**

bing issues related to  redirects

**How To Reproduce**

`curl --ipv4  'https://www.bing.com'` works but when I use `curl -L 'https://www.bing.com'` its an endless redirect from https://www.bing.com/ to https://cn.bing.com/ and back.

```
curl -L  'https://www.bing.com'
curl: (47) Maximum (50) redirects followed

$ ping www.bing.com
PING www.bing.com(g2a02-26f0-ab00-0000-0000-0000-0214-8ebb.deploy.static.akamaitechnologies.com (2a02:26f0:ab00::214:8ebb)) 56 data bytes

$ ping cn.bing.com
PING a-0001.a-msedge.net (204.79.197.200) 56(84) bytes of data.
```

**Additional context**

Tried to set ``local_addresses`` in the bing engine but it doesn't helped / it seems it has no effect

```yaml

engines:

  - name: bing
    local_addresses: 0.0.0.0
```

What helped is to set the `source_ips` for [`outgoing` communication](https://docs.searxng.org/admin/settings/settings_outgoing.html) to all engines (but this is not wanted / the issue is only related to bing, not to all engines).

```yaml
outgoing:
  source_ips: 0.0.0.0
```

**Technical report**

Error
  * Error: 12 redirects, maximum: 0
  * Percentage: 100
  * Parameters: `('200', 'OK', 'www.bing.com')`
  * File name: `searx/search/processors/online.py:126`
  * Function: `_send_http_request`
  * Code: `count_error(`

**Comment by ahmad-alkadri** [comment]
Hello @return42 

> curl --ipv4  'https://www.bing.com' works but when I use curl -L 'https://www.bing.com' its an endless redirect from https://www.bing.com/ to https://cn.bing.com/ and back.

Did you try that on the server's terminal? 

This bug seems oddly familiar; I think it used to be related in some way to cookie problems in Chrome, but I guess for you the problem is at the server's level?

**Comment by return42** [comment]
Yes is at server.

**Comment by 9Ninety** [comment]
The redirect behavior could be happen when Bing think you (or your IPv6 address) are located in China.

Google previously has similar behavior, if there are a lot of search being made with location in keywords, for example: "shop near somewhere in Beijing", the IP address will be marked as located in China and redirect from `google.com` to `google.com.hk`.

I haven't find any link to report IP address issue on Bing or Microsoft website, but contact them with your IP address might help.

**Comment by return42** [comment]
>  "shop near somewhere in Beijing", the IP address will be marked as located in China 

@9Ninety: seems you are right, ~I never thought that a DNS routing is based on a search term used in the application layer .. crazy .. but why not, microsoft is known for piercing layers :facepalm:~ .. and spontaneous self-healing forces have also fixed the problem in the meantime :-)

**Comment by 9Ninety** [comment]
@return42 No, it's application layer 302 redirect, not DNS based:
```
< HTTP/2 302
< cache-control: private
< content-length: 137
< content-type: text/html; charset=utf-8
< location: https://cn.bing.com/
```

They just deployed IP based redirect code on all of their server, to prevent users from China access uncensored search result.

**Comment by return42** [comment]
> to prevent users from China access uncensored search result.

Oh, "censored" that's where motivation comes from .. I hadn't thought of that at all. Thanks for the clarification :+1:
