### ISSUE TITLE
Pagination numbers appear vertically

### ISSUE THREAD

**Issue by ryankask** [searxng/searxng#2194]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
295c87a9

**How did you install SearXNG?**
Docker

**What happened?**
The page numbers at the bottom of the page appear vertically.

**How To Reproduce**

HTTP method is set to POST.

**Expected behavior**

The pages should appear horizontally.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/81891/219026014-f5a148df-ee24-40a4-88be-0530418a3b98.png)

**Additional context**

**Comment by return42** [comment]
Looks very strange .. is your instance public, where I can test it?

**Comment by ryankask** [comment]
Please disregard. I cleared the cache and it worked correctly.
