### ISSUE TITLE
Fewer and bad results compared to normal googling 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [searxng/searxng#2206]
Hi there :wave: ,

Thanks for the amazing project :) Since some time ago (3 months), I am experienced terrible search results. (see screenshot)

only `wikipedia` and `google` are on in my `config/engine`

![image](https://user-images.githubusercontent.com/15908060/219952150-dc6fe08d-d9fc-43a8-a1da-3550e718c1c3.png)

**Comment by g-plex** [comment]
If you search Google with English as your selected language, you get the same results as SearXNG in your screenshot.  If you change SearXNG to Italian, you will get the results from your Google screenshot.

Just make sure you select the same language for both SearXNG and Google.

**Comment by return42** [comment]
> Just make sure you select the same language for both SearXNG and Google.

.. and we are working to improve the language & region handling .. see my comment here:

- https://github.com/searxng/searxng/issues/1966#issuecomment-1441308635

I am going to close this issue.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @return42 , thanks a lot for the reply

It's not true - I've set google (on the right) to unitest states as well 

![image](https://user-images.githubusercontent.com/15908060/221415731-d52158ee-bf02-4948-b32a-9ace21ad26a8.png)

Results from searxng are just ridiculous - like a result from `[https://www.france24.com](https://www.france24.com/en/europe/20220823-they-would-have-preferred-hell-the-battle-of-stalingrad-80-years-on)`?

I'm not sure how searing is getting its results, but not in the same way that google gets them (assuming I am doing everything correctly). This is the setting from google I've set to United States

![image](https://user-images.githubusercontent.com/15908060/221415828-d1cf5ae2-0ab4-45e7-ab6b-129e7128da43.png)
