### ISSUE TITLE
searx Logo

### ISSUE THREAD

**Issue by vitaprimo** [searxng/searxng#2229]
I made a logo for searx years ago and [I even forked the project so I could try to contribute](https://github.com/vitaprimo/searx), but since it's not code I thought it would be reject and I really didn't want to be rejected so I decided against it in the end — _also, I'm a little iffy on git, still, a by a "little iffy" I mean completely ignorant._

I wouldn't want for it to go to waste if you find it usable. :)

![image](https://user-images.githubusercontent.com/18566096/222431510-e07005f7-41c2-45e1-930a-2798bcb3f8ff.png)

More colors, favicons and the original files are on [this post.](https://senseivita.com/index.php/2023/01/09/searx-instance-logo-refresh/). I'd be happy to update them for the newer searx if you want, too :) …y'know, the NG.

-----

> _Thanks for sharing searx though, it's the only thing that can bypass my firewall for image search these days with soo much tracking going on, so I'm abusing that little instance, well, the remaining search engines that haven't blocked it. 🤓_

**Comment by LinuxinaBit** [comment]
Something like this for a dark theme could work well:
![151A7C27-8F7C-4166-9CD2-DAAC5AFAF594](https://user-images.githubusercontent.com/105567407/222484797-95145cca-f09b-4d81-b1bf-a6863eeea798.png)
Keep in mind this is SearXNG, not the upstream project. The main SearX project is here: https://github.com/searx/searx
