### ISSUE TITLE
Bug: wikipedia engine

### ISSUE THREAD

**Issue by jpx40** [searxng/searxng#2233]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.3.2+abd2d860

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by Solirs** [comment]
Please fill in the form in the message (i.e How did you install searxng, what happened, etc.)
Otherwise we cant know what the bug is, what could be causing it, and how to reproduce it.

**Comment by return42** [comment]
Closed due lack of feedback.
