### ISSUE TITLE
Bug: invidious engine

### ISSUE THREAD

**Issue by jameibumblebee** [searxng/searxng#224]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 10
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:99`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Checker
  * paging: `thumbnail URL is invalid`,
  

I was using searx.be instance

**Comment by return42** [comment]
Unfortunately the engine is not named in the error section, @emayljames do you remember from which engine https://searx.be/stats the error comes from?

**Comment by unixfox** [comment]
@return42 you can safely close this issue. It was due to a misconfiguration.
