### ISSUE TITLE
Public Usecase

### ISSUE THREAD

**Issue by bijsven** [searxng/searxng#2249]
**How did you install SearXNG?**
searxng-docker

**about**
Hi, is there a way to change the logo and disable editing the settings?

**Comment by Solirs** [comment]
Both of those features are unsupported for now.
You can change the logo by replacing facivon.svg and favicon.png in searx/static/themes/simple/img (/usr/local/searxng/searx/static/themes/simple/img in docker). Make sure to comment the static-map line in your uwsgi.ini as searxng handles that already and it causes issues with this. You might also need to hard refresh your searxng window to see the change. I'll probably PR a way to change icons via settings.yml in the future.

For disabling editing the settings, i'm pretty sure there is no way to do that without changing the source code.

**Comment by unixfox** [comment]
changing the logo is not supported
