### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by InabaKumori** [searxng/searxng#2251]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.3.2+abd2d860

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by ahmad-alkadri** [comment]
Duplicate #2246
