### ISSUE TITLE
[Feature request] Add description in Wikidata results

### ISSUE THREAD

**Issue by ngosang** [searxng/searxng#2254]
**Is your feature request related to a problem? Please describe.**
The results from Wikidata always have empty description
![image](https://user-images.githubusercontent.com/10577978/225126751-f65c1739-45b1-4643-90f7-5ed1d13059d8.png)

**Describe the solution you'd like**
Get the description from the Wikidata page, make sure you get the description from the right language (english and spanish)
https://www.wikidata.org/wiki/Q251

![image](https://user-images.githubusercontent.com/10577978/225126124-a960ecec-9239-448f-bbf7-dc1cc38bea26.png)

**Comment by Solirs** [comment]
Quickly implemented this on my fork and it looks good, i'll PR it and see what is thought.
