### ISSUE TITLE
[Feature request] Distinguish official page in Wikidata results 

### ISSUE THREAD

**Issue by ngosang** [searxng/searxng#2255]
**Is your feature request related to a problem? Please describe.**
There are 3 results. It could be helpful to show in the description if it's the official web link or Wikipedia article. Related to this issue => #2254
![image](https://user-images.githubusercontent.com/10577978/225127286-d64583e3-301c-48ca-9dbc-87264fc22114.png)

**Describe the solution you'd like**

https://www.wikidata.org/wiki/Q251
Show "Official website" in the description together with the Wikidata description.
![image](https://user-images.githubusercontent.com/10577978/225127777-409f7e78-5aa8-48c6-9194-3580d7bb0297.png)
![image](https://user-images.githubusercontent.com/10577978/225128050-0ae7513d-b189-422b-b1af-5c0fceafe47c.png)

**Comment by return42** [comment]
closed by #2272
