### ISSUE TITLE
Search leading to Internal Error

### ISSUE THREAD

**Issue by keithdanielll** [searxng/searxng#2256]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
<!-- If you are running on master branch using git execute this command
in order to fetch the latest commit ID:
```
2023.3.2+abd2d860

**How To Reproduce**
<!-- How can we reproduce this issue? (as minimally and as precisely as possible) -->
Take any of the top rated public instances and insert this search:
`WARNING: /plugins/Live/VisitorProfile.php(24): Deprecated - Creation of dynamic property Piwik\Plugins\Live\VisitorProfile::$idSite is deprecated - Matomo 4.13.3 `

... will result in "internal server error"

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Some search result, or masking of "forbidden" characters

**Comment by keithdanielll** [comment]
[Seems to be related](https://github.com/searxng/searxng/issues/2250)

**Comment by Solirs** [comment]
I found a way to patch this by running re.escape() on the query inside of the problematic function call.
`content = re.sub(regex_highlight_cjk(q), f'<span class="highlight">{re.escape(q)}</span>', content)`
It fixes it for both your issue and the other one so i'll PR it.
