### ISSUE TITLE
Linux Viruses

### ISSUE THREAD

**Issue by linuxnoodle** [searxng/searxng#2259]
I want to download Linux viruses on my Linux laptop for my Linux friend. How do I download a Linux virus on a Linux laptop for my Linux friend? I will do anything to be able to download a Linux virus on a Linux laptop for my Linux friend. Please, can anyone help me download a Linux virus on my Linux laptop for my Linux friend? Tell me what kind of Linux viruses I can download on my Linux laptop for my Linux friend. It would be very much appreciated if you helped me download a Linux virus on my Linux laptop for my Linux friend. I am making this request on the Linux laptop that my Linux friend uses to do Linux stuff. This is a serious request. Respond ASAP to help me download a Linux virus on my Linux friend's Linux laptop ASAP.

With love in my Linux heart,
Linus Sex Tips

**Comment by linuxnoodle** [comment]
I apologize for this comment, my friend had access to my laptop and posted an issue without my knowledge.

**Comment by keithdanielll** [comment]
> I apologize for this comment, my friend had access to my laptop and posted an issue without my knowledge.

Has your friend been punished accordingly?
