### ISSUE TITLE
Add Option to Supress Inaccessible Engine Warning

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2261]
**Is your feature request related to a problem? Please describe.**
It is annoying (especially in single column) to see a large red box of the engines that didn't work. The information can be useful, but an option to disable or move that information to a footer would be nice (especially if you use a lot of engines, especially small ones like marginalia or wiby).

**Describe the solution you'd like**
a toggleable option in preferences to hide these warnings, or enable a less intrusive piece of 

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by return42** [comment]
Closed by: https://github.com/searxng/searxng/pull/2370
