### ISSUE TITLE
No Run Up !

### ISSUE THREAD

**Issue by adim-att** [searxng/searxng#2263]
Nothing shows up after running `python searx/webapp.py`
It says:

`123Serving Flask app 'webapp'`
`Debug mode: off`

I check the main **address**, I get *apache*'s empty directory. I check the ports which I changed to **8889**, and I see an error of `Unable to connect`

When running **debug**, I get this :

`12345_SEARXNG\_URL : http://vps.ushby.org/searxng`
`SEARXNG\_PORT:8888`
`SEARXNG\_BIND\_ADDRESS : 127.0.0.1`
`uWSGI socket is located at: /usr/local/searxng/run/socket`
`got 308 from : http://vps.ushby.org/searxng_`

Also, if try to put the port **8889** on Listen, in *ports.conf*, of *apache2*.. I can't run the `webapp.py`, it says : `port is being taken`. So I am stuck with that one!

I don't get it, what is the  issue ? As well, I read on freeBSD, that you should do **Binding** in *apache2* configuration, but I don't get it ? Any syntax for that one ?

After I stopped *apache2* from *systemctl*, it ran but with different output, saying it's :

`12WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.`
 `* Running on http://127.0.0.1:8889`

Still I can't connect to the instance.

When I tried *nginx*.. it told me :
`ERROR: Public service at http://vps.ushby.org/searxng is not available!`

Thank you !

**Comment by return42** [comment]
> Nothing shows up after running `python searx/webapp.py`
> ..
> Also, if try to put the port **8889** on Listen, in *ports.conf*, of *apache2*
> ..
> When I tried *nginx*.. it told me :

Consult [installation instructions](https://docs.searxng.org/admin/installation.html).

Its not a bug of SearXNG, going to close this issue.
