### ISSUE TITLE
settings.yml: remove locales setting

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#228]
This issue suggest to remove this part of settings.yml:
https://github.com/searxng/searxng/blob/ed0db4d61a2e0dae4953eb813604e2d8834868bb/searx/settings.yml#L1659-L1704

it is possible to:
* scan the existing language codes (scan the directory `searx/translations`, most probably Babel has a feature to do that too)
* rely on Babel to get the native and English names:
  * `babel.Locale.parse(f'{language_code}').display_name`
  * `babel.Locale.parse(f'{language_code}').english_name`

ping @MarcAbonce

**Comment by MarcAbonce** [comment]
> scan the existing language codes (scan the directory searx/translations, most probably Babel has a feature to do that too)

Flask-Babel has a [list_translations](https://flask-babel.tkte.ch/index.html#flask_babel.Babel.list_translations) method in its Babel class, but it will break with our Occitan translation.

> rely on Babel to get the native and English names: 

I agree. I think we're currently using some inconsistent names for the languages, but I don't know enough about each language to really tell for sure.
In fact this reminded me that "Tibetian" is actually a misspelling and I forgot to ever open an issue for that.

**Comment by dalf** [comment]
The list:

| code | name                           | settings.yml                   |
|------|--------------------------------|--------------------------------|
| oc | Lenga D'òc (Occitan)           | Lenga D'òc (Occitan)           |
| zh_CN | 中文 (Chinese)                   | 中文 (Chinese)                   |
| zh_TW | 國語 (Taiwanese Mandarin)        | 國語 (Taiwanese Mandarin)        |
| ar | العربية (Arabic)               | العَرَبِيَّة (Arabic)          |
| bg | Български (Bulgarian)          | Български (Bulgarian)          |
| bo | བོད་སྐད་ (Tibetan)             | བོད་སྐད་ (Tibetian)            |
| ca | Català (Catalan)               | Català (Catalan)               |
| cs | Čeština (Czech)                | Čeština (Czech)                |
| cy | Cymraeg (Welsh)                | Cymraeg (Welsh)                |
| da | Dansk (Danish)                 | Dansk (Danish)                 |
| de | Deutsch (German)               | Deutsch (German)               |
| el_GR | Ελληνικά (ελλάδα)              | Ελληνικά (Greek_Greece)        |
| en | English                        | English                        |
| eo | Esperanto                      | Esperanto (Esperanto)          |
| es | Español (Spanish)              | Español (Spanish)              |
| et | Eesti (Estonian)               | Eesti (Estonian)               |
| eu | Euskara (Basque)               | Euskara (Basque)               |
| fa_IR | فارسی (ایران)                  | (fārsī) فارسى (Persian)        |
| fi | Suomi (Finnish)                | Suomi (Finnish)                |
| fil | Filipino                       | Wikang Filipino (Filipino)     |
| fr | Français (French)              | Français (French)              |
| gl | Galego (Galician)              | Galego (Galician)              |
| he | עברית (Hebrew)                 | עברית (Hebrew)                 |
| hr | Hrvatski (Croatian)            | Hrvatski (Croatian)            |
| hu | Magyar (Hungarian)             | Magyar (Hungarian)             |
| ia | Interlingua                    | Interlingua (Interlingua)      |
| it | Italiano (Italian)             | Italiano (Italian)             |
| ja | 日本語 (Japanese)                 | 日本語 (Japanese)                 |
| lt | Lietuvių (Lithuanian)          | Lietuvių (Lithuanian)          |
| nl | Nederlands (Dutch)             | Nederlands (Dutch)             |
| nl_BE | Nederlands (belgië)            | Vlaams (Dutch_Belgium)         |
| pl | Polski (Polish)                | Polski (Polish)                |
| pt | Português (Portuguese)         | Português (Portuguese)         |
| pt_BR | Português (brasil)             | Português (Portuguese_Brazil)  |
| ro | Română (Romanian)              | Română (Romanian)              |
| ru | Русский (Russian)              | Русский (Russian)              |
| sk | Slovenčina (Slovak)            | Slovenčina (Slovak)            |
| sl | Slovenščina (Slovenian)        | Slovenski (Slovene)            |
| sr | Српски (Serbian)               | српски (Serbian)               |
| sv | Svenska (Swedish)              | Svenska (Swedish)              |
| ta | தமிழ் (Tamil)                  | தமிழ் (Tamil)                  |
| te | తెలుగు (Telugu)                | తెలుగు (telugu)                |
| tr | Türkçe (Turkish)               | Türkçe (Turkish)               |
| uk | Українська (Ukrainian)         | українська мова (Ukrainian)    |
| vi | Tiếng việt (Vietnamese)        | tiếng việt (Vietnamese)        |

using
```python
import os

from babel import Locale
from . import settings


LOCALE_NAMES = {
    "oc": "Lenga D'òc (Occitan)",
    "zh_CN": "中文 (Chinese)",
    "zh_TW": "國語 (Taiwanese Mandarin)",
}


def _get_locale_name(locale):
    locale = Locale.parse(locale)
    display_name = locale.display_name.capitalize()
    english_name = locale.english_name.capitalize()
    if '(' not in display_name and '(' not in english_name and display_name != english_name:
        return display_name + ' (' + english_name + ')'
    return display_name


def initialize_locales(directory):
    global LOCALE_NAMES
    for dirname in sorted(os.listdir(directory)):
        """Based on https://flask-babel.tkte.ch/_modules/flask_babel.html#Babel.list_translations"""
        locale_dir = os.path.join(directory, dirname, 'LC_MESSAGES')
        if not os.path.isdir(locale_dir):
            continue
        info = LOCALE_NAMES.get(dirname)
        if not info:
            LOCALE_NAMES[dirname] = _get_locale_name(dirname)


if __name__ == "__main__":
    initialize_locales(os.path.join(os.path.dirname(__file__), 'translations'))
    print(f"| code | {'name':30} | {'settings.yml':30} |")
    print('|------|--------------------------------|--------------------------------|')
    for code, name in LOCALE_NAMES.items():
        settings_code = code if code != 'zh_CN' else 'zh'
        print(f"| {code} | {name:30} | {settings['locales'][settings_code]:30} |")
```

In settings.yml, the language name is `native name ( english name )`.
In Babel, the native name and english name can contain parenthesis:

| Native name         | English name                  |
|---------------------|-------------------------------|
|  Ελληνικά (ελλάδα)  |         Greek (greece)        |
| فارسی (ایران)       | Persian (iran)                |
| Nederlands (belgië) | Dutch (belgium)               |
| Português (brasil)  | Portuguese (brazil)           |
| 中文 (简体, 中国)   | Chinese (simplified, china)   |
| 中文 (繁體, 台灣)   | Chinese (traditional, taiwan) |

The code above keep `native name ( english name )` except when there are parenthesis in the native name.
Two exceptions to this rule: `zh_CN` and `zh_TW`.
Perhaps it is confusing?

**Comment by return42** [comment]
> Two exceptions to this rule: zh_CN and zh_TW.

```python
>>> from babel import Locale
>>> zh_CN = Locale.parse('zh_CN')
>>> zh_TW = Locale.parse('zh_TW')
>>> zh_CN.english_name
'Chinese (Simplified, China)'
>>> zh_TW.english_name
'Chinese (Traditional, Taiwan)'
>>> 
```

... strange; I thought zh_CN is the old name for *traditional* (aka `zh_Hant_CN`)

```
>>> Locale.parse('zh_Hant_CN').english_name
'Chinese (Simplified, China)'
>>> Locale.parse('zh_Hans_CN').english_name
'Chinese (Simplified, China)'
```
... strange babel says `zh_Hant_CN` is _(Simplified, China)_

```
Locale.parse('zh_Hant_TW').english_name
'Chinese (Traditional, Taiwan)'
>>> Locale.parse('zh_Hans_TW').english_name
Traceback (most recent call last):
...
babel.core.UnknownLocaleError: unknown locale 'zh_Hans_TW'
```
... `zh_Hans_TW` does not exists in babel (but exists in the [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry))

Could it be that babel has some issues .. or do I miss something?

**Comment by dalf** [comment]
AFIK:
* mainland China (CN) uses simplified Chinese: https://en.wikipedia.org/wiki/Simplified_Chinese_characters#Mainland_China
* Taiwan uses traditional Chinese

I don't think zh_Hant_CN or zh_Hans_TW will be useful as translation here.

**Comment by return42** [comment]
@dalf it seems you are right / [in practice, `zh-CN` and `zh-SG` are subsets of `zh-Hans`; `zh-TW` and `zh-HK` are subset of zh-Hant](https://github.com/mozilla/addons/issues/4515)
