### ISSUE TITLE
Brave powered by Chrome browser- Suspended: too many requests

### ISSUE THREAD

**Issue by JourneysFutpath** [searxng/searxng#2284]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

The [Chrome Web Store](https://chrome.google.com/webstore/detail/bing-search-automator/lgihmoefhpfdigbbgfmiblfbdblpjpig) says the version is 1.9 & was last updated 12/29/2022 the size is 20.29 KiB:
![image](https://user-images.githubusercontent.com/124089707/227719088-9f0ac0d8-c020-48b0-832a-ad64fb92e5e1.png)

However, when I click "[Suspended: too many requests](https://search.mdosch.de/stats?engine=google)" link here: 
![image](https://user-images.githubusercontent.com/124089707/227717240-96b33ef4-7c3d-4c3c-9483-3c195bfa6711.png)

It takes me to this screen:
![image](https://user-images.githubusercontent.com/124089707/227716722-bf92f796-c7a7-425d-96dc-df67fbbd2b9a.png)

with this alternate information at the bottom:
![image](https://user-images.githubusercontent.com/124089707/227717776-31b99df7-f184-4ff1-856c-4948f34f5192.png)

When I follow the [Source Code](https://github.com/searxng/searxng) link it takes me to the master branch:
![image](https://user-images.githubusercontent.com/124089707/227717926-4a28e4b8-0c83-491a-a6fc-8c4905c04587.png)

**How did you install SearXNG?**

I got this thing from the [Chrome Web Store](https://chrome.google.com/webstore/detail/bing-search-automator/lgihmoefhpfdigbbgfmiblfbdblpjpig)
 
**What happened?**

After a couple of searches the browser started throwing up this red beast 
![image](https://user-images.githubusercontent.com/124089707/227718009-a4efcdb6-a822-44f3-ad91-6d6f41a6aca8.png)
on the final load- I was given this [Search URL](https://search.mdosch.de/search?q=represcribed&language=en-US&time_range=&safesearch=0&categories=general)

and the option to download this Json file: 
[searchxngjson.txt](https://github.com/searxng/searxng/files/11068933/searchxngjson.txt)

In addition to the above documentation- none of the searches collected the Bing rewards

**How To Reproduce**
Download from chrome web store > click extension puzzle on top right of browser > click the extension "Bing Search Automator > Click "Perform 60 Bing Searches"- *Note: Bing only rewards for 50 searches*

**Expected behavior**
Expected the extension/script to perform as advertised- perform a succession of 50/60 Bing browser searches & collect the maximum daily allotment of points on my Microsoft Rewards account.

**Screenshots & Logs**

I think I provided all the pertinent information & screenshots above. This is my first time reporting a bug on here so I hope I didn't mess anything up!!!

**Comment by return42** [comment]
> Download from chrome web store > click extension puzzle on top right of browser > click the extension "Bing Search Automator > Click "Perform 60 Bing Searches"- Note: Bing only rewards for 50 searches

> Expected the extension/script to perform as advertised- perform a succession of 50/60 Bing browser searches & collect the maximum daily allotment of points on my Microsoft Rewards account.

Not sure what you want  .. but this is the SearXNG project / we are not responsible for Chrome, Brave or whatever browser extension.

**Comment by JourneysFutpath** [comment]
> > Download from chrome web store > click extension puzzle on top right of browser > click the extension "Bing Search Automator > Click "Perform 60 Bing Searches"- Note: Bing only rewards for 50 searches
> 
> > Expected the extension/script to perform as advertised- perform a succession of 50/60 Bing browser searches & collect the maximum daily allotment of points on my Microsoft Rewards account.
> 
> Not sure what you want .. but this is the SearXNG project / we are not responsible for Chrome, Brave or whatever browser extension.

I apologize- as a newb to this all- I was under the impression that the extension made available on Chrome is this project because the link provided to report an issue lead me here.

**Comment by return42** [comment]
> impression that the extension made available on Chrome is this project because the link provided to report an issue lead me here.

May I misunderstand .. can you link to the page that directs you here / thanks!
