### ISSUE TITLE
Bug: openstreetmap engine

### ISSUE THREAD

**Issue by Serhat17** [searxng/searxng#2285]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.3.24+64fea2f9+dirty

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 100
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:114`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
What SearXNG instance did you used?

**Comment by return42** [comment]
Closed due lack of feedback.
