### ISSUE TITLE
Implement a python module for https://search.brave.com/

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2294]
We have a XPath implementation of the brave engine (see below).  In the past, however, we found that there were always problems with the XPath implementation, and brave also offers more possibilities than we can realize with an XPath implementation.

In the long run we should implement a Python module for https://search.brave.com/ that is more robust and also supports safe-search and localization.

- https://github.com/searxng/searxng/issues/2020
- https://github.com/searxng/searxng/pull/2178#issuecomment-1426650913
- https://github.com/searxng/searxng/issues/392#issuecomment-938085057

----

https://github.com/searxng/searxng/blob/007bc7322723fd8bf1db50820638528a51f6120d/searx/settings.yml#L1827-L1853

----

Related:

- [`!brave !g something` returns no result](https://github.com/searxng/searxng/issues/392#issuecomment-938085057)
- https://github.com/searxng/searxng/issues/1651#issuecomment-1503277191
- https://github.com/searxng/searxng/issues/2590

**Comment by return42** [comment]
implemented by 

- https://github.com/searxng/searxng/pull/2599

**Comment by RaptaG** [comment]
Brave appears to remain broken #2616

**Comment by return42** [comment]
@RaptaG I know, please lets continue in your issue https://github.com/searxng/searxng/issues/2616
