### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by dragooji** [searxng/searxng#2307]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.3.31+901ccce6

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
To reopen please fill out the form .. whats your public URL?

---

BTW: `Percentage: 5` .. I think you can safely ignore this error rate.
