### ISSUE TITLE
Error in translation license

### ISSUE THREAD

**Issue by comradekingu** [searxng/searxng#231]
https://weblate.bubu1.eu/projects/searxng/searxng/#information says "GPLv3-only", whereas
many files in the source code repo are "or any later version"
https://github.com/searxng/searxng/blob/6c0114567e7ba1b3f4a54327eddf658b7474ca58/searx/version.py#L6

Ostensibly that means (?) current translations are also GPLv3+.
In any event, going or-later for everything causes fewer problems in that it is compatible, and has the most flexibility down the road.

**Comment by dalf** [comment]
Updated.

**Comment by return42** [comment]
I close this issue / ask for reopen this issue if you think the issue is not solved serious.

**Comment by comradekingu** [comment]
AGPLv3+ makes a lot more sense with the network protections. Good choice :)

**Comment by return42** [comment]
FYI: https://github.com/searxng/searxng/blob/master/LICENSE
