### ISSUE TITLE
./manage : call to the delete file searxng_extra/update/update_languages.py

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#2314]
https://github.com/searxng/searxng/blob/3ab85db5ddd12e1d17dab7d72ea8a7cb7ca961b5/manage#L403-L412

* The function name should be `data.traits()`
* The script to call is `searxng_extra/update/update_engine_traits.py`

Related to https://github.com/searxng/searxng/pull/2269

**Comment by return42** [comment]
@dalf thanks for pointing out, this brings me to the next issue

- https://github.com/searxng/searxng/pull/2316

----

We can close this issue (#2314) when #2316 is merged.

**Comment by return42** [comment]
Finally closed by https://github.com/searxng/searxng/pull/2316
