### ISSUE TITLE
Wikipedia engine: misusage of zh-classical.wikipedia.org

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#2330]
See https://en.wikipedia.org/wiki/Chinese_Wikipedia

> To avoid this near-[forking](https://en.wikipedia.org/wiki/Fork_(software_development)) of the project, starting around January 2005, the Chinese Wikipedia began providing a [server](https://en.wikipedia.org/wiki/Server_(computing))-side mechanism to automatically convert different characters and vocabulary items into the user's local ones, according to the user's preference settings, which may be set to one of two settings that convert the script only, or one of six settings that also take into account regional vocabulary differences:

> Finally, requests were also made, and granted, to create a Classical Chinese Wikipedia ([zh-classical:](https://zh-classical.wikipedia.org/wiki/)), based on [Classical Chinese](https://en.wikipedia.org/wiki/Classical_Chinese), an archaic register of Chinese with grammar and vocabulary drawn from [classical works](https://en.wikipedia.org/wiki/Chinese_literature) and used in all official contexts until the early 20th century, when it was displaced by the Vernacular Chinese standard.

* Traditional Chinese reader most probably don't won't the content from zh-classical.wikipedia.org (we can create an engine for that).
* The HTTP header `Accept-Language` must be set accordingly.

The initial code was:
https://github.com/searxng/searxng/blob/3d96a9839a12649874b6d4cf9466bd3616b0a03c/searx/engines/wikipedia.py#L25-L45

With https://github.com/searxng/searxng/pull/1560 the condition in wikipedia.py has been removed.

With https://github.com/searxng/searxng/pull/2269 , I'm not sure about the header value, however 
https://github.com/searxng/searxng/blob/fed2bab65b7830a38052b7f592684a19de16b746/searx/data/engine_traits.json#L3598
is not what the user expect.

**Comment by return42** [comment]
> Wikipedia engine: misusage of zh-classical.wikipedia.org

Not sure I fully understand where you see a issue:

> - The HTTP header `Accept-Language` must be set accordingly.

When a users selects locale zh-TW, with ..

https://github.com/searxng/searxng/blob/fed2bab65b7830a38052b7f592684a19de16b746/searx/engines/wikipedia.py#L35

the zh-TW is used in the HTTP `Accept-Language` header send in the request.  Same with zh-CN and zh-HK

> - Traditional Chinese reader most probably don't won't the content from zh-classical.wikipedia.org (we can create an engine for that).

> 
> With https://github.com/searxng/searxng/pull/2269 , I'm not sure about the header value, however 
> https://github.com/searxng/searxng/blob/fed2bab65b7830a38052b7f592684a19de16b746/searx/data/engine_traits.json#L3598
> is not what the user expect.

When a users selects locale zh-TW (Traditional Chinese)

- the search [`!wikipedia 日 :zh-TW`](https://darmarit.org/searx/search?q=%21wikipedia+%E6%97%A5+%3Azh-TW) links to the article from--> https://zh-classical.wikipedia.org
- and  [`!wikipedia 日 :zh`](https://darmarit.org/searx/search?q=%21wikipedia+%E6%97%A5+%3Azh) links to the article from --> https://zh.wikipedia.org

.. do I oversee something or do I not understand the intention of this issue?

**Comment by dalf** [comment]
For the SearXNG locale `zh-TW`:
* The HTTP header `Accept-Language` should be `zh-tw` in lower case. I don't know if it works with `zh-TW`.
* the URL should be `zh.wikipedia.org` <-- currently this is `zh-classical.wikipedia.org`.

Some examples: 
* if the user searches for `!wp :zh-cn 臺北市`, the result should be `https://zh.wikipedia.org/wiki/臺北市`. 
* if the user searches for `!wp :zh-tw 臺北市`,the result should be the same : `https://zh.wikipedia.org/wiki/臺北市` not `https://zh-classical.wikipedia.org/wiki/臺北市` as it is the case now.

Said differently:
* `zh-classical`  is dedicate to [classical Chinese](https://en.wikipedia.org/wiki/Classical_Chinese) which is not [traditional Chinese](https://en.wikipedia.org/wiki/Traditional_Chinese_characters).
* zh.wikipedia.org is going to dynamically show simplified or traditional Chinese according to the `Accept-Language` header.

Disclaimer: I don't read Chinese, I base my reasoning on the previous implementation and on @MarcAbonce 's PR (see https://github.com/searx/searx/pull/2554).

**Comment by return42** [comment]
> Said differently:
>
> * `zh-classical`  is dedicate to classical Chinese which is not traditional Chinese

Oops, I made complete wrong assumptions about that.  Thanks for clarify, the link to https://github.com/searx/searx/pull/2554 was also very helpfull ..

> * zh.wikipedia.org is going to dynamically show simplified or traditional Chinese according to the `Accept-Language` header.

This seems true for the HTML query (but not for JSON API):

  - https://zh.wikipedia.org/wiki/%E5%87%BA%E7%A7%9F%E8%BB%8A

I implemented a WIP commit on top for that.

But now --  when `Accept-Language` is set correct -- I realize that the JSON API don't care about that header:

- https://zh.wikipedia.org/api/rest_v1/page/summary/%E5%87%BA%E7%A7%9F%E8%BB%8A

  You can test it here: https://reqbin.com/gesg2kvx

I will continue with my WIP commit the next days ...

**Comment by dalf** [comment]
The OpenAPI documentation says the `Accept-Language` header works also on the REST API:
https://zh.wikipedia.org/api/rest_v1/#/Page%20content/get_page_summary__title_

On https://reqbin.com/gesg2kvx the extract is different if the HTTP header is `zh-cn` rather than `zh-hk`.

https://www.chineseconverter.com/en/convert/find-out-if-simplified-or-traditional-chinese says the wikipedia REST API returns traditional Chinese with `zh-hk`, and simplified Chinese with `zh-cn`.

Note: As far I remember (I might be wrong) : see the third characters. `車` is traditional Chinese, `车` is simplified Chinese.

**Comment by return42** [comment]
> On https://reqbin.com/gesg2kvx the extract is different if the HTTP header is `zh-cn` rather than `zh-hk`.

Hm, now I see .. only the *displaytitle* field changed ..

![grafik](https://user-images.githubusercontent.com/554536/230942891-50c1d92f-cd25-4662-bfea-cde6562f935e.png)

![grafik](https://user-images.githubusercontent.com/554536/230943111-6e88145b-d7b0-4ced-b5c1-ddb5261e4507.png)

> Note: As far I remember (I might be wrong) : see the third characters. `車` is traditional Chinese, `车` is simplified Chinese.

FYI: from https://github.com/searx/searx/pull/2554 I copied:

- ``!wp 出租車 :zh``    中文 should show 出租車
- ``!wp 出租車 :zh-CN`` 中文 (中国) should show 出租车
- ``!wp 出租車 :zh-TW`` 中文 (台灣) should show 計程車
- ``!wp 出租車 :zh-HK`` should show 的士
- ``!wp 出租車 :zh-SG`` should show 德士

..  in the engine we use `title` .. fcfcf66 .. I think this is the issue :-)

----

> The OpenAPI documentation says the `Accept-Language` header works also on the REST API:
https://zh.wikipedia.org/api/rest_v1/#/Page%20content/get_page_summary__title_

I can't find a hint about `Accept-Language` header in the linked API .. can you point me closer (or a screenshot .. may I oversee it).

**Comment by dalf** [comment]
The  `wikipedia` engine uses also:
* [`description`](https://github.com/searxng/searxng/blob/007bc7322723fd8bf1db50820638528a51f6120d/searx/engines/wikipedia.py#L98)
* [`extract`](https://github.com/searxng/searxng/blob/007bc7322723fd8bf1db50820638528a51f6120d/searx/engines/wikipedia.py#L105)

The script to update the descriptions uses the `extract` field.

> Hm, now I see .. only the displaytitle field changed ..

All the fields are affected. Look at the `extract` field (at the end of the response):

The third character is `车` (simplified Chinese):
![image](https://user-images.githubusercontent.com/1594191/230950279-ab8145c2-a0ec-43f4-804f-32f24ba671fd.png)

The third character is `車` (traditional Chinese):
![image](https://user-images.githubusercontent.com/1594191/230950351-062001d3-cd0c-4604-9088-22f874c009bd.png)


> I can't find a hint about Accept-Language header in the linked API .. can you point me closer (or a screenshot .. may I oversee it).

![image](https://user-images.githubusercontent.com/1594191/230950011-0a91c8f1-7072-491f-b3c2-129e9588c5e7.png)

**Comment by return42** [comment]
@dalf I have now fixed the wikipedia engine. Thank a lot for your support, without I would not have been able to do this. In the [documentation](https://docs.searxng.org/src/searx.engines.wikipedia.html#module-searx.engines.wikipedia) I tried to describe how the LanguageConverter of Wikipedia works, how we use it in SearXNG.

**Comment by return42** [comment]
@MarcAbonce the bugfix of this issue is now in current master branch. Can you have a look and check that wikipeda's language variants .. work as expected? 

https://github.com/searxng/searxng/blob/5a3f99ee1a89f8a858922f50d87e20a9aeedf051/searx/engines/wikipedia.py#L112-L119

Your https://github.com/searx/searx/pull/2554 was very helpful to me / I added some words about Wikipedia's LanguageConverter to engine's [documentation](https://docs.searxng.org/src/searx.engines.wikipedia.html#module-searx.engines.wikipedia).

**Comment by MarcAbonce** [comment]
I can't read Chinese either but those test cases seem to work for me.

Nitpick: I think that [this documentation](https://github.com/searxng/searxng/blob/f950119ca87363aec81591dc4985f11371aa2b3e/searx/locales.py#L248) also needs to be updated, right?

**Comment by return42** [comment]
> Nitpick: I think that [this documentation](https://github.com/searxng/searxng/blob/f950119ca87363aec81591dc4985f11371aa2b3e/searx/locales.py#L248) also needs to be updated, right?

.. yes, its misleading here .. I fixed the example to `zh_TW` in 

- https://github.com/searxng/searxng/pull/2354

> I can't read Chinese either but those test cases seem to work for me.

Thanks a lot for having a look :+1:
