### ISSUE TITLE
[Feature request] Custom CSS without modifying static/theme files

### ISSUE THREAD

**Issue by sevmonster** [searxng/searxng#2335]
**Is your feature request related to a problem? Please describe.**
Currently, the only way I can see to inject some custom CSS is to modify the theme. Modifying in-place is not easily doable if you use the Docker image, so you must instead copy it to a folder and mount it. Either way is not particularly fun and just adds unnecessary overhead to the server administrator.

**Describe the solution you'd like**
A way to inject custom CSS without copying and modifying the theme. A config value to specify files to inject would be most welcome. Allowing for multiple `static_path` vars to override files was already discussed [in Searx](https://github.com/searx/searx/issues/1042) but seems to not have gone anywhere, that would also work though I consider it less optimal for my particular use-case.

**Describe alternatives you've considered**
Injecting into the page with Nginx `sub_filter` and mounting `custom.css` into `/usr/local/searxng/searx/static/custom.css`. I did this [on my instance](https://searx.sev.monster).
## `nginx.conf`
```nginx
location / {
    sub_filter </head> '<link rel="stylesheet" href="/static/custom.css"></head>';
    sub_filter_once on;
}
```

**Comment by return42** [comment]
The simple theme has no official interface, so it cannot be customized.  It is also not planned to provide the simple theme with interfaces for customization.

Customization of the theme requires regular maintenance and therefore only recommended in a fork (aka brand).
