### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by devmalick** [searxng/searxng#2336]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.4.10+007bc7322

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 5
  * Parameters: `('get_sc_code: got redirected to https://www.startpage.com/sp/captcha',)`
  * File name: `searx/engines/startpage.py:221`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineCaptchaException(`

**Comment by return42** [comment]
@devmalick please fill out the form .. and a link to the SearXNG instance will be helpful / we reopen the issue when the needed informations available .. thanks.
