### ISSUE TITLE
add cloudflare connecting ip to self info plugin

### ISSUE THREAD

**Issue by winneratwin** [searxng/searxng#234]
**Is your feature request related to a problem? Please describe.**

it doesn't show the correct ip behind cloudflare

**Describe the solution you'd like**

add Cf-Connecting-Ip header to the list of headers that the self info plugin uses when the query is ip

**Describe alternatives you've considered**

there is another header True-Client-IP in cloudflare enterprise plan but the Cf-Connecting-Ip header is always active

**Additional context**

none required

**Comment by unixfox** [comment]
Searx is usually run behind a reverse proxy, so you must configure your reverse proxy to forward the given client IP address by cloudflare to Searx.

In no way this is Searx fault.

**Comment by return42** [comment]
OT: Cloudflare violates privacy, hosting SearXNG on is a bad idea / https://github.com/searx/searx/issues/1965#issuecomment-632548230

Further see:

- http://crimeflare.eu.org
- https://git.nogafam.es/deCloudflare/deCloudflare/src/branch/master/subfiles/the_trouble_with_codeberg.md

**Comment by dalf** [comment]
At this line
https://github.com/searxng/searxng/blob/feef577f996b00c4b4b610b6e3a17e2183d20927/searx/plugins/self_info.py#L37
you can replace `X-Forwarded-For` by `Cf-Connecting-Ip`, it should work.

But it won't be supported in this repository for the reasons described above.
