### ISSUE TITLE
Bug: z-library engine

### ISSUE THREAD

**Issue by fabsau** [searxng/searxng#2345]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.4.15+0adfed19

**How did you install SearXNG?**
Docker

**What happened?**
Z-Library was seized and now they are back to the clearnet. The old engine is not adapted to work with the updated z-library page. Every user gets a custom domain and has to signin using their password.
I tested it with the following config:
    base_url: https://newprivatedomain.example.com/s/{query}
    password: mysecretpassword

It would be nice if searxng could update the engine. Thank you very much in advance

Edit: More info about z-library:
https://www.reddit.com/r/zlibrary/comments/zx6z62/megathread_how_to_access_zlibrary_on_tor_app

**Comment by return42** [comment]
I would give it a try, but I don't want to register .. do you have a domain & password for me /  send me an eMail markus.heiser@darmarit.de

**Comment by fabsau** [comment]
> I would give it a try, but I don't want to register .. do you have a domain & password for me / send me an eMail [markus.heiser@darmarit.de](mailto:markus.heiser@darmarit.de)

Mail sent. Thank you!

**Comment by return42** [comment]
> Mail sent. Thank you!

@fabsau thanks :-)  

.. I did a short analysis and I see few drawbacks:

1. With the login a session is opened and the session data (cookie) hast to send with each request .. this is a technical requirement that could still be managed with a few lines of code.  However, I see a disadvantage for the user that we cannot solve:

2. The Z-library links in the Searx result list would be of no use to the user: He would have to log in again at the destination address to be able to load the content. (the download request would need the same cookie) .. This problem could be solved theoretically by implementing a proxy for z-library (like for images).  But even then there would be another problem: 

3. The downloads would all go through this one account and the download rate for one account is limited.

I haven't had time to look at z-library via tor yet, I don't know if you need a login there too ... if not, then maybe we should look for a solution that goes via tor.

**Comment by fabsau** [comment]
> > Mail sent. Thank you!
> 
> @fabsau thanks :-)
> 
> .. I did a short analysis and I see few drawbacks:
> 
>     1. With the login a session is opened and the session data (cookie) hast to send with each request .. this is a technical requirement that could still be managed with a few lines of code.  However, I see a disadvantage for the user that we cannot solve:
> 
>     2. The Z-library links in the Searx result list would be of no use to the user: He would have to log in again at the destination address to be able to load the content. (the download request would need the same cookie) .. This problem could be solved theoretically by implementing a proxy for z-library (like for images).  But even then there would be another problem:
> 
>     3. The downloads would all go through this one account and the download rate for one account is limited.
> 
> 
> I haven't had time to look at z-library via tor yet, I don't know if you need a login there too ... if not, then maybe we should look for a solution that goes via tor.

Thank you for your time and analysis! When accessing via tor, you will also need a login.
I am the only user that is using the searxng instance, in that case implementing session and cookie data should be in my use case sufficient. The proxy would be optional.
But I don't know if these limitations are against the general idea of searxng are :)

**Comment by return42** [comment]
Closed by 

- #2519
