### ISSUE TITLE
Move functions from utils/lib.sh to utils/lib_install.sh

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#237]
Some functions from `utils/lib.sh` are related to the installation scripts ( utils/searx.sh, utils/morty.sh, utils/filtron.sh, utils/lxc.sh ).

To quote some, but not all:
* cache_download
* install_template
* go_is_available
* install_go
* service_account_is_available
* drop_service_account
* interactive_shell
* systemd_install_service
* systemd_remove_service
* systemd_activate_service
* systemd_deactivate_service
* systemd_restart_service
* nginx_distro_setup
* install_nginx
* nginx_is_installed
* nginx_reload
* nginx_install_app
* nginx_include_apps_enabled
* nginx_remove_app
* nginx_enable_app
* nginx_dissable_app
* apache_distro_setup
* install_apache
* apache_is_installed
* apache_reload
* apache_install_site
* apache_remove_site
* apache_enable_site
* apache_dissable_site

Would it make sense to move them to `utils/lib_install.sh` since all installation scripts have these pattern:
```sh
# shellcheck source=utils/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
# shellcheck source=utils/lib_install.sh
source "${REPO_ROOT}/utils/lib_install.sh"
```

But instead of a huge `utils/lib_install.sh` file, perhaps it makes sense to create `utils/lib_apache.sh`, `lib_nginx.sh` etc... ?

No functional change, but `utils/lib.sh` could focus one thing: a helper for `./manage` and other scripts.

**Comment by return42** [comment]
> But instead of a huge utils/lib_install.sh file, perhaps it makes sense to create utils/lib_apache.sh, lib_nginx.sh etc... ?

This is my intention :-) .. I want to modularize the lib.sh successively / I use this lib in other projects also. may be I force some changes their and bring them back here to SearXNG .. give me some time, changes will come.

**Comment by dalf** [comment]
Another method: copy required functions for `./manage` to a dedicated location.

See branch: https://github.com/dalf/searxng/tree/tiny_lib ( the content of `./manage` is split into different small files, one big file is also possible, also don't look too much at the commit history or how the functions are dispatched into `./makefile.lib`, however everything seems to work). 

[./utils/lib.sh](https://github.com/searxng/searxng/blob/master/utils/lib.sh) becomes two files:
* [makefile.lib/0_toolbox.sh](https://github.com/dalf/searxng/blob/tiny_lib/makefile.lib/0_toolbox.sh)
* [makefile.lib/1_pyenv.sh](https://github.com/dalf/searxng/blob/tiny_lib/makefile.lib/1_pyenv.sh)

In total:
* searxng/master: 2412 lines (1864 lines for ./utils/lib.sh)
* dalf/tiny_lib: 1035 lines (copy / paste 332 lines from ./utils/lib.sh)

The 332 lines are copy / paste from ./utils/lib.sh however since there is no abstraction, some implementations are simpler.

This way the install scripts and `./manage` can evolve at different speeds, and perhaps `./utils/lib.sh` will require less dedicated functions for searxng.

I understand that it creates two versions that you have to maintain and update but:
* here I can more easily contribute.
* we can customize / rewrite the functions at will

**Comment by return42** [comment]
> I understand that it creates two versions that you have to maintain and update but:
> 
> - here I can more easily contribute. 

Is it really that hard to contribute to "as is" / What do you want to change in the lib.sh? 

>
> - we can customize / rewrite the functions at will

IMO this is a library like any other lib we use from npm or pypi .. instead of a package manager it is copied from https://github.com/return42/boilerplate/tree/master/utils

I would not expect as much changes to the lib.sh, the lib does not have known issues and the SearXNG script we write is in ./manage and other files.

I would not invest to much time in the `lib.sh` here on SearXNG when I could solve that modularizing issue in other projects.

IMO we spend to much time on developer's boilerplate, so this topic has not that priority for me. I think we should prioritize  other topics like UX and engines.

**Comment by dalf** [comment]
To answer few questions here:
* Why there are two functions `pyenv` and `pyenv.install` ?
* Why `pyenv.check` and `pyenv.install` are declared in `utils/lib.sh` and `manage`?
* `utils/brand.env` ask to be commited but the git repository already provides this informations.

An example of a more simple implementation: https://github.com/dalf/searxng/tree/f3985630cbcb7cb4a172387e21569302b7a982c7/utils based on the master branch :
  * see `utils/config.sh` which gathers all the settings
  * `utils/python.sh` : 151 lines
  * `utils/lib.sh` : 114 lines.
  * everything works EXCEPT the installation scripts

My initial intent was to have the installation script in a different repository (which would solve the permission issue when the repository [clones itself from the local storage](https://github.com/searxng/searxng/blob/7592d85982d0878940b4c9d57e78e51047adf8d7/utils/searxng.sh#L453-L456)).

I close the issue, see https://github.com/searxng/searxng/pull/2121
