### ISSUE TITLE
Make run is not working

### ISSUE THREAD

**Issue by arda618** [searxng/searxng#2371]
I am on linux, I ran cd (path to my root searxng folder) on terminal and then ran "make run", it worked perfectly yesterday but it seems not to work today. I am getting this error when I run "make run" : make: *** No rule to make target 'run'. Stop.

And when I run "make" only, it says No targets specified and no makefile found. Stop. 

I have the Makefile on the right path, haven't modified it, I also have makefile.include untouched on /utils/. What's the problem here?

**Comment by return42** [comment]
> And when I run "make" only, it says No targets specified and no makefile found. Stop

then you are not in the path where the `Makefile` is, please double check:

>  I ran cd (path to my root searxng folder)
