### ISSUE TITLE
Limiting search to specific sites

### ISSUE THREAD

**Issue by arda618** [searxng/searxng#2372]
I was wondering, as a developer, how I can limit searching to specific websites of my wish and exclude the websites that are not listed there. Let's say I want images only to be from pinterest.com and tumblr.com, how will I achieve it? The only two search engines that I am using are qwant and bing images...

**Comment by return42** [comment]
You can disable search engines (by default) in your `/etc/searx/settings.yml` --> https://docs.searxng.org/admin/engines/settings.html#engine-settings see `disabled: true`.

----

BTW: if you have questions about SearXNG, please do not open new issues here in the issue tracker which is intended for reporting errors or suggesting changes.

1. consult the docs: https://docs.searxng.org/index.html
2. discuss with the community on Matrix [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
3. or ask questions in the [discussion board](https://github.com/searxng/searxng/discussions)

**Comment by arda618** [comment]
> 

What I meant is to get results only from the websites of my wish. Let's say I only have Google enabled and I only want a list of websites to be indexed, and ignore all the other results that are not from the websites that I've listed. What do I have to do to achieve that? Also, thanks for the answer, the matrix channel is inactive and I will also post this on the discussion board.
