### ISSUE TITLE
[Feature/Bug] settings.yml: option to set 'default_locale' to 'all' or 'auto'

### ISSUE THREAD

**Issue by glaceorizer** [searxng/searxng#2378]
When customizing the SearXNG settings via the user interface, there is an option to set the search language to "Default language [all]" and "Auto detection [auto]". However, you cannot specify this in the settings.yml file with default_locale.

**Comment by return42** [comment]
The search language is set by ...
https://github.com/searxng/searxng/blob/216751dac86be8836434cf9a666da4f5a4ac2444/searx/settings.yml#L34

in the `search` section --> https://docs.searxng.org/admin/engines/settings.html#search

The `default_locale` in the `ui:` section is used for the language of the UI, there exists not "auto" or "all" value ... leaf this value unset to take the language from the browser for the UI language --> https://docs.searxng.org/admin/engines/settings.html#ui
