### ISSUE TITLE
Search error?

### ISSUE THREAD

**Issue by arda618** [searxng/searxng#2379]
I am not able to search for anything. I have slightly modified the code but there are no errors to be seen. Everything is so good so far but I am encountering this issue (check embedded image)
![image-30](https://user-images.githubusercontent.com/112322858/234631818-cd7a5616-f1d4-49f0-b2e4-57c6451f00a5.png)

**Comment by arda618** [comment]
Okay, I have checked the console output: Please read the full message 🙏 It'd be truly appreciated.
What I was trying to do was to implement search results from specific sites, you've linked me to one github issues page from 2021 (https://github.com/wcerfgba/searx/commit/fb12d9ff4458fc9ecbaa356039ae4041c20ce02f) and closed my issue due to it being a duplicate. I have pasted everything required from the latest commit of the repository linked, and checked the full code, some text formatting were different and I have changed to their current state on latest versions, and used a diff checker to make sure I haven't missed anything.

Conclusion:
There are no syntax errors.
A definition is missing. I have looked for it using grep (┌──(arda㉿kali)-[~/Documents/sxl/searx-master]
└─$ grep -r "site_query" .
./searx/search/__init__.py:                    site_query = self.search_query.query + " site:" + search_site
./searx/search/__init__.py:                    requests.append((engineref.name, site_query, request_params))

Here is the full console output:

ERROR   searx.webapp                  : cannot access local variable 'site_query' where it is not associated with a value
Traceback (most recent call last):
  File "/home/arda/Documents/searxng/searx/webapp.py", line 688, in search
    result_container = search.search()
                       ^^^^^^^^^^^^^^^
  File "/home/arda/Documents/searxng/searx/search/__init__.py", line 255, in search
    super().search()
  File "/home/arda/Documents/searxng/searx/search/__init__.py", line 228, in search
    self.search_standard()
  File "/home/arda/Documents/searxng/searx/search/__init__.py", line 214, in search_standard
    requests, self.actual_timeout = self._get_requests()
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/Documents/searxng/searx/search/__init__.py", line 156, in _get_requests
    requests.append((engineref.name, site_query, self.search_query.query, request_params))
                                     ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'site_query' where it is not associated with a value

**Comment by return42** [comment]
>  closed my issue due to it being a duplicate. 
> I have slightly modified the code 

Where is the code published?

**Comment by arda618** [comment]
> > closed my issue due to it being a duplicate.
> > I have slightly modified the code
> 
> Where is the code published?

Greetings, the only modifications are here:
https://github.com/wcerfgba/searx/commit/fb12d9ff4458fc9ecbaa356039ae4041c20ce02f
Otherwise it is the exact same SearXNG

**Comment by unixfox** [comment]
Closing as this is an issue tracker for searxng and not searx.

The issue tracker for searx is here: https://github.com/searx/searx/issues
