### ISSUE TITLE
Bug: Bing Engine

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searxng#2388]
**Version of SearXNG*
This happens on instances with an IP from Singapore, such as https://priv.au and https://opnxng.com

**How did you install SearXNG?**

Opnxng.com is installed using docker.

**What happened?** **How To Reproduce**

Searching with !bing on instances with an IP from Singapore will result in bing ( [parsing error](https://priv.au/stats?engine=bing) )

**Expected behavior**
Able to search with Bing or a notice that it is not supported.

**Screenshots & Logs**
```
lxml.etree.ParserError	Percentage	100
Filename	searx/engines/bing.py:186
Function	response
Code	dom = html.fromstring(resp.text)
```

**Comment by return42** [comment]
Hm, thats a very strange issue, when this line:

```dom = html.fromstring(resp.text)```

raise such an exception it seems the response is not a valid HTML (never seen this before in bing.py).

I can't reproduce this issue since I do not have an IP Singapore / can you dump the value in ```resp.text```?

**Comment by extremelyonline** [comment]
I'm sorry I don't know how to dump the value. But I'll try as soon as I have time.

**Comment by sonnysighedup** [comment]
I'm not the OP, but am getting the same error trying to host on [a VPS in Chicago](https://searx.eni-mega.com/) [running OpenBSD & using gunicron in place of uWSGI - so not exactly a standard install]. Here's the traceback I get which seems to suggest that resp.text is empty?

`2023-05-02 12:35:56,408 WARNING:searx.engines.bing: ErrorContext('searx/engines/bing.py', 186, 'dom = html.fromstring(resp.text)', 'lxml.etree.ParserError', None, ()) False`
`2023-05-02 12:35:56,410 ERROR:searx.engines.bing: exception : Document is empty`
`Traceback (most recent call last):`
`  File "/usr/local/searxng/searxng-src/searx/search/processors/online.py", line 165, in search`
`    search_results = self._search_basic(query, params)`
`  File "/usr/local/searxng/searxng-src/searx/search/processors/online.py", line 153, in _search_basic`
`    return self.engine.response(response)`
`  File "/usr/local/searxng/searxng-src/searx/engines/bing.py", line 186, in response`
`    dom = html.fromstring(resp.text)`
`  File "/usr/local/lib/python3.10/site-packages/lxml/html/__init__.py", line 873, in fromstring`
`    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)`
`  File "/usr/local/lib/python3.10/site-packages/lxml/html/__init__.py", line 761, in document_fromstring`
`    raise etree.ParserError(`
`lxml.etree.ParserError: Document is empty`
