### ISSUE TITLE
Firefox for Android: Cannot get search results when open in app is allowed

### ISSUE THREAD

**Issue by SleeplessOne1917** [searxng/searxng#2397]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
I do not run an instance, however I tested this on three popular instances:
- searx.be (2023.4.03)
- searx.org (2023.4.12+b07e44e5)
- etsi.me (2023.4.30+9967fbb7)

**How did you install SearXNG?**
n/a

**What happened?**
Performing a search on a SearXNG instance when Firefox is allowed to open links in apps, the search result page will not be reached. This only happens if you navigate to a SearXNG instance and search from there. If you have Firefox configured to use a SearXNG instance as it's default search and search from the address bar, it will still owrk as expectd.

**How To Reproduce**
- Download Firefox for Android.
- Set "Open links in apps" to a value other than "Never"
- Navigate to a SearXNG instance's home page
- Search for a query

**Expected behavior**
The page with the search results should be returned (usually the app it's asking to open in is a browser).

**Screenshots & Logs**
n/a

**Additional context**
Firefox version: 112.2.0 Build #2015946691
User agent: Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0

**Comment by return42** [comment]
@SleeplessOne1917 sorry for the very late response .. I do not have an Android at hand so I wanted to ask; does the issue still exist?

**Comment by SleeplessOne1917** [comment]
Not anymore. Closing.
