### ISSUE TITLE
Thumbnails don't load (CSP issue)

### ISSUE THREAD

**Issue by Ay1tsMe** [searxng/searxng#2399]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 commit 9967fbb7d14170f443c6cfb6938d444ecff3f442
Merge: ac241fe6 18c8ac06
Author: Markus Heiser <markus.heiser@darmarIT.de>
Date:   Sun Apr 30 08:32:45 2023 +0200

    Merge pull request #2383 from searxng/dependabot/pip/master/flask-2.3.1
    
    Bump flask from 2.2.3 to 2.3.1

**How did you install SearXNG?**
 
installed on Debian server using the utils/searxng.sh install all
**What happened?**

Thumbnails fail to load in search results.
Images load fine when you go to "images" tab but they fail to load for thumbnails
**How To Reproduce**

the instance is running on https://searx.tuxtower.net/

**Expected behavior**

For the thumbnails to load.
**Screenshots & Logs**

What happens: https://0x0.st/HPI4.png

**Comment by return42** [comment]
Hi @Ay1tsMe: you need to fix your CSP  ..

![image](https://user-images.githubusercontent.com/554536/235707107-531288e6-a605-4460-ac3a-3b3867f3b777.png)

at least ` img-src 'self' data:` is also needed to show the base64 embedded images.

Related: https://github.com/searxng/searxng/discussions/918
