### ISSUE TITLE
Brave Search Language Bug

### ISSUE THREAD

**Issue by smcmackin20** [searxng/searxng#2400]
Brave Search on a english search always make results show up in German and I cannot fix it
![Screen Shot 2023-05-02 at 3 26 53 PM](https://user-images.githubusercontent.com/96853437/235766039-53d9b586-2fbd-4642-b9b3-ed2c16619c7b.png)
![Screen Shot 2023-05-02 at 3 27 16 PM](https://user-images.githubusercontent.com/96853437/235766043-c60d999b-ebb2-4def-a006-5cf58db83a90.png)
I included searches for Los Angeles and Microsoft

**Comment by return42** [comment]
duplicate 

- https://github.com/searxng/searxng/issues/2294

[In the long run we should implement a Python module for https://search.brave.com/ that is more robust and also supports safe-search and localization.](https://github.com/searxng/searxng/issues/2294)
