### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by MisterDeee** [searxng/searxng#2401]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.20+d669da81

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:114`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Hi @MisterDeee

> Version: 2023.2.20+d669da81

please update your instance / if you are not the maintainer, contact the maintainer or use updated instance from https://searx.space/
