### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by beyond9thousand** [searxng/searxng#2402]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.3+e6f4765e

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 20
  * Parameters: `('Too many request',)`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by return42** [comment]
- https://github.com/searxng/searxng/issues/2294
