### ISSUE TITLE
No Longer Starts

### ISSUE THREAD

**Issue by stef204** [searxng/searxng#2407]
searxng-git-1.0.0.r3138.ge840c4812
linux x86_64

All of a sudden no longer starts and results in `Internal Server Error`:

````
% systemctl status uwsgi@searx
● uwsgi@searx.service - uWSGI service unit
     Loaded: loaded (�]8;;file://archlinux/usr/lib/systemd/system/uwsgi@.service/usr/lib/systemd/system/uwsgi@.service�]8;;; disabled; preset: disabled)�]8;;
     Active: active (running) since Thu 2023-05-04 21:33:59 EDT; 6s ago
   Main PID: 75741 (uwsgi)
     Status: "uWSGI is ready"
      Tasks: 4 (limit: 18519)
     Memory: 94.1M
        CPU: 1.781s
     CGroup: /system.slice/system-uwsgi.slice/uwsgi@searx.service
             ├─75741 /usr/bin/uwsgi --ini /etc/uwsgi/searx.ini
             ├─75742 /usr/bin/uwsgi --ini /etc/uwsgi/searx.ini
             └─75744 /usr/bin/uwsgi --ini /etc/uwsgi/searx.ini

May 04 21:34:00 archlinux uwsgi[75741]:   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
May 04 21:34:00 archlinux uwsgi[75741]:     resp = self.send(prep, **send_kwargs)
May 04 21:34:00 archlinux uwsgi[75741]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 04 21:34:00 archlinux uwsgi[75741]:   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
May 04 21:34:00 archlinux uwsgi[75741]:     r = adapter.send(request, **kwargs)
May 04 21:34:00 archlinux uwsgi[75741]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 04 21:34:00 archlinux uwsgi[75741]:   File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
May 04 21:34:00 archlinux uwsgi[75741]:     raise ConnectionError(e, request=request)
May 04 21:34:00 archlinux uwsgi[75741]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gigablast.com', port=443): Max retries exceeded with url: /search?c=main&qlangcountry=en-us&q=south&s=10 (Caused by NewConnectionError(>
May 04 21:34:00 archlinux uwsgi[75741]: WARNING:searx.engines:yggtorrent engine: Fail to initialize // HTTP error 403, suspended_time=86400
````
Not sure what to make of this but it's possible that some python package updates on my system broke something?

**Comment by return42** [comment]
> searxng-git-1.0.0.r3138.ge840c4812

not sure what you installed .. please install from SearXNG's master branch / follow https://docs.searxng.org/admin/installation.html

**Comment by stef204** [comment]
It's already building `master`.  See [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=searxng-git)

**Comment by unixfox** [comment]
@return42 does searxng support python 3.11?

**Comment by stef204** [comment]
I don't know, not seeing python version required in requirements.  Link please?
I am seeing this in requirements though: `flask-babel==3.1.0` and Arch is still on `python-flask-babel 3.0.1-2`

**Comment by return42** [comment]
> It's already building `master`.  See [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=searxng-git)

@stef204 was not clear that you installed the AUR package for searxng on ArchLinux,

> @return42 does searxng support python 3.11?

Personally I haven't tested, but "yes" we have it in the [CI](https://github.com/searxng/searxng/actions/runs/4892086811/jobs/8733405154)

https://github.com/searxng/searxng/blob/6f0f9baa38cb92e3d6d141580924a9e7420860a0/.github/workflows/integration.yml#L19

@HLFH AFAIK archlinux uses python 3.10 by default / can you reproduce the issue reported by @stef204  ?

> Not sure what to make of this but it's possible that some python package updates on my system broke something?

@stef204 Not sure what you have configured on your archlinux.

- how did you upgraded your archlinux to py3.11?
- did you have installed https://pypi.org/project/searx/ in a previous attempt? / you reported your issue also in the searx project https://github.com/searx/searx/discussions/3514

Please clarify what you have done and why you report this issue here and in the searx project (its all a little bit confusing to me).

**Comment by stef204** [comment]
I cross-posted to `searx` since this is a fork and the issue might be "upstream" -- hard to know.
I've only ever installed `searxng` (or `searx` prior to that) using the AUR, so always tracked by pacman if you will.
I did try to install `searx` instead of `searxng` prior to posting to see if the error was not present with `searx` but it is present there too.
Reverted to `searxng` now and still stuck with this error.
As far as python version, I just update system periodically "officially" using the standard method.  My system is pretty much plain vanilla, so to speak.
Arch runs python 3.11.3 -- official package.
````
% pacman -Si python       
Repository      : core
Name            : python
Version         : 3.11.3-1
````

**Comment by return42** [comment]
> My system is pretty much plain vanilla, so to speak.

Thanks for clarifying .. I see you have also posted in the AUR package https://aur.archlinux.org/packages/searxng-git :+1:

I think we have to wait about the AUR package maintainer @HLFH  ...

**Comment by stef204** [comment]
I've also emailed the maintainer of `python-flask-babel` to see if he could update from `3.0.1` to `3.1.0` -- at this point, I don't know what else to do, or how to troubleshoot further.  But it is highly likely some package updates in Arch broke `searx*`. I'm open to suggestions here.

**Comment by stef204** [comment]
I've uninstalled `searxng`, rebuilt a bunch of python packages on my system; and reinstalled it.  Seems to be running now. Not sure which of the python dependencies was the culprit but seems OK now.
Thanks for feedback.
I will run this for a couple days and if all OK, will close this issue.
