### ISSUE TITLE
Bug: wikidata engine

### ISSUE THREAD

**Issue by Batlez** [searxng/searxng#2410]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.6+0aade75e

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'query.wikidata.org')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: some results are invalids: invalid content
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:112`
  * Function: `_extend_container_basic`
  * Code: `result_container.extend(self.engine_name, search_results)`

**Comment by return42** [comment]
> Percentage: 0

... has no relevance, next time please fill out this form.
