### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by mattigilmore** [searxng/searxng#2417]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.6+0aade75e

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = network.get(query_url, headers=headers)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: RuntimeError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = network.get(query_url, headers=headers)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by sizquirt** [comment]
Same issue for me.

**Comment by return42** [comment]
> Percentage: 0

I think you can safely ignore this error rate.

--- 

To reopen please fill out the form .. whats your public URL?
