### ISSUE TITLE
500 error on WebKit-based browsers

### ISSUE THREAD

**Issue by Eolien55** [searxng/searxng#2434]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

I've tested many instances at [searx.space](https://searx.space), the only ones that work with WebKit-based browsers (or more precisely, WebKitGTK) such as vimb or luakit, are those whose version number is below 2023.5.3, so 2023.4.30+9967fbb7 works for example.
**How did you install SearXNG?**

N/A
**What happened?**

When you go to any url on the instance, nothing works (https://searx.work, /search, /this_url_isnt_valid, etc.) : it always returns a big **Internal Error**.
**How To Reproduce**

Install a WebKitGTK-based browser (like vimb), and open any instance, like https://searx.work.
**Expected behavior**

The server not returning that it encountered an internal error.
**Screenshots & Logs**

N/A
**Additional context**

N/A

**Comment by return42** [comment]
> the only ones that work with WebKit-based browsers (or more precisely, WebKitGTK) 

WebKit does not have issues .. tested e.g. here https://dev.searxng.org/screenshots.html#config=Mobile+Safari&test_case=search_general

Only related to WebKItGTK?

Not sure how to install vimb, but last release seems from 2020 https://github.com/fanglingsu/vimb/releases

luakit last release is from Nov. 2022 https://github.com/luakit/luakit/releases

--> I tested with "Gnome Web" aka Epiphany 3.36 and WebKitGTK 2.28 and it works.

**Comment by Eolien55** [comment]
> Only related to WebKItGTK

Seems so. If mobile Safari works correctly, the problem can only affect WebKitGTK-based browsers.

> last release seems from 2020
> luakit last release is from Nov. 2022

SearxNG works perfectly fine in elinks, whose last release was in 2012. I don't think the release date should matter: SearxNG shouldn't crash at all.

> --> I tested with "Gnome Web" aka Epiphany 3.36 and WebKitGTK 2.28 and it works.

Both vimb and luakit use WebKitGTK 2.40 on my machine, so the problem comes from releases after 2.28.

**Comment by return42** [comment]
> I don't think the release date should matter: SearxNG shouldn't crash at all.

That might true, but I don't recommend to use WEB browsers that did not have a (security) update since years.

> Both vimb and luakit use WebKitGTK 2.40 on my machine, so the problem comes from releases after 2.28.

Compiled by your own? .. can you please debug by your own and report what the issue is?

**Comment by Eolien55** [comment]
> can you please debug by your own and report what the issue is?

In `searx/preferences.py`, in the function `from_http_request` of the class `ClientPref`, there's this line:

```python
return cls(locale=pairs[0][0])
```

which results in an IndexError, when pairs is empty. The function parses the `Accept-Language` HTTP header, which not mandatory, and puts it in `pairs`. Almost all browsers do send this header [according to mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language), but as RFC9110 indicates, it is not compulsory.

This results in a crash when the header is not sent (which seems to be the case for vimb and luakit, at least on my machine).

Simple fix:
```diff
diff --git a/searx/preferences.py b/searx/preferences.py
index 8552305a..be488f45 100644
--- a/searx/preferences.py
+++ b/searx/preferences.py
@@ -332,6 +332,8 @@ class ClientPref:
                 continue
             pairs.append((locale, qvalue))
         pairs.sort(reverse=True, key=lambda x: x[1])
+        if len(pairs) == 0:
+        	pairs.append((babel.Locale.parse("en_US"), 1.0))
         return cls(locale=pairs[0][0])
 
 
```

**Comment by return42** [comment]
> The function parses the `Accept-Language` HTTP header, which not mandatory

In the implementation the `Accept-Language` HTTP header is not mandatory ...

https://github.com/searxng/searxng/blob/73c023bbea51c76516ea51321711d0f1d5299b7b/searx/preferences.py#L319-L321

But the implementation fails if set but value is empty or invalid:

- https://github.com/searxng/searxng/pull/2452

> This results in a crash when the header is not sent (which seems to be the case for vimb and luakit, at least on my machine).

I assume these browsers set `Accept-Language` to an empty value / the PR should fix this issue.

Thanks a lot for you research on this issue :+1:
