### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by samsapti** [searxng/searxng#2439]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.15+50cd7e2b
Instance: https://search.sapti.me

**How did you install SearXNG?**

Via Docker.

**What happened?**

DuckDuckGo and DDG Definitions has been returning `timeout` and `Suspended: timeout` for the last few days, and when it does SearXNG is slow to load. The 15% reported below is not really accurate, it happens pretty much all the time for me. It's probably closer to 95%.

**How To Reproduce**

1. Go to SearXNG
2. Search `!ddg foo`
3. Observe error

**Expected behavior**

DDG should return results.

**Screenshots & Logs**

```log
2023-05-16 22:45:51,188 ERROR:searx.engines.duckduckgo: engine timeout
2023-05-16 22:45:51,202 WARNING:searx.engines.duckduckgo: ErrorContext('searx/engines/duckduckgo.py', 98, 'res = network.get(query_url, headers=headers)', 'httpx.ConnectTimeout', None, (None, None, 'duckduckgo.com')) False
2023-05-16 22:45:51,203 ERROR:searx.engines.duckduckgo: HTTP requests timeout (search duration : 3.014873551990604 s, timeout: 3.0 s) : ConnectTimeout
```

**Additional context**

`suspended_times`:
```yaml
suspended_times:
  SearxEngineAccessDenied: 0
  SearxEngineCaptcha: 600
  SearxEngineTooManyRequests: 600
  cf_SearxEngineCaptcha: 600
  cf_SearxEngineAccessDenied: 1200
  recaptcha_SearxEngineCaptcha: 600
```

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 15
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = network.get(query_url, headers=headers)`

Error
  * Error: httpx.ReadError
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 0
  * Parameters: `('Request failed',)`
  * File name: `searx/engines/duckduckgo.py:101`
  * Function: `get_vqd`
  * Code: `raise SearxEngineAPIException('Request failed')`

Error
  * Error: httpx.WriteError
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = network.get(query_url, headers=headers)`

**Comment by PatyaRishim** [comment]
Long user and tester of public instances here. I have seen this error in every other instance, you can reproduce it in any latest updated instance, weirdly enough, the newest version fixed it for a short period of time. Hopefully a fix will come soon.

**Comment by PatyaRishim** [comment]
> Long user and tester of public instances here. I have seen this error in every other instance, you can reproduce it in any latest updated instance, weirdly enough, the newest version fixed it for a short period of time. Hopefully a fix will come soon.

Ok, for some reason, the problem disappeared, at least in the next instances (they weren't working some hours ago):
>darmarit.org
>https://search.ononoki.org
>https://searx.tuxcloud.net
>https://searx.tiekoetter.com
>https://search.sapti.me

Searx.be has the error.

Wish I could provide some technical data, but I'm not that tech-savvy.

**Comment by return42** [comment]
>  the newest version fixed it for a short period of time. 

this issue is different even the symptoms are looking the same.

> Ok, for some reason, the problem disappeared

The experience is individual and change over the time: ddg is sometimes slow in response (this is what I suppose). But the accumulation of problems is suspicious.

ddg-Web and ddg-Images APIs do need a `vqd` value .. to get this value the request to ddg is sent twice (see below) .. with a caching / the caching is not very good, so most often the request is sent twice .. may be this is the cause .. IDK.

> DuckDuckGo and DDG Definitions has been returning `timeout`

That's what puzzles me, if it was the vqd value, ddg-definitions shouldn't have any problems, because this engine doesn't need vqd code and doesn't send two requests.

But when I look at searx.be the reliability of ddg-definitions is down by 35%:

![grafik](https://github.com/searxng/searxng/assets/554536/a954a634-06db-4c7d-83e0-bd4856cb147b)

So I asking myself: is it just ddg that response sometimes very slow? .. IDK .. we need to continue to monitor this.


----

https://github.com/searxng/searxng/blob/50cd7e2b03dbce50a41d39aad9521dab6d2ff246/searx/engines/duckduckgo.py#L82-L98

**Comment by samsapti** [comment]
@PatyaRishim you're right, it seems to be gone now. Weird.
Next time it happens, I'll try to increase the timeout for DDG and DDG Definitions.

**Comment by return42** [comment]
Seems my IP is now on duckduckgo.com's .block list. I disable ddg engine for the next days.

-- 

Two or three ours later duckduckgo.com pulled my IP from the block list.

**Comment by samsapti** [comment]
For me it comes and goes.

**Comment by return42** [comment]
> For me it comes and goes.

The cause are the bots that pass the limiter.

Yesterday I observed my server for a few hours and identified round about 300 IPs with bot request, for the interim I added a block list to my instance: 

- https://github.com/searxng/searxng/commit/08429b42ba15229bb40bed1583b82bb6ef979198

But the true is there is a bot from RU that has endless IPs .. about 200 of the 300 IPs in my block list are from the same bot .. I gave up after a while.

On the long term we have to improve the limiter / I start a first attempt in this PR:

- https://github.com/searxng/searxng/pull/2357

**Comment by unixfox** [comment]
I just switch to the onion endpoint, it may add more latency but at least it will always work: https://tor.stackexchange.com/questions/6152/how-do-i-add-the-duckduckgo-onion-version-to-the-tor-browser-search-providers

**Comment by return42** [comment]
> goes away for me when I restart my SearXNG instance .. caching ..  Maybe it's what's causing it?

No.  When you restart your instance the suspend time of the engine gets lost. We discussed suspend times by example here: https://github.com/searxng/searxng/issues/2011#issuecomment-1541377981  

> We should open a discussion "suspended_times: practical experience / best values?"

**Comment by samsapti** [comment]
Increasing timeout to 5.0 didn't work.

**Comment by return42** [comment]
>  Increasing timeout to 5.0 didn't work.

Response time median is at 0.7 sec --> https://search.sapti.me/stats?engine=duckduckgo

If you see a timeout on ddg on your instance again, [you can open ddg from your servers's IP](https://docs.searxng.org/admin/answer-captcha.html) and see why ddg response some time so slow.

**Comment by return42** [comment]
> If you see a timeout on ddg on your instance again, [you can open ddg from your servers's IP](https://docs.searxng.org/admin/answer-captcha.html) and see why ddg response some time so slow.

Today I also had a timeout on my instance and I did a request to https://duckduckgo.com/ from my server's IP .. but nothing happened .. ddg did never response. A ping did work, its only HTTP that did not response.

Timeout seems the method ddg uses to block IPs that send "to much" suspicious requests.

**Comment by samsapti** [comment]
Yep, also happened to me. However, when I tried with cURL it worked fine for a short period, I got some HTML back. Even when specifying the same user-agent as my browser. But shortly after it stopped working.

```sh
# Either this or use cURL from an SSH session
curl -x socks://127.0.0.1:8080 https://duckduckgo.com
curl -A "<User-Agent>" -x socks://127.0.0.1:8080 https://duckduckgo.com
```

**Comment by muzzah** [comment]
Is there any way to just completely disable duckduckgo? 

Since searxng stores config in cookies, and I delete cookies upon browser tab being closed, it keeps coming back.

Is there a way to just disable it alltogether from the engine since my ddg searches neever work?

**Comment by return42** [comment]
> Is there a way to just disable it alltogether from the engine

Disable (`disabled: true`) the duckduckgo engine in your settings.yml file / https://docs.searxng.org/admin/engines/settings.html#engine-settings

>  since my ddg searches neever work?

What is your public IP? .. Is the limiter active?

**Comment by return42** [comment]
@samsapti: the limiter was redesigned and advanced bot-blocking methods were implemented (https://github.com/searxng/searxng/pull/2357).  Since I enabled the [`link_token` method](https://docs.searxng.org/src/searx.botdetection.html#module-searx.botdetection.ip_limit), thousands of bot requests have been blocked. 

since the bot requests are recognized and blocked in their multiplicity, it happens only extremely rarely that DDG blocks my instance.

If you still get blocked by DDG (timeout error) I recommend you to enable the `link_token` method on your instance.  

Two hints:

1. this method must run for several days to detect bots / the effect will only be felt after a longer runtime

2. Such bot blocking methods are always based on blocking IPs / instances that are reached through an onion gateway can not be protected by the limiter, because it is in the nature of the onion network that the IPs of the requesting clients are not known.

With this recommendation I close this ticket / another method than improved bot blocking does not exist to solve the problem of this ticket ...

**Comment by samsapti** [comment]
@return42 that sounds great, will try it out.

> this method must run for several days to detect bots / the effect will only be felt after a longer runtime

Does this mean that the Redis DB data needs to persist between runs (fx. when restarting after an upgrade)? My Redis DB currently resides in a `tmpfs` in my `docker-compose.yml`.

**Comment by return42** [comment]
> Does this mean that the Redis DB data needs to persist between runs

Yes.  / FYI: my DB has a size of ~1MB ..

```
-rw-rw---- 1 searxng-redis searxng-redis 1.2M Jun 24 10:05 dump.rdb
```
