### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by hiiamboris** [searxng/searxng#2443]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.15+50cd7e2b

**How did you install SearXNG?**
https://docs.searxng.org/admin/installation-docker.html#installation-docker

**What happened?**
qwant (general, images, videos) reports "API error" for last day or two (API change?)

**How To Reproduce**
Search using qwant

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by dsmith2001** [comment]
Your IP has likely been blocked by Qwant, you can try this: https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619

**Comment by hiiamboris** [comment]
Sorry, don't know how I searched :D
