### ISSUE TITLE
TimeoutException: yep engine

### ISSUE THREAD

**Issue by deererum** [searxng/searxng#2444]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.15

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 10
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.yep.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Error: httpx.TimeoutException
> Percentage: 10

Its not really a bug, if you need/want increase the timeout of the engine by example to 5sec (default is 3sec):

```yaml
- name: yep
  timeout: 5
```

---

BTW: next time please fill out the form.

**Comment by deererum** [comment]
#xyz •••czechsubmarine
#xyz •••czechsubmarine
