### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by linuxoak** [searxng/searxng#2449]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.1.23+522ba9a1

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by unixfox** [comment]
Duplicate https://github.com/searxng/searxng/issues/2011
