### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by xbdmHQ** [searxng/searxng#2456]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.22+b2d0b743

**How did you install SearXNG?**
SearxNG Docker

**What happened?**
Trying to use mojeek engine by selecting it in preferences and I went and go search it gave the error.

**How To Reproduce**
Trying to use mojeek engine by selecting it in preferences and I went and go search it gave the error.

**Expected behavior**
be able to use mojeek

**Screenshots & Logs**
![](https://bffr.wtf/r/SJlZ5a.jpg?compress=true)

```
searxng    |   File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response
searxng    |     raise_for_httperror(response)
searxng    |   File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
searxng    |     raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searxng    | searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
searxng    | 2023-05-23 21:57:22,897 WARNING:searx.engines.library of congress: ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
searxng    | 2023-05-23 21:57:22,897 ERROR:searx.engines.library of congress: Searx is blocked
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
searxng    |     search_results = self._search_basic(query, params)
searxng    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 149, in _search_basic
searxng    |     response = self._send_http_request(params)
searxng    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 118, in _send_http_request
searxng    |     response = req(params['url'], **request_args)
searxng    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng    |     return future.result(timeout)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
searxng    |     return self.__get_result()
searxng    |            ^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
searxng    |     raise self._exception
searxng    |   File "/usr/local/searxng/searx/network/network.py", line 291, in request
searxng    |     return await self.call_client(False, method, url, **kwargs)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/network/network.py", line 274, in call_client
searxng    |     return Network.patch_response(response, do_raise_for_httperror)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response
searxng    |     raise_for_httperror(response)
searxng    |   File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
searxng    |     raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searxng    | searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
searxng    | 2023-05-23 21:58:23,706 WARNING:searx.engines.mojeek: ErrorContext('searx/engines/xpath.py', 199, 'raise_for_httperror(resp)', 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
searxng    | 2023-05-23 21:58:23,707 ERROR:searx.engines.mojeek: Searx is blocked
searxng    | Traceback (most recent call last):
searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
searxng    |     search_results = self._search_basic(query, params)
searxng    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 153, in _search_basic
searxng    |     return self.engine.response(response)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/engines/xpath.py", line 199, in response
searxng    |     raise_for_httperror(resp)
searxng    |   File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
searxng    |     raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searxng    | searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
```

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 20
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by return42** [comment]
From what instance you got this issue? is it https://search.whateveritworks.org --> https://github.com/searxng/searx-instances/issues/337#issuecomment-1560449857

> Trying to use mojeek engine by selecting it in preferences and I went and go search it gave the error.

Use the [search syntax](https://docs.searxng.org/user/search-syntax.html) .. its much easier, just type :`!mojeek foo`

**Comment by xbdmHQ** [comment]
ah might be mojeek, they might be blocking the ips of searxng instances. might remove it and just use the other engines tbh

**Comment by return42** [comment]
mojeek is a XPath engine

https://github.com/searxng/searxng/blob/b2d0b7435710f1d2b989d5db71dd5de9af3992d0/searx/settings.yml#L1661-L1681

XPath engines often have trouble (and got more often blocked) since XPath implementation is a very simple REST API call .. 

- https://github.com/searxng/searxng/issues?q=is%3Aissue+mojeek

> might remove it and just use the other engines tbh

thats what I recommend .. or we have to implement a more elaborate python module for this engine (I don't have time for, but may be someone others?

BTW: on my instance I can't reproduce the issue : https://darmarit.org/searx/search?q=%21mojeek+foo&language=en

**Comment by return42** [comment]
> BTW: on my instance I can't reproduce the issue : https://darmarit.org/searx/search?q=%21mojeek+foo&language=en

Today I get blocked by mojeek ..

FYI: if your instance gets blocked by mojeek:

    Error: searx.exceptions.SearxEngineAccessDeniedException

You have to open https://www.mojeek.com/search in a WEB browser on your instance server and do some searches / it is important that the request is sent from the IP of the SearXNG server.  

This can also be done with your local WEB browser which sends its request via an SSH tunnel from your server's IP / the method is described here:

- https://docs.searxng.org/admin/answer-captcha.html

**Comment by jordanmontt** [comment]
I get this error too. I'm running searxng on localhost. I confirm that, sometimes, doing a lot of requests to mojeek from my instance (my computer because it's localhost) can fix the issue, but sometimes and for a limited time.
