### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by bitshifter52** [searxng/searxng#2474]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.4.30+9967fbb7

**How did you install SearXNG?**

Running https://searx.org
**What happened?**

I used this search: subtitle generator
**How To Reproduce**

Typed in: subtitle generator 
Error message appeared in results window
**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 80
  * Parameters: `('Request failed',)`
  * File name: `searx/engines/duckduckgo.py:101`
  * Function: `get_vqd`
  * Code: `raise SearxEngineAPIException('Request failed')`

Error
  * Error: RuntimeError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = network.get(query_url, headers=headers)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Hi @bitshifter52 

> Version: 2023.4.30+9967fbb7

please update your instance / if you are not the maintainer, contact the maintainer or use updated instance from https://searx.space/
