### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Samppady** [searxng/searxng#2475]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.29+c1b5ff7e

**How did you install SearXNG?**
Installed through Docker

**What happened?**
This keeps happening a lot lately for the Google engine. A few users and I are using this searxng.

**How To Reproduce**
Usually halfway into a day (maybe 20-50 searches done over the morning) it stops working and gives this error. 

Sometimes after a few searches

**Expected behavior**
Google should return results.

**Screenshots & Logs**
https://www.dropbox.com/s/t041mbpshpd30wh/google%20http%20error.PNG?dl=0
https://www.dropbox.com/s/ir2l5sn1midoatx/google%20tests.PNG?dl=0

**Additional context**
I noticed that when that error message appears, I can no longer access Google.com with other browsers or smart devices on the home network.

Chrome error: ERR_CONNECTION_REFUSED

Engines cannot retrieve results:
google ( [HTTP connection error )  

Just tell me what data you need if more is required and ill try to retrieve it

Limiter is already On.

**Technical report**

Error
  * Error: httpx.ConnectError
  * Percentage: 15
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Samppady** [comment]
Is there any way to determine that the Google search engine uses a different outgoing IP address?
If I have second Gateway IP for outgoing traffic.

**Comment by return42** [comment]
> Installed through Docker ...
> I noticed that when that error message appears, I can no longer access Google.com with other browsers or smart devices on the home network.

Did you installed SearNXG in the same subnet where your desktop and smart devices are located?

**Comment by Samppady** [comment]
> > Installed through Docker ...
> > I noticed that when that error message appears, I can no longer access Google.com with other browsers or smart devices on the home network.
> 
> Did you installed SearNXG in the same subnet where your desktop and smart devices are located?

Searxng is on a different network.

Lan: 192.168.0.0/24 (Desktop PC)
IoT: 192.168.60.0/24 (Smart Devices) 
Docker Network (I think it was 172.17. 0.0/16 default one.)

The Docker host computer is on the LAN network, and Docker uses a different network.

Both networks use the same outgoing WAN IP address.

Docker-compose.yaml : https://github.com/searxng/searxng-docker/blob/master/docker-compose.yaml

**Comment by Samppady** [comment]
This morning, I performed a search and once again received the error message "ERR_CONNECTION_REFUSED" from Google.com.

However, I checked Google's alternative search addresses, such as "google.fi" and "google.se," and I was able to access those sites using a web browser.

At 8:00, it was not possible to access the "Google.com" site, but at 8:25, it appears that the site became accessible again.

**Comment by unixfox** [comment]
It's 100% a network issue on your side. Google is not going to return connection refused randomly like that.
