### ISSUE TITLE
Plugin system broken

### ISSUE THREAD

**Issue by SatoshiGuacamole** [searxng/searxng#2490]
Here's me all excited about migrating from Searx to SearxNG to enjoy well maintained search engines. Turns out that themes and plugin systems are ripped out with no clear documentation on how to develop custom themes and misleading documentation on how to develop plugins.

https://github.com/searxng/searxng/blob/master/docs/dev/plugins.rst

Should be updated to reflect the missing plugin functionality.

How do I add custom CSS and JavaScript nowadays? How do I get my homepage search category selectors back?

**Comment by return42** [comment]
> Turns out that themes and plugin systems are ripped out with no clear documentation on how to develop custom themes and misleading documentation on how to develop plugins.

It has not been ripped out. Its a while ago I tested the [Example Plugin](https://docs.searxng.org/dev/plugins.html) may we can improve the docs.

> How do I add custom CSS and JavaScript nowadays? 

take a look at the [Example Plugin](https://docs.searxng.org/dev/plugins.html)

> How do I get my homepage search category selectors back?

Not sure in detail what you want to do or what you miss .. can you describe your plugin or give us a link to the sources ..

**Comment by SatoshiGuacamole** [comment]
Plugin js_dependencies and css_dependencies no longer load the files, must've been disabled on purpose. I'm making good strides developing a custom theme extending from simple adding back the advanced search functionality of oscar, theming also gives options to load custom js and css. Will publish and contribute. Just unpleasantly surprised with the current state where searx.space is calling too soon for a complete ban of regular searx instances when this project is clearly inferior for the moment.

**Comment by dalf** [comment]
> Not sure in detail what you want to do or what you miss .. can you describe your plugin or give us a link to the sources ..

I think the request is to have
![image](https://github.com/searxng/searxng/assets/1594191/0d36f65f-40a7-48ce-9d95-9b48d9937bfc)

in the front page.

I usually use a bang to overcome this, however, it is messy when I try to change to click on the General category from `!images foobar`: I need to remove the bang first, and then click on the General category. It is painful on mobile phone.

So I second this request.

---

Regarding the js_dependencies  and css_dependencies  : 
* [webapp.py](https://github.com/searxng/searxng/blob/8a85d1b0c7b03cc0d0f82287a114728b521a5a47/searx/webapp.py#L473-L487) initialize the required variables.
* As far I remember, js_dependencies and css_dependencies has never been implemented in the simple theme : the JS and CSS from plugins are hard wired for the oscar theme, the simple implements it own version.

**Comment by SatoshiGuacamole** [comment]
This is what I could come up with to restore the search filters on the homepage: https://github.com/SatoshiGuacamole/searxng-advanced-theme.git

<img width="1007" alt="image" src="https://github.com/searxng/searxng/assets/103341519/50484729-c419-44d8-a1d9-9eb638ca74dd">

Taking the approach where scripts are included as jinja partials feels wrong, but this is just one of the limited amount of ways where I was able to include the javascript needed to restore the 'search on category select' functionality.

I managed to dump the user_plugins inside the template but whatever I try, the css_dependencies and js_dependencies remain empty.

If there's interest for it I'd be happy to port the advanced search filters to the simple template of this repo.

**Comment by xbdmHQ** [comment]
plugins work on mines:
https://github.com/WhateverItWorks/my-SearXNG-Docker-Compose

**Comment by SatoshiGuacamole** [comment]
@xbdmHQ Did you get any external plugins to work? Such as the [only show green results](https://github.com/return42/tgwf-searx-plugins) plugin?

**Comment by SatoshiGuacamole** [comment]
> What does it do?, Show green renewal results?

It filters websites that are green climate wise.

> EDIT: Hasn't been updated for years.

And still running smooth on regular Searx instances.

**Comment by xbdmHQ** [comment]
> > What does it do?, Show green renewal results?
> 
> It filters websites that are green climate wise.
> 
> > EDIT: Hasn't been updated for years.
> 
> And still running smooth on regular Searx instances.

That's and searx hasn't been updated as well. Hint why completent hosters use searxng instead. I enabled it on mines, if you want to test, https://search.whateveritworks.org

**Comment by SatoshiGuacamole** [comment]
Right. Shall I just start on:
1. advanced search filters in simple template, controllable through ui setting
2. fix template inclusion of external plugin js_dependencies and css_dependencies in base.html

Is it worth spending my time on this @return42 @dalf

**Comment by return42** [comment]
@SatoshiGuacamole : thanks a lot for your offer :+1: .. but :-)

About https://github.com/return42/tgwf-searx-plugins 

.. this plugin is from mine, I haven't tested it since a long time.  Its a very old  and long time not updated plugin, requires `requests` which is not in SearXNG since a long time (I have to fix the plugin / beside the request issue the plugin works):

    File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/only_show_green_results.py", line 7, in <module>
      import requests
    ModuleNotFoundError: No module named 'requests'


About CSS & JS

.. Style and Code injection is a concept of the (old) oscar theme that is not supported any longer.  Conflicts are to be expected with this type of customizing, which is why we not support this type of customizing.

- https://github.com/searxng/searxng/pull/2497

To customize CSS & JS the instance maintainer has to create its own *brand* (a fork)

- https://docs.searxng.org/admin/engines/settings.html#brand

By setting the *brand-options* it becomes clear to the user that this instance is not a vanilla SearXNG / Related:

- https://github.com/searxng/searxng/issues/2335#issuecomment-1504671011


About "Plugin system broken"

.. plugins do work / except the CSS & JS injection which is not supported in simple theme (see remarks above).

**Comment by return42** [comment]
FYI: I fixed the "Green WEB" plugin ..

- https://github.com/return42/tgwf-searx-plugins/issues/2

and installed it on my instance as described here ..

- https://docs.searxng.org/dev/plugins.html#external-plugins

User can activate it in the preferences "Only show green hosted results" --> https://darmarit.org/searx/preferences

But take into account

1. My instances uses the Green-WEB API (very slow) / see [README](https://github.com/return42/tgwf-searx-plugins/blob/master/README.rst)
2. Popular sites such as Wikipedia are not part of the "Green WEB" and are filtered out of the result lists.

**Comment by xbdmHQ** [comment]
so its added in update?

**Comment by SatoshiGuacamole** [comment]
Thank you for fixing the plugin, works a charm.

So the way forward would seem to create a new theme.

**Comment by return42** [comment]
> So the way forward would seem to create a new theme.

@SatoshiGuacamole: it depends what you want .. alternatively you can create your own brand .. in its simplest form, this is just one commit in your branch on top of the master branch from SearXNG.

Here is for example the brand of my instance https://github.com/searxng/searxng/commit/deaba96ef2 .. as you can see, its very simple to create a brand.

> How do I add custom CSS and JavaScript nowadays? 

In your brand, add the CSS and JS you want to the `base.html`

https://github.com/searxng/searxng/blob/1f0fb3122d5d342d6537d77f1c51d2f44c2f81f6/searx/templates/simple/base.html#L30-L33
