### ISSUE TITLE
Add Privacy AI Searches

### ISSUE THREAD

**Issue by xbdmHQ** [searxng/searxng#2495]
**Describe the solution you'd like**
Kagi.com a privacy search engine has added ai search into their search engine, require sign up. If you add AI in searxng in a privacy way without a account more people would be using it.

**Comment by return42** [comment]
I am closing this topic, we have  similar threads on this topic:

- https://github.com/searxng/searxng/issues/2008
- https://github.com/searxng/searxng/issues/2273
- https://github.com/searxng/searxng/issues/2163
