### ISSUE TITLE
Define Redis URL from Environment variable

### ISSUE THREAD

**Issue by robigan** [searxng/searxng#2499]
**Describe the solution you'd like**
To be able to specify a certain environment variable that I can set at runtime that'll point to my redis database connection URL

**Describe alternatives you've considered**
I use the Dockerfile to build SearX NG and then deploy. My build pipeline doesn't permit being able to specify a build argument that allows me to run some custom sed command to subsitute the redis.url parameter in settings.yml. Besides I think many people would benefit from this as it's quite common to specify database locations using environment variables in the Docker space of things, especially with docker-compose definitions.

**Comment by return42** [comment]
Is this a docker question/issue should, we move this to https://github.com/searxng/searxng-docker ?

I can't really help on docker, but as far I know you have a mounted /etc/searxng folder where your https://github.com/searxng/searxng-docker/blob/master/searxng/settings.yml is located .. in this file you can modify the redis setting to your needs.

**Comment by robigan** [comment]
> Is this a docker question/issue should, we move this to https://github.com/searxng/searxng-docker ?
> 
> I can't really help on docker, but as far I know you have a mounted /etc/searxng folder where your https://github.com/searxng/searxng-docker/blob/master/searxng/settings.yml is located .. in this file you can modify the redis setting to your needs.

Not at all a docker question/issue, as the requirements for such an implementation are at the project level, relevant to this repository. Yes I am aware I can change my settings.yml, but my build pipeline doesn't mount any folders, and uses a modified Dockerfile to bootstrap /etc/searxng with my configs. As stated above many other projects on the internet can configure database connections via relevant files, but it's a common thing to be able to do this via environment variables.

Reasons for this:
* Redis connection string may change and is useful for restarting the container easily by redefining variables rather than parsing and replacing the contents of redis.url
* Definition of redis connection string is defined within the same file as the docker-compose.yml, making the docker-compose.yml a single source of truth and not making it more complicated by needing to update elsewhere
* This feature makes the lives of people who use web dashboards for docker such as portainer easier because then they don't have to ssh into their machine, change settings.yml, etc. (Or upload changes to github repos for people who keep track of their configs via repos)

**Comment by return42** [comment]
Updated documentation has been deployed --> [`$SEARXNG_REDIS_URL`](https://docs.searxng.org/admin/engines/settings.html#redis)
