### ISSUE TITLE
Can't Open the Other Research Tabs

### ISSUE THREAD

**Issue by bbergeron0** [searxng/searxng#2511]
On SearXNG-Docker 2023.6.23+2e4a4351, clicking on the "Images," "Videos," "News," etc. tabs doesn't do anything besides toggling the tab text and icon blue. There's no error in the console, and nothing in the network debugger either.

**Comment by return42** [comment]
Did you set [ui: results_on_new_tab:](https://docs.searxng.org/admin/engines/settings.html#ui)?

What instance do you use?

**Comment by bbergeron0** [comment]
results_on_new_tab is commented out. It's a self-hosted docker instance running behind a Nginx proxy. My client is Firefox 102.12.0esr (64-bit).

**Comment by return42** [comment]
Sorry, my fail ..  `results_on_new_tab` is irrelevant.

In preferences did you activate ...

![image](https://github.com/searxng/searxng/assets/554536/56ab14dd-45cb-44e9-b795-591438375dbd)

**Comment by bbergeron0** [comment]
That's it chief, thanks a lot!

Shouldn't this be the default behaviour, since that's how other major search engine do it, and how new users expect it to work? What's the motive?

And how can I turn it on by default on my instance?

**Comment by return42** [comment]
> Shouldn't this be the default behaviour, 

this is the "Search on category select" plugin and its enabled by default

https://github.com/searxng/searxng/blob/2e4a435134e0f677fbe24853dd81453a54770674/searx/settings.yml#L205-L211
