### ISSUE TITLE
Google is actively blocking SearXNG instances - SearxEngineTooManyRequestsException: Too many requests

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#2515]
# Description about the issue

It appears that Google is now trying to block SearXNG instances. If you install a fresh SearXNG instance and then perform 5 searches in a row, your instance gets instantly blocked.

The used technique is probably TLS and/or HTTP2 fingerprinting, as restarting SearXNG brings back the ability to perform queries because on startup, like implemented in #2266 SearXNG rotate the ciphers list. There is also the possibility that Google think that SearXNG is some kind of botnet and if one SearXNG instance is doing too many requests or sending "bots" queries, then it affects all the other legitimate SearXNG instances.

Enabling the new advanced limiter (#2357) is probably not going to solve anything, as there will still be public instances without the limiter enabled or people maliciously using SearXNG locally/privately.

I do not have any metrics for the global workability of the Google engine over the time (maybe it would be a good thing to monitor?), but currently it seems like Google now works on a lot less SearXNG public instances than before. Only 25 instances out of 91 have Google engine working ([saved archive](https://archive.is/sMUvA)).
According to web archive, a few days ago (19th June) it was 66 out of 91: http://web.archive.org/web/20230619001339/https://searx.space/

# Possible solutions for fixing this issue

- Periodically rotate the cipher list, like every 5 requests. May not work very well because there is a finite amount of ciphers that you can rotate to.
- Bring back the old ability to not use the mobile UI (this worked fine on private/local SearXNG instance) and set it by default like before. And hope it will reduce the amount of requests to that endpoint from SearXNG instances and thus Google will rate limit less the SearXNG instances.  
   Now that Google is aware, I don't think this will help except maybe for private/local SearXNG instance where the default endpoint (not mobile UI) worked very good.
- Try to look like as close as possible to a Firefox browser in terms of TLS fingerprint (and maybe HTTP2 fingerprint). I shared in https://github.com/searxng/searxng/pull/2266#issuecomment-1581162826 a couple of python libraries for doing that.
- Use HTTP3

I'll in the coming days try to find other solutions, understand a bit better the root cause, as this deeply affect me because I'm used to only use Google engine on SearXNG for the great results...

# Opinion about switching off the ability to switch between normal Google endpoint and the mobile UI endpoint

I did warn in https://github.com/searxng/searxng/issues/774#issuecomment-1071271965 that the mobile UI should never be used by default as it is just a way to secretly "bypass" the too many requests error from Google.

A couple of months has passed since the mobile UI endpoint was turned on by default in https://github.com/searxng/searxng/commit/249989955497cd048fa3312d115971282983b269, like stated in my comment Google has now found that SearXNG is using a special endpoint for doing its requests and has effectively implemented some kind of protection on it because now everyone is using the endpoint, and it's not a secret anymore...

It's also possible that Google is now caring about protecting even more its systems from bots, like it is also doing for YouTube with major alternative frontends to Youtube like this current issue Invidious faces: iv-org/invidious issues 3822

Some people theorize that it's in order to not let people fetching data to feed their "AI technologies", I do not have a clear opinion on this.

**Comment by return42** [comment]
> If you install a fresh SearXNG instance and then perform 5 searches in a row, your instance gets instantly blocked.

BTW a `make run` does have the issue you described. 

> There is also the possibility that Google think that SearXNG is some kind of botnet and if one SearXNG instance is doing too many requests or sending "bots" queries, then it affects all the other legitimate SearXNG instances.

IDK why, but I can't reproduce this issue on my instance.  On my instance google is active by default and has a [Reliability of 100%](https://darmarit.org/searx/stats?engine=google).

IDK if it is related to what you have observed

- my instance uses google autocomplete
- my instance has only IPv4
- The implementation of the google and other engines has some **network issues** (I am currently still in the analysis phase) ..
  --> https://github.com/searxng/searxng/issues/2513#issuecomment-1605331026 
  --> https://github.com/searxng/searxng/issues/762#issuecomment-1605323861

I will first analyze & fix the **network issues**.

**Comment by unixfox** [comment]
> IDK why, but I can't reproduce this issue on my instance.  On my instance google is active by default and has a [Reliability of 100%](https://darmarit.org/searx/stats?engine=google).
> 
> IDK if it is related to what you have observed
> 
> - my instance uses google autocomplete
> - my instance has only IPv4

I did try on the IPv4 of my home internet and with the default settings.

There are also instances on https://searx.space where it works fine too. This blockage may be per region or per certain Google datacenter.

Don't forget that Google is usually deploying things in A/B testing in order to not affect everyone: https://vwo.com/ab-testing/

> - The implementation of the google and other engines has some **network issues** (I am currently still in the analysis phase) ..
>   --> https://github.com/searxng/searxng/issues/2513#issuecomment-1605331026 
>   --> https://github.com/searxng/searxng/issues/762#issuecomment-1605323861
> 
> I will first analyze & fix the **network issues**.

Thank you indeed for my use case it would be great to be able to set proxies, switch on/off HTTP2 and more.

**Comment by return42** [comment]
> BTW a `make run` does have the issue you described.

Not sure .. but since

- https://github.com/searxng/searxng/pull/2517

has been merged a `make run` is not blocked by 4 or 5 queries .. I need to repeat round about 15-20 times the same query in a few seconds to get blocked .. I'm not sure if this is causally related, but it is at least noticeable in my test scenarios that google blocks less than without the patch.

**Comment by unixfox** [comment]
> > BTW a `make run` does have the issue you described.
> 
> Not sure .. but since
> 
>     * [[fix] engine & network issues / documentation and type annotations #2517](https://github.com/searxng/searxng/pull/2517)
> 
> 
> has been merged a `make run` is not blocked by 4 or 5 queries .. I need to repeat round about 15-20 times the same query in a few seconds to get blocked .. I'm not sure if this is causally related, but it is at least noticeable in my test scenarios that google blocks less than without the patch.

No it doesn't I did test. I don't think the signature of the HTTP client changed (TLS fingerprint, HTTP2 fingerprint and more). So this won't help in solving the blockage unfortunately.

**Comment by unixfox** [comment]
@return42 for some strange reasons, Google doesn't like that we send the `gl` query string located in https://github.com/searxng/searxng/blob/master/searx/engines/google.py#L215

If I comment it then I do not get any rate limit error anymore that's odd.

-------------
EDIT:

Want to also point out that I've been starting to use my new project that try to replicate as much as possible a Chrome browser when sending requests: https://github.com/unixfox/gotlsproxy

**Comment by return42** [comment]
> Google doesn't like that we send the `gl` .. If I comment it then I do not get any rate limit error anymore that's odd.

Thanks for pointing out :+1: / FYI the gl argument is described here:

https://developers.google.com/custom-search/docs/xml_results#glsp

But I have the impression that this documentation is outdated (at least for google's WEB search).

IDK if it is any longer mandatory for Google News:

https://github.com/searxng/searxng/blob/e8706fb738da9feb21e596f403dddb40e69c8a7b/searx/engines/google.py#L204-L215

But back to Google-WEB:  when I select UI language English and Region Germany:

![image](https://github.com/searxng/searxng/assets/554536/fda2efba-9e55-490a-b415-75edb34cd6af)

Then I see this arguments are now combined in the hl argument ..

![image](https://github.com/searxng/searxng/assets/554536/82c4ae19-e6e2-4239-b5e5-7ee0d2759337)

It seems to me, that this is the point where the interface has been changed.  To remind 'hl' is documented here:

https://developers.google.com/custom-search/docs/xml_results#hlsp

https://github.com/searxng/searxng/blob/e8706fb738da9feb21e596f403dddb40e69c8a7b/searx/engines/google.py#L166-L175

In the past there was only the UI language in the hl value but nowadays it seems a combination of the UI language and the "search region" is mixed in this argument.

I don't know if I'm right with my assessment: I'm very surprised that google is starting to mix the parameters of the UI with the parameters of the search index.  At Microsoft (bing) I have often noticed that they mix such thematically different parameters in one argumen.  At google, everything was always nicely separated until now?

So far I have only looked at Google-WEB, the analysis would still have to be extended to other services such as Google-News and Google-Video ... possibly Google is currently rolling out a modified API, which also affects some the other services (Except: most often google-scolar is independent from the APIs of the other google services).

**Comment by return42** [comment]
> It appears that Google is now trying to block SearXNG instances

After the analysis I don't think so any longer / I think ...

- https://github.com/searxng/searxng/pull/2521

@unixfox (and other who follow this thread) can you please test the PR .. since the error pattern currently still seems to depend on the location of an IP, among other things, it would be good if we could get many participants to test the PR.

**Comment by unixfox** [comment]
> @unixfox (and other who follow this thread) can you please test the PR .. since the error pattern currently still seems to depend on the location of an IP, among other things, it would be good if we could get many participants to test the PR.

I have already implemented the change in my instance: https://searx.be and everything is working again now!

**Comment by return42** [comment]
> I have already implemented the change in my instance: https://searx.be/ and everything is working again now!

Thanks a lot for your support .. I close this issue now / if you think different please reopen and leaf a comment .. thanks again :+1:

**Comment by unixfox** [comment]
I prefer to keep it open until we are really sure it's fixed for at least 3/4 of the up to date SearXNG instances and for at least week.

Let's not close issues too quickly please :). This is an ongoing issue.

**Comment by unixfox** [comment]
Now finally closing this issue a bit earlier, 99% of the up-to-date instances have Google working again.

Now 55 out of 93 public instances have Google working again.
