### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by zorro37000** [searxng/searxng#2516]
**YES**  Google is actively blocking SearXNG instances - SearxEngineTooManyRequestsException: Too many requests #2515 
see also https://github.com/searxng/searxng/issues/2515
version 2023.6.23+2e4a43513
**BUT version 2023.6.24+257e8f4e seems to fix this issue** 

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 95
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)
  * 
Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/issues/2515
