### ISSUE TITLE
Google (and Startpage) search doesn't return any result

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2520]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2023.6.23 and 2023.6.25
**How did you install SearXNG?**
Almost all the public instances running the latest two versions
**What happened?**
Searching something with Google and Startpage returns the message: "Sorry!we didn't find any results. Please use another query or search in more categories"
I don't know if it's somehow related to #2515

**Comment by unixfox** [comment]
are you using a locally installed instance?

**Comment by unixfox** [comment]
which instance did you try?

**Comment by ghost** [comment]
I tried at least the first 10 instances in searx.me based on 2023.6.23 or 2023.6.25

**Comment by Midou36O** [comment]
Can confirm, our [instance](https://search.projectsegfau.lt) seem to not return anything, restarted 3 times, it works and after a few minutes it returns the same error.
Edit: this includes all 3 servers we're running.
Edit 2: Seems to indeed be related to #2515

**Comment by ghost** [comment]
FWIW I have just noted that paulgo.io is not affected.

**Comment by return42** [comment]
lets discuss google here 

- https://github.com/searxng/searxng/issues/2515

Startpage is a different issue .. its known that startparge blocks temporary / I haven't found a solution for this problem, thats why I disabled startpage on my engine (startpage results are from the google index).

----

> FWIW I have just noted that paulgo.io is not affected.

@Evhorizon: see comment from @unixfox :

- https://github.com/searxng/searxng/issues/2515#issuecomment-1605949861
