### ISSUE TITLE
[Engine request] crowdview (forum search engine)

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#2543]
**Working URL to the engine**

https://crowdview.ai/

**Why do you want to add this engine?**

it's nice, i like lots of forums in my search.

**Features of this engine**

Here's post from the creator: https://news.ycombinator.com/item?id=34507965

**How can SearXNG fetch the information from this engine?**

all you need to do to add support for this engine is add this (or similar) to the settings.yml:
  - name: crowdview
    engine: json_engine
    shortcut: cv
    categories: general
    paging: false
    search_url: https://crowdview-next-js.onrender.com/api/search-v3?query={query}
    results_query: results
    url_query: link
    title_query: title
    content_query: snippet
    disabled: true

**Applicable category of this engine**

general

**Comment by unixfox** [comment]
Feel free to create a pull request then

**Comment by Austin-Olacsi** [comment]
Ok, just made a pull request.

**Comment by Austin-Olacsi** [comment]
great, it was added. closing now.
