### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by northrup** [searxng/searxng#2550]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.4.21+98387e29

**How did you install SearXNG?**
Installed using the docker image, verified this happens on the `latest` tagged release.

**What happened?**
Any search returns an error for duckduckgo

**How To Reproduce**
launch the server and perform a search that should hit duckduckgo

**Expected behavior**
Searches are returned from duckduckgo

**Screenshots & Logs**
The only error I get is one generated from the SearX code

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('Request failed',)`
  * File name: `searx/engines/duckduckgo.py:101`
  * Function: `get_vqd`
  * Code: `raise SearxEngineAPIException('Request failed')`

**Comment by return42** [comment]
> Version: 2023.4.21+98387e29

Hi @northrup please update 

> Installed using the docker image, verified this happens on the `latest` tagged release.

Seems a while ago :-)

Related: https://github.com/searxng/searxng/commits/master/searx/engines/duckduckgo.py

**Comment by northrup** [comment]
🤦 @return42  - I had assumed a redeploy would pull a new version, it didn't. You were right - checking the hashes I had an old version cached.  🎉 thanks, this totally fixed it.

**Comment by viasux** [comment]
> > Version: 2023.4.21+98387e29
> 
> Hi @northrup please update
> 
> > Installed using the docker image, verified this happens on the `latest` tagged release.
> 
> Seems a while ago :-)
> 
> Related: https://github.com/searxng/searxng/commits/master/searx/engines/duckduckgo.py

I'm on version:
2023.4.8+71bd091f

and still getting this issue?

**Comment by df8819** [comment]
Bug/Error still persistent. I have the same docker installation (with ver. 2023.4.30+9967fbb7) and error as [northrup](https://github.com/northrup).

**Comment by return42** [comment]
@df8819 this is an old issue .. have you seen 

- https://github.com/searxng/searxng/issues/3276 and its fix ..
- https://github.com/searxng/searxng/pull/3291 

if you have ongoing issues, then it is a new problem, so  please open a new bug report with more details (I can't reproduce the issue / for me ddg works: see "reliability" 100% https://darmarit.org/searx/stats?engine=duckduckgo).
