### ISSUE TITLE
[Engine request] bt4g 

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2553]
**Working URL to the engine**

https://bt4gprx.com/
**Why do you want to add this engine?**

bt4g is a BitTorrent DHT search engine it has a better UI than [btdig](https://btdig.com), and it shows the number of Seeders and Leechers, No annoying google captchas, its faster in crawling new torrents
**Features of this engine**

fast, good UI, simple to use, showes the numbre of Seeders and Leechers
**How can SearXNG fetch the information from this engine?**

**Additional context**

**Comment by unixfox** [comment]
Very interesting, I've did some search on it and it seems to give the same results as btdigg.

There is an API in RSS: https://bt4gprx.com/search?q=windows%2011&page=rss. Only minor issue is that you don't know if there is a next page in the API.
