### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by DearLi111** [searxng/searxng#2554]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.7.14+4380fc2b

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 100
  * Parameters: `(None, None, 'www.google.com.hk')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Seems there are issues with `www.google.com.hk` .. @DearLi111 is the instance you use public / what is the URL?

**Comment by unixfox** [comment]
lack of replies.
reply and we will reopen if needed
