### ISSUE TITLE
Return number of result pages in the API

### ISSUE THREAD

**Issue by Lanhild** [searxng/searxng#2560]
**Is your feature request related to a problem? Please describe.**
Yes, the API should return the number of result pages it has for the current query.

**Describe the solution you'd like**
A new field in the API returning the number of pages

**Describe alternatives you've considered**
No possible alternatives currently.

**Additional context**
n/a

**Comment by return42** [comment]
The total number of pages is unknown to SearXNG / SearXNG is a meta-search engine and there is no pre-fetch of pages.  This is also the reason why we cant show the number of pages in the UI :-(

I'm sorry, there is no way to implement a solution for this feature request / I close this issue.

Nevertheless, if you have a clue or suggestions for a workaround, please post it here (we can reopen the issue).

**Comment by Lanhild** [comment]
> This is also the reason why we cant show the number of pages in the UI :-(

Can't the behavior of the `Next page` button be reproduced in the API? i.e. see my #2561 issue

![image](https://github.com/searxng/searxng/assets/73610779/be2c7859-36df-4272-9a6b-20508c7c944a)

**Comment by return42** [comment]
This is what I mean ...

try `&pageno=1` https://darmarit.org/searx/search?q=!mvw+Thaidigsmann&pageno=1

![image](https://github.com/searxng/searxng/assets/554536/913dbfae-61f8-43b0-88b5-3d0352301529)

and when you press on the "Next page" button the URL:

`&pageno=2` https://darmarit.org/searx/search?q=!mvw+Thaidigsmann&pageno=2

is requested and the result is ..

![image](https://github.com/searxng/searxng/assets/554536/2aeba2c4-a36e-48be-8a0c-19f949a88e74)

SearXNG does not know if there is a next page or how many pages total .. in the UI there is just a "Next page" button that opens the URL with an increment of the `&pageno=2` .. `&pageno=3` .. 

Or with other words, SearXNG's WEB-Client uses the same API ..

**Comment by Lanhild** [comment]
Alright, thanks for the insight
