### ISSUE TITLE
Support cursor based pagination in the API

### ISSUE THREAD

**Issue by Lanhild** [searxng/searxng#2561]
**Is your feature request related to a problem? Please describe.**
Yes, currently there are no ways in the API to get to the next page other than guessing if there is one or not.

**Describe the solution you'd like**
Supporting cursor based pagination

**Describe alternatives you've considered**
No possible alternatives currently

**Additional context**
n/a

**Comment by unixfox** [comment]
You can't in searxng either, this is because not all engines return if there is a next page available or not.

I feel like this won't be possible implement in the API.

**Comment by return42** [comment]
See my https://github.com/searxng/searxng/issues/2560#issuecomment-1642368507 .. I close this request / if you have suggestions, please post / thanks!
