### ISSUE TITLE
Bug: google images engine // KeyError: 'metadata' on empty result list

### ISSUE THREAD

**Issue by nordkorea** [searxng/searxng#2562]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.7.20+d901664c+dirty

**How did you install SearXNG?**
Cloned the repository locally, the only thing I changed is  
query = query + "site:site1.com OR site:site2.com OR site:site3.com" in google_images.py to get results from specific websites by default after the user input.

**What happened?**
No search results appear. That's all I got.

**Technical report**

Error
  * Error: KeyError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/google_images.py:99`
  * Function: `response`
  * Code: `for item in json_data["ischj"]["metadata"]:`

**Comment by return42** [comment]
what instance do you use?

**Comment by nordkorea** [comment]
> what instance do you use?

its my own modification of searxng, not a public instance, turns out it is working completely fine but the parsing error is most likely caused by the limited search results here in germany because google didnt return any results either

**Comment by return42** [comment]
In a `make run` (developer) instance the issue can be reproduced by a search term like `!goi site:site1.com OR site:site2.com OR site3.com foo`

```
WARNING searx.engines.google images   : ErrorContext('searx/engines/google_images.py', 98, 'for item in json_data["ischj"]["metadata"]:', 'KeyError', None, ()) False
ERROR   searx.engines.google images   : exception : 'metadata'
Traceback (most recent call last):
  File "/share/searxng/searx/search/processors/online.py", line 165, in search
    search_results = self._search_basic(query, params)
  File "/share/searxng/searx/search/processors/online.py", line 153, in _search_basic
    return self.engine.response(response)
  File "/share/searxng/searx/engines/google_images.py", line 98, in response
    for item in json_data["ischj"]["metadata"]:
KeyError: 'metadata'
```

**Comment by return42** [comment]
Issue had been fixed by:

- https://github.com/searxng/searxng/pull/2824
