### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by Kadmaan** [searxng/searxng#2585]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.7.29+8b4ba204b

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by return42** [comment]
Hi @Kadmaan this issue is known / qwant blocks your instance, see https://github.com/searxng/searxng/issues/2011#issuecomment-1556859070

- [Answer CAPTCHA from server’s IP](https://docs.searxng.org/admin/answer-captcha.html)
