### ISSUE TITLE
lib.rs: Rust libraries and applications

### ISSUE THREAD

**Issue by Juliaria08** [searxng/searxng#2600]
**Working URL to the engine**
`https://lib.rs/search?q=<request>`

**Why do you want to add this engine?**
It's about a open and free system to be able to see rust libraries and crates

**Features of this engine**
Doesn't require Javascript, I think it also doesn't track users.

**How can SearXNG fetch the information from this engine?**

**Applicable category of this engine**
science or general, but I think science (preffereably a new code category could be created for code search engines)

**Additional context**
Rust Crates package list

**Comment by return42** [comment]
The engine already exist in a XPath configuration (see below) .. the engine is disabled by default, but you can activate the engine in the preferences or -- much simpler -- you can use the [Search syntax](https://docs.searxng.org/user/search-syntax.html), try by example `!lrs foo`.

https://github.com/searxng/searxng/blob/5fcc75185620b80ec97d095f6bf88280e0e4d7f8/searx/settings.yml#L1872-L1887
