### ISSUE TITLE
Change Logos via GUI

### ISSUE THREAD

**Issue by freddydopfel** [searxng/searxng#2602]
**Is your feature request related to a problem? Please describe.**
For those running a docker container it is extremely difficult to change the logo or theme, especially if the user does not have access to docker config or the file structure

**Describe the solution you'd like**
A simple option to upload a png file to replace the Searxng logo (available in the GUI)

**Describe alternatives you've considered**
Since I am running on synology, I cannot access docker config and am unable to see the file system to replace the png of the logo

**Additional context**

**Comment by return42** [comment]
Sorry, but we do not plan to implement a admin UI.

**Comment by return42** [comment]
Sorry, but we do not plan to implement a admin UI.
