### ISSUE TITLE
Timeout issues: duckduckgo and bing engine

### ISSUE THREAD

**Issue by manzing** [searxng/searxng#2604]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.8.6+64100db90

**How did you install SearXNG?**

Searxng-docker
**What happened?**

request timeout with duckduckgo and same thing for bing
**How To Reproduce**

Any researches on theses engines.
**Expected behavior**

Some results, as Google and Qwant results are fine.
**Screenshots & Logs**

```
 File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng    |     return request('get', url, **kwargs)
searxng    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng    |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng    |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng    | httpx.TimeoutException: Timeout
searxng    | 2023-08-07 07:24:00,137 WARNING:searx.tools.config: missing config file: /etc/searxng/limiter.toml
searxng    | 2023-08-07 07:24:03,166 ERROR:searx.engines.bing: engine timeout
searxng    | 2023-08-07 07:24:03,252 WARNING:searx.engines.bing: ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'www.bing.com')) False
searxng    | 2023-08-07 07:24:03,266 ERROR:searx.engines.bing: HTTP requests timeout (search duration : 3.100270776078105 s, timeout: 3.0 s) : ConnectTimeout
```
**Additional context**

I tried to update to latest image but issue remains the same. Ping on these addresses from the server is OK.
A reverse proxy (nginx) is used.
**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 50
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = get(query_url, headers=headers)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 50
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = get(query_url, headers=headers)`

**Comment by return42** [comment]
Bing & DDG temporary block SearXNG instances.

> Ping on these addresses from the server is OK.

Ping says nothing, its ICMP not TCP and the ping echo can be activated/deactivated.  Further more it does not say anything about a application level.

Use your instance IP as a proxy for your WEB browser to see whats going on ..  / see https://docs.searxng.org/admin/answer-captcha.html 

most often you see a captcha, in case of ddg you will see your browser runs into timeout / not to response is the way ddg blocks IPs.

**Comment by manzing** [comment]
Well, I am aware that ICMP is not TCP, that was to demonstrate that the problem is not a DNS resolution issue.
My server also act as a proxy and access to the 2 search engines is fine, and no captcha asked, the answer is elsewhere.

I can also access directly to the bing and DDG pages from server's command line using Lynx, no problem.
Only Searxng is affected.

I understand there are many issues like this one that can be solved with a simple captcha, but I wouldn't have open an issue whitout trying those things and read other issues first.

**Comment by return42** [comment]
All other (or at least most) of SearXNG do work? / Is your instance public (what URL)?

**Comment by manzing** [comment]
Thanks for reopening @return42 
My instance is private, I mean I have a public address but I don't want to disclose it here (very low resources). I can send it to you privately.
I just tried again and now Bing seems to work despite I have not made any configuration change, except maybe rerun container.
So far, Google, Brave, Qwant and now Bing work, maybe some others.
Still no answer from duckduckgo, but the issue is less annoying now Bing is OK.
I have a v2ray proxy on the server and can search with DDG on my browser through the proxy without any issue or captcha.

A few minutes later, Bing is down again. A timeout too short, if I raise it to 5 seconds Bing is OK, but that seems a little too much waiting.

**Comment by return42** [comment]
>  I mean I have a public address but I don't want to disclose it here (very low resources).

No problem .. its OK.

> A few minutes later, Bing is down again. A timeout too short, if I raise it to 5 seconds Bing is OK, but that seems a little too much waiting.

Depends on your network connection .. may you also need to increment the timeout of ddg.

I don't have a clue, but it is noticeable that all your engines often run into timeouts ... I think the connection to the net is slow for some reasons.

**Comment by manzing** [comment]
Connection is 100 MBits, it should be enough as for now I am the only user.
But obviously, if I set to 5 or 6 seconds, I can retrieve results from Bing and Brave and wikis.
For duckDuckGo, even at 10 seconds I still have nothing though.
Still, I cannot understand why Google and Qwant are really faster than the others.

![SearXNG](https://github.com/searxng/searxng/assets/2737265/70768036-2fac-48f9-a3c4-1d8d6e5629e7)

**Comment by return42** [comment]
@manzing I'm going to close this issue / the timeout you have are related to you network connectivity  .. about the ddg timeouts please have a look at 

- https://github.com/searxng/searxng/issues/2666#issuecomment-1707121815

**Comment by manzing** [comment]
I understand, I just updated to the latest release to look for improvement, but sadly the issue is still the very same.

```
Exception | httpx.ConnectTimeout | Pourcentage | 65

NoneNonelite.duckduckgo.com
searx/engines/duckduckgo.py:97
get_vqd
res = get(query_url)

Exception | httpx.TimeoutException | Pourcentage | 35

searx/engines/duckduckgo.py:97
get_vqd
res = get(query_url)

```
I will follow other issue threads hoping to find a solution.
