### ISSUE TITLE
New engine: Tagesschau

### ISSUE THREAD

**Issue by Bnyro** [searxng/searxng#2609]
**Working URL to the engine**
* https://www.tagesschau.de/api2u/

**Features of this engine**
* provides recent news in German

**How can SearXNG fetch the information from this engine?**
* https://www.tagesschau.de/api2u/search?searchText=test
* https://github.com/AndreasFischer1985/tagesschau-api
* the implementation is not the issue, it's rather whether it'd be accepted

**Applicable category of this engine**
* news, general

**Additional context**
There are two concerns/questions from my side regarding adding it:
* According to https://github.com/AndreasFischer1985/tagesschau-api, we're not allowed to run more than 60 api requests per hour (though there's no rate-limiting, so it wouldn't be a problem to fetch more), so it's only some legal stuff about which I'm not sure
* It only provides results in German: I don't know whether engines, that only support a single language other than English are fine to become added

**Comment by return42** [comment]
> so it's only some legal stuff about which I'm not sure

From programmers point of view there is no (legal) issue .. depends on the government where the maintainer do host their SearXNG instances.

> It only provides results in German: I don't know whether engines, that only support a single language other than English are fine to become added

Its OK .. not all engines do support all languages on planet earth ;-) 

By example, we have [MediathekViewWeb](https://github.com/searxng/searxng/blob/master/searx/engines/mediathekviewweb.py) .. you can try [`!mvw tagesschau`](https://darmarit.org/searx/search?q=%21mvw+tagesschau)

**Comment by Bnyro** [comment]
Okay cool, thanks!
I'll open a PR for it then in the next days :)

PS: Great to see MediatheViewWeb being supported, I actually already have been using it for some years, but really didn't expect it to be available here as well!
