### ISSUE TITLE
Make it display the full url parameters including the query, not only site.tld/search

### ISSUE THREAD

**Issue by arda618** [searxng/searxng#2623]
**Is your feature request related to a problem? Please describe.**
I have tried many things to make it display the full URL but it does not.

**Describe the solution you'd like**
Being able to configure the source code or preferences to display the full url parameters

**Additional context**
All I want is to be able to see the results the way I do in other search engines such as Google.com

**Comment by return42** [comment]
Next time please open a question in our Q&A discussion / BTW your question has been already asked a few days ago

- https://github.com/searxng/searxng/discussions/2612
