### ISSUE TITLE
Adding option to setup NGINX/Apache in Installation script

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2630]
**Is your feature request related to a problem? Please describe.**
I didn't have NGINX server when installing, hence I would prefer it being automatically installed

**Describe the solution you'd like**
Adding it as **option** to Installation script, only if NGINX **isn't** installed, so that servers don't accidentally get messed up

**Comment by return42** [comment]
Please read the docs before posting .. there is already a script https://docs.searxng.org/admin/installation-nginx.html

BTW: when you installed by `sudo -H ./utils/searxng.sh install all` an existing NGINX or Apache installation is already checked an you are informed if non of booth is installed.

https://github.com/searxng/searxng/blob/01c0ec5d19498f33bbdc3a214167ebe007e9b26c/utils/searxng.sh#L362-L377

**Comment by ghost** [comment]
I know and, in fact, I used it. 
But in my case it wasn't working - it was giving me a `Bad Gateway`.
However, I can't reproducing it now, and honestly I'm not sure why it happened.
Sorry for wasting your time.
