### ISSUE TITLE
Add change proposal issue template

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2632]
**Is your feature request related to a problem? Please describe.**
I would like there to be a template to propose a change and discuss it with maintainers before implementing. This way, contributors don't need to waste time if their pull request won't be merged

**Describe the solution you'd like**
Adding a new template for `change proposal`

**Example**
I want to know maintainers' opinions on change to documentation proposed by me, before I make them and create a pull request

**Comment by return42** [comment]
For this we have a "ideas" category in the discussions --> https://github.com/searxng/searxng/discussions/categories/ideas

**Comment by ghost** [comment]
Sorry, I'm new to Github's collaboration features
