### ISSUE TITLE
Refresh engine metrics

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#2635]
**Is your feature request related to a problem? Please describe.**
When testing timeout and reliability of engines, I have to constantly refresh /preferences and click go to engines tab.

**Describe the solution you'd like**
Keep information on which tab in preferences opened (e.g. /preferences/engines, /preferences?tab=engines, /preferences#engines) 

**Describe alternatives you've considered**
Add a button to refresh the stats on the same page

**Comment by return42** [comment]
Not planned .. to much work for less benefit and we do not want to split up this page in multiple sites or add JS stuff to toggle CSS (tabs are controlled by CS).

--- 

I have one request, please don't flood us with all your ideas that come to mind when you first use it ... work with SearXNG for a while and then if you discover any lasting problems, please report them.

Thank you for your understanding
