### ISSUE TITLE
Bug: youtube engine [updated]

### ISSUE THREAD

**Issue by freeload101** [searxng/searxng#2647]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.8.14+7052a1a7c

**How did you install SearXNG?**
docker at home and on my personal site if keep defualts it works fine ... 
 

but if i use ```youtube_api``` I can't get it to be stable at all 

**What happened?**
youtube sometimes worked for 'monkey' or 'goomba' or 'music video' but it's almost like anything with maybe DRM it fails with a 'KeyError' terms like 'tesla' or 'newell' but yet it worked for 'samsung watch'  

🤷

**How To Reproduce**
seatch for anything ```!yt``` basicly ... 

**Expected behavior**
at one point in time ```!yt newell brands``` gave me results WITH working embeded player .. sometimes the embed player does not work .. 🤷

**Screenshots & Logs**
I have no idea where the logs are for the docker.. I can't find them for the life of me

* working API key now had to **enable youtube in the project again !** but still having issues with random searches ... it's not a throttle thing I have no idea ... 

![image](https://github.com/searxng/searxng/assets/4307863/f8db6ba3-739c-4b83-88f8-95af3afe89ce)

**Additional context**
I also tried wiping all the keys and createing a new ones had forgot to enable youtube API on the project ... disabled by default  

**Technical report**

Error

Exception | KeyError | Percentage | 65
-- | -- | -- | --
searx/engines/youtube_api.py:58
response
videoid = result['id']['videoId']

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by return42** [comment]
> if keep defaults it works fine ... but if I use ```youtube_api``` I can't get it to be stable at all 

Do you have a ``api_key``? .. since ```youtube_api``` needs a ``api_key`` its not tested very well (and the implementation is from 2015).

**Comment by freeload101** [comment]
Ok 2015 wow ... OK so just maybe note that in the settings xml and do a pull request ? I also can take a look at it if you think it would be useful not sure the difference between ```youtube_noapi``` and ```youtube_api```  at least with one user ```youtube_noapi```  seems fine ? or is it deprecated  / covered by other defualt video searches now days. I'm not sure where to find logs outside of hacking the py script ?

API key works fine it's just almost random filtering/blocking throttling ? home IP (24.216.55.197) Charter Communications but my VPS is MONTREAL,QC  162.250.190.93 ( servarica.com )  the servarica IP seems more feniky but still both broken.

![image](https://github.com/searxng/searxng/assets/4307863/bb40daa1-4050-4208-b1c3-084a48b2cfe7)

**Comment by return42** [comment]
> not sure the difference between youtube_noapi and youtube_api at least with one user youtube_noapi seems fine ?

youtube_api and youtube_noapi are completely different implementations, the API returns JSON while the noapi scraps a HTML result.

> OK so just maybe note that in the settings xml and do a pull request ?  ... I also can take a look at it if you think it would be useful 

As you prefer / a PR for one or the other is welcome :+1: 

> covered by other default video searches now days.

Beside the both youtube engines, SearXNG has engines for [invidious](https://github.com/searxng/searxng/blob/master/searx/engines/invidious.py) and [piped](https://docs.searxng.org/dev/engines/online/piped.html) ..

But if someone see some features in youtube_api missed in piped or invidious it might be useful to have a robust youtube_api implementation.

**Comment by freeload101** [comment]
I don't know enough about youtube API I know I used it with Kodi and parsing HTML is always fun especlay with moving target like youtube. ```yt-dlp``` and ```youtube-dl``` both update/break all the time but if somebody needs something in the SearXNG UI please let me know. I'm no Kodi parse master and can poke with the existing code.  I been known to make ummm ..... API's for stuff :) Let me know if you have a personal donate link or have a link for me to donate in SearXNG's name

**Comment by return42** [comment]
> Let me know if you have a personal donate link or have a link for me to donate in SearXNG's name

Thank you very much, that is very kind of you :+1: / We currently still have enough donations to run our infrastructure, so our fundraising campaign is over for now :-)
