### ISSUE TITLE
Blocked after a minute?

### ISSUE THREAD

**Issue by TechMitten** [searxng/searxng#2649]
### Discussed in https://github.com/searxng/searx-instances/discussions/385

<div type='discussions-op-text'>

<sup>Originally posted by **techcow2** August 14, 2023</sup>
I'm having trouble with my server and my instance will be down until further notice.</div>

I was having some server trouble so I had to reinstall my instance. Minutes if not seconds after launching my instance I noticed Google was blocked. Then came DuckDuckGo. I had no problems up until now. What could this be?

----

Related: https://github.com/searxng/searx-instances/issues/387

**Comment by return42** [comment]
> What could this be?

IDK ..

> I noticed Google was blocked. Then came DuckDuckGo.

Having DDG timeouts from time to time is not unusual, your engine stats arre looking quite normal:

![image](https://github.com/searxng/searx-instances/assets/554536/9e9e2683-c388-4738-8105-9807ab8b4559)

Except the google engine, according to my experience the google engine should never block.

Use your instance IP as a proxy for your WEB browser to see whats going on .. / see https://docs.searxng.org/admin/answer-captcha.html

**Comment by unixfox** [comment]
Closing as it needs to be in a dedicated issue and there are already dedicated ones for each engine.
