### ISSUE TITLE
Random Search Queries to Prevent Tracking

### ISSUE THREAD

**Issue by jboucher614** [searxng/searxng#2654]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like for SearXNG to perform, in the background, a chosen number of random searches per hour. The search query could be random words and/or pulled from an external website's list of frequent searches at the time. 

**Describe alternatives you've considered**
- writing a second program to perform this
- creating a browser extension to do this

**Additional context**
Many instances have just one user. Because of this, search engines can use IP to identify that individual or individuals. It has been recommended to have instances be shared with others to prevent this form of identification: https://www.privacyguides.org/en/search-engines/

AdNauseam is a browser extension which clicks on advertisements in the background as a form of data obfuscation. This pollutes the data used by advertisers to form a profile of you.

I propose that SearXNG have an option similar to AdNauseam to allow one user to use an instance at a single IP without the search engines being able to build an accurate profile of that user. Users would specify a range for the number of searches per hour (with a hard-coded maximum to prevent abuse). SearXNG would choose a random number within the specified interval each hour and perform that number of searches at random times within that hour. Users would also specify if search queries should come from random word generation and/or a list of popular search terms pulled from the internet at random intervals. 

In doing so, the individual user's searches would blend into the background noise of fake searches, similarly to how having other users would blend search data together.

**Comment by return42** [comment]
> In doing so, the individual user's searches would blend into the background noise of fake searches, similarly to how having other users would blend search data together.

A public instance has many users and bots :-)  .. BTW; tracking is most often based on JS and cookies .. which, unlike a WEB browser, a SearXNG instance does not process.
