### ISSUE TITLE
Add PriEco search engine

### ISSUE THREAD

**Issue by xbdmHQ** [searxng/searxng#2668]
**Working URL to the engine**
https://search.jojoyou.org/

**Why do you want to add this engine?**

PriEco is a new search engine powered by Google, Bing and Mojeek. It is focused on Privacy, Security and Ecology.

Has its own INDEX.

**Features of this engine**
Eco-friendly
Secure
Private
Open Source
Self-hostable

**How can SearXNG fetch the information from this engine?**
Looks like there's no API, probably just scrape it like the rest of the engines.

**Applicable category of this engine**
general, images, map, news, and videos.

**Comment by return42** [comment]
Related: https://codeberg.org/JojoYou

> Has its own INDEX.

sure? .. from where do you have this info?  // as you titled, it has not its own index

> search engine powered by Google, Bing and Mojeek

**Comment by Bnyro** [comment]
The engine pretty much looks like a metasearch engine like searxng is one, wouldn't it make more sense if we just used Mojeek, Bing and Google directly?

Nevertheless, it might be useful to fix some issues related to these engines (#2666, #2641), the code for scraping the engines can be found [here](https://codeberg.org/JojoYou/PriEco/src/commit/1ff1fcc759478aae5021fe5ea617cf0226a9c136/Controller/functions/engines/web) (didn't look into it yet).

**Comment by JojoYou** [comment]
Hello, PriEco founder here.
PriEco has own index but we are still building it.
There is a version which uses only our results and search suggestions: https://search.jojoyou.org/pri (still not very good results)

I don't want to add PriEco to Searxng because the search engine is still small and Searxng traffic would do significant harm to it.
