### ISSUE TITLE
[bug] missing "Google" results in other languages?

### ISSUE THREAD

**Issue by throwaway242685** [searxng/searxng#2672]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG.**

2023.8.22+4b4264457

**How did you install SearXNG?**

they're public instances.

**What happened?**

Google results are missing in languages other than English.

**How To Reproduce.**

search something like:

`:es !go site:reddit.com argentina`

... nothing will show up.

**Expected behavior.**

you should get results. 

**Screenshots & Logs.**
| Spanish | English |
| --- | --- |
|  ![Screenshot_2023-08-23_10-34-57.png](https://github.com/searxng/searxng/assets/85243826/3a4b57ca-fbdc-4f47-bd21-5c6b8d52516c) | ![Screenshot_2023-08-23_10-34-44.png](https://github.com/searxng/searxng/assets/85243826/a37c29dd-828f-4f69-b90a-a78bba1c23be) |

**Additional context.**
.

**Comment by return42** [comment]
When I go to google.es and do an extended search ..

![image](https://github.com/searxng/searxng/assets/554536/52206e13-17aa-4bfb-a34c-04575abdb522)

google.es returns no results:

![image](https://github.com/searxng/searxng/assets/554536/e6591b8d-e1ef-4948-9329-4fb72c2ef229)
