### ISSUE TITLE
Alignment: wide

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng#2677]
**Is your feature request related to a problem? Please describe.**
Not a problem - but left/center align both don't look right to me ... if results were "wider" and filled more of the screen it would be more pleasing to the eye.

**Describe the solution you'd like**
Some way to make results "wider"

**Describe alternatives you've considered**
Userstyle from 2017 that didn't work

**Comment by unixfox** [comment]
probably duplicate of https://github.com/searxng/searxng/issues/1169

**Comment by privacyguy123** [comment]
make this make sense to me - Im currently messing about in Stylus using that Github Wide code as a guide and I can get everything else to move and change shape except the width of the search results and info box :S

**Comment by dalf** [comment]
> Im currently messing about in Stylus using that Github Wide code

Can you share your code? This may help to start the work on that subject.

**Comment by return42** [comment]
I close this issue in lack of feedback .. BTW its more or less duplicate of https://github.com/searxng/searxng/issues/1169
