### ISSUE TITLE
[ru-RU] Correct the Russian language in the settings

### ISSUE THREAD

**Issue by MadTooth** [searxng/searxng#268]
"(Учтите, что указанные пользовательские настройки в URL адресе, могут привести к их утечке на посещаемых сайтах из поисковой выдачи.)"

![Screenshot_20210823-235407_FOSS_Browser](https://user-images.githubusercontent.com/30464341/130487914-38bee4f8-d470-4973-96af-04df287e7d24.png)

**Comment by return42** [comment]
FYI: we are looking for translators, if you want, you can contribute your translations at https://weblate.bubu1.eu/projects/searxng/searxng/ru/ thanks!

**Comment by return42** [comment]
@MadTooth thanks a lot for your contribution on weblate / FYI: I confirmed your suggestions and a update translation [job](https://github.com/searxng/searxng/actions/workflows/translations-update.yml) will run next weekend.

**Comment by MadTooth** [comment]
I translated everything I could, changed the old translation, maybe my translation is not the most accurate

**Comment by return42** [comment]
@MadTooth just for your Information .. the update job has pulled your translations from weblate, again: thanks a lot for your contribution / [searx/translations/ru/LC_MESSAGES/messages.po](https://github.com/searxng/searxng/pull/274/files#diff-975f193b15869730fdd7c847c71a82708a45ed2df29b1fbfd079bf2b0c10c8ea)
