### ISSUE TITLE
Bug: wikicommons.images

### ISSUE THREAD

**Issue by bonswouar** [searxng/searxng#2707]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2023.9.2+4f8895c6d

**How did you install SearXNG?**
Docker from official wiki

**What happened?**
I always get 0 result with wikicommons images (but no error)

**How To Reproduce**
`!wc birds`

**Expected behavior**
Should return results

**Screenshots & Logs**
```
searxng    | DEBUG   searx.engines.wikicommons.imag: HTTP Accept-Language:
searxng    | DEBUG   searx.search                  : actual_timeout=3.0 (default_timeout=3.0, ?timeout_limit=None, max_request_timeout=None)
searxng    | DEBUG   searx.network.wikicommons.imag: HTTP Request: GET https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=search&gsrnamespace=6&gsrprop=snippet&prop=info%7Cimageinfo&iiprop=url%7Csize%7Cmime&iiurlheight=180&uselang=en&gsrlimit=10&gsroffset=0&gsrsearch=filetype%253Abitmap%257Cdrawing+birds "HTTP/2 200 OK" (application/json; charset=utf-8)
```

**Additional context**
It seems to be because of https://github.com/searxng/searxng/blob/master/searx/engines/wikicommons.py#L43
For some reason it gets url encoded twice, resulting in `filetype%253Abitmap%257Cdrawing+birds` instead of `filetype%3Abitmap%7Cdrawing+birds` (see logs)

**Comment by return42** [comment]
@bonswouar thanks for early testing and your deep analysis, which was very helpful to me :+1: .. seems we should better [not url-quote `:` and `|`](https://github.com/searxng/searxng/pull/2708/files) --> I send PR #2708 to fix this issue, if you would have a look ..
