### ISSUE TITLE
Bug: archive is engine

### ISSUE THREAD

**Issue by vachan-maker** [searxng/searxng#271]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:99`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Checker
  * simple: `searx.exceptions.SearxEngineTooManyRequestsException `,

**Comment by unixfox** [comment]
Unfortunately we can't do much about this, the engine is just blocking Searx due to the huge amount of requests done.

Please use another searx instance on https://searx.space or run your own locally.

(Issue can be closed)

**Comment by dalf** [comment]
I confirm it works on my laptop


And clearly not on public instances (see engines tab of searx.space):

![image](https://user-images.githubusercontent.com/1594191/131114397-830683e2-7de2-404f-84e3-6da65efe68b5.png)
