### ISSUE TITLE
Bug: stackoverflow engine

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng#2714]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.9.5+4fb26cd96

**How did you install SearXNG?**
Official searxng-docker 

**What happened?**
Search showing errors.

**How To Reproduce**
Include ```askubuntu stackoverflow & superuser``` in searches

**Expected behavior**
Searches used to work.

**Screenshots & Logs**

**Additional context**
API changed or something?

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('400', 'Bad Request', 'api.stackexchange.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
@privacyguy123 I can't reproduce your issue, all three engines work as expected --> [!st !ubuntu !superuser foo](https://darmarit.org/searx/search?q=%21st+%21ubuntu+%21superuser+foo)

Is your instance public .. can we test your instance?

**Comment by privacyguy123** [comment]
> @privacyguy123 I can't reproduce your issue, all three engines work as expected --> [!st !ubuntu !superuser foo](https://darmarit.org/searx/search?q=%21st+%21ubuntu+%21superuser+foo)
> 
> Is your instance public .. can we test your instance?

Oddly it's self hosted ... what could this mean? Too many requests back to back?

**Comment by return42** [comment]
> Too many requests back to back?

not sure what you mean.

**Comment by privacyguy123** [comment]
> > Too many requests back to back?
> 
> not sure what you mean.

Getting timed out from searching many times with no pauses in between

**Comment by privacyguy123** [comment]
This seems to be back again without explanation, along with some odd perhaps FireFox related bugs with saving the preferences
