### ISSUE TITLE
[FEATURE REQUEST] use the left and right arrow keys to switch between images when the image preview is open

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#2720]
**Is your feature request related to a problem? Please describe.**
i want to use the left and right arrow keys to switch between images when the image preview is open.

**Describe the solution you'd like**
this is a habit of mine, something i have always done, and it works in almost all other search engines.

**Describe alternatives you've considered**

**Additional context**
i've tried to hunt down the source, and i found this file:
/searxng/searx/static/themes/simple/js/searxng.min.js

and in it, i found result-detail-previous and result-detail-next

i stopped here because i do not know javascript... and i only think i am looking at the right thing...

**Comment by BernieHuang2008** [comment]
You know that `.min.js` is a sort of sign of compiled js code, so you may need to find the function in the source code.

**Comment by Austin-Olacsi** [comment]
thanks... i think the source is

searxng/searx/static/themes/simple/src/js/main/results.js

then i can compile by running make themes.all
following this guide https://docs.searxng.org/dev/quickstart.html

again still not completely sure i'm looking at the right file...

**Comment by BernieHuang2008** [comment]
I think what you are finding is in `keyboard.js` in the same dictionary of your `results.js`
https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/src/js/main/keyboard.js#L58
you can have a look of this 👆

And if you want to add your new feature, you can ref for L165
https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/src/js/main/keyboard.js#L165

ps：if you are difficult in js, maybe I can help you with it at weekends.

**Comment by bonswouar** [comment]
PR is submitted, although I didn't see your last comment @BernieHuang2008 , I actually didn't include the event listener in the "hotkeys" part as they need to enable "Vim-like hotkeys" (and I believe this feature is not)

**Comment by dalf** [comment]
Currently, you can use `j` and `k` to navigate between the images. `Esc` close the detail, but... it is going to appear again the next time you press on `j` or `k` because of this line:

https://github.com/searxng/searxng/blob/019bd97f4b3bcd875feef760b7c1c3e6f00ad942/searx/static/themes/simple/src/js/main/keyboard.js#L53

called from

https://github.com/searxng/searxng/blob/019bd97f4b3bcd875feef760b7c1c3e6f00ad942/searx/static/themes/simple/src/js/main/keyboard.js#L239
