### ISSUE TITLE
Allow to easily set up search to use 2 languages

### ISSUE THREAD

**Issue by ChuckBartowski91** [searxng/searxng#2734]
**Is your feature request related to a problem? Please describe.**
Hello, when I search using all languages I get more results in the language from the country of the instances I'm using, so I would like to use only english and my language.

**Describe the solution you'd like**
Set 2 languages into preferences or allow to use multiple language strings (example :hu:en)

**Describe alternatives you've considered**
I think that I cannot use custom settings.yml with the search engine in other langauge workaround since I'm not hosting the instance, correct me if I'm wrong.
I know I can use an instance from my country, but I would like to use one from another.

**Comment by return42** [comment]
Sorry, that is not possible.
