### ISSUE TITLE
Access Denied from search engines

### ISSUE THREAD

**Issue by lvkaszus** [searxng/searxng#2739]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Repository: https:/github.com/searxng/searxng
Branch: master
Version: 2023.9.9+8e45ac42

**How did you install SearXNG?**
SearXNG Install Script https://docs.searxng.org/admin/installation-scripts.html

**What happened?**
Google, DuckDuckGo and Brave stopped working - Getting HTTP 403 error while submitting search query in SearXNG. Everything was working previous day (maybe Google blocked my server IP?)

**How To Reproduce**
Just go to my instance https://search.lvkaszus.pl and type something into search bar. On the right side you will be able to see the HTTP 403 error coming out of these search engines. It happened not only with me, but also with others who host SearXNG - just check on searx.space list

**Expected behavior**
Everything was working last night, today I can't search pretty much everything because core search engines won't work anymore in SearXNG instance(s).

**Screenshots & Logs**
![image](https://github.com/searxng/searxng/assets/121642236/bb0e067c-3192-4d6e-8c93-62b11927ffb1)
![image](https://github.com/searxng/searxng/assets/121642236/eb2a304d-0ec7-47e6-9bc7-f63aa3fd9096)

**Additional context**
Tried to change my server IPv4 and IPv6 address but with no luck, and the problem is also on the other SearXNG instances like searx.baczek.me or search.fawkesguy.com

searx.baczek.me instance - same problem as mine:
![image](https://github.com/searxng/searxng/assets/121642236/84218dcd-1f6c-48b4-bb35-3ddd40a65c84)

and search.fawkesguy.com - also same problem:
![image](https://github.com/searxng/searxng/assets/121642236/88afcd71-2841-4ca8-b733-0564450a4320)

**Comment by Bnyro** [comment]
Brave and DDG: duplicate of #2666 and #2616

**Comment by ZhenyaPav** [comment]
I'm also having issues with Google, but ddg works fine

**Comment by ZhenyaPav** [comment]
Google works fine for about a minute after restarting searx, but then stops working once again. I don't think i've been flagged by google - if I use the server as proxy and try to use google.com, it works fine.

**Comment by Michael-Sebero** [comment]
I can confirm that the search function is down on my side too, it's been down a week for me.

**Comment by return42** [comment]
Please let us open (or contribute to) issues dedicated to an engine / we can not track issues over a mix of engines without ending in confusion and aberrations.

- https://github.com/searxng/searxng/issues/2616
- https://github.com/searxng/searxng/issues/2719
- https://github.com/searxng/searxng/issues/2641
- https://github.com/searxng/searxng/issues/2456#issuecomment-1618000053
- https://github.com/searxng/searxng/issues/1081#issuecomment-1488162918
- [Answer CAPTCHA from server’s IP](https://docs.searxng.org/admin/answer-captcha.html#answer-captcha-from-server-s-ip)
