### ISSUE TITLE
[Engine:Google Video] Safesearch is not considered when set to None

### ISSUE THREAD

**Issue by lemonadeforlife** [searxng/searxng#2762]
Brief description by @unixfox

For the Google video engine, if you set Safesearch to None in the preferences it seems like it's not considered by the search engine behind.

With a search like `!gov block porn`, on the second page or first one you get thumbnails blurred.

![image](https://github.com/searxng/searxng/assets/4016501/3e007d35-44f4-467e-9f52-98afc22b808c)

Example URL: https://paulgo.io/search?q=%21gov+block+porn&category_none=1&pageno=2&language=all&time_range=&safesearch=0&theme=simple

---------------

Original message:

**Is your feature request related to a problem? Please describe.**
Basically as the title says whenever you search for something NSFW or not even NSFW but in google video engine the video thumbnail gets blurred out.
![SearXNG google video blurred video thumbnail](https://i.imgur.com/h6wNFYf.png)

**Step to reproduce this issue**
!gov porn
!gov block porn
basically any nsfw related search on google video (!gov)

**Describe the solution you'd like**
without blur, video thumbnail of Google video search result

**Describe alternatives you've considered**
N/A   

**Additional context**
I don't know if this going to help or not, the only working parameters I have found is `&safe`.

`safe` parameter has 3 value: `on`, `off`, `images`(for blurring the images)
**Google Video url without blurred image:** https://www.google.com/search?q=%s&tbm=vid&safe=off

<Table>
<tr>
<th>
without `safe=off`: <img src="https://i.imgur.com/uYDL9bm.png" alt="youtube age restricted video with blurred video thumbnail">
</th>
<th>
with `safe=off`: <img src="https://i.imgur.com/FRJHjFx.png" alt="youtube age restricted video with video thumbnail">
</th>
</tr>
</Table>

**Comment by unixfox** [comment]
Did you try in the preferences (`/preferences`) setting `SafeSearch` to None?

**Comment by lemonadeforlife** [comment]
> Did you try in the preferences (`/preferences`) setting `SafeSearch` to None?

yeap

**Comment by unixfox** [comment]
I can't replicate your issue no blur here: https://paulgo.io/search?q=%21yt+How+to+block+porn+sites+without+any+software&language=all&time_range=&safesearch=0&theme=simple

Using youtube engine (not google videos, the video doesn't exist there!) and with SafeSearch to None.

![image](https://github.com/searxng/searxng/assets/4016501/e74d2f71-ccbc-47f5-a1eb-87e1e6faafdd)

**Comment by lemonadeforlife** [comment]
@unixfox I know. That's why I wrote [Engine: Google Video]. And that image is just a sample. try some nsfw search on google video engine you will get blurred images.

**Comment by unixfox** [comment]
Please send the exact keyword used, using the bang for forcing the engine used.

bang for google video: `!gov`
bang for youtube: `!yt`

**Comment by lemonadeforlife** [comment]
@unixfox By default, I am only using google video engine for video on my preference. If you are want to see my settings.yml I can show you

**Comment by unixfox** [comment]
I repeat, please send the exact keyword used, using the bang. This allows us to more easily reproduce the issue.

**Comment by lemonadeforlife** [comment]
> I repeat, please send the exact keyword used, using the bang. This allows us to more easily reproduce the issue.

!gov block porn

**Comment by unixfox** [comment]
Ok which video should be blurred because no videos are blurred here: https://paulgo.io/search?q=%21gov+block+porn&language=all&time_range=&safesearch=0&theme=simple?

**Comment by lemonadeforlife** [comment]
> Ok which video should be blurred because no videos are blurred here: https://paulgo.io/search?q=%21gov+block+porn&language=all&time_range=&safesearch=0&theme=simple?
Searched with real ip:
![](https://i.imgur.com/tRrb9v1.png)

search using different ip using tor:
![](https://i.imgur.com/QtRL4og.png)

**Comment by unixfox** [comment]
The IP address doesn't matter but ok I was able to reproduce the issue on the second page.

![image](https://github.com/searxng/searxng/assets/4016501/2f411dcf-5c00-43bc-96b7-b64a55a1cb08)

The safesearch parameter is not correctly sent or something.

**Comment by lemonadeforlife** [comment]
@unixfox I thought maybe google result might sort differently depends on different country.
But please do note that it's only about this video any nsfw related or some case sfw related it gets blurred.
To make things easier just `!gov porn` you'll find endless blurred images.

**Comment by BernieHuang2008** [comment]
#2786 has this problem on ddg too.
It's more possible because the parameters haven't been passed to engine correctly.

You're right @unixfox , may be we can work it together.

**Comment by shirespours** [comment]
So I fixed this on my own instance (just have to do it after every pull). All you need to do is set safe=off. I did this by adding into the params section 'safe': 'off' and then removing the if option to enable/disable safe mode. I'm guessing searing is trying to use 0, 1, 2 instead of off (unknown) and on. safe=off shows everything, safe=on shows nothing, default shows blurred.

**Comment by shirespours** [comment]
Oh and for duckduckgo, you go into duckduckgo_extra.py and replace "safesearch_args = {0: '1', 1: None, 2: '1'}" with "safesearch_args = {0: '-2', 1: '-1', 2: '1'}"

**Comment by return42** [comment]
> So I fixed this on my own instance (just have to do it after every pull). 

Please send us your PR :+1: / same with ddg .. thanks a lot.

**Comment by shirespours** [comment]
Never done a PR before so it might take awhile lol. But, the google one as of now won't work for prod since so far the only way I can make it work is to force safesearch off, so no matter what the user selects it will be off (for google videos). ddg works fully and follows the users selected safesearch preference though.

**Comment by BernieHuang2008** [comment]
> Oh and for duckduckgo, you go into duckduckgo_extra.py and replace "safesearch_args = {0: '1', 1: None, 2: '1'}" with "safesearch_args = {0: '-2', 1: '-1', 2: '1'}"

sorry, i've test this, but seems that nothing has changed according to my experiment??

**Comment by BernieHuang2008** [comment]
got it! 
@return42 , look at here: 
https://github.com/searxng/searxng/blob/8dfc1dbc5c0ed4968a7111909dc597a755cc94c6/searx/engines/google_videos.py#L90-L91
if safesearch is set to 'off', the value of `params['safesearch']` will be `0`, which equals `False` in python, so the `if` codeblock won't be executed!
