### ISSUE TITLE
CI: upgrade actions/checkout@v2 and actions/upload-artifact@v2

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2777]
Not sure, may we need to upgrade the `actions/checkout@v2` in our CI builds?

The CI reports the following annotation:

```
The following actions uses node12 which is deprecated and will be
forced to run on node16: actions/checkout@v2, JamesIves/github-pages-deploy-action@3.7.1.
```
For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by Bnyro** [comment]
There's already `actions/checkout@v4`, it might be time to upgrade that dependency :)

From my experience, upgrading `actions/checkout` just works by increasing the version and doesn't break anything, so I think that should be fine.

**Comment by return42** [comment]
@Bnyro thanks for your hint / I'm not experienced with .. do you know if there is also a new package for `actions/upload-artifact@v2` ?

**Comment by Bnyro** [comment]
> @Bnyro thanks for your hint / I'm not experienced with .. do you know if there is also a new package for `actions/upload-artifact@v2` ?
>
Yes, there's `actions/upload-artifact@v3` now. Just changing the version number should be sufficient!
