### ISSUE TITLE
Safe search won't activate on ddg and startpage

### ISSUE THREAD

**Issue by verduxy** [searxng/searxng#2786]
**2023.9.8+9e83c0ded**
**Istalled locally by script on debian 12**

Duckduckgo and startpage engines output nsfw content even with strict search on, i don't understand if both engines use moderate settings even if i set strict one or it's an incompatibility matter.

**How To Reproduce**
Search nsfw keywords with safe_search on "strict" and with ddg and startpage engines activated.

**Expected behavior**
No nsfw result should be displayed

**Comment by BernieHuang2008** [comment]
Can you give me a example keyword that has this problem? it appears to me that ddg does filter some results.

**Comment by verduxy** [comment]
Try simply "adult content", i also tested other public instances it's the same

**Comment by BernieHuang2008** [comment]
![Collage_20230917_141119.jpg](https://github.com/searxng/searxng/assets/88757735/c6c5aee9-da59-472a-828a-f382ffdb0f09)

Left is struck mode on, right is off

It actually filter some, but not completely.

When I searched the same keyword on ddg.com, it returns nothing.

![Screenshot_20230917_141540_com.microsoft.emmx.jpg](https://github.com/searxng/searxng/assets/88757735/6ea74c12-982c-44c7-a39f-fa3f98bbd631)

**Comment by BernieHuang2008** [comment]
It's as same as #2762

**Comment by verduxy** [comment]
exactly, maybe it pass only moderate parameters and not strict ones, i tried to figure out where are implemented but i found /searxng-src/searx/engines/duckduckgo.py missing filtering ones, in other engines we find for example:

bing
`safesearch_types = {2: 'STRICT', 1: 'DEMOTE', 0: 'OFF'}  # cookie: ADLT=STRICT`
brave
`safesearch_map = {2: 'strict', 1: 'moderate', 0: 'off'}  # cookie: safesearch=off`

Shounldn't we have have something like this:  
_**`safesearch_ddg = {2: 'on', 1: 'moderate', 0: 'off'}  # cookie: NSFWs=off`**_

I also in the same above file i found a comment on safesearch line:
`### safesearch = True  **# user can't select but the results are filtered`**

I am wondering what this comment mean, it can't be implemented? Or ddg api don't allow this parameters?

**Comment by BernieHuang2008** [comment]
Thanks for diving into it!

> I am wondering what this comment mean, it can't be implemented? Or ddg api don't allow this parameters?

Ping @return42 @dalf 
Do you knows what that comment mean?

It appears to me that ddg allows safesearch, but the parameter doesn't reflected in the URL.

**Comment by BernieHuang2008** [comment]
FYI, safesearch is defined by `ex` parameter in ddg:
`0`: strice (default)
`-1`: moderate
`-2`: off

**Comment by BernieHuang2008** [comment]
it's mainly because we're using ddg-light, where it doesn't support safesearch.
see lite.duckduckgo.com/lite, there're not any filters about safesearch.
`ex` parameter can filt some, but lite version is not as strict as in duckduckgo.com.

**Comment by verduxy** [comment]
Thank you very much i now understand why, i'll look further in implementing a new api for now i think it's ok to close
