### ISSUE TITLE
[feature] highlight keywords

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#2787]
Highlight the user's search keyword improved the UX a lot. User can judge the result quality better.

**Describe the solution you'd like**
i think it's easy, because a XPath or HTML Selector can simply find them.
for example, `bing` will highlight keywords by using `<strong>` tags, and `google` will use `<em class="t55VCb">`.

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/searxng/searxng/assets/88757735/ae976fd3-6b1a-4147-901c-209a95b28ab7)

**Comment by return42** [comment]
SXNG already highlight the words of the search term in the "content" text in a result item .. is it what you mean .. or do you miss highlight in the title?

Here is an example, in the last result there is no "john" or "Doe" in the "content" text --> nothing highlighted:

![image](https://github.com/searxng/searxng/assets/554536/1f5c31ce-6564-4e01-94d3-115240468942)

**Comment by BernieHuang2008** [comment]
Well ... i'd probably find a page that doesn't have any highlights...

I suggested that you can use another color such as red to make it more attractive.

**Comment by return42** [comment]
Since #2800 has been closed I have to ask if this request here in #2787 does any longer exists / if yes, please describe what exactly do you suggest / if no, I think we can close this issue.

**Comment by BernieHuang2008** [comment]
Oh, sorry I forgot to close it with #2800
