### ISSUE TITLE
Problems about Keyboard Navigation

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#2788]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
since #2724 .

**What happened?**
When using arrowkey-navigation on first/last result, it will jump to bottom/top  (that is, loop select).
I think it's not good for the UX, but seems you write a special code that cause this "bug".
https://github.com/searxng/searxng/blob/ec540a967a66156baa06797183cc64c4a3e345be/searx/static/themes/simple/src/js/main/keyboard.js#L237-L239

i think it shouldn't act like that, because users will be confused by this sudden jump.

**How To Reproduce**

- Search anything
- focus on the first result
- press `Arrow-Left`
and you will see the page has scrolled to bottom (the last result).

**Expected behavior**

do nothing

**Comment by return42** [comment]
I think we should collect the issue we have with the keyboard navigation:

- https://github.com/searxng/searxng/issues/2751
- in the preferences the "vim plugin" need to be converted to a drop down menu from where the user can select one keyboard layout from a list of keyboard layouts
- clear the misuse/mess of the `data-vim-selected` attribute that is also used outside of a vim keyboard layout

**Comment by BernieHuang2008** [comment]
Do you mean a simple menu which you can choose one of the `pre-defined` layouts ?

**Comment by return42** [comment]
Yes, currently we already have two layouts .. the default layout (with the Arrows you implemented) and the vim layout, which can be activated in the preferences:

![image](https://github.com/searxng/searxng/assets/554536/ab9d4034-6e14-434f-a4d6-3f1cb95fad17)

The on-off checkbox should be replaced by a drop-down menu --> "default" & "vim-like" .. may be later -- when there is a need -- we can add more layouts .. or we add an option to select "none layout" ..

**Comment by BernieHuang2008** [comment]
good idea, i will try it. 
(when i finished your #2751 )

**Comment by return42** [comment]
> good idea, i will try it.

Thanks a lot for taking the time :+1:

The thing with the preferences is a little tricky since (for historical reasons) currently the vim-like hotkeys are registered as a plugin (on/off switch) .. don't fight to long with this, I can then better take over this part (the preferences) of the work.

**Comment by BernieHuang2008** [comment]
ok, you can do the preferences, and i will try to format the code to more extend-able.

**Comment by BernieHuang2008** [comment]
Can you pass the `layout name` to me by storing it in the variable `searxng.settings.hotkeys`?
for example, 
```
searxng.settings.hotkeys = "vim";
OR
searxng.settings.hotkeys = "default";
```
or you may specified a variable.

**Comment by return42** [comment]
Yes I can .. was also what I had in mint, to use the `hotkeys` variable / this code will be changed to pass the selected value from the menu in the preferences to the JS on client side:

https://github.com/searxng/searxng/blob/ec540a967a66156baa06797183cc64c4a3e345be/searx/webapp.py#L365

**Comment by BernieHuang2008** [comment]
My changes at https://github.com/BernieHuang2008/searxng/tree/feat-2788

**Comment by return42** [comment]
> My changes at https://github.com/BernieHuang2008/searxng/tree/feat-2788

Thanks a lot .. I will cherry pick you patch and implement the preferences part .. when I finished I will send a PR (can take a while).

**Comment by BernieHuang2008** [comment]
No need to be hurry, I shall go and finish my homework now ...

**Comment by return42** [comment]
> My changes at https://github.com/BernieHuang2008/searxng/tree/feat-2788

I cherry picked .. just FYI in your implementations you implemented a "vim" table and a "default" table .. in the old implementation the vim table was a merge, see --> [To add Vim-like key bindings, merge the 'vimKeys' into 'keyBindings'.](https://github.com/searxng/searxng/compare/master...BernieHuang2008:searxng:feat-2788#diff-b7b8b88bb487a0c8a04b3f0253cdfaa6dede3e33ebc79b8bb35f81c72ef4ae74L175-R179)

.. I will squash the fix into your commit / you will see it when I send the PR.

**Comment by BernieHuang2008** [comment]
Shall we move the hockey list into a config file? It's more likely to be there instead of in the source code.

**Comment by return42** [comment]
I had already thought about that ... but let's finish the https://github.com/searxng/searxng/pull/2795 first.  Afterwards we can cleanup the code .. at this opportunity we could also work on the point I mentioned above

> clear the misuse/mess of the data-vim-selected attribute that is also used outside of a vim keyboard layout
