### ISSUE TITLE
[question] Searxng searches fail 95% of the time w/ zero results in multiple browsers

### ISSUE THREAD

**Issue by lakrsrool** [searxng/searxng#2797]
I get: "Sorry! we didn't find any results. Please use another query or search in more categories".

I am using 7 of the most common "Web" engines available in searx.  I have tried clearing cookies, cache, history, application cache - no help.

This happens in all browsers I've tried it in (currently attempting to get it to work in Vivaldi).

An interesting result was when I tried searching for: "Best search engines" it consistently worked for once 
(as long as I don't change anything in the search, but if I add the two words "for security" at the end it consistently fails 
to work producing the results referenced above.

**Comment by unixfox** [comment]
Please choose a working instance from https://searx.space from the top10 that works. Unfortunately there are search engines that have blocked searxng and we are working on it.

**Comment by keithdanielll** [comment]
And that is the only possible answer that you could come up with? Or suggest "change the IP of your server every few weeks"? This project has failed and I will delete my instance.
