### ISSUE TITLE
Zero results 95% of the time

### ISSUE THREAD

**Issue by lakrsrool** [searxng/searxng#2798]
I get: "Sorry! we didn't find any results. Please use another query or search in more categories".

I am using y of the most common "Web" engines in searx.  I have tried clearing cookies, cache, history, application cache - no help.

This happens in all browsers I've tried it in (currently attempting to get it to work in Vivaldi).

An interesting result was when I tried searching for: "Best search engines" it consistently worked for once (as long as I don't change anything in the search, but if I add the two words "for security" at the end it consistently fails to work producing the results referenced above.

**Comment by unixfox** [comment]
please do not open duplicated issues: https://github.com/searxng/searxng/issues/2797
