### ISSUE TITLE
[Feature Request] Show icon of domain URLs

### ISSUE THREAD

**Issue by Guanran928** [searxng/searxng#2809]
**Is your feature request related to a problem? Please describe.**

URL icons are commonly used in other search engines, to show the domain of search results. This makes it easier for users to quickly identify the source of the information. However, SearXNG currently does not have this feature, which can sometimes make it difficult for users to evaluate search results.
Here's what SearXNG currently has, as you can see, it is really difficult to tell apart different domains:
![image](https://github.com/searxng/searxng/assets/68757440/25ec3f0c-142d-4204-9661-5db7e5127438)

**Describe the solution you'd like**

I would like to see icons of domain URLs displayed before the URL/Title.
For example (Brave search):
![image](https://github.com/searxng/searxng/assets/68757440/8b2e6b75-02aa-4f7e-8a19-5be5c8099858)

**Describe alternatives you've considered**

I have not considered any alternatives at this time.

**Additional context**

https://github.com/searx/searx/issues/1690
https://github.com/searx/searx/pull/2951

**Comment by return42** [comment]
thanks for pointing out, but we had this topic in the past without finding an acceptable solution:

- https://github.com/searxng/searxng/pull/441
- https://github.com/searxng/searxng/issues/1014

Before we start a thread more about this topic I suggest to continue the discussions in the existing threads.
