### ISSUE TITLE
Qwant Lite: Incomplete URLs in results where links are too long

### ISSUE THREAD

**Issue by dsmith2001** [searxng/searxng#2812]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2023.9.18+90b0bfd1b
**How did you install SearXNG?**
searxng-docker
**What happened?**
If a Qwant result link title has three dots (...), it uses those three dots in the result URL as well.
**How To Reproduce**
Search with Qwant (qwant **lite** must be used in settings.yml, seems like the default as of recent commits)
**Expected behavior**
The full URL should be in the result, not a trimmed one where the link becomes invalid.
**Screenshots & Logs**
![image](https://github.com/searxng/searxng/assets/129474298/5c89a7f9-7c7f-4b17-9b02-8348df5bbe55)

**Comment by return42** [comment]
@dsmith2001 thanks for reporting the issue .. 

> If a Qwant result link title has three dots (...), it uses those three dots in the result URL as well.

could you give me an example of a search term where you observed this issue?

----

EDIT: now I see, these are the the randomly interspersed advertising adds from qwant we didn't filter out right now / I will fix!
