### ISSUE TITLE
Show error message about no-results only on the first page

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2815]
After using a while 

- https://github.com/searxng/searxng/pull/2808

I think its better when the error message is only shown on the first page.

We have many engines that do support only one or a few of result pages, by instance qwant does have 5 result pages, when you click on the sixth page the error message is shown.

It might be better when we show a "no more results" message on no-result when page number is greater than one.

**Comment by return42** [comment]
@unixfox if you have time, could you have a look about this feature? / thanks :+1:

**Comment by obfuscated-loop** [comment]
@return42 Hi mate, I just made a branch where I've added this functionality but think I screwed up the commits lol - you might have to 'cherrypick' it again :rofl: I was also thinking it might be worth having an individual translation for `You can try to:` instead of having it included in the full sentence.

See here: https://github.com/searxng/searxng/commit/2b38d8c7d89a1c5491587f383205bf0fdd5ab8b3

**Comment by obfuscated-loop** [comment]
What's the best way of adding the translation data/ID?

**Comment by return42** [comment]
> What's the best way of adding the translation data/ID?

@obfuscated-loop you did it already by adding the *underline-function* like in `_("Sorry!")` .. the *underline-function* translates the term .. the term is automatically add to the translation framework  .. by example the old term you replaced `_("No results were found. You can try to:")` can be translated here --> https://translate.codeberg.org/translate/searxng/searxng/en/?q=No+results+were+found.+You+can+try+to%3A&sort_by=-priority%2Cposition&checksum=#translations

>  I've added this functionality but think I screwed up the commits lol 

Don't worry, just send a PR from you branch .. we can clean up the commit history in your branch later.

---

EDIT: Sorry to late I see you already send:

- https://github.com/searxng/searxng/pull/3023

Thanks :+1:

**Comment by obfuscated-loop** [comment]
Oh I see! I knew about the underline function already from i18n in PHP but didn't realise this one was connected to Weblate - very cool! You're welcome too.
