### ISSUE TITLE
Bug: internetarchivescholar engine

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng#2823]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.9.19+3ac7c40b6

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: KeyError
  * Percentage: 25
  * Parameters: `()`
  * File name: `searx/engines/internet_archive_scholar.py:59`
  * Function: `response`
  * Code: `'title': result['biblio']['title'],`

**Comment by Bnyro** [comment]
Please share a search query to reproduce this with.
