### ISSUE TITLE
[Bug] Search box not in center in mobile view.

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#2836]
**Version of SearXNG** 2023.9.22+71358e9c6

**How To Reproduce**

Just open it on your phone.

**Screenshots & Logs**

![Screenshot_20230922_231303_com.microsoft.emmx.jpg](https://github.com/searxng/searxng/assets/88757735/0ff1ed84-0bc6-4415-a988-7421f4e35594)

**Additional context**
1. Find out which PR cause this.
2. solve it.

**Comment by BernieHuang2008** [comment]
I think this commit cause the bug.


https://github.com/searxng/searxng/commit/a76c8e4101dceb68cf7d846868e5e50e54461b08

**Comment by BernieHuang2008** [comment]
it's also exist in pc mode (just a bit dificult to recognize), so it'll be better to solve it asap.
![image](https://github.com/searxng/searxng/assets/88757735/08fbfcd7-5ed3-4f27-baa1-5e62bcf2c1ec)

**Comment by unixfox** [comment]
Fixed in https://github.com/searxng/searxng/pull/2833
