### ISSUE TITLE
Stackoverflow preview on search

### ISSUE THREAD

**Issue by Robby3St** [searxng/searxng#2851]
**Is your feature request related to a problem? Please describe.**

A friend tried a new (paid) search machine and I remembered SearXNG as an alternative. He's a software developer and so he liked the feature of the paid search engine to show StackOverflow answers directly on the search page underneath the stackoverflow search result. 

**Describe the solution you'd like**

I would like to see (if possible) a quick preview of e.g. StackOverflow answers directly under the specific search results to improve the developer's search workflow. 

**Describe alternatives you've considered**

Push StackOverflow or common IT forum sites in IT search results.

**Comment by unixfox** [comment]
That's already available: https://github.com/searxng/searxng/blob/master/searx/settings.yml#L1364
