### ISSUE TITLE
Bug: bilibili engine is broken

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#2861]
Something has changed, and now some fixes are needed to use the api successfully.

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.9.27+1a66d7467+dirty

**How did you install SearXNG?**
make run

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Comment by BernieHuang2008** [comment]
i've solved this issue with PR #2862.
