### ISSUE TITLE
Allow non-interactive updates using searxng.sh (when SearXNG is installed using the scripts)

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#2881]
**Is your feature request related to a problem? Please describe.**
The update script `sudo -H ./searxng.sh instance update` offers a menu at the end, when it detects and existing `settings.yml`, offering to replace the file, leave it as is and so on. Without user interaction, the menu pauses indefinitely. This disallows the creation of scripts for automated, unattended upgrades, something which is highly desirable, given the fast pace of SearXNG development.

![image](https://github.com/searxng/searxng/assets/25054477/4390a7c3-e538-4423-9ad5-5e7407b15aeb)
 

**Describe the solution you'd like**
It would be nice to specify a command line argument with a predefined choice for `settings.yml`. For instance, something such as `sudo -H ./searxng.sh instance update 2` or `sudo -H ./searxng.sh instance update leave` or the likes. This would allow to create scripts/systemd services that would periodically update SearXNG instances without any intervention from the instance maintainer.

**Describe alternatives you've considered**
I have looked into modifying the script myself, but I have a limited knowledge of shell programming.

**Comment by return42** [comment]
duplicate / see https://github.com/searxng/searxng/discussions/2473

**Comment by catfluoride** [comment]
Oh... My bad. Thanks a lot and sorry for the noise.
