### ISSUE TITLE
Bug: ddg broken on every instances

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#2909]
***Duckduckgo has crashed, every instance have the same error as below.***

---

**Version of SearXNG**
Repository: https://github.com/return42/searxng
Branch: darmarit.org
Version: 2023.10.6+d55a7d7b

**How To Reproduce**

Search any query with bang `!ddg`.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 60
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: IndexError
  * Percentage: 40
  * Parameters: `()`
  * File name: `searx/engines/duckduckgo.py:99`
  * Function: `get_vqd`
  * Code: `value = doc.xpath("//input[@name='vqd']/@value")[0]`

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/issues/2796

**Comment by BernieHuang2008** [comment]
Are they same? I think #2796 first appears than this one ... never mind, and thank you.
