### ISSUE TITLE
Owner request: Remove matrixrooms.info instance

### ISSUE THREAD

**Issue by aine-etke** [searxng/searxng#2918]
Hi there,
I'm one of the etke.cc developers, and we operate MRS demo instance on matrixrooms.info / apicdn.matrixrooms.info

Please remove that **instance** from your code base - nobody contacted or notified us before its inclusion, and now we have to pay for the traffic your project generates.

Moreover, the integration metadata is completely invalid:

* [WikiData ID is wrong](https://www.wikidata.org/wiki/Q107565255)
* [Official API documentation is not provided](https://gitlab.com/etke.cc/mrs/api/-/blob/main/openapi.yml?ref_type=heads)
* It uses the official API
* Category should be instant messages

---

To avoid any misunderstanding, let me clarify some things.

1. You may want to integrate Matrix Rooms Search - self-hosted search engine over matrix federation: https://gitlab.com/etke.cc/mrs/api
2. You're supposed to host your own instance of MRS
3. The matrixrooms.info is a demo instance, and it is not intended for such integration
4. We pay for matrixrooms.info / apicdn.matrixrooms.info traffic from our own pockets and if it becomes unbearable, we can consider shutting it down.

**Comment by aine-etke** [comment]
@Bnyro @return42

**Comment by aine-etke** [comment]
Added PR that fixes the issue: https://github.com/searxng/searxng/pull/2919

**Comment by Bnyro** [comment]
> Please remove that **instance** from your code base - nobody contacted or notified us before its inclusion, and now we have to pay for the traffic your project generates.
> 
The engine is disabled by default - there won't be much traffic generated via SearXNG. And if there's traffic, the user would have used the web UI of matrixrooms.info instead if we don't support it - so the API traffic is the same.
> Moreover, the integration metadata is completely invalid:
> [WikiData ID is wrong](https://www.wikidata.org/wiki/Q107565255)
> 
That's my bad, forgot to remove it during copy and paste and modificiation of the `about` metadata of an other engine
>  [Official API documentation is not provided](https://gitlab.com/etke.cc/mrs/api/-/blob/main/openapi.yml?ref_type=heads)
> It uses the official API
>
I've searched for that on the website, but I could neither find the source code or the API docs via the website hence it's not been added there.
> Category should be instant messages
>
We don't have such a category and social media is the most appropriate category.


> To avoid any misunderstanding, let me clarify some things.
> 1. You may want to integrate Matrix Rooms Search - self-hosted search engine over matrix federation: https://gitlab.com/etke.cc/mrs/api
> 2. You're supposed to host your own instance of MRS
> 3. The matrixrooms.info is a demo instance, and it is not intended for such integration
> 4. We pay for matrixrooms.info / apicdn.matrixrooms.info traffic from our own pockets and if it becomes unbearable, we can consider shutting it down.
> 
As I said above, you should not expect to get much more additional traffic than you would anyways. It's just more comfortable to find results directly with one search using SearXNG than using SearXNG to find matrixrooms.info and use that to search for a room.

**Comment by aine-etke** [comment]
> I've searched for that on the website, but I could neither find the source code or the API docs via the website hence it's not been added there.

Official API docs [is listed in the project README](https://gitlab.com/etke.cc/mrs/api/#api) and the **demo** instance website doesn't have such link, well, because it's just a demo instance.

> We don't have such a category and social media is the most appropriate category.

I'm sorry, didn't know that, I'll adjust the PR in a minute

> As I said above, you should not expect to get much more additional traffic than you would anyways. It's just more comfortable to find results directly with one search using SearXNG than using SearXNG to find matrixrooms.info and use that to search for a room.

Nevertheless, we've had several gigabytes of traffic generated by SearXNG in ~1 week, and we had to reject such requests automatically.

Unfortunately, I have to disagree with your arguments. MRS is open source project that promotes decentralization and selfhosting. By using the **demo** instance provided for **demo** purposes as **the only** hardcoded option is just contrary to the MRS project goals. 

Would you consider a compromise to include the provided PR, but have the demo instance set as default config option? Again, MRS is intended to be self-hosted, otherwise matrixrooms.info may become "gmail of MRS" one day and that's entirely wrong.

**Comment by unixfox** [comment]
> Nevertheless, we've had several gigabytes of traffic generated by SearXNG in ~1 week, and we had to reject such requests automatically.

That's quite a surprising amount considering that we do not advertise anywhere the new engines, the users have to find out about it. The engine code has been out for only 7 days, and it's disabled by default.

Would you be able to join our official matrix room: https://matrix.to/#/#searxng:matrix.org so that we can discuss a bit further? I would be interested to have some proof that it's really searxng behind the traffic. Maybe discover a new thing where some people that using searxng in a bad way?

**Comment by aine-etke** [comment]
(Sorry, misclick)

Sure

**Comment by return42** [comment]
> MRS is open source project that promotes decentralization and selfhosting.

In SearXNG we have a list of public known instances at https://searx.space/ .. the engines on this list are registered in https://github.com/searxng/searx-instances/blob/master/searxinstances/instances.yml

Is there similar for MRS, a list of public MRS instances?

If such a list exists I would like to fetch this list while initialization of the engine .. the engine itself can than pic randomly MRS instances.

https://github.com/searxng/searxng/blob/213cb74378a02a0863c3028d6817751124c62183/searx/engines/mrs.py#L41-L47

**Comment by aine-etke** [comment]
@return42 unfortunately, there is no such list yet - MRS is in the alpha status at this moment and community is too small.

Plus, there is no any telemetry, so we don't know about other deployments
