### ISSUE TITLE
Engine request: brave goggles

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#2939]
**Working URL to the engine**
https://search.brave.com/goggles?q=apple

**Why do you want to add this engine?**
goggles is a category of brave search. This feature allows users to customize brave's search results by using a config file. The URL to this file is used in the query params when making a search. Anyone can make their own goggles, or use existing ones.

**Features of this engine**
should be easy to integrate since we can reuse code from the brave engine

**How can SearXNG fetch the information from this engine?**

**Applicable category of this engine**
general

**Additional context**

What i'm thinking is this:
to use this in searxng, you uncomment the brave goggles engine in settings.yml, paste the URL to the goggles that you want to use, then save the settings.yml file.

**Comment by allendema** [comment]
(Outdated) xpath engine:
https://github.com/allendema/searxng/blob/12d9de269825759eb3ce15f22357f39968e2c513/searx/settings.yml#L1790
