### ISSUE TITLE
reddit engine: duplicate results

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#294]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

Last version of searx, same issue on public instanes

**How did you install Searx?**
`make run`

**How To Reproduce**
It happens with various query.
Example `!reddit rumilly` :

![image](https://user-images.githubusercontent.com/1594191/132207079-6ce10c3e-8daf-48b2-921b-c75c474bf8fc.png)

In this example the duplicates have the same image URL and same result URL..

**Expected behavior**
Merge the duplicate results.

**Comment by return42** [comment]
Is this really a bug? Images are coming from different URL .. Seams bot generated content .. e.g. try: `!reddit Vanderbilt vs East Tennessee` .. it is the same, you will find the same image used in different URLs / here are just two links ...

- https://www.reddit.com/r/Rocketsportsfeed/comments/phw93y/how_to_watch_texas_am_vs_kent_state_football_2021/
- https://www.reddit.com/r/Rocketsportsfeed/comments/phw9cw/college_football_2021ncaaf_2021_vanderbilt_vs/

**Comment by dalf** [comment]
I see exactly the same links:
* image: `b[dot]thumbs[dot]redditmedia[dot]com/Qk0YfqxWOLvd8A8WjBmeQ4ETHD9-XstmfphX0UvQr7s.jpg`
* URL: `rocket-sports-feed-live[dot]blogspot[dot]com/p/live-soccer-2021-stream.html`

**Comment by dalf** [comment]
Closing: there are spam with slightly different texts.
