### ISSUE TITLE
Google engine: the first result is sometimes ignored

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#2942]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2023.10.13+b013cbb4c
( https://search.bus-hit.me/search as example, but basically the master branch)

**How did you install SearXNG?**
N/A

**How To Reproduce**
`!google opnsense`

The first result is opnsense.org in google, but not in SearXNG:

| google | SearXNG |
| -- | -- |
| ![image](https://github.com/searxng/searxng/assets/1594191/8d43908a-73be-413a-b1de-9b88868565c0) | ![image](https://github.com/searxng/searxng/assets/1594191/ba3de430-4225-4136-9cd3-ac5f6b454c30) |
 
**Expected behavior**

See the first result : https://opnsense.org

**Additional context**

**Comment by unixfox** [comment]
Try with "default language" option: https://search.bus-hit.me/search?q=%21go%20opnsense&language=all&time_range=&safesearch=0&categories=none

This is due to the language selection.
