### ISSUE TITLE
Bug: artic & devianart engine

### ISSUE THREAD

**Issue by ductridev** [searxng/searxng#2951]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master

**How did you install SearXNG?**

**What happened?**
Update to the lastest version and see this error in the image tab.

**How To Reproduce**
Just update to lastest version and facing this problem.

**Expected behavior**

**Screenshots & Logs**
![image](https://github.com/searxng/searxng/assets/49811496/15310846-8b47-4154-a8d1-6c8cf18ea428)

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params["url"], **request_args)`

**Comment by Austin-Olacsi** [comment]
both of these engines work fine for me when running Searxng on my local PC

the instance you're using is getting blocked

try picking a working instance from https://searx.space/
