### ISSUE TITLE
Install script should ask all the questions up front to make installation more streamlined

### ISSUE THREAD

**Issue by shodanx2** [searxng/searxng#2952]
Just a simple quality of life improvement.

Took me 3 attempts getting through that script I always ended up distracted long enough and then lose the connection each time so I had to start over.

However it does seem the script will recover gracefully from interruptions.

Also, the install script does not check or warn about the absence of python

The install script does not start the application, or tell the user how to start it once completed

It also does not tell the user how to make searxng auto-start at reboot

The step by step installations at https://docs.searxng.org/admin/installation-searxng.html

Have underscore characters add to every commands, making them not copy-pastable, same with the other instructions at https://docs.searxng.org/admin/installation-scripts.html. They also have leading "$" characters that must be removed

Also, something didn't quite work in my case 

```
root@searxng:/searxng# ./searx/webapp.py
  File "./searx/webapp.py", line 172
    preferences: Preferences
               ^
SyntaxError: invalid syntax
root@searxng:/searxng# python searx/webapp.py
  File "searx/webapp.py", line 172
    preferences: Preferences
               ^
SyntaxError: invalid syntax
root@searxng:/searxng# python3 searx/webapp.py
Traceback (most recent call last):
  File "/searxng/searx/webapp.py", line 27, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

```

**Comment by return42** [comment]
I think the topic could also be titled "lack of concentration" :)

> Also, the install script does not check or warn about the absence of python

On which linux distro did you tried to install? --> [The script does install packages](https://docs.searxng.org/admin/installation-searxng.html#install-packages)

> It also does not tell the user how to make searxng auto-start at reboot

The script installs a service.

> Have underscore characters add to every commands, 

Just C&P should work, I don't have issues with.

**Comment by unixfox** [comment]
Closing as it's a normal thing to have questions for each step of the installation, there are multiple options for installing searxng so that's why it may ask questions later in the installation progress.
