### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by un99known99** [searxng/searxng#2953]
after upgrade from bullseye to bookwork searXNG stopped working with error in logfile:

ModuleNotFoundError: No module named 'httpx'
Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/webapp.py", line 27, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

searXNG is started via:

Type=simple
User=searxng
Group=searxng
ExecStart=/usr/local/searxng/searx-pyenv/bin/python /usr/local/searxng/searxng-src/searx/webapp.py
StandardOutput=append:/var/log/searXNG.log
StandardError=append:/var/log/searXNG.log
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=10
SyslogIdentifier=searXNG

**Comment by return42** [comment]
Seems there was something wrong with your installation ..

You should have a folder:

     ls -la  /usr/local/searxng/searx-pyenv/

I have `python3.11` and the `httpx` is in this folder (under):

     ls -lad /usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/httpx*

**Comment by un99known99** [comment]
hm, how  could it be fixed?

root@pihole[/etc/systemd/system] # ls -la  /usr/local/searxng/searx-pyenv/
total 28
drwxr-xr-x 6 searxng searxng 4096 Sep 23 21:09 .
drwxr-xr-x 5 searxng searxng 4096 Sep 23 21:11 ..
drwxr-xr-x 2 searxng searxng 4096 Oct 14 09:54 bin
drwxr-xr-x 2 searxng searxng 4096 Sep 23 21:09 include
drwxr-xr-x 3 searxng searxng 4096 Sep 23 21:09 lib
-rw-r--r-- 1 searxng searxng   69 Sep 23 21:09 pyvenv.cfg
drwxr-xr-x 3 searxng searxng 4096 Sep 23 21:09 share
root@pihole[/etc/systemd/system] # ls -lad /usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/httpx*
ls: cannot access '/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/httpx*': No such file or directory

**Comment by un99known99** [comment]
root@pihole[/etc/systemd/system] # ls -lad /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/httpx*
drwxr-xr-x 4 searxng searxng 4096 Sep 23 21:14 /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/httpx
drwxr-xr-x 3 searxng searxng 4096 Sep 23 21:14 /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/httpx-0.24.1.dist-info
drwxr-xr-x 3 searxng searxng 4096 Sep 23 21:14 /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/httpx_socks
drwxr-xr-x 2 searxng searxng 4096 Sep 23 21:14 /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/httpx_socks-0.7.7.dist-info


3.9 vs 3.11 with upgrade

**Comment by un99known99** [comment]
ln python3.11 -> python3.9  seems to work, will it break something in the future - how did it work on ur side after bookworm upgrade?

Nope, dies after some secs ....

**Comment by return42** [comment]
I assume bookwork upgraded default python version to 3.11 .. try to reinstall SearXNG to get a `/usr/local/searxng/searx-pyenv/lib/python3.11/` ..

**Comment by un99known99** [comment]
thx, reinstalled fixed it

**Comment by return42** [comment]
> thx, reinstalled fixed it

great :+1: .. BTW you can delete the old python venv at `/usr/local/searxng/searx-pyenv/lib/python3.9`
