### ISSUE TITLE
searxng/searx/engines/recoll.py references an HTML template for results that does not exist.

### ISSUE THREAD

**Issue by virtadpt** [searxng/searxng#2957]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
commit 526d5c7b308a314f7a118a5ecc3b47013e4a9ce9 (HEAD -> master, origin/master,  origin/HEAD)

Not forked.

**How did you install SearXNG?**
Manual installation.

**What happened?**
While in the process of migrating to SearxNG, I ported my configuration blocks over for Recoll.  When accessing the Recoll engine to test it (search term: "!library charles stross") I received an HTTP 500 error.  Because I was running SearxNG in a shell I noted the following stack dump:

```
2023-10-24 17:54:22,612 ERROR:searx.webapp: Exception on /search [POST]
Traceback (most recent call last):
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/searx/webapp.py", line 768, in search
    return render(
           ^^^^^^^
  File "/home/drwho/searxng/searx/webapp.py", line 465, in render
    result = render_template('{}/{}'.format(kwargs['theme'], template_name), **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/drwho/searxng/searx/templates/simple/results.html", line 6, in top-level template code
    <input type="hidden" name="engine_data-{{ engine_name }}-{{ k|e }}" value="{{ v|e }}" />
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/searx/templates/simple/base.html", line 62, in top-level template code
    {% block content %}
  File "/home/drwho/searxng/searx/templates/simple/results.html", line 97, in block 'content'
    {% include get_result_template('simple', result['template']) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drwho/searxng/env/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result_templates/files.html
```

Searching the clone of the SearxNG repo (`find /home/drwho/searxng -type f -name 'files.html' -print`) shows that there is no files.html to be found in searxng/searx/templates/simple/result_templates/.

**How To Reproduce**
Install Recoll and configure it to index a directory.  Install and configure the recollwebui (which presents a REST API to interface with /usr/bin/recollindex).  Configure SearxNG to use recollwebui (edit appropriately):

```
  - name: recoll - library
    engine: recoll
    shortcut: library
    base_url: 'http://127.0.0.1:8080/'
    search_dir: ''
    mount_prefix: /home/drwho/lib
    dl_prefix: 'http://leandra/lib'
    timeout: 120.0
    categories: recoll
    disabled: false
    enable_http: true
```

Run a search on just the Recoll engine while running SearxNG in a shell.

Alternatively, maybe somebody just forgot to `git add` the files.html template?

**Expected behavior**
I get a list of the Charles Stross texts on my hard drive, as indexed by Recoll, looking like it fits the Simple theme along with everything else.

**Additional context**
I checked the older Searx install that I'm migrating away from (which I also interfaced with Recoll) and there is a files.html template (searx/searx/templates/oscar/result_templates/files.html) which, to date, has worked pretty well.  A brief test suggests that it would need significant modification to work with SearxNG.

**Comment by return42** [comment]
A `files.html` template is missed in the simple theme / we have a DRAFT PR:

- https://github.com/searxng/searxng/pull/2323#issuecomment-1510264513

@virtadpt may you and @OliveiraHermogenes have time to develop the PR further?

**Comment by virtadpt** [comment]
I'll take a look at it... it's been dropped into my install and I'm giving it a whirl.  It has a few minor improvements from my quick and dirty hack of Searx's last night to see what would happen.  It doesn't look too bad at all - it's laid out in the Searx!Oscar like fashion that I favor (which suggests one or two things about the Firefox install I normally use, so take that with a grain of salt), watching the output of SearxNG in a terminal isn't showing any errors or exceptions.

The CSS of the document metadata is a bit much, it looks double or triple spaced but at least it's there.  I'll see if I have time to look at the CSS after work this afternoon.

For very long URLs it seems that the earlier bits are being truncated instead of the later ones (e.g., "http://leandra   sychology of interrogations and questioning.pdf" instead of "http://leandra/lib/textbooks/psychology of interro")

Another random thing: In searxng/searx/settings.yml, it might be useful to add comments to the effect of "If you want your 'files' category search results to have valid URLs, be sure there's a trailing slash on the URL in the `dl_prefix` line", like so:

```
  - name: recoll - library
    engine: recoll
    shortcut: library
    base_url: 'http://127.0.0.1:8080/'
    search_dir: ''
    mount_prefix: /home/drwho/lib
    dl_prefix: 'http://leandra/lib/'
    timeout: 120.0
    categories: recoll
    disabled: false
    enable_http: true
```

**Comment by OliveiraHermogenes** [comment]
Nice! Thanks for the review @virtadpt !

I don't know any CSS at all. So, I would have to spend more than a couple of hours to turn #2323 into something robust, a time I unfortunately don't have at the moment. @virtadpt Please, feel free to take whatever is worthwhile from #2323 (assuming there is anything) and submit a different PR of your own.

With regards to the trailing slash in `dl_prefix`, I have two recoll engines configured, one with trailing slash and the other without. Both work fine, with valid URLs. So, I am not sure that's a SearX issue. What version of recoll-webui are you running? In my case, apache2 also sits in front of SearX. Maybe that's relevant.

**Comment by virtadpt** [comment]
I will give it a try.  It'll probably be laughably bad, so I apologize in advance.  Repo forked, and I'll work on integrating it.

I'm running commit e4c09a3982d86b4c5c80f64956e0106dc6502fc1 of recollwebui.

It might be that I have Nginx sitting in front of SearxNG, as well as serving those directories over HTTP.  It's probably an idiosyncrasy in my configuration.
