### ISSUE TITLE
Bug: google engine --> SearxEngineAccessDeniedException

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2972]
To reproduce the issue query a high page number / e.g. page no. 500:

      http://127.0.0.1:8888/search?q=!go%20foo&pageno=500

**Technical report**

```
Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`
```

On my instance I have bots going into wild and request a page number 458, here is a request from the bot:

```python
form: {
    'q': 'brown wicker side table',
    'category_general': '1',
    'pageno': '458',   # <--- here !!!
    'language': 'auto',
    'time_range': '',
    'safesearch': '2',
    'theme': 'simple'
}
```

As a result, some engines block, e.g. google responds with an HTTP 403 (Forbidden). As a result a `SearxEngineAccessDeniedException` is thrown and the engine is blocked for a long time (by default 86400 sec / 24h). 

https://github.com/searxng/searxng/blob/b63841f0a1a059a1567d91f8c5c9cb645eb1849d/searx/settings.yml#L48-L60

**Comment by unixfox** [comment]
Superseded by https://github.com/searxng/searxng/issues/2982

**Comment by return42** [comment]
> Superseded by https://github.com/searxng/searxng/issues/2982

not really ..

- https://github.com/searxng/searxng/issues/2982

is a feature request while #2972 is a bug report.  Since 

- https://github.com/searxng/searxng/pull/2979

has been merged, the bug is back --> I reopen this bug report.

**Comment by unixfox** [comment]
A bug report or a feature request, whatever you call it, the outcome is the same.

This is for limiting the number of pages per engine in order to reduce the likeliness of the engine blocking searxng.

We can keep this one if you really want, but #2982 is the one to discuss what we are going to do with this issue.

**Comment by return42** [comment]
> We can keep this one if you really want, 

Yes, please .. This is the bug report that users will look for before opening a new bug report on github ("with the green button")

![image](https://github.com/searxng/searxng/assets/554536/b84fc1ee-0b08-4a5a-bf7d-3ee9e153af7e)
