### ISSUE TITLE
Enabling `server.public_instance` without `server.limiter` does not send `link_token` pings

### ISSUE THREAD

**Issue by sevmonster** [searxng/searxng#2975]
Enabling `server.public_instance` forcefully enables the [`server.limiter`](https://github.com/searxng/searxng/blob/7e2e335dd1e06ea20496028abe58b3ad8b255662/searx/plugins/limiter.py#L27) and limiter [`botdetection.ip_limit.link_token`](https://github.com/searxng/searxng/blob/7e2e335dd1e06ea20496028abe58b3ad8b255662/searx/botdetection/ip_limit.py#L113) features, even if these settings are disabled in their respective settings files. However, because the in-memory values for the associated settings are not updated, other areas that reference these values without also checking `public_instance` will act as if the feature is disabled. This is a particularly important distinction for `link_token` injection in the `simple` theme which checks only `server.limiter`:

https://github.com/searxng/searxng/blob/7e2e335dd1e06ea20496028abe58b3ad8b255662/searx/templates/simple/base.html#L20

This regression results in servers running with `use_default_settings` and `public_instance` detecting every incoming IP as suspicious, which blocks every user for a long time after only a few requests.

I have published a PR that will fix this, but I would highly recommend that instead of checking for `public_instance`, that the values for the desired features be [overridden when loading the config](https://github.com/searxng/searxng/blob/7e2e335dd1e06ea20496028abe58b3ad8b255662/searx/settings_loader.py#L68) so that these kinds of regressions are avoided in the future. This also means that any custom theme templates do not have to be updated to check `public_instance` like the simple theme.

**Comment by return42** [comment]
> Users are blocked as suspicious if `server.limiter` is not explicitly enabled when `server.public_instance` has force-enabled the limiter and the `simple` theme is used

Ooops .. good point we had not in mind when 

- https://github.com/searxng/searxng/pull/2848

was developed .. thanks for pointing out :+1:

**Comment by unixfox** [comment]
> I have published a PR that will fix this, but I would highly recommend that instead of checking for public_instance, that the values for the desired features be overridden when loading the config so that these kinds of regressions are avoided in the future.

The second try of implementation of public_instance feature did try to override both settings limiter and link_token: https://github.com/searxng/searxng/pull/2848#issuecomment-1732560535

But because @return42 decided to put link_token outside of settings.yml this implementation could not work due to a circular error when trying to load link_token module which was depending on searxng log module that is not yet loaded.

You can read more here: https://github.com/searxng/searxng/pull/2848#pullrequestreview-1641095725

To be fair if we would have stick to keep using the only settings.yml as a central place for all the settings we would have never had such a bug.

And I would really like to do like you explained above @sevmonster but unless link_token setting is moved in the settings.yml section that is not possible to do.

**Comment by return42** [comment]
> To be fair if we would have stick to keep using the only settings.yml as a central place for all the settings we would have never had such a bug.

The intention of separating the settings was to modularize the botdetection from the core (botdetection is not a core component of a search engine).  In the long run we want to develop the botdetection in a separate reposetory.

Here we have a conflict of interests, on the one hand we want the modularization, on the other hand we have with `public_instance` a switch that acts on both modules ... our task is to cover both interests.  We will find a solution for this.

**Comment by dalf** [comment]
IMO, the reliable way to implement public_instance is to update the searx.settings variable and the in memory content of limiter.toml:

* in one place we have the description of what public_instance does = simple to read code.
* no need to think about it all over the places

I have tried to implement that but failed to update the in memory content of limiter.toml

The right place to do that is settings_defaults.py

**Comment by return42** [comment]
> I have tried to implement that but failed to update the in memory content of limiter.toml

I will give it a try ..

> The right place to do that is settings_defaults.py

Yes, in the initialization of the settings we should also implement a function named like "init_public_instance()"  .. then we have on central point where all the manipulations of this option can be implemented & documented.

**Comment by dalf** [comment]
Reminder for myself: open issue for https://github.com/searxng/searxng/issues/2975#issuecomment-1784683703

**Comment by return42** [comment]
> Reminder for myself: open issue for https://github.com/searxng/searxng/issues/2975#issuecomment-1784683703

@dalf I decided to merge ..

- https://github.com/searxng/searxng/pull/2894

I requested a review from team members here on github and in our matrix channel a month ago and  a multiple time but got only a feedback from @Bnyro  .. I hope it was OK to merge.

In its second commit this PR implements most of the things the `public_instance` has been missed.

> I have tried to implement that but failed to update the in memory content of limiter.toml

https://github.com/searxng/searxng/blob/d13a8f64534b2ba7883cabdae1d08ea68b7899c8/searx/limiter.py#L237-L240

**Comment by return42** [comment]
@dalf I'm not sure if we can close this issue .. As far I know, the bug is fixed .. not sure why I have reopened this issue on Nov 1, 2023 ..

**Comment by return42** [comment]
> As far I know, the bug is fixed 

I have to reopen this ticket. it will be fixed in conjunction with PR:

- https://github.com/searxng/searxng/pull/2981
