### ISSUE TITLE
Add options for instance maintainers to enforce safe search

### ISSUE THREAD

**Issue by tjkeller-xyz** [searxng/searxng#2980]
**Is your feature request related to a problem? Please describe.**
I want my private instance to enforce safe search so that it cannot be turned off by a client. This would be a useful feature for families with young children, schools, etc.

**Describe the solution you'd like**
Option in settings.yml such as 'enforce_safe_search_level' which describes a minimum safe search level.
Also possibly a feature such as is described below that would allow hosting an alternate port/subdomain with enforced safesearch.

**Describe alternatives you've considered**
Using pihole or adguard home allows you to block certain sites at the dns level, but with any search engine you can easily bypass this restriction by using image search to look at pornography or other explicit material. Google, youtube, and other popular search engines allow network administrators to enforce safe search on a network level. Eg. by mapping google.com to forcesafesearch.google.com (ref. https://support.google.com/websearch/answer/186669). A feature like this would also be a nice optional feature for instances.

**Additional context**
N/A

**Comment by return42** [comment]
In a `preferences:`  section in your settings.yml you can `lock` the `- safesearch` setting.

![grafik](https://github.com/searxng/searxng/assets/554536/63886139-2fa7-4b8e-8faa-2d9c19b41044)


https://github.com/searxng/searxng/blob/b05a15540e1dc2dfb8e4e25aa537b2a68e713844/searx/settings.yml#L133-L141

**Comment by dalf** [comment]
> This would be a useful feature for families with young children, schools, etc.

I'm not sure SearXNG is safe regarding this usage: while the engine are maintained, most of them don't rely on well defined API. In other words, the safesearch feature might be ignored for a time for some engine now or in the future.

At least, I would recommend:
* to allow only a very small subset of the engines especially in the general, images and videos categories. 
* to check the news category.
* to remove the engines in the files category, subcategory "without further subgrouping" (safesearch is not implemented for these engines and they can return unsafe results).
* to check the "Social Media" category: I would remove 9gag for example.

Please, double check if the engines really take into account the safesearch setting with unsafe queries.
