### ISSUE TITLE
JSON `number_of_results` is wrong

### ISSUE THREAD

**Issue by miranyx** [searxng/searxng#2987]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
023.11.1+b5a8ddfec, no fork
**How did you install SearXNG?**
I am using searxng-docker inside a docker-compose file.
**What happened?**
On json the field `number_of_results` is 0 even though there are results.

**How To Reproduce**
Search a term. Press on the json results.

**Expected behavior**
The number is equal to the number of returned results.

**Screenshots & Logs**
![20231103_13h42m22s_grim](https://github.com/searxng/searxng/assets/64905406/4b1bf1ee-aeeb-47c0-92fa-ceb8a033a376)

**Comment by unixfox** [comment]
I don't think it's a bug.

This item "number_of_results" is a what the number of results the engine think there are for a specific keyword. For example, if you type something on Google, you will get "About XXX results":

![image](https://github.com/searxng/searxng/assets/4016501/137b6e3c-9a02-47e0-921a-785b6e55a65b)

So we return this number to the user. It's not the number of results available through the API or in the search page of searxng.

------

Related:

- https://github.com/searxng/searxng/issues/2987
- https://github.com/searxng/searxng/issues/2457

**Comment by miranyx** [comment]
So when should it increase since when I search for e. g: `ok` it is also still 0?

**Comment by unixfox** [comment]
Some engine may not give us the number of actual results, so in this case we return "0" because we do not know the amount.

For Google, it's very specific because the parsing for the number of results is broken, that's why you are getting "0".

**Comment by miranyx** [comment]
Ah okay, so not a bug will close it then
