### ISSUE TITLE
Json api doesn't work with server.public_instance enabled

### ISSUE THREAD

**Issue by mdosch** [searxng/searxng#2993]
Version: 2023.11.3+96ccec1aa

Installed according the wiki, no docker involved.

When I set "server.public_instance" to "true" the json api is not working and always returns `Too Many Requests%`. Json results can be shown via the web interface but the api doesn't work.

**How To Reproduce**
Enable json api:

```
  formats:                                                            
    - html                                                                          
    - json                                                                   
```

Also enable `server.public_instance`.

Test json api: `curl "https://search.example.org/search?q=searxng&amp;format=json"` → `Too Many Requests%`

**Expected behavior**
Json api should work when activated, despite having `server.public_instance` set.

**Comment by unixfox** [comment]
Not sure if this is really a bug because it's not recommended at all to allow the API on a public instance. That would get abused by bots very quickly.

Which public instance are you running by the way? This parameter is only for instances from the public list, not semi-private ones.

**Comment by mdosch** [comment]
Thanks for the quick reply, I am running search.mdosch.de.
I fixed it now by adding the ip of the bot which uses the json api to 
the whitelist. But I was surprised that the api didn't work anymore.

Why is it not recommended to allow the api? I thought the limiter (and 
before this was added to searxng filtron) should take care of 
misbehaving bots.

**Comment by unixfox** [comment]
> Thanks for the quick reply, I am running search.mdosch.de. I fixed it now by adding the ip of the bot which uses the json api to the whitelist. But I was surprised that the api didn't work anymore. Why is it not recommended to allow the api? I thought the limiter (and before this was added to searxng filtron) should take care of misbehaving bots.
> […](#)
> On 06.11.2023 11:50, Émilien (perso) wrote: Not sure if this is really a bug because it's not recommended at all to allow the API on a public instance. Which public instance are you running by the way? This parameter is only for instances from the public list, not semi-private ones. -- Reply to this email directly or view it on GitHub: [#2993 (comment)](https://github.com/searxng/searxng/issues/2993#issuecomment-1796228273) You are receiving this because you authored the thread. Message ID: ***@***.***>

The bot protections only apply to HTML pages, not JSON or RSS API.

**Comment by return42** [comment]
> Also enable server.public_instance.

This option activates the limiter

>> The bot protections only apply to HTML pages, not JSON or RSS API.

The limiter filters all request and tools like `curl` are rated as a bot.

https://github.com/searxng/searxng/blob/96ccec1aa6507ef4d3dc05a08e01187f80080972/searx/limiter.py#L147-L205

> I fixed it now by adding the ip of the bot which uses the json api to
the whitelist.

This is the correct solution .. FYI the option `server.public_instance` ads some hard coded IPs from searxng org to the same pass-list: 

https://github.com/searxng/searxng/blob/96ccec1aa6507ef4d3dc05a08e01187f80080972/searx/botdetection/ip_lists.py#L41-L46
