### ISSUE TITLE
[BUG] Images cannot be clicked anymore

### ISSUE THREAD

**Issue by WreckingBANG** [searxng/searxng#3003]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2023.11.12-6368f845c

**How did you install SearXNG?**
docker-compose

**What happened?**
When i click on any image from any search engine, there should appear a section showing the image in a bigger size with the options to open the website it is from and other option. This section is not appearing anymore.

**How To Reproduce**
1. Search Anything
2. Click on any Image
3. Nothing happens (No section is opening)

**Expected behavior**
There should appear a section showing the image in a bigger size with the options to open the website it is from and other option.

**Screenshots & Logs**
 @@
![Screenshot from 2023-11-13 21-29-54](https://github.com/searxng/searxng/assets/86848811/ab397fde-a390-478c-92df-915a0c9cb6be)
I marked the Section that is now missing red

**Additional context**
I tested it on my own private instance as well as on https://search.inetol.net . Both instances showed the same behaviour. 
I tested it on Chromium and Firefox .
I tested it on Mobile (Android) and Desktop (Linux).
I tried clearing my Browser Cache.
It seems to be since 2023.11.11-7b1951aa9

**Comment by return42** [comment]
Not sure but it seems the JS is broken on https://search.inetol.net 

![grafik](https://github.com/searxng/searxng/assets/554536/d727aade-bcb6-4e29-9051-fcb5a482c7ef)

I tested with 2023.11.12+76b91a3ef (current master) and it works and I tested some instances from searx.space and version 2023.11.11 .. no issues.

Did you customized CSS or JS?

**Comment by unixfox** [comment]
Can't replicate either on https://paulgo.io/

On searx.space, for [search.inetol.net](https://search.inetol.net/) it says the instance is customized.

![image](https://github.com/searxng/searxng/assets/4016501/abed64dd-122d-4b27-93f7-27ab06d77fe5)

**Comment by WreckingBANG** [comment]
I did not customize my css, i will check for errors on my instance tomorrow

**Comment by WreckingBANG2** [comment]
https://search.sapti.me does not use custom css and has the same error. 
![grafik](https://github.com/searxng/searxng/assets/117087198/496f5527-7b00-4299-bae0-2194b3c49acf)

**Comment by return42** [comment]
I guess the initialization fails due to this exception, when the page is loaded.

![grafik](https://github.com/searxng/searxng/assets/554536/1424bb6a-7238-41a0-b428-f36d97261919)

This line raises the error ..

https://github.com/searxng/searxng/blob/76b91a3ef685e288cc54e6a1131760d9c68faff0/searx/static/themes/simple/src/js/main/results.js#L19

But I do not understand why / and why it works in current master but not on some of the instances.

**Comment by BernieHuang2008** [comment]
According to the error message, it seems that the script is loaded before HTML, but I'm not sure, and this can't explain why it failed sometimes.

**Comment by return42** [comment]
> According to the error message, it seems that the script is loaded before HTML, but I'm not sure, and this can't explain why it failed sometimes.

The HTML loads the CSS and then JS .. but for some reasons the instances with this issue miss the button in the sidebar:

![image](https://github.com/searxng/searxng/assets/554536/f0163ed8-6188-4e96-a43f-aa238968853c)

https://github.com/searxng/searxng/blob/76b91a3ef685e288cc54e6a1131760d9c68faff0/searx/templates/simple/elements/search_url.html#L4

![image](https://github.com/searxng/searxng/assets/554536/e2d4368f-3764-46e3-afc4-2234f13b2bf6)

Aah .. here is the reason .. URL is only shown in HTTP POST request: 

https://github.com/searxng/searxng/blob/76b91a3ef685e288cc54e6a1131760d9c68faff0/searx/templates/simple/results.html#L56-L58

When set to ``GET`` ..

https://github.com/searxng/searxng/blob/76b91a3ef685e288cc54e6a1131760d9c68faff0/searx/settings.yml#L89

there is no URL in the sidebar!
@BernieHuang2008 can you please fix it (here):

https://github.com/searxng/searxng/blob/76b91a3ef685e288cc54e6a1131760d9c68faff0/searx/static/themes/simple/src/js/main/results.js#L19

**Comment by extremelyonline** [comment]
Hello, I encountered a similar issue but only on the mobile site. In my testing, the image click doens't work on:
```
priv.au
search.inetol.net
paulgo.io 
opnxng.com
```
However, it works on:
```
331221.xyz
searx.be
```
I did my testing on Android Cromite, with ad block and incognito mode disabled.

**Comment by BernieHuang2008** [comment]
@return42 

I apologize for my mistake, now it's solved in #3006, please have a look ~

**Comment by return42** [comment]
> I apologize for my mistake, 

no need to apologize .. its a *complex thing* .. don't ask how many mistakes I do every day ;)

**Comment by WreckingBANG** [comment]
Thank you for fixing it that quickly!👍
