### ISSUE TITLE
[BUG] Images are moving if I click on navigaton button

### ISSUE THREAD

**Issue by inson1** [searxng/searxng#3017]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

https://searx.kutay.dev/
2023.11.14+b3d29cb86

**How To Reproduce**

![brave_2HbEXi8zVV](https://github.com/searxng/searxng/assets/75314629/62a75fa8-6985-4211-9fdd-a385d63ea02c)
![brave_Nnjv2L54OB](https://github.com/searxng/searxng/assets/75314629/3accc9e6-e0c5-4813-a326-7bba55369ded)
![brave_rZ7oKNYmPG](https://github.com/searxng/searxng/assets/75314629/7500baeb-5cf0-42bf-ba2c-c77fdd4b5192)

**Comment by return42** [comment]
@mrpaulblack  I can confirm the issue exists when clicking on the left/right arrows to navigate from one image to the next.  The keyboard navigation does not have this issue --> I assume its an issue with the focus that is moved when the mouse-click is done / but not when navigate via keyboard.

**Comment by dalf** [comment]
Late answer: this is actually intended (even if the implementation could be better).
On small screen, the detail might hide the search field at least partially ; so when the first images are displayed, the detail height is reduced to make sure the search field is visible.
I agree on bigger screen, this is ... disturbing.

**Comment by return42** [comment]
> Late answer: this is actually intended (even if the implementation could be better).

IMO its not OK and there other bugs .. checkout current master, `make run`, query for `!images bmw`, scroll down and click on picture somewhere in the middle of the result list .. the sidebar opens the gallery-view .. in this view click on the arrow buttons (in the gallery-view) and you will see that the left side and the header are hopping in a very crazy manner ..

**Comment by ahmad-alkadri** [comment]
Did some checks and basically added some lines that prevent default actions done by browser.

Commit link: https://github.com/searxng/searxng/pull/3074/commits/d8fcb40c7ddf24e5ff27ab5ec3b29adca240233f

PR draft up #3074, @return42 @dalf would you like to check it? Could potentially fix this, though definitely open to more inputs. Thanks in advance.
