### ISSUE TITLE
Bug: qwant news engine

### ISSUE THREAD

**Issue by immerzu** [searxng/searxng#3020]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.11.14+b3d29cb86

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by return42** [comment]
Please fill out the form / otherwise we can't help.

Further give a hint, what instance do you use.

**Comment by return42** [comment]
Close for lack of feedback / qwant itself did work.
