### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by un99known99** [searxng/searxng#3031]
while  ddg search enabled:

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.11.23+cc6058057

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 50
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/engines/duckduckgo.py:119`
  * Function: `get_vqd`
  * Code: `res = get(query_url)`

![grafik](https://github.com/searxng/searxng/assets/1615207/74d0ecad-e744-42fb-916a-ed4465cafefa)

**Comment by return42** [comment]
Did you have a redis DB? .. the reliability of your ddg engine is at 50% --> to optimize the reliability of ddg accesses, the result value of `get_vql` is stored in the redis DB for about 10min.

Is your instance puplic? / do you have a URL for us?

BTW a activated limiter (with a redis DB) will protect the  engine from bot requests what will additional improve the  reliability of the ddg accesses.

We cannot completely avoid the `SearxEngineAccessDeniedException` error, but the ddg engine should still work reliably: for example [the ddg engine on my instance](https://darmarit.org/searx/stats?engine=duckduckgo) has reported `SearxEngineAccessDeniedException`, but the over-all reliability is at 100%.

**Comment by un99known99** [comment]
@return42 

* no, I don't have a redis DB
* private instance

anything I can help with / provide more info, just let me know

**Comment by return42** [comment]
> no, I don't have a redis DB

To improve reliability add a redis DB / as I mentioned above; with the `vqd` caching in the redis DB the ddg requests are reduced.

**Comment by un99known99** [comment]
@return42 
is there a kind of "howto" to setup a redis DB?

**Comment by return42** [comment]
If you use a docker image there is already one [included](https://github.com/searxng/searxng-docker#what-is-included-) .. but you said yo did not have one .. there is a script, see [Redis Developer Notes](https://docs.searxng.org/admin/settings/settings_redis.html#redis-developer-notes) .. but may be its the best you use the official [Install Redis](https://redis.io/docs/install/install-redis/) instruction .. but don't forget to set the redis url in your settings:

https://github.com/searxng/searxng/blob/a85274eff5f41794521bcf9eccc7ec75614be6c5/searx/settings.yml#L97-L100

**Comment by un99known99** [comment]
hm, I am a bit "lost", so if I get u right, redis will just be installed as described.

User/group stuff will be auto-setup via redis install?

In searXNG only the settings.yml will be adjusted to just uncomment the url?


url: unix:///usr/local/searxng-redis/run/redis.sock?db=0

Do you know how much mem redis grabs?

redis install to be run as searxng user?

**Comment by unixfox** [comment]
I think you should create a GitHub discussions or join our matrix: https://matrix.to/#/#searxng:matrix.org or IRC: https://web.libera.chat/?channel=#searxng
Because this is a bit off-topic to the original discussion.

**Comment by return42** [comment]
I'm going to close this issue since DDG did work / and is less blocked with the limiter activated.
