### ISSUE TITLE
Miniatures not loading in web search results due to Content Security Policy

### ISSUE THREAD

**Issue by Kaligula0** [searxng/searxng#3046]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

I'm a user of https://search.demoniak.ch which now shows "2023.11.29+5a72977ef" in footer.

**How did you install SearXNG?**

I'm only a user.

**What happened?**

Whatever I'm trying to search (in first=Main=General tab, not Images) no images (miniatures) can be loaded. Console shows an error:
```
Refused to load the image 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgk…' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**How To Reproduce**

Open the search engine web page, type the search string of something that may include images in response and hit Search.

**Expected behavior**

Miniature should load near each search result.

**Screenshots & Logs**

![image](https://github.com/searxng/searxng/assets/3950811/52ad0b1e-c2d3-4278-aa28-8fb8154b5eef)

**Additional context**

**Comment by return42** [comment]
> I'm a user of https://search.demoniak.ch/

There is not much we can do .. but in the meantime the maintainer of https://search.demoniak.ch/ has fixed the CSP / I tested and it no works.

**Comment by Kaligula0** [comment]
You're right, it works on other servers. Still doesn't work on demoniak.ch, even after wiping preferences, so it must be their local thing. Thanks.

**Comment by return42** [comment]
> Still doesn't work on demoniak.ch, even after wiping preferences, so it must be their local thing.

Sure? .. I do not haven an issue with: 

- https://search.demoniak.ch/search?q=dogs+cats&category_news=&language=en&time_range=&safesearch=0&theme=simple

I get this response ..

![grafik](https://github.com/searxng/searxng/assets/554536/958d334c-d2f9-4ff8-adce-c8209f471c67)

**Comment by Kaligula0** [comment]
I investigated further – this happens with Google results.
