### ISSUE TITLE
Bug: wolframalpha engine

### ISSUE THREAD

**Issue by NanashiTheNameless** [searxng/searxng#3065]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.12.11+8a4104b99

**How did you install SearXNG?**

**What happened?**

I searched for "test1212" qnd was faced with the wolfram error

**How To Reproduce**

Im unsure of the cause at present 

**Expected behavior**

Search normally

**Screenshots & Logs**

**Additional context**

I'm using a private instance

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('400', 'Bad Request', 'www.wolframalpha.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Thanks for your bug report,

> I searched for "test1212"

sadly I can't reproduce the issue / `!wa test1212` ends on my side in an empty result but without an error .. can you give us more hints how to reproduce?

Did you configured `wolframalpha` engine to use the `wolframalpha_api` or you just tested the default configured `wolframalpha_noapi`? 

https://github.com/searxng/searxng/blob/2863b0f6daed89e228075ba3af3df0984474b87c/searx/settings.yml#L1852-L1864

**Comment by NanashiTheNameless** [comment]
It appears as though this bug was a one-off as now it is working fine. I appreciate you looking into it
