### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by vfosnar** [searxng/searxng#3098]
**Is your feature request related to a problem? Please describe.**
Configuration can't always be backwards compatible. I need to be aware of deprecated options or new options that may negatively affect the security and privacy, like introducing new search engine enabled by default.

**Describe the solution you'd like**
Switch to semantic versioning.

**Describe alternatives you've considered**
Using the latest tag - rolling release, this is not solving the problem

**Additional context**
None

**Comment by unixfox** [comment]
No, searxng is in rolling release because the engines can change at any time.

Hence you need to always be on latest.
