### ISSUE TITLE
inconsistent ouput of `$(pyenv.cmd wlc lock-status)`

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#310]
See https://github.com/searxng/searxng/runs/3564689542?check_suite_focus=true#step:6:367

The output of `$(pyenv.cmd wlc lock-status)` is 
```
PYENV     [check] import yaml --> OK
PYENV     OK
locked: True
PYENV     [check] import yaml --> OK
PYENV     OK
```

So this check fail:
https://github.com/searxng/searxng/blob/75daef8986142bff65ef67aff4f278e41a4d0854/manage#L165-L167

It can be reproduce locally:
* `VERBOSE=1 ./manage pyenv.cmd wlc lock-status`
* `VERBOSE=0 ./manage pyenv.cmd wlc lock-status`

---

Possible fixes:
* `$(VERBOSE=0 pyenv.cmd wlc lock-status)`
* Enable the virtualenv since everything runs inside `( set -e .... )`:
https://github.com/searxng/searxng/blob/75daef8986142bff65ef67aff4f278e41a4d0854/manage#L392-L393
-->
```sh
    (   set -e
        # shellcheck source=/dev/null 
        source "${PY_ENV_BIN}/activate" 
        if [ "$(wlc lock-status)" != "locked: True" ]; then
            die 1 "weblate must be locked, currently: $(wlc lock-status)"
        fi
        # weblate: commit pending changes
        wlc pull
        wlc commit
...
```

**Comment by return42** [comment]
> The output of `$(pyenv.cmd wlc lock-status)` is 
> ```
> PYENV     [check] import yaml --> OK
> PYENV     OK
> locked: True
> PYENV     [check] import yaml --> OK
> PYENV     OK
> ```

Hm, not for me ...

```
$ VERBOSE=1 ./manage pyenv.cmd wlc lock-status
PYENV     [check] import yaml --> OK
PYENV     OK
+ local/py3/bin/python -c 'import sys; sys.path.pop(0); import  searx ;'
+ wlc lock-status
locked: False
```
> Enable the virtualenv since everything runs inside ( set -e .... )

The example you give is from docker.build, this command is different.  This is what pyenv.cmd does: open a subshell, activate virtualenv and run a command in the subshell ..

https://github.com/searxng/searxng/blob/13a4d20e8dc3fbad8f4094b318a96153d563823e/utils/lib.sh#L718-L726


Why https://github.com/searxng/searxng/runs/3564689542?check_suite_focus=true#step:6:367 fails is not clear to me right now, I have to dig ...

**Comment by dalf** [comment]
> This is what pyenv.cmd does: open a subshell, activate virtualenv and run a command in the subshell ..

The first thing `pyenv.cmd` does is to make sure the virtualenv is setup correctly with `pyenv.install` (the version in `./manage` not the one in `./utils/lib.sh` if I understand correctly ):
https://github.com/searxng/searxng/blob/76e0f6807ccddb12ca9efe3b2343735d6e1777d4/utils/lib.sh#L718-L726

This is why `$(pyenv.cmd python -c "print('foobar')")` can be actually output more than "foobar": when `VERBOSE=1`, `pyenv.install` outputs different things (like `PYENV     [check] import yaml --> OK` etc...).

So 
```bash
#!/bin/sh
CMD='print("foobar")'
if [ "$(./manage pyenv.cmd python -c "${CMD}")" == "foobar" ]; then
  echo 'true'
else
  echo 'false'
fi
```
displays false if `VERBOSE=1`

**Comment by return42** [comment]
> This is why `$(pyenv.cmd python -c "print('foobar')")` can be actually output more than "foobar": when `VERBOSE=1`, 

Ooops .. sorry, now I understand. I haven't tested but I think, the following patch should fix the issue ..

```diff
diff --git a/manage b/manage
index bd89e7f2..8ca77897 100755
--- a/manage
+++ b/manage
@@ -162,7 +162,7 @@ weblate.to.translations() {
     #    remote 'weblate' and push it on branch 'translations' of 'origin'
 
     (   set -e
-        if [ "$(pyenv.cmd wlc lock-status)" != "locked: True" ]; then
+        if [ "$(VERBOSE=0 pyenv.cmd wlc lock-status)" != "locked: True" ]; then
             die 1 "weblate must be locked, currently: $(pyenv.cmd wlc lock-status)"
         fi
         # weblate: commit pending changes
```

**Comment by dalf** [comment]
It works (see the initial comment), but this is wordy solution.
I wish a simpler implementation on the long run.

**Comment by return42** [comment]
> I wish a simpler implementation on the long run.

I don't have a clue how to make it simpler.  The intention of the `./manage pyenv.cmd` command was to build up (or update) the whole environment if it does not exists (or is not up-to-date).   Building up the environment might run installation procedures and other task like testing the environment (everything, what is needed to have a up-to-date environment).  Those task might have some output on stdout especially when a _verbose_ option is set or inherited from the superordinate process.

**Comment by dalf** [comment]
What about this ?

In `utils/lib.sh` :
```sh
pyenv.activate() {
	pyenv.install
        # shellcheck source=/dev/null
	source "${PY_ENV_BIN}/activate"
	[ "$VERBOSE" = "1" ] && set -x
}
```

In `manage`:
```sh
weblate.to.translations() {
    ...
    (   set -e
        pyenv.activate
        if [ "$(wlc lock-status)" != "locked: True" ]; then
            die 1 "weblate must be locked, currently: $(wlc lock-status)"
        fi
        # weblate: commit pending changes
        wlc pull
        wlc commit
        ...
```

**Comment by return42** [comment]
A new function `pyenv.activate` seems a good solution to me.  I suppose there are other use cases in the future where we could need such a function.

**Comment by dalf** [comment]
See PR #327
 
All `pyenv.cmd` inside `( set -e ... )` can be replaced by `pyenv.activate`.
So it adds complexity: either `pyenv.cmd`, either `pyenv.activate`.

Why not activate the virtualenv at the top of `./manage`. 
* activate = try to activate the virtualenv, if it is not there, no error
* `pyenv.install` can ensure the virtualenv is installed and activate when it is required. --> no need for `pyenv.cmd`

**Comment by return42** [comment]
> Why not activate the virtualenv at the top of `./manage`. 

The environment should be activated when it is needed / may be we have tasks where we do not need or do not want to have this environment active.

**Comment by dalf** [comment]
> The environment should be activated when it is needed

-->

> activate = try to activate the virtualenv, if it is not there, no error

But differently, about this code:
```sh
gecko.driver() {
    pyenv.install

    build_msg INSTALL "gecko.driver"
    # run installation in a subprocess and activate pyenv
    (   set -e
        pyenv.activate
        ...
```

Is there an issue with:
```sh
gecko.driver() {
    pyenv.activate

    build_msg INSTALL "gecko.driver"
    # run installation in a subprocess and activate pyenv
    (   set -e
        ...
```
?

==> 

* Currently: `./manage` run with the virtualenv deactivate, and activate only on some locations with subshell calls.
* Possible change: `./manage` activates the virtualenv globally when it is required.

**Comment by return42** [comment]
> no need for pyenv.cmd

that is right, `pyenv.cmd` was intended for the easiness of command line usage and the pylint.activate (you suggested) fits better to bash scripting (IMO).

> activate = try to activate the virtualenv, if it is not there, no error

Not sure I understand you fully, but from my POV, commands should be stateless / I mean, when call a command to activate an environment I want this environment to be activated, if this fails for some reason I want to see an error / not sure if this was what you mean.

```sh
gecko.driver() {
    pyenv.install

    build_msg INSTALL "gecko.driver"
    # run installation in a subprocess and activate pyenv
    (   set -e
        pyenv.activate
        ...
```

The implementation above is _stateless_, the virutalenv is (only) activated in a subshell / the code in between the parenthesis `( ... )`. Since the virtualenv is only activated in the  subshell, the environment of the caller left _untouched_.

In the implementation below, the environment is activated in the the _current_ shell. This means, the environment of the caller is touched.  IMO such an implementation is no longer _stateless_: suppose a command `foo` what needs a virtualenv (but does not activate it), it will run flawless when gecko.driver is called before but it will fail when after foo was called.

```sh
gecko.driver() {
    pyenv.activate

    build_msg INSTALL "gecko.driver"
    # run installation in a subprocess and activate pyenv
    (   set -e
        ...
``` 

I suggest to use `pyenv.cmd` for simple use cases, 

```sh
foo(){
   pyenv.cmd ... # simple call of a command in the virtualenv
}
```

and for more elaborate scripting I recommend to use a subshell which uses the `pyenv.activate`

```sh
foo(){
    (   set -e
        pyenv.activate
        ...  # some scripting in the virtualenv
}
```
