### ISSUE TITLE
Bug: bt4g engine

### ISSUE THREAD

**Issue by lsnnt** [searxng/searxng#3110]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.12.31+3535377c9

**How did you install SearXNG?**

By using Docker
**What happened?**

Access denied

**How To Reproduce**

search for any torrent file in files tab in searxng

**Expected behavior**

it shows access denied

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by unixfox** [comment]
Unfortunately the service is blocking the access to you.

Nothing we can do on our side.

On top of that, it's odd because bt4g still works perfectly on my public instance.
