### ISSUE TITLE
Bug: solidtorrents engine

### ISSUE THREAD

**Issue by lsnnt** [searxng/searxng#3111]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.12.31+3535377c9

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by lsnnt** [comment]
same problem as #3110

**Comment by unixfox** [comment]
Unfortunately the service is blocking the access to you.

Nothing we can do on our side.

On top of that, it's odd because solidtorrents still works perfectly on my public instance.
