### ISSUE TITLE
Bug: reddit engine

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng#3112]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.1.9+54a662658

**How did you install SearXNG?**

**What happened?**

Trying to search

**How To Reproduce**

Search with Reddit included

**Expected behavior**

No error

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by unixfox** [comment]
closing as works for me.

Please be a bit more descriptive with your github issues...

**Comment by privacyguy123** [comment]
Not sure what else to provide ... just getting access denied every time.
