### ISSUE TITLE
Time-frame searches with Presearch are not correctly filtered

### ISSUE THREAD

**Issue by geckolinux** [searxng/searxng#3115]
**SearXNG 2024.1.9+54a662658**, not forked.

**How did you install SearXNG?**
`searxng-docker`

Hi there, I really like the results that I get from Presearch in SearXNG because Presearch itself is a meta search engine that pulls from the three best search indexes (Google, Bing/DuckDuckGo, and Yandex).

Apart from that I have also enabled: Brave, Mojeek, Qwant, Stract, and Yep.

I assume that the other ones except Brave don't support searches filtered by time ranges, because when I select the "Last week" time filter it usually shows only results from Presearch (with one strange exception that I'll show later). However, the results that appear are not correctly filtered.

To test this I searched for some random Linux distribution names from Distrowatch.com that aren't very popular and I filtered by "Last week".

SearXNG shows the original canonical page for the distribution name, and older reviews that mention the product name, but none of those pages have been updated within the last week.

On the other hand, the same query on presearch.com correctly shows only a few results, mainly in things like frequently updated tag / index list pages where the distribution name appeared in an old article.

----

<img src='https://github.com/searxng/searxng/assets/2692138/00b2df91-c8e6-401c-823b-9fdfe9371768' width='450'>

<img src='https://github.com/searxng/searxng/assets/2692138/69c00902-f60e-4430-9e75-73c9cf896fa8' width='450'>

----

<img src='https://github.com/searxng/searxng/assets/2692138/21f5dd70-d09e-4624-8d00-d7f43e0f59c5' width='450'>

<img src='https://github.com/searxng/searxng/assets/2692138/e992031a-691d-4ebc-afde-a221ea287451' width='450'>

----

<img src='https://github.com/searxng/searxng/assets/2692138/7d6e3e7f-51d4-4c20-8078-e233d87fe83a' width='450'>

<img src='https://github.com/searxng/searxng/assets/2692138/0b6ca675-fff5-4b96-a454-9d0488099b37' width='450'>

**Comment by return42** [comment]
> Apart from that I have also enabled: Brave, Mojeek, Qwant, Stract, and Yep.
> I assume that the other ones except Brave don't support searches filtered by time ranges,

FYI; if Safe-Search and Time-Range are supported is shown in the preferences .. see check boxes

![image](https://github.com/searxng/searxng/assets/554536/661148ae-bac6-4fbc-b71f-54550ca59b79)

![image](https://github.com/searxng/searxng/assets/554536/b8c5962c-33a6-4b4b-8593-ed31665ce666)

--> brave and presearch support Time-Range query.

Seems presearch engine has an issue with the `time=week` argument? @Bnyro As far I have tested .. the first hits in the result table are always the same .. whatever date range I use / can you have a look?

**Comment by Bnyro** [comment]
Opened https://github.com/searxng/searxng/pull/3123.

**Comment by geckolinux** [comment]
Thank you very much, the fix seems to work great.
