### ISSUE TITLE
Brave search results miss description, and title is prepended by site name and page url

### ISSUE THREAD

**Issue by allixx** [searxng/searxng#3167]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

559b8606189ff44eee6e8bcde2763daf3c2cbd7c

**How did you install SearXNG?**

**What happened?**

I've noticed most (if not all) search results coming from Brave are malformed: results titles include site name and result url (in breadcrumbs form), followed by the actual results page title.
Also, most of results descriptions are empty (This site did not provide any description).

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

![brave_results](https://github.com/searxng/searxng/assets/1695323/c227a496-b03a-41a9-9323-b3074b98cdc5)

**Additional context**

**Comment by return42** [comment]
@allixx thanks for your bug report :+1: .. I implemented PR

- https://github.com/searxng/searxng/pull/3168

If you have the ability, you can test the PR ..
