### ISSUE TITLE
Remove `X-XSS-Protection` headers. (Deprecated header not used by browsers nowadays)

### ISSUE THREAD

**Issue by Fijxu** [searxng/searxng#3171]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Consider the removal of X-XSS-Protection headers in:
https://github.com/searxng/searxng/blob/90072eb6ff2a7c402ab47f2d8c973e6b24116795/searx/settings.yml#L91
https://github.com/searxng/searxng/blob/90072eb6ff2a7c402ab47f2d8c973e6b24116795/tests/unit/settings/user_settings.yml#L22
https://github.com/searxng/searxng/blob/90072eb6ff2a7c402ab47f2d8c973e6b24116795/docs/admin/settings/settings_server.rst#L19

**Describe alternatives you've considered**

Make use of the `Content-Security-Policy` header instead.

**Additional context**

I will not reinvent the wheel so I will just cite the sources.

*"In modern browsers, X-XSS-Protection has been deprecated in favor of the Content-Security-Policy to disable the use of inline JavaScript. Its use can introduce XSS vulnerabilities in otherwise safe websites. This should not be used unless you need to support older web browsers that don’t yet support CSP. It is thus recommended to set the header as X-XSS-Protection: 0."* 
https://infosec.mozilla.org/guidelines/web_security#x-xss-protection

There is no need to use `X-XSS-Protection` unless we want to support the <2010 version of Chrome or the <2015 version of Microsoft Edge. Other browsers like firefox never implemeneted or make use of this header so it makes no sense to use it nowadays because no browser uses it. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by return42** [comment]
@Fijxu thanks a lot for pointing out / I prepared PR #3173
