### ISSUE TITLE
Defect: searxng.min.js - Code does not check for null value - this results in failed listener activation

### ISSUE THREAD

**Issue by kent57** [searxng/searxng#3172]
This code defect  presents itself as the date_range listener not working.
Note: This was not found to be a problem with the docker container version  (only searxng/searxng)

Debug method: client browser developer tools - debug.  showed the listener was not active.

Before Code Change:
 var a = window.searxng || {}
  35     a.on = function (r, e, o, t) {
  36         t = t || false
  37         //
  38         if (typeof r !== 'string' ) {
  39             r.addEventListener(e, o, t)
  40         } else {
  41             i.addEventListener(
  42                 e,
  43                 function (e) {
  44                     var t = e.target || e.srcElement,
  45                         n = false
  46                     while (t && t.matches && t !== i && !(n = t.matches(r)))
  47                         t = t.parentElement
  48                     if (n) s(o, t, e)
  49                 },
  50                 t
  51             )
  52         }
  53     }

AFTER CODE CHANGE:
 var a = window.searxng || {}
  35     a.on = function (r, e, o, t) {
  36         t = t || false
  37         // 1/30/2024 added && r !== null
  38         if (typeof r !== 'string' && r !== null) {  
  39             r.addEventListener(e, o, t)
  40         } else {
  41             i.addEventListener(
  42                 e,
  43                 function (e) {
  44                     var t = e.target || e.srcElement,
  45                         n = false
  46                     while (t && t.matches && t !== i && !(n = t.matches(r)))
  47                         t = t.parentElement
  48                     if (n) s(o, t, e)
  49                 },
  50                 t
  51             )
  52         }
  53     }

**Comment by return42** [comment]
@kent57 please use [markup to format code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) and use `git diff` to show us what you have changed / otherwise we do not know what code you refer.

**Comment by unixfox** [comment]
Closing as the bug report is invalid, we do not understand what you say.
