### ISSUE TITLE
Image search: show resolution beneath title or url

### ISSUE THREAD

**Issue by ddogfoodd** [searxng/searxng#3177]
**Is your feature request related to a problem? Please describe.**
When searching for images it is quite annoying to click at all the images just to notice their resolution doesn't fit my need. Probably not all engines provide a resolution but for those who do, it would be great to show it beneath the image title or url.

**Describe the solution you'd like**
I would like to see the resolution of images on the image search overview where possible. An option to enable/disable would be even better.

**Describe alternatives you've considered**
Use another search engine for image search or click on every image and hope for the best. A filter function to only show certain resolutions would be another possible solution.

**Comment by return42** [comment]
>  it would be great to show it beneath the image title or url.

@jalemann thanks to the PR https://github.com/searxng/searxng/pull/3231 from @Bnyro the resolution (if available) is shown in the thumbnails ..

![image](https://github.com/searxng/searxng/assets/554536/a4bfcd7a-5849-40ea-89a7-c960d6bd15a1)

**Comment by ddogfoodd** [comment]
@Bnyro thank you for the time and effort, looks great and vastly improves the usability of the image search!
