### ISSUE TITLE
Feature Request: Site favicons and friendly names

### ISSUE THREAD

**Issue by LoganJFisher** [searxng/searxng#3184]
**Is your feature request related to a problem? Please describe.**
Placing the favicons of websites next to their friendly names above a smaller font size URL helps make websites more easily identifiable at a glance. This often results in finding the results you're looking for much quicker. For reference, see Google or Bing search results.

**Describe the solution you'd like**
Including the favicons of websites next to their friendly names above smaller font size URLs in the search results

**Describe alternatives you've considered**
No alternatives have occurred to me.

**Additional context**
None

**Comment by return42** [comment]
Discussed in:

- https://github.com/searxng/searxng/pull/441#issuecomment-997636405
- https://github.com/searxng/searxng/issues/1014
- https://github.com/searxng/searxng/issues/2162
- https://github.com/searxng/searxng/issues/2809

**Comment by LoganJFisher** [comment]
I've looked at every instance of SearXNG on Searx.Space and didn't see this feature present on any of them.

**Comment by YannBirba** [comment]
Sorry for pinging, so is this feature planned in the developement ?

**Comment by LoganJFisher** [comment]
I should note that I'm now self-hosting SearXNG, and even there, I'm not seeing favicons and friendly names.

I used Container Manager for a Synology NAS, with this image: https://registry.hub.docker.com/r/searxng/searxng

I made no edits to the image. If this image is out of date, please let me know.

**Comment by YannBirba** [comment]
Same here ✋ ! Using the same image in arm64 for my rasp 4. Using latest, i update as soon as the image is updated every time

**Comment by return42** [comment]
> I've looked at every instance of SearXNG on Searx.Space and didn't see this feature present on any of them.

Did you ever had a look at the comments I linked above? To be clear: **This feature has been discussed often in the past, but has been never implemented for some reasons**, mentioned in the articles I linked above.

Please read the comments:

- https://github.com/searxng/searxng/pull/441#issuecomment-997636405
- https://github.com/searxng/searxng/issues/1014#issuecomment-1079044776
- https://github.com/searxng/searxng/issues/2162#issuecomment-1417126895
- https://github.com/searxng/searxng/issues/2809#issuecomment-1722540330
