### ISSUE TITLE
Feature Request: Embed OpenStreetMap into "Map" search tab

### ISSUE THREAD

**Issue by LoganJFisher** [searxng/searxng#3185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Replicate the functionality of the Maps tab on Google by embedding OpenStreetMap

**Describe alternatives you've considered**
No alternatives have occurred to me.

**Additional context**
None.

**Comment by return42** [comment]
OSM is already in --> https://docs.searxng.org/user/configured_engines.html#tab-map
