### ISSUE TITLE
Error in gihub CI while running script: Update data - update_currencies.py

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3205]
When I run on my desktop:

```
$ V=1 ./manage pyenv.cmd python searxng_extra/update/update_currencies.py 
```

it updates the currencies flawlessly.  In the github CI the HTTP request from the wikidata query [ends wit a timeout](https://github.com/searxng/searxng/actions/runs/7689352816/job/21438235435#step:6:118)

```
File "searx/engines/wikidata.py", line 162, in send_wikidata_query
    http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
...
httpx.ReadTimeout
Error: Process completed with exit code 1.
```

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/pull/3206

(just a temporary timeout)
