### ISSUE TITLE
utils/searxng.sh uses searx.shared module which no longer exists 

### ISSUE THREAD

**Issue by KalokaK** [searxng/searxng#3224]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

commit number : 76845ea42c2c3484e30c118f07671b13ade07a29

**How did you install SearXNG?**

install script, following the wiki

**What happened?**
running: 
 ```sh
sudo -H ./utils/searxng.sh install all
```
(as per [the wiki](https://docs.searxng.org/admin/installation-scripts.html) after cloning)

one gets the following output in the section on "do you want to install a reverse proxy"
```
Do you want to install a reverse proxy [YES/no] 
Yes

Install nginx site searxng.conf
===============================

This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
located at: /etc/nginx/default.apps-available/searxng.conf and requires
a uWSGI.
INFO:  uWSGI socket is located at: /usr/local/searxng/run/socket
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'searx.shared'

The configured redis DB is not available: If your server is public to
the internet, you should setup a bot protection to block excessively
bot queries.  Bot protection requires a redis DB.  About bot protection
visit the official SearXNG documentation and query for the word 'limiter'.
```
The `ModuleNotFoundError: No module named 'searx.shared'` seemed strange to me. So I looked at the [searxng.sh](utils/searxng.sh). On line 699:
```sh
    if ! searxng.instance.exec python -c "from searx.shared import redisdb; redisdb.initialize() or exit(42)"; then
```
the import from `searx.shared` makes no sense, as a `shared` module does not exist in the current version of the repo. On line 299 you have a correct version of the same code:
```sh
    if searxng.instance.exec python -c "from searx import redisdb; redisdb.initialize() or exit(42)"; then
```
I suspect this is a bug as this check will always fail due to the `redisdb` module haveing been moved to searx
**How To Reproduce**

Clone the repo run the install script
**Expected behavior**

bash ckeck should fail (or succeed) based on the state of the redisdb not based on the fact a module does not exist.
**Screenshots & Logs**

not applicable
**Additional context**

**Comment by KalokaK** [comment]
If this is actually just a (minor) bug, I have fixed it in a fork and could create a PR to here if you want me to. Somehow me closing it on my fork has closed it here???

**Comment by Bnyro** [comment]
> If this is actually just a (minor) bug, I have fixed it in a fork and could create a PR to here if you want me to.
>
PRs are always welcome, please open one for sure :+1:

> Somehow me closing it on my fork has closed it here???
>
Yes, GitHub closes any issue you mention with `closes <issuelink>` which you have permissions for (either in your repos or because you opened the issue).
