### ISSUE TITLE
Default time range 

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#3243]
I am mainly looking for results from last year. That's why I often have to change the time range before sending the search query.

My suggestion: an additional setting option for a default value for time range.

**Comment by return42** [comment]
I vote against such an option: be aware, when time range is used (is a default) only engines with [time range support](https://docs.searxng.org/user/configured_engines.html#tab-general) are active .. most engines do not have a time range or support of .. this might confusing when searching in [`!map berlin`](https://darmarit.org/searx/search?q=%21map+berlin&language=auto&time_range=year) with a time range --> no results

**Comment by Bnyro** [comment]
I agree with @return42 on this - additionally, I don't really see the point of having such an option:
1. Most engines usually start by providing the most recent / up to date results anyways
2. 99% of the users will never even use the time range search

Overall, this really looks like a niche feature and I don't think we should add more options for only very few people that would use this.

**Comment by Talk2Giuseppe** [comment]
Both arguments are valid.  Perhaps we can have the results sorted by TIME where time exists, and all other results follow or can be omitted as an option by the user.   Time based results are vital for those who are looking for tech related solutions.  Hours are wasted reading solutions that are currently outdated by a decade.

**Comment by Bnyro** [comment]
> Both arguments are valid. Perhaps we can have the results sorted by TIME where time exists, and all other results follow or can be omitted as an option by the user. Time based results are vital for those who are looking for tech related solutions. Hours are wasted reading solutions that are currently outdated by a decade.
>
Hmm. Search engines usually sort results by relevance, so I don't think that we can generally say that more recent articles are more relevant. That especially applies even more since the last 2 years, as many very new articles are just LLM-generated SEO trash. In that case, the most recent articles are usually the worst.

**Comment by Talk2Giuseppe** [comment]
> I don't think that we can generally say that more recent articles are more relevant. That especially applies even more since the last 2 years, as many very new articles are just LLM-generated SEO trash. In that case, the most recent articles are usually the worst.

I would have to agree with that!  Would be nice if AI generated results were tagged somehow so that they can be skipped from being displayed.  Kinda like an ad blocker, but for AI.

**Comment by Bnyro** [comment]
> I would have to agree with that! Would be nice if AI generated results were tagged somehow so that they can be skipped from being displayed. Kinda like an ad blocker, but for AI.
>
That's the reason why I have opened https://github.com/searxng/searxng/pull/5804, but unfortunately its performance is currently not good enough for production yet - need to revisit it one day to see if a hash-based lookup approach could work.
