### ISSUE TITLE
[Docker] Persist TIMEOUT variable

### ISSUE THREAD

**Issue by mtompkins** [searxng/searxng#3248]
Thanks for this image, I've been using it for quite some time and really appreciate the privacy it provides.

I have one frustration that I can't seem to overcome .. on a new image the update overwrites the:
```
outgoing:
  request_timeout:
```

I'd love a way to pass this specific variable through docker in order to alleviate having to edit the `settings.yml` often.

Many thanks!

**Comment by return42** [comment]
> Please I have already moved the issue. That's not for nothing 😄.

Oops I'm sorry :facepalm:

**Comment by return42** [comment]
> I'd love a way to pass this specific variable through docker in order to alleviate having to edit the `settings.yml` often.

I'm not a docker expert, but there is a `./searxng:/etc/searxng:rw` volume for custom `settings.yml` --> https://github.com/searxng/searxng-docker/blob/8e3220be095d758b627afaa83ac8129823edfe94/docker-compose.yaml#L42-L43

For your custom settings I recommend to use [`use_default_settings: true`](https://docs.searxng.org/admin/settings/settings.html#use-default-settings)


```yaml

use_default_settings: true

outgoing:
  request_timeout: 3.0
```

**Comment by mtompkins** [comment]
Thank you for your reply, but the issue isn't addressed with what you've shared. 
Whomever handles your docker implementation simply needs to expose the variable.

**Comment by return42** [comment]
You want a environment variable for this setting?  .. why not in your /etc/searxng/settings.yml where you have all your custom settings?

**Comment by mtompkins** [comment]
> on a new image the update overwrites

**Comment by unixfox** [comment]
Reopening until I can try to replicate the potential issue.

**Comment by mtompkins** [comment]
> Reopening until I can try to replicate the potential issue.

Happy to provide a bit of how to replicate using docker compose.
```
  searxng:
    container_name: "searxng"
    # Note arbitrary older release
    image: "searxng/searxng:2024.1.17-7c80807bb"
    command: "-f"
    volumes:
	  # Note the persistent mount to keep settings preserved
      - "/opt/searxng:/etc/searxng:"
    environment:
      TZ: America/New_York
      BIND_ADDRESS: 0.0.0.0:8080
      BASE_URL: https://somewhere.com/
      INSTANCE_NAME: searx
      MORTY_URL: https://somewhere.com/morty/
      MORTY_KEY: xxxxxxx
```
Once properly configured based on the above, make a change to the settings file - for example the timeout from 3 to 13.
Then change to the `:latest` image and you'll see the settings file is overwritten.

HTH

**Comment by unixfox** [comment]
Maybe meanwhile try to force read only on the volume:
```
volumes:
      - "/opt/searxng:/etc/searxng:ro"
```

**Comment by mtompkins** [comment]
That is exactly what I've done - thank you. My fear is that some change to that file will get missed (like adding or removing search engines) and why I was looking to persist the settings :)

**Comment by unixfox** [comment]
No, if you use `use_default_settings: true` like explained here: https://github.com/searxng/searxng/issues/3248#issuecomment-1978225454

This won't matter.

**Comment by mtompkins** [comment]
> No, if you use `use_default_settings: true` like explained here: [#3248 (comment)](https://github.com/searxng/searxng/issues/3248#issuecomment-1978225454)
> 
> This won't matter.

AH!! I think it is the chosen description and choice of the variable from the doc that threw me.
I'll try this and revert. Thank you for your patience.

**Comment by mtompkins** [comment]
Ok I tried that approach and it spews a ton of errors. 
While I appreciate the replies I'm going to stop here. Please consider the ask of an Env Variable .. otherwise thank you.

**Comment by unixfox** [comment]
Closing as I don't have the time to investigate on the issue anymore. Sorry
