### ISSUE TITLE
Bug: bing engine

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#3264]
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.3.1+858b2071d

**How did you install SearXNG?**
Manual install (scripts)

**What happened?**
Bing throws a "Parsing error" in "engines" page, when performing a search. Nonetheless, results for Bing are displayed.

**How To Reproduce**
Just perform a search.

**Expected behavior**
No error should be thrown.

**Screenshots & Logs**
![brave_screenshot_searx catfluori de](https://github.com/searxng/searxng/assets/25054477/e44d0461-1f64-4bd9-b4fd-10ffe5883951)

**Additional context**
I suspect this behavior may cause slowdown of the instances where Bing is activated.

**Technical report**

Error
  * Error: lxml.etree.ParserError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/engines/bing.py:128`
  * Function: `response`
  * Code: `dom = html.fromstring(resp.text)`

**Comment by return42** [comment]
> I suspect this behavior may cause slowdown of the instances where Bing is activated.

Nope .. parsing errors do not slow down a instance / timeouts from engines do slow down an instance.

**Comment by dalf** [comment]
Related to the bing engine: the paging does not work.

**Comment by return42** [comment]
> Related to the bing engine: the paging does not work.

duplicate / (at least strong related):

- https://github.com/searxng/searxng/issues/3402
