### ISSUE TITLE
Add search-to-calculate feature to SearXNG

### ISSUE THREAD

**Issue by gigirassy** [searxng/searxng#3273]
**Is your feature request related to a problem? Please describe.**
I love the fact that SearXNG is so comprehensive, but when I realized that it surprising doesn't have a built-in option where you can calculate math problems (Algebra, weights and volumes counterparts, etc) by searching like most major search engines nowadays, it kinda bummed me. Here's an example of the calculate-by-search option on DuckDuckGo, so you know what I'm talking about.
![GIF of the math problem 6 x 10 x 20 being entered on DuckDuckGo's search. A calculator with 1200 filled in pops up.](https://i.imgur.com/GJhPwkR.gif)

**Describe the solution you'd like**
I feel that it'd be great if a feature like this was built into SearXNG instances for the convenience of the users, and so they don't have to pull up a different calculator everytime. We could use an open-source calculator for it, or have it built in as a feature in SearXNG with scripts.

**Describe alternatives you've considered**
Considering SearXNG's nature as a metasearch engine, we could also compile math problem answers from different search engines, IE Google and DuckDuckGo.

**Additional context**
[Here's an informational article about the Google search engine calculator function](https://www.calculatorlibrary.com/blog/the-google-calculator); it's existed since July 2012, and other search engines followed suit. So, I feel it's extra surprising SearXNG doesn't have it in some form.

Thank you all for your awesome work on this project!

**Comment by return42** [comment]
See my comment in #1022 --> https://github.com/searxng/searxng/pull/1022#issuecomment-1080201609

Duplicate:

- https://github.com/searxng/searxng/pull/1022
- https://github.com/searxng/searxng/issues/2191

Interim solution is to use WolframAlpha which is able to do more complex tasks

- [`!wa 6 x 10 x 20`](https://darmarit.org/searx/search?q=%21wa+6+x+10+x+20)
- [`!wa x = 1+ y²`](https://darmarit.org/searx/search?q=%21wa+x+%3D+1%2B+y%C2%B2)
