### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#3276]
The duckduckgo engine does not work anymore whatever instance.

**Comment by dalf** [comment]
Perhaps related same for duckduckgo image, duckduckgo videos and duckduckgo news: these engines don't work.

**Comment by return42** [comment]
> Perhaps related same for duckduckgo image, duckduckgo videos and duckduckgo news: these engines don't work.

we use ddg-lite for ddg-WEB .. ddg-lite does no longer have (need) a vqd value (ddg's bot protection) .. images, videos and news  from ddg still use bot protection based on the vqd value  .. I'm working on a solution.
