### ISSUE TITLE
Bug: mastodon users broken ?

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#3281]
I've searched for some profiles on mastodon.social without success. 
How to use this engine?

**Comment by Bnyro** [comment]
Works fine for me, e.g. `!mau Linux` doesn't work for you either?

**Comment by dalf** [comment]
Sorry, it works yes.
Actually I've search account name that don't exist... (alias that exists on other platform but not on mastodon...).

A relevant test must be written in settings.yml to avoid false negative during the checker tests.
