### ISSUE TITLE
Installation script doesn't work on AlmaLinux or Rocky Linux

### ISSUE THREAD

**Issue by jebofponderworthy** [searxng/searxng#3296]
### Discussed in https://github.com/searxng/searxng/discussions/3271

<div type='discussions-op-text'>

<sup>Originally posted by **jebofponderworthy** March  1, 2024</sup>
When I run the install script on my new Alma Linux 9.3, it seems to indicate that it doesn't know how to do the uwsgi and apache steps on Alma 9.3.  Everything else seems to go through beautifully.  

Also applies to Alma 8.</div>

![image](https://github.com/searxng/searxng/assets/8252044/94fcd088-f854-4c4b-9104-81c7c5703f08)

**Comment by Bnyro** [comment]
The same is the case for Void Linux though. I don't think we aim to support all available Linux distributions (100+)? Shouldn't we just focus on a few important ones like Debian and Alpine to make things easier to maintain?

(Talking to @unixfox)

**Comment by jebofponderworthy** [comment]
Ditto Rocky.  I've had great results with Ubuntu 20 and 22.  I'd love to see at least one free RPM-based.

**Comment by return42** [comment]
Sorry, we are not able to support all Linux distributions.

**Comment by unixfox** [comment]
Can we then write the Linux distribution that are supported in the docs?

**Comment by unixfox** [comment]
By the way @jebofponderworthy, if you have the knowledge we are not against code changes into the installation script if you want to support all the RHEL linux distributions.

**Comment by virtadpt** [comment]
> The same is the case for Void Linux though. I don't think we aim to support all available Linux distributions (100+)? Shouldn't we just focus on a few important ones like Debian and Alpine to make things easier to maintain?

I would have thought that the basic process laid out in the installation script could be executed, by hand, appropriately to whatever distro is in use.

**Comment by jebofponderworthy** [comment]
> By the way @jebofponderworthy, if you have the knowledge we are not against code changes into the installation script if you want to support all the RHEL linux distributions.

@unixfox , I think I can probably extend to AlmaLinux easily, given its code relationship to RH, and Rocky is probably as easy.  On Alma 9.3 I have the script running without errors until the very end, where it says:

`uWSGI socket not available at: /usr/local/searxng/run/socket`

I'm tending to think this is probably an OS-level firewall blockage.  Should I be unblocking a process (or two), or a port or two?  I know what a socket is, but am unclear on whether this is a TCP socket with a port number, or something else, and also, whether there might be a Searxng best practice to follow.

**Comment by jebofponderworthy** [comment]
> > The same is the case for Void Linux though. I don't think we aim to support all available Linux distributions (100+)? Shouldn't we just focus on a few important ones like Debian and Alpine to make things easier to maintain?
> 
> I would have thought that the basic process laid out in the installation script could be executed, by hand, appropriately to whatever distro is in use.

Probably.  And of course we have step-by-step in the docs.  But I like to use the script because of its automatic update capability.

**Comment by seulgiism** [comment]
i just had the same problem on my rocky linux machine...
decided to switch to debian since it seems to be the most stable, what do you know....it goes further but the socket is still missing and the redisdb as well... i think the install script is broken.

i tried doing the step-by-step install, but the uwsgi and redis steps are waaaaay above my level and i just can't wrap my head around it.

**Comment by return42** [comment]
> i just had the same problem on my rocky linux machine...

The installation scripts are only work on 

![image](https://github.com/searxng/searxng/assets/554536/48ae32e1-f230-444c-a4b9-2518f3114110)

TBH the step-by-step guide is generated by the installation scripts.

> i tried doing the step-by-step install, but the uwsgi and redis steps are waaaaay above my level and i just can't wrap my head around it.

The step-by-step is intended for those of us who are familiar with setting up services but do not have one of the distros listed in the screenshot above .. or do not want the installation scripts for other reasons.  Especially when it comes to set up a uWSGI service distros diverges massively (compare [How uWSGI is implemented by distributors varies.](https://docs.searxng.org/admin/installation-uwsgi.html#searxng-uwsgi) .. you need to know a lot of your distro to set up uWSGI).

Long story told shot:

If you have one of the distros from above, you **can** use the installation script .. but if you are not familiar with the details of services and the particularities of your distro, its recommended to use our docker image --> https://hub.docker.com/r/searxng/searxng

// most of the operators of a SearXNG instance will probably use the docker image.

Those of us who have problems with all three variants (script, step-by-step, docker), should not set up an instance, as running an instance also involves a certain amount of maintenance work ... alternatively there are a lot of public instances from where you can pick up one --> https://searx.space/

**Comment by seulgiism** [comment]
Hi,

I got it working by running the install script as root in my /opt/searx directory on a debian machine. I decided to go over each line and i saw there was something wrong with premissions despite using sudo on an user account.

I can't use the docker container; since I am also running multiple other services that uses nginx's webserver; so my only choices were using it step by step, since the RHEL commands also didn't do the trick for me.

**Comment by ACR-Jeff** [comment]
I have tried the install script, Step by step as well as also the docker-searxng on Debian 12 and am faced with similar issues, Nothing works. Even though the install script and step by step instructions claim to be for Debian, Nothing has worked, The docker was the closest I could get to loading searxng, Yet searching was null.

**Comment by ACR-Jeff** [comment]
Since I commented above, I figure I would update my issue to solved, I was having directory permission issues, I followed @return42 instructions 
in this issue https://github.com/searxng/searxng/issues/1669#issuecomment-1214936502
I proceeded with the searxng installation script instructions. Installed perfect
I also had an issue with nginx, Most likely because I am not experienced with nginx, So I went and followed the apache2 instructions and everything worked flawlessly. Thank you

**Comment by Raize** [comment]
I'm in the same scenario. Can't use the docker version on Rocky and the installation script doesn't work.

**Comment by return42** [comment]
> I'm in the same scenario. Can't use the docker version on Rocky and the installation script doesn't work.

This issue is in state "not planed", read here, why: https://github.com/searxng/searxng/issues/3296#issuecomment-2025604737
