### ISSUE TITLE
[Feature Request]: Redirecting to open source frontends

### ISSUE THREAD

**Issue by radiumatic** [searxng/searxng#3307]
**Is your feature request related to a problem? Please describe.**

It is a bit annoying to manually change URLs when browsing search results. Also, not all devices support userscripts or extensions for redirection.

**Describe the solution you'd like**

A new setting that allows to set alternative front ends for popular services.

**Describe alternatives you've considered**

Using a userscript or extension.

**Additional context**

Alternative Front-ends are projects intending to serve the content from popular platforms using an interface with less distractions and/or more privacy. Please see the following collections that list the mentioned projects and explain in more detail:

* https://github.com/mendel5/alternative-front-ends
* https://github.com/digitalblossom/alternative-frontends
* https://notabug.org/kzimmermann/alternative-frontends

**Comment by return42** [comment]
Is it a duplicate of ? ...

- https://github.com/searxng/searxng/pull/2946
- https://github.com/searxng/searxng/issues/1575
- https://github.com/searxng/searxng/issues/2351

Related tag [URL rewrite & filter](https://github.com/searxng/searxng/issues?q=is%3Aopen+label%3A%22URL+rewrite+%26+filter%22)

**Comment by radiumatic** [comment]
Yes, searching on Google didn't show these. Can't this be done with the same mechanism used for selective engine query? All SearxNG instances have a list of alternative frontend instances for each popular platform and allow to either select a specific one, BEST (many frontends have a bot for benchmarking them) or a custom one.

**Comment by return42** [comment]
> Yes, searching on Google didn't show these.

Going to close this thread ..

> Can't this be done with the same ..

In order not to fray the discussion, you should better post your questions and suggestions in one of the existing threads / may https://github.com/searxng/searxng/issues/1575 is a good place for your comment?

**Comment by radiumatic** [comment]
Yeah, sorry.
