### ISSUE TITLE
Caching (make it faster with caching)

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3328]
Searxng is slow due to having to visit multiple sites.

Caching could speed up Searxng and take it to a new level.

One way this could work is to build a database of most frequently used keywords and make that a search engine in Searxng. Perhaps a prefer cache checkbox.
The sqlite3 database is downloaded with searxng and if the search term exists in the database, the metasearch is completely avoided.

Querying a local database is fast and the results in 95% of cases would be the same.

The user does not build the database, they instead download an existing cache.

**Comment by unixfox** [comment]
Related: https://github.com/asciimoo/searx/issues/255

About searxng, not something we are going to implement because the cache miss will be high due to the fact that you do not generally search for the same thing.

Also privacy wise it's bad to store somewhere what the users searched for.
