### ISSUE TITLE
Bug: all engine

### ISSUE THREAD

**Issue by Finoway** [searxng/searxng#334]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-795-d95c46d6

**How did you install SearXNG?**
Install with
$ cd ~/Downloads
$ git clone https://github.com/searxng/searxng.git searx
$ cd searx

$ sudo -H ./utils/searx.sh install all
$ sudo -H ./utils/filtron.sh install all

**What happened?**
If the meta search engine is not used for a long time when searching all timed out engines
![image](https://user-images.githubusercontent.com/48923336/133919889-3fdd3454-77d3-461f-972f-93bbf619a0e8.png)

**How To Reproduce**
As said before, I don't know what's going on but I just know that if the meta search engine is not used for a while all engines timed out during a search.

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 10
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`
  
I hope that it will suit you

**Comment by return42** [comment]
Is your SearXNG instance public?

**Comment by Finoway** [comment]
No, I want to avoid putting it in public and that's why it can be used for hours at a time (all users are friends of mine, we are all French)

**Comment by return42** [comment]
> If the meta search engine is not used for a long time when searching all timed out engines

If you repeat your query did the timeout issue stay, or do the results improve.

**Comment by Finoway** [comment]
> Is your SearXNG instance public?

I just realized that I forgot to specify I try to configure a CRON task every hour to do a speedtest to try to see if it is a problem of the host network level but that has not changed anything and i had the same problem with searx

**Comment by Finoway** [comment]
> > If the meta search engine is not used for a long time when searching all timed out engines
> 
> If you repeat your query did the timeout issue stay, or do the results improve.

yes they are improving yes they improve after 1-3 research

**Comment by dalf** [comment]
Most probably, you can solve this issue if you increase the request_timeout value:
https://github.com/searxng/searxng/blob/d95c46d64617edddbb36a7f764e1affaafa551fc/searx/settings.yml#L103

Technically:  when you send a query, the HTTP connections from SearXNG to the search engines are kept opened.
* A second user query just after has a fast response time because the HTTP connections are opened.
* After some time, they are closed by the search engines:
    * a new user query takes longer, and may time out BUT this query opens the HTTP connections between SearXNG and the search engines.
    * few seconds after, another user query will show the engines as suspended by SearXNG.
    * a third user query gives the results (the HTTP connections are still opened).

**Comment by Finoway** [comment]
> Most probably, you can solve this issue if you increase the request_timeout value:
> 
> https://github.com/searxng/searxng/blob/d95c46d64617edddbb36a7f764e1affaafa551fc/searx/settings.yml#L103
> 
> Technically: when you send a query, the HTTP connections from SearXNG to the search engines are kept opened.
> 
>     * A second user query just after has a fast response time because the HTTP connections are opened.
> 
>     * After some time, they are closed by the search engines:
>       
>       * a new user query takes longer, and may time out BUT this query opens the HTTP connection between SearXNG and the search engine.
>       * few seconds after, another user query will show the engines as suspended by SearXNG.
>       * a third user query gives the results (the HTTP connections are still opened).

Just to be sure I have to go and change it where on server ?

**Comment by dalf** [comment]
For information (out of topic) there is also the [`max_request_timeout`](https://github.com/searxng/searxng/blob/55b30b5b494a59c62e9e7d1a5cb6fdbf8729f64f/searx/settings.yml#L105) setting:

for example:
```yaml
outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
```

With this settings:
* by default the timeout is 5 seconds.
* you can ask to wait from 1 to 10 seconds using `<` in the query : 
   * `<3 time` searches for `time` with a timeout of 3 seconds
   * `<10 time` search for  `time` with a timeout of 10 seconds
   * `<11 time` search for  `time` with a timeout of 10 seconds (because the maximum in settings.yml is 10 seconds).

see https://github.com/searx/searx/pull/1640#issuecomment-517227357 for more details.

**Comment by dalf** [comment]
I close the issue. Feel free to reopen if increasing the timeout doesn't solve the issue.

**Comment by Finoway** [comment]
> For information (out of topic) there is also the [`max_request_timeout`](https://github.com/searxng/searxng/blob/55b30b5b494a59c62e9e7d1a5cb6fdbf8729f64f/searx/settings.yml#L105) setting:
> 
> for example:
> 
> ```yaml
> outgoing:
>   request_timeout: 5.0
>   max_request_timeout: 10.0
> ```
> 
> With this settings:
> 
>     * by default the timeout is 5 seconds.
> 
>     * you can ask to wait from 1 to 10 seconds using `<` in the query :
>       
>       * `<3 time` searches for `time` with a timeout of 3 seconds
>       * `<10 time` search for  `time` with a timeout of 10 seconds
>       * `<11 time` search for  `time` with a timeout of 10 seconds (because the maximum in settings.yml is 10 seconds).
> 
> 
> see [searx/searx#1640 (comment)](https://github.com/searx/searx/pull/1640#issuecomment-517227357) for more details.

Hello,

I am still annoyed with this configuration and even at times the site timed out towards the user's browser. (sorry for the time I took to talk about it I was very busy).

That I am sincere I do not know at all what to do it can come from openvz ? other ? I do not understand much of this problem.

![image](https://user-images.githubusercontent.com/48923336/134765628-4b414a79-ba42-43e9-8a80-ff82316adbd2.png)

![image](https://user-images.githubusercontent.com/48923336/134765610-f95ca9ea-0a2d-437d-853f-3fbc387ee07b.png)

**Comment by dalf** [comment]
> at times the site timed out towards the user's browser

In this case may be this is CPU and / or memory issue on the server:
* first check the memory usage and make sure there is no out of memory. Each SearXNG work takes about 256Mo of RAM (see uwsgi.ini to get the number of worker. ith Docker by default there are 4 workers, so container takes 1Go of RAM).
* If the RAM is okay, I think you should try on a faster server (BTW It seems Dyjix doesn't sell OpenVZ VPS anymore).

**Comment by Finoway** [comment]
> > at times the site timed out towards the user's browser
> 
> In this case may be this is CPU and / or memory issue on the server:
> 
>     * first check the memory usage and make sure there is no out of memory. Each SearXNG work takes about 256Mo of RAM (see uwsgi.ini to get the number of worker. ith Docker by default there are 4 workers, so container takes 1Go of RAM).
> 
>     * If the RAM is okay, I think you should try on a faster server (BTW It seems Dyjix doesn't sell OpenVZ VPS anymore).

Hello, thanks for your answer can you add me on discord ? it will allow me to see the answer more easily (because I am a bit slow on github)

**Comment by dalf** [comment]
I prefer to keep the discussion here, so someone with the same issue can read it ( = the knowledge is centralize in one place). 

To sum up:
* you need a server with at least 2 vCPU and 2Go of RAM (with the default configuration, if you turn knobs here and there it can be less).
* According to your report, I advice you to give a try on another faster VPS (even for few days) or even simpler: locally on your computer and see if it solves the issues.

**Comment by Finoway** [comment]
I just thought I used the installation script and not docker and I will install it on a VM at home in KVM on my laptop to test it (it will take a few hours to see if the problem comes back in this case)

**_VPS Dyjix:_**
htop:
![image](https://user-images.githubusercontent.com/48923336/134769936-f33b57a4-14df-4fca-aab2-ba99e8d7abe7.png)
lscpu:
![image](https://user-images.githubusercontent.com/48923336/134769905-01974c39-b74c-4635-95fe-965f6743aaa2.png)

**Comment by return42** [comment]
I have lost track, does the problem still exist?

**Comment by Finoway** [comment]
Hello, yes the problem still exists I did not answer because I am not too available during the week.

**Comment by unixfox** [comment]
Maybe Dyjix is having some regular networking issues, try to `ping google.com` for 4 hours and see if you have any packet loss or high pings.
Post the final output of ping here (after `ping statistics`).

**Comment by Finoway** [comment]
Hello, I was very busy I had not seen and I did it for several days.
![image](https://user-images.githubusercontent.com/48923336/136647057-527aee35-d270-45e6-983b-fed79ebe58de.png)

**Comment by unixfox** [comment]
Could you try to turn off http2: https://github.com/searxng/searxng/blob/master/searx/settings.yml#L115 and try again?
