### ISSUE TITLE
Feature Request: Ability to add website blacklists in SearXNG

### ISSUE THREAD

**Issue by chickun-io** [searxng/searxng#3342]
First of all, thank you for developing and maintaining SearXNG. I am planning to install and use SearXNG for my searches, but I have noticed that it does not currently support the ability to add website blacklists. This is a feature that I would find very useful, as it would allow me to customize my search results and avoid seeing content from certain websites that I prefer not to visit.
Therefore, I would like to request the addition of this feature to SearXNG. It would be great if users could add their own custom website blacklists, which would then be applied to the search results. This would provide a more personalized and tailored search experience for users.
Thank you for considering this request. I look forward to hearing your thoughts on this feature and any updates on its implementation.

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/discussions/970
