### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by david-0609** [searxng/searxng#335]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 1.0.0-805-875fd3e8

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'html.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:93`
  * Function: `response`
  * Code: `get(url_ping, headers=headers_ping)`

**Comment by tiekoetter** [comment]
DuckDuckGo sometimes blocks my instance (HTTP error 403). This is not a fault of searx/searxng.

**Comment by david-0609** [comment]
Thank you for the clarification!
