### ISSUE TITLE
feature request: show video views

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#3351]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
for some videos engines it is possible to get the view count, but the videos template does not support showing it

**Describe alternatives you've considered**

**Additional context**

**Comment by Bnyro** [comment]
That sounds like a good idea to me, you probably want to contribute it yourself?

**Comment by Austin-Olacsi** [comment]
Probably not, i'm tied up with other priorities unfortunately.
