### ISSUE TITLE
E0611: No name '_ElementStringResult' in module 'lxml.etree'

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3368]
In lxml 5.1.1 the private name `_ElementStringResult` in module `lxml.etree` does no longer exists.

This name is imported and used by `searx.utils.extract_text(..)`:

https://github.com/searxng/searxng/blob/f5bb64cca8a63a10c470b4f9bff647702b6de74c/searx/utils.py#L220-L221

- https://github.com/searxng/searxng/pull/3366 reports issue:

```
TEST      [pylint] ./searx ./searxng_extra ./tests
************* Module searx.utils
searx/utils.py:21:0: E0611: No name '_ElementStringResult' in module 'lxml.etree' (no-name-in-module)
```

**Comment by dalf** [comment]
For information: this code was written nearly a decade ago, perhaps a clear interface exists now.
