### ISSUE TITLE
Bug: duckduckgo engine has an unexpected crash when using an unhandled bang

### ISSUE THREAD

**Issue by csfore** [searxng/searxng#3370]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.3.29+f5bb64cca

**How did you install SearXNG?**

N/A (Using a hosted instance)

**What happened?**

Sending a query with a bang in it that isn't handled by Searx will result in Searx reporting that duckduckgo crashed:
```
duckduckgo ( unexpected crash )
```

**How To Reproduce**

Submit a query that uses a bang not handled by Searx like the following: `!g test` 

**Expected behavior**

When attempting to use bangs in a search, maybe sanitize inputs that will result in a redirect and potential timeout?

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:100`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: redis.exceptions.DataError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/engines/duckduckgo.py:68`
  * Function: `cache_vqd`
  * Code: `c.set(key, value, ex=600)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
@csfore thanks a lot for you bug report ..

> Sending a query with a bang in it that isn't handled by Searx will result in Searx reporting that duckduckgo crashed

Please you give an example of such a bang .. BTW this is SearXNG (Searx ended in 2023).

Is you bug the same reported in: 

- https://github.com/searxng/searxng/issues/392

**Comment by csfore** [comment]
Hello,

I believe I gave a bang in the reproduce section (it also worked using `!b` too). I'd consider this one different from the bug you linked however, since this one reports ddg crashing unexpectedly. 

Also, sorry about calling it Searx, just muscle memory 🙂

**Comment by return42** [comment]
> I believe I gave a bang in the reproduce section 

Opps sorry .. I'm blind today :)

OK, tested with `!ddg !b foo` .. and ..

>> Is you bug the same reported in https://github.com/searxng/searxng/issues/392 

.. its not related!

**Comment by csfore** [comment]
> Opps sorry .. I'm blind today :)

No worries!

> .. its not related!

Nice! :)
