### ISSUE TITLE
Bug: presearch engine

### ISSUE THREAD

**Issue by nxs8739** [searxng/searxng#3372]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.12.31+3535377c9

**How did you install SearXNG?**

via docker

**What happened?**

not sure, it gave the option to make an issue here on github and since i saw no issues about this i made one.

**How To Reproduce**

im not entirely sure... try using presearch?

**Expected behavior**

 to have this possibly fixed. or an explanation as to why im dumb and got this in the first place lol

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 5
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: KeyError
  * Percentage: 5
  * Parameters: `()`
  * File name: `searx/engines/presearch.py:115`
  * Function: `parse_search_query`
  * Code: `for item in [info['subtitle'], info['description']]:`

**Comment by nxs8739** [comment]
i am new to github so please go easy if i didnt do this properly.

**Comment by Bnyro** [comment]
Could you please share the search query you used to get this error? I can't seem to reproduce it with some random queries I tested.

**Comment by Austin-Olacsi** [comment]
That looks like an older version of searxng, the presearch engine was updated since then, are you sure this issue still exists on the latest version?

**Comment by Bnyro** [comment]
Oh right, @return42 already fixed this issue in https://github.com/searxng/searxng/commit/a2c269bbac95879be02423cb834833654e22521b 3 months ago 👍

**Comment by nxs8739** [comment]
Ah, thank you! I will update it then 😊
