### ISSUE TITLE
Self Information not showing IP address

### ISSUE THREAD

**Issue by euh2** [searxng/searxng#3374]
**Version of SearXNG**
SearXNG version 2024.3.29+f5bb64cca

*** Starting uWSGI 2.0.23 (64bit) on [Fri Apr  5 10:16:28 2024] ***
compiled with version: 13.2.1 20231014 on 30 November 2023 14:34:33
os: Linux-6.6.13+bpo-cloud-amd64  SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15)

No fork. 

**How did you install SearXNG?**

Helm Chart

**What happened?**

Self Information is enabled. When searching for `useragent`, useragent is returned by Searxng. But when searching `ip`, client IP address is not returned.

**How To Reproduce**

Enable Self Information, then search for `ip`.

**Expected behavior**

Search term `ip` should return client IP address.

**Screenshots & Logs**

```
2024-04-05 10:18:17,947 ERROR:searx.plugins.self_info: Exception while calling post_search
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/__init__.py", line 203, in call
    ret = getattr(plugin, plugin_type)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/self_info.py", line 24, in post_search
    ip = get_real_ip(request)
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/botdetection/_helpers.py", line 109, in get_real_ip
    x_for: int = cfg['real_ip.x_for']  # type: ignore
                 ~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
**Additional context**

Container runs on Kubernetes behind ingress-nginx reverse proxy. Proxy forwards `X-Real-IP` and `X-Forwarded-For` headers to searxng container.

**Comment by return42** [comment]
Sorry this is an old issue I have to fix ..

- https://github.com/searxng/searxng/issues/2995

**Comment by return42** [comment]
@euh2 issue is fixed in PR 

- https://github.com/searxng/searxng/pull/3380

can you test/review the PR  .. thanks :+1:

**Comment by euh2** [comment]
> can you test/review the PR .. thanks 👍

Yes, works now! Thanks!
