### ISSUE TITLE
Ability to customise result URL formatting

### ISSUE THREAD

**Issue by NormPlum** [searxng/searxng#3376]
**Is your feature request related to a problem? Please describe.**
I personally find it weird that the result URLs are formatted using spaces and `>` characters, instead of `/` like one expects to see in a URL. This formatting looks like a [breadcrumb trail](https://en.wikipedia.org/wiki/Breadcrumb_navigation), which doesn't always match up with the URL of a webpage, so it's off-putting.

I understand this was requested in https://github.com/searxng/searxng/issues/504 as a way to make the results page cleaner, but I'd like a way to disable it.

**Describe the solution you'd like**
Would it be possible to add a setting to toggle this behaviour on and off? That way everyone can have the formatting they prefer. DuckDuckGo has a similar setting:

![image](https://github.com/searxng/searxng/assets/162703454/7d908fba-0744-4667-bfc5-578af7327c43)

**Describe alternatives you've considered**
Leaving things as they are, or reverting them to how they were, are options; but they don't allow all users to have the formatting they like.

**Additional context**
![image](https://github.com/searxng/searxng/assets/162703454/23fb4532-15b3-46e0-847c-6470ffa9bd7d)

**Comment by joestump** [comment]
Agreed, that would be nice. Somewhat related, I recently wrote a plugin that redirects news sites to Postlight parser proxy, but the URLs don't show `GET` arguments so you can't really tell what's going on. It would be nice if there was a `display_url` and `display_parsed_url` in the `result` argument passed to `on_result`.

**Comment by return42** [comment]
@joestump, @NormPlum and all coming around: would you please have a look at ..

- #4057
