### ISSUE TITLE
CI github action "Update translations branch" is broken

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3379]
The github action reports error message shown below / see https://github.com/searxng/searxng/actions/runs/8590294364/job/23537686312

```
/usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
```

**Comment by return42** [comment]
@dalf translation integration fails on this step .. could it be that the `${{ secrets.WEBLATE_GITHUB_TOKEN }}` is no longer valid?


https://github.com/searxng/searxng/blob/4acb52f68f5a40408b8331686111658a1030de0b/.github/workflows/integration.yml#L136-L140

**Comment by dalf** [comment]
@return42 see the matrix channel

**Comment by return42** [comment]
fixed by renewing the token / see https://github.com/searxng/searxng/pull/3411 / thanks goes to @Bnyro :rocket:
