### ISSUE TITLE
Better options for long URLs

### ISSUE THREAD

**Issue by NormPlum** [searxng/searxng#3385]
**Is your feature request related to a problem? Please describe.**
When a search result has a long URL, it seems that the beginning and end are shown while the middle is cut off:

![image](https://github.com/searxng/searxng/assets/162703454/184816b5-2f7c-4cbe-ab9e-1b7ca4479436)

This doesn't present a very readable URL, especially since the URL can be cut off mid-character.

**Describe the solution you'd like**
I'm not sure what the best option here is... I assume the cut off in the middle is because people preferred seeing the end of long URLs, rather than just an ellipsis at the end.

Perhaps instead of a hard cut off, it can be faded, or an ellipsis put before the end part. For example:
`https://www.environment.nsw.gov.au ... -and-reporting › toorale-water-infrastructure-project`

**Comment by return42** [comment]
> Better options for long URLs

You already asked in https://github.com/searxng/searxng/issues/3376 for better options, please post additional remarks / discussions there.

**Comment by NormPlum** [comment]
@return42 That issues was more about providing an option to change the formatted, `›`-spearated URL into a regular URL.

This one is for people who continue to use the current, formatted URL style; changing how the cut-off part in the middle looks.

Two separate issues IMO.
