### ISSUE TITLE
Libtretranslate

### ISSUE THREAD

**Issue by cy8aer** [searxng/searxng#3387]
https://libretranslate.com/

**Why do you want to add this engine?**

This is a translation engine like google translate or deepl

... and it is free and self hostable!

**Features of this engine**

Web site creates the api calls when typing in a request!

**How can SearXNG fetch the information from this engine?**

... the web page is self describing

**Applicable category of this engine**

It is - like all other translation engines "general"

**Additional context**

The engine is written in python.

**Comment by Bnyro** [comment]
The Mozhi engine supports LibreTranslate too btw.

**Comment by cy8aer** [comment]
Oups, really? I'll try it out.

**Comment by Bnyro** [comment]
SearXNG's mozhi engine needs to be configured to use LibreTranslate, so you either need to be the instance admin or ask the instance admin to configure it.

**Comment by cy8aer** [comment]
Does the mozhi engine have an api token parameter?
Does not look like. So for a working LibreTranslate the api key is needed, especially if it is self hosted to avoid spamming.

**Comment by Bnyro** [comment]
No, Mozhi is self-hostable. Therefore the person hosting Mozhi has to set the API key.

I just came up with Mozhi to say it's already possible in theory (I've already used it via my private SearXNG instance), but for your use case that's probably not the best.

**Comment by cy8aer** [comment]
I see, mozhi is a searx like proxy for other engines, libretranslate is a translation engine itself.

**Comment by rasos** [comment]
The engine could be adapted for calling LibreTranslate https://github.com/searxng/searxng/blob/master/searx/engines/mozhi.py - but what would be the ideal user experience? How do I choose the target language?

**Comment by Bnyro** [comment]
`!mozhi en-de Hello World` translates `Hello World` from English to German.

**Comment by cy8aer** [comment]
I need an api key for my libretranslate instance. But this does not look like it is possible with:

```
require_api_key: true
api_key: my-api-key
```

**Comment by Bnyro** [comment]
No, the Mozhi instance owner has to the provide the api key.

**Comment by Bnyro** [comment]
If you want to, you can test https://github.com/searxng/searxng/pull/3398.

**Comment by cy8aer** [comment]
yes that works for me
