### ISSUE TITLE
How to restore setting without cookies

### ISSUE THREAD

**Issue by Gamer750** [searxng/searxng#3388]
Can't restore settings by link

**Comment by return42** [comment]
Not sure, what you mean / please explain in more detail.

**Comment by Gamer750** [comment]
I can't restore my setting eg(safe search strict )
When I use the link to restore it goes to default instead of what I saved

**Comment by return42** [comment]
I assume you refer to this problem: https://github.com/searxng/searxng/issues/1365#issuecomment-11802481233 .. I'm going to close this issue here, lets continue in the existing issue ...
