### ISSUE TITLE
locales zh_CN and zh_TW don't work

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#339]
On the master branch, `zh_CN` and `zh_TW` fallback to English.

The fix seems to rename the directories `zh_Hans_CN` and `zh_Hant_TW` respectively.

I'm not sure about the consequences.

**Comment by return42** [comment]
> On the master branch, zh_CN and zh_TW fallback to English.

You are talking about the UI settings .. right?

> The fix seems to rename the directories zh_Hans_CN and zh_Hant_TW respectively.

do you have a branch which implements the fix / do you like to send a DRAFT?

Related:

- https://github.com/searxng/searxng/issues/228#issuecomment-888187967
- https://github.com/searxng/searxng/issues/195#issuecomment-887624534
- https://github.com/flask-admin/flask-admin/issues/403

**Comment by dalf** [comment]
> You are talking about the UI settings .. right?

Yes

I remember to have read that there are some issues when the territory is specified (but not sure how, and where I've read that).

ping @MarcAbonce

**Comment by MarcAbonce** [comment]
Oh sorry, I guess I was wrong then. In that case we should rename the translation directories like you said.

We just need to make sure that we're keeping the more updated translation for the Taiwanese files.
For example, in searx, which still has both versions, you can see that the [zh_TW](https://github.com/searx/searx/blob/master/searx/translations/zh_TW/LC_MESSAGES/messages.po) translation was last updated this year but [zh_Hant_TW](https://github.com/searx/searx/blob/master/searx/translations/zh_Hant_TW/LC_MESSAGES/messages.po) was last updated in 2018.
