### ISSUE TITLE
DuckDuckGo's Image Proxy

### ISSUE THREAD

**Issue by Dispatch3376** [searxng/searxng#3395]
**Is your feature request related to a problem? Please describe.**

Serving images by a searxng instance can use a lot of bandwidth, especially if they're in high resolution, and for small servers, this can be a problem.

**Describe the solution you'd like**

Implementing an image proxy like DuckDuckGo's image proxy can take off some bandwidth and load on the server, and images could load faster when using DuckDuckGo's image proxy as they have CDNs all around the world.

**Describe alternatives you've considered**

DuckDuckGo's image proxy or startpage's image proxy
**Additional context**

https://github.com/vladimiry/ElectronMail/issues/312
https://stackoverflow.com/questions/56132631/how-to-scrape-images-from-duckduckgos-image-search-results-in-python

**Comment by return42** [comment]
> and images could load faster when using DuckDuckGo's image proxy as they have CDNs all around the world.

The intention of SearXNG's image proxy is not to send the IP of the end user to the image services.
