### ISSUE TITLE
News filters incorrectly return when using  date filter

### ISSUE THREAD

**Issue by cameronj86** [searxng/searxng#3400]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 
2024.4.7+bf3845b09
**How did you install SearXNG?**

Docker Install
**What happened?**

Searching news w/o a filter returns content
Searching news w/ a filter doesn't find any results
**How To Reproduce**

1. Search w/ news like !qwn !ddn on a popular topic in the news
2. Notice that some of the content was created in the past week
3. Filter to only show the past week
4. "Sorry no results were found"

**Expected behavior**

**Screenshots & Logs**

Query showing results from yesterday + the past week in 'Anytime' view:
![image](https://github.com/searxng/searxng/assets/8635023/dba2cd72-08ef-4f06-8bf7-bf651ff8a416)
Filter to past week errors out:
![image](https://github.com/searxng/searxng/assets/8635023/0f6bc222-25ba-4f80-b1a4-6171baa91a94)

**Additional context**

I feel like the functionality has worked (intermittently?) in the past but let me know if I'm mistaken

**Comment by return42** [comment]
> Search w/ news like !qwn !ddn on a popular topic in the news

Notice that most news engines do not support time range filter and will be disabled when you chose a time range filter:

![grafik](https://github.com/searxng/searxng/assets/554536/c463d587-86e4-4621-a60f-e3761cbffb1c)

**Comment by cameronj86** [comment]
Woof. I never realized there was a `time range` flag in the preferences. The fact that some news sites do have the functionality explains why it has worked intermittently in the past. Thanks for looking into it!
