### ISSUE TITLE
Missing localizable (gettext) messages from some files in translation workflow

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3412]
I noticed that we use terms such as 

https://github.com/searxng/searxng/blob/f5bb64cca8a63a10c470b4f9bff647702b6de74c/searx/engines/wttr.py#L55

https://github.com/searxng/searxng/blob/f5bb64cca8a63a10c470b4f9bff647702b6de74c/searx/engines/wttr.py#L68

But for some reason they seem to be missing in our [translation workflow](https://docs.searxng.org/dev/translation.html) ... [search for "Temperature" on Weblate](https://translate.codeberg.org/projects/searxng/searxng/en/?q=temperature#search) ..

May we have a bug in our translation workflow ..

_Originally posted by @return42 in https://github.com/searxng/searxng/pull/3359#pullrequestreview-1985132187_
            
-----

I'm not sure, but it seems to me that pybabel doesn't find (all?) `gettext` passages in the engines?

https://github.com/searxng/searxng/blob/af3be2b12b3bfd03af319e0901a19121281c1d11/utils/lib_sxng_weblate.sh#L143-L147

https://github.com/searxng/searxng/blob/af3be2b12b3bfd03af319e0901a19121281c1d11/babel.cfg#L1-L6

**Comment by dalf** [comment]
f-string are not supported [1] but there is no error [2].

[1] https://github.com/python-babel/babel/issues/594
[2] https://github.com/python-babel/babel/issues/715

**Comment by return42** [comment]
> f-string are not supported 

Thanks for pointing out .. / see my PR:

- https://github.com/searxng/searxng/pull/3413
