### ISSUE TITLE
Duplicate logic for formatting human readable file sizes

### ISSUE THREAD

**Issue by Bnyro** [searxng/searxng#3419]
@return42 added a `humanize_bytes` function in https://github.com/searxng/searxng/commit/e76ab1a4b3a99b0ec2ef90c3aadc92ffbf6889b1.

However I figured out when working on a PR recently, that we already had a similar logic before https://github.com/searxng/searxng/blob/master/searx/templates/simple/result_templates/files.html#L38 used in the `files.html` template - it however covers less cases that the `humanize_bytes` function.

We should probably replace the logic in `files.html` with using `humanize_bytes`.

**Comment by return42** [comment]
Yeah, good point .. we should normalize all the implementation to ..

https://github.com/searxng/searxng/blob/e0214412f82305eee4a4f0b721c92ef9b869d240/searx/utils.py#L355-L364

You already mentioned the template ..

https://github.com/searxng/searxng/blob/e0214412f82305eee4a4f0b721c92ef9b869d240/searx/templates/simple/result_templates/files.html#L38-L45

Haven't look deep, but it seems to me the torrent engines first do calculate from a human readable format to the number of bytes (`see utils.get_torrent_size(..)`) and in the file template of the torrent engine the number of bytes is calculated back to a human readable format .. may this can be also be simplified a little bit(?).

```
./searx/engines/btdigg.py:66:        filesize = get_torrent_size(filesize, filesize_multiplier)
./searx/engines/tokyotoshokan.py:78:                    params['filesize'] = get_torrent_size(groups[0], groups[1])
./searx/engines/1337x.py:45:        filesize = get_torrent_size(filesize, filesize_multiplier)
./searx/engines/bt4g.py:117:                'filesize': get_torrent_size(filesizeParsed[0], filesizeParsed[1]),
./searx/engines/piratebay.py:90:            filesize = get_torrent_size(result["size"], "B")
./searx/engines/digbt.py\08:from searx.utils import extract_text, get_torrent_size
./searx/engines/digbt.py:48:        filesize = get_torrent_size(files_data[FILESIZE], files_data[FILESIZE_MULTIPLIER])
./searx/engines/solidtorrents.py:17:    get_torrent_size,
./searx/engines/solidtorrents.py:66:            'filesize': get_torrent_size(*extract_text(stats[1]).split()),
./searx/engines/nyaa.py:106:            filesize = get_torrent_size(*filesize_info.split())
./searx/engines/kickass.py:57:        result['filesize'] = get_torrent_size(*extract_text(eval_xpath(tag, './/td[contains(@class, "nobr")]')).split())
```

https://github.com/searxng/searxng/blob/e0214412f82305eee4a4f0b721c92ef9b869d240/searx/utils.py#L332-L352
