### ISSUE TITLE
Yep timeout on all searxng instances

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [searxng/searxng#3421]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
no idea i'm a client 

**How did you install SearXNG?**
i didn't i'm a client

**What happened?**
Every random instance of searxng I've tried ( via http://farside.link/searxng/preferences?preferences=eJx1V8uu4zYM_ZpmY0zQ6RQousiqaPsDszdki7Y5lkSNHkl8v75U7MRUfLu4Dx1JfIk8pHuVYKSAEC8jOAjKnIxyY1YjXFROdDLUKwMXcKey7Ml6AwkuJ7R8pPWB7svle8hwspAm0pd___5-imqACCr00-XXU5rAwiViuXgKELNJsSXXOri1SXXrZU3Y8h6ZK4QLKV6eKYyn9VYb02I2c3pwCUKrDI7O8v-Xf5SJcFL6qlwPut3UrujPDGFp0bUJEwtYQXQDOkwstQ9kzKp_vVbM6teALCzJQJ_W7YnSDEu8aBgU23_SGFVnWB24ER3H7s9RjW1L7Gv45be_lHMqNkUiXkHAfm4shkBBYuxgw7-bmCjIw0715LRqW0y87NBg-WnbK2qgWKCkcRRa2Z2bviKHtd2e8iXfKh_3gyPRyKA3aimaxY5l5wMq0yDrZvzxyEUX2jEHsWZjggpLUxRFrCUEvAciK8Gb7Yy0yi1K7duklwggPCMPLoAnISLRvFCiONGsnICLPbGfVJbiJcppVkQmq7v92g1njB56Tnt5r4Ij_-GUKjCZISirjJ-UPP7127c_7sJL4uB7NJR2jP2aQ1NseFmyQmskRURXeA2BCEW8jiUS4uCSrTXLrsLP43mks4ZrSZUTuDozSxY2Bl2-N8W9LZ1USNgLoSrc8Sp97pTTvbK-bW2O2G_B8aCxCkGHbnxfH317oFUQHsjB2Q5Tl_sZ0mZl3_df0vUtMZghIgjh_QTDTFy8shBiDDBIfxbw0s4-B4PwhgQ-u0hMA3ww2bxCwDFG5RIHT-jXemyYFwqn4KNoxH1iZ0Iz5W5zCLhEUdd5qFWqQqo5AuVnpM_RY3jF3g1UEb1rAEs_ns_2KhpOjKVyHtJiyXGWCAL6ehcqBh1IGj4Y7GdJCEMAaCIN6aYCNBoDc2dh0dXvIaCbUcmMY-WY4x5bXiei7fzIfK26fbFHsCcNHYTxufegMunKRm6HIG14lYUbdsjDDWcGIaOCTCNJnY96r6550lrmy6SYJcuvzdpps_axwIqR0CkhCR3_i5Tj59hT_g9kPtxlzPwmKgrSNGDt0nDPtrlkJxy2cuRiegeZd9OnQviFBP7xZWsC4ujWFWjg846JK8aqZ7jxWqW6oS4mOBcTVlb6MEvAXnjIQ4XqfWH8xwGL995Q1vsB5-1zT3GKwTPUhSkUZ2Gprgip4vPnns8dp7Hayrbej4kTOnHfFESrOLwjxic7ed2BvOZ5SiDRmzyWUQWiJAtfalE86mN9fjiz--QxcB_ulCT53D0Zfl3ZIkboXvyT2n_emKJklB9AnfgrdKiRFT6UA0dRY9XUPKptYhKdijK3jPp1Ir_eTMzYg6Hb85HjnLvsUn7WQYmS43dex6VPii5mD6Gk6nZjVV2YoCm_XhxTWjRnILyOcUpwm_usjmMhcV8mWBEoHj9RM2uFOtGzi1zvcZI9WE1U0fMDqGO8UE65k2PNC3n1E4WGibckoDh2RQsk1jfsqq7E4_idu3OoO3FpJR3RfBhoKqMK8DNTgsPYQzn072gxrCrwcrL0X0zLu4ArLW_hLGihDa6u87FnYZ8-yFUX7GK5XTF_pKBcNFwDouPorMHJHPxwyla36QePUNWUqa4lZ3Yg5G4ZwT7pxgOEtyeypVOyirnM0TfoZBVkHmLl2RsF7XAW0aE7zuS4UJu4OHLsjjD4hz_7mxxdiRJPDVp265syZmKrnYhUCaPl6aIKbUrhjEIY8-61iuUDOIZ9hY-D1wOuMoUraSfmNTumnPa2WylLvz-_Q_ZPI28yT6DxUqr1ft5W54mbCz8c8NceF9Vai9UBUu36MXgL_JH2Gmf_R1opy3VxEMTfbwN_-w102OESb3lq7OfjTlBlYmt5OmQLbGGuE395cDu4_AdMmbyj&save=1&q=%s
(which still doesn't preserve %s with what is typed in the urlbar)) cannot retrieve yep results, claiming a timeout error, all the while yep.com is still online and reachable 

**How To Reproduce**

Open searchng via http://farside.link/searxng/preferences?preferences=eJx1V8uu4zYM_ZpmY0zQ6RQousiqaPsDszdki7Y5lkSNHkl8v75U7MRUfLu4Dx1JfIk8pHuVYKSAEC8jOAjKnIxyY1YjXFROdDLUKwMXcKey7Ml6AwkuJ7R8pPWB7svle8hwspAm0pd___5-imqACCr00-XXU5rAwiViuXgKELNJsSXXOri1SXXrZU3Y8h6ZK4QLKV6eKYyn9VYb02I2c3pwCUKrDI7O8v-Xf5SJcFL6qlwPut3UrujPDGFp0bUJEwtYQXQDOkwstQ9kzKp_vVbM6teALCzJQJ_W7YnSDEu8aBgU23_SGFVnWB24ER3H7s9RjW1L7Gv45be_lHMqNkUiXkHAfm4shkBBYuxgw7-bmCjIw0715LRqW0y87NBg-WnbK2qgWKCkcRRa2Z2bviKHtd2e8iXfKh_3gyPRyKA3aimaxY5l5wMq0yDrZvzxyEUX2jEHsWZjggpLUxRFrCUEvAciK8Gb7Yy0yi1K7duklwggPCMPLoAnISLRvFCiONGsnICLPbGfVJbiJcppVkQmq7v92g1njB56Tnt5r4Ij_-GUKjCZISirjJ-UPP7127c_7sJL4uB7NJR2jP2aQ1NseFmyQmskRURXeA2BCEW8jiUS4uCSrTXLrsLP43mks4ZrSZUTuDozSxY2Bl2-N8W9LZ1USNgLoSrc8Sp97pTTvbK-bW2O2G_B8aCxCkGHbnxfH317oFUQHsjB2Q5Tl_sZ0mZl3_df0vUtMZghIgjh_QTDTFy8shBiDDBIfxbw0s4-B4PwhgQ-u0hMA3ww2bxCwDFG5RIHT-jXemyYFwqn4KNoxH1iZ0Iz5W5zCLhEUdd5qFWqQqo5AuVnpM_RY3jF3g1UEb1rAEs_ns_2KhpOjKVyHtJiyXGWCAL6ehcqBh1IGj4Y7GdJCEMAaCIN6aYCNBoDc2dh0dXvIaCbUcmMY-WY4x5bXiei7fzIfK26fbFHsCcNHYTxufegMunKRm6HIG14lYUbdsjDDWcGIaOCTCNJnY96r6550lrmy6SYJcuvzdpps_axwIqR0CkhCR3_i5Tj59hT_g9kPtxlzPwmKgrSNGDt0nDPtrlkJxy2cuRiegeZd9OnQviFBP7xZWsC4ujWFWjg846JK8aqZ7jxWqW6oS4mOBcTVlb6MEvAXnjIQ4XqfWH8xwGL995Q1vsB5-1zT3GKwTPUhSkUZ2Gprgip4vPnns8dp7Hayrbej4kTOnHfFESrOLwjxic7ed2BvOZ5SiDRmzyWUQWiJAtfalE86mN9fjiz--QxcB_ulCT53D0Zfl3ZIkboXvyT2n_emKJklB9AnfgrdKiRFT6UA0dRY9XUPKptYhKdijK3jPp1Ir_eTMzYg6Hb85HjnLvsUn7WQYmS43dex6VPii5mD6Gk6nZjVV2YoCm_XhxTWjRnILyOcUpwm_usjmMhcV8mWBEoHj9RM2uFOtGzi1zvcZI9WE1U0fMDqGO8UE65k2PNC3n1E4WGibckoDh2RQsk1jfsqq7E4_idu3OoO3FpJR3RfBhoKqMK8DNTgsPYQzn072gxrCrwcrL0X0zLu4ArLW_hLGihDa6u87FnYZ8-yFUX7GK5XTF_pKBcNFwDouPorMHJHPxwyla36QePUNWUqa4lZ3Yg5G4ZwT7pxgOEtyeypVOyirnM0TfoZBVkHmLl2RsF7XAW0aE7zuS4UJu4OHLsjjD4hz_7mxxdiRJPDVp265syZmKrnYhUCaPl6aIKbUrhjEIY8-61iuUDOIZ9hY-D1wOuMoUraSfmNTumnPa2WylLvz-_Q_ZPI28yT6DxUqr1ft5W54mbCz8c8NceF9Vai9UBUu36MXgL_JH2Gmf_R1opy3VxEMTfbwN_-w102OESb3lq7OfjTlBlYmt5OmQLbGGuE395cDu4_AdMmbyj&save=1&q=%s
(which still doesn't preserve %s with what is typed in the urlbar) and search for something
**Expected behavior**

For yep to work for at least one of them
**Screenshots & Logs**
![Screen Shot 2024-04-25 at 20 19 13](https://github.com/searxng/searxng/assets/577091/477e8cde-3913-40e2-a6d7-a60a1f3a1872)

**Additional context**

**Comment by return42** [comment]
@neurodiverseEsoteric thanks a lot for your bug report ..

> Every random instance of searxng I've tried `https://farside.link/searx`

These are old searx instances, please post an issue at fareside that the searx project is no longer alive and these instance are broken / no longer usable.

Here, this project is the successor of searx and this project is named "SearXNG" (*searx next generation*).

Further please do not post `https://farside.link` links here .. we can't reproduce where these links are routed to .. if you look out for an overview use https://searx.space/# (have a look at the "Engines" tab) .. or just post a bug report from the instance you used at the end.

However, I posted:

- https://github.com/searxng/searxng/pull/3422

to solve the issue you reported here about yep engines ..

**Comment by neurodiverseEsoteric** [comment]
Sorry, I copied the wrong thing there.

**Comment by neurodiverseEsoteric** [comment]
farside offers the convenience of automatically adding the custom preferences string over to  the instance it randomly selects (also thanks to the "create custom search-engines" add-on), so I don't keep track of which instance was chosen, unless farside keeps switching to the same one. But since yep kept timing-out for every instance, I assumed that the issue was affecting all of them...
