### ISSUE TITLE
Bug: yacy's used instance seem broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [searxng/searxng#3428]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.4.24+e0214412f

**How did you install SearXNG?**

Docker

**What happened?**

Yacy hasn't worked in a while on my instance and looks like it was never reported.
After looking into it, it looks like the used instance stopped showing any results (and is really slow to load the (empty) results page): 
![image](https://github.com/searxng/searxng/assets/47571719/d11c6a23-aadd-4040-a747-bb127a6832d8)

**Additional context**

Semi-private instance with dozens of users... (so IP ban is possible, Mojeek has done it recently)

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 50
  * Parameters: `(None, None, 'yacy.searchlab.eu')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Do you know alternatives for ..?

https://github.com/searxng/searxng/blob/0e09014df56d1d3b6011c8022f88790aa5cb37bf/searx/settings.yml#L2074

https://github.com/searxng/searxng/blob/0e09014df56d1d3b6011c8022f88790aa5cb37bf/searx/settings.yml#L2087

ping @Bnyro @pointhi

**Comment by Bnyro** [comment]
There unfortunately is no list of public instances, see https://github.com/yacy/yacy_search_server/issues/326.

It seems to be possinle seeing the public instances when temporary self-hosting an instance (described in the linked issue). If anyone wants to do that and share the results here, that'd be helpful.

**Comment by lolcatw** [comment]
The best way to pull results from YaCy is to host your own local instance and pulling results from the API, or re-implement the YaCy p2p protocol to handle it within Searx

**Comment by Bnyro** [comment]
https://search.webproject.link/Network.html?page=2&maxCount=1000

**Comment by ThunderHen** [comment]
search.webproject.link/
s.menghuqiangwei.com/
yacy.excloo.com/
yacy.applefritter.com/
search.open.us.org/
yacy/s.cd0.eu/
search.lomig.me/
yacy.ecosys.eu/
yacy.daj.pw/
yacy.p4u.xyz/
search.blume-it.com/
yayc.fxlqwq.link/
search.fedisonic.cloud/
search.postblue.cz/
search.userbrewerages.uk/
search.webproject.link/
yacy.dieregierung.at/
yacy.reu.nsupdate.info/
oraclex86.nsupdate.info/
google.infocepo.com/
yacy.everythingcostsmoney.com/
applesandoranges.monoskop.org/
yacy.searchlab.eu/
yacy-8652.herokuapp.com/

**Comment by return42** [comment]
@ThunderHen from where do got the list?

I'm working on a fix .. and tested the list ...

OK:
- https://search.webproject.link/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://search.lomig.me/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.ecosys.eu/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

OK (SELF_SIGNED_CERT):
- https://yacy.dieregierung.at/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

no response:
- https://s.menghuqiangwei.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.daj.pw/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.p4u.xyz/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.everythingcostsmoney.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.searchlab.eu/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

login required:
- https://yacy.applefritter.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://search.open.us.org/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://oraclex86.nsupdate.info/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://applesandoranges.monoskop.org/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

not useful JSON response:
- https://s.cd0.eu/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
 .. there was a typo in the list above `yacy/s.cd0.eu/ <--> s.cd0.eu/` ?

Not a yacy instance:
- https://yacy-8652.herokuapp.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

404 page not found:
- https://search.blume-it.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yayc.fxlqwq.link/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

502 bad gateway:
- https://google.infocepo.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

JSON response says "No route matches [GET] /yacysearch.json"
- https://search.fedisonic.cloud/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

TLS issues:
- https://search.postblue.cz/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

Host unknown:
- https://search.userbrewerages.uk/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.excloo.com/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de
- https://yacy.reu.nsupdate.info/yacysearch.json?query=foo&startRecord=0&maximumRecords=10&contentdom=text&resource=global&lr=lang_de

**Comment by return42** [comment]
Seems yacy.searchlab.eu is back today and works / at least for me .. Inspired by the discussion here, I have send a PR with slightly improvements of the engine / you can review https://github.com/searxng/searxng/pull/3472

**Comment by ThunderHen** [comment]
I got the list from https://urlscan.io/result/c5af79f9-2117-4772-bb4d-51cd799fa447/related/ you will need an account.  I did not test the list but they where yacy instances at one point.

**Comment by ThunderHen** [comment]
http://yacy.drastical.net:8090
