### ISSUE TITLE
Searches with startpage no longer work

### ISSUE THREAD

**Issue by TBDwarf** [searxng/searxng#3447]
For several days now, searches with the startpage engine have not been working. There are no error messages, but there are still no results.
I've gone to other Searxng instances and the problem is identical.
- https://www.gruble.de
- https://searx.be
- etc.

To reproduce the problem, just set startpage as the search engine and make a query.

![image](https://github.com/searxng/searxng/assets/79540750/fe9b14ac-7c90-4b8a-8220-8bf732567519)

![image](https://github.com/searxng/searxng/assets/79540750/c99a1dff-06e5-4e75-8e15-78c5daf21669)

![image](https://github.com/searxng/searxng/assets/79540750/5a3559cd-f1af-4aad-9d0d-78553f04fd61)

**Comment by unixfox** [comment]
~https://github.com/searxng/searxng/issues/2989~ https://github.com/searxng/searxng/pull/3457

**Comment by return42** [comment]
Hi @TBDwarf, sorry we closed your report with the wrong link / the bug you reported is fixed in https://github.com/searxng/searxng/pull/3457
