### ISSUE TITLE
Can't click on "next page" because button is covered with text

### ISSUE THREAD

**Issue by stemy2** [searxng/searxng#3448]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.5.01
**How did you install SearXNG?**

**What happened?**

I can't click on "next page" because it is covered by text.
**How To Reproduce**

1. Perform a search
**Expected behavior**

The "next page" button is clickable.
**Screenshots & Logs**

![Screenshot_20240502_213111](https://github.com/searxng/searxng/assets/22192600/ae6634c6-9ab5-49de-b628-a5fadab9bf40)

**Additional context**

**Comment by unixfox** [comment]
This is probably from searx.be which is running oscar. A theme not supported by searxng anymore.
