### ISSUE TITLE
Searxng and Python 3.12.3

### ISSUE THREAD

**Issue by stef204** [searxng/searxng#3449]
Does `searxng` actually support `python 3.12.3`?
Running searxng-git from AUR, version `1.0.0.r3817.g11fe88bb4-1` which I take is latest master..
Cannot get it to start properly, fails with:
```
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
*** RRDtool library available at 0x647b17ac0400 ***
uwsgi[66792]: probably another instance of uWSGI is running on the same address (:8888).
uwsgi[66792]: bind(): Address already in use [core/socket.c line 769]
uwsgi[734]: Thu May  2 20:37:09 2024 - [emperor] curse the uwsgi instance searxng.ini (pid: 66792)
uwsgi[734]: Thu May  2 20:37:12 2024 - [emperor] removed uwsgi instance searxng.ini
```

I see [this](https://github.com/searxng/searxng/blob/6f0f9baa38cb92e3d6d141580924a9e7420860a0/.github/workflows/integration.yml#L19) but 3.12 not mentioned there in spite of issue #2745

**Comment by return42** [comment]
> Does `searxng` actually support `python 3.12.3`? 

Yes, Python 3.12 has been added by #2880

- https://github.com/searxng/searxng/pull/2880/files

> I see [this](https://github.com/searxng/searxng/blob/6f0f9baa38cb92e3d6d141580924a9e7420860a0/.github/workflows/integration.yml#L19) but 3.12 not mentioned there in spite of issue #2745

You linked an old commit ..

https://github.com/searxng/searxng/blob/11fe88bb40b9a18583798e15fd6ab4f88cb5aaf1/.github/workflows/integration.yml#L16-L19

**Comment by stef204** [comment]
thanks, my mistake. I will close this issue and open another one.
