### ISSUE TITLE
Searxng no longer starts after large python upgrade

### ISSUE THREAD

**Issue by stef204** [searxng/searxng#3453]
Searxng no longer starts after large python upgrade on `Archlinux`.

Running `searxng-git` from AUR, version `1.0.0.r3817.g11fe88bb4-1` on up-to-date Archlinux.

The problem seems to be related to `python-httpx` and/or `python-httpx-socks` and/or perhaps `python-httpcore`

Checking this ` sudo systemctl status emperor.uwsgi.service` gives:

```
May 03 uwsgi[755]:   File "/usr/lib/python3.12/site-packages/searx/network/__init__.py", line 16, in <module>
May 03 uwsgi[755]:     from .network import get_network, initialize, check_network_configuration  # pylint:disable=cyclic-import
May 03 uwsgi[755]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 03 uwsgi[755]:   File "/usr/lib/python3.12/site-packages/searx/network/network.py", line 14, in <module>
May 03 uwsgi[755]:     from .client import new_client, get_loop, AsyncHTTPTransportNoHttp
May 03 uwsgi[755]:   File "/usr/lib/python3.12/site-packages/searx/network/client.py", line 12, in <module>
May 03 uwsgi[755]:     from httpx_socks import AsyncProxyTransport
May 03 uwsgi[755]: ModuleNotFoundError: No module named 'httpx_socks'
May 03 uwsgi[755]: unable to load app 0 (mountpoint='') (callable not found or import error)
May 03 uwsgi[755]: *** no app loaded. going in full dynamic mode ***
```

As I remember, last time I had a similar problem, I had to downgrade version of `python-httpcore` on which both `python-httpx-socks` and ` searxng-git` depend.  Downgrading that package now to previous (next to last) version does not impact the problem.

Would appreciate some help troubleshooting.

**Comment by return42** [comment]
ping @HLFH 

I assume its an issue of https://aur.archlinux.org/packages/searxng-git ?

**Comment by HLFH** [comment]
I'll have a look this week-end and will fix it.

**Comment by virtadpt** [comment]
@stef204 Just out of curiosity, what happens if you don't install the AUR package, but instead clone the repo and install to a venv?

**Comment by stef204** [comment]
@virtadpt I don't know yet but I can try.
Edit: wasn't able to build it.

```
Getting requirements to build editable ... error
  error: subprocess-exited-with-error
```
I'm not going to troubleshoot the `venv`.  It's off-topic for this ticket.

**Comment by stef204** [comment]
Downgrading Archlinux `python-httpcore` to `0.17.3` fixes the problem, it seems (although that is not necessarily the best solution.)  See [this](https://aur.archlinux.org/packages/searxng-git#comment-971005).

Incidentally, `systemctl status emperor.uwsgi.service` produces this now (although `searxng` does work):
```
May 04 uwsgi[817]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 04 uwsgi[817]:   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
May 04 uwsgi[817]:     with map_httpcore_exceptions():
May 04 uwsgi[817]:   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
May 04 uwsgi[817]:     self.gen.throw(value)
May 04 uwsgi[817]:   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
May 04 uwsgi[817]:     raise mapped_exc(message) from exc
May 04 uwsgi[817]: httpx.ConnectTimeout
May 04 uwsgi[792]: Sat May  4 - [emperor] vassal searxng.ini is now loyal
May 04 uwsgi[817]: announcing my loyalty to the Emperor...
```

**Comment by stef204** [comment]
Had to rebuild more python dependencies, it seems and all is back to normal. Will close. Thanks.

**Comment by HLFH** [comment]
I have [bumped `searxng-git`](https://aur.archlinux.org/packages/searxng-git#comment-971337), so it can be built against Python 3.12.  
I have also bumped python packages that I maintain, and I have flagged out-of-date third-party python packages that have not been bumped.  
I also advise to install `rebuild-detector` to rebuild all required python packages that have not been bumped:
```
pacman -S rebuild-detector

```
