### ISSUE TITLE
Please add torrent search like librey

### ISSUE THREAD

**Issue by gthzee** [searxng/searxng#3454]
I usually use them to search for torrent. But, since my ISP got little bit aggressive and I can't control it, then they blocked me by stating 'i am a spammer', and also many their instances don't support (disable) a torrent search. So, i'm not be able to use their service.
I love searx, this my main search engine, and I would love to see, if i can search torrent within searx. Please consider it

many thanks

**Comment by virtadpt** [comment]
Try searching with `!files` on your SearxNG site of choice.  There are a bunch of torrent-related engines already represented (1337x, bt4g, btdigg, nyaa).

**Comment by Bnyro** [comment]
If you have any particular torrent engine you would like to see added, please use the dedicated `Engine request` template.
