### ISSUE TITLE
[proposal] extend package template with documentation link

### ISSUE THREAD

**Issue by dkuku** [searxng/searxng#3456]
**Is your feature request related to a problem? Please describe.**

I added search on hex.pm for elixir packages and I'm thinking of adding search for documentation but this can be linked from the same search result. It would also work for rust crates which I plan to add. I can add it myself - ri just wanted to consult it with the community
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bnyro** [comment]
I think that's a good idea :+1:

**Comment by dkuku** [comment]
Added in #3464
