### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by farhan-real** [searxng/searxng#3459]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.5.01

**How did you install SearXNG?**

I used the website 
**What happened?**

It says unexpected crash of startpage

**How To Reproduce**

Include startpage in search engines
Search anything on the searx website

**Expected behavior**

Startpage should load

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/startpage.py:216`
  * Function: `get_sc_code`
  * Code: `resp = get(get_sc_url, headers=headers)`

**Comment by Bnyro** [comment]
Fixed in https://github.com/searxng/searxng/pull/3457, updating SearXNG will fix it.
