### ISSUE TITLE
[question] em vs fix pixel size in CSS "@media screen and (max-width: ...)"

### ISSUE THREAD

**Issue by return42** [searxng/searxng#346]
In the simple theme we use `em` to select different media adaptions .. (e.g. in style.less)

https://github.com/searxng/searxng/blob/b046322c7b9467a7de6e9e289e1c5b0c0baaf4a6/searx/static/themes/simple/src/less/style.less#L577

If I'm not wrong, this makes the media adaptions dependended on the font size in the browser settings. With other words: When I change the default font size in my WEB browser's preferences the media adaptions changes.

I realized this behaviour when I tested in FFox and Chrome, both have different font and fontsize settings in their (default) preferences. (Same pixel size but different layout due to the selected media adaptions, due to the different font size)  

Isn't it better when we set the max-width condition to a fix pixel size?

Or do we have an other option to distinguish between tablet, smartphones and desktop media adaption in CSS?

**Comment by return42** [comment]
Drawbacks of fixed pixel size in media query compared to `em`:

- there are several displays out in the wild with various pixel ranges (e.g. smartphone displays from HD over UHD to 4k)
- `em` is relative to the _default font size_ and the _default_ font size of the browser best fits to the dpi.

**Comment by mrpaulblack** [comment]
Also: The width of the content is defined using em (and rem). If we would use fixed pixel sizes, content could be out of frame / the site would not be as responsive as before. I was testing with the 1250px width for tablets, but content would just go out of frame before the grid layout changes to tablet/mobile layout. If we keep using em we get around this issue...
