### ISSUE TITLE
Changing logo fails

### ISSUE THREAD

**Issue by bboyles303** [searxng/searxng#3469]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.5.7+58320222e

**How did you install SearXNG?**
 searxng-docker

Perhaps I am missing something, but when attempting to replace the logo in the docker-compose.yaml like this:

    volumes:
      - ./searxng:/etc/searxng:rw
      - type: bind
        source: ./searxng.png
        target: /usr/local/searxng/searx/static/themes/simple/img/searxng.png

when I docker compose up it fails with the following: 

searxng  | spawned 4 offload threads for uWSGI worker 1
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/webapp.py", line 141, in <module>
searxng  |     static_files = get_static_files(settings['ui']['static_path'])
searxng  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 203, in get_static_files
searxng  |     walk(static_path_path)
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 201, in walk
searxng  |     walk(file)
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 201, in walk
searxng  |     walk(file)
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 201, in walk
searxng  |     walk(file)
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 198, in walk
searxng  |     static_files[str(file.relative_to(static_path_path))] = get_hash_for_file(file)
searxng  |                                                             ^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 183, in get_hash_for_file
searxng  |     with file.open('rb') as f:
searxng  |          ^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.11/pathlib.py", line 1044, in open
searxng  |     return io.open(self, mode, buffering, encoding, errors, newline)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  | PermissionError: [Errno 13] Permission denied: '/usr/local/searxng/searx/static/themes/simple/img/searxng.png'
searxng  | unable to load app 0 (mountpoint='') (callable not found or import error)
searxng  | *** no app loaded. going in full dynamic mode ***

Is there a different way I can sub out the logo? 

**How To Reproduce**
Edit the docker-compose.yaml as described above, then docker compose up and view error in console

**Expected behavior**
Searxng starts and replaces the logo as intended.

**Comment by unixfox** [comment]
Not supported.
