### ISSUE TITLE
Bug: wikidata engine

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#3481]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.5.9+383d87359

**How did you install SearXNG?**

Docker (TrueNAS Scale)

**What happened?**

crash searching for `Maumusson `

**How To Reproduce**

^^

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: TypeError
  * Percentage: 5
  * Parameters: `('can only concatenate str (not "dict") to str',)`
  * File name: `searx/engines/wikidata.py:541`
  * Function: `get_str`
  * Code: `return value + " " + get_label_for_entity(unit, language)`

**Comment by return42** [comment]
Should be fixed by .. can you verify?

- https://github.com/searxng/searxng/pull/3480

**Comment by dalf** [comment]
I confirm the issue can be closed / the PR fixes the issue.
