### ISSUE TITLE
Implement DuckDuckGo-Lite engine (incl. paging)

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#349]
Cross request: https://github.com/searx/searx/issues/2982

I can take the time to implement that, but if someone else wants to do it then feel free to do it.

**Comment by return42** [comment]
**Working URL to the engine**

https://lite.duckduckgo.com/

**Why do you want to add this engine?**

The existing [DuckDuckGo engine](https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py) does not support paging.

**Features of this engine**

DuckDuckgo-Lite is much faster, [less verbose](https://news.ycombinator.com/item?id=22077861) and does have a paging option.

**How can Searx fetch the information from this engine?**

Technical details (copied from https://github.com/searx/searx/issues/2982#issuecomment-928040573):

- Headers:
  Content-Type: `application/x-www-form-urlencoded`
    
- Form data:
  `q`: _the query keyword_
  `o`: `json`
  `dc`: _the number of the first result, for example 1 is the first result_
  `api`: `d.js`

- HTTP method: `POST`
- URL: https://lite.duckduckgo.com/lite/

Additional notes: If `o` and `api` are not provided, then DuckDuckGo Lite only return 5 results.
