### ISSUE TITLE
Unit Converter Operating Backwards

### ISSUE THREAD

**Issue by PeanutAcoustics** [searxng/searxng#3497]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Unforked

**How did you install SearXNG?**

Docker

**What happened?**

Unit converter in PR https://github.com/searxng/searxng/pull/3378 seems to be operating in reverse when handling conversions, resulting in things like 16 pounds per ounce and 1000 kilograms per gram

**How To Reproduce**

Attempt to use unit converter, ex. gram to kilogram or pounds to ounces

**Expected behavior**

A conversion of 1 kilogram to 1000 grams or vice versa

**Screenshots & Logs**

<img width="710" alt="Screenshot 2024-05-19 at 12 16 46 AM" src="https://github.com/searxng/searxng/assets/159606721/086e5a9f-2198-4557-a4e2-0375cb43b9a6">
<img width="710" alt="Screenshot 2024-05-19 at 12 17 00 AM" src="https://github.com/searxng/searxng/assets/159606721/1e07f3f8-f35f-4849-a895-53cb4aa765c6">
<img width="710" alt="Screenshot 2024-05-19 at 12 17 13 AM" src="https://github.com/searxng/searxng/assets/159606721/b70e4deb-cabb-44a5-b1b5-870b695d9c51">

**Additional context**

**Comment by return42** [comment]
Thanks for pointing out .. I send PR #3499 to fix / can you test it / thanks :+1:
