### ISSUE TITLE
simple theme: /preferences: layout issue on mobile.

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#351]
On smartphone (real one or mobile view on FF with touch simulation), the engine response time is displayed at the wrong place:
![image](https://user-images.githubusercontent.com/1594191/135041955-5dd14dc4-4edd-4714-88b1-d650d055b1a5.png)

**Comment by return42** [comment]
It also minifies the font size .... the screenshot is from FFox emulation but I see the same effect on my smartphone

![grafik](https://user-images.githubusercontent.com/554536/135060943-7904f95c-2634-4ad3-b9c0-15fe5e9e2227.png)

Another issue I see is the value in the column "Response Time" (have a look at the 0.4 value from quant) ..

![grafik](https://user-images.githubusercontent.com/554536/135061308-e1db7f7d-fa96-42a3-902c-fdd73caf1bc4.png)

when I drag the table to the left side, the 0.4 value is fixed at the same position (does not move with its column) ..

![grafik](https://user-images.githubusercontent.com/554536/135061946-4e424734-2a16-42f2-8546-98be876a020b.png)

**Comment by return42** [comment]
Can't remember in which PR but this issue is fixed / I close this issue @dalf if you think different, please reopen.
