### ISSUE TITLE
autocomplete-js used by simple theme is not CSP compliant

### ISSUE THREAD

**Issue by return42** [searxng/searxng#352]
The [autocomplete-js](http://autocomplete-js.com/) lib used by the simple theme is not CSP compliant [(and old / last commit from 2018)](https://github.com/autocompletejs/autocomplete.js/commits/2.7).

The CSP issue is, that this lib set the style attributes by `setAttribute("style", ...)` like here:

https://github.com/searxng/searxng/blob/ca67f1555aa3c7dbb8dbb7ace7d4a0be9b65c717/searx/static/themes/simple/js/searx.js#L1419

This invokes the HTML parser and CSP is triggered / see [How to let script to use setAttribute 'style' without breaking CSP](https://stackoverflow.com/a/57633533) and [best practice](https://joji.me/en-us/blog/html-attribute-vs-dom-property/#md-best-practice)

**Comment by return42** [comment]
I looked for a simple replacement of the [autocomplete-js](http://autocomplete-js.com/) lib, there are a lot of other tools around but most often they lack support over a long period.  I haven't looked in deep, but the oscar theme uses a jQuery implementation and it might be the simplest solution to took over what we have in the oscar theme. But this means the simple theme needs to add a jQuery dependence. Before going any deeper, I want to ask if someone see some cons when using jQuery in the simple theme?

**Comment by dalf** [comment]
I wish to avoid a such huge library (28kb when compressed) when all we need is [140 lines](https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/src/js/main/00_searx_toolkit.js) (this is not copy / paste from jquery, it is a minimal re-implementation to provide the required features for the theme).

About autocompletion, the oscar theme uses [corejs-typeahead](https://www.npmjs.com/package/corejs-typeahead) (see [package.json](https://github.com/searxng/searxng/blob/a582cf3d8231f5ed8a881aa87576dfc0600e1c07/searx/static/themes/oscar/package.json#L17) ), and same there are some `style` attributes :  
![image](https://user-images.githubusercontent.com/1594191/135293662-c3ac563a-5936-4c14-96df-1d5565c43ddc.png)

Looking at the autocomplete-js source, only one line sets the `style` attribute: https://github.com/autocompletejs/autocomplete.js/blob/87069524f3b95e68f1b54d8976868e0eac1b2c83/src/autocomplete.ts#L383

May be it is easier to make a subclass / hook AutoComplete: the code is well documented (and I don't know if this is doable).

---

After this issue, some other components use the `style` attribute:
* the [image_layout.js](https://github.com/searxng/searxng/blob/a582cf3d8231f5ed8a881aa87576dfc0600e1c07/searx/static/themes/__common__/js/image_layout.js#L63-L68) : no `style` attributes = we remove this JS, and provide a full CSS implementation. I don't know if this is doable.
* the OSM maps (leftlet)
* [embedded media players](https://github.com/searxng/searxng/blob/a582cf3d8231f5ed8a881aa87576dfc0600e1c07/searx/engines/youtube_noapi.py#L38-L40) : here we can do something.

**Comment by return42** [comment]
> I wish to avoid a such huge library (28kb when compressed) when all we need is 140 lines 

OK, I understand .. that's right.

My initial problem was: the autocompletion box in the result page is over the input field and I can't see what I'm typing .. 

![grafik](https://user-images.githubusercontent.com/554536/135400813-6dfe2167-9051-44cb-852f-b1677a72b0a8.png)

You can test it on https://darmarit.org/searx (you have to switch to the simple theme and on the result page type something in the input field).

If I'm not wrong, this issue is caused by this CSP blocking ...

![grafik](https://user-images.githubusercontent.com/554536/135401451-ef8f23c3-7fde-4192-9e57-4570cb693345.png)

Both issues are caused by sources from the autocomplete-js

https://github.com/autocompletejs/autocomplete.js/blob/87069524f3b95e68f1b54d8976868e0eac1b2c83/src/autocomplete.ts#L545

https://github.com/autocompletejs/autocomplete.js/blob/87069524f3b95e68f1b54d8976868e0eac1b2c83/src/autocomplete.ts#L383

Side note: I do not see such blocking in oscar theme
