### ISSUE TITLE
[Documentation - Enhancement] Mojeek Safe Search

### ISSUE THREAD

**Issue by PrivacyDingus** [searxng/searxng#3526]
Mojeek now provides safe search: https://www.mojeek.com/support/api/search/request_parameters.html

This can be used with ```safe=1``` i.e.

https://www.mojeek.com/search?q=mojeek&safe=1

This has been introduced recently but could be reflected on: https://docs.searxng.org/user/configured_engines.html

**Comment by Austin-Olacsi** [comment]
those docs show features that have been implemented in searxng, but mojeek safe search won't work in searxng (yet). i think we should create a module for mojeek to support the safe search and also the time range.
