### ISSUE TITLE
[Question]: Too many requests ONLY when using SearXNG programmically

### ISSUE THREAD

**Issue by uhidontkno** [searxng/searxng#3537]
* Using public SearXNG instances (eg. searxng.site)

**What happened?**
`Too Many Requests` error when using SearXNG programmically (eg. via curl)

**How To Reproduce**
```bash
curl https://searxng.ca/search?q=google
```
(Same error when using a browser user agent and when using different instances, only works when visiting via browser)

**Expected behavior**
Search results to be given when using tools like cURL to fetch info without a browser like Puppeteer

**Comment by unixfox** [comment]
It's because the anti bot is doing well its job.

You are not allowed to scrape the instance if the instance has not allowed you to get their results through JSON API.

Please don't use scrape public instances. Just run your own searxng instance: https://docs.searxng.org/admin/installation.html

SearXNG instances receive too much bot traffic which result in engines not working well so please don't make it worse.

**Comment by HoneyJoe** [comment]
You need to set the limiter to false
`server:
   limiter: false # default is true
`

**Comment by HoneyJoe** [comment]
You need to set the limiter to false
`server:
   limiter: false # default is true`

**Comment by return42** [comment]
> You need to set the limiter to false `server: limiter: false # default is true`

The opener wrote:

> Using public SearXNG instances (eg. searxng.site)
> ... `curl https://searxng.ca/search?q=google`

.. and its not recommended to run a public instance without any protection against bots / without limiter.

**Comment by HoneyJoe** [comment]
> > You need to set the limiter to false `server: limiter: false # default is true`
> 
> The opener wrote:
> 
> > Using public SearXNG instances (eg. searxng.site)
> > ... `curl https://searxng.ca/search?q=google`
> 
> .. and its not recommended to run a public instance without any protection against bots / without limiter.

you are right, but I couldn't find a better solution.  please give me some advice on what I should do.

**Comment by return42** [comment]
> you are right, but I couldn't find a better solution. please give me some advice on what I should do.

Botdetection was made to block automated request like the one from `curl` example the opener gave. 

And the opener used a public instance where the instance owner decided to protect his instance ..

Either you protect your instance from such access (limiter on) or you do not protect it (limiter off).

So what should be the alternative when it comes to deciding in favor of one or the other?
