### ISSUE TITLE
[bug] "DDG Images" is broken

### ISSUE THREAD

**Issue by throwaway242685** [searxng/searxng#3543]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.5.31+18fb701be

**How did you install SearXNG?**

they're all public instances.

**What happened?**

"DDG Images" seems to be currently broken.

**How To Reproduce**

search for something like: `!ddi cats`

**Expected behavior**

the engine should work, but 99% of times it will just fail.

**Screenshots & Logs**

![sshot-2024-06-06-13-55-50](https://github.com/searxng/searxng/assets/85243826/f28c34bc-f4c1-407c-8751-e674d81f5074)
![sshot-2024-06-06-13-55-58](https://github.com/searxng/searxng/assets/85243826/99b94b3d-65c3-413d-83d0-8b5019719e9b)

**Additional context**

**Comment by Bnyro** [comment]
It's not "broken" per se, it just has a very strict rate limiting.

You can confirm it works fine by running a local instance as described in the SearXNG developer documentation at docs.searxng.org.
