### ISSUE TITLE
URL is truncated in some cases

### ISSUE THREAD

**Issue by coxde** [searxng/searxng#3550]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.5.31+18fb701be

**How did you install SearXNG?**

searxng-docker

**What happened?**

The lower part of the URL is truncated in the desktop version. Can't see that in mobile version. Probably because of the `overflow: hidden` in `.url_wrapper`.

**How To Reproduce**

1. Conduct any searches.
2. Can observe that the lower part of some characters will be truncated.

**Expected behavior**

No parts should be truncated, except for URLs that are too long.

**Screenshots & Logs**

Note that the "g" in the screenshot. 
![image](https://github.com/searxng/searxng/assets/63153334/435df88c-2210-4d4c-bc96-e7949d46345a)

**Additional context**

https://github.com/searxng/searxng/pull/510

**Comment by return42** [comment]
> No parts should be truncated, except for URLs that are too long.

The URL in the example you gave is to long .. URL is split in two parts, the left one `https://developer.mozilla.org` and the path name of the URL on the right side.

Depending on the screen size the path name is truncated on its left side .. so the user can always see the end of the path name ..

![image](https://github.com/searxng/searxng/assets/554536/f5dd5ad9-4272-47bf-8e39-bb0fb824bada)

![image](https://github.com/searxng/searxng/assets/554536/842fd044-6531-421c-b061-8e2a6f98ddab)

**Comment by coxde** [comment]
Thank you for your reply, but I was not talking about the left side is truncated, but the bottom, like the `org` in `developer.mozilla.org` in my screenshot.

Edit: For me it only happened on Firefox (126), but I can't reproduce it on Chromium.

**Comment by return42** [comment]
> For me it only happened on Firefox (126)

Strange .. I also using FF 126.0.1 but can't reproduce the issue.

**Comment by coxde** [comment]
> Strange .. I also using FF 126.0.1 but can't reproduce the issue.

Well I tried to install a new FF and still the same, 127.0.1 (64-bit) archlinux

**Comment by coxde** [comment]
Like I described in the issue, delete `overflow: hidden;` can make it be normal because part of link overflow the flex box.

![image](https://github.com/searxng/searxng/assets/63153334/140b6f48-0291-4b5e-98d2-1148127382fc)

```css
.result .url_wrapper {
  display: flex;
  font-size: 1rem;
  color: var(--color-result-url-font);
  flex-wrap: nowrap;
  overflow: hidden;
  flex-direction: row;
  margin: 0;
  padding: 0;
}
```

**Comment by return42** [comment]
Thanks for helpful hints .. now I can reproduce the issue .. really rare, but when I size to 80% I have one result item that has this issue .. and yes, its caused by the (hidden) overflow :+1:  ... I send PR https://github.com/searxng/searxng/pull/3592 to fix .. can you give it a try / thanks :+1:

**Comment by coxde** [comment]
Thank you for the quick fix, I've tested it and it works well!

**Comment by coxde** [comment]
Thanks for the quick fix, I've tested it and I found some issues. As in the screenshot, the `https://www.techtarget.com` works well but the `g` in `searchnetworking › definition › URL` is still be truncated.

![image](https://github.com/searxng/searxng/assets/63153334/047d7abd-9822-42f1-a758-c9b5a3a68f95)
