### ISSUE TITLE
[Plugin Request] XMPP integration

### ISSUE THREAD

**Issue by sjehuda** [searxng/searxng#3554]
**Is your feature request related to a problem? Please describe.**

This is a feature request to integrate SearxNG with XMPP (RFC 4287).

**Describe the solution you'd like**

I would like to have access to SearxNG via XMPP, without even a shref of HTTP nor even HTML, this would allow to use SearxNG from XMPP chat clients and without an HTML browser.

**Describe alternatives you've considered**

Writing a bot on which pulls results from the RSS feed of SearxNG.

Note: There is a bot which utilizes SearxNG at https://her.st/bot/

**Additional context**

While pulling data from [API](https://searx.github.io/searx/dev/search_api.html) or CSV/JSON/RSS is valid and gives the expected results, it is not the same as having XMPP integration directly embedded (i.e. plugin) to SearxNG.

Also, an external software will not be able to access, read and communicate with object within process SearxNG, which might be preferable in order to achieve some functionalities that can not be achieved otherwise.

**Additional context**

I am currently working on two projects: [News Bot](https://git.xmpp-it.net/sch/Slixfeed) and [Bookmarks Bot](https://codeberg.org/sch/BukuBot) and I am willing to assist with writing a plugin for XMPP.

**Technical information**

The chat bot is utilizing the slixmpp library and can be found at https://codeberg.org/sch/BukuBot/src/branch/master/bukubot/xmpp/client.py

The basic chat bot object is:
```python
    def __init__(self, jid, password):
        slixmpp.ClientXMPP.__init__(self, jid, password)
        # XEPs to load
        self.register_plugin('xep_0030') # Service Discovery
        self.register_plugin('xep_0004') # Data Forms
        self.register_plugin('xep_0060') # Publish-Subscribe
        self.register_plugin('xep_0050') # Ad-Hoc Commands
        self.register_plugin('xep_0115') # Entity Capabilities
        self.register_plugin('xep_0122') # Data Forms Validation
        self.register_plugin('xep_0199') # XMPP Ping
        # Events to listen to
        self.add_event_handler("session_start", self.process_session_start)
        self.add_event_handler("message", self.process_message)
        self.add_event_handler("disco_info", self.process_disco_info)
        # Connect and process
        self.connect()
        self.process()
```

The instruction `self.process()` can be neglected, unles you are interested in adding animated extra functionalities such as chat indicators with which it would be possible to send status messages in chat while requests are being processed.

**Comment by Bnyro** [comment]
I personally don't think that this is in scope for SearXNG, but that's just my opinion.

**Comment by virtadpt** [comment]
@Bnyro I'm inclined to agree.  It's easy enough to make this work with unrelated software.  It would make sense for SearxNG to do one thing, and one thing well (i.e., implementing a metasearch engine).

**Comment by return42** [comment]
> this would allow to use SearxNG from XMPP chat clients and without an HTML browser.

I would agree with previous speakers .. integration is more on the side of the chat service  and is less a task for SearXNG.  The Infrastucture of the chat service would have to run its own (localhost) SearXNG instance anyway ... and could request a JSON response there.

**Comment by sjehuda** [comment]
Gentlemen, please pardon

I am suggesting this as a plugin, which is fairly easy to do and I am willing to work on the XMPP aspect of it, and I will be happy if someone would be willing to help me to integrate and test it.

* I have changed the title (Feature was replaced by Plugin) and I would appreciate if someone would be willing to assist.

P.S.

I am not an authority to decide whether or not it is out of scope or not, yet SearxNG also offers magnet links for BitTorrent and it may also offer support for Gemini and Gopher, as well.

The fact that the public is being indoctrinated that "search engines" and HTML browsers are complementing each other and are exclusive to each other does not mean that it is true.

HTML pages can be fetched and read without html browsers (aka "web browsers").

Please also read the postscript of my message at standards@xmpp.org (dated 13 Jun 2024 5:26 a.m.)

[Standards] Re: Bibliography and PubSub
https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/message/HJ5CIJKBSJWA4WX6GJIT63IGUB6FWZ4Q/

XMPP PubSub is adequate enough to replace HTTP/HTML.

**Comment by sjehuda** [comment]
I have changed the title (Feature was replaced by Plugin) and I would appreciate if someone would be willing to assist.
