### ISSUE TITLE
Domain blacklist feature request

### ISSUE THREAD

**Issue by chickun-io** [searxng/searxng#3561]
**Is your feature request related to a problem? Please describe.**

I frequently encounter search results from specific websites that are not useful to me. It would be beneficial to have a way to permanently filter out results from these domains to improve the relevance and efficiency of my searches.
**Describe the solution you'd like**

I would like the ability to create a user-defined blacklist within SearXNG. This blacklist would allow me to enter specific domain names that I do not wish to see in my search results. When I perform a search, SearXNG would then automatically exclude any results from these blacklisted domains.
**Describe alternatives you've considered**

An alternative could be a more granular filter option, where I can select types of content or specific keywords to exclude, but this might be less efficient than a simple domain-based blacklist.
**Additional context**

Implementing a blacklist feature would enhance user experience by providing more control over the content that appears in search results. This could be a setting that is manageable through the user's account preferences or a configuration file for advanced users.

**Comment by return42** [comment]
> I would like the ability to create a user-defined blacklist within SearXNG.

- Duplicate of https://github.com/searxng/searxng/issues/2351
