### ISSUE TITLE
Increase font size of cached links

### ISSUE THREAD

**Issue by antgig** [searxng/searxng#3572]
**Is your feature request related to a problem? Please describe.**
I am a big fan of the cached links that appear when performing a search. However, the links are small to see and clicking on them requires moving the cursor/finger to a very small area where the link is.

**Describe the solution you'd like**
Increase the font size of the cached links to 50-75% of a normal site link.

**Describe alternatives you've considered**
Replace the naming 'cached' with something longer such as 'Web Archive Link.'

**Comment by return42** [comment]
As we have not heard any response to this request so far, I assume that the feature is not wanted in the SearXNG core.

For those coming around and think different, please add your comment / we can reopen this feature request as soon as serious use is desired
