### ISSUE TITLE
dictzone does no longer return results

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3582]
I assume the HTML layout of the response had been changed and we need an update of our XPath selectors:

https://github.com/searxng/searxng/blob/e9f8412a6e4b399a3335da73b3d321104bb0c4fb/searx/engines/dictzone.py#L25

**Comment by allendema** [comment]
`!dictzone de-en hello` return results here.

**Comment by return42** [comment]
> `!dictzone de-en hello` return results here.

thanks :+1:  .. forgot  its a dictionary engine :facepalm:
