### ISSUE TITLE
Bug: genius engine

### ISSUE THREAD

**Issue by MandiYang** [searxng/searxng#3584]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: Searxng
Branch: master
Version: 2024.6.7+f5eb56b63

**How did you install SearXNG?**
By using the install script, I can't search up lyrics using the genius engine, do I need an API key?

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Error
> 
>   * Error: searx.exceptions.SearxEngineAccessDeniedException
>   * Percentage: 100

Hm, strange .. I do not have issues with genius https://darmarit.org/searx/search?q=!genius+maceo+parker  .. may your IP is blocked by https://genius.com/ ?

**Comment by omentic** [comment]
(Genius pretty aggressively blocks exit nodes of VPNs, FYI - is your server running behind one?)

**Comment by MandiYang** [comment]
I am also running a tor relay on my free oracle vps server, does that count?

**Comment by return42** [comment]
> I am also running a tor relay on my free oracle vps server, does that count?

If this answer your question .. try to open https://genius.com/ in a tor browser ..

![grafik](https://github.com/searxng/searxng/assets/554536/dc7dbfe5-04de-415d-802b-06ff70dacf99)
