### ISSUE TITLE
Dragging highlighted text to a new tab does not work

### ISSUE THREAD

**Issue by kchousos** [searxng/searxng#3590]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Docker version: 2024.6.20+f195d98bf

**How did you install SearXNG?**

From the official docker compose

**What happened?**

When highlighting text and dragging it in a new tab in Firefox 127, SearXNG does not perform a search, it just loads the starting page.

**How To Reproduce**

1. Make SearXNG the default search engine.
2. Highlight some text in a tab.
3. Drag it to create a new tab.

**Expected behavior**

There should be a new SearXNG tab with the dragged text as a search query.

**Comment by return42** [comment]
Works for me; FF 126 and [OpenSearch](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine) .. not sure its related but my instance https://darmarit.org/searx/ uses HTTP GET method by default.

**Comment by kchousos** [comment]
I tried both POST and GET, same issue persists.

**Comment by return42** [comment]
> 1. Make SearXNG the default search engine.

How? .. did you used [OpenSearch](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine)?

**Comment by kchousos** [comment]
> did you used [OpenSearch](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine)?

Yes. I removed it and added it again just now and the problem persists.

**Comment by return42** [comment]
> in Firefox 127

on what OS & desktop?

**Comment by kchousos** [comment]
Fedora Linux 40, Gnome 46 under Wayland.

**Comment by Bnyro** [comment]
My SearXNG instance says the following in the debug logs:
`
OK ::/48: /search || X-Forwarded-For: my.ip.address || X-Real-IP: my.ip.address || form: {} || Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 || Accept-Language: en-US,en;q=0.5 || Accept-Encoding: gzip, deflate, br, zstd || Content-Type: None || Content-Length: None || Connection: None
`
when dragging text to a new tab as describe above.

So it seems that the search query is not actually forwarded anywhere (at least SearXNG doesn't see any query), I can't tell why as it works for DDG & co.

**Comment by return42** [comment]
> My SearXNG instance says the following in the debug logs:

Strange; I can reproduce it on a `make run` instance .. but not on my instance at https://darmarit.org/searx/ .. could you give my instance a try and report if it works for you or not / thanks!

**Comment by Bnyro** [comment]
> Strange; I can reproduce it on a `make run` instance .. but not on my instance at https://darmarit.org/searx/ .. could you give my instance a try and report if it works for you or not / thanks!
>
Yep, your instance works perfectly ...

**Comment by return42** [comment]
> Strange; I can reproduce it on a make run instance .

but when setting GET method in settings.yml its works --> POST vs GET is the problem!

> I tried both POST and GET, same issue persists.

Nope .. this issues is caused by POST methode .. I send PR #3619 .. 

When you tested POST vs GET you probably didn't delete the search engine from the browser and add it again .. it can be very confusing to have GET in the search field but the browser continues to use POST in the tabs .. thats why I locked this property in the UI / see my descriptions to #3619 ..

**Comment by kchousos** [comment]
@return42 Thank you very much! It works!

> When you tested POST vs GET you probably didn't delete the search engine from the browser and add it again .. it can be very confusing to have GET in the search field but the browser continues to use POST in the tabs .. thats why I locked this property in the UI / see my descriptions to #3619 ..

Indeed, when I tried it, I did not remove the search engine. Thanks for the clarification.
