### ISSUE TITLE
Restarts

### ISSUE THREAD

**Issue by blade10101** [searxng/searxng#3593]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Powered by [searxng](https://search.darkness.services/info/en/about) - 2024.6.20+f195d98bf

**How did you install SearXNG?**

Used searxnf-docker

**What happened?**

Most of the time when typing in the search box anything it just reloads the page instead of displaying any results. If I repeatedly do it over and over it will sometimes display the results.

**How To Reproduce**

Type anything in the search box.

**Expected behavior**

I expect the results page to show up.

**Screenshots & Logs**

**Additional context**

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/issues/3191
