### ISSUE TITLE
Mullvad Leta: Enable Configuration to switch between Google or Brave engine

### ISSUE THREAD

**Issue by glanham-jr** [searxng/searxng#3594]
**Is your feature request related to a problem? Please describe.**
No - this is a new feature request for an existing working engine.

**Describe the solution you'd like**
Naieve initial solution to allow basic switching
1. In the yaml engine file, allow either `Google` or `Brave` to be selected. By default, it will be `Google` if nothing is provided.
2. Update the mullvad leta engine to propagate this information to the request. The form data needs to be updated to send which engine is selected.

**Describe alternatives you've considered**
I'm curious if this is possible - is there a way to switch between the two at runtime? i.e. an override bang for `mlg -> Mullvad Leta Google` and `mlb -> Mullvad Leta Brave`? This would be nice from a user experience that the engine doesn't need to hard configure it but the user can select it with the bangs and also send 2 requests for 2 different engines.

Also curious if I could split this into multiple engines (`MullvadLetaGoogle` and `MullvadLetaBrave`), but with the core logic the same and shared somewhere. I'm not sure if this has been done or how support of this would look like. While this is a but more awkward, it would support the above

**Additional context**
Since I worked on the original Mullvad Leta integration, and I use it daily, I'm also happy to pick this up. I'm writing it down here for visibility and implementation discussion.

Screenshot of the updated Leta engine which supports Google / Brave.
![image](https://github.com/searxng/searxng/assets/58887802/a6ebe747-25e3-463a-a269-1def1c4eb320)

POST form-requests updates needed to update:

```
Content-Disposition: form-data; name="engine"

google
```

```
Content-Disposition: form-data; name="engine"

brave
```

**Comment by Austin-Olacsi** [comment]
IMO we should have a single mullvad leta engine in the settings.yml and just have the option in there, like mullvad_search_engine: google. of course the admin could easily add a second mullvad leta engine just by editing the yml file.

**Comment by glanham-jr** [comment]
So in this case, we have 1 engine, but we can copy/paste the yaml file which will serve a 2 engines pointing to the same implementation. Makes sense, just wasn't sure this was possible 😄 lets go with the suggested approach as you said.
