### ISSUE TITLE
Google News no results

### ISSUE THREAD

**Issue by ROHANREDDYGADE** [searxng/searxng#3598]
version - 1.0.0

Installed - manually

In the log it has been shown as our search query is success with 200 code but not returning any results for Google News
**How To Reproduce**

Turn off all other search engines for news and just use Google news the output will be like:-

Sorry!

No results were found. You can try to:

Refresh the page.
Search for another query or select another category (above).
Change the search engine used in the preferences: [/preferences](http://127.0.0.1:8888/preferences)
Switch to another instance: https://searx.space/

**Screenshots & Logs**

![news_log](https://github.com/searxng/searxng/assets/114584272/0fcb1430-f0b6-4b4a-99f2-9a7a874eee78)
![image](https://github.com/searxng/searxng/assets/114584272/a35b0c45-e9ff-4037-89f4-d35a5443a810)

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/issues/3277

**Comment by ROHANREDDYGADE** [comment]
https://news.google.com/search?q=sachin&hl=en-US&lr=lang_en&cr=countryUS&ie=utf8&oe=utf8&gl=US&ceid=US:en
it is getting redirected to the correct url and we are getting the html doc when used in postman for this google link but not working in searxng

**Comment by return42** [comment]
> it is getting redirected to the correct url

Nope .. its redirected to https://consent.google.com/m?continue=https://news.google.com/search?q%3Dsachin%26hl%3Den-US%26lr%3Dlang_en%26cr%3DcountryUS%26ie%3Dutf8%26oe%3Dutf8%26gl%3DUS%26ceid%3DUS:en&gl=DE&m=0&pc=n&cm=2&hl=en-US&src=1

@unixfox already pointed you to the issue https://github.com/searxng/searxng/issues/3277 .. if you have further info, please discuss it there.
