### ISSUE TITLE
Language auto-detection detects wrong language, and it affects search results

### ISSUE THREAD

**Issue by ferreus** [searxng/searxng#3604]
Using public instances.
2024.6.23+9a9ca307f

**How To Reproduce**
Search for anything in english, for example: "Searxng issue tracker"
The search results page shows language as: "Auto-detect (en-GB)"

**Expected behavior**
The search results page shows language as: "Auto-detect (en)"

**Screenshots & Logs**
![Screenshot from 2024-06-24 14-24-53](https://github.com/searxng/searxng/assets/206508/1c4b6b0e-e5a2-4b83-b55f-a8634bb5bb12)
![Screenshot from 2024-06-24 14-25-13](https://github.com/searxng/searxng/assets/206508/1d4cdad5-e227-426a-b1c6-16e725fcc93a)

**Comment by return42** [comment]
Its not a bug, its a feature ;-)

From https://github.com/searxng/searxng/issues/2018

> SearXNG's locale of a query comes from (_highest wins_):
> 
> 1. The `Accept-Language` header from user's HTTP client.
> 2. The user select a locale in the preferences.
> 3. The user select a locale from the menu in the query form (e.g. `:zh-TW`)
> 4. Autodetection plugin is activated in the preferences and the locale (only the language code / none region code) comes from the fastText's language detection.

To not have too often wrong matches from fastText's language detection we set the threshold to `0.8`:

https://github.com/searxng/searxng/blob/9a9ca307fe53ea8ed9d18a06a1a7da9fa4a1c28f/searx/webadapter.py#L269-L271

- `4.` for your search Term "SearXNG issue tracker" the probability is lower `0.8` --> `None`
- `3.` you selected `auto` / or `auto` is the default
- `2.` if I assume you did not set a language in the preferences --> `None` (or you set en-GB preferences)
- `1.` seems your browsers sends `Accept-Language` `en-GB` / check your browser's locale settings .. I'm right?

Related:

- https://github.com/searxng/searxng/discussions/266
- https://github.com/searxng/searxng/issues/2018

**Comment by ferreus** [comment]
You where right, my browser had two languages English United Kingdom and English for some reason.
After I removed the UK one, it correctly detects the language.
Thank you.
