### ISSUE TITLE
Min. 10 Pages when there is one result

### ISSUE THREAD

**Issue by 4yman-0** [searxng/searxng#3614]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.6.17+accc1c103 (https://github.com/tiekoetter/searxng/commit/9f4de22f20ba45851ba11cbe2a8ee9019c4226e2)
in https://searx.tiekoetter.com/

**How did you install SearXNG?**

SearXNG is not mine. I do NOT own this instance.

**How To Reproduce**
1. Go to [EXAMPLE](https://searx.tiekoetter.com/search?q=%22browser.migrate.chromium.enabled%22) link or any search with few results.
2. Find 10 links at the bottom (1 2 3 4 ...).
3. Click on any link except 1
4.  Find "There are no more results" error

**Expected behavior**
Find one link or none at all

**Screenshots & Logs**
![10 links in page](https://github.com/searxng/searxng/assets/170770027/314d37eb-8f90-4fef-8cce-bd9b61b9cced)
I do NOT have any access to logs.

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/discussions/3538

**Comment by 4yman-0** [comment]
IDC
