### ISSUE TITLE
Ebay - Custom Engine

### ISSUE THREAD

**Issue by lscherub** [searxng/searxng#3628]
**Working URL to the engine**

https://www.ebay.com/sch/i.html?_nkw={query}

**Why do you want to add this engine?**

I want to add a shopping category to my searxng instance. 

**Features of this engine**

Product search.

**How can SearXNG fetch the information from this engine?**

- name: ebay
    engine: xpath
     paging: true
     shortcut: eb
     base_url: https://www.ebay.com/sch/i.html?_nkw={query}
     url_xpath: //h3[@class='s-item__title']/parent::a/@href
     title_xpath: //h3[@class='s-item__title']
     content_xpath: //div[@class='s-item__subtitle']
     disabled: true
     timeout: 10.0

**Applicable category of this engine**

Other, General, Shopping

**Additional context**

**Comment by allendema** [comment]
Simply uncomment it in your settings.
https://github.com/searxng/searxng/blob/39aaac40d63d53555b7fc12d56f0825c85ecf567/searx/settings.yml#L731-L736
