### ISSUE TITLE
Search Engines Timeout On Raspberry Pi

### ISSUE THREAD

**Issue by WillChamness** [searxng/searxng#3636]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Latest docker image:

searxng/searxng:2024.7.3-4eaa0dd27

**How did you install SearXNG?**
Via docker on a Raspberry Pi 4b 8GB model and on an x64 Ubuntu Server 20.04 instance.

**What happened?**
Some engines timeout and do not return results. I am using a Raspberry Pi. Here is a description of the steps I took to troubleshoot:

At first, ALL engines timeout were giving an error (screenshot 1). After looking around, I noticed that DNS queries take an unusually long time to resolve in docker (screenshot 2). Note that this is not an issue with Searxng specifically; other containers do the same thing. My solution to this issue was to change `/etc/resolv.conf` in the Searxng docker container to use a different nameserver, which sped up DNS resolutions significantly (screenshot 3). Although this works for some search engines, others still give the same error (screenshot 4).

I also tried this on Ubuntu Server 20.04. Nothing appears out of the ordinary. DNS resolution time is the same on both the docker container and the host by default. All search engines return results very quickly with no issue.

**How To Reproduce**
Install Docker and pull the latest image of searxng/searxng on a Raspberry Pi. Run the container and run any query. All search engines should timeout.

This is what I did to get the DNS query time:
- Inside the docker container, run `apk update && apk add bind-tools`
- Run `dig google.com`
- The query time (for me) is 4 seconds.

**Expected behavior**
All search engines returning results.

**Screenshots & Logs**
![searxng error](https://github.com/searxng/searxng/assets/105455707/35581705-6831-499e-b82c-9c6f3c569554)

![raspi dig result](https://github.com/searxng/searxng/assets/105455707/89125b45-4d08-4be7-a3f9-584837447b82)

![searxng resolv](https://github.com/searxng/searxng/assets/105455707/8491e170-4c2d-47dd-bf06-580f34238be0)

![searxng error 2](https://github.com/searxng/searxng/assets/105455707/1e03225c-2be5-4e2c-babb-b2d2fd85c2bd)

**Additional context**
The same error happened a few months ago. Presumably, the cause is the same. Unfortunately, I don't remember exactly when. At the time, the issue somehow resolved itself while troubleshooting, but now I am getting the same error.

**Comment by return42** [comment]
If all engines are running in timeouts, it is very clear that this is not a bug in SearXNG, but a problem with the IP infrastructure in which the SearXNG instance is running.

To all coming around: please do not create new bug reports for such problems here in the ticket system for the SearXNG software.

- https://github.com/searxng/searxng/discussions/3223
- https://github.com/searxng/searxng/issues/3626
- https://github.com/searxng/searxng/issues/1962

We have an excellent community with which you can exchange experiences about the operation of SearXNG on Matrix.  For such problems, it is also recommended to discuss them on [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org), where you will usually get better feedback.

**Comment by WillChamness** [comment]
Hi,

Sorry for the confusion. Maybe I should have been more clear. I added the details about all search engines timing out to document what I have done so that other people might have an idea of why they are having this issue. As you mentioned, it was not an issue with SearXNG, but with Docker. 

The current issue that I am having is that only some search engines time out, but not all. As mentioned in the description, this only occurs on my Raspberry Pi. I do not have this issue on an x64 device. To help you understand the infrastructure of my home network, here is a quick sketch of the topology:

![topology](https://github.com/searxng/searxng/assets/105455707/a68592f1-1208-4777-9ede-2840ffc400b0)

If you still think this is an issue with my IP infrastructure, then fair enough. I will see what I can do to resolve this on my own.

**Comment by return42** [comment]
> My solution to this issue was to change /etc/resolv.conf in the Searxng docker container to use a different nameserver, which sped up DNS resolutions significantly (screenshot 3). Although this works for some search engines, others still give the same error (screenshot 4).

> As mentioned in the description, this only occurs on my Raspberry Pi. I do not have this issue on an x64 device.

> If you still think this is an issue with my IP infrastructure, then fair enough. I will see what I can do to resolve this on my own.

In the use case where it only occurs on you Pi, yes .. The causes for this can be very varied, for example:

The duration of the DNS resolution and the duration of an engine response are added to a total response time ... if, for example, the timeout of an engine is 3sec (the default timeout in SearXNG) and the engine needs ~2sec for the response, but the DNS resolution also takes around one second, then there is a good chance that the total time is above the timeout of 3sec.

I'm sorry, but here in the SearXNG software development we can't help more with docker, DNS and other topics related to the infrastructure .. believe me, those topics are better discussed at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) ..

**Comment by WillChamness** [comment]
Understandable. I'll take a look at that later. I appreciate your time and your patience with me. Just wanted to also mention that, as shown in the screenshots, DNS resolution time was about 15msec. I guess it could be a bandwidth issue causing responses to slow down, but I didn't think that was the case. I don't have it in front of me at this time, but I believe I made the request_timeout and max_request_timeout settings to 5.0 and 10.0 respectively. I will probably look into it later. Thanks!

**Comment by unixfox** [comment]
more related issues:
- https://github.com/searxng/searxng/issues/1181
- https://github.com/searxng/searxng/issues/1563

**Comment by WillChamness** [comment]
I do not have Pi-hole installed, and the container is able to resolve DNS queries just fine, as shown in the screenshots. I'll still look into DNS when I have the time, though. Thanks again!
