### ISSUE TITLE
The engine "gentoo" is missing.

### ISSUE THREAD

**Issue by devops-snap-shoot** [searxng/searxng#3641]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**
 manually by executing the searx/webapp.py
**What happened?**

give me erro The engine "gentoo" is missing.
**How To Reproduce**

by executing the searx/webapp.py
**Expected behavior**

eliminate gentoo or add as search engine 
**Screenshots & Logs**

**Comment by return42** [comment]
Please check you rebased/merged branch .. or checkout SearXNG's master .. you did some mistakes while merge/rebase.
