### ISSUE TITLE
Do not prefix language select with icons.

### ISSUE THREAD

**Issue by mdillondc** [searxng/searxng#3645]
**Is your feature request related to a problem? Please describe.**
When selecting the language to search, do not prefix each select option with an icon.

**Describe the solution you'd like**
Currently, if I click the select menu and start typing e.g. "sv" for "Svenska", the select list won't be able to select sweden because the icon is in the way. If you get rid of the icons, people could use the keyboard to select what language they want used in the search by typing the keyboard. As it is now, the user has to use their mouse and/or arrow keys to scroll down the list of every country in the world. It doesn't make any sense.

**Comment by glanham-jr** [comment]
Here is an image of the issue mdillondc is referring to. I wonder if there is a way to get icons without sacrificing the list search. At the very least, icons could be flush to the right with even spacing?

![image](https://github.com/searxng/searxng/assets/58887802/7f66ea23-8b3b-459b-a828-13e3a4f4218b)

**Comment by glanham-jr** [comment]
Was able to fix this in #3647 - will need review from a maintainer if they wish to continue
