### ISSUE TITLE
Image search: fixed search parameters

### ISSUE THREAD

**Issue by madcollectordev** [searxng/searxng#3657]
While browsing the search results from an image search, the search input scrolls with the page. To adapt the query, one has to scroll all the way back up.

It woud be nice if the input was in a fixed floating position, always at the top of the frame.

Mockup:
![image](https://github.com/user-attachments/assets/632890c5-308b-4e8e-9b79-73d45a34994d)

**Comment by return42** [comment]
> To adapt the query, one has to scroll all the way back up.

Just type `i` to jump into the search field .. BTW type `h` to get an overview of the hotkeys:

![image](https://github.com/user-attachments/assets/a38f0235-0c06-451e-a5f8-1136acff1fc7)
