### ISSUE TITLE
Auto-detect Language don`t work

### ISSUE THREAD

**Issue by Otar666** [searxng/searxng#3658]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.7.13+5468d97d3

**How did you install SearXNG?**
 Im using a public instance, but the same happened on my own install of the latest version

**What happened?**
 When you select the language Auto-detect the detected language is always english for me, i speak a few and queries in other languages are always selected as en-US, maybe because its the default of the operational system and browser too.

**How To Reproduce**
 Just make a query using another language with Auto-detect selected

**Expected behavior**
 The query language to be selected instead

**Screenshots & Logs**
 Not needed, easy to reproduce.

**Additional context**
 Not needed.

**Comment by return42** [comment]
> When you select the language Auto-detect the detected language is always english for me, i speak a few and queries in other languages are always selected as en-US,

"en-US" is the default .. given by your browser settings. [To not have too often wrong matches from FastText's language detection we set the threshold to `0.8`](https://github.com/searxng/searxng/issues/3604#issuecomment-2186484253).

Related:

- https://github.com/searxng/searxng/issues/2018
- https://github.com/searxng/searxng/issues/3604
