### ISSUE TITLE
hostnames replace

### ISSUE THREAD

**Issue by caywin25** [searxng/searxng#3664]
I don't know if it's really a bug but I just implemented the hostnames plugin as described here: 

> https://docs.searxng.org/dev/plugins/hostnames.html

and it seems that it doesn't work :(
I have no errors but no rewriting is done.
Can you help me please ?
Thanks

**Comment by return42** [comment]
We had already a long discussion about this .. check your settings carefully:

- https://github.com/searxng/searxng/issues/3558#issuecomment-2175058128

And don't forget to activate the plugin ;-)

**Comment by caywin25** [comment]
OK all it's good 
Thx :)
