### ISSUE TITLE
SSL error: certificate validation has failed

### ISSUE THREAD

**Issue by andersnordh** [searxng/searxng#3668]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.7.20+657dcb973

**How did you install SearXNG?**
Fresh install using the official Wiki.

**What happened?**
When adding a search phrase all search engines report back a SSL failure.

Error! Engines cannot retrieve results:
brave ( [SSL error: certificate validation has failed](https://search.nordh.tech/searxng/stats?engine=brave) )
duckduckgo ( [SSL error: certificate validation has failed](https://search.nordh.tech/searxng/stats?engine=duckduckgo) )
google ( [SSL error: certificate validation has failed](https://search.nordh.tech/searxng/stats?engine=google) )
wikipedia ( [SSL error: certificate validation has failed](https://search.nordh.tech/searxng/stats?engine=wikipedia) )

**How To Reproduce**
Any search phrase generate the same result, SSL fail.

**Expected behavior**
Search results presented.

**Screenshots & Logs**
![Skärmavbild 2024-07-21 kl  21 30 59](https://github.com/user-attachments/assets/64a99cb9-9ee0-4991-8445-8e4c367849e1)

**Additional context**

**Technical report**

Error
  * Error: ssl.SSLCertVerificationError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/duckduckgo.py:119`
  * Function: `get_vqd`
  * Code: `res = get(query_url)`

The server is available at https://search.nordh.tech ...

**Comment by return42** [comment]
> **How did you install SearXNG?**
> Fresh install using the official Wiki.

We do not have a wiki. If all engines end with an SSL error, then it is pretty obvious that the root cause is to be found in the outgoing network and not in SearXNG.

I'm sorry, but here in the SearXNG software development we can't help more with TLS/SSL and other topics related to the infrastructure .. those topics are better discussed at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) ..

**Comment by andersnordh** [comment]
If someone else is experiancing this issue, you might have a problem with DNS being reverse proxied. Try to point the server to 8.8.8.8 ... ;-)
