### ISSUE TITLE
How to add a SearXNG instance on `localhost` to the browser

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3679]
Setting browser homepage for local instance is not trivial, in Firefox there are 3 places where Google is the default search engine. I need to use two extensions, 1 to change the address bar search engine to searxng and the other to change the new tab start page, the home button start page is still editable through Firefox settings.  

It would be great if there was a documentation addition/upgrade detailing how to set searxng as the default startpage in all the places in the major browsers.

The two extensions I use are...

Firefox New Tab Change Startpage for SearXNG

https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/

Change Address bar Search Engine to SearXNG

https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/

and the third setting is in the browser.

Browser market share:
Chrome
Safari
Firefox
Opera

**Comment by return42** [comment]
> It would be great if there was a documentation addition/upgrade detailing how to set searxng as the default startpage in all the places in the major browsers.

We are in luck, there is already one :-) --> [How do I set it as the default search engine?](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine)

This documentation is also available at the *"about"* page of a SearXNG instance.

**Comment by Immortality-IMT** [comment]
The Firefox instructions are not correct for local instances running on localhost.
![Uploading Screenshot from 2024-07-27 14-54-24.png…]()

**Comment by return42** [comment]
Sorry haven't seen that you addressed SearXNG instances on localhost .. I think this is not a common use case .. anyway I reopen this issue / I edited the title of this issue.

**Comment by return42** [comment]
> The Firefox instructions are not correct for local instances running on localhost.
![Uploading Screenshot from 2024-07-27 14-54-24.png…]()

Please fix the link to the image.

**Comment by return42** [comment]
Closed due to lack of response.
