### ISSUE TITLE
Image category: layout using flexbox instead of javascript

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#368]
The image sizes are changed to fill the screen width:

Oscar:
![image](https://user-images.githubusercontent.com/1594191/135585174-3ba68eb4-5ef4-4659-94fb-3e7035895db9.png)

Simple theme:
![image](https://user-images.githubusercontent.com/1594191/135585247-2e4c8328-f6a0-4937-b295-cc23a77d37c1.png)

The current implementation use javascript: https://css-tricks.com/adaptive-photo-layout-with-flexbox/

It would be interesting to use CSS:
* to reduce the number of javascript files
* not to use the `style` attributes

Possible implementation: https://css-tricks.com/adaptive-photo-layout-with-flexbox/

The implementation can focus on the simple theme.

**Comment by dalf** [comment]
from https://github.com/searxng/searxng/issues/523#issuecomment-974117015
ping @mrpaulblack 

After a quick test, it works, but it requires to create HTML element to group the images when there are mixed result (from the general category and image category).

(I don't have a preference between flex or grid).

**Comment by mrpaulblack** [comment]
Just as a heads up I strongly prefer grid layout...

**Comment by return42** [comment]
@mrpaulblack how would you rate it, is this PR a requirement for #665?

**Comment by mrpaulblack** [comment]
Yeah its part of the simple theme board, I am going to start working on the project in early January and tackle a lot of these issues... But please just hold on for a while, thanks :+1: 

[EDIT] and yeah I forgot this when I approved your PR earlier today :/
