### ISSUE TITLE
Start page quick links like the forefox start page

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3699]
Quick links below the search to imitate Firefox start page, which I find convenient. Has someone already done this?

I developed a version of quick links which I use for my private instance, screenshot attached, and now I am upgrading it and need some tips on privacy implementation. I assume it only acceptable implementation is as cookies, and perhaps the links can be manually added somewhere in the preferences tab.

Adding a template is easy enough.
With an add link form that updates the cookie. I assume it's only two places, the template and /route/prefernces

The alternative saved the links to a text file.
Attached are some screenshots of where I am at.[
![Screenshot from 2024-07-31 18-10-06](https://github.com/user-attachments/assets/738f851a-fcb4-4131-a755-1ef2035cb9dc)
![Screenshot from 2024-07-31 18-09-42](https://github.com/user-attachments/assets/f8401284-8f94-4db6-ba55-d30a1f105b86)
![Screenshot from 2024-07-31 18-09-07](https://github.com/user-attachments/assets/05529aad-8ff5-4934-b4b3-4dc35454a369)
](url)

**Comment by return42** [comment]
@Immortality-IMT I feel you constantly ignore my comments --> https://github.com/searxng/searxng/discussions/3678#discussioncomment-10160356

If you don't want to add a feature request and you just want to discuss your private hacking, the SearXNG core is the wrong place .. may you will find some echo at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
