### ISSUE TITLE
SearXNG logo wanted

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#370]
SearXNG needs a logo !

---

Currently the themes still use the searx logo.

The GitHub org logo: https://gist.github.com/dalf/b670d030ce191c1a6a3826df5ac9366d

png version:
![image](https://user-images.githubusercontent.com/1594191/135627863-d169fb24-c078-43ea-b9f8-55700ee1e424.png)

This is not my domain, a new logo would be welcomed.

**Comment by return42** [comment]
@dalf as we discussed / I will give it a try / sorry, I am still behind schedule :(

The Github org logo does not renders well in my FFox ..

![grafik](https://user-images.githubusercontent.com/554536/135627638-1c9133a4-99e5-4573-8cfe-1fcb23988470.png)

For the interim we can replace the logo by a string "SearXNG" I would suggest.

**Comment by dalf** [comment]
I've edited the original message to include a PNG version.

**Comment by return42** [comment]
> @dalf as we discussed / I will give it a try / sorry, I am still behind schedule ..

A first implementation is in #378

**Comment by nonetrix** [comment]
What font does the normal searx logo use?

**Comment by return42** [comment]
We have not committed ourselves to a font. If we use a font in the design of the logo, the font license should be "free" ..  in the manner we use it in the logo.

**Comment by mrpaulblack** [comment]
Just FYI: There is also a light version of the search logo as well as the smaller favicon for the dark mode needed.

**Comment by SecularSteve** [comment]
I have another design proposition.

I couldn't decide on a variety with these layers, so I made all of them.

![searXNG_new_logo](https://user-images.githubusercontent.com/33793273/140885766-549d5590-0954-4aec-9fbe-e927b0febb11.png)

Pick and choose which one looks best, because I have no clue.

Released under the CC BY-SA 4.0, made in Inkscape.

ZIP contains SVG and PNG...

[searXNG_new_logo.zip](https://github.com/searxng/searxng/files/7503011/searXNG_new_logo.zip)

**Comment by mrpaulblack** [comment]
@SecularSteve I really like your logo idea (especially the last one), but I think that that green is not really representative for SearXNG anymore... I think this logo would work really well with the blue color we used with the watermark and temp. logo and the text color color could be `@base-font` color in dark and light mode respectively ... What do you think @dalf @return42 ?

[EDIT] also not sure the license works with SearXNG?

**Comment by return42** [comment]
Personally I prefer what we have in the simple theme https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/img/searxng.svg .. may be we can polish up it a little bit but not to much glitter and colours, I think. And it should be flat, no shadow or 3D effects / compare https://github.com/searxng/searxng/issues/472.

**Comment by raskitoma** [comment]
Any clues on the location to use any of those logos into my instance?

I'm using a docker container, I would like to know the image current path.

Thanks in advance.

**Comment by return42** [comment]
@raskitoma I want to route you to the discussion:

- https://github.com/searxng/searxng/discussions/1413#discussioncomment-3071351
