### ISSUE TITLE
Quicklinks like the Firefox Start Page

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3700]
As a start page, I have a selection of frequently visited websites rather than performing a search. For example, the Firefox start page, there is the search and several frequently visited websites below the search.

I would like a similar implementation into searxng. 

The alternatives I have considered is a custom implementation that used a flat file to store the websites, considering the privacy search engine I would assume cookies would store the frequent sites. Perhaps the websites could be listed in preferences and added/deleted manually.

Here is a screenshot of how searxng could appear after the implementation.
![Screenshot from 2024-07-31 20-18-19](https://github.com/user-attachments/assets/419c9bb0-66d6-4f6d-a04a-da92172e24a3)

**Comment by Immortality-IMT** [comment]
I find my self doing a general search and then selecting images because there is no way to jump directly to an image search. I copied the categories from search template into the simple search template.

![Screenshot from 2024-08-08 08-20-02](https://github.com/user-attachments/assets/dd29ade9-8481-49c1-b0ab-ab29730b3ee6)

**Comment by return42** [comment]
As we have not heard any response to this request so far, I assume that the feature is not wanted in the SearXNG core.
