### ISSUE TITLE
pip -e --> DEPRECATION: Legacy editable install of searxng==... (setup.py develop) is deprecated.

### ISSUE THREAD

**Issue by ralphrmartin** [searxng/searxng#3701]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.7.29+98c73010f
-->
**How did you install SearXNG?**
By following the wiki

**What happened?**
I entered  the following to update searxng:
`cd ~searxng/searxng-src; sudo -H ./utils/searxng.sh instance update
`and got the following warning output (otherwise the update seems to have gone ok)
```
  |searxng|   DEPRECATION: Legacy editable install of searxng==2024.7.29+98c73010f from file:///usr/local/searxng/searxng-src (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  |searxng|   Running setup.py develop for searxng
  |searxng| Successfully installed searxng-2024.7.29+98c73010f

```
My server is running Python 3.11.2

**How To Reproduce**
Presumably just by using a new enough Python / Pip and running sudo -H ./utils/searxng.sh instance update on an installed searxng

**Expected behavior**
Should complete without a deprecation warning, to avoid problems down the line

**Screenshots & Logs**

**Additional context**
Using debian bookworm.

**Comment by return42** [comment]
> I entered the following to update searxng:
> `cd ~searxng/searxng-src; sudo -H ./utils/searxng.sh instance update `

Not from `~searxng/searxng-src` .. updates follow the same rules as install:

```
$ cd ~/Downloads
$ git clone https://github.com/searxng/searxng.git searxng
$ cd searxng
$ sudo -H ./utils/searxng.sh instance update
```

**Comment by ralphrmartin** [comment]
doing 
`cd /tmp; git clone https://github.com/searxng/searxng.git searxng; cd searxng; sudo -H ./utils/searxng.sh instance update
`
I still get the deprecation warning:
```
 |searxng|     Uninstalling searxng-2024.7.29+98c73010f:
  |searxng|       Successfully uninstalled searxng-2024.7.29+98c73010f
  |searxng|   DEPRECATION: Legacy editable install of searxng==2024.7.29+98c73010f from file:///usr/local/searxng/searxng-src (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

```

**Comment by return42** [comment]
Related to https://github.com/pypa/pip/issues/11457

Deprecation message is reported on every `pip -e .`  .. we already have it when using `make run` for example.

**Comment by ralphrmartin** [comment]
I confirm the message no longer occurs.
