### ISSUE TITLE
Add Yandex Search Engine support

### ISSUE THREAD

**Issue by 825i** [searxng/searxng#3706]
**Is your feature request related to a problem? Please describe.**
I would like SearxNG to contain boilerplate for working with Yandex by default. Even if the option is disabled by default.

**Describe the solution you'd like**
Working settings.yml boilerplate code for Yandex

Yandex is one of the most popular search engines in the world. It should be an option when using SearxNG and not need to be configured or enabled manually.

**Comment by return42** [comment]
Duplicate https://github.com/searxng/searxng/issues/961
