### ISSUE TITLE
Bug: google scholar engine

### ISSUE THREAD

**Issue by Tuwase** [searxng/searxng#3708]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.01

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 100
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/google_scholar.py:89`
  * Function: `detect_google_captcha`
  * Code: `raise SearxEngineCaptchaException()`

**Comment by return42** [comment]
- https://github.com/searxng/searxng/issues/3615

duplicate
