### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by Tuwase** [searxng/searxng#3709]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.01

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('get_sc_code: [PR-695] query new sc time-stamp failed! (https://www.startpage.com/en/errors/?t=device&sc=0tFkGsEmGcK920)',)`
  * File name: `searx/engines/startpage.py:231`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineCaptchaException(`

**Comment by return42** [comment]
- https://github.com/searxng/searxng/issues/2989

duplicate
