### ISSUE TITLE
Bug: bing engine

### ISSUE THREAD

**Issue by Tuwase** [searxng/searxng#3711]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.01

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**
 I performed a simple search which returned the errors I submitted as bugs all errors are from a single search.

**Expected behavior**
 I expected search results not errors.

**Screenshots & Logs**
 All of this should be a automated process. I have none.

**Additional context**

**Technical report 

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.bing.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> I performed a simple search which returned the errors I submitted as bugs all errors are from a single search. 

Next time please follow the rule  ..

![image](https://github.com/user-attachments/assets/74adca63-eff9-4962-b5d3-a6b4d4f77d62)
