### ISSUE TITLE
Engine request: Swisscows

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#3712]
**Working URL to the engine**
https://swisscows.com/en

**Why do you want to add this engine?**
Swisscows would offer users an alternative to DuckDuckGo, as both utilize results from Bing with claims of respecting user privacy.

**Features of this engine**
Claims to keep the end user anonymous with claims that storage of user data is impossible in their infrastructure. Does not utilize cookies, and filters adult content from results.

**Applicable category of this engine**
general, images, videos, music

**Additional context**
Appears as if the search engine was removed from Searx (ffe0972f9) according to [this issue](https://github.com/searx/searx/issues/1859) in their now-archived repository. Unsure if the issues experienced then still apply as four years have passed since.

**Comment by Bnyro** [comment]
From my research today, the only categories that can be fetched without a request nonce and signature are news and audio, which are probably not the most useful categories.

Any other categories require some sort of verification, similar to what's described in https://github.com/searx/searx/issues/1859#issuecomment-589952307. Hence this engine is very unlikely to be added as per my point of view.
