### ISSUE TITLE
Bug: currency engine

### ISSUE THREAD

**Issue by DanielSzewczuk** [searxng/searxng#3713]
Repository: https://github.com/searxng/searxng-docker
Branch: master
Version: 2024.8.2+c151683a0

**How did you install SearXNG?**
Searxng-docker

**What happened?**
When I try to lookup PLN exchange rate, it throws an error.

**How To Reproduce**
Search "1 pln to usd"

**Expected behavior**
See exchange rate for 1 pln.
![image](https://github.com/user-attachments/assets/edf1b19b-a509-464e-aa6f-4eb3739f8aed)

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('400', 'Bad Request', 'duckduckgo.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mintsuku** [comment]
I would be interested in tackling this issue, I’ve been using SearXNG for roughly 6 months now. I am not sure how I can be familiarized with the codebase though. I also apologize if this is the wrong place to ask!

**Comment by Immortality-IMT** [comment]
On 1 January 1995, 10,000 old złoty (PLZ) became one new złoty (PLN).

Searx makes the call with: https://duckduckgo.com/js/spice/currency/1/PLZ/AUD but should be https://duckduckgo.com/js/spice/currency/1/PLN/AUD

Delete all instances of PLZ and replace with PLN, likely in file searxng-src/searx/data/currencies.json

**Comment by mintsuku** [comment]
@Immortality-IMT Thank you! I appreciate the help! I’ll have this fixed by tomorrow or so!
