### ISSUE TITLE
If no search is entered, disable the search button until query is input

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3714]
Version 2024.6.23
**1)**
If no search is entered, the search is performed with q="" and the page refreshes, giving the start page again.

Check the result on different existing search engines,  push the search button with no query.

In google, pushing the search button with no query gives trending topics
In DuckDuckGo, the search button is disabled until search query is entered

The solution is to replicate the DuckDuckGo action. Disable the button until a search term is entered.

Two layers, requires no python code change...

Add the html5 tag ** required ** in both the template searches, one being the search.html and the other being simple_search.html, output a tooltip. However, this tooltip is only never shown if JavaScript is disabled and if previous html5 browser is used. Add the required tag.

```        
<input id="q" name="q" type="text" placeholder="{{ _('Search for...') }}" autocomplete="off" autocapitalize="none" spellcheck="false" autocorrect="off" dir="auto" value="{{ q or '' }}" required>
```
Adding the required tag will also add a input box hover tooltip.

**Comment by return42** [comment]
> The solution is to replicate the DuckDuckGo action. Disable the button until a search term is entered.

The use is too small, moreover there are users who have not activated Javascript.

**Comment by Immortality-IMT** [comment]
Do you mind if I catalog my changes here for my personal local instance?
