### ISSUE TITLE
Cloudflare & Rocket-Loader issue: JS - Cross to clear input field does not work on result page

### ISSUE THREAD

**Issue by pro-sumer** [searxng/searxng#3730]
EDIT: TL;DR; .. the user reports a CSP issue caused by a Cloudflare proxy .. 

---

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.8.9+f1c05e7c1

**How did you install SearXNG?**
searxng-docker

**What happened?**
Cross to clear input field does not work on result page (does work on start page) 

**How To Reproduce**
1. Search for any text
2. Click on the cross in the input field on the results page

**Expected behavior**
Input field is cleared after clicking on cross

**Screenshots & Logs**
![Input@2x](https://github.com/user-attachments/assets/5f75db2c-a671-4e53-aeef-3241ff614ec6)

**Additional context**
Seems to work fine on public instances?

**Comment by return42** [comment]
For me it works .. can you please test it on https://darmarit.org/searx/search?q=foo .. I tested with FFox and Chromium .. does the issue appears only in Safari?

> Seems to work fine on public instances?

Should work on any instance.

**Comment by pro-sumer** [comment]
Yes, it works fine on https://darmarit.org/searx/search?q=foo in Safari on Mac.

I experienced the issue with my instance both in Safari (Mac) and Mobile Safari (iPhone/iPad), but I just tested my instance in Firefox and Edge on a Windows PC. The cross does not work there either, so it's probably not the browser, but something with (the settings of?) my instance.

Hope to do some more experimenting this weekend.

**Comment by Immortality-IMT** [comment]
I have raised this issue previously, you have to copy and paste the query without using the keyboard to replicate the issue. As soon as you press the keyboard the cross appears.

If a search is pasted rather than entered by keyboard, the x clear button does not appear but still works. The x icon does not appear if no keyboard is used and the search term is pasted. Thereafter, if the keyboard is used, the clear input x appears. 

The fix is to look for the input event /searxng.min.js:

```
function a(t){
    var e=document.getElementById("clear_search");
    var n=function(){
        if(t.value.length===0){
            e.classList.add("empty")
        }else{
            e.classList.remove("empty")
        }
    };
    n();
    e.addEventListener("click",function(e){
        t.value="";
        t.focus();
        n();
        e.preventDefault()
    });
    t.addEventListener("keyup",n,false);
    t.addEventListener("input",n,false); // Add this line to handle paste events
}

**Comment by return42** [comment]
@Immortality-IMT [Your experience comes from an outdated copy of SearXNG that you are tinkering with](https://github.com/searxng/searxng/issues/3726#issuecomment-2282647078)

> Yes, it works fine on https://darmarit.org/searx/search?q=foo in Safari on Mac ..
> I experienced the issue with my instance .. The cross does not work there either, so it's probably not the browser, but something with (the settings of?) my instance.

@pro-sumer: Can you check the JavaScript files are loaded / I expect a `searxng.head.min.js` and a `searxng.min.js` to be loaded (use SHIFT-CTRL-I to open debugger in your WEB browser):

![image](https://github.com/user-attachments/assets/b91b9be0-2404-473e-8876-691cf56f5a91)

**Comment by return42** [comment]
> I have raised this issue previously, you have to copy and paste the query without using the keyboard to replicate the issue.

@Immortality-IMT : The issue you report here is different to the issue the opener reports .. please refer to your ticket where reported your issue previously .. than we can re-open this ticket from yours.

**Comment by pro-sumer** [comment]
> Can you check the JavaScript files are loaded / I expect a searxng.head.min.js and a searxng.min.js to be loaded (use SHIFT-STRG-I to open debugger in your WEB browser)

I think so:

![JavaScript@2x](https://github.com/user-attachments/assets/93b48a29-db29-4493-9887-55b70ddc84cc)

PS: For those wondering; "STRG" is (German for?) what is known as "CTRL" in most parts of the world. However, for Safari on Mac the shortcut to show the Web Inspector is `⌥⌘I`.

**Comment by pro-sumer** [comment]
Does the difference in error message on the result page lead us anywhere?

**My private instance**
![CSP-private@2x](https://github.com/user-attachments/assets/c1ee7570-f7a9-434d-99b3-7536a5d8e3d9)

**Random public instance**
![CSP-public@2x](https://github.com/user-attachments/assets/f4dd3acd-6537-45bd-a295-74378dc35115)

**Comment by return42** [comment]
> Does the difference in error message on the result page lead us anywhere?

Yes :-)  .. its an Content-Security-Policy (CSP) issue / https://github.com/searxng/searxng/issues/140

> Yes, it works fine on https://darmarit.org/searx/search?q=foo in Safari on Mac.

On my instance I do not have a CSP header

> How did you install SearXNG? .. searxng-docker

In the docker image the caddy HTTP server has a CSP header

https://github.com/searxng/searxng-docker/blob/35525c664bfaf340eeb8422eba5e0e6b1dadbc34/Caddyfile#L79-L82

Sorry, I can't help on setting up caddy in docker .. I move this ticket to the searxng-docker project.

**Comment by pro-sumer** [comment]
Note: (even) when changing
```
script-src 'self'
```
into
```
script-src 'self' 'unsafe-inline
```
in `Caddyfile` the errors are gone, but the cross still does not work.

**Comment by return42** [comment]
> in `Caddyfile` the errors are gone, but the cross still does not work.

Check again in browser's developer tools .. there might be other reasons why the JavaScript Code of the button is not loaded or executed.

**Comment by pro-sumer** [comment]
I tried again after removing all the `Content-Security-Policy` entries.

Not a single error/warning, but still nothing happens when I click on the cross (it does turn blue when I hove the cursor over it).

**Comment by return42** [comment]
Just to check other JS implementation do work: when you type `h` (cursor should not in the search box) do you see a help about the hotkeys pop up:

![image](https://github.com/user-attachments/assets/0ccba1a9-33a8-4697-9b40-4d2e713ff4a9)

**Comment by pro-sumer** [comment]
No, `h` does nothing at all.

For a moment I thought it fixed it by adding `cdnjs.cloudflare.com` to `script-src` (since I use Cloudflare's proxy), because when I did that, the cross did work in Safari on Mac. However, it did still not work in Mobile Safari on iPhone/iPad. When I then returned to my Mac it did not work there anymore either... (without me changing anything)

**Comment by return42** [comment]
> since I use Cloudflare's proxy)

oh no, not really? .. we are fighting with cloudflare quirks? .. Sorry I'm out.

Please understand, we do not support Cloudflare setups: it's not recommended to use Cloudflare as reverse proxy because it MITM every request, which is a disaster for user's privacy.

BTW Cloudflare is more or less the cause of such a lot of issues: https://github.com/search?q=org%3Asearxng+cloudflare&type=issues

@pro-sumer it is not against you, but it is simply wrong in the matter and we do not want to support such wrong ways, please understand that I have to close this thread now.

**Comment by pro-sumer** [comment]
Understood.

For anyone in the future seeing this ticket: disabling Cloudflare's "Rocket Loader" using a configuration rule solves the issue.

It might also be possible to adapt the CSP instead as explained [here](https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/), but I failed to do so (so far).

**Comment by return42** [comment]
> For anyone in the future seeing this ticket: disabling Cloudflare's "Rocket Loader" using a configuration rule solves the issue.

Just for reference / its a known issue: https://github.com/searxng/searxng/issues/1113#issuecomment-1101357319
