### ISSUE TITLE
Add French translation for infopage

### ISSUE THREAD

**Issue by jcarnat** [searxng/searxng#3738]
**Is your feature request related to a problem? Please describe.**
I have just realised the infopage has no French translation.

**Describe the solution you'd like**
I have translated those pages into French based on what I saw was done for other languages.
Unfortunately, I don't know enough GitHub to actually make a proper PR so I'm attaching the translated pages here.

**Describe alternatives you've considered**
n/a

**Additional context**
[searxng-infopage-fr.tar.gz](https://github.com/user-attachments/files/16626907/searxng-infopage-fr.tar.gz)

**Comment by return42** [comment]
> Unfortunately, I don't know enough GitHub to actually make a proper PR 

Don't worry, it's perfect this way:

> I'm attaching the translated pages here.

Thank you for providing the translation :+1: ... can you confirm that PR https://github.com/searxng/searxng/pull/3744 is OK for you, then I would merge the translation.

**Comment by jcarnat** [comment]
> > Unfortunately, I don't know enough GitHub to actually make a proper PR
> 
> Don't worry, it's perfect this way:
> 
> > I'm attaching the translated pages here.
> 
> Thank you for providing the translation 👍 ... can you confirm that PR #3744 is OK for you, then I would merge the translation.

I clicked the PR link and read the diffs. They look good to me :)

**Comment by return42** [comment]
> I clicked the PR link and read the diffs. They look good to me :)

Again, thanks for your contribution :+1: / its merged now.
