### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by mdosch** [searxng/searxng#374]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-869-e39a03cc

**How did you install SearXNG?**

https://searxng.github.io/searxng/admin/installation-searx.html
Installed on Debian Bullseye.

**What happened?**

Qwant show's an API error on every single search.

**How To Reproduce**

Perform a search with qwant or qwant images enabled.

**Expected behavior**

No error.

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:115`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by return42** [comment]
Strange, for me qwant works https://darmarit.org/searx/search?q=%21qwant%20paris&language=en (v1.0.0-870 what is the same version like yours)

Do you have any special language? I tested de, fr and en and several others ..
Or any special query?

**Comment by mdosch** [comment]
That's weird. I am using en and de as well. I'm in the Biergarten right now but maybe I can enable debug logging and have a closer look tomorrow. My instance is search.mdosch.de which I just installed today (used searx before).

**Comment by return42** [comment]
**edit** https://search.mdosch.de/search?q=%21qwant%20paris&categories=none&language=de

Could you file the debug log (`make run`) around of a query, eg. `!qwant paris`?  Do you have any special qwant settings, the default is ...
 https://github.com/searxng/searxng/blob/e39a03cc61e9792afb34084fb4d9973a61deecea/searx/settings.yml#L1043-L1051

**Comment by mdosch** [comment]
I don't have any special settings.
Can I tell `make run` to log to a file? It seems to mess up my terminal 
therefore it's pretty difficult to find something useful.

**Comment by dalf** [comment]
> Can I tell `make run` to log to a file?

Does `make run > log.txt 2>&1` work ?

---

Can you try `https://api.qwant.com/v3/search/web?q=q=test&count=10&offset=0&locale=en_gb` with the same IP than the instance?

Otherwise, can you apply this temporary patch?
```patch
diff --git a/searx/engines/qwant.py b/searx/engines/qwant.py
index 18e6a65d..6ee03afa 100644
--- a/searx/engines/qwant.py
+++ b/searx/engines/qwant.py
@@ -111,7 +111,8 @@ def response(resp):
 
     # check for an API error
     if search_results.get('status') != 'success':
-        msg = ",".join(data.get('message', ['unknown', ]))
+        msg = ",".join(data.get('message', ['status=', str(search_results.get('status'))]))
+        logger.debug('API error: %s', str(data))
         raise SearxEngineAPIException('API error::' + msg)
 
     # raise for other errors
```

* `/stats?engine=qwant` will contains the status
* the log message will contains the full response.

**Comment by return42** [comment]
You can start a debug session by `make run` .. then switch to your browser and do a query which causes the issue (e.g. `!qwant paris`) ... then look for lines logged from the `searx.network.qwant` logger .. C&P what you see ...

Since I do not have this quant issue, my log is very small ...

```
DEBUG   searx.search                  : actual_timeout=3.0 (default_timeout=3.0, ?timeout_limit=None, max_request_timeout=None)
DEBUG   searx.network.qwant           : HTTP Request: GET https://api.qwant.com/v3/search/web?q=q=paris&count=10&offset=0&locale=de_de "HTTP/2 200 OK" (application/json; charset=utf-8)
DEBUG   searx.webapp                  : http%3A//127.0.0.1%3A8888/search uses locale `de`
```

**Comment by mdosch** [comment]
I just wanted to debug this but now it is working without me changing 
anything. ^^

**Comment by return42** [comment]
Have an eye on, if the issue happens again, send a debug log and reopen this issue / thanks!
