### ISSUE TITLE
"No results" for Wikipedia search

### ISSUE THREAD

**Issue by pro-sumer** [searxng/searxng#3743]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.8.16+29056b9dd

**How did you install SearXNG?**
Docker, with "wp" as shortcut for Wikipedia:

```
  - name: wikipedia
    shortcut: wp
    engine: wikipedia
    display_type: ["infobox"]
    base_url: 'https://{language}.wikipedia.org/'
    categories: [general]
```

**What happened?**
* The search "Cooper test !wp" returns "Sorry! No results were found." in the main pane.
* Yet, there's info about the Cooper test in the info box on the right...
* And without "!wp" the first Google/DDG result is actually from Wikipedia...

**How To Reproduce**
Search `Cooper test !wp`

**Expected behavior**
See the Wikipedia entry for "Cooper test" on the main pane.

**Screenshots & Logs**
N/A

**Additional context**
N/A

**Comment by return42** [comment]
add `list` to the array `display_type` to get results in the results list  ..

https://github.com/searxng/searxng/blob/c0369ee48812451d40f331de80d388841a8bcf77/searx/settings.yml#L407-L413
