### ISSUE TITLE
LIMITER: 'missing config file: /etc/searxng/limiter.toml'

### ISSUE THREAD

**Issue by meaz** [searxng/searxng#3754]
```
git log -1
``` 
gives:
```
git log -1
commit 2033f30c8df9e6af23876345785ec28ba982d5e5 (HEAD -> master, origin/master, origin/HEAD)
Author: Dennis ten Hoove <dennistenhoove@protonmail.com>
Date:   Fri Aug 16 05:14:25 2024 +0200

    [docs] improve Hostname plugin documentation
```

**How did you install SearXNG?**
I installed SearXNG using the official wiki

**What happened?**
I use limiter. So I set `limiter: true` in settings. In logs, I see `WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml`

Should I manually create the `limiter.toml` in `/etc/searxng/` using parameters like explained here https://docs.searxng.org/admin/searx.limiter.html ? Or should that file be automatically created?

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Comment by return42** [comment]
You have to create one --> https://docs.searxng.org/admin/searx.limiter.html#configure-limiter

If your instance is public, you should activate `link_token = true` as described.

Next time please do not open a "BUG" issue for a question / we have 

- https://github.com/searxng/searxng/discussions
- [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
