### ISSUE TITLE
Page titles in search results do not show text in angle brackets

### ISSUE THREAD

**Issue by DokterKaj** [searxng/searxng#3767]
**What happened?**
When browsing search results, if a page title has opening and closing angle brackets (e.g. `C Library - <string.h>`), the text in between will not show up (`C Library -`).

**How To Reproduce**
Search up something that would have angle brackets around it (e.g. `string.h`).

**Expected behavior**
Page titles are shown in full (e.g. `C Library - <string.h>`).

**Comment by glanham-jr** [comment]
Good catch. Provided some screenshots of what this looks like for reference.

![image](https://github.com/user-attachments/assets/59b051e6-0dc5-472e-a872-2a755066fb85)

![image](https://github.com/user-attachments/assets/48617999-ea45-4035-8ba1-67ce5f1c731e)
