### ISSUE TITLE
Bug: alexandria engine (504 Gateway Time-out)

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3786]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.28+..

**How did you install SearXNG?**

    make run

**What happened?**

The origin alexandria.org is broken / https://www.alexandria.org/?c=&r=&a=0&q=foo returns "504 Gateway Time-out"

**Additional context**

If it isn't a temporary issue, alexandria.org engine should be dropped:

https://github.com/searxng/searxng/blob/cbd86473aadb31c0a12694f56a94c41ab2581142/searx/settings.yml#L1881-L1898

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 100
  * Parameters: `(None, None, 'api.alexandria.org')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by virtadpt** [comment]
Confirmed.  This broke both of my instances uintil I dumped the logs.  Disabling the engine got them running again but that's a workaround.
