### ISSUE TITLE
Bug: hoogle engine (502 Bad Gateway)

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3787]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.28+..

**How did you install SearXNG?**

    make run

**What happened?**

The origin hoogle.haskell.org is broken / 'https://hoogle.haskell.org/?hoogle=html'
 returns "502 Gateway"

**Additional context**

If it isn't a temporary issue, engine should be dropped:

https://github.com/searxng/searxng/blob/cbd86473aadb31c0a12694f56a94c41ab2581142/searx/settings.yml#L992-L1008
**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('502', 'Bad Gateway', 'hoogle.haskell.org')`
  * File name: `searx/engines/xpath.py:251`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by Bnyro** [comment]
Probably a temporary outage, seems to work again now.
