### ISSUE TITLE
Yahoo: HTML tags are included in result titles

### ISSUE THREAD

**Issue by dsmith2001** [searxng/searxng#3790]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.8.31+5e576b223

**How did you install SearXNG?**
searxng-docker

**What happened?**
HTML tags are included in result titles when Yahoo is enabled.

**How To Reproduce**
Enable Yahoo engine, or use **!yh** bang.

**Expected behavior**
The HTML tags should be excluded.

**Screenshots & Logs**
![image](https://github.com/user-attachments/assets/2a6b9fff-eb2a-49b4-8ab3-ac59ea916d82)

**Additional context**
N/A

**Comment by return42** [comment]
Seems related to

- https://github.com/searxng/searxng/pull/3770

but it is strange, I can't reproduce the issue .. do you see this issue in other engines also?

![grafik](https://github.com/user-attachments/assets/0bf2f3c2-62f4-4b57-aadf-53b85d911c0f)

**Comment by dsmith2001** [comment]
Nope, only with Yahoo. My instance uses a US IP, if that changes anything.

**Comment by return42** [comment]
> Nope, only with Yahoo. 

:+1: 

> My instance uses a US IP, if that changes anything.

Yeah, seems related .. I send PR:

- https://github.com/searxng/searxng/pull/3791

can you please check it works from your US IP / thanks :+1:

**Comment by dsmith2001** [comment]
Still an issue with the latest commits:
![image](https://github.com/user-attachments/assets/29815f56-6b75-49c4-a41b-67afef807d09)

**Comment by Bnyro** [comment]
I can't reproduce HTML tags from my German IPs either.

**Comment by dsmith2001** [comment]
Sorry for the delay, I can confirm the issue is resolved with your PR @return42
