### ISSUE TITLE
Impossible to add to Firefox Search Bar

### ISSUE THREAD

**Issue by elbubar** [searxng/searxng#3795]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.9.1+b09aa7e36

**How did you install SearXNG?**
https://apps.yunohost.org/app/searx

**What happened?**
Click on the icon of Firefox to add a search engine results with this message : 

![image](https://github.com/user-attachments/assets/6cec5823-7db1-4995-a088-c69653136b41)

**How To Reproduce**
Clic on the Firefox button : 

![image](https://github.com/user-attachments/assets/8312e011-7fa0-49e3-81f3-046fcbedfab3)

**Expected behavior**
Should add SearxNG to the list of available search engines

**Screenshots & Logs**
Already provided

**Additional context**
N/A

**Comment by return42** [comment]
> **How did you install SearXNG?** https://apps.yunohost.org/app/searx

Are you sure? You have linked to the no longer maintained searx, but are referring to SearXNG.

OpenSearch in SearXNG (& FireFox) do work / if you have issues on yunohost please open an issue there / may its related to the required login?

**Comment by elbubar** [comment]
Sorry, https://apps.yunohost.org/app/searxng 

I have no login interface... and still : Firefox could not install the search engine from: https://searx.ravidat.net/searxng/opensearch.xml?method=POST&autocomplete=

Should I adress that on YNH ?

**Comment by return42** [comment]
> Should I adress that on YNH ?

Yes, but first read the existing issue on YNH:

- https://github.com/YunoHost-Apps/searxng_ynh/issues/91 ..

---

> I have no login interface... and still : Firefox could not install the search engine from: https://searx.ravidat.net/searxng/opensearch.xml?method=POST&autocomplete=

You have one .. when  I click on the link a login dialog is shown to me.

**Comment by elbubar** [comment]
@return42, thanks you so much. I wouldn't have expected you to search for me. This is very appreciated, have a great day !
