### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by mitexleo** [searxng/searxng#3806]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.30+e86c96974

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 30
  * Parameters: `('unknown (27)',)`
  * File name: `searx/engines/qwant.py:191`
  * Function: `parse_web_api`
  * Code: `raise SearxEngineAPIException(f"{msg} ({error_code})")`

Error
  * Error: httpx.TimeoutException
  * Percentage: 5
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> Error: searx.exceptions.SearxEngineAPIException

This is a CAPTCHA that is currently not recognized.  I have fixed the CAPTCHA detection:

- https://github.com/searxng/searxng/pull/3828
