### ISSUE TITLE
KeyError in bing images

### ISSUE THREAD

**Issue by 0xhtml** [searxng/searxng#3807]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
153a28ccd

**How did you install SearXNG?**
manual

**What happened?**
bing images fails due to a KeyError:

    Traceback (most recent call last):
        …
        File "searx/engines/bing_images.py", line 102, in response
            'content': metadata['desc'],
                       ~~~~~~~~^^^^^^^^
    KeyError: 'desc'

**How To Reproduce**
e.g. https://searx.aleteoryx.me/search?q=%21bing_images%20alpha%20beta%20pruning&language=auto&time_range=&safesearch=0&categories=none

**Expected behavior**
parsing should work

**Additional context**
could be a simple problem of results not having a description or some bigger breaking change of the way bing images provides results

**Comment by glanham-jr** [comment]
Sadly [Bing is fraught with difficult bugs](https://github.com/searxng/searxng/labels/bing-engine). However, this seems like something that is quite avoidable, and luckily reproducible (thank you for providing steps to reproduce). I can try to see if I can patch this.

@return42 you can assign me to this one.

**Comment by glanham-jr** [comment]
Problematic code is located here:

https://github.com/searxng/searxng/blob/6be56aee11e5b2bd2a95479578349a561ab7ff2e/searx/engines/bing_images.py#L102

Tested `!bing_images alpha beta pruning` locally. Most of the results were fine. Below is print of the `metadata` in that loop.

```
{'sid': '', 'cturl': '', 'cid': 'iO4u9NwW', 'purl': 'https://universitymcqs.com/alpha-beta-pruning/', 'murl': 'https://static.javatpoint.com/tut
orial/ai/images/alpha-beta-pruning-step3.png', 'turl': 'https://tse1.mm.bing.net/th?id=OIP.iO4u9NwWsuYd5wAdS8YyuAHaGn&pid=15.1', 'md5': '88ee2ef
4dc16b2e61de7001d4bc632b8', 'shkey': 'i9dBfAhgwgxZZSsGJCOhHZAgjbc6zgnwjhITjOuVK74=', 't': '\ue000Alpha-Beta Pruning\ue001 - UniversityMCQS', 'mi
d': '5DA4C8CB9E854EA6D23CE9AD2C215D20F2DF4F02', 'desc': ''}
```

But there is one failing image with the following `metadata`. It doesn't have a `desc`. However, is still has the image source (`murl`) so I think its fine enough to return. If it isn't enough information, I would assume that the caller of the engine would handle that.

```
{'sid': '', 'cturl': '', 'cid': '', 'purl': '', 'murl': 'https://www.researchgate.net/profile/Sharjeel-Akram/publication/357974330/figure/fig2/A
S:1114383195348997@1642701066718/Alpha-Beta-Pruning-example.ppm', 'turl': '', 'md5': '', 'shkey': '3siujEXqVBumJN4EdfZ08f9gArEneZ7feBTqNjkdXJc='
}
```

I tested locally in just returning the key value or none for `desc` and it seems to solve the issue. I'll open a PR with this fix very shortly.
