### ISSUE TITLE
Fix the ability to see and copy the links in the Download requests part of the Simple theme.

### ISSUE THREAD

**Issue by virtadpt** [searxng/searxng#3808]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Git commit ba257da33.

**How did you install SearXNG?**
Bare metal.  Cloned repo, created a venv in searxng/, `pip install -t requirements.txt`.  Running under uwsgi.

**What happened?**
The Simple theme does not make it easy to get the URL to get search results as CSV, JSON, or RSS files.  If you hover over one of those buttons it lights up but the URL is not shown by the browser.  Right-clicking on one of those buttons does not bring up a "Copy link" option.  The buttons can be clicked on; the CSV file is offered for download, the JSON document is served to the browser (but the URL it came from is not), the RSS feed is served to the browser but the URL to get it from is not (only the search URL).

Searx (the original) did not do this.  It offered the capability to see and copy the URL if desired, vis a vis `https://searxng.example.com/?q=california%20wildfires%202024&categories=news&time_range=day&format=rss` or `https://searxng.example.com/?q=reported%20mpox%cases%20united%20states&categories=social+media&time_range=month&format=json`

If one has the patience to do a View Source for a search results page and scan through the raw HTML some of this information can be teased out.  But it's not good user experience.

Browsers uses: Google Chrome, Firefox, Librewolf.

**How To Reproduce**
Do a search for some search term on a SearxNG instance: `https://searxng.example.com/?q=virtual%20adepts`

On the search page, click "Download results" to expand the block.

Click on one of the buttons (CSS, JSON, RSS).  You should but do not see the URL for that version of the search results returned.

**Expected behavior**
You should see a URL for that version of the search results returned in the "this is the URL for the link you are hovering your cursor over" bit of your web browser, which should be of the form `https://searxng.example.com/?q=virtual%20adepts&format=rss`

**Additional context**
This is just a theme problem, but it's the default theme so that's the one that most users are going to see.

**Comment by glanham-jr** [comment]
> On the search page, click "Download results" to expand the block.

Hmmmm, maybe I'm missing something obvious, but I don't see this after a search. Could you add a screenshot?

**Comment by glanham-jr** [comment]
For reference this is what I see - I can copy the URL with the button.

![image](https://github.com/user-attachments/assets/6f3827bd-d09e-4e7d-9902-6d7e7f4c6b98)

**Comment by vojkovic** [comment]
> > On the search page, click "Download results" to expand the block.
> 
> Hmmmm, maybe I'm missing something obvious, but I don't see this after a search. Could you add a screenshot?

Not the guy, but try adding more formats under `formats:`. Pretty sure the Download button only shows when json, rss or csv are enabled.

**Comment by virtadpt** [comment]
@vojkovic They are enabled.  I use the JSON and RSS search feeds pretty extensively, mostly because I set them up when I used regular Searx and those mechanisms haven't changed.

This image is when I clicked into the Search URL box and tried to drag right to view later parts of the URL.  In other words, I wasn't able to, that's all I get:
![Screenshot 2024-10-07 at 9 43 04 AM](https://github.com/user-attachments/assets/6e9a8c0e-e013-4196-b60c-55b90e698bc9)

Before clicking Download results -> json:
![Screenshot 2024-10-07 at 9 44 35 AM](https://github.com/user-attachments/assets/ceac1c03-a3e7-4e0d-9291-41a8a727a689)

After (note the lack of a useful URL that shows how to get those results as JSON under other contexts):
![14 AM](https://github.com/user-attachments/assets/3766e712-d965-4ef4-b0af-01fdedf4a784)

**Comment by glanham-jr** [comment]
Found the source of the confusion - code is in the [apis.html](https://github.com/searxng/searxng/blob/master/searx/templates/simple/elements/apis.html) file. Its definitely not a link, its currently formatted as a bunch of `inputs`. For POST requests, this is definitely by design in order to avoid having the parameters as part of the URL . However, if a user configures the settings for GET, I could image this being formatting as a link as OP wanted.

@virtadpt - would you change your preferences to use GET instead of POST to get a well formatted URL?

**Comment by return42** [comment]
I think the answer is already given by https://github.com/searxng/searxng/issues/3808#issuecomment-2398157887

@virtadpt I'm going to close the issue / if it does not solve your issue, ask to reopen.

**Comment by virtadpt** [comment]
@glanham-jr I'm not opposed to doing so.

**Comment by glanham-jr** [comment]
There is some dev work to conditionally change the input to an anchor tag. It's a small quality of life improvement, as you can still just click the button and copy/paste the URL. It's only slightly tricky as there is a for-each loop that generates inputs, so we'd need a custom "url-for" method to flatten that array.
