### ISSUE TITLE
Add a link in the instance footer to compare the git revision to the latest

### ISSUE THREAD

**Issue by Ember-ruby** [searxng/searxng#3809]
**Is your feature request related to a problem? Please describe.**

To easily check changes between your searxng and the latest 

**Describe the solution you'd like**

As well as the link to the source code, a link to a compare, like `https://github.com/searxng/searxng/compare/f1c05e7c1...master`

**Describe alternatives you've considered**

This would be an alternative to an update checker or the like

**Additional context**

browsing a commit log can get tedious, narrowing it down to just commits past a certain one would make it more pleasant to upgrade

**Comment by return42** [comment]
> As well as the link to the source code, a link to a compare, like `https://github.com/searxng/searxng/compare/f1c05e7c1...master`

HINT: not all forks and branches of SearXNG are hosted on github and not all do a rebase on SearXNG's master ..

> Add a link in the instance footer to compare the git revision to the latest

The intention makes sense ... but as there is unfortunately no universal solution for this task, we are not planning to implement this function / sorry :disappointed:

**Comment by Ember-ruby** [comment]
fair enough
