### ISSUE TITLE
GitLab engine mixes up titles, URLs and produces invalid results

### ISSUE THREAD

**Issue by sclu1034** [searxng/searxng#3810]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Latest Docker image: `2024.9.6+153a28ccd`

**How did you install SearXNG?**
Official Docker image (https://hub.docker.com/r/searxng/searxng)

**What happened?**
When searching with the default Gitlab engine, the titles and URLs don't match up. Additionally, some results shouldn't be showing up at all.

For most or all search results, the title doesn't match the URL of the same result, but rather belongs to some other result. There is no clear pattern, as sometimes it's off by one, sometimes it's a title that belongs to a result all the way down the page.

Additionally, some results don't seem to match the query, mostly users or groups.

Example: `!gitlab searx` (see screenshot)

The group `gugal` (https://gitlab.com/groups/gugal) owns a repository that matches the query `searx`. That's technically an indirect match, but it should rather return that repository, rather than the group. And it should certainly rank the repo much higher than the group/

Additionally, a result for https://gitlab.com/uhidontkno doesn't match at all. Nowhere on that page do I see a reference to the search term.

Looking at the raw API results from Gitlab (`curl -s 'https://gitlab.com/api/v4/projects?search=searx&page=1'`), those groups and users don't even show up in the 4 pages of results.

**How To Reproduce**
- Search for `!gitlab searx`
- I first noticed it on my own instance, but the same happens at e.g. https://metasearx.com/?q=%21gitlab%20searx&categories=none&language=en or https://searx.bndkt.io/search?q=%21gitlab%20searx&language=all&time_range=&safesearch=0&categories=none

**Expected behavior**

- Title and URL should match up correctly
- Users and groups that have no direct (name, description, etc.) match with the query, and instead only match indirectly through owning a repository should not be ranked as high.

**Screenshots & Logs**
![image](https://github.com/user-attachments/assets/bf8c1f5c-3b03-439a-a821-e36c9cfa8dcd)

**Comment by Bnyro** [comment]
The issue is somewhere in the `do_query` function here: https://github.com/searxng/searxng/blob/master/searx/engines/json_engine.py#L70.

Anyways, I think it makes more sense to implement a dedicated Python module for GitLab, I'll create a PR soon.

**Comment by sclu1034** [comment]
It's not in `do_query`, it's the `zip` further below.

**Comment by Bnyro** [comment]
> It's not in `do_query`, it's the `zip` further below.
>
It's kind of both. The `do_query` function returns results it shouldn't and thus the `zip` function doesn't behave as expected, due to the fact that some calls of `do_query` have more than one result, e.g. if the api provides a `namespace` dictionary that contains a `web_url` field, it will be part of the returned data,
