### ISSUE TITLE
Startpage searches return "no results were found"

### ISSUE THREAD

**Issue by nikolasdmtr** [searxng/searxng#3811]
-  2024.9.6+153a28ccd
- Installed using Docker
- When Startpage is selected as the engine, searches return a "no results were found"

![20240910_13h59m52s_grim](https://github.com/user-attachments/assets/de925815-c43a-425f-b9e4-2ff7d1bcefbf)

**Comment by nikolasdmtr** [comment]
Right now I am in Argentina.

**Comment by return42** [comment]
We can't reproduce the issue .. going to close / for those of you coming around and having the same issue (Argentina or non-European country?); please give additional information and ask to reopen this issue / thanks :+1:
