### ISSUE TITLE
[Cloudflare]  Pressing X does not clear the contents of the search bar

### ISSUE THREAD

**Issue by theAlevan** [searxng/searxng#3817]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.9.12+9e2bfe14d

**How did you install SearXNG?**
Using searxng-docker

**What happened?**
Pressing the X button on the right side of the search bar does not delete the current content of the search bar.

**How To Reproduce**
Write something in the search bar, the press the X on the right side.

**Expected behavior**
Pressing X on the right side of the search bar deletes the current content of the search bar.

**Screenshots & Logs**

![image](https://github.com/user-attachments/assets/91050e79-f7f2-4b95-9889-631a49e2b7b7)

**Additional context**
It happens on both Windows (tried in Google Chrome and Microsoft Edge), iOS (tried in Safari) and Android (tried in Google Chrome and Microsoft Edge)

**Comment by return42** [comment]
Can you reproduce the issue on https://darmarit.org/searx/search?q=foo ?

**Comment by theAlevan** [comment]
> Can you reproduce the issue on https://darmarit.org/searx/search?q=foo ?

On the mentioned server it works perfectly.

**Comment by return42** [comment]
> On the mentioned server it works perfectly.

Then there is an issue with your SearXNG instance .. is the instance public, do you like to post the URL here?

**Comment by Bnyro** [comment]
Have you tried clear clearing your browser's caches?

**Comment by theAlevan** [comment]
> > On the mentioned server it works perfectly.
> 
> Then there is an issue with your SearXNG instance .. is the instance public, do you like to post the URL here?

I made a public instance available on this url:
_removed_


> Have you tried clear clearing your browser's caches?

Even reinstalled Chrome before trying other browsers or platforms.

Edit:
It happens only on the page where there are already results:

![image](https://github.com/user-attachments/assets/6f8de578-f2f2-4535-94c6-1634022fdaf5)

Not on the default page, that opens when Searxng is loaded.

**Comment by Bnyro** [comment]
> Even reinstalled Chrome before trying other browsers or platforms.
>
Reinstalling does not necessarily clear the cache :)

**Comment by return42** [comment]
Don't use Cloudflare! 

### Cloudflare can read everything (because they MITM your https connection) .. which contrasts with any efforts to preserve privacy.

duplicate: 

- https://github.com/searxng/searxng/issues/3730
- https://github.com/searxng/searxng/issues/1113#issuecomment-1101357319

**Comment by theAlevan** [comment]
Thank you for your help. This is the first time in years since I began using Cloudflare, that something I hosted had trouble with cloudflare.

Disabling Rocket Loader resolved the issue.

**Comment by return42** [comment]
> Disabling Rocket Loader resolved the issue.

but not the privacy issue, which counts more!
