### ISSUE TITLE
Bug: google engine with specified "language: it_IT"

### ISSUE THREAD

**Issue by paolobasso99** [searxng/searxng#384]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-885-feb2d4dd

**How did you install SearXNG?**

I used searxng-docker.

**What happened?**

I tried to set up the Google engine with `language: it_IT` but it crashes.
**How To Reproduce**

Add this engine:
```
-  name: google italian
   engine: google
   shortcut: goit
   language: it_IT
   use_mobile_ui: false
```
and try to perform a search.

**Expected behavior**

Results from the google engine with a specified language.

**Additional context**
I followed the [guide in the wiki](https://searxng.github.io/searxng/user/search_syntax.html#multilingual-search) to add multilingual search to the letter but it does not work.

**Technical report**

Error
  * Error: AttributeError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/google.py:232`
  * Function: `get_lang_info`
  * Code: `ret_val['params']['hl'] = lang_list.get(lang_country, language)`

**Comment by paolobasso99** [comment]
I have also tried `it-IT`, `it` and `italian` but none of these works.

**Comment by return42** [comment]
You can fix the issue by:

    make data.languages

Or you approve https://github.com/searxng/searxng/pull/386 ...

**Comment by return42** [comment]
@paolobasso99 the issue reported is fixed, update your instance and just uncomment ..

https://github.com/searxng/searxng/blob/7246d62770a00af1583d1b977e6fad1f09073721/searx/settings.yml#L604-L608
