### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by mrbooshehri** [searxng/searxng#387]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:98`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:93`
  * Function: `response`
  * Code: `get(url_ping, headers=headers_ping)`

**Comment by return42** [comment]
Not very helpful to post a form without any informations filed in .. what exactly is your issue, how (or where) can we reproduce it?

**Comment by dalf** [comment]
I see:
* timeout: the administrator can fix the issue by increasing the timeout value in settings.yml
* access denied exception: no so much be can done, except using a VPN and / or proxy.

All percentage are rounded to 0 (between 0 and 4% of the total number requests).

Without more information, I close this issue.
