### ISSUE TITLE
Update variable-rgx in .pylintrc file to allow longer method names for unit tests

### ISSUE THREAD

**Issue by glanham-jr** [searxng/searxng#3879]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

 - master branch

**How did you install SearXNG?**

 - n/a, testing purposes only 

**How To Reproduce**

Create any long method name (more than 30 chars), and it raises errors with pylint.

For example `test_init_no_query_str_raises_exception` raises an exception.

https://github.com/searxng/searxng/blob/master/.pylintrc#L164-L165

**Expected behavior**

For unit tests, I think we should relax the variable name lengths. Descriptive unit test names are more important than trying to squeeze in under a certain number of characters. Or at least this is my opinion. I've ran into this issue innumerable times when writing unit tests, and have to think of a way to shorten it and still make sense.

I'd ideally update this **just** for unit tests to maybe be 40 characters, but if I update the `.pylintrc` file directly, I'll update the pylint for the entire codebase. Not sure what the best workaround is, or if its OK to bump for the entire codebase. Wanted to see opinions first on this before attempting anything.

**Screenshots & Logs**

![image](https://github.com/user-attachments/assets/d6a30df5-8624-4c17-9630-44250759d455)

**Additional context**

- n/a

**Comment by return42** [comment]
> I'd ideally update this **just** for unit tests to maybe be 40 characters, but if I update the `.pylintrc` file directly, I'll update the pylint for the entire codebase. Not sure what the best workaround is, or if its OK to bump for the entire codebase. Wanted to see opinions first on this before attempting anything.

Personally I think (very) long function names do not improve the readability  .. and if we need long names here or there, we can add ``# pylint:disable=...`` comments to prevent pylint from reporting errors / [see "Messages control"](https://pylint.readthedocs.io/en/latest/user_guide/messages/message_control.html)
