### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by mrbooshehri** [searxng/searxng#388]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'alternativeto.net')`
  * File name: `searx/search/processors/online.py:106`
  * Function: `_send_http_request`
  * Code: `count_error(self.engine_name,`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'www.google.com')`
  * File name: `searx/search/processors/online.py:106`
  * Function: `_send_http_request`
  * Code: `count_error(self.engine_name,`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'www.google.com')`
  * File name: `searx/search/processors/online.py:106`
  * Function: `_send_http_request`
  * Code: `count_error(self.engine_name,`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:98`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'search.brave.com')`
  * File name: `searx/search/processors/online.py:106`
  * Function: `_send_http_request`
  * Code: `count_error(self.engine_name,`

**Comment by return42** [comment]
Not very helpful to post a form without any informations filed in .. what exactly is your issue, how (or where) can we reproduce it?

**Comment by mrbooshehri** [comment]
You are right, sorry about that. It happens when I search for a term in search bar - randomly for duckduckgo but every time for brave. Honestly I don't know what kind of information are useful, so please tell  me what I should  give you
[Image](https://ibb.co/1b4S8jN)

**Comment by unixfox** [comment]
Both duckduckgo and brave are blocking the IPs addresses of searx.be

It's an issue that searxng can't really solve, unfortunately.

**Comment by return42** [comment]
>  Honestly I don't know what kind of information are useful, so please tell me what I should give you

What the form asks for ..

![grafik](https://user-images.githubusercontent.com/554536/136811716-cc736451-e34c-4cb8-aeea-af61a82e5256.png)

Edit your initial https://github.com/searxng/searxng/issues/388#issue-1017982489

**Comment by return42** [comment]
I close in lack of feedback

**Comment by unixfox** [comment]
You can close it yes.
