### ISSUE TITLE
Gibiru search engine.

### ISSUE THREAD

**Issue by patyarishimai** [searxng/searxng#3891]
Hello SearXNG community. I have been using this project for years and I am truly happy on how it has evolved so far. With the recent addition of RightDao I was thinking Gibiru would be a nice addition too.

**Working URL to the engine**
https://gibiru.com/

**Why do you want to add this engine?**
The engine has a function called "Censored Results" which gives uncensored results. I believe it could give more organic results to SearXNG.

**Features of this engine**
The engine itself has privacy features, nevertheless the main reason for me requesting it is because it could give more diverse results if combined with the already existing engines.

**How can SearXNG fetch the information from this engine?**

**Applicable category of this engine**
General

**Additional context**

**Comment by return42** [comment]
> The engine itself has privacy features, nevertheless the main reason for me requesting it is because it could give more diverse results if combined with the already existing engines.

Sure they are not biased? .. They promise "privacy" but loading google JS and CSS in their search result page:

![image](https://github.com/user-attachments/assets/f583688d-99f6-44bd-ae48-ae2d49153373)

Do you have any link that gives us information about the search (index) and the company ..

Seems the search engine has none language or time range filter .. which makes it less suitable for use in SearXNG.

**Comment by Bnyro** [comment]
![](https://github.com/user-attachments/assets/1d66c9fc-55a4-4fb2-8a17-3001d645c00c)

They are just fetching the results directly from Google (without even proxying it), that's by far the most privacy disrespecting search engine I've ever seen.

**Comment by patyarishimai** [comment]
I'm not a tech savvy guy, if it indeed doesn't even use a proxy then there's no reason to add it.
