### ISSUE TITLE
oscar's logicodev-dark (less) compiled into logicodev.css and vice versa?

### ISSUE THREAD

**Issue by return42** [searxng/searxng#39]
I had a look at oscar's `gruntfile.js` and was wondering why _dark_ theme (`logicodev-dark/oscar.less`)  is compiled into _light_ CSS (`css/logicodev.css`) and vice versa .. does anyone know the reason for .. or did I missed something? 

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/static/themes/oscar/gruntfile.js#L99-L100

**Comment by dalf** [comment]
There is one theme: oscar
There are 3 styles:
* logicodev
* logicodev-dark
* pointhi

The 3 styles:
* are compiled into the same directory, the one dedicated for the oscar theme
* share the same Jinja2 templates.

theme and style are two different preferences:

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/preferences.py#L375-L379

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/preferences.py#L395-L398

Also:
https://github.com/searxng/searxng/blob/3755cf2eba17a98d8e78e0a286aa69a27e2041e6/searx/templates/oscar/base.html#L14-L18

**Comment by return42** [comment]
Thanks for the detailed explanation! ...

Sorry, if my question was unclear: I was asking about the grunt-file, I guess there is a bug in the 'development' compilation:

Here _dark_ goes into `css/logicodev.css`

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/static/themes/oscar/gruntfile.js#L99

Here _light_ goes into `css/logicodev-dark.css`

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/static/themes/oscar/gruntfile.js#L100

In the 'production' compilation I can see what I would expect also for the 'development'

https://github.com/searxng/searxng/blob/fe3831db1aa73ebda6eb12fa3a321002c176ccc1/searx/static/themes/oscar/gruntfile.js#L118-L119

**Comment by dalf** [comment]
Ah, sorry.

Good catch, yes, it should be
```js
 "css/logicodev.min.css": "src/less/logicodev/oscar.less", 
 "css/logicodev-dark.min.css": "src/less/logicodev-dark/oscar.less" 
```
in both cases

**Comment by return42** [comment]
OK, thanks for the feedback .. I will patch it  (ATM I already prepare a patch for another reason).
