### ISSUE TITLE
Bug: bing videos engine

### ISSUE THREAD

**Issue by tian-IRT** [searxng/searxng#3907]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.9.29+f07ab6deb

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 100
  * Parameters: `('200', 'OK', 'cn.bing.com')`
  * File name: `searx/search/processors/online.py:125`
  * Function: `_send_http_request`
  * Code: `count_error(`

**Comment by return42** [comment]
I cant reproduce the issue reported above (redirects), but I have confusing results.  I started an instance by `make run` and send the following query `!bing_videos foo :en`

- first page "no results" --> http://127.0.0.1:8888/search?q=%21bing_videos+foo+%3Aen&pageno=1
- second page has results in the returned link list --> http://127.0.0.1:8888/search?q=%21bing_videos+foo+%3Aen&pageno=2

I think both issues are more or less related to the parameters how the origin search service (bing) is called.

- [information on the parameters](https://github.com/searxng/searxng/pull/3416#issuecomment-2344841069)
- https://github.com/searxng/searxng/issues/3264

duplicate / (at least strong related):

- https://github.com/searxng/searxng/issues/3402
- https://github.com/searxng/searxng/issues/2641#issuecomment-1742526819
