### ISSUE TITLE
searxng-2024.10.12+7e8b330b3 / stretching pics in "pic search"

### ISSUE THREAD

**Issue by un99known99** [searxng/searxng#3915]
setup is NOT "show pics / results in the middle", but:

![grafik](https://github.com/user-attachments/assets/6665a5c1-3389-4cf5-acbb-52d0c21ea417)

![grafik](https://github.com/user-attachments/assets/0da7434b-1606-4825-95b9-70a897d47831)

before that version it was ok

also pics are not opening in seperate tab - despite setup so

**Comment by return42** [comment]
> before that version it was ok

Argh .. I guess the issue is related to the merge of https://github.com/searxng/searxng/pull/3895

**Comment by return42** [comment]
> also pics are not opening in seperate tab - despite setup so

If you set ..

![grafik](https://github.com/user-attachments/assets/375ad90d-4b25-4266-91a1-ae47dc25e2e6)

and click on the image in the *image-details*, the link to the origin URL of the image is opened in a new tab.

**Comment by return42** [comment]
To fix the issue "stretching pics" I send PR, asking for your review / thanks a lot :+1: 

- https://github.com/searxng/searxng/pull/3921

**Comment by un99known99** [comment]
![grafik](https://github.com/user-attachments/assets/de03f9e2-1098-4b82-8682-441e64387fee)


![grafik](https://github.com/user-attachments/assets/7448b4da-9b4a-4ce1-a2ba-52e1ba78599d)

**Comment by un99known99** [comment]
> > also pics are not opening in seperate tab - despite setup so
> 
> If you set ..
> 
> ![grafik](https://private-user-images.githubusercontent.com/554536/376219694-375ad90d-4b25-4266-91a1-ae47dc25e2e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTY0OTEsIm5iZiI6MTcyODkxNjE5MSwicGF0aCI6Ii81NTQ1MzYvMzc2MjE5Njk0LTM3NWFkOTBkLTRiMjUtNDI2Ni05MWExLWFlNDdkYzI1ZTJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNDI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjI2NWU2NjkyYmQ5Yjk0Y2RlNjgyMjcyMWJlZjdkODM3MDNhZWI0NDJhNTg2ZjI3YTkwMzUyZGQ2NmM2ZDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UVoDME6IZkolu_UkJ1RBZwwcR4zXw4I_xRaN55l6UBw)
> 
> and click on the image in the _image-details_, the link to the origin URL of the image is opened in a new tab.

so, no new tab, please see above @return42 
it is opening right aside

**Comment by return42** [comment]
> it is opening right aside

Yes, this is the "image-details" I mentioned above:

> and click on the image in the image-details, the link to the origin URL of the image is opened in a new tab.

**Comment by un99known99** [comment]
> > it is opening right aside
> 
> Yes, this is the "image-details" I mentioned above:
> 
> > and click on the image in the image-details, the link to the origin URL of the image is opened in a new tab.

@return42 
but same behaviour if I unmark the "open in new tab"
slider makes no difference
saw that the strected picture issue is fixed, when are you planning to release it?

**Comment by return42** [comment]
> but same behaviour if I unmark the "open in new tab"

with ..

![grafik](https://github.com/user-attachments/assets/93a20eda-65e0-44d0-ac87-d4ea532eb448)

and clicking on the image ..

![grafik](https://github.com/user-attachments/assets/1305c616-2331-43a3-85d6-f64ebd0ac577)

.. the image is opened in a new tab .. if this is not the case in your browser, check your browser settings.

> saw that the strected picture issue is fixed, when are you planning to release it?

Its merged .. if you a docker user, please take note of:

- https://github.com/searxng/searxng/issues/3887
