### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by dhanushofc** [searxng/searxng#3919]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.10.4+3e747d049

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 100
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/qwant.py:196`
  * Function: `parse_web_api`
  * Code: `raise SearxEngineCaptchaException()`

**Comment by Bnyro** [comment]
https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619
