### ISSUE TITLE
duckduckgo blocked by CAPTCHA

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3927]
Not often, but at some point ddg might block the SearXNG requests by a CAPTCHA,

The CAPTCHA goes away when opening duckduckgo.com in a browser / from the SearXNG IP .. as described here: [Answer CAPTCHA from server’s IP](https://docs.searxng.org/admin/answer-captcha.html#answer-captcha-from-server-s-ip)

I have created this ticket with the intention that we (I) re-engineer the ddg engine ... especially the determination of the [vqd value](https://docs.searxng.org/dev/engines/online/duckduckgo.html#searx.engines.duckduckgo.get_vqd) should be paid attention to again, this should actually avoid CAPTCHAs

----

May we consider to switch to https://html.duckduckgo.com/html/ the URL where ddg routes your browser, when JS is disabled.

https://github.com/searxng/searxng/blob/058a072404a4e9ec4c5a0a957fe06ce66e652938/searx/engines/duckduckgo.py#L56-L56

**Comment by MansurEsm** [comment]
Hi @return42,

I'm still experiencing DuckDuckGo CAPTCHA issues despite running **searxng/searxng:2025.9.1-b93cc2f** which should contain the fix from PR #3955. It's happening occasionally.

The error from log is:
ERROR searx.engines.duckduckgo: CAPTCHA searx.exceptions.SearxEngineCaptchaException: CAPTCHA (de-de), suspended_time=0 DEBUG searx.network.duckduckgo: HTTP Request: POST [https://html.duckduckgo.com/html/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) "HTTP/2 202 Accepted"

I run it as a pod in-cluster (one replica).

My config:
'''
search:
   [...]
   formats:
        - html
        - json
 [....]
 - name: duckduckgo
        engine: duckduckgo
        shortcut: ddg
        disabled: false
        weight: 0.8
        categories: [general]
        timeout: 5.0
'''

If you have further questions to assist you in solving, then let me know.

**Comment by return42** [comment]
@MansurEsm this issue is obsolete (from oct. 2024) .. please follow https://github.com/searxng/searxng/issues/4824

**Comment by odellus** [comment]
This needs revisiting. It's an arms race.

**Comment by return42** [comment]
I lock this already closed issue from 2024, please follow: https://github.com/searxng/searxng/issues/6596
