### ISSUE TITLE
Images rendering incorrectly on the page.

### ISSUE THREAD

**Issue by seulgiism** [searxng/searxng#3949]
![image](https://github.com/user-attachments/assets/1242b2e7-ad0e-434d-b787-0778e9ae7504)

I am on 2024.10.12+7e8b330b3 with the install script.

How can i fix this?

**Comment by return42** [comment]
> How can i fix this?

just update ;-)

Duplicate of https://github.com/searxng/searxng/issues/3928 fixed in https://github.com/searxng/searxng/pull/3930

**Comment by seulgiism** [comment]
> > How can i fix this?
> 
> just update ;-)
> 
> Duplicate of #3928 fixed in #3930

![image](https://github.com/user-attachments/assets/f84b1553-af6c-48ce-946e-2fd2c8420417)

updating just broke my entire instance. how can i debug this?
