### ISSUE TITLE
Main page displayed instead of results sporadically

### ISSUE THREAD

**Issue by hugalafutro** [searxng/searxng#3961]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
irrelevant, happens since about a month ago, install is always on :latest docker image, currently `2024.10.26+ae496e9dd`

**How did you install SearXNG?**
docker

**What happened?**
only main searxng page comes up when inputting search term to browser address bar / search bar, immediately doing the same correctly opens page with results

**How To Reproduce**
1. put search term into address bar / search bar of browser
2. press enter
3. Main SearxNG page appears
4. [RAGE]
5. do 1. again
6. correct page with results appear
7. [RAGE]

**Expected behavior**
page with results for the search term should appear first time, preserving my fragile nerves

**Screenshots & Logs**
n/a

**Additional context**
This happens 1 to 3 times a day or not at all for 3 days, absolutely randomly and non-repeatably. Immediately repeating the same action that landed me on the main page instead of the page with results correctly opens page with results. Doesn't matter if android/linux/windows browser.

**Comment by return42** [comment]
duplicate:

- https://github.com/searxng/searxng/issues/3191#issuecomment-2202729527
