### ISSUE TITLE
search string pulls up odd results for multiple different searches

### ISSUE THREAD

**Issue by alcxander** [searxng/searxng#4009]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Powered by [searxng](https://searx.bndkt.io/info/en/about) - 2024.11.10+dfaf5868e

**How did you install SearXNG?**

no I'm using the search at this URL:
 
https://searx.bndkt.io/

**What happened?**

I search for this exact string
"what types of shares are there in a company"

and it produces one result at the top that explains what a share is from some indian site (e.g. Different types of shares include ordinary, preference, redeemable preference, convertible preference and treasury shares. Shares represent ownership in a company and are an essential aspect of the corporate world.
[www.bajajfinserv.in](https://www.bajajfinserv.in/types-of-shares) ) then every other site search (minus the first one which is a link for whatsapp) result is the definition of the word 'what' (e.g. https://www.merriam-webster.com/dictionary/what ). then it goes back to share pages for a few iterations and then it goes back to definitions of 'what' and then goes to looking up pages that contain the word 'what' in them not related to anything at all (e.g. https://www.nytimes.com/2024/10/23/opinion/election-polls-results-trump-harris.html)

moving to page 2 of results then shows normal expected results of share definitions but moving back to page 1 then shows correct share definitions and is pulling resources from a different cache. 

![image](https://github.com/user-attachments/assets/e4231329-1488-490b-8f0f-8fcc06ac4cff)
not sure if this is related to the search string being removed after navigating the search results or something?

**How To Reproduce**

search for the string what types of shares are there in a company 
URL result is
https://searx.bndkt.io/search?q=what+types+of+shares+are+there+in+a+company
**Expected behavior**

not to get so many mixed search results in a clear type of search function.

**Screenshots & Logs**

![image](https://github.com/user-attachments/assets/eb1ea55b-ad28-441f-ad65-38c4586d3051)

![image](https://github.com/user-attachments/assets/a4319ca9-6a2d-4642-9c25-451b30310436)

![image](https://github.com/user-attachments/assets/17db2fa0-c427-43b5-a043-3a52110c0dec)

**Additional context**

**Comment by llyama** [comment]
There appears to be a problem with the duckduckgo engine. It only uses the first word of the search terms. That's why all duckduckgo results are about the word "what".

**Comment by nicolasdato** [comment]
I'm having the same issue lately. I don't remember if this happened after and update, or out of the blue.

In my case it is as @llyama said, I'm getting results for the first word in the query from DuckDuckGo.

I'm trying this change, and now I'm getting normal results: https://github.com/nicolasdato/searxng/commit/a05697a5b039837ed963c32132dae184d1082215 and the PR is  #4011

**Comment by return42** [comment]
For those coming around here:

> I'm having the same issue lately. I don't remember if this happened after and update, or out of the blue.

Issue was introduced in 

- https://github.com/searxng/searxng/pull/3955

and fixed in:

- #4011
