### ISSUE TITLE
When using Chinese search terms, the results from DuckDuckGo (DDG) always "URL-decode" related URLs

### ISSUE THREAD

**Issue by Aliang-code** [searxng/searxng#4019]
Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG 
2024.11.15+4b57bc3db 

How did you install SearXNG? 
searxng-docker 

What happened? 
When using Chinese search terms, the results from DuckDuckGo (DDG) always URL-decode related URLs. 

How To Reproduce 
Use Chinese search terms to query, regardless of language setting being "all" or "zh". 

Expected behavior 
DDG results should be relevant to the search query without URL encoding related URLs. 

Screenshots & Logs 
![图片](https://github.com/user-attachments/assets/b817346b-ad99-4c6a-b221-eadcf0540817)
![图片](https://github.com/user-attachments/assets/66745f4a-b8f4-49c2-963e-7a4a4d49b54d)

Additional context 
https://github.com/searxng/searxng/pull/4011
maybe this fix is not completion

**Comment by return42** [comment]
> Additional context
> #4011
> maybe this fix is not completion

Yeah, I url-qouted the query string in #4011 .. but the URL-qouted query string result in unexpected *URL decoded* and other garbish results .. to fix the issue I implemented this PR:

- #4021

please give it a try :+1:

**Comment by ShlomiD83** [comment]
> please give it a try 👍

My Hebrew problem seems to be resolved with this fix.

**Comment by return42** [comment]
Closed by https://github.com/searxng/searxng/pull/4021
