### ISSUE TITLE
Problem with DDG and Hebrew search

### ISSUE THREAD

**Issue by ShlomiD83** [searxng/searxng#4020]
Searxng is running inside a docker container on a raspberry pi 4.
Since version  - 2024.11.15+4b57bc3db I'm having issues with Hebrew searching, the results from duckduckgo are in gibberish. 
![Screenshot_20241116_221012_Chrome](https://github.com/user-attachments/assets/b022b828-973a-4580-9eca-52919acfc6cf)
![Screenshot_20241116_221019_Chrome](https://github.com/user-attachments/assets/d36d1111-b90e-46b3-a156-0d427f356268)
When Reverting to the 10.11 version, the issue doesn't happen. 
Please assist.

**Comment by ShlomiD83** [comment]
https://github.com/searxng/searxng/issues/4019

This seems to be the same issue.

**Comment by ShlomiD83** [comment]
@unixfox what does that mean? 🤔

**Comment by return42** [comment]
> @unixfox what does that mean? 🤔

The issue you opened is a duplicate of https://github.com/searxng/searxng/issues/4019 ..
in order not to fray the discussion we have closed your issue, the discussion will be continued in the already existing issue.
