### ISSUE TITLE
Installation fails during "Clone SearXNG sources"

### ISSUE THREAD

**Issue by astier** [searxng/searxng#404]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

64df011e2f99fceb16c861b28aff0ca5ea74f307

**How did you install SearXNG?**

I followed https://searxng.github.io/searxng/admin/installation.html

```sh
cd ~/Downloads
git clone https://github.com/searxng/searxng.git searx
cd searx
sudo -H ./utils/searx.sh install all
```

**What happened?**

Installation fails with the following error:

```
Clone SearXNG sources
---------------------

ls: cannot access '/home/user/Downloads/searx': Permission denied
ERROR: ./utils/searx.sh: line 416: user 'searx' missed read permission: /home/user/Downloads/searx
```

Also during the step when the user is created a useradd-operation can not be executed because its not permitted.

```
user searx
----------

useradd --shell /bin/bash --system  --home-dir "/usr/local/searx"  --comment 'Privacy-respecting metasearch engine' searx
useradd: failed to reset the lastlog entry of UID 970: Operation not permitted
mkdir "/usr/local/searx"
chown -R "searx:searx" "/usr/local/searx"
groups searx
-->|searx
```

**How To Reproduce**

Follow my installation-steps.

**Expected behavior**

Successful searxng installation.

**Additional context**

If I clone the repo under `/usr/local/searxng` I don't get this errors. In the installation-manual there is a paragraph which says:

>For the installation procedure, use a sudoer login to run the scripts. If you install from root, take into account that the scripts are creating a searx, a filtron and a morty user. In the installation procedure these new created users do need read access to the clone of searx, which is not the case if you clone into a folder below /root.

Maybe I don't understand what it exactly means to use a `sudoer login` and thats why the installation fails. When cloning the repo I am using my normal user-account and not a `sudoer login`.

I use arch-linux if thats relevant.

**Comment by return42** [comment]
Welcome @astier  / a _sudoer_ login is a login which has the rights to use the `sudo` command .. like your `user` login.

> If I clone the repo under `/usr/local/searxng` I don't get this errors. In the installation-manual there is a paragraph ... _ In the installation procedure these new created users do need read access .._

Compare the access rights of your `/usr/local/searxng` and your `/home/user/Downloads/searx`.. there must be a difference.

The manual might be a bit misleading, the point is, that the new created users (searx, filtron, morty) need access to the folder.

> Also during the step when the user is created a useradd-operation can not be executed because its not permitted.

This is something different .. I assume you can ignore the line ..

     useradd: failed to reset the lastlog entry of UID 970: Operation not permitted

this line is issued while `useradd` creates the user `searx` .. the creation of the login success, but I don't know why this line is issued on your archnlinux (I tested on archlinux without this issue).

I hope this answers your questions .. I close this issue, if you think your questions are not answered, please reopen this issue and give additional details.

**Comment by astier** [comment]
Thanks for the reply. I still don't understand why I can't install searxng with my normal user. Are people supposed to be able to install searxng by cloning it into `~/Downloads`? If yes I don't understand why I can't do it. If no than I am confused about the installation-instructions because it says I should clone searxng in `~/Downloads`.

The user I used to clone searxng into `/home/user/Downloads` should have rights to use sudo. He is in the wheel-group and in the sudoers-file I have set:

```
%wheel ALL=(ALL) NOPASSWD: ALL
```

The permissions for `/home/user/Downloads` and `/home/user/Downloads/searxng` are then:

```
drwxr-xr-x  3 user user 4.0K Oct 12 13:22 Downloads
drwxr-xr-x 11 user user 4.0K Oct 12 13:22 searxng
```

The rights for `/usr/local` and `/usr/local/searxng` are:

```
drwxr-xr-x 13 root root 4.0K Oct 12 04:40 local
drwxr-xr-x 11 root root 4.0K Oct 12 04:40 searxng
```

Maybe I misunderstand something about how rights work on linux. I don't understand why `searx`-user has rights to access `/usr/local/searxng` which is owned by root but not the rights to access `/home/user/Downloads/searxng` which is owned by `user`-user.

**Comment by astier** [comment]
I understand why I get the following line

```
 useradd: failed to reset the lastlog entry of UID 970: Operation not permitted
```

I set `chattr +i /var/log/lastlog` to clean up the messages I get during boot. It disables the message during boot which tells the time of the last login. This shouldn't be a problem.

**Comment by return42** [comment]
Sorry, the installation might be misleading ..  there is no need to clone to `~/Download` it is just a suggestion, to have access .. it takes to long to describe, why we suggest this ... and it might confuse you more than it helps.

Don't be confused, it is very simple .. 

1. You clone somewhere e.g. `~/Download/searxng`
2. then you run the installation procedures .. these procedures are create new users, e.g. the `searx` user under which the installation takes place
3. to install under `searx`s home folder, the `searx` user needs access to the `~/Download/searxng`

Most often this works without any issue .. I can't say why the `searx` user does not have a access in your scenario .. The 3. step is the point where your installation fails:

    ls: cannot access '/home/user/Downloads/searx': Permission denied

Then you posted ..

> The permissions for ... and `/home/user/Downloads/searxng` are then:

may you mix `/home/user/Downloads/searxng`  and `/home/user/Downloads/searx`?  .. compare with the "permission denied" from above.

**Comment by astier** [comment]
>may you mix /home/user/Downloads/searxng and /home/user/Downloads/searx? .. compare with the "permission denied" from above.

I maybe mix up `searx` and `searxng` while describing the issue which might be confusing but I clone it as `~/Downloads/searx` by executing `git clone https://github.com/searxng/searxng.git searx`. Only if I clone it in `/usr/local` I clone it as searxng because the installation scripts creates `/usr/local/searx`.

The general steps you described I understand. Also that it doesn't have to be in `~/Downloads`. Just a folder where searx-user has access to. I just don't understand why in my case the searx-user doesn't has access to `~/Downloads/searx` but access to `/usr/local/searxng`.

The only reason why I figured out that it works with `/usr/local` is because I watched Luke Smith searx-installation-video https://www.youtube.com/watch?v=oufXi3e-VuA&t=168s where at 02:55 he apparently uses some older searx-installation instructions which say that searx should be cloned into `/usr/local`.

**EDIT:** Although Luke doesn't use the official installation-script. I just somehow got the idea that I could try to clone it in `/usr/local`.

**Comment by return42** [comment]
> is because I watched Luke Smith searx-installation-video

this video describes searx not SearXNG .. and is old.

> I just don't understand why in my case the searx-user doesn't has access to ~/Downloads/searx but access to /usr/local/searxng.

I can't answer this question .. may you have changed something in the umask, or anything other (e.g. did you set some more `chattr`) .. many causes are conceivable .. I don't know.

> I maybe mix up `searx` and `searxng` while describing the issue which might be confusing but I clone it as `~/Downloads/searx` by executing `git clone https://github.com/searxng/searxng.git searx`.

OK, but you did not post the access rights of `~/Downloads/searx` in your https://github.com/searxng/searxng/issues/404#issuecomment-940938794

**Comment by astier** [comment]
>this video describes searx not SearXNG .. and is old.

I know. I was aware of that. Still wanted to see how he does it.

>I can't answer this question .. may you have changed something in the umask, or anything other (e.g. did you set some more chattr) .. many causes are conceivable .. I don't know.

I would say since it works for you its most likely an issue on my side. I can install it anyway now by using `/usr/local`.

>OK, but you did not post the access rights of ~/Downloads/searx in your #404 (comment)

Sorry if I am confusing. I usually clone it as searx but for various reasons I later cloned it as searxng. In both cases the rights are the same. Anyway I cloned it again as searx:

```
drwxr-xr-x 11 user user 4.0K Oct 12 14:42 searx
```

Thank you for your help. My only problem was the rights-issue. Other than that I think the documentation is good. You can close this issue now if you want.

**Comment by return42** [comment]
> Other than that I think the documentation is good. 

I tagged this issue with "documentation" ..

> You can close this issue now if you want.

I left this issue open .. my english is "improvable" ... I hope there comes the day I have time to improve the documentation about the rights-issue ..

> Thank you for your help.

Feel welcome ..
