### ISSUE TITLE
Invalid OpenMetrics formatting

### ISSUE THREAD

**Issue by vojkovic** [searxng/searxng#4044]
@Bnyro @return42 

Was testing https://github.com/searxng/searxng/commit/8744dd3c71bcf29e8df7fdaf18448c3ff65c1035 and noticed that when an engine can't be scraped, the metrics respond with 'None' instead of 0.

See screenshots.
<img width="1015" alt="none" src="https://github.com/user-attachments/assets/3f965821-55f2-4797-912b-4e28d080207b">

<img width="994" alt="all" src="https://github.com/user-attachments/assets/a2a3fbdf-372e-4df0-b2d9-4495aa6e2c45">

**Comment by vojkovic** [comment]
Fixed - Thanks!

**Comment by Bnyro** [comment]
Thanks for the fast report, you're probably the only one that will ever have come across this issue :)
