### ISSUE TITLE
API Parameter for Longer "Content" Snippets in Search Results

### ISSUE THREAD

**Issue by s9anus98a** [searxng/searxng#4064]
https://searx.foss.family/search?q=anak%20dpr%20vonis%20bebas&format=json

Hello Searx developers,

I'm currently working on an application that utilizes the Searx API to retrieve search results. I've noticed that the "content" snippets returned in the JSON response are often truncated and quite short.

Is there an API parameter or configuration option available that allows me to request longer or potentially even full-length content snippets in the search results?  I understand there may be limitations due to performance and resource constraints, but I'm looking for a way to get more context within the API response itself, if possible.

If such a parameter doesn't exist, would you consider adding it as a feature request?  It would be very beneficial for applications that need to display more informative previews of search results without having to fetch the full content from the source URLs separately.

Alternatively, if there are any recommended strategies for getting more complete content previews through the existing API, I'd appreciate any guidance or suggestions.

Thank you for your time and consideration.

---

**Example API Request (current):**

https://searx.foss.family/search?q=example+query&format=json

**Desired Behavior (Hypothetical):**

https://searx.foss.family/search?q=example+query&format=json&content_length=long

or

https://searx.foss.family/search?q=example+query&format=json&full_content=true

(or any other parameter that could control content length/completeness)

---

**Current behavior:** The "content" field in the JSON response often contains truncated snippets.

**Expected behavior:**  Ideally, there would be a way to control the length or completeness of the "content" field through an API parameter, allowing for more informative previews in the search results.

**Comment by return42** [comment]
Thats not possible, the SearXNG engines just wrap the content from the origin search engines.

**Comment by Strangahhh** [comment]
Is there no way that this is possible?

**Comment by return42** [comment]
> Is there no way that this is possible?

How .. when the content is already limited by the origin search engine?

By example, when SearXNG uses the ddg engine, all the content we get is:

![Image](https://github.com/user-attachments/assets/fa18385a-e59b-4443-8138-8e8ea94ade81)

**Comment by Strangahhh** [comment]
Thank you so much. For explanation
