### ISSUE TITLE
Request for adding New (for SearXNG) Language - Tatar (tt).

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [searxng/searxng#4098]
Hello!

It seems like that "Translators needed" can't be a good Place for requesting Languages, because Requests are w/o any Answer, which makes Me think it will be ignored.
So [after a while](https://github.com/searxng/searxng/issues/540#issuecomment-2264083028) I've decided to make separate Issue Request for My Language:

> Hello!
> I am Amirkhandrend-Nicest-XII in CodeBerg Project that sent Tatar Language Request.
> I was impressed by SearX and liked searching via that Engine, but unfortunately for Me I found that SearX's GitHub Repo was archived so I can't request Tatar for SearX...
> But I found SearXNG! I even ran own (for Myself) version in Docker... and for now I really want to translate SearXNG into Tatar Language!
> 
> I hope that this Request will be accepted.
> 
> Just some clarification for Tatar Language and why this Language:
> Tatar Language is The Biggest Minority (yep, that's probably sounds strange) Language in Russia. [Politics Expunged]. We are trying to translate as much as possible projects and doing it with best Quality (if that is possible; Translation String System can differ from project to project) to digitalize our Language.

For this Time I actually didn't abandon using SearXNG, so I know some Context for some Strings without need of Asking someone who knows.

**Comment by return42** [comment]
@Amirhan-Taipovjan-Greatest-I I'm sorry, I overlooked your request, thanks for reminding me :+1: 

In PR #4106 I added `tt` .. the new language should be synced to https://translate.codeberg.org/projects/searxng/searxng/ next time (I don't know the sync interval).

-----

The process is described here: https://docs.searxng.org/dev/translation.html

------

Seems the sync is not triggered when a new language is added / the trigger is a modification of the pot file:

https://github.com/searxng/searxng/blob/c60fe999cf6dd77599992918b0cdb6f6c5df4baf/utils/lib_sxng_weblate.sh#L149-L154

@dalf do we have a chance to trigger the sync manually?

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> @Amirhan-Taipovjan-Greatest-I I'm sorry, I overlooked your request, thanks for reminding me 👍
> 
> In PR #4106 I added `tt` .. the new language should be synced to https://translate.codeberg.org/projects/searxng/searxng/ next time (I don't know the sync interval).
> 
> The process is described here: https://docs.searxng.org/dev/translation.html
> 
> Seems the sync is not triggered when a new language is added / the trigger is a modification of the pot file:
> 
> https://github.com/searxng/searxng/blob/c60fe999cf6dd77599992918b0cdb6f6c5df4baf/utils/lib_sxng_weblate.sh#L149-L154
> 
> @dalf do we have a chance to trigger the sync manually?

Thank You!

Also I've wanted this to be noticed (sorry if You already saw this, I just don't sure about that):
>Also I've noticed that "Татар (Tatar)" used instead of "Татарча (Tatar)". Yes, I know that in Unicode CLDR Standart this appears too, but I think (and also I've asked this Question to more Knowing Native, and he also stated "Татарча" being more Natural as Language's Self-Name) that My Option sounds more Natural for My Language's Self-Name as Language Name, "Татар" is more like a Standart Adjective like "Tatar Culture".

**Comment by return42** [comment]
@Amirhan-Taipovjan-Greatest-I your translations from weblate are now merged -> https://github.com/searxng/searxng/pull/4122 :+1:
