### ISSUE TITLE
url contains search so going back a page doesn't break searches

### ISSUE THREAD

**Issue by Melechtna** [searxng/searxng#4116]
It would be nice to have an option, to allow the search engine to retain the search. This way if you press back, you don't have to resubmit the form every time. If this is an option, I can't find it, but as an example, if you search something with searxng, it just results in a URL like this

ipaddress:port/search

When to avoid breaking things, it should be something like

ipaddress:port/search?q=test+something+else

Then the search will be automatically resubmitted. This can kind of be accomplished by manually inputting the search engine into the browser with the correct flags, but it would be better if this behavior could just be toggled.

**Comment by return42** [comment]
Duplicate:

- https://github.com/searxng/searxng/discussions/2612
