### ISSUE TITLE
The returned JSON result is incorrect

### ISSUE THREAD

**Issue by Jaleel-zhu** [searxng/searxng#4120]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

earxng-docker
**What happened?**

When no results are found, JSON returned an incorrect URL list
**How To Reproduce**

When no results are found, JSON returned an incorrect URL list
**Expected behavior**

When there are no query results,JSON returns an empty list

**Comment by return42** [comment]
Can you please give an example of what you get and what you expect.

**Comment by return42** [comment]
Closed due to lack of Feedback.
