### ISSUE TITLE
Bug: google videos engine

### ISSUE THREAD

**Issue by CactusPie** [searxng/searxng#4127]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.12.16+65c970bdf

**How did you install SearXNG?**

I installed it with docker, but it can be reproduced on public instances as well, such as the top 3 instances on https://searx.space/

**What happened?**

Google Videos search gives a parsing error and no videos from Google Videos are shown. Videos from other search engines appear correctly. To see the error you have to unfold the "Response time: X seconds" section

**How To Reproduce**

Search for any videos with Google Videos enabled and to see the error you have to unfold the "Response time: X seconds" section

**Expected behavior**

Google Videos results should be shown

**Screenshots & Logs**

![image](https://github.com/user-attachments/assets/3feb1dc5-a404-4441-b368-99b61a7e1a70)

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 80
  * Parameters: `('.//div[@class="ITZIwc"]', 'index 0 not found')`
  * File name: `searx/engines/google_videos.py:118`
  * Function: `response`
  * Code: `c_node = eval_xpath_getindex(result, './/div[@class="ITZIwc"]', 0)`

**Comment by return42** [comment]
@CactusPie thanks for pointing out / I patched the bug in PR #4128, can you please test the PR :+1:

**Comment by CactusPie** [comment]
Wow, that was fast! Since it was only 2 lines, I manually put in the changes from the PR into the file and it seems to work now. Thank you so much!
