### ISSUE TITLE
Option to remove websites containing ads from search results? 

### ISSUE THREAD

**Issue by hdkw** [searxng/searxng#4150]
**Is your feature request related to a problem? Please describe.**

Hi. Is there a way, once a page of results appears, to have the engine quickly open each site and check for the presence of ads (for example by testing if there's elements from adblockers lists), and then remove those sites from the search results?

**Describe the solution you'd like**

I am back with this suggestion I made for Searx almost 10 years ago because, more than ever, people (and the planet) need to have ways to escape that predatory part of the internet that sells audience to advertisers. 
With the problems of AI content and disinformation, we really need a way to look at adfree websites only.

**Describe alternatives you've considered**

I am not tech savy and I don't know how this can be done.

**Additional context**

Make internet great again ;)

**Comment by unixfox** [comment]
We do not plan to add such feature, that would slow down the search by a lot. You would have to wait for searxng to visit ALL the websites.

Anyway if you want to exclude website from the results you can use the hostname filter plugin.

**Comment by hdkw** [comment]
Ok, thanks for your answer. I hope someone somewhere will create such a search option..
