### ISSUE TITLE
Searx POST method

### ISSUE THREAD

**Issue by simpvn** [searxng/searxng#434]
**1.0.0**

**How did you install SearXNG?**
I'm using public instance searx.be

**What happened?**
POST method does not work on Brave browser as search query is shown on search bar and history

**How To Reproduce**
Enable POST method and search anything

**Expected behavior**
Search query is hidden on search bar and history

**Additional context**
Startpage does not have the same problem

<img width="781" alt="Screen Shot 2021-10-25 at 12 33 35" src="https://user-images.githubusercontent.com/78357927/138640109-f31ea140-4197-4ca6-a678-96b368b2724e.png">
<img width="1178" alt="Screen Shot 2021-10-25 at 12 33 54" src="https://user-images.githubusercontent.com/78357927/138639953-a21ebc16-ffb7-410a-92ac-1038a2f537cb.png">
79b-4ab1-bfdd-a5c5d3671768.png">
<img width="669" alt="Screen Shot 2021-10-25 at 12 34 25" src="https://user-images.githubusercontent.com/78357927/138639962-c67be16e-2498-48f8-a9fe-55621a413a77.png">
<img width="947" alt="Screen Shot 2021-10-25 at 12 34 39" src="https://user-images.githubusercontent.com/78357927/138639966-f43f0cae-eb69-4ed0-aea1-41bc8fc33411.png">

**Comment by unixfox** [comment]
Which method is set in the section "privacy" from the preferences page?

Did you try to search again? It should use POST after that.

**Comment by simpvn** [comment]
> Which method is set in the section "privacy" from the preferences page?
> 
> Did you try to search again? It should use POST after that.

POST does not work
Like the pics above, chossing POST doesn't hide anything

**Comment by dalf** [comment]
* With Brave `Version 1.31.87 Chromium: 95.0.4638.54 (Build officiel) (64 bits)`, no extension
* searx.be, if I go to the preferences, "Privacy" tab, I select "POST", save
* After that, if I enter a query on searx.be and then press enter (or click on magnifier on the right of the input field on the web page), the HTTP request is using the POST method:

![image](https://user-images.githubusercontent.com/1594191/139209018-96668911-b631-46be-bf52-dfa4469cc2f4.png)

Do you have any installed extensions ?

**Comment by unixfox** [comment]
> > Which method is set in the section "privacy" from the preferences page?
> > Did you try to search again? It should use POST after that.
> 
> POST does not work Like the pics above, chossing POST doesn't hide anything

Are you talking about when you type in the address bar and then press enter?

**Comment by simpvn** [comment]
> * With Brave `Version 1.31.87 Chromium: 95.0.4638.54 (Build officiel) (64 bits)`, no extension
> * searx.be, if I go to the preferences, "Privacy" tab, I select "POST", save
> * After that, if I enter a query on searx.be and then press enter (or click on magnifier on the right of the input field on the web page), the HTTP request is using the POST method:
> 
> ![image](https://user-images.githubusercontent.com/1594191/139209018-96668911-b631-46be-bf52-dfa4469cc2f4.png)
> 
> Do you have any installed extensions ?

I have no extensions
The search query won't show up on brave search bar if you search directly on searx search bar but will show up if you search on brave search bar
Queries are logs in history no matter what
<img width="779" alt="Screen Shot 2021-10-28 at 15 05 34" src="https://user-images.githubusercontent.com/78357927/139214132-7640ed95-e150-475d-910b-d737acb1b0f3.png">
<img width="714" alt="Screen Shot 2021-10-28 at 15 05 43" src="https://user-images.githubusercontent.com/78357927/139214180-23867c90-f21d-43b5-90fb-066d6be5bb2e.png">
<img width="770" alt="Screen Shot 2021-10-28 at 15 05 59" src="https://user-images.githubusercontent.com/78357927/139214189-b2520ce6-ac6e-4e74-9431-4c95268750f3.png">
>

**Comment by simpvn** [comment]
> > > Which method is set in the section "privacy" from the preferences page?
> > > Did you try to search again? It should use POST after that.
> > 
> > 
> > POST does not work Like the pics above, chossing POST doesn't hide anything
> 
> Are you talking about when you type in the address bar and then press enter?

Like I reply to @dalf 
Type in searx address bar does hide the query on brave address bar but doesn't hide in history
Type in brave addressbar does not hide anything

**Comment by unixfox** [comment]
Ok so I did my own testing.

The POST method works on Searx for Brave when searching directly on the Searx search bar.

The query is stored in the browser history, but that's because Searx return the query in the title of the page. We can allow hiding the query from the page title if that's what you are asking for.
Startpage doesn't include the query in the page title, so that's why it is not in the history, but the page title is still included in the history.

And about the query being in the search bar URL when searching from the brave search bar we can't do anything about that, that's how every chromium browsers works (brave is based on chromium): https://www.chromium.org/tab-to-search. Even startpage has this issue:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/4016501/140542269-26e4a081-f09a-4310-bca1-266f542197e5.png">
If you want to have a POST method that works directly from the browser search bar then use Firefox.

**Comment by simpvn** [comment]
> Ok so I did my own testing.
> 
> The POST method works on Searx for Brave when searching directly on the Searx search bar.
> 
> The query is stored in the browser history, but that's because Searx return the query in the title of the page. We can allow hiding the query from the page title if that's what you are asking for. Startpage doesn't include the query in the page title, so that's why it is not in the history, but the page title is still included in the history.
> 
> And about the query being in the search bar URL when searching from the brave search bar we can't do anything about that, that's how every chromium browsers works (brave is based on chromium): https://www.chromium.org/tab-to-search. Even startpage has this issue: <img alt="image" width="617" src="https://user-images.githubusercontent.com/4016501/140542269-26e4a081-f09a-4310-bca1-266f542197e5.png"> If you want to have a POST method that works directly from the browser search bar then use Firefox.

Ok, thanks for your clafification
As a private search engine, I think hiding the search query in browser in history is important, like Startpage, queries don't show up in history and even when you click on it, it returned you to the search engine mainpage rather than the query.

**Comment by dalf** [comment]
The Simple theme hides the query with the POST method, but Chrom* browsers don't support the POST method when the query is sent from the URL bar ; so this is not a solution.

Two possible changes:
* always remove the title
* add an preference

---

Related lines of code:
* Simple theme: https://github.com/searxng/searxng/blob/1ccf296a558260e46f5b7a294807bd74285e70fc/searx/templates/simple/results.html#L10
* Oscar theme: https://github.com/searxng/searxng/blob/1ccf296a558260e46f5b7a294807bd74285e70fc/searx/templates/oscar/results.html#L19

**Comment by unixfox** [comment]
I would prefer a preference because on Firefox nothing is stored in the history and I need the query in the page title in order to find which specific search I did between all my tabs.

I don't like how it's done on Startpage, imagine finding a specific search between all these different searches that I did, it's just a nightmare: 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/4016501/140625055-1fadb2eb-9536-42f9-b0ac-a2d397215882.png">

**Comment by simpvn** [comment]
> I would prefer a preference because on Firefox nothing is stored in the history and I need the query in the page title in order to find which specific search I did between all my tabs.
> 
> I don't like how it's done on Startpage, imagine finding a specific search between all these different searches that I did, it's just a nightmare: <img alt="image" width="1216" src="https://user-images.githubusercontent.com/4016501/140625055-1fadb2eb-9536-42f9-b0ac-a2d397215882.png">

I can see the problem with that but like @dalf suggested, being something you can toggle on/off would be nice because I still think that hiding past searches in history is important

**Comment by dalf** [comment]
Fixed by #485

With Firefox, using the POST HTTP method, you can enable the new setting "query in title" safely: the queries are not store in the FF history.
