### ISSUE TITLE
Most of the instances lost the TLS rating on the searx.space

### ISSUE THREAD

**Issue by johndoe432** [searxng/searxng#435]
![0001](https://user-images.githubusercontent.com/44312135/138844979-b5e2cc91-b41d-4fc0-b8e1-bf636e8a6adb.png)

What could be the reason for this?

**Comment by return42** [comment]
Please report this at https://github.com/searxng/searx-space/issues / Thanks!

**Comment by johndoe432** [comment]
> 
> 
> Please report this at https://github.com/searxng/searx-space/issues / Thanks!

Sure! Sorry for using this repo for that kind of question
