### ISSUE TITLE
Yummly engine

### ISSUE THREAD

**Issue by czadikem** [searxng/searxng#438]
**Working URL to the engine**

https://www.yummly.com/

**Why do you want to add this engine?**

I think that it would be cool to have a category for recipes like duckduckgo has.  That way people can find recipes easily.  Not open source or libre that I know of.

**Features of this engine**

Finds recipes for people.
**How can SearXNG fetch the information from this engine?**

Create a new category called recipes.

**Additional context**

Example of what I think it should look similar to https://duckduckgo.com/?q=shrimp+scampi&ia=recipes&iax=recipes

**Comment by dalf** [comment]
The interesting URL seems to be `https://duckduckgo.com/js/spice/recipes/{{ search }}`

**Comment by allendema** [comment]
@dalf Here is a list of spices that could be used https://github.com/Snazzah/duck-duck-scrape/tree/master/src/spices.
And their docs: https://duck-duck-scrape.js.org/modules.html#currency


I wonder if ```dictionaryDefinition```, ```dictionaryPronunciation``` and/or ```dictionaryHyphenation``` could be implemented as autocomplete backends, something [similiar to this demo.](https://github.com/allendema/searx/commit/25bf3a81b54811fdd8f1469e668b9dd31e7e906c)

DDG have a list of zeroclickanswers too but sure how that all works.
https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/t
