### ISSUE TITLE
Add newer ui themes

### ISSUE THREAD

**Issue by czadikem** [searxng/searxng#439]
**Is your feature request related to a problem? Please describe.**

Searx look a little dated and I saw these webpage sytles for searx that work really well. They also look great.
**Describe the solution you'd like**

Why don't you add a dark theme of the Pointhi style a newer almost duckduckgo material like one that is light and one that is dark.  Here are the examples https://userstyles.org/styles/127046/dark-searx-oscar-pointhi-theme-8-backgrounds (pointhi dark) https://userstyles.org/styles/151116/searx-material-design(duckduckgo material light)  then combine the two for (duckduckgo material dark) 
**Describe alternatives you've considered**

**Additional context**

![Screenshot 2021-10-26 145135](https://user-images.githubusercontent.com/35937408/138959397-dcfa021a-b4bb-4c9c-8c50-23e1ebeb28dd.png)
![Screenshot 2021-10-26 145025](https://user-images.githubusercontent.com/35937408/138959271-2675819a-2b95-4a16-b515-5b1167e4ddd5.png)
![Screenshot 2021-10-26 145058](https://user-images.githubusercontent.com/35937408/138959294-42678983-e809-4ff5-b511-d5bd10f49eea.png)

**Comment by return42** [comment]
> Searx look a little dated 

This is SearXNG, searx is here https://github.com/searx/searx/

> and I saw these webpage sytles for searx that work really well. 

We are in the process of redesigning the simple theme / this is an ongoing process, [watch](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository) SearXNG to be informed and participate.
