### ISSUE TITLE
Unwanted suggestions when a currency conversion is made with Google

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#442]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
* 1.0.0-948-cec9ded2, master branch, not forked

**How did you install SearXNG?**
* searxng-docker

**What happened?**
* "Disclaimer" and "Data provided by Morningstar for Currency and Coinbase for Cryptocurrency" are being added to search suggestions when they should not be there.

**How To Reproduce**
* Do a currency conversion with Google **enabled**.

- Examples:
    - 10 usd to cad
    - 1 btc to usd

**Expected behavior**
* Suggestions circled in red below are not suggestions and not should be there.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/52939984/138983976-90f4564d-737a-43d9-b6f8-4c1ce32b2429.png)

**Comment by dalf** [comment]
The suggestions comes from the google engine: `!google 10 usd to cad`

**Comment by return42** [comment]
Hi @pyvon thanks for your report .. the google & google-videos engine need a rework, I fixed the issues in https://github.com/searxng/searxng/pull/547 / can you test the PR / thanks!
