### ISSUE TITLE
[question] filtron fails after reinstalation / in new installations

### ISSUE THREAD

**Issue by return42** [searxng/searxng#443]
Today I (re-) installed filtron on two hosts (archlinux, ubu2004) and got strange response .. see below .. is it only me?

@dalf can you try a re-installtion of filtron in a docker iimage?

```
OKServer: fasthttp
Date: Wed, 27 Oct 2021 23:47:23 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 10751
Server-Timing: total;dur=17.155, render;dur=13.062
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
X-Download-Options: noopen
X-Robots-Tag: noindex, nofollow
Referrer-Policy: no-referrer

<!DOCTYPE html>
<html lang="de-DE" xml:lang="de-DE" class="nojs">
<head>
    <meta charset="UTF-8" />
    <meta name="description" content="SearXNG - a privacy-respecting, hackable metasearch engine" />
    <meta name="keywords" content="SearXNG, search, search engine, metasearch, meta search" />
    <meta name="generator" content="SearXNG/1.0.0-961-2624034c">
....
```

**Comment by mrpaulblack** [comment]
Yeah I had the same problem with my instance on monday (but only when using filtron from dalfs fork tho): https://paulgo.dev/paulgoio/searxng/-/issues/11 ....

[EDIT] right now its possible to use dalf/filtron or to build asciimoo/filtron from the git repo...

**Comment by dalf** [comment]
Few days ago, I have installed a searxng-docker without issue.

I'm not sure to understand the issue, is it related to https://github.com/valyala/fasthttp/issues/875 ?

**Comment by mrpaulblack** [comment]
So the imge dalf/filtron:latest works fine, but rebuilding it from your git repo does not work. Filtron seems to serve data with the HTTP 0.9 Protocol for whatever reason!? And there is also the issue return42 already mentioned, where it cuts of the served html after the header....

**Comment by tiekoetter** [comment]
filtron is currently also broken when updating/installing it via utils/filtron.sh

**Comment by dalf** [comment]
I've updated https://github.com/dalf/filtron : 
*  `docker build` / `make build` works again.
*  the built docker image doesn't have this issue

searx(ng)-docker uses dalf/filtron docker image.

About `utils/filtron.sh`, see  #455
