### ISSUE TITLE
docker & installation scripts: uwsgi.ini : avoid out of memory.

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#447]
**Is your feature request related to a problem? Please describe.**
Currently the number of uwsgi worker doesn't take into account the memory limit : each worker takes about 256MB of memory. If the memory is low ( < 512MB ), the docker image & the installation scripts start more than one worker. Consequence: there is either OOM or swap usage. From the user point of view, the application is really slow.

**Describe the solution you'd like**

The default configuration must avoid OOM.

The uwsgi worker count can be defined using:
```python
import psutil
import multiprocessing

# 256MB without the checker per worker, 320MB with the checker 
memory_total = psutil.virtual_memory().total
worker_count_from_memory = int(memory_total / 320)
worker_count_from_core = multiprocessing.cpu_count()
worker_count = math.min(worker_count_from_memory, worker_count_from_core)
```
(or the bash version of this code).

**Describe alternatives you've considered**
?

**Additional context**

**Comment by yellowhat** [comment]
I am limited to 512 MB of RAM.
Are there any settings that I can change to lower the memory utilization?

Thanks

**Comment by dalf** [comment]
In your `uwsgi.ini`, set the number of worker to 1 : 
https://github.com/searxng/searxng/blob/afde954df8fedc0c9d21d1cc75407ecafed020ab/dockerfiles/uwsgi.ini#L7
(here the version used in the docker image as an example)
