### ISSUE TITLE
Document how to switch from searx to searxng

### ISSUE THREAD

**Issue by ralphrmartin** [searxng/searxng#450]
**Is your feature request related to a problem? Please describe.**

I want to install searxng (on debian). I already have a running instance of searx (not searxng).
The documentation says how to install from scratch, or how to upgrade searxng. Assuming a simple recipe is possible, a few lines explaining how to convert an existing searx instance to use searxng instead would be reassuring and helpful.

**Describe the solution you'd like**

A step by step guide in the documentation of how to change a running searx installation into a running searxng installation

**Describe alternatives you've considered**

I could just try what might work, but that risks leaving me with a broken / botched installation.

**Additional context**

I guess there are plenty of others with the same request.

**Comment by dalf** [comment]
How did you installed searx ? the installation scripts ? docker ? the debian package ?

Did you customized your instance ?

**Comment by ralphrmartin** [comment]
Personally, I used the scripts, but I suppose whichever method one used, some documentation would be helpful.

I edited the configuration files, but made no other customisation.

**Comment by dalf** [comment]
@return42 when the code is not modified, can you confirm this procedure:
* uninstall searx using `./utils/searx.sh remove all` (only searx, not morty, not filtron)
* reinstall SearXNG using https://searxng.github.io/searxng/admin/installation.html

I'm not sure about `/etc/searx/settings.yml` ?

**Comment by ralphrmartin** [comment]
Any news on this request, please?

**Comment by return42** [comment]
@ralphrmartin sorry for the delay, I have lost sight of this issue .. thanks for your reminder.

I send PR .. may you like to have a look at: https://github.com/searxng/searxng/pull/622

Does it help? .. suggestions are welcome (lets move the discussion to this PR).

**Comment by ralphrmartin** [comment]
Thank you!  Comments under the PR.
