### ISSUE TITLE
simple theme: UI issue with results without description

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#458]
_Originally posted by @MrPaulBlack in https://github.com/searxng/searxng/issues/457#issuecomment-954903607_ :

I think we should add a default description if the returned result from the engine does not provide any; Right now results look really dull without a description and a simple `The website did not provide a description.` could make the elements of the simple theme a lot more streamlined looking...

Current layout:
![image](https://user-images.githubusercontent.com/38733246/139474646-beb40bab-f2e3-415f-a3e0-b5f84302600e.png)

(And yeah you are right, once images are using grid layout it should be pretty easy to fix the padding. Just a selector if they are inside the default result container and making the left margin or gap bigger...)

**Comment by return42** [comment]
Ooops .. sorry my fail / I reopen this issue!
