### ISSUE TITLE
Permit cycling of images with arrow keys

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#464]
**Is your feature request related to a problem? Please describe.**

No it is not. It would however be cool to cycle through images via keyboard right and left keys like you can do in most search engines. The image detail would simply show the previous or next image when you hit left and right keys on your keyboard respectively in the Simple Theme.

**Describe the solution you'd like**

The image detail looks very clean and I love it. The cherry on top would be to allow cycling of images via RIGHT (next) and LEFT (previous) like all search engines do. This will also make SearXNG feel more aligned with other engines. Thank you for your hard work!

**Describe alternatives you've considered**

I have not considered any alternatives.

**Additional context**

![image](https://user-images.githubusercontent.com/68975831/139597832-68434ad9-a9f9-4688-abf7-daab31c105f3.png)

**Comment by dalf** [comment]
Thank you for your message!

In the preferences, enable "Vim-like hotkeys" :
![image](https://user-images.githubusercontent.com/1594191/139598285-dc05b43c-c470-46e4-9a04-a1bac7e67a7a.png)
(actually it seems you don't have to do that, this is a bug).

Then press "h":
![image](https://user-images.githubusercontent.com/1594191/139598293-bd0bb98b-d0d9-43a6-a9ea-9f9077eff26c.png)

So you can use 
* `j` and `k` keys to go the previous and next images (actually any results). I agree the left and right keys are more usual.
* `Esc` to close the detail
* `Enter` to open it
* `o` opens the full size image (`t` to open it in another tab)

**Comment by ACodingGenie** [comment]
Yeah that works nicely. You can close this if you'd like unless you'd like to backlog this for sometime in the future to allow the same with right and left keys. Thank you!

**Comment by mrpaulblack** [comment]
Closing in favor of #836.
