### ISSUE TITLE
[SIMPLE THEME]: Reddit search engine breaks Simple Theme "Image" tab Style.

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#470]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Powered by searxng - 1.0.0-999-e4025cd1

**How did you install SearXNG?**
SearXNG docker image with docker-compose.

**What happened?**

If you turn on reddit search engine from settings.yml it gets enabled for several categories including "Images." However, things get a little funny with the images tab as far as the formatting goes. As you can see in the image below, the results don't encompass the entire canvas but only a portion like they do with "General" tab. I believe this might be due to reddit returning search results vs images when you're in the image tab (image 2 below). You'll see these search results if you keep scrolling down.

**How To Reproduce**

1. Make sure reddit search engine is turned on for images category in settings or globally via settings.yml.
2. Search for something and go to images tab.
3. Notice the behavior where images only take up the left-hand side of the canvas.

**Expected behavior**

Images should use the entire canvas like they do when reddit search engine is turned off (image 3) and search should only include images or gifs etc.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/68975831/139709131-bf5468ea-d3de-41a6-994b-0e09ec3adcac.png)
![image](https://user-images.githubusercontent.com/68975831/139709582-a6b6194a-6941-4ddb-be66-85238a5784a2.png)
![image](https://user-images.githubusercontent.com/68975831/139710023-e5def10b-e633-481c-a6c9-0e0ab2c8fda3.png)

**Alternatives**
Remove Reddit search engine from images category by default so it doesn't get enabled from settings.yml.

**Comment by dalf** [comment]
Technically, an alternative to #471 is to replace
https://github.com/searxng/searxng/blob/07f849cd56c48ad74769eb9d4af1d917329164c3/searx/engines/reddit.py#L69
by
```python
elif resp.search_params["category"] != 'images':
```

So:
* `!reddit test` returns text and image results
* with the reddit engine included: `!images test` returns only images
* with the reddit engine included: `!social test` returns text and images.

But I think #471 is better.

**Comment by return42** [comment]
> But I think #471 is better.

I'm going to merge #471 ...
