### ISSUE TITLE
[simple theme] remove shaddow effects and other blur

### ISSUE THREAD

**Issue by return42** [searxng/searxng#472]
Some of the elements from the simple theme have shadow effects / some of these effects are only visible in light mode

IMO the simple theme should be "flat and simple" .. no shadows, no 3D effects, no blur effects.

* back to top button (shadow effect):

![grafik](https://user-images.githubusercontent.com/554536/140034711-9d0f6fb2-7b18-4668-983c-a89517439997.png)

* toggle button (shadow effect / only viewable in light mode)

![grafik](https://user-images.githubusercontent.com/554536/140034895-9698e9e6-a393-4bfa-b0c5-18ee0352664f.png)

![grafik](https://user-images.githubusercontent.com/554536/140035179-2ed2cd12-3361-4d67-a742-0c0e5782e78d.png)

**Comment by mrpaulblack** [comment]
What about transitions? I was planning on adding transitions to the btn hover effects the search box and stuff like this... (Right now there is only a transition on the backtotop element...)

[EDIT] also: there are shadows on these elements in the dark theme but since they are darker than the background they are very faint (but still there; check out dark theme result page on mobile for example...)

**Comment by return42** [comment]
IMO transitions are OK, my remark is only about the "flat and simple" design. By example; it bits my eyes to have a shadow at the right button but none at the left ... for me, the right one is placed in a third dimension (3D) as the button casts a shadow ...

![grafik](https://user-images.githubusercontent.com/554536/140034711-9d0f6fb2-7b18-4668-983c-a89517439997.png)

... if we want to have a shadow, I think the shadow should be added to all buttons.  But before adding shadows all over there I think we should reduce the complexity and should stay by a very _flat_ design (no 3D effects, all items are 2D).

My English is not very elaborated, hope I could clarify what I mean (2D vs. 3D)

>  there are shadows on these elements in the dark theme but since they are darker

is exactly what I wanted to say :)

**Comment by return42** [comment]
Closed by https://github.com/searxng/searxng/pull/474/commits/ca971bd5e5c1421777696a3c7f315880110ffc65
