### ISSUE TITLE
docker image broken

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#482]
The last docker image doesn't work:
* the web page shows `Internal Server Error`
* `/var/log/uwsgi/uwsgi.ini` :
```
Traceback (most recent call last):
  File "/usr/local/searxng/searx/webapp.py", line 61, in <module>
    from searx.engines import (
  File "/usr/local/searxng/searx/engines/__init__.py", line 22, in <module>
    from searx.utils import load_module, match_language, gen_useragent
  File "/usr/local/searxng/searx/utils.py", line 11, in <module>
    from lxml import html
  File "/usr/lib/python3.9/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3.9/site-packages/lxml/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

How to test:
* https://searxng.github.io/searxng/admin/installation-docker.html#searxng-searxng
* (or https://github.com/searxng/searxng-docker )

I've tried:
1. to remove the latest-build-cache tag from https://hub.docker.com/r/searxng/searxng/tags
2. trigger again https://github.com/searxng/searxng/actions/runs/1426096185

Same result.
Perhaps it is related to https://github.com/searxng/searxng/pull/477

**Comment by ACodingGenie** [comment]
Can confirm. Same issue here for a few hours :'(

**Comment by mrpaulblack** [comment]
yeah same for my latest staging: https://staging.paulgo.io (pipeline: https://paulgo.dev/paulgoio/searxng/-/jobs/744); I am building without cache in my gitlab ci/cd so its def. not a problem with github pipeline...

**Comment by dalf** [comment]
Fixed, but it takes 3 hours to build the docker image instead of 1 hour (for amd64, arm64 and arm/v7):
https://github.com/searxng/searxng/blob/1ccf296a558260e46f5b7a294807bd74285e70fc/manage#L436

It happens on when the requirements*.txt files change.

The limit on GitHub is 6 hours: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
