### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by cinetube** [searxng/searxng#490]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1043-90acb342

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectError
  * Percentage: 100
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @cinetube ,
Thank you for you bug report. Could you please provide more information with your bug report. How did you install SearXNG? Did you change any settings in `settings.yml`? or in the /preferences in your webbrowser when that issue happened? Did you use a public instance (If yes please provide the URL)?

**Comment by return42** [comment]
>   * Parameters: `(None, None, 'lite.duckduckgo.com')`

Did you checked `lite.duckduckgo.com` is reachable from the host where SearXNG runs / to exclude a DNS resolve issue try to ping from the SearXNG host ...

**Comment by return42** [comment]
closed because there is no feedback

**Comment by cinetube** [comment]
@return42 I am sorry for not providing feedback earlier. Though "lite.duckduckgo.com" works perfectly but when I ping "lite.duckduckgo.com" I get request timed out. Is this problem related to my ISP?

**Comment by return42** [comment]
> Though "lite.duckduckgo.com" works perfectly .. but .. "lite.duckduckgo.com" ...I get request timed out.

typo? you mean "ping duckduckgo.com" works / correct?

Seems lite.duckduckgo.com does not echo a ping .. when you use nslookup you should see something like this ..

```
$ nslookup lite.duckduckgo.com
Server:		46.38.225.230
Address:	46.38.225.230#53

Non-authoritative answer:
lite.duckduckgo.com	canonical name = duckduckgo.com.
Name:	duckduckgo.com
Address: 40.114.177.156
```

**Comment by cinetube** [comment]
```
nslookup lite.duckduckgo.com

Name:      lite.duckduckgo.com
Address 1: 40.81.94.43
```

```
nslookup duckduckgo.com

Name:      duckduckgo.com
Address 1: 40.81.94.43
```

I get above answer when I nslookup duckduckgo domains. 

Still getting errors with duckduckgo

![Screenshot 2021-11-26 001637](https://user-images.githubusercontent.com/23441775/143487189-b92f3f0d-ab3e-4a44-b89e-3221df1d7b1a.jpg)

**Comment by return42** [comment]
Don't look to close to the stats / having temporary timeouts is common.

Try if searches like `!ddg foo` works .. if this works, you do not have an issue.
