### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by cinetube** [searxng/searxng#497]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1043-90acb342

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectError
  * Percentage: 35
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @cinetube ,
Thank you for you bug report. Could you please provide more information with your bug report. How did you install SearXNG? Did you change any settings in settings.yml? or in the /preferences in your webbrowser when that issue happened? Did you use a public instance (If yes please provide the URL)?

Also as return42 already pointed out in #490 : Did you checked `api.qwant.com` is reachable from the host where SearXNG runs / to exclude a DNS resolve issue try to ping from the SearXNG host ...

**Comment by cinetube** [comment]
@MrPaulBlack  

I installed searxng using docker. 

I didn't change any settings in settings.yml.

`api.qwant.com` is reachable. When I access `api.qwant.com` from a web browser I get `{"status":"success","data":[]}`

**Comment by return42** [comment]
> I installed searxng using docker. 
> ...
> When I access `api.qwant.com` from a web browser I get `{"status":"success","data":[]}`

You have to test the connection from within the container.

**Comment by cinetube** [comment]
<img width="398" alt="Screenshot 2021-11-13 005708" src="https://user-images.githubusercontent.com/23441775/141520446-e82a149a-ec87-4a39-9a8a-5a8b2131ac1a.png">

@return42  

When I try to ping `api.qwant.com` I get no response. 

How to resolve this issue?

`qwant.com` is working fine and is not blocked by my isp.

**Comment by return42** [comment]
Seems `api.qwant.com` does not echo to a ping, alternatively you can use `curl -v` if a host does not echo.  But when `qwant.com` echoes to a ping, the DNS resolution works and the connection success.

May be you had a temporary problem, can you confirm that the search `!qwant foo` do not work?

**Comment by dalf** [comment]
on my laptop `curl -v https://api.qwant.com` works, but not `ping api.qwant.com` --> curl is a more reliable test.

**Comment by return42** [comment]
closed because there is no feedback
