### ISSUE TITLE
The magnifier glass is not displayed as expected / is broken

### ISSUE THREAD

**Issue by return42** [searxng/searxng#502]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Updated to current master https://github.com/searxng/searxng/commit/c6dcedb911b0fc3c0982fcf8294a19389e5a2ac9 at https://darmarit.org/searx

**What happened?**

The magnifier glass is not displayed as expected / is broken ...

![grafik](https://user-images.githubusercontent.com/554536/141653405-b0cb68fc-6900-429e-adbd-079aaae9cb0d.png)

This issue is only observed at my server .. when I try `make run` locally, everything is fine.

**How To Reproduce**

Have a look at the result page of the simple theme:  [here](https://darmarit.org/searx/?preferences=eJxtVU2P4zYM_TXxxdgAO9ui3UNOA_TaAt27QUuMzLUkupScjObXl8o4G3lmDjasJ_HxiV82kNGxEKaTw4gCvvMQ3QoOTxg7zwb87QvWzIbD4jHjya5mro_jjoIeHRbhl3L6ISt2AfPE9vTP3__-6BKcMSGImU5PXZ4w4ClR5egE0-pzGjgOEa9DhvH0F_iEnWUadJP9BeXEoMsji-s4GZAvKRdV49mRYYuXDuwFokE7bE42CkowekUxOop6s4QBYibTJzOxBxmGZAjV8PD0fKWZ_ls54zBsAVAQXn0RMqnF3lxUv319DQNlRb9--_bHyzCcyWOqbPxCM8ejHkolcixhx3tlsZHmFhK0lrIqYkPg-4CWYJMVKFJ7lOKFLPGqsvQDuTqUdSwOQ9rkeB5TxqPc1wUm5p0C5dXIJsplTw0NqTHmS740QLXSNClrfddgHJ5_P_z5xFe9Tf_z8Pzb4fv31zJDv7BPM2lJteyYS-DolaJFgwYnsJQ-C8TktRBtu70gSl5HbGTEJWz3QuEr7Y47cpp0SPn9bUfmeZfICUaB-tq4alo1Jj3tTn3VrN5q--a4ADySPFIetfgxbwSPbujfLBpLCnZsaUeKrl17UjEag4qkvYKUQfJSu6sBzwIBqtG9AB2z89gvHkof-ELYVsct_f0ucwuYGRylu_grjbtKKM5lFsGYm6rWMCZexeC-IV4jhBbJPBfOnCaeIT7MW4mwLKnZWdhalAcQ4VKX7-qVy7soNJ0Q1kRGoZn0Xqnh5gWj4MINdBaKM4Fp8mOt6y2etdMycdzF_5e4B2RXi_HTM-_a9yyoE4DP-QqCvSVBo1EtW8zr_BhR3LYM_BNxfnfrKgdkl5rrpLM4ebK4by7WntuNlDXo-GvKwFH2MN4LRn1lCrcqzR3G_ah8DM_FrwrV4QnyctxWR4q3WKFOUGF_n4uP_QuFYeI8Y0kf9iZOWSsGdb5rLdym7_4Aw_A2_q-iLn5p-1zJBGnatj4QJfTnQaXyhx2dNdq5Mqzi1Y82DMon1nUk1F-Tefs7Fv2_eM1gpwWOKuR_nuS5xg==&q=John%20Doe)

**Additional context**

I don't know if it is related to the issue, but the server has a very strong CSP ..

![grafik](https://user-images.githubusercontent.com/554536/141653481-322214d7-76a9-4396-ae1b-8a711e7a12df.png)

**Comment by dalf** [comment]
> I don't know if it is related to the issue, but the server has a very strong CSP ..

Yes this is related.
Some of the svg elements use the style attribute, since the CSP forbid its usage, the svg is broken.
svgo can minified the svg and also replace the style attributes by svg attributes. see the `convertStyleToAttrs` plugin : https://www.npmjs.com/package/svgo

now svgo is already included and grunt-webfont is no more a problem.

**Comment by return42** [comment]
Thanks for clarifying .. I will implement a svgo solution that replaces htnlmin / as you suggested in https://github.com/searxng/searxng/pull/473#discussion_r745355881
