### ISSUE TITLE
Filtron install script always downloads AMD64 binaries even on AArch64 systems.

### ISSUE THREAD

**Issue by NoaHimesaka1873** [searxng/searxng#507]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
commit 646db5d4f942b4c4da4a62f38b159bd80b7f9db1
**How did you install SearXNG?**
followed the official wiki https://searxng.github.io/searxng/admin/installation.html
**What happened?**
When trying to install filtron, it downloads AMD64 version of Go, so exec format error happens

**How To Reproduce**
Grab an AArch64 server, install Oracle Linux 8.4, and try to follow the guide.

**Expected behavior**
It should've downloaded AArch64 binaries.

**Screenshots & Logs**
```
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
INFO:  using instance at: /usr/local/searx/searx-src
INFO:  switching to /usr/local/searx/searx-src/.config.sh

=======
filtron
=======

Install filtron (service)
=========================

user filtron
------------

useradd --shell /bin/bash --system  --home-dir "/usr/local/filtron"  --comment 'Reverse HTTP proxy to filter requests' filtron
mkdir "/usr/local/filtron"
chown -R "filtron:filtron" "/usr/local/filtron"
groups filtron
-->|filtron : filtron
export SERVICE_HOME=/usr/local/filtron
Environment /usr/local/filtron/.go_env has been setup.
grep -qFs -- 'source /usr/local/filtron/.go_env' ~/.profile || echo 'source /usr/local/filtron/.go_env' >> ~/.profile
** press any [KEY] to continue **

Install Go in user's HOME
-------------------------

download and install go binary ..
INFO:  caching: https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
INFO:    --> /home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz
--2021-11-16 11:07:03--  https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
Resolving golang.org (golang.org)... 2404:6800:4004:826::2011, 172.217.175.81
Connecting to golang.org (golang.org)|2404:6800:4004:826::2011|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz [following]
--2021-11-16 11:07:03--  https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 2404:6800:4004:81d::200e, 172.217.175.46
Connecting to dl.google.com (dl.google.com)|2404:6800:4004:81d::200e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134803982 (129M) [application/x-gzip]
Saving to: '/home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz'

/home/mihatehiura/s 100%[===================>] 128.56M  17.2MB/s    in 7.8s

2021-11-16 11:07:12 (16.4 MB/s) - '/home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz' saved [134803982/134803982]

echo $PATH
  |filtron| /usr/local/filtron/local/go/bin:/usr/local/filtron/go-apps/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
echo $GOPATH
  |filtron| /usr/local/filtron/go-apps
mkdir -p $HOME/local
rm -rf $HOME/local/go
tar -C $HOME/local -xzf /home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz
-bash: line 2: /usr/local/filtron/local/go/bin/go: cannot execute binary file: Exec format error
** press any [KEY] to continue **

Install filtron in user's ~/go-apps
-----------------------------------

go install -v github.com/asciimoo/filtron@latest
  |filtron| -bash: line 1: /usr/local/filtron/local/go/bin/go: cannot execute binary file: Exec format error

Install filtron rules
=====================

INFO:  install rules /home/mihatehiura/searx/utils/templates/etc/filtron/rules.json
INFO:    --> /etc/filtron/rules.json
** press any [KEY] to continue **

Install System-D Unit filtron
-----------------------------

INFO:  install (eval=1): /lib/systemd/system/filtron.service
INFO:  BUILD /home/mihatehiura/searx/cache/lib/systemd/system/filtron.service
INFO:  BUILD using template /home/mihatehiura/searx/utils/templates/lib/systemd/system/filtron.service
chown: invalid group: 'mihatehiura:mihatehiura'
INFO:  install: /home/mihatehiura/searx/cache/lib/systemd/system/filtron.service
-->|'/home/mihatehiura/searx/cache/lib/systemd/system/filtron.service' -> '/lib/systemd/system/filtron.service'
** press any [KEY] to continue **

Activate filtron (service)
--------------------------

systemctl enable  filtron.service
systemctl restart filtron.service
Created symlink /etc/systemd/system/multi-user.target.wants/filtron.service → /usr/lib/systemd/system/filtron.service.
systemctl status --no-pager filtron.service
● filtron.service - filtron
   Loaded: loaded (/usr/lib/systemd/system/filtron.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-11-16 11:07:37 KST; 17ms ago
 Main PID: 728751 ((filtron))
    Tasks: 1 (limit: 36875)
   Memory: 2.8M
   CGroup: /system.slice/filtron.service
           ‣ 728751 [(filtron)]

Nov 16 11:07:37 oracle-arm systemd[1]: Started filtron.
Nov 16 11:07:37 oracle-arm systemd[1]: filtron.service: Main process exited…EXEC
Nov 16 11:07:37 oracle-arm systemd[1]: filtron.service: Failed with result …de'.
Hint: Some lines were ellipsized, use -l to show in full.
** press any [KEY] to continue **

ERROR: Filtron is not listening on: http://127.0.0.1:4004
INFO:  Apache is installed on this host.

Do you want to install a reverse proxy (ProxyPass) [YES/no] n

Do you want to inspect the installation? [NO/yes] n
```
_Note: that username is not real name, just ~~google~~searx it and you will know where it's from._

**Additional context**
Don't be AMD64 centric and please test these scripts on AArch64 systems from now on.

**Comment by return42** [comment]
> When trying to install filtron, it downloads AMD64 version of Go, so exec format error happens
> ...
> Don't be AMD64 centric and please test these scripts on AArch64 systems from now on.

We are a small team, we don't have the time and resource needed to implement & test various architectures.

**Comment by dalf** [comment]
@return42 can we leave this open.

The issue is really small: 
https://github.com/searxng/searxng/blob/646db5d4f942b4c4da4a62f38b159bd80b7f9db1/utils/filtron.sh#L46

we just need to replace `amd64` by the right architecture using something like https://github.com/canha/golang-tools-install-script/blob/71df49a4aedffac73fa8ae6b5913de66be6aead4/goinstall.sh#L10-L37

Once done, most probably there will some adjustments to do, but the maintenance is going to be low. 
(the searxng/searxng docker image supports various architectures)

I can create a PR about this topic, this week.

---

@NoaHimesaka1873 can you patch these two scripts:
* https://github.com/searxng/searxng/blob/646db5d4f942b4c4da4a62f38b159bd80b7f9db1/utils/filtron.sh#L46
* https://github.com/searxng/searxng/blob/646db5d4f942b4c4da4a62f38b159bd80b7f9db1/utils/morty.sh#L32

In these lines, replace `amd64` by `arm64`, and try again?

**Comment by return42** [comment]
> Once done, most probably there will some adjustments to do, but the maintenance is going to be low.

Don't think so .. how can we test issues with different architecture? On the long term I prefer to invest the time in a (built-in) replacement of morty & filtron.

**Comment by NoaHimesaka1873** [comment]
@dalf Tried it, but systemd scripts all output 203/EXEC error and if I launch them manually and set up nginx, it just gives 502 bad gateway. Also, searxng/searxng-docker says it only supports AMD64, which conflicts with your statement.

**Comment by dalf** [comment]
> Also, searxng/searxng-docker says it only supports AMD64, which conflicts with your statement.

* `searxng/searxng` is built for AMD64, ARM64, ARM/v7: see https://hub.docker.com/r/searxng/searxng/tags
* https://github.com/searxng/searxng-docker supports only AMD64 because the filtron & morty docker image are only built for AMD64

> On the long term I prefer to invest the time in a (built-in) replacement of morty & filtron.

That's another issue, but @mrpaulblack  uses the embedded image proxy (not Morty) on a public instance. I don't know the full configuration, but it means Morty dependency can be dropped in a near future. That's another topic.

**Comment by return42** [comment]
FYI: I'm on the way to implement a PR to detect the right go binary to download.

**Comment by mrpaulblack** [comment]
On another note; maybe filtron should be moved into SearXNG org. from your fork @dalf? I think it would be better to keep that central organized in the org.... Then we could build and publish our own filtron images to docker hub. For example I really want to use the patch https://github.com/dalf/filtron/pull/2 to finally drop the image proxy logging in my fork... (We can also update searx-docker to use  our image instead)....

**Comment by dalf** [comment]
@NoaHimesaka1873  can you try the PR #508 ?
