### ISSUE TITLE
start and stop without any log on arm V7 orangepi zero

### ISSUE THREAD

**Issue by bodtx** [searxng/searxng#514]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
probably the latest 

docker pull searxng/searxng:latest

-->
**How did you install SearXNG?**

sudo docker run --rm -it -m 250m  -v ${PWD}/searxng:/etc/searxng -p 8686:8080 -e BASE_URL=http://192.168.1.xx:8686/ -e "INSTANCE_NAME=maison" searxng/searxng

**What happened?**

try to start 🤘

```
SearXNG version
Use existing /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
```

and then stop 😭

**How To Reproduce**

Running it on an orangepi zero Armbian 21.02.3 Buster with Linux 5.10.21-sunxi

512Mo RAM

**Expected behavior**

do not stop 

**Additional context**

if I try to update uwsgi.ini to get logs in /dev/stdout, it says

   open("/dev/stdout"): Permission denied [core/logging.c line 288]

tried to change to root the running user but same thing 🙄

```
uid = root
gid = root
```

**Comment by mrpaulblack** [comment]
Hi @bodtx ,
Thank you for your bug report. So if I get this right; you started the SearXNG docker container interactively on your pi and you cannot stop it anymore? Did you try pressing ctrl-c to send a interrupt to the container? Else you can also try opening another terminal on your pi; type in `docker ps` copy the id of the container and stop it with `docker container stop [CONTAINER ID]`.. Does this help or could you otherwise try to give reproducible steps for your issue with the actual behavior you want to happen?

**Comment by bodtx** [comment]
@mrpaulblack hi, no
* it stops automatically after this line `[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static`, I cannot keep it up, I do not have any reason in the logs
* it is an orange pi not a raspberry.

**Comment by mrpaulblack** [comment]
Hmm I am actually not sure if the arch of the orange pi is supported by SearXNG tbh... maybe @return42 knows more (also is a port in the base url like this even allowed)...? Also just to clarify; with 

> it stops automatically after this line [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static, I cannot keep it up, I do not have any reason in the logs

You mean that the container stops and you get a fresh input line in the terminal, where you can execute commands normally, right? (Also did you try to connect to your instance?)

**Comment by return42** [comment]
> Hmm I am actually not sure if the arch of the maybe @return42 knows more (also is a port in the base url like this even allowed)...?

Different port should be OK .. But @bodtx uses a docker container and I can't speak for docker / nor docker setup. 

@bodtx to narrow down the error / 

- did you ever succeed to start a docker container on your device? / if unsure, try to start/stop a little "hello-world" container to see if containers are running well.

- What OS (image) do you run on your device Ubuntu, Debian or Raspbian Image?

----

About arch: I assume there is a https://en.wikipedia.org/wiki/ARM_Cortex-A7 assembled / what is a 32Bit CPU

>      docker pull searxng/searxng:latest

I do not know, what happens when the searxng/searxng docker container runs on a 32Bit CPU / may be @dalf has an idea

**Comment by bodtx** [comment]
@mrpaulblack yes I have a fresh input line.
@return42 I assume docker is running as I can run a working murmur server with it.

I use this indeed `docker pull searxng/searxng:latest`

I did connect to the instance (-it does not work, used entrypoint), 
`sudo docker run -i -t --entrypoint sh    -v ${PWD}/searxng:/etc/searxng -v ${PWD}/searxng/log:/var/log/ -p 8686:8080 -e BASE_URL=http://192.168.1.xx:8686/ -e "INSTANCE_NAME=maison" searxng/searxng`

but then try to launch searxng inside the container but same thing:
```
/usr/local/searxng # /usr/local/searxng/dockerfiles/docker-entrypoint.sh
SearXNG version
Use existing /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
/usr/local/searxng #
```

seems that [here ](https://github.com/searxng/searxng-docker#multi-architecture-docker-images)it is compatible only with amd64?

**Comment by dalf** [comment]
> seems that here it is compatible only with amd64?

searxng-docker is compatible only with amd64 (for now).

the docker image searxng/searxng should be compatible with amd64, arm64, arm7: https://hub.docker.com/r/searxng/searxng/tags . 

Inside the image can you look at the content of `/var/log/uwsgi/uwsgi.log` ?

**Comment by bodtx** [comment]
> Inside the image can you look at the content of /var/log/uwsgi/uwsgi.log

launching directly with this command inside container `/usr/local/searxng # /usr/local/searxng/dockerfiles/docker-entrypoint.sh`

```
/usr/local/searxng # cat /var/log/uwsgi/uwsgi.log
*** Starting uWSGI 2.0.19.1 (32bit) on [Sun Mar  1 10:28:32 1970] ***
compiled with version: 10.3.1 20210424 on 05 April 2021 18:18:03
os: Linux-5.10.21-sunxi #21.02.3 SMP Mon Mar 8 00:28:04 UTC 2021
nodename: 681b9682cd4d
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1311 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 7
Python version: 3.9.5 (default, May 12 2021, 20:44:22)  [GCC 10.3.1 20210424]
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6fa7390 (most recent call first):
<no Python frame>
```

**Comment by return42** [comment]
> `Fatal Python error: init_interp_main: can't initialize time`

I haven't seen such error before, but may be this link can help? ... https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-735236388

**Comment by bodtx** [comment]
> I haven't seen such error before, but may be this link can help? ... linuxserver/docker-papermerge#4 (comment)

tried but same thing :\

**Comment by bodtx** [comment]
> I haven't seen such error before, but may be this link can help? ... linuxserver/docker-papermerge#4 (comment)

tried but same thing :\

**Comment by return42** [comment]
> What OS (image) do you run on your device Ubuntu, Debian or Raspbian Image?

**Comment by bodtx** [comment]
`Welcome to Armbian 21.02.3 Buster with Linux 5.10.21-sunxi`

debian base

**Comment by return42** [comment]
> tried but same thing :\

- did you restart the container after confirming you have libseccomp2.4.4 installed .. see https://docs.linuxserver.io/faq#libseccomp
- you can also try to run the docker container in privileged mode ...

I'm not familiar with / AFAIK Buster has libseccomp2.3.x https://packages.debian.org/buster/libseccomp2 .. if read this [article](https://docs.linuxserver.io/faq#libseccomp) right, you need at least  libseccomp2.4.4  .. I assume Armbian just compiles the source packages of a common 64bit buster distro for 32bit ARM

**Comment by bodtx** [comment]
mmm thx for the tip, it [seems](https://docs.linuxserver.io/faq#resolution) I need docker 20+.

I only have 

`Docker version 18.09.1, build 4c52b90`

to much work to me, thx anyway

**Comment by return42** [comment]
> to much work to me, thx anyway

feel welcome / I close this issue .. feel free to reopen if needed.
