### ISSUE TITLE
[simple theme] news: image, alternative text overwrites box intended for the image 

### ISSUE THREAD

**Issue by return42** [searxng/searxng#523]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

current master

**How To Reproduce**

In category news search for items which have a long alternative text / and the image is not available ..

**Expected behavior**

Text should not overwrite ..

**Screenshots & Logs**

![grafik](https://user-images.githubusercontent.com/554536/142631148-c449b5b3-0fb2-42c9-9c68-43b1faaff0b2.png)

**Comment by return42** [comment]
Another issue I found is the text that goes over in the column intended for the image

![grafik](https://user-images.githubusercontent.com/554536/142632061-dc400486-bfba-4e8f-b821-b49d23fd180b.png)

**Comment by mrpaulblack** [comment]
I think the news category needs to be reworked as a whole tbh. The description should be bigger and I would like to move the images to the right...

**Comment by return42** [comment]
> I think the news category needs to be reworked 

@mrpaulblack sounds good to me .. what do you think about the music category ... IMO the image can be a little bit smaller

![grafik](https://user-images.githubusercontent.com/554536/142636584-d079638a-cfe0-428c-8617-f992b28fccb0.png)


BTW: listen to this https://maceoparker.bandcamp.com/album/funk-overload ;)

**Comment by dalf** [comment]
> Text should not overwrite ..

Technical answer:
https://stackoverflow.com/questions/51326819/alt-text-of-broken-image-overflows-bounds/51326948

[edit] the alt text is actually the title.
https://github.com/searxng/searxng/blob/master/searx/templates/simple/macros.html#L22
I don't know what is recommended, my intuition is:
* to remove the alt text: 
* add `aria-hidden="true"`
because the text is repeated twice, which not very helpful.

But I don't have experience with web accessibility.

**Comment by mrpaulblack** [comment]
On the long run I think something like this:
* video category like our image category (based on ddg video tab); but before I want to try  grid layout for images to drop the js for the grid
* news category more description; Images on the right
* maps category; either the entire screen leaflet with the results marked as POI on the map or the results like in general with detail modal like in images
* music def. needs to be reworked two; this I am not sure what would be the best here; maybe as you already set smaller images
* files, science and IT is good IMO

**Comment by return42** [comment]
> the alt text is actually the title.
> I don't know what is recommended,

lets remove the `alt` attribute
