### ISSUE TITLE
[question] Add support for multiple architectures 

### ISSUE THREAD

**Issue by return42** [searxng/searxng#53]
I just want to leave some links here, what else we could do to support multiple architectures:

- There is a PR https://github.com/searx/searx/pull/2490 fixing filtron.sh and morty.sh to support multiple architectures
- There is a https://github.com/searx/searx/discussions/2680#discussioncomment-569197 worth to read // **update**: done in #22)
- LXC: Here is what I will try to test: https://askubuntu.com/a/1223581  .. also using qemu-arm-static  and [binfmt_misc](https://en.wikipedia.org/wiki/Binfmt_misc) .. the charm is, that (I hope) I can integrate it in searx's LXC suite.

what else should we consider?

**Comment by dalf** [comment]
> There is a searx/searx#2680 (comment) worth to read

Done with https://github.com/searxng/searxng/pull/22

**Comment by mrpaulblack** [comment]
I think this is already done, since we dont use morty and filtron anymore and the scripts and the docker image already support multiple architectures; Closing.

(Feel free to reopen if I missed something)
