### ISSUE TITLE
Add support for the language Esperanto

### ISSUE THREAD

**Issue by telmobss1** [searxng/searxng#530]
Mi ŝatus peti vin plene aldoni subtenon por la lingvo Esperanto, kaj kiel parola lingvo, kaj ankaŭ manieron grupigi novaĵojn kaj retejojn tute en la lingvo Esperanto. 

I would like to ask you to fully add support for the language Esperanto, both as a spoken language, as well as a way to group news and websites entirely in the language Esperanto

**Comment by return42** [comment]
You can help to translate SearXNG UI at https://weblate.bubu1.eu/projects/searxng/searxng/eo/

**Comment by telmobss1** [comment]
It's not really a question of translation, but of creating a region to centralize Esperanto sites

**Comment by telmobss1** [comment]
![IMG_20211120_170920](https://user-images.githubusercontent.com/80489312/142735079-f8b32b99-dbcb-49b8-bef6-9774bd21146a.jpg)

**Comment by return42** [comment]
We can add Esperanto to the language list, but first it would be nice to have some help in translating UI.

**Comment by dalf** [comment]
> creating a region to centralize Esperanto sites

If I understand correctly you want to add a new category Esperanto, in addition to General, Videos, etc...
This category would group different engines dedicated to the Esperanto language.
So `!esperanto io` would search on these engines.

Am I correct?

**Comment by telmobss1** [comment]
> > criando uma região para centralizar sites Esperanto
> 
> Se bem entendi, você deseja adicionar uma nova categoria Esperanto, além de Geral, Vídeos, etc ... Esta categoria agruparia diferentes motores dedicados à língua Esperanto. O mesmo `!esperanto io`aconteceria com a pesquisa nesses motores.
> 
> Estou correcto?

exactly

**Comment by return42** [comment]
Good to know you can translate English to Esperanto. If you want, we help you, help us and translate the UI: https://weblate.bubu1.eu/projects/searxng/searxng/eo/

thanks

**Comment by telmobss1** [comment]
it's more a matter of getting content in the Esperanto language.

**Comment by telmobss1** [comment]
I know Google has the Esperanto language, that's what I'd like to see in searxng, since the interface translation is not a priority, as most only want to read posts in Esperanto, and not have everything in Esperanto

**Comment by return42** [comment]
just choose language Esperanto `!eo vetero` / no need for a category dedicated to one language.

**Comment by dalf** [comment]
@return42 , I think the idea is to add some new engines dedicated to the Esperanto language.
For example https://tekstaro.com/ , and I guess there are many other websites.

@telmobss1 can you write new SearXNG engine for these websites? or do you know someone who can? We can help new developers.
It can be as simple as [few lines in settings.yml](https://github.com/searxng/searxng/blob/1c8b731791f1ca82887e776fefed86618a775b36/searx/settings.yml#L475-L491), or some Python code.

**Comment by telmobss1** [comment]
> basta escolher o idioma Esperanto `!eo vetero`/ não há necessidade de uma categoria dedicada a um idioma.

Yes,There is a problem, because when we select Esperanto interface, it doesn't search for Esperanto content.

**Comment by return42** [comment]
Please do not repost what we have written, in a different language / this is an international forum and we write exclusively in English. SearXNG is a meta search engine .. you know what a meta search engine is?

Read dalf's https://github.com/searxng/searxng/issues/530#issuecomment-974761830 and send us your PR .. before contributing, please read the doc: https://searxng.github.io/searxng
