### ISSUE TITLE
Bug: google engine Suspended: too many requests

### ISSUE THREAD

**Issue by amansubhan** [searxng/searxng#531]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1123-1c8b7317

**How did you install SearXNG?**
Iinstalled via docker image

**What happened?**
While running searched i hit this issue (Suspended: too many requests)

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
Is your SearXNG instance public / do you often see this issue or just temporary?

**Comment by mrpaulblack** [comment]
Try enabling `use_mobile_ui: true` in google section of settings.yml:

https://github.com/searxng/searxng/blob/1c8b731791f1ca82887e776fefed86618a775b36/searx/settings.yml#L611-L617

**Comment by amansubhan** [comment]
> Is your SearXNG instance public / do you often see this issue or just temporary?

Not really, just installed last night, and only i am using on my 2 devices yet.

**Comment by amansubhan** [comment]
> Try enabling `use_mobile_ui: true` in google section of settings.yml:
> 
> https://github.com/searxng/searxng/blob/1c8b731791f1ca82887e776fefed86618a775b36/searx/settings.yml#L611-L617

Will try this and let you know

**Comment by amansubhan** [comment]
> > Try enabling `use_mobile_ui: true` in google section of settings.yml:
> > https://github.com/searxng/searxng/blob/1c8b731791f1ca82887e776fefed86618a775b36/searx/settings.yml#L611-L617
> 
> Will try this and let you know

This indeed resolved the issue. Thanks

**Comment by sadie626** [comment]
hey guys i had the same problem  i use cloudflare what i did to fix it was turn proxy off on the A name record it started working with no prob  hope this hellps  someone

**Comment by return42** [comment]
[Just a piece of advice: it's not recommended to use Cloudflare as reverse proxy because it MITM every request, which is a disaster for user's privacy.](https://github.com/searxng/searx-instances/issues/85#issuecomment-1154107294)

**Comment by crashedthecymbal** [comment]
Same here, no search engine works anymore, except wikipedia. 
duckduck --> CAPTCHA
brave --> CAPTCHA
google --> Suspended: CAPTCHA

**Comment by dimon222** [comment]
> Same here, no search engine works anymore, except wikipedia. duckduck --> CAPTCHA brave --> CAPTCHA google --> Suspended: CAPTCHA

most of engines started implementing aggressive captcha/anti-bot protections because of AI scraping load of insane amounts.
