### ISSUE TITLE
Bug: google images engine

### ISSUE THREAD

**Issue by TheEssem** [searxng/searxng#532]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1123-1c8b7317

**How did you install SearXNG?**
I installed it using the official wiki.

**What happened?**
I searched for a specific query in the image search and it didn't parse the Google Images results properly.

**How To Reproduce**
1. `!goi n64 controller`
2. See a parsing error on the side.

**Expected behavior**
I expected the results from Google Images to show alongside the other results.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/21112968/142747338-4464943c-e19d-4500-8e45-b2380db3621a.png)
```
2021-11-20 20:34:42,490 WARNING:searx.engines.google images: ErrorContext('searx/engines/google_images.py', 175, "url = eval_xpath_getindex(link_node, '@href', 0)", 'searx.exceptions.SearxEngineXPathException', None, ('@href', 'index 0 not found')) False
2021-11-20 20:34:42,490 ERROR:searx.engines.google images: exception : @href index 0 not found
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 142, in search
    search_results = self._search_basic(query, params)
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 130, in _search_basic
    return self.engine.response(response)
  File "/usr/local/searx/searx-src/searx/engines/google_images.py", line 175, in response
    url = eval_xpath_getindex(link_node, '@href', 0)
  File "/usr/local/searx/searx-src/searx/utils.py", line 618, in eval_xpath_getindex
    raise SearxEngineXPathException(xpath_spec, 'index ' + str(index) + ' not found')
searx.exceptions.SearxEngineXPathException: @href index 0 not found
```

**Additional context**
The `use_mobile_ui` option has no effect on this issue.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 65
  * Parameters: `('@href', 'index 0 not found')`
  * File name: `searx/engines/google_images.py:175`
  * Function: `response`
  * Code: `url = eval_xpath_getindex(link_node, '@href', 0)`

**Comment by return42** [comment]
@TheEssem thanks for reporting this issue ..

> The `use_mobile_ui` option has no effect on this issue.

FYI: this setting is not used in the google images engine.

> `searx.exceptions.SearxEngineXPathException: @href index 0 not found`

very strange / I can't reproduce this issue on my instances nor in a local `make run`, but I can confirm that this issue pops up on your instance for some queries while other queries do [work](https://searx.projectlounge.pw/search?q=%21goi%20dali&categories=none&language=en) .. 

I will have a look if we can harden the !goi scrapper .. stay tuned / coming soon ...

**Comment by return42** [comment]
@TheEssem could you please test https://github.com/searxng/searxng/pull/533 .. since I can't reproduce the issue, please have a look at logging, I added an error log for items causing this issue .. thanks!

**Comment by TheEssem** [comment]
Just got around to testing it, it works like a charm. Thanks for the speedy fix! :)
