### ISSUE TITLE
[simple theme] autocomplete results not clickable

### ISSUE THREAD

**Issue by tiekoetter** [searxng/searxng#542]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

commit dae165eaa02ff51f6c1aec8c1ab33dfe4aed3797

**How did you install SearXNG?**

https://searxng.github.io/searxng/admin/installation.html

**What happened?**

When using simple theme I am not able to click on the autocomplete suggestions the list just instantly closes and the "data-autocomplete-old-value" value just stays the same as before. If I use the arrow keys to select one of the suggestions and hit enter the "data-autocomplete-old-value" gets refreshed as expected.

This problem occurs in Chrome / Chromium (Windows, Linux (Arch), macOS and Android) and Safari (iOS and macOS)

**How To Reproduce**

Installing SearXNG and trying to use the autocomplete feature.

**Expected behavior**

autocomplete behaving like it does when using arrow keys and enter.

---

Sorry if it is some trivial issue. I just discovered it while using SearXNG on a phone where arrow keys are (mostly) not available.

**Comment by return42** [comment]
@tiekoetter sounds strange .. I can't reproduce this issue, do you have any cookies set? /  please go into the preferences and try to reset all settings.

Do you have any other setting changed in the settings.yml?

What happens if you clone SearXNG and run a local instance by `make run`?

**Comment by tiekoetter** [comment]
@return42 I have some strange news: In a fresh Windows VM with Firefox and Google Chrome I encountered this issue again with Google Chrome. Firefox seems to work though.

**settings.yml**
autocomplete: 'google'

**preferences**
I only selected simple as the default theme and didn't change anything else.

By your suggestion I tried to run a local instance with ``make run``. This led to the same result as above.

**Comment by dalf** [comment]
I confirm I have the issue on Chrome on Windows and Chrome on Android.

**Comment by mrpaulblack** [comment]
Yeah also happens on Safari on iOS

**Comment by return42** [comment]
@not-my-profile copied from https://github.com/searxng/searxng/issues/693#issuecomment-1005467686

> the bug apparently occurs on all browsers

I can't reproduce this issue (this is also the reason why I can't fix it) ... tested on FFFox & Chrome Desktop and on my android device where I use Fennec.

**Comment by tiekoetter** [comment]
@return42 Yes Firefox works correctly. Chrome doesn't and it is irrelevant if it is mobile Chrome on Android or desktop Chrome on Windows, macOS or Linux. It is also irrelevant if it is Chromium, Google Chrome or any other Chromium based Browser.

Could you share your Chrome configuration?

Also I don't really understand how the autocomplete feature works. I could maybe help troubleshooting it if you could give further insight.

**Comment by not-my-profile** [comment]
>Yes Firefox works correctly.

The problem happens in Firefox for me (Firefox 95 on Debian).

EDIT: Weird ... I could reproduce it earlier ... now I can't. Maybe it's unreliable.

**Comment by tiekoetter** [comment]
@not-my-profile I can't reproduce this with Firefox 95.0.2 on Arch Linux, macOS or Windows using simple theme on searx.tiekoetter.com, searx.be or paulgo.io

**Comment by return42** [comment]
@tiekoetter I made a mistake .. I have to precise:

1. In Chrome & Chromium .. it is selectable by the up and down arrow keys (and pressing ENTER) .. **but it is not clickable**

2. In FFox it is also **clickable**

> The problem happens in Firefox for me (Firefox 95 on Debian).

@not-my-profile strange, I have ubuntu FFox 95 and it is **clickable** in oscar and in simple theme.

**Comment by xiaoyong-wang** [comment]
If you visit https://searx.tiekoetter.com/ (or another SearXNG instance using the simple theme) through https://www.browserling.com (select win7 + chrome) you will be able to see the issue.

**Comment by return42** [comment]
Could you please test PR https://github.com/searxng/searxng/pull/737

**Comment by tiekoetter** [comment]
@return42 It works now!

**Comment by return42** [comment]
@tiekoetter thanks a lot for your feedback / good to here it works :)

> Yeah also happens on Safari on iOS

@mrpaulblack do you have a Safari to test PR #737?

EDIT: now I have seen https://github.com/searxng/searxng/pull/737#issuecomment-1009150916

**Comment by mrpaulblack** [comment]
@return42 I tested PR on mobile safari as well as chrome and works in both cases perfectly :+1: LGTM
