### ISSUE TITLE
Searx is not recognized as a search engine on vivaldi

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#546]
**How did you install SearXNG?**
From git then python -m searx.webapp 

**How To Reproduce**
1. Install Vivaldi
2. Make a search on searx
3. Right click on the search bar on the home page.
4. There is no "Add as a search engine..."

**Expected behavior**
Have the "Add as a search engine" button.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/4016501/143503751-a1b7ec78-7846-4218-9a06-e51127be236c.png)

**Additional context**

**Comment by mrpaulblack** [comment]
@unixfox does it work with Chrome/Chromium? (I think vivaldi is chromium based...)

**Comment by unixfox** [comment]
I think it does because last time I tried it showed up in my settings. Maybe vivaldi is a bit different.

**Comment by unixfox** [comment]
Well it seems like Searx need to be in GET method in order to have the "add search engine" button.

**Comment by return42** [comment]
> Well it seems like Searx need to be in GET method in order to have the "add search engine" button.

Thats true, but even when the "add search engine" button is shown, this is a simple URL-placeholder (`?q=%s`) entry .. Vivaldi does not support OpenSearch (with OpenSearch you also have a autocompletion). I added a link to:

- https://github.com/searxng/searxng/issues/431#issue-1033790847

and going to close this issue (its not a bug we can fix).
