### ISSUE TITLE
Make HTML templates more CSP compliant

### ISSUE THREAD

**Issue by return42** [searxng/searxng#57]
**What happened?**

We have a lot of not CSP compliant `style='...'` attributes (and element) in our HTML templates

This single style element is not CSP compliant:

https://github.com/searxng/searxng/blob/d36adfa59f242a8775ad74245c696d62b7727a36/searx/templates/oscar/base.html#L39-L44

But there is also a lot of `style='...'` attributes usage ...

**update:**: with patches from this PR https://github.com/searxng/searxng/pull/81 applied, the following remain ...
```
./oscar/preferences.html:25:<td class="{{ label }}" style="padding: 2px">{{- "" -}}
./oscar/preferences.html:29:        <span style="width: calc(max(2px, 100%*{{ (stats[engine_name].time / max_rate95)|round(3) }}))" class="stacked-bar-chart-median"></span>{{- "" -}}
./oscar/preferences.html:30:        <span style="width: calc(100%*{{ ((stats[engine_name].rate80 - stats[engine_name].time) / max_rate95)|round(3) }})" class="stacked-bar-chart-rate80"></span>{{- "" -}}
./oscar/preferences.html:31:        <span style="width: calc(100%*{{ ((stats[engine_name].rate95 - stats[engine_name].rate80) / max_rate95)|round(3) }})" class="stacked-bar-chart-rate95"></span>{{- "" -}}
./oscar/preferences.html:284:                                    <th scope="col" style="width: 10rem">{{ _("Selected language") }}</th>
./oscar/preferences.html:285:                                    <th scope="col" style="width: 10rem">{{ _("SafeSearch") }}</th>
./oscar/preferences.html:286:                                    <th scope="col" style="width: 10rem">{{ _("Time range") }}</th>
./oscar/preferences.html:288:                                    <th scope="col" class="text-right"  style="width: 7rem">{{ _("Max time") }}</th>
./oscar/preferences.html:289:                                    <th scope="col" class="text-right" style="width: 7rem">{{ _("Reliablity") }}</th>
./oscar/result_templates/default.html:19:        <img src="{{ image_proxify(result.img_src or result.thumbnail) }}" title="{{ result.title|striptags }}" style="width: auto; max-height: 60px; min-height: 60px;" class="col-xs-2 col-sm-4 col-md-4 result-content">
./oscar/result_templates/map.html:64:        <div style="height:300px; width:100%; margin: 10px 0;" id="osm-map-{{ index }}"></div>
./oscar/result_templates/files.html:24:<img src="{{ image_proxify(result.img_src) }}" alt="{{ result.title|striptags }}" title="{{ result.title|striptags }}" style="width: auto; max-height: 60px; min-height: 60px;" class="col-xs-2 col-sm-4 col-md-4 result-content">
./simple/preferences.html:39:<td class="{{ label }}" style="padding: 2px; width: 13rem;">{{- "" -}}
./simple/preferences.html:43:        <span style="width: calc(max(2px, 100%*{{ (stats[engine_name].time / max_rate95)|round(3) }}))" class="stacked-bar-chart-median"></span>{{- "" -}}
./simple/preferences.html:44:        <span style="width: calc(100%*{{ ((stats[engine_name].rate80 - stats[engine_name].time) / max_rate95)|round(3) }})" class="stacked-bar-chart-rate80"></span>{{- "" -}}
./simple/preferences.html:45:        <span style="width: calc(100%*{{ ((stats[engine_name].rate95 - stats[engine_name].rate80) / max_rate95)|round(3) }})" class="stacked-bar-chart-rate95"></span>{{- "" -}}
./simple/preferences.html:77:    <div class="engine-tooltip" style="right: 12rem;" role="tooltip" id="{{engine_name}}_reliability">
./simple/preferences.html:258:     <p class="text-muted" style="margin:20px 0;">
./simple/result_templates/map.html:65:    <div id="result-map-{{ index }}" class="invisible"><div id="osm-map-{{ index }}" style="height:300px; width:100%; margin: 10px 0;" ></div></div>
```

Related: 70cc196

**Comment by return42** [comment]
pew .. I tried to make the `stats.html` templates from _oscar & simple_ more CSP compliant, but after 3h I gave up .. for this it is necessary to completely redesign the layouts of the _new_ `stats/` and there are quirks like the calculated bar which is hard to implement CSP compliant:

https://github.com/searxng/searxng/blob/332e3a2a09d6a708ea2c17d2e731335b051c45aa/searx/templates/simple/stats.html#L57-L58

and the convolution of the table is hard for me to imagine ..

https://github.com/searxng/searxng/blob/332e3a2a09d6a708ea2c17d2e731335b051c45aa/searx/templates/simple/stats.html#L108-L126

@dalf: if you have time, could  you have a look at?

**Comment by dalf** [comment]
About
>  `<span style="width: calc(max(2px, 100%*{{ (engine_stat.http / engine_stats.max_time )|round(3) }}))" class="stacked-bar-chart-serie1"></span>{{- "" -}}`

[`attr()`](https://developer.mozilla.org/en-US/docs/Web/CSS/attr()) doesn't work because it will define the width property not the content.

[CSS3 variables](https://css-tricks.com/css-attr-function-got-nothin-custom-properties/#you-know-what-can-pass-any-sort-of-value-and-is-equally-easy-to-implement-as-attributes) requires to use the `style` attribute.

A [jsfiddle](https://jsfiddle.net/dalf73/te6gk18p/49/)

---

So, perhaps a solution: add a new `/stats.css` URL which provides the right CSS rendered from the server, then `/stats` references `/stats.css`.

---

It is related to the CSP header: if it is generated from the server (not hard coded in the reverse proxy), we can:
* set a very restrictive configuration on the result page, but (debatable choice) dynamically allow the [`embedded_url`](https://github.com/searxng/searxng/blob/332e3a2a09d6a708ea2c17d2e731335b051c45aa/searx/engines/peertube.py#L55-L60) from the engines (if there are no peertube results, then the `peer.tube` host won't be included in the CSP header). 
* set a different configuration on the `/stats` page which allow the `style` element with a [nonce](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#other_values) uniquely generated for each page.

In this scenario, the `/stats` page uses a `style` element to define CSS variables, then the CSS from the themes uses these variables.

Disclaimer: it is after reading your comment that I remembered the nonce and CSP...

**Comment by return42** [comment]
> So, perhaps a solution: add a new /stats.css URL 

Hmm .. personally I do not like generic CSS.  I would prefer a solution like [ _percentage_ classes](https://html-css-js.com/?html=%3C!doctype%20html%3E%0A%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3Cstyle%20type=%22text/css%22%3E%0A%20%20%20%20%3C/style%3E%0A%20%20%3C/head%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Cdiv%20class=%22graph%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar20%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar40%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar60%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar80%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar100%22%3E%3C/div%3E%0A%20%20%20%20%3C/div%3E%0A%20%20%3C/body%3E%0A%3C/html%3E%0A%0A&css=/*%20CSS%20styles%20*/%0A%20%20%20%20%20%20.graph%20%7B%20wi$*$dth:%20300px;%20%7D%0A%20%20%20%20%20%20.bar%20%7B%0A%09%20%20border:%203px%20soli$*$d%20seagreen;%0A%09%20%20margin:%201px%200;%0A%09%20%20clear:%20both;%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20.bar20%20%20%7B%20wi$*$dth:%2020%25;%20%7D%0A%20%20%20%20%20%20.bar40%20%20%7B%20wi$*$dth:%2040%25;%20%7D%0A%20%20%20%20%20%20.bar60%20%20%7B%20wi$*$dth:%2060%25;%20%7D%0A%20%20%20%20%20%20.bar80%20%20%7B%20wi$*$dth:%2080%25;%20%7D%0A%20%20%20%20%20%20.bar100%20%7B%20wi$*$dth:%20100%25;%20%7D%0A%20%20&js=)

```html
<!doctype html>
<html>
  <head>
    <style type="text/css">
      .graph { width: 300px; }
      .bar {
	  border: 3px solid seagreen;
	  margin: 1px 0;
	  clear: both;
      }
      .bar20  { width: 20%; }
      .bar40  { width: 40%; }
      .bar60  { width: 60%; }
      .bar80  { width: 80%; }
      .bar100 { width: 100%; }
    </style>
  </head>
  <body>
    <div class="graph">
      <div class="bar bar20"></div>
      <div class="bar bar40"></div>
      <div class="bar bar60"></div>
      <div class="bar bar80"></div>
      <div class="bar bar100"></div>
    </div>
  </body>
</html>

```

**Comment by dalf** [comment]
I guess, in your example, the style goes into searx.min.css, so it can be generated using a less loop: https://lesscss.org/features/#mixins-feature-loops-feature

Then it depends on which precision we want to display.

---

Alternative: the embedded CSS can be very simple using [CSP nonce and CSS variables](https://html-css-js.com/?html=%3C!doctype%20html%3E%0A%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3C!--%20Content-Security-Policy:%20...%20style-src%20'nonce-8IBTHwOdqNKAWeKl7plt8g=='%20...%20--%3E%0A%20%20%20%20%3Cstyle%20type=%22text/css%22%20nonce=%228IBTHwOdqNKAWeKl7plt8g==%22%3E%0A%20%20%20%20%20%20.bar_a%20%7B%20--value:%2040%25%20%7D%0A%20%20%20%20%20%20.bar_b%20%7B%20--value:%2060%25%20%7D%0A%20%20%20%20%20%20.bar_c%20%7B%20--value:%2080%25%20%7D%0A%20%20%20%20%20%20.bar_d%20%7B%20--value:%2030%25%20%7D%0A%20%20%20%20%20%20.bar_e%20%7B%20--value:%2020%25%20%7D%0A%20%20%20%20%3C/style%3E%0A%20%20%3C/head%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Cdiv%20class=%22graph%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar_a%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar_b%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar_c%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar_d%22%3E%3C/div%3E%0A%20%20%20%20%20%20%3Cdiv%20class=%22bar%20bar_e%22%3E%3C/div%3E%0A%20%20%20%20%3C/div%3E%0A%20%20%3C/body%3E%0A%3C/html%3E%0A&css=/*%20CSS%20styles%20*/%0A%20%20%20%20%20%20.graph%20%7B%20%0A%20%20%20%20%20%20%20%20wi$*$dth:%20300px;%20%0A%20%20%20%20%20%20%20%20border:%201px%20soli$*$d%20black;%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20.bar%20%7B%0A%09%20%20%20%20border:%203px%20soli$*$d%20seagreen;%0A%09%20%20%20%20margin:%201px%200;%0A%09%20%20%20%20clear:%20both;%0A%20%20%20%20%20%20%20%20wi$*$dth:%20var(--value);%0A%20%20%20%20%20%20%7D%0A%20%20&js=)

**Comment by return42** [comment]
I would vote for a less loop.

**Comment by dalf** [comment]
Notes:
* the images are resized using the style attribute: https://github.com/searxng/searxng/blob/9ef7f38e4f20bad5a76867aa3e5049a92bc58e59/searx/static/themes/__common__/js/image_layout.js#L63-L72
* leaflet uses the style attribute too.
