### ISSUE TITLE
search bar hidden, after search with safari 

### ISSUE THREAD

**Issue by theeddie** [searxng/searxng#579]
![image](https://user-images.githubusercontent.com/11677311/144666283-030f3dec-d8ce-44c9-aa17-7f501f381121.png)

**Comment by tiekoetter** [comment]
This was initially fixed in issue #323

**Comment by dalf** [comment]
@theeddie which version of Safari are you using ?

Is the simple theme suitable for you?

**Comment by theeddie** [comment]
15.1

I haven't tried simple, i  actually have it disabled. 

I have tried it on a few other instances including paul and they all have the issue 

![image](https://user-images.githubusercontent.com/11677311/144675128-e863b6eb-d8cd-4438-97ed-3edc05b232e7.png)

**Comment by dalf** [comment]
Can you try the code from this branch : https://github.com/dalf/searxng/tree/oscar-safari ?
