### ISSUE TITLE
Bug: yggtorrent engine ( Suspended: access denied )

### ISSUE THREAD

**Issue by jydhthrshrhty** [searxng/searxng#580]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 1.0.0-1246-10968a7f

**Comment by tiekoetter** [comment]
It is probably just my instance getting blocked. I will take a look and report back if it isn't a problem of my instance. For the time being you can try another public instance.

**Comment by return42** [comment]
A can confirm this issue: in a `make run` instance a `!yggtorrent ..` is blocked.

**Comment by jydhthrshrhty** [comment]
Qny instance will do the de
Same

**Comment by tiekoetter** [comment]
I can now also confirm that this happens with a fresh install.

**Comment by return42** [comment]
I had a short look: There is a cloudflare wall in front of https://www3.yggtorrent.nz doing some redirects to set cookies .. I don't know how to get around.

When I disable cookies in my browser the page stops at:

![image](https://user-images.githubusercontent.com/554536/144704511-38c3a62e-ce28-4230-8bb9-6d12027b7cbc.png)

**Comment by dalf** [comment]
The DNS configuration of ygg has changed 3 days ago, all public instances are blocked.
I guess we can remove the engine.
