### ISSUE TITLE
If possible please add lbry or odysee on it

### ISSUE THREAD

**Issue by arsg0etia** [searxng/searxng#590]
Thanks in advance.
LBRY is a blockchain-based file-sharing and payment network that powers decentralized platforms, primarily social networks and video platforms. LBRY's creators also run Odysee, a video-sharing website that uses the network.

**Comment by unixfox** [comment]
Useful info: https://github.com/TeamNewPipe/NewPipeExtractor/issues/434#issuecomment-719995735

**Comment by davidcollini** [comment]
I was just about to suggest this feature aswell, since right now I only filter youtube for the videos tab

**Comment by return42** [comment]
@arsg0etia today we merged the odysee engine 

- https://github.com/searxng/searxng/pull/2656

**Comment by Bnyro** [comment]
I think this issue could be closed now, I don't think there are any other widely used use cases for LBRY than Odysee, which could be used for searching.
