### ISSUE TITLE
Better Doc Navigation / Maybe new SearXNG doc theme and URL?

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#635]
**Is your feature request related to a problem? Please describe.**

Right now the navigation in our doc does not show all available pages, but rather only the next page after a current page and the previous one as well as where the page is located in the directory tree. This makes it hard IMO to find a resource, since a user always needs to go back to https://searxng.github.io/searxng/ to find the right resource.

**Describe the solution you'd like**

Have a navigation like https://doc.traefik.io/traefik/ (on the left) or rather have the overview of https://searxng.github.io/searxng/ as navigation on the left.

**Describe alternatives you've considered**

Maybe add a navigation manually if it cannot be generated by the theme?

**Additional context**

Ping @return42 @not-my-profile

**Comment by mrpaulblack** [comment]
(Also: https://searxng.github.io/ returns a 404 instead of redirecting to https://searxng.github.io/searxng);

Maybe its better to have the doc root on https://searxng.github.io/?

**Comment by return42** [comment]
> Maybe its better to have the doc root on https://searxng.github.io/?

AFAIK it is not possible to use [github pages](https://docs.github.com/en/pages) in that way / you can add documentation only on the project level not on the group level.

> Maybe add a navigation manually if it cannot be generated by the theme?

AFAIK the [Pallets-Sphinx-Themes](https://github.com/pallets/pallets-sphinx-themes) we use did not offer such a navigation bar.

I know that the [Read the Docs Sphinx Theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/) has a navigation bar. I used the RTD theme over years but was not very happy with / IMO the RTD theme is a little bit bloody.  That was the reason why I chose the [Pallets-Sphinx-Themes](https://github.com/pallets/pallets-sphinx-themes) which is more lightweight and uncluttered.

What I also miss is a dark/light mode switch for the theme, I tested https://github.com/pallets/pallets-sphinx-themes/issues/48 but this PR needs a lot more work.

May be we should consider to look forward for a theme that supports mode switch and navigation bar (I have not had time for this yet).

**Comment by dalf** [comment]
> Maybe its better to have the doc root on https://searxng.github.io/?

> AFAIK it is not possible to use github pages in that way

untested solution:

* We can create the searxng.github.io project : https://github.com/searxng/searxng.github.io
* Create a GH API token in this project
* Store a token as a secret in searxng/searxng
* Adjust this section : https://github.com/searxng/searxng/blob/56f68a1c29f0639da35aedefc5d7083f4c3da496/.github/workflows/integration.yml#L82-L91 (perhaps just specify the TOKEN is enough)

**Comment by mrpaulblack** [comment]
What about a custom URL? I already bought https://searxng.com a while ago and pointed it to the docs or we could use something like https://searxng.org... The deployment would not be with github pages in that case tho (I don't think they support custom URLs), but rather one of us hosting the docs on their stack... (like with searx.space)

[EDIT] also since the project is relatively new we have the freedom of choosing whatever name fits best...

**Comment by not-my-profile** [comment]
I think a custom domain is a good idea since it makes the project website independent of GitHub/Microsoft. Regarding TLDs I consider `.org` to be generally more fitting for a non-commercial open source project than `.com`.

**Comment by mrpaulblack** [comment]
I bought .com .net and .org just in case :upside_down_face:

**Comment by dalf** [comment]
I vote for searxng.org

* we can use the GitHub page: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
* or our own host (searx.space VPS can host the content for example).

**Comment by return42** [comment]
> I vote for searxng.org

Me too, but we should discuss deployment on another issue .. this issue is about doc-navigation and the sphinx-theme we should use.

Does anyone have suggestions about other sphinx-themes that fit our needs:

- navigation bar
- dark/light mode
- ????

**Comment by mrpaulblack** [comment]
Same I also like searxng.org; We could use searxng.net for backend stuff, when something comes up and searxng.com so nobody can impersonate the project with a common tld...

**Comment by dalf** [comment]
> this issue is about doc-navigation and the sphinx-theme we should use.

What about https://pradyunsg.me/furo/ ?

**Comment by return42** [comment]
> What about https://pradyunsg.me/furo/ ?

Thanks! / LGTM .. I will give it a try and send a DRAFT / more suggestions also welcome ..

**Comment by dalf** [comment]
I forgot this about furo: 
* https://github.com/encode/httpcore/pull/285 <-- add Sphinx + Furo
* https://github.com/encode/httpcore/pull/420 <-- replace by Mkdocs (I think the code will be merged into httpx which uses Mkdocs)

**Comment by dalf** [comment]
Another theme: 
* https://github.com/executablebooks/sphinx-book-theme
* https://sphinx-book-theme.readthedocs.io/en/stable/customize/index.html

**Comment by return42** [comment]
FYI: the [Sphinx Themes Gallery](https://sphinx-themes.org/) has collected most of the common known themes.

A preview of sphinx-book-theme: https://sphinx-themes.org/sample-sites/sphinx-book-theme/

I can give sphinx-book-theme a try, but I see some of our requests not answered (e.g. dark-mode)

IMO the table representation is poor https://sphinx-themes.org/sample-sites/sphinx-book-theme/kitchen-sink/tables/

My 2cent: what me bothers most often is the "sans serif" font in the float text.  If there is a wish list I would wrote on it to have "serif" in the float text and "sans" in the navigation elements and I like to have dark/light modes. .. But sadly I have never seen a theme that fulfills all my wishes ..

---

EDIT: I am coming from LaTeX where some guys teach me some essentials about typography .. perfect layouts for books and white-papers .. never seen "sans" in literature ..

**Comment by return42** [comment]
I have tested several Sphinx themes and I always look out for new themes to test.

The Pocoo-Theme (the one we use) is the most elaborated theme, which also meets the most diverse requirements that go beyond a "test suite".  Even if it lacks nice features like a light/dark mode, its layout is stable and consistent in all projects I know.

I am going to close this issue / an optional theme alternative should be discussed in a dedicated issue. 

----

Update: started new discussion in ..

- https://github.com/searxng/searxng/pull/3408
