### ISSUE TITLE
whaleslide.com is dead

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#639]
Added half a year ago in #178 (from https://github.com/searx/searx/pull/2861) the website (both https://whaleslide.com/ and  https://search.whaleslide.com) appear to be completely offline. Should we just remove it from `settings.yml`?

**Comment by return42** [comment]
Hm, from my side, we can drop it / may be it is temporary offline? .. no tweet about offline/dead: https://twitter.com/whaleslide
