### ISSUE TITLE
Group engines in preferences by enabled / disabled

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#642]
**Is your feature request related to a problem? Please describe.**

A long page with many toggle buttons is bad for UX because it's not easy to see which engines are enabled / disabled.

![image](https://user-images.githubusercontent.com/73739153/147100421-ec081185-8ac0-4aff-abdc-ae08ac4767ab.png)

**Describe the solution you'd like**
List enabled engines first, followed by the disabled engines.

**Comment by return42** [comment]
IMO alphabetic sort is what user do expect / may be I am wrong?

**Comment by not-my-profile** [comment]
I think there are two reasons a user might use that settings page:

1. To see which engines they have enabled. (This could be improved by grouping enabled engines first.)
2. To enable a disabled engine. (This would not become more difficult if enabled engines were grouped first.)

So if case 1 can be improved and case 2 stays the same I think we should introduce grouping.

I think it is generally common practice to group disabled options last (e.g. Firefox, Chrome and VS Code do it for extensions).

**Comment by return42** [comment]
I have no preference on the sort order ... let's hear what others say.

**Comment by dalf** [comment]
I'm not sure to follow:
* Engines are enabled by default, some are disabled in `settings.yml`. These are only the default settings.
* When the users goes into the preferences, they can enable / disable engines at will (this is the "Allow" column, which should be named "Enabled").
* They can also call some engines directly: for example `!apkmirror time` (even if the engine is disabled).

IMO:
* So if the engines are grouped by enabled / disabled, when the user enables an engine, the engine has to change group. It will be disturbing.
* The "Engines" tab is a way to discover and define the engines. So what could be added is a way to sort the engines., or some filters, but this is another issue.

**Comment by not-my-profile** [comment]
>So if the engines are grouped by enabled / disabled, when the user enables an engine, the engine has to change group. It will be disturbing.

It does not have to switch group immediately it can switch group when you re-open the tab. This is also how Firefox, Chrome and VS Code do it ... it's well established practice.

**Comment by return42** [comment]
With arguments from @dalf in mind I think it is better we stay with alphabetic order .. I think there are things we can improve about the UX that will have a greater effect with less effort.

**Comment by not-my-profile** [comment]
> I think there are things we can improve about the UX that will have a greater effect with less effort.

Of course but that to me doesn't mean we shouldn't do this. Small details like this matter for a polished UX.

**Comment by return42** [comment]
AFAIK this "feature" will need to touch the JS Client, the templates and the python code and the profit is questionable. Some users will like it, others not .. my time is limited, I'm out / sorry.

**Comment by not-my-profile** [comment]
I opened this issue because I felt that the engine tables in the preferences lacked grouping, so I suggested grouping by enabled/disabled. But I have since had a better idea: grouping them by subcategory, and I implemented that in my PR #634.

So I'm closing this in favor of #634.
