### ISSUE TITLE
Issues: labels

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#647]
Which labels do we need to add or rename ?

Currently:
https://github.com/searxng/searxng/labels

May be this issue has more this place in the chat.

**Comment by dalf** [comment]
To start : `enhancement` is somewhat generic, it can be renamed `new feature`

**Comment by return42** [comment]
IMO "good first issue" and "javascript" can be removed.

**Comment by not-my-profile** [comment]
`enhancement` has been renamed and `javascript` has been removed. We should probably keep `good first issue` since GitHub has a mechanism to promote these issues. Closing this for now.
