### ISSUE TITLE
docker environment variable INSTANCE_NAME not work due to wrong default instance name assumption

### ISSUE THREAD

**Issue by contrun** [searxng/searxng#65]
We substitute instance name with environment variable INSTANCE_NAME here https://github.com/searxng/searxng/blob/332e3a2a09d6a708ea2c17d2e731335b051c45aa/dockerfiles/docker-entrypoint.sh#L70-L74, which assumes the default configuration has line containing `instance_name : "searx" `. This is not true for searxng https://github.com/searxng/searxng/blob/332e3a2a09d6a708ea2c17d2e731335b051c45aa/searx/settings.yml#L3. I think it is very brittle to use sed to substitute yaml file. Can we use something like [yq](https://github.com/kislyuk/yq) to update `settings.yml`. This allows users to update more configurations in a more general and more reliable way.

**Comment by return42** [comment]
@contrun thanks for your issue .. should be fixed in b46a3ec

> I think it is very brittle to use sed to substitute yaml file.

In general I would say you are right, but when it comes to _installation procedures_ it is most often simpler or even better to use _existing_ tools, instead to have install prerequisites before the _installation procedure_ can start.
