### ISSUE TITLE
How to disable stats of SearXNG in docker ?

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#657]
Hi,
i would like to disable the stats of my SearXNG instance using docker since it's set by default.
Thanks !

**Comment by tiekoetter** [comment]
Have you tried setting `enable_stats` to `false` in settings.yml?

**Comment by ghost** [comment]
> Have you tried setting `enable_stats` to `false` in settings.yml?

yes but @dalf approved that this env settings wasn't supported.

**Comment by dalf** [comment]
> Have you tried setting enable_stats to false in settings.yml?

I confirm this is not implement.
Implemented in https://github.com/dalf/searxng/tree/settings_enable_stats (this is a draft, it is going to be a PR when it is ready).
