### ISSUE TITLE
Broken links (to example.org) in official documentation

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#659]
The documentation links example searches like `` :search:`query` ``. `conf.py` however fallsback to `example.org`:

https://github.com/searxng/searxng/blob/6ffa741e7a739a8b7df210054300dda8c33d75b7/docs/conf.py#L17

Users clicking on those links will be confused.

**Comment by return42** [comment]
It is not a bug / its a feature ;)

At SearXNG we do not recommend a instance (URL), but instance maintainer can build their own documentation in which the `server.base_url` will be used.

**Comment by not-my-profile** [comment]
I did not say we have to recommend an instance. I am just saying we shouldn't have broken links in our documentation.

I see two possible solutions:

* Somehow turning the `:search:` links into plain text in the official documentation.
* Somehow linking it to `searx.space` so that you can then select one of the instances.

>instance maintainer can build their own documentation

You said yourself that many instances don't do that.

Broken links are always bugs, so please reopen this :)
