### ISSUE TITLE
Allow all/Disable all buttons also toggle engines in other tabs

### ISSUE THREAD

**Issue by rmlrml** [searxng/searxng#660]
I don't have it installed, I'm just a user of other people's searx and searxng instances.

I see a lot of different instances because I have my default search in Firefox set to the Random Searx Redirector at searx.neocities.org.

Whether a searx or searxng instance, any version, when you click the "Allow all" or "Disable all" buttons in the Engines tab of Preferences, it not only flips all the toggle switches under the Engines tab, but all the toggle switches in the General, Plugins, User Interface, Privacy, and Special Queries tabs too.

I don't think it should do that, as the "Allow all" and "Disable all" buttons are only present under the Engines tab which seems to indicate that they should only apply to the engines in the Engines tab.

**Comment by return42** [comment]
I recommend to use simple theme .. at some point in the (near) future we will drop oscar theme / I do not know if it still makes sense to fix these issues in oscar .. especial since you are the first one who recognized this issue which has overlooked over years :-)

**Comment by dalf** [comment]
The buttons exist only in the Oscar theme, but IMO, it makes sense to have them in the Simple theme

Related issues in searx:
* https://github.com/searx/searx/issues/45 
* https://github.com/searx/searx/pull/1979

<sub>(I've noticed the issue but I haven't opened an issue).</sub>

**Comment by rmlrml** [comment]
Yes I like being able to disable all and then just select the ones I want, can't do that in the Simple theme.
