### ISSUE TITLE
PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by HLFH** [searxng/searxng#662]
Repo: https://github.com/dalf/searxng
Branch: upgrade-httpx > https://github.com/dalf/searxng/tree/upgrade-httpx
Last commit of this branch.
Related to: https://github.com/searxng/searxng/pull/596

```
déc. 27 17:24:10 arch-server uwsgi[2672526]: 2021-12-27 17:24:10,806 ERROR:searx: Error while getting the version: fatal: not a git repository (or any of the parent directories): .git
déc. 27 17:24:10 arch-server uwsgi[2672526]: 2021-12-27 17:24:10,813 ERROR:searx: Error while getting the git URL & branch: fatal: not a git repository (or any of the parent directories): .git
```
What shall I do on this one?

```
déc. 27 17:24:11 arch-server uwsgi[2672526]: 2021-12-27 17:24:11,865 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
déc. 27 17:24:11 arch-server uwsgi[2672526]: cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
```
Scheduler is enabled in `/etc/searxng/settings.yml` and requested config line is in `/etc/uwsgi/vassals/searxng.ini `. 
What shall I do more on this one? 

EDIT: 

```
python -m searx.version freeze
```

To fix the first issue.

**Comment by HLFH** [comment]
cc @dalf 

How to fix the `uwsgi.ini configuration error` issue?

**Comment by dalf** [comment]
I can't figure out why there is a new error.

Can you try https://github.com/dalf/searxng/tree/test-uwsgi ?
This is the master branch + upgrade-httpx + small change to log the uwsgi exception (in addition to the existing generic message).

After running the server, uwsgi.ini should contain a more useful message.

**Comment by HLFH** [comment]
```
déc. 28 11:03:55 arch-server uwsgi[1731476]: 2021-12-28 11:03:55,287 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
déc. 28 11:03:55 arch-server uwsgi[1731476]: cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
déc. 28 11:03:55 arch-server uwsgi[1731476]: Traceback (most recent call last):
déc. 28 11:03:55 arch-server uwsgi[1731476]:   File "/usr/lib/python3.10/site-packages/searx/shared/__init__.py", line 16, in <module>
déc. 28 11:03:55 arch-server uwsgi[1731476]:     uwsgi.cache_update('dummy', b'dummy')
déc. 28 11:03:55 arch-server uwsgi[1731476]: SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
déc. 28 11:03:58 arch-server uwsgi[1731476]: WSGI app 0 (mountpoint='') ready in 14 seconds on interpreter 0x55f54bef08d0 pid: 1731520 (default app)
```

The small change to log the uwsgi exception improves things ;)

```
➜  ~ python --version
Python 3.10.1
```

Linked to: https://bugs.python.org/issue40943

And linked to: https://github.com/unbit/uwsgi/pull/2363

uwsgi 2.0.21 has to be released to fix it.

**Comment by dalf** [comment]
I'm not sure how to fix this issue: will the issue be fixed with the version 2.0.21 of uwsgi archlinux package?

https://pypi.org/project/uWSGI/#history doesn't show the version 2.0.21

**Comment by HLFH** [comment]
@dalf As the PR https://github.com/unbit/uwsgi/pull/2363 has been merged, they need to release the next version of uwsgi which would be 2.0.21. And it would fix this https://github.com/searxng/searxng/issues/662 issue.

**Comment by HLFH** [comment]
@dalf I fixed `version_frozen.py` with the updated PKGBUILD of [searxng-git](https://aur.archlinux.org/packages/searxng-git/) on the AUR.
I submitted [uwsgi-ng](https://aur.archlinux.org/packages/uwsgi-ng/), which is uwsgi 2.0.20 with the Python 3.10 patch.
searxng-git depends now from uwsgi-ng and uwsgi-ng-plugin-python, and no longer from the broken uwsgi* packages.

**Comment by return42** [comment]
Wow, thanks a lot / just want to leave a link to the patch: https://aur.archlinux.org/cgit/aur.git/log/?h=uwsgi-fix

**Comment by HLFH** [comment]
Update: [uwsgi](https://archlinux.org/packages/community/x86_64/uwsgi/) on [community] now contains the Python 3.10 patch.
