### ISSUE TITLE
Bug: wikipedia engine

### ISSUE THREAD

**Issue by danass** [searxng/searxng#669]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('400', 'Bad Request', 'en.wikipedia.org')`
  * File name: `searx/engines/wikipedia.py:70`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by not-my-profile** [comment]
Does this still happen for you?

**Comment by return42** [comment]
I close the issue / the form has not been filled in. @danass if you have more informations ask for reopen.
