### ISSUE TITLE
Can i redirect youtube to invidious by default in searxng ?

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#678]
Hi,
i would like to know (if it's possible) what do i have to add to my /searxng/settings.yml to redirect youtube to invidious or reddit to libreddit etc... ?
thanks.

**Comment by return42** [comment]
https://github.com/searxng/searxng/blob/c2e4b95e8d68ac151d51fbcd3f0875f2aaa3640f/searx/settings.yml#L176-L186

and activate ""Hostname replace" plugin.
