### ISSUE TITLE
`categories_as_tabs` followups

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#690]
This is a follow up issue for #634, which introduces categories that are not displayed as tabs and only searchable via bangs.

* [ ]  #769
* [x] fix obvious UX problems
    * [x] #702
    * [x] #854
* [x] #722
* [x] Document "How to search"
* [x] Document how to categorize engines.
    * https://github.com/searxng/searxng/pull/1545
* [x] Make "non tab category" bangs discoverable.
  Maybe by updating the autocompletion so that `!` lists the available category bangs and their descriptions / drawback: not all have autocompletion and it requires JS on the client
    * categories are in the autocompletion
    * !bangs are shown in the preferences https://github.com/searxng/searxng/pull/1545
* [x] Introduce `category_labels` with a custom babel extractor to get rid of hardcoded `gettext` calls in `webapp.py`
    * https://github.com/searxng/searxng/pull/859
* [ ] Stop hardcoding icons in the Simple theme (`searx/templates/simple/categories.html`), define them in `categories_as_tabs` in `settings.yml` instead
* [x] Display country flags for language codes in preferences (e.g. DE -> :de:, PL -> :poland:)
* [ ] Introduce `about.powered_by` and group preference tabs by it

**Comment by return42** [comment]
AFAI can say this issue can be closed / if not, ask for reopening.
