### ISSUE TITLE
Bug: startpage engine does not show any results

### ISSUE THREAD

**Issue by Stratos42** [searxng/searxng#692]
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1392-00d3a747

**How did you install SearXNG?**
 searxng-docker

**What happened?**
The startpage engine returns no results (but no specific error message)

**How To Reproduce**
!sp test 

I have tried on other instances (older or even searx instances) and I get the same thing. Maybe a change on the startpage side that prevents parsing the results?

**Comment by not-my-profile** [comment]
I cannot reproduce this. `!sp test` works as expected for me (running the latest master locally).

**Comment by mrpaulblack** [comment]
broken in my fork rn: `https://paulgo.io/search?q=%21sp%20test&language=en-US&time_range=None&safesearch=1&categories=none` But there is no error log in `/var/log/uwsgi/uwsgi.log`, same for https://searx.be and https://searx.tiekoetter.com/search?q=%21sp+time

[EDIT] but it works locally... Maybe they shadow banned IPs of public instances or something?

**Comment by return42** [comment]
BTW: [Startpage is owned by an advertising company](https://restoreprivacy.com/startpage-system1-privacy-one-group/) 

> [EDIT] but it works locally.

really .. may be you tracked already by startpage :footprints:

When I test `make run`, I got a redirect to a captcha .. I just wondering that they don't ask my Social Security Number.
 
![grafik](https://user-images.githubusercontent.com/554536/148196607-4b0bf076-d138-4054-84df-015af3f59088.png)

**Comment by dalf** [comment]
We can add a `raise_for_startpage_captcha` function to this existing list : https://github.com/searxng/searxng/blob/00d3a7477c01981a6ef2d396332670ad5b831fa6/searx/network/raise_for_httperror.py#L47-L49

**Comment by return42** [comment]
> We can add a `raise_for_startpage_captcha` function to this existing list

Thanks / I will have a look .. if there is no way around captcha, I will add startpage to the list.

**Comment by Stratos42** [comment]
Hi,
I'm not sure if the problem is directly related to a captcha (at least not in my case).

It's only a hypothesis but when I use startpage.com directly I see some kind of latency when loading the results. I wonder if this does not affect the retrieval of results by SearxNG.

**Comment by return42** [comment]
@Stratos42 thanks for your additional notes. It seems that startpage changed their API and I suppose this is the reason why we get a captcha.

I send https://github.com/searxng/searxng/pull/695 .. do you have time to test?

**Comment by Stratos42** [comment]
Test OK!
It seems to work perfectly, thank you!

**Comment by return42** [comment]
@Stratos42 thanks for your test / I will wait to merge PR until one of the SearXNG member approved it.
