### ISSUE TITLE
Autocomplete results are not clickable on mobile

### ISSUE THREAD

**Issue by xiaoyong-wang** [searxng/searxng#693]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 searxng 1.0.0

**How did you install SearXNG?**
I used the official wiki/docs

**What happened?**
When you open a SearXNG instance on mobile (I used searx.be), using the "simple" theme/template, and start typing into the search box, you are not able to click/tap any autocomplete results. If you tap one, the autocomplete menu simply closes.

**How To Reproduce**
Open a web browser on your smartphone (I am using Bromite on Android), start typing something in the search box (for example, "Linus"), and try clicking/tapping one of the options displayed in the autocomplete menu which pops up (you must have autocomplete enabled).

**Expected behavior**
When tapping an option/result in the autocomplete menu on mobile, you should be redirected to begin the search for the term you chose.

**Screenshots & Logs**
![Screenshot_two](https://user-images.githubusercontent.com/54741819/148147716-cf9ddeb6-983c-4ba4-a937-0fe7082d0626.png)
![Screenshot_1](https://user-images.githubusercontent.com/54741819/148147722-92983471-10fa-4bf9-95f0-b2231828ed4a.png)

**Additional context**

**Comment by xiaoyong-wang** [comment]
Update: The same issue appears to occur on desktop as well.

**Comment by tiekoetter** [comment]
Related to https://github.com/searxng/searxng/issues/542

**Comment by not-my-profile** [comment]
Yes this issue is a duplicate of #542 (the bug apparently occurs on all browsers).

Until this is fixed you can use the Oscar theme as a workaround.
