### ISSUE TITLE
Add lemmy.ml

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#698]
**Working URL to the engine**

https://lemmy.ml

**Why do you want to add this engine?**

From https://join-lemmy.org/docs/en/index.html

> Lemmy is similar to sites like Reddit, Lobste.rs, Raddle, or Hacker News: you subscribe to forums you're interested in, post links and discussions, then vote, and comment on them. Behind the scenes, it is very different; anyone can easily run a server, and all these servers are federated (think email), and connected to the same universe, called the Fediverse.

TLDR : fediverse engine.

**Features of this engine**

**How can SearXNG fetch the information from this engine?**
https://lemmy.ml/post/89578

**Applicable category of this engine**
* social

**Additional context**

https://github.com/searx/searx/issues/2055

**Comment by allendema** [comment]
Some configs have been suggested there: https://lemmy.ml/post/89578
