### ISSUE TITLE
Make request parameters configurable for `json_engine` and `xpath`

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#701]
Somebody on IRC recounted that they tried to add a [Manticore](https://manticoresearch.com/) engine to their SearXNG instance using the `json_engine` but failed to do so because Manticore requires POST requests and `json_engine` apparently only supports GET requests.

Unless I'm missing something they're correct.  Looking into this I think the most elegant way to solve this is to allow overriding the [request `params`](https://docs.searxng.org/dev/engine_overview.html#specify-request) in the [engine settings](https://docs.searxng.org/admin/engines/settings.html#settings-engine), so e.g. something like:

```yml
- name: example engine
  engine: json_engine
  request_params:
    method: POST
```

To clarify this would work for any engine module: the specified request parameters would simply be applied as overrides just before sending the request (and could e.g. also be used to specify a specific HTTP header for an engine). The main appeal for this of course however is to allow `json_engine` and `xpath` engines that use `POST`.

(The exact config format is of course up to debate). What do you think?

**Comment by return42** [comment]
> To clarify this would work for any engine module: the specified request parameters would simply be applied as overrides just before sending the request (and could e.g. also be used to specify a specific HTTP header for an engine).

I think `methode` a good idea for the generic engines like XPath & JSON but won't work for all other engine modules.  Engine modules do define the query arguments in the URL (GET) or in the `data` segment (POST) and some of the engine modules need some HTTP `headers` quirks.

From the viewpoint of the engine-developer: having _general_ options in settings.yml that can break down the engine is not a good idea.  The implementation from a engine module has to decide what options from a settings.yml file should be applied and how to apply.

BTW: we also have [offline](https://docs.searxng.org/src/) engines like [SQL, NoSQL, Recoll ..](https://docs.searxng.org/admin/engines/)

>  The main appeal for this of course however is to allow `json_engine` and `xpath` engines that use `POST`.

:+1:

**Comment by not-my-profile** [comment]
>having general options in settings.yml that can break down the engine is not a good idea.

Good point. How about making `request_params` configurable only for `json_engine` and the `xpath` engine?

**Comment by return42** [comment]
> Good point. How about making `request_params` configurable only for `json_engine` and the `xpath` engine?

Sorry I was unclear: YES! :-)

**Comment by virtadpt** [comment]
While doing some experimenting I ran into something else - POSTs require a request body.  The parameters can't be passed as part of the URL.  searchd definitely doesn't support this.  Are there any other engines that do, or would this have to be retrofitted into the json_engine only?
