### ISSUE TITLE
`?` search syntax is broken

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#702]
The [user documentation says](https://docs.searxng.org/user/search_syntax.html):
  
>**Prefix: `?`**
>to add engines and categories to the currently selected categories

But to me it is unclear how it is different from the `!` bang syntax. The following queries all yield exactly the same results:

* `!bing test !images`
* `!bing test ?images`
* `?bing test !images`

Only `?bing test ?images` for some reason only yields images??? :confused: 

Can somebody explain to me why somebody would want to use `?` over `!`?

If there is no satisfying answer to that question, I vote that we remove (or at least deprecate) the `?` syntax.

**Comment by return42** [comment]
> But to me it is unclear how it is different from the `!` bang syntax. 

I have never used `?` but I assume the intention is **to add something to currently selected categories**

>>to add engines and categories to the **currently selected categories**

E.g. when you are in category "general" and you use `?images paris` you get results from the engines of categ "general" and categ "images" ..

This feature seems broken ... I don't know .. IMO we can remove this feature (I have never seen an issue about / seems no one use it).

**Comment by not-my-profile** [comment]
>E.g. when you are in category "general" and you use ?images paris you get results from the engines of categ "general" and categ "images" ..

Yes ... except that it doesn't work.

Searching for `?images paris` in the General tab does not yield any images for me. @dalf do you have some insight?

**Comment by return42** [comment]
> Searching for `?images paris` in the General tab does not yield any images for me.

That is what I mean / lets here what @dalf says.

**Comment by dalf** [comment]
The idea of `?` : you have a selected category (`general` for example), but you want to add an engine, let's say `wordnik` for example: you can type `?wordnik something` instead of `!general !wordnik something`. Then you select the images category with the tab, the search is going to include engines from the images category and wordnik (because the query is `?wordnik something`)

I can't find when it started not to work.

**Comment by not-my-profile** [comment]
Ok, I can see the appeal of the feature. Since it is currently completely broken, why don't we take the opportunity to change the syntax to something more intuitive? How about the following?

* `paris !images` searches for `paris` in the `images` category
* `paris +!images` searches for `paris` in the current categories plus the `images` category
* `paris -!images` searches for `paris` in the current categories minus the `images` category

I think it makes sense to handle this in two steps:

1. remove the broken `?` syntax as a bug fix
2. add the new syntax (`+!` and `-!`) as a new feature
