### ISSUE TITLE
404 pages on docs.searxng.org have broken CSS

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#703]
E.g. https://docs.searxng.org/not_found/

**Comment by return42** [comment]
@dalf @mrpaulblack should we handle 404 in the HTTP setup of docs.searxng.org?

I haven't tested but an alternative might be https://sphinx-notfound-page.readthedocs.io/en/latest/index.html

**Comment by return42** [comment]
@dalf @mrpaulblack  ping

**Comment by dalf** [comment]
* [https://docs.searxng.org/not_found](https://docs.searxng.org/not_found) is fine
* [https://docs.searxng.org/not_found/](https://docs.searxng.org/not_found/) is not

the issue is the relative reference to the static files. For example:
```html
<script src="_static/jquery.js"></script>
```

It should be
```html
<script src="/_static/jquery.js"></script>
```

Perhaps `conf.py` should have:
```python
html_static_path = ['/_static']  # add a slash
```

**Comment by return42** [comment]
> Perhaps `conf.py` should have:
> ```python
> html_static_path = ['/_static']  # add a slash
> ```

The meaning of `html_static_path` is different from what you assume, these are path names not URLs: 

[A list of paths that contain custom static files (such as style sheets or script files). Relative paths are taken as relative to the configuration directory. They are copied to the output’s _static directory after the theme’s static files, so a file named default.css will overwrite the theme’s default.css.](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_static_path)
