### ISSUE TITLE
`leaflet.js` files pollute `git grep <term> searx` searches

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#704]
I like to search our code with `git grep <term> searx` ... while my Git is clever enough to detect some of our vendored files as binary files, e.g:

```
Binary file searx/static/themes/oscar/img/searxng.svg matches
Binary file searx/static/themes/oscar/js/bootstrap.bundle.min.js matches
Binary file searx/static/themes/oscar/js/bootstrap.min.js matches
Binary file searx/static/themes/oscar/js/jquery.min.js matches
```

for some reason though `searx/static/themes/oscar/js/leaflet.js` is not detected as a binary file.

You can reproduce this by running `git grep zoom searx` in the root directory of the repository.

I'm using the latest Git 2.34.1.

**Comment by dalf** [comment]
related to https://github.com/searxng/searxng/blob/master/.gitattributes
