### ISSUE TITLE
[theme] hash-plugin: sha512 values overwrite the answers box

### ISSUE THREAD

**Issue by return42** [searxng/searxng#710]
Try search term `sha512 The quick brown fox`

![grafik](https://user-images.githubusercontent.com/554536/148404476-c69ee097-e0e4-4b16-95c1-e1c6d2e8ebf6.png)

**Comment by MontyQI** [comment]
It is because hashes are long. We should split it into pieces or find a way to render it correctly as one word.

**Comment by return42** [comment]
I think "overwrite" the answer box is an issue of the UI and needs to be rendered correctly .. in any way / I don't have a solution at hand right now (did not had time for).

**Comment by dalf** [comment]
With:
```css
#answers span {
  word-break: break-all;
}
```

![image](https://user-images.githubusercontent.com/1594191/150331084-2ef4d632-c14f-4e03-8857-a932853cc48d.png)

Notice how the line is broken:
![image](https://user-images.githubusercontent.com/1594191/150331263-5c423788-8572-4ef9-aa30-c65192fe4f92.png)

Following this idea, we need two different styles for the answers: text & code.
