### ISSUE TITLE
Method POST harms UX without providing a tangible privacy benefit

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#711]
In the preferences users can choose which HTTP method is used by the UI to perform searches: POST or GET. The setting defaults to POST.

## Privacy implications

POST has two privacy benefits:

1. the search query does not end up in the browser history
2. the search query does not end up in the web server log

I'd like to argue that both of these benefits are mostly superficial, because:

1. If you don't want your search queries to end up in your browser history, you should be using a private/incognito browser window. Because otherwise the search results you click on will end up in the browser history anyway, revealing what you have searched for.
2. There is nothing stopping a malicious server from logging search queries in POST request bodies. Either you trust the server admin or you don't. If you trust them, you should also be able to trust them to disable / periodically delete their web server logs. If you don't trust them, then they might log your every query even when you submit them using POST.

I think we should rather educate our users about the importance of private/incognito browser mode & trusting the server admin than giving them a false sense of security by using POST.

## UX implications

* **Open Link in New Tab** does not work for our search result tabs because they aren't actual links.
* **Bookmarking** a search becomes more difficult with POST. You cannot just press a browser keyboard shortcut `Ctrl+D` ... no you have to copy the Search URL from the sidebar. This can pose a real struggle for less technically-minded users.
* **Sharing** a search with somebody else becomes more difficult with POST (for the same reason).

## Conclusion

I think by using POST we are sacrificing our UX without actually getting any tangible privacy benefit.

I therefore propose that we should switch to GET by default. Since POST does not provide any real privacy benefit I think that we should remove the option.

**Comment by return42** [comment]
> I therefore propose that we should switch to GET by default. Since POST does not provide any real privacy benefit I think that we should remove the option.

additional note: I remember about some issues in the context of [browsers that support OpenSearch](https://github.com/searxng/searxng/issues/431)  .. if I'm not wrong POST is not supported by Chrome.

**Comment by unixfox** [comment]
While I agree that if a user wants to hide their search history they should use the incognito mode, and if a malicious instance owner really wants to log the search of their users he can log the POST body.

But the benefit of having POST method by default is that we conveniently offer a protection for the searx users without having them doing anything.
- By default, the search queries are not logged in the history.
- It's more time-consuming for instance owners to log the search queries.
- Whatever the web server configuration, the search queries keyword are not logged in the logs of the web server. This also offer the benefit of leaving no trace of the search queries done if an investigation would be done by external parties on the web server.

About the UX arguments:
- > Bookmarking a search becomes more difficult with POST.

  We could implement a button for that, an easy click for bookmarking on the browser.
- > Sharing a search with somebody else becomes more difficult with POST (for the same reason).

   The user can copy the link from `Search URL` in the bottom right corner.


So I'm quite reluctant to switch the default method to GET, mostly because I see more benefit to have POST method than the issues of having the POST method by default.

**Comment by not-my-profile** [comment]
>the benefit of having POST method by default is that we conveniently offer a protection for the searx users without having them doing anything

That is false. Defaulting to POST does not provide "protection".

>By default, the search queries are not logged in the [browser] history.

Which does not really help the user if the URLs of search results end up in the browser history when they click on them.

>It's more time-consuming for instance owners to log the search queries.

It takes an instance owner about **one minute** to add two lines to their NGINX config:

```
log_format post_logs '[$time_local] "$request" $status "$http_user_agent" [$request_body]';
access_log  /var/log/nginx/all-your-searx-queries.log post_logs;
```

(Note the `$request_body`). By spending one minute a malicious instance owner can log every single query to their Searx instance for years (or even decades) to come. It is foolish to think that any malicious actor will be deterred by having to add two lines to their configuration.

>Whatever the web server configuration, the search queries keyword are not logged in the logs of the web server. 

That is wrong. It's just the "default" web server config that doesn't log request bodies. As I explained in the previous paragraph adding two lines suffices to log every single query for every single user.

>We could implement a button for that, an easy click for bookmarking on the browser.

In fact we cannot. Browsers do not provide an API to websites to create bookmarks (for obvious reasons). We could only redirect the user to another URL ...  they then would still need a second click to bookmark the request. My point is that users are used to be able to create bookmarks straight via their browser UI / shortcut ... which will never work if we don't put the search query into the URL.

>The user can copy the link from Search URL in the bottom right corner.

Yes ... I didn't say it was impossible. I just said that it's more difficult ... which is kinda what UX is all about ... making things less difficult for the user.

Let me make my point clear one more time: Defaulting to POST does not provide any tangible protection. It does not really matter if search queries don't end up in the browser history, if the search results the user follows do. Logging every single search query sent using POST takes two lines of configuration ... that will not stop anybody.

So all my points still stand. I firmly believe that we should not mislead users into thinking that POST "provides protection".

**Comment by return42** [comment]
my 5cent about ..

> tangible protection

Over all I would agree with @not-my-profile / complete different example: requests to SearXNG instances hosted on cloudflare are also read-able by cloudflare itself.  What I mean: if we want to assure _privacy_ we should focus on methods which have tougher criterias, e.g warn about SearXNG instances hosted at cloudflare ;-)

**Comment by mrpaulblack** [comment]
I am not sure if its a good idea to use GET be default (and maybe even drop post completely) or if its better to keep POST as the default.

I mean on the one hand is it going to simplify SearXNG and you could argue that its easy to log search queries with GET as well as with POST, so the privacy benefit of using POST is really slim.
On the other hand is SearXNG the project about being a privacy focused search engines. Even if using POST requests has only the little benefit of search queries not getting logged in browser history, its still a benefit for the privacy of the end user (I mean yes they can use incognito tabs or something so the queries do not get logged by the browser, but I mean how many people are actually dialing driving their computer like this). And even if this is only a small benefit, it still is one. Removing POST or making GET default would IMO hurt the core reason why this repo exists.

But tbh I am not sure myself if it would be better to use POST or GET...?

**Comment by return42** [comment]
> Even if using POST requests has only the little benefit of search queries not getting logged in browser history, its still a benefit for the privacy of the end user ..

That is also true .. I don't know what is better .. there are _cons & pros_ .. I can't judge what is better :confused:

**Comment by not-my-profile** [comment]
Being able to save or share the page your currently viewing by copying its URL from the address bar is an important UX principle.

I don't think violating that principle is worth it for a very slim privacy benefit. We cannot protect users from their own browsing habits.

If users could easily share their SearXNG results that could also help SearXNG gain adoption (and thus improve the privacy of more people who previously used Google). (And no ... needing to change a preference or copy a value from some input on the page is neither obvious nor easy ... every deviation from default browser mechanisms is bad UX).

**Comment by return42** [comment]
> @mrpaulblack says: Even if using POST requests has only the little benefit of search queries not getting logged in browser history, 
> @not-my-profile says: copying its URL from the address bar is an important UX principle.

~Using the backward / forward button in the browser is also an important UX principle.  Its hard to explain uninitiated users why this basic feature does not work in SearXNG.~

**Comment by not-my-profile** [comment]
(slightly off-topic: back & forward buttons do actually also for me with SearXNG and POST)

**Comment by return42** [comment]
> slightly off-topic: back & forward buttons do actually also for me with SearXNG and POST)

Ooops .. seems related to my FFox setup.

**Comment by mrpaulblack** [comment]
We as SearXNG maintainers agreed that it is a good idea to keep POST requests around for the reasons mentioned above; Closing.
