### ISSUE TITLE
Don't change current language when searching for e.g. `:es`

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#720]
Searching for e.g. `:es gato` changes the default search language to Spanish so that e.g. subsequent searches for `cat` are also in Spanish. I think this is counter-intuitive ... when you remove the language code you expect to be back at your previous language. I think it would be better, if the default language would be preserved and something like "temporarily searching in Spanish" would be displayed.

This is important because users are likely to perform the majority of their searches in their mother language. Searches using language codes are more likely to be one-off searches. It's unlikely that users want to use that syntax to change their default search language.

**Comment by return42** [comment]
> It's unlikely that users want to use that syntax to change their default search language.

Is it? .. I'm not representative but: I'm one of the guys who prefer to do everything with the keyboard and I often switch between the two major languages I use by typing `:en` or `:de`.

**Comment by not-my-profile** [comment]
Yes it's neat that this is possible but it's totally not obvious that this is possible. For people that don't know about it this behavior is more confusing than helpful.

To support users with a keyboard-centric workflow we could introduce some system that allows the changing of all preferences via some CLI-style syntax. e.g. `/theme simple` could change the theme to Simple, `/theme oscar` could change the theme to Oscar, `/lang de` could change the default language to German, etc. (This would of course be especially neat with autocompletion).

**Comment by return42** [comment]
> To support users with a keyboard-centric workflow we could introduce some system that allows the changing of all preferences via some CLI-style syntax

I don't think so, keyboard-centric users like me are not representative.  99% of the SearXNG users are not developers or other keyboard-centric users / they just want to have a _google like experience_ where the quality of the results score (what is also the reason for https://github.com/searxng/searxng/pull/709 )

**Comment by not-my-profile** [comment]
>they just want to have a google like experience

Exactly. So you agree with me that the current behavior is problematic for the majority of users?

**Comment by return42** [comment]
> Exactly. So you agree with me that the current behavior is problematic for the majority of users?

I go beyond, I assume they will never use `:en`, because they don't know that this option exists.

**Comment by not-my-profile** [comment]
>because they don't know that this option exists

Yes I think that's a separate problem we should fix by addressing #722.

**Comment by return42** [comment]
Closed as not planned.
