### ISSUE TITLE
Integrate the user documentation into the application

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#722]
Currently the user documentation lives at https://docs.searxng.org/user/. Most SearXNG instances do host their own documentation. There are several problems with that:

1. Currently users are unlikely to find the user documentation.
   (https://docs.searxng.org/ is only linked from the bottom of the About page)

2. When they do find the user documentation it might not fit with the version of SearXNG they are using.
    (because some instances of SearXNG run an outdated version)

3. The official user documentation cannot link example queries to the search page since it doesn't know which instance the user is using. (#659)

4. The user documentation cannot embed information about the instance (e.g. how many engines it has).

5. The user documentation cannot be translated via Weblate to match the UI language.

Moving the user documentation into the application would solve all of these problems.
While we're at it I think we should convert the user documentation to Markdown because I think it's easier to integrate into a web application than reStructuredText. (RST is mainly useful for documenting API which we don't need for user documentation)

**Comment by return42** [comment]
solved by https://github.com/searxng/searxng/pull/930
