### ISSUE TITLE
Docker image: build fail

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#741]
The docker build fails since the PR https://github.com/searxng/searxng/pull/686 has been merged.

Explanation:
* the new dependency `redis` depends on [packaging](https://pypi.org/project/packaging/) ( see https://github.com/redis/redis-py/blob/master/requirements.txt)
* `packaging` is built in in Python
* the docker image doesn't create a virtualenv
* when redis is installed, pip tries to upgrade `packaging` but fails because it doesn't know how to uninstall it.

[EDIT] This is also mean that the redis dependency requires SearXNG to be install in a virtualenv (even without docker). It was not the case before.

Related to https://github.com/redis/redis-py/issues/1869

**Comment by return42** [comment]
Should we rollback #686 and fix this issue first?

EDIT: seems fixed in https://github.com/redis/redis-py/pull/1854/files .. may be we wait until this commit is released at pypi

**Comment by dalf** [comment]
IMO, if there is no release tomorrow evening, we can rollback and take the time to integrate redis into the code or at least wait for a release without blocking the other PR (for the docker image).

**Comment by return42** [comment]
Solved since https://github.com/searxng/searxng/pull/775 is merged
