### ISSUE TITLE
Global engines access tokens

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#755]
It would be very useful to have the possibility to specify global token(s) for all upstream search engines.
In this way, only people knowing the token(s) would be actually able to use a particular SearXNG instance.

This would be an easy way to avoid the abuse of a particular instance without the need to specify tokens for each one of the many upstream engines in settings.yml.

Should this feasible, I guess that for coherence a couple of options should be created under 'general' or 'engines" on the likes of:

```
general:
  enable_global_tokens: true # enables global tokens
  global_tokens: [ 'my-secret--global-token' ] # actual global tokens
```
  
Also, these should have priority over tokens specified for search engines. For example, if `engine1` needs `token1` to be accessed, then only people knowing both `my-secret--global-token` and `token1` would be able to use that `engine1`.

**Comment by return42** [comment]
IMO blocking a SearXNG instance by a global token is conceptual wrong.  Even if all functions are blocked, the application is penetrated by unauthorized requests.  A Basic Authentication & HTTPS is a simple solution to authorize and prevent unauthorized requests to the application.

**Comment by catfluoride** [comment]
> IMO blocking a SearXNG instance by a global token is conceptual wrong. Even if all functions are blocked, the application is penetrated by unauthorized requests. A Basic Authentication & HTTPS is a simple solution to authorize and prevent unauthorized requests to the application.

I understand HTTPS, but what do you mean by Basic Authentication? Something like login/password or...?

**Comment by return42** [comment]
In your HTTP server you can configure HTTP [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) 

- [nginx](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
- [apache](https://httpd.apache.org/docs/2.4/howto/auth.html)

since the password is not encrypted this method should only be used on a HTTPS connection // but this would be the same when you use tokens.

EDIT: generally .. always use HTTPS :)

**Comment by catfluoride** [comment]
> In your HTTP server you can configure HTTP [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication)
> 
> * [nginx](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
> * [apache](https://httpd.apache.org/docs/2.4/howto/auth.html)
> 
> since the password is not encrypted this method should only be used on a HTTPS connection // but this would be the same when you use tokens.

I wasn't aware of this possibility. Thanks a lot!

**Comment by return42** [comment]
> I wasn't aware of this possibility. Thanks a lot!

Is your request fulfilled / can we close this issue?

**Comment by catfluoride** [comment]
> > I wasn't aware of this possibility. Thanks a lot!
> 
> Is your request fulfilled / can we close this issue?

I guess so. Thank you.
