### ISSUE TITLE
Hostname replace toggle button doesn't say what it does

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#765]
![image](https://user-images.githubusercontent.com/73739153/149648004-8327ecd2-6bb3-48bd-bd6c-81c33c63cc6a.png)

Users should be informed about how their results are rewritten / censored.

**Comment by return42** [comment]
> Users should be informed about how their results are rewritten / censored.

Since this is individual to every engine .. and it won't help to face regular expressions to the end user .. I think there is no solution for this request that would really help .. I close this issue .. if you think different and have some suggestions for us, we can reopen the issue.
