### ISSUE TITLE
[question] Google redirecting to google.com.hk

### ISSUE THREAD

**Issue by tiekoetter** [searxng/searxng#767]
Google thinks that my proxies are located in Jiangsu, China for whatever reason now.
Is there any way to stop google from redirecting to .com.hk? I know of google.com/ncr but this doesn't allow any queries.

**Comment by return42** [comment]
Can you please post the log from the `make run` where we can see the redirection ..

**Comment by tiekoetter** [comment]
```DEBUG   searx.search                  : actual_timeout=2.0 (default_timeout=2.0, ?timeout_limit=None, max_request_timeout=None)
DEBUG   searx.network.google          : HTTP Request: GET https://www.google.com/search?q=test&hl=en&lr=lang_en&ie=utf8&oe=utf8&start=0&filter=0&asearch=arc&async=use_ac%3Atrue%2C_fmt%3Apc "HTTP/1.1 302 Found" (text/html; charset=UTF-8)
DEBUG   searx.network.google          : HTTP Request: GET https://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=https://www.google.com.hk/search%3Fq%3Dtest%26hl%3Den%26lr%3Dlang_en%26ie%3Dutf8%26oe%3Dutf8%26start%3D0%26filter%3D0%26asearch%3Darc%26async%3Duse_ac%253Atrue%252C_fmt%253Apc&ust=1642363791746788&usg=AOvVaw1YTo2_lxuCcQdBxVhEPwLt "HTTP/1.1 302 Found" (text/html; charset=UTF-8)
DEBUG   searx.network.google          : HTTP Request: GET https://www.google.com.hk/search?q=test&hl=en&lr=lang_en&ie=utf8&oe=utf8&start=0&filter=0&asearch=arc&async=use_ac%3Atrue%2C_fmt%3Apc "HTTP/1.1 200 OK" (text/plain; charset=UTF-8)
WARNING searx.engines.google          : ErrorContext('searx/search/processors/online.py', 105, 'count_error(', None, '2 redirects, maximum: 0', ('200', 'OK', 'www.google.com.hk')) True
DEBUG   searx.engines.google          : did not find 'answer'
DEBUG   searx.webapp                  : https%3A//searx.test.tiekoetter.net/search%3Fq%3D%2521google%2Btest%26language%3Den%26time_range%3D%26safesearch%3D0%26theme%3Dsimple uses locale `de`
INFO    werkzeug                      : 192.168.178.129 - - [16/Jan/2022 21:09:22] "GET /search?q=%21google+test&language=en&time_range=&safesearch=0&theme=simple HTTP/1.0" 200 -
```

**Comment by return42** [comment]
OK in your LOG I can see that the first request goes to `google.com` and is redirected to `google.com.hk` .. to validate this I needed the LOG for.

The sad news: I don't know how you can avoid such redirects by google.

May be some others have an idea ...

**Comment by tiekoetter** [comment]
I "fixed" this by using google.de for every language which defaults to google.com.

**Comment by return42** [comment]
> Google thinks that my proxies are located in Jiangsu, China for whatever reason now.

@tiekoetter where is your server's IP located?  / Is your server public, if so what address?

**Comment by tiekoetter** [comment]
@return42 

Instance: searx.tiekoetter.com
Proxies: alpha.proxy.searx.tiekoetter.net; beta.proxy.searx.tiekoetter.net

**Comment by foxdodo** [comment]
Confirm fixed by adding `base_url: https://www.google.ca/search` in the google section, and I found out that the default setting triggers 2 redirects, which dramatically increase search time.
