### ISSUE TITLE
[question] activate google's use_mobile_ui by default?

### ISSUE THREAD

**Issue by return42** [searxng/searxng#774]
From time to time we hear that SearXNG admins do not get google results, most often we recommend to activate `use_mobile_ui: true` .. may be it is time, we set the default to this value? ...

https://github.com/searxng/searxng/blob/96ab5e57ff92aba4ab0fedeb4e5fbfa09e9fc2e2/searx/settings.yml#L623-L627

**Comment by return42** [comment]
@unixfox @tiekoetter @mrpaulblack do you use google mobile UI .. should we change the default to use it?

You can vote with thumbs up/down.

**Comment by unixfox** [comment]
no it should stay off by default or google will notice it and block this method. google on searx works well locally without any workaround so there is no point in having use_mobile_ui by default

**Comment by unixfox** [comment]
Now that I think again about it, maybe we could print in the logs a help message explaining that the user may need to enable `use_mobile_ui`?

If we find a too many requests error, then we print the help message.

**Comment by samsapti** [comment]
> Now that I think again about it, maybe we could print in the logs a help message explaining that the user may need to enable `use_mobile_ui`?
> 
> If we find a too many requests error, then we print the help message.

@unixfox I think that's a good idea.
