### ISSUE TITLE
Update input when selecting autocomplete prediction with keyboard

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#778]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
SearXNG Docker: `1.0.0-1516-96ab5e57`

**How did you install SearXNG?**
SearXNG Docker using the docs.

**What happened?**

(NOTE: THIS IS HARD TO EXPLAIN WITH WORDS) This is an inconsistency more than a bug, but it does affect the user experience. The Search Suggestion behavior should be tweaked so when the user selects from the suggestions using the up and down arrows on desktop it autopopulates the search box. Doing this results in a better experience because the user does not need to press `Enter` twice to perform a search. They simply select using the arrow keys  to autopopulate the search box and press `Enter` to search VS highlighting the suggestion via arrow keys and then pressing `Enter` to select and then `Enter` again to search. Likewise, a similar behavior should apply to touching the suggestion on mobile or using a mouse on the desktop. If I click on a suggestion --> immediately search for it VS I click --> populates the search box --> Hit the search button to search. As far I can tell all search engines to this, and it feels clunky to not have the same behavior on SearXNG. Currently, using `Simple Dark Theme`. BTW, is this because there's minimal JS?

**How To Reproduce**
1. Make sure simple theme is selected in SearXNG (Haven't tested with Oscar).
2. Be on a Chromium-Based browser (I'm using Brave).
3. Go to SearXNG instance main page and type something into the box (could do with results page too, same thing).
4. Use the arrow keys or mouse to select something from the Search Suggestions.
5. If using arrow keys, notice you can highlight the `search suggestion` but it doesn't populate the `search box`
6. You have to press `Enter` to populate the search box with your selection and `Enter` again to perform the search.
7. If using mouse, notice you can click the `search suggestion` to populate the `search box` BUT it doesn't search for it right away!
8. Similar behavior as `7` with mobile.

**Expected behavior**
If using arrows, it should populate the search box when selecting via dropdown and the user should only have to press enter once to search.
If using mouse or touch on mobile, clicking the suggestion should populate the search box AND perform the search.
This behavior is seen on all other search engines.

**Screenshots & Logs**
Arrow example where the user has to press enter twice since the arrow down or up doesn't populate the search box.
![Arrow-Example](https://user-images.githubusercontent.com/68975831/149843705-fd7257fe-eb25-434d-b3ec-88e2f1135d05.gif)

Same thing on DDG. Arrow keys populated the search box and pressed enter once to search.
![Arrow-Example-DDG](https://user-images.githubusercontent.com/68975831/149843858-68665899-4fd7-4daa-8958-1788817c04d5.gif)

Mouse example, user has to click twice. Once to make the selection to populate the search box and another on Magnifying glass to search.
![Mouse-Example](https://user-images.githubusercontent.com/68975831/149844212-fe7a8b41-8a37-4d3f-a338-528ecaa6dc0f.gif)

Mouse example DDG. User only has to click once.
![Mouse-Example-DDG](https://user-images.githubusercontent.com/68975831/149844347-094f5d60-c21e-422c-8e26-4a251bf20bb6.gif)

**Additional context**
I have only tested this on my primary browser: Brave. Nothing Firefox based. Same thing happens on iOS mobile.

**Comment by return42** [comment]
> NOTE: THIS IS HARD TO EXPLAIN WITH WORDS

you just did it perfect :-)

> Expected behavior
> If using arrows, it should populate the search box when selecting via dropdown and the user should only have to press enter once to search.

.. and when the user press [TAB] the input form should be filled with the highlighted item from the autocomplete list, but not release a search / with other words: what we now have by pressing once on [ENTER] should be mapped to the [TAB] key and pressing [ENTER] once should release a search query.

> If using mouse or touch on mobile, clicking the suggestion should populate the search box AND perform the search.
> This behavior is seen on all other search engines.

:+1:
