### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by muzihuaner** [searxng/searxng#779]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0-1355-7966fd3b

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: some results are invalids: invalid content
  * Percentage: 40
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:111`
  * Function: `_extend_container_basic`
  * Code: `result_container.extend(self.engine_name, search_results)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 5
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
did you tried `use_mobile_ui` ... otherwise it is https://github.com/searxng/searxng/issues/771 & https://github.com/searxng/searxng/pull/777

```yaml
- name: google
  ...
  use_mobile_ui: true
```
