### ISSUE TITLE
Document directory structure

### ISSUE THREAD

**Issue by MontyQI** [searxng/searxng#785]
**Is your feature request related to a problem? Please describe.**

The structure of searx is hard to understand.

**Describe the solution you'd like**

In documentation in developer category, add new section explaining the basic structure (directories and the most important files).

**Describe alternatives you've considered**

**Additional context**

Example of such documentation:
https://github.com/benbusby/whoogle-search#contributing

**Comment by return42** [comment]
> The structure of searx is hard to understand.

Oh yes, thats true .. but instead documenting we want to reorder the structure in several smal steps.  The first step was to remove the oscar theme, in second step https://github.com/searxng/searxng/pull/1188 simplifies the searx/templates and in another PR, the source files of the static directory will be moved to the src directory.

I close this issue / if you think different, ask for reopen the issue.
