### ISSUE TITLE
Currency engine has DuckDuckGo metadata

### ISSUE THREAD

**Issue by Dalethium** [searxng/searxng#787]
In the engine selector of the preferences window, the currency search engine has the same metadata and wikidata url as duckduckgo, I'd assume there should be a difference of some sort there clarifying what source the currency uses or, if it's a duckduckgo service, at least clarifying that it's a currency service by duck duck go.

**Comment by return42** [comment]
Its a service from ddg.  May be when https://github.com/searxng/searxng/pull/811 is merged, we can overwrite the description by adding

```
        "description" : "service from DuckDuckGo"
```

to the about dictionary in ..

https://github.com/searxng/searxng/blob/1f15d50aace578a63433a2b60c18ceb73dfa6230/searx/engines/currency_convert.py#L9-L16
