### ISSUE TITLE
Allow custom about hover data

### ISSUE THREAD

**Issue by Dalethium** [searxng/searxng#788]
**Is your feature request related to a problem? Please describe.**
Hovering over custom engines leads to very  little information based on the available configs

**Describe the solution you'd like**
a string value in the about tag called ``desc`` for overriding/setting the description of an engine

**Describe alternatives you've considered**
None, it seems fairly straight forward in this case and a clear missing feature.

**Additional context**
an example of the about section I am referring to
![image](https://user-images.githubusercontent.com/22735418/150298644-68771189-eca8-43f5-8767-9a7684a49e6a.png)

**Comment by return42** [comment]
The description is (un-) regularly updated froḿ various sources by the script https://github.com/searxng/searxng/blob/master/searxng_extra/update/update_engine_descriptions.py

If a "wikidata_id" is given ...

https://github.com/searxng/searxng/blob/1a210e653c80d33dfebaafc7d6697d7ee58655e1/searx/engines/gigablast.py#L17

The description is fetched from [Wikidata](https://github.com/searxng/searxng/blob/master/searx/engines/wikidata.py).

Why do you think there is a need for a manual configuration?

**Comment by Dalethium** [comment]
> Why do you think there is a need for a manual configuration?

It's needed as there is the ability to add custom search engines from torznab, postgress, comandlets, etc. These would not be suited for a public wikidata page if I understand that correctly.

**Comment by return42** [comment]
Ah, OK that makes sense / I haven't thought about (I looked at your Gigablast example).

**Comment by return42** [comment]
@Dalethium I assume i18n is not needed .. I send PR https://github.com/searxng/searxng/issues/788 may you have a look at.
