### ISSUE TITLE
Mastodon & Pixelfed

### ISSUE THREAD

**Issue by GreenLunar** [searxng/searxng#792]
**Working URL to the engine**

I don't know yet. I'll find out later and update.

**Why do you want to add this engine?**

To encourage libre and decentralized www.

**Features of this engine**

Photo sharing platform.

**How can SearXNG fetch the information from this engine?**

images, social media

**Additional context**

https://pixelfed.social/
https://pixelfed.org/

**Comment by not-my-profile** [comment]
Apparently [Pixelfed's API](https://docs.pixelfed.org/technical-documentation/api-v1.html) is designed after the Mastodon API so it probably makes more sense to support Mastodon.

Ref: https://github.com/pixelfed/ideas/issues/12

**Comment by GreenLunar** [comment]
Thanks. Closing, for now.

**Comment by GreenLunar** [comment]
Title changed to Mastodon (reopen)

**Comment by austinhuang0131** [comment]
I don't think you can search Mastodon/Pixelfed without logging in

For Mastodon, you *can* look at hashtags without logging in, but then it will largely depend on perspective (ie. which instance you choose)

**Comment by GreenLunar** [comment]
> I don't think you can search Mastodon/Pixelfed without logging in

Only certain type of posts (e.g. classified as Public).

> but then it will largely depend on perspective (ie. which instance you choose)

Similarly to diaspora*, GNU Social, Movim (XMPP) and PeerTube (supported by searx), cross search is possible from one instance alone.
Yet, not every instance may have results from all other instances, so I encourage the practice of searching from multiple instances at once in order to reveal more results.

**Comment by GreenLunar** [comment]
I'm a big fan of @austinhuang0131
Good job, Austin!

**Comment by nichu42** [comment]
Would it be possible to enable search on Mastodon via Tootfinder API? 
https://tootfinder.ch/wiki/index.php?name=the-tootfinder-rest-api

Tootfinder (https://tootfinder.ch/) is a full-text search for Mastodon. Though it requires users to opt in (that's the only accepted approach in the Fediverse right now), it would definitely be a big plus for SearXNG.

/cc @mrpaulblack
