### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by atom7xyz** [searxng/searxng#800]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

commit f3d4b25e739164ea6af087379536b3ef3538d63c

**How did you install SearXNG?**

Using the official wiki.

**What happened?**

After updating the software from version 1375 to the latest one my SearXNG instance stopped working, an "Internal Server Error" is returned when I visit the page.
To be clear, I did non change a single thing in the configuration(s).

**How To Reproduce**

I'm not sure, I fresh-installed everything (searxng, morty, filtron...) and the same error appears.

**Expected behavior**

To work as in version 1375 or prior.

**Screenshots & Logs**

The request is recived by filtron and gives an output:

![img](https://user-images.githubusercontent.com/45697827/150601005-1ab7d939-f508-40da-894d-435a90ca230e.png)

SearXNG does not give any output:

![img](https://user-images.githubusercontent.com/45697827/150601301-db63cb4c-355b-48cc-a07b-4f87f7b6b459.png)

SearXNG logs: https://pastebin.com/vkPNAUd6

Since the logs mention "_KeyError: 'engine'_", here is my engine list:

![img](https://user-images.githubusercontent.com/45697827/150603194-2acf7f34-41ca-496d-8478-fd2d7d492ce5.png)

**Additional context**

//

**Comment by tiekoetter** [comment]
You need to specify the "engine" attribute inside the engines.

Example:
https://github.com/searxng/searxng/blob/977e9a433085124e17f2f7f26afabbeb71db9470/searx/settings.yml#L475-L478

**Comment by atom7xyz** [comment]
> You need to specify the "engine" attribute inside the engines.
> 
> Example:
> 
> https://github.com/searxng/searxng/blob/977e9a433085124e17f2f7f26afabbeb71db9470/searx/settings.yml#L475-L478

Solved, thank you!
