### ISSUE TITLE
Weblate doesn't show the "other"/"others" categories as translatable strings

### ISSUE THREAD

**Issue by MarcAbonce** [searxng/searxng#814]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
61853aa0fbcd2573f50e9c092f61cde1ad71492a (current master)

**What happened?**

Weblate doesn't show the "other"/"others" categories as translatable strings. They do not show up in any of the [messages.po](https://github.com/searxng/searxng/blob/master/searx/translations/en/LC_MESSAGES/messages.po) files either, even though all the other new subcategories already appear in there.

**How To Reproduce**
1. Go to Weblate.
1. Try to find the "other" string.

**Expected behavior**
1. Strings should be translatable.

**Additional context**

I think that the script used to generate the messages.po files wasn't able to pick up those strings because they are defined outside the gettext, see: https://github.com/searxng/searxng/blob/master/searx/webapp.py#L189-L190
```python
...
    gettext('web'),
    gettext(DEFAULT_GROUP_NAME),
    gettext(OTHER_CATEGORY)
)
```

**Comment by not-my-profile** [comment]
Ah yeah my bad ... I thought that the `gettext` functions actually did something, I guess the strings are extracted statically.

**Comment by return42** [comment]
May be we can use https://babel.pocoo.org/en/latest/messages.html#writing-extraction-methods

I got this tip from https://github.com/python-babel/babel/issues/807#issuecomment-1021223474

**Comment by return42** [comment]
> I think that the script used to generate the messages.po files wasn't able to pick up those strings because they are defined outside the gettext

@MarcAbonce I fixed this issue in PR https://github.com/searxng/searxng/pull/859 .. if you have time for, would like to have a look at this PR? / thanks!
