### ISSUE TITLE
[question] Integrate Trivy or Synk GitHub Actions?

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#823]
What are your thoughts in integrating Trivy OR Synk into the GitHub repo (probably the Docker repo) to continuously scan for vulnerabilities and misconfigurations? I'm not technical enough to know if this is feasible for this project, so please take a look.

Trivy main page: `https://github.com/aquasecurity/trivy`
Trivy GH action is available here: `https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning`
Synk GitHub integration docs: `https://docs.snyk.io/features/integrations/git-repository-scm-integrations/github-integration`

**Comment by dalf** [comment]
See:
* https://github.com/searxng/searxng-docker/blob/master/.github/workflows/security.yml
* https://github.com/searxng/searxng-docker/actions/runs/1765900959


The dalf/morty and dalf/filtron docker images contains only the bare minimum now:
* https://github.com/dalf/filtron/blob/922ba305c5695e7aeb4ba372af555043ed586085/Dockerfile#L23-L37
* https://github.com/dalf/morty/blob/25fe0e3b55af15f9d6c977dc80b70bb9c5cba803/Dockerfile#L20-L33
