### ISSUE TITLE
morty issue and question

### ISSUE THREAD

**Issue by caywin25** [searxng/searxng#834]
Hello 

When I want to use morty with -key I get an error : 

invalid "mortyhash" parameter

Am I using it wrong?
I run it with : 

> ./morty -key <key> (generated with: openssl rand -base64 33)

If I run it without key, it works fine.

Is it planned in the near future that morty will be integrated directly into searxng and we won't have to clone : github.com/asciimoo/morty ?

Thanks for your answer and thanks for your work.

Translated with www.DeepL.com/Translator (free version)

**Comment by return42** [comment]
> Is it planned in the near future that morty will be integrated directly into searxng 

its already done :-) .. deinstall morty and activate `image_proxy: true` ..

https://github.com/searxng/searxng/blob/8f100d7046cad3fa5ed2fbacdd69e2825a4660a7/searx/settings.yml#L52

See https://docs.searxng.org/admin/engines/settings.html#server

**Comment by caywin25** [comment]
Oh thx you.
My bad for this useless issue.

Regards
