### ISSUE TITLE
Bug: invidious engine

### ISSUE THREAD

**Issue by AvianaDownloadLinux** [searxng/searxng#846]
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 40
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Checker
  * simple: `searx.exceptions.SearxEngineTooManyRequestsException `,
  * paging: `searx.exceptions.SearxEngineTooManyRequestsException `,

**Comment by return42** [comment]
Having `Too many request` from time to time seems normal .. 

Fore the future: please give us some more hints and fill out the form of the bug report / I close this issue .. ask for reopen when your have more information.

FYI: Invidious setup & tips are discussed here: https://github.com/searxng/searxng/issues/821
