### ISSUE TITLE
Tab confusion

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#854]
The search tabs:

![image](https://user-images.githubusercontent.com/73739153/151932208-caf08d12-a27a-4ad3-9fcb-ccac1992e97f.png)

are actually implemented as labels for invisible checkboxes. Since it's possible to search multiple tabs at once, multiple tabs can be active at once (=> multiple checkboxes can be checked at once).

Since users expect that clicking on a tab immediately opens that tab, the `search_on_category_select` plugin implements that behavior via JavaScript.

There are two problems with this:

1. without JavaScript the checkboxes that were dressed up as tabs suddenly act like checkboxes which is confusing. While there is a "Click on magnifier" help text shown ... it's still confusing (see #498).

2. The `search_on_category_select` JavaScript changes the semantics of the `<label>`s which is confusing for people relying on accessibility software like screen readers.

Before this issue can be addressed we should convert the `search_on_category_select` plugin to a user preference, see  #769.

**Comment by return42** [comment]
See https://github.com/searxng/searxng/issues/769#issuecomment-1132481995
