### ISSUE TITLE
Yacy local mode

### ISSUE THREAD

**Issue by Dalethium** [searxng/searxng#855]
**Describe the solution you'd like**
Adding a boolean config toggle for "global" or "local" here: https://github.com/searxng/searxng/blob/07f7289e23c3ed28bb5e4f71d47e0da554ca9aea/searx/engines/yacy.py#L38

**Describe alternatives you've considered**
I tried setting a tupple via the config to override the URL but it would not work. Currently, I am just manually editing the engine file.

**Additional context**
The yacy P2P search engine has a "local" mode and "global" mode when you are part of the DHT -- this is an important difference as things like loadtime, and content, can be very different. Your local yacy peer may have content that you have **specifically** curated and crawled, whereas the global p2p engine functions more analogous to google. This is all fine and well, however, seeing how it's just a boolean toggle we'd need, it seems like a fair thing to add considering the "nicheness" of the situation is the engine itself, and not the config I am proposing.

**Comment by allendema** [comment]
Can you try this patch?
https://github.com/searxng/searxng/compare/master...allendema:searxng:yacy-modes

**Comment by return42** [comment]
closed by https://github.com/searxng/searxng/pull/2587
