### ISSUE TITLE
Redirect to Privacy respecting alternatives

### ISSUE THREAD

**Issue by GreenLunar** [searxng/searxng#856]
In the spirit of ticket #821 and UntrackMe

Realization
https://f-droid.org/en/packages/app.fedilab.nitterizeme/
https://fedilab.app/wiki/nitterizeme/

>  UntrackMe once set by default to open Twitter, YouTube and Instagram links will transform them into Nitter, Invidious and Bibliogram links and delegate the action to another app.
> It also supports Google Maps links to transform them into OpenStreetMap links or Geo URI.
> The app will detect shortened URLs and will display the full URL before visiting the site.

> **Lite version:
> - When sharing a Twitter, YouTube or Google Maps link just pick up UntrackMe to transform it before sharing it with another app.

> **Full version:
> - Contains all features of the lite version and it also handle all links to remove tracking parameters. It uses its own app picker that display URLs before visiting them.

> What is Nitter:
> A free and open source alternative Twitter front-end focused on privacy.
Github project: https://github.com/zedeus/nitter

> What is Invidious:
> A free and open source alternative front-end to YouTube
Github project: https://github.com/omarroth/invidious

> What is Bibliogram:
> A free and open source alternative front-end to Instagram
Github project: https://github.com/cloudrac3r/bibliogram

> What is Teddit:
> A free and open source alternative Reddit front-end focused on privacy.
Github project: https://github.com/teddit-net/teddit

> What is Scribe:
> An alternative Medium front-end
Sources: https://git.sr.ht/~edwardloveall/scribe

> What is Wikiless:
> A free open source alternative Wikipedia front-end focused on privacy.
Project: https://codeberg.org/orenom/Wikiless

**Comment by return42** [comment]
Just wanted to add a link to https://github.com/searxng/searxng/issues/725

**Comment by dalf** [comment]
Side note:
* A link to another project: https://github.com/benbusby/farside
* The list is auto updated: https://github.com/benbusby/farside/blob/main/.github/workflows/update-instances.yml

**Comment by emanruse** [comment]
It would be good onion instances of Searx to use onion instances of the alternatives.

Please consider also:

https://github.com/mendel5/alternative-front-ends


Facebook doesn't seem to have an alternative front-end. However it has a version which doesn't need JavaScript:

https://mbasic.facebook.com/

And an official onion instance too:

https://mbasic.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/

**Comment by peepo5** [comment]
farside seems like a great gateway but then how do you know how much strain it would put on the instance?

**Comment by GreenLunar** [comment]
Some instances already got links to "other instances", so it's feasible
to make an automatic redirect mechanism that would be activiated when
needed.

Such mechanism needs to be added to each instance seperately.

**Comment by return42** [comment]
> Such mechanism needs to be added to each instance separately.

That's right, there isn't always a generic solution that fits to the needs. We can discuss the various aspects in our Q&A section:

- https://github.com/searxng/searxng/discussions/911
- https://github.com/searxng/searxng/discussions/970

I will also move this Issue in the Q&A section.
