### ISSUE TITLE
Bug: solidtorrents engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#858]
**Version of SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0 (searx.be)
Version: 1.0.0-1638-9fae80fa (search.mdosch.de)
Version: 1.0.0-1537-f0ee5103 (homeserver)

**How did you install SearXNG?**
searxng-docker (for my own instance)

**What happened?**
Solidtorrent is not working. I tested it with my homeserver instance, searx.be, search.mdosch.de.

**How To Reproduce**
Select solidtorrents engine in the "files" category.
Search and select the files tab.

**Technical report**
(from searx.be)

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('404', 'Not Found', 'solidtorrents.net')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Checker
  * simple: `httpx.HTTPStatusError `,
  * paging: `httpx.HTTPStatusError `,

**Comment by mrpaulblack** [comment]
For vis: https://github.com/paulgoio/searxng/issues/17
