### ISSUE TITLE
Lets remove aboutextend.html

### ISSUE THREAD

**Issue by return42** [searxng/searxng#871]
Sine we have https://github.com/searxng/searxng/tree/master/searx/help where additional content can be added, there is no longer a need for aboutextend.html in https://github.com/searxng/searxng/tree/master/searx/templates/__common__

https://github.com/searxng/searxng/blob/10e6881ca861cfce70e99ededf2c864a9274b5dd/searx/user_help.py#L56-L60

We should not support two methods to add additional content to about (help) page / the __common__/aboutextend.html was needed in the past where no other method exists to add content.

**Comment by not-my-profile** [comment]
I think we should replace it with an `about_instance.md` file that by default just contains:

```
<!--
Below this comment you can write something about your instance if you want to.
(Whatever you write here is shown at the end of the /about page.)
-->
```

**Comment by return42** [comment]
Should we really "replace"? .. I think an empty page in the help section might give the impression to the end user, that something with this (empty) page is wrong.

I would suggest to add `about_instance.md` to the `_TOC`

https://github.com/searxng/searxng/blob/10e6881ca861cfce70e99ededf2c864a9274b5dd/searx/user_help.py#L19

which is only shown, when a file with this name exists.

**Comment by not-my-profile** [comment]
Ok, yeah that's also possible. In that case though I think it should additionally be linked from the footer if it exists (next to `general.contact_url`). I am however fond of the idea that the file exists by default with such a comment because it's easier for admins if they don't have to create the file.

**Comment by return42** [comment]
> I am however fond of the idea that the file exists by default with such a comment because it's easier for admins if they don't have to create the file.

I know .. its easier for admins, but an empty page (in a vanilla SearXNG instance) might confuse the end user?  I can only speak for myself, but I most often wondered when I linked to a page that is empty.

**Comment by not-my-profile** [comment]
We could just have the Python module skip the page if it is empty.

**Comment by return42** [comment]
This issue does no longer exists / I close it.
