### ISSUE TITLE
[SIMPLE THEME]: Results page looks improper on 720p screen.

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#874]
**How did you install SearXNG?**
SearXNG Docker.

**What happened?**
After some of the latest updates the results shift towards the middle of the page vs being towards the left side like it used to be. I'm on a 720p laptop, and it looks very awkward. 

**How To Reproduce**
1. Visit any SearXNG instance on a 720p screen.

**Expected behavior**
It should look like the first screenshot on default zoom.

**Screenshots & Logs**
Expected: on 90% zoom BTW:
![image](https://user-images.githubusercontent.com/68975831/152655859-dfd8c7ae-2807-4706-a44b-5be6d32f7ea3.png)

Actual: on 100% or default zoom:
![image](https://user-images.githubusercontent.com/68975831/152655898-45833f93-b502-4e1b-9c7f-76c8c341610c.png)

**Comment by dalf** [comment]
I guess the screen resolution is 1280 x 720.

The layout change to tablet mode exactly at 1280 pixel:
https://github.com/searxng/searxng/blob/afde954df8fedc0c9d21d1cc75407ecafed020ab/searx/static/themes/simple/src/less/definitions.less#L241

@mrpaulblack is it a problem to replace `80em` ( = 1280px ) by `79.75em`. ?

**Comment by mrpaulblack** [comment]
Yeah I tested it and it works on pref, landing, result page and so on without problems...

The only real reason against it, is that the desktop layout will be shown on a 720p tablet, but normally the font is IMO big enough that this will not be a problem or if the desktop layout is shown on tablet it means more content on the same screen size for the end user so I am ok with the change for tablet to `79.75em` :+1:
