### ISSUE TITLE
Images in instant answer are not loaded if "image proxy" is enables

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#875]
SearXNG Version: 1.0.0-1669-10e6881c

Simple theme is used

**How did you install SearXNG?**

SearxNG was installed by "installation scripts", without Morty or Filtron.

**What happened?**

If  "image proxy" is enabled, images searches work correctly. However, images in "Instant Answers" under the  "General" category are absent and just a broken image placeholder is shown.

For instance, if I search for "Enrico Fermi" in the General category, with the Image Proxy enabled Wikipedia's image is broken.

**How To Reproduce**
This bug is reproducible. Just enable "Image Proxy" an settings GUI and perform the aforementioned search

**Expected behavior**

An image should be displayed in place of the broken image placeholder

**Screenshots & Logs**

Expected result:
![expected](https://user-images.githubusercontent.com/25054477/152677025-85823d66-728c-4f6b-850a-9722c67bc474.png)

Actual result:
![actual](https://user-images.githubusercontent.com/25054477/152677023-0821723f-bae7-44db-a9a8-c46d47e75ebb.png)

Inspection of the page source gives the following:

`<img src="/image_proxy?url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FEnrico%2520Fermi%25201943-49.jpg%3Fwidth%3D500%26height%3D400&amp;h=dff389296b41618681172e6ca9f6a4e50b6ad32554484ff828889e64f4a419ab" title="Enrico Fermi" alt="Enrico Fermi">`

Somewhat "image_proxy" is misbehaving on the home page.

**Comment by return42** [comment]
I can confirm that the image is not loaded:

```
INFO    werkzeug                      : 127.0.0.1 - - [06/Feb/2022 12:24:41] "GET /static/themes/simple/js/searxng.min.js HTTP/1.1" 304 -
DEBUG   searx.network.image_proxy     : HTTP Request: GET https://commons.wikimedia.org/wiki/Special:FilePath/Enrico%20Fermi%201943-49.jpg?width=500&height=400 "HTTP/1.1 302 Found" (text/html; charset=utf-8)
DEBUG   searx.webapp                  : image-proxy: wrong response code: 302
INFO    werkzeug                      : 127.0.0.1 - - [06/Feb/2022 12:24:41] "GET /image_proxy?url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FEnrico%2520Fermi%25201943-49.jpg%3Fwidth%3D500%26height%3D400&h=c5affd8c6746b4d64eb63447da9f4138674fcab7dbc0a60576267cbea2232578 HTTP/1.1" 400 -
```

But the URL (now without image_proxy) ...

![grafik](https://user-images.githubusercontent.com/554536/152678861-641a58ee-e9bb-451d-b79d-9748df5de509.png)

is valid: https://commons.wikimedia.org/wiki/Special:FilePath/Enrico%20Fermi%201943-49.jpg?width=500&height=400

**Comment by tiekoetter** [comment]
~~I can't reproduce this.~~

If wikidata is enabled the image is broken.

See https://searx.tiekoetter.com/search?q=%21wikidata+enrico+fermi&language=en-US&time_range=&safesearch=0&theme=simple

**Comment by catfluoride** [comment]
> ~I can't reproduce this.~
> 
> If wikidata is enabled the image is broken.
> 
> See https://searx.tiekoetter.com/search?q=%21wikidata+enrico+fermi&language=en-US&time_range=&safesearch=0&theme=simple

Indeed, this it it. Disabling wikidata, everything works as expected on my instance.
Thank you for sharing this finding.

**Comment by tiekoetter** [comment]
@return42 Does the image proxy have a size limit?

**Comment by return42** [comment]
It seems the img URL from Wikidata's PNG is redirected (twice)

https://commons.wikimedia.org/wiki/Special:FilePath/Enrico%20Fermi%201943-49.jpg?width=500&height=400

![grafik](https://user-images.githubusercontent.com/554536/152684337-7d4e5752-6eda-49a6-942c-45c5b8437b90.png)

while the URL of the JPG from wikipedia is not redirected

https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Enrico_Fermi_1943-49.jpg/258px-Enrico_Fermi_1943-49.jpg

![grafik](https://user-images.githubusercontent.com/554536/152684434-a5950ec8-651a-43c5-ae8f-8bd7bf8760e0.png)

**Comment by tiekoetter** [comment]
I am currently working on a solution. I think I can do a PR soon.

**Comment by return42** [comment]
> I am currently working on a solution. I think I can do a PR soon.

Thanks .. I also working on a solution ;-)  ..  I just stuck at the meaning of priority . and why it must be lower:

https://github.com/searxng/searxng/blob/10e6881ca861cfce70e99ededf2c864a9274b5dd/searx/engines/wikidata.py#L223-L225

----
EDIT: I think image proxy should support redirects

**Comment by tiekoetter** [comment]
> EDIT: I think image proxy should support redirects

Maybe but then image proxy would do 2 redirects for every wikidata image. I don't think this would be good for performance.

**Comment by return42** [comment]
> Maybe but then image proxy would do 2 redirects for every wikidata image. I don't think this would be good for performance.

This arguments counts .. I just think about rewrite the image URL in the wikidata engine ... needs some more analysis .. I just digging :)

**Comment by return42** [comment]
OK, if I'm not wrong all images from commons.wikimedia.org are redirected to upload.wikimedia.org .. may be it is better we do not use images from commons.wikimedia.org in the info box. 

Another issue seems the _lower priority_ condition in

https://github.com/searxng/searxng/blob/10e6881ca861cfce70e99ededf2c864a9274b5dd/searx/engines/wikidata.py#L223-L225

**Comment by tiekoetter** [comment]
@return42 
https://github.com/tiekoetter/searxng/commit/4c8a6cd987871c697fec9f0e747a498941ecccd1
This should temporarily fix wikidata until a better solution can be found.

**Comment by return42** [comment]
@tiekoetter: I cloned your branch .. wow, very cool ..

    img_src_name_md5[0] + "/" + img_src_name_md5[0:2]

from where did you know it? I have never thought that it is the prefix of md5 digest.

Do you like to send a PR .. in the PR we can do some polish, but the md5 digest is the solution I think.

**Comment by tiekoetter** [comment]
> from where did you know it? I have never thought that it is the prefix of md5 digest.

https://stackoverflow.com/questions/33689980/get-thumbnail-image-from-wikimedia-commons

I will send the PR now.
