### ISSUE TITLE
[question] docker generated new settings.yml does not contain instance_name/base_url of the commandline 

### ISSUE THREAD

**Issue by neiaberau** [searxng/searxng#876]
I stated this as question as I do not know whether this is supposed to happen, but when I start 
docker run -d --name=test -p 8898:8080  -v "${PWD}/test:/etc/searxng" -e INSTANCE_NAME=test  searxng/searxng

the settings.yml does not contain the instance_name (or base_url)  settings as supplied on the line above, which I would have expected as with searx/searx this is done. 

after some digging I came to the conclusion that commit    
[yamllint] searx/settings.yml    5a7b12ee6f6285dbf5f0be164f93460839d99c98
changed the yml formating, and the sed expressions in docker_entrypoint.sh do no longer match and therefore do not replace the content anymore

I guess settings.yml or docker_entrypoint.sh should be changed to match again

**Comment by return42** [comment]
@neiaberau: thanks a lot for your deep analysis! .. I tried to fix the issue in #877.
