### ISSUE TITLE
Add libgen.is

### ISSUE THREAD

**Issue by troymaclure** [searxng/searxng#895]
**Working URL to the engine**
http://libgen.is/search.php?req=request

**Why do you want to add this engine?**
Must Have for computing/enginering documentation. 

**Features of this engine**
Tons of documentation/books specialized in engineering and computing, alternative to Z-library which is blocked in numerous country.

**How can SearXNG fetch the information from this engine?**

Simple Search url 
***Param :*** req
***Value :*** { `request` : String} 
***Example "api":*** `http://libgen.is/search.php?req=api`

Detailed | Simple result view 
***Param :*** `view`
***Values :*** { `detailed` | `simple` }
***Example "simple":*** `http://libgen.is/search.php?req=api&open=0&res=25&view=simple&phrase=1&column=def`
***Example "detailed":*** `http://libgen.is/search.php?req=api&open=0&res=25&view=detailed&phrase=1&column=def`

Displayed results number
***Param :*** `res`
***Values :*** `25` | `50` | `100` 
***Example "25":*** `http://libgen.is/search.php?req=api&open=0&res=25&view=simple&phrase=1&column=def`
***Example "50":*** `http://libgen.is/search.php?req=api&open=0&res=50&view=simple&phrase=1&column=def`
***Example "100":*** `http://libgen.is/search.php?req=api&open=0&res=100&view=simple&phrase=1&column=def`

Search in column 
***Param :*** `column`
***Values :*** { `def` | `title` | `author` | `series` | `publisher` | `year` | `identifier` | `language` | `md5` | `tags` | `extension` }
***Example "def":*** `http://libgen.is/search.php?req=api&open=0&res=100&view={detailed|simple}&phrase=1&column=def`
***Example "title":*** `http://libgen.is/search.php?req=api&open=0&res=100&view=simple&phrase=1&column=title`
***Example "author":*** `http://libgen.is/search.php?req=Li+Gong&open=0&res=100&view=simple&phrase=1&column=author`
***Example "series":*** `http://libgen.is/search.php?req=&open=0&res=100&view=simple&phrase=1&column=series`
***Example "publisher":*** `http://libgen.is/search.php?req=CRC+Press&open=0&res=25&view=simple&phrase=1&column=publisher`
***Example "year":*** `http://libgen.is/search.php?req=2020&open=0&res=100&view=simple&phrase=1&column=year`
***Example "identifier" (ISBN):*** `http://libgen.is/search.php?req=9780585110387&open=0&res=25&view=simple&phrase=1&column=identifier`
***Example "language":*** `http://libgen.is/search.php?req=english&open=0&res=25&view=simple&phrase=1&column=language`
***Example "tags":*** `http://libgen.is/search.php?req=api&open=0&res=25&view=simple&phrase=1&column=tags`
***Example (file) "extension":*** `http://libgen.is/search.php?req=pdf&open=0&res=100&view=simple&phrase=1&column=extension`

**Applicable category of this engine**
it, science.

**Additional context**
There is also a fiction and foreignfiction subforder.
`https://libgen.is/fiction/?q=api`

**Comment by allendema** [comment]
Just add your desired domain here and test it.
Some domains may not respond.

https://github.com/searxng/searxng/blob/1fbb514a4ead209c95b4ddca0430f754a4c11554/searx/settings.yml#L866

**Comment by return42** [comment]
- https://github.com/searxng/searxng/pull/1145

The engine exists in SearXNG, I close this issue. @troymaclure if you have  suggestions to improve the engine please open another issue or even better ask for PR :+1:
