### ISSUE TITLE
Printable and shareable and readable feeds

### ISSUE THREAD

**Issue by GreenLunar** [searxng/searxng#897]
This is a great (and cheap) addition to add to SearxNG.

Not only it makes RSS pages to look better, it also makes them printable, and also exportable to PDF with hyperlinks too.  See attachments set

Test link: https://archlinuxarm.org/forum/feed.php
a) [screenshot](https://github.com/OtterBrowser/otter-browser/files/8014673/Arch.Linux.ARM.png.pdf)
b) [shareable in pdf and hyperlinks](https://github.com/OtterBrowser/otter-browser/files/8014680/Arch.Linux.ARM.pdf)
c) [without xsl](https://github.com/OtterBrowser/otter-browser/files/8014724/Arch.Linux.ARM.otter.pdf)

https://github.com/QupZilla/qupzilla/issues/1361#issuecomment-262802841

Searx https://github.com/searx/searx/issues/2051 @dalf @gloschtla @return42 @sjehuda @unixfox

**Comment by GreenLunar** [comment]
Guy, I really want this RSS styling feature.

It's already ready.
You only need the CSS design in place (I'm willing to take that CSS task) and just attache a reference to the XSL file so it would work.

**Please tell me what you want to be done in order to accelerate a PR for this.**

**Comment by GreenLunar** [comment]
Friends, I really want this RSS styling feature.

It's already ready.
You only need the CSS design in place (I'm willing to take that CSS task) and just attache a reference to the XSL file so it would work.

**Please tell me what you want to be done in order to accelerate a PR for this.**

**Comment by return42** [comment]
Hi @GreenLunar .. we are sorry for the delay, but our resources are limited and we have a lot of (other) work on the stack .. it is Open-Source, since no one pays for, no one can say when a feature is implemented .. this does not mean that we disagree with your request.

If you want to accelerate your request implement a PR by yourself .. or look out for someone who has time and skills needed for.

Sorry that we can't help you right now ..

**Comment by GreenLunar** [comment]
I'll make a PR.
Please tell me, the style of which themes do you want me to comply with?

**Comment by GreenLunar** [comment]
I'll make a PR.
Please tell me, the style of which themes do you want me to comply with?
Please give me an initial help and point me directly to the cide responsible for SearcxxNG RSS feed feature.

**Comment by sjehuda** [comment]
I've e-mailed to GL earlier.
I'll take care of it with a little surprise you probably didn't expect.
Wait for it. It's gonna be interesting!
