### ISSUE TITLE
Simple theme: image is not always fulll size

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#898]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 1.0.0-1691-a4942213 

**How did you install SearXNG?**
searxng-docker

**What happened?**
* Search for anything with the openverse engine.
* Click on any image
* The image does not cover the full size of the detail area. However the image is high resolution

**How To Reproduce**

**Expected behavior**
See screenshot: the image should use the full detail area.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/1594191/154138872-dd676551-463b-4850-9419-6663bbf09d18.png)

**Additional context**

The issue is fixed by removing `width="200" height="200"` here:
https://github.com/searxng/searxng/blob/288e3086d2a67aaee45576f13b032f31ab782b45/searx/templates/simple/result_templates/images.html#L14

I think these two attributes should be removed:
* the detail is hidden and browser won't load the image when the page is loaded.
* the default width and height is 0: this is what we want here, since the detail is hidden by default.

**Comment by return42** [comment]
> I think these two attributes should be removed:

AFAIK the `width="200" height="200"` are needed by lazy loading:

- https://github.com/searxng/searxng/pull/573

Images should include dimension attributes.  Without `width` and `height` specified, image dimensions are 0×0 pixels at first.  ...  In this case the browser determines that all of them are visible to the user and decides to load everything [1].

In CSS the `width` is set to a value and the `height` is _unset_ to scale the image proportional in both dimensions.

[1] https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes
[2] https://caniuse.com/loading-lazy-attr

**Comment by dalf** [comment]
From what I understand: the `width` and `height` are here only to push the visible content out of the viewport, so the browser doesn't load the images outside of the viewport.

These images (high resolution images) are hidden by CSS: even if the browser thinks the images are displayed (before the browser load & parse the CSS), the width and height of 0 is exactly what we want: take no space of the visible viewport (and when the user click on a thumbnail, the page is fully initialized with CSS & JS).

But JS is involved in the code anyway, so an alternative is:
`<img data-src="{{ image_proxify(result.img_src) }}" alt="{{ result.title|striptags }}">`

**Comment by mrpaulblack** [comment]
@dalf are you sure this is still a issue? I tried to repro on my instance and with openverse there where no small images in the image detail view:

![image](https://user-images.githubusercontent.com/38733246/168450445-3d76f033-d143-4453-8b08-048ca1225df0.png)


(If its not an issue anymore please close :+1: )

**Comment by dalf** [comment]
Please don't close the issue, I'm going to try tomorrow on a 4K screen.

**Comment by return42** [comment]
FYI I tested the example from initial comment and for me it works on a 4k desktop

**Comment by dalf** [comment]
> FYI I tested the example from initial comment and for me it works on a 4k desktop

So ok (I've not tested).

The thing is the template is too complicated:
https://github.com/searxng/searxng/blob/f814ac703b25640d28ab3a4a096f693808cde6db/searx/templates/simple/result_templates/images.html#L12-L16

Could be
```jinja2
<img src="" data-src="{{ image_proxify(result.thumbnail_src or result.img_src) }}" alt="{{ result.title|striptags }}">
```

so, `lazy-loading` can be removed.

**Comment by return42** [comment]
> The thing is the template is too complicated:

Do you like to send a PR / then we can test how it works without lazy-loading.
