### ISSUE TITLE
[FEATURE] Add image sizes to thumbnails on image search

### ISSUE THREAD

**Issue by Shituation** [searxng/searxng#908]
**Is your feature request related to a problem? Please describe.**
Would be good to be able to see image sizes on each thumbnail of the image search category. Like commercial search engines do.

**Comment by tiekoetter** [comment]
Is this linked to #909 ?

**Comment by Shituation** [comment]
Yes, I would link it. Thanks.

**Comment by tiekoetter** [comment]
Can you close this issue please?

**Comment by Shituation** [comment]
Closing this since its being taken into account with the image size problems on #909
