### ISSUE TITLE
[BUG ?] Images on search engine are mostly small.

### ISSUE THREAD

**Issue by Shituation** [searxng/searxng#909]
Using searx.be public instance.
Images returned on the search image category are too small. Like really too small. No sizes on thumbnails option makes this worse, so the image search is unusable right now.

**How To Reproduce**
Search for images of whatever topic.

**Expected behavior**
To see a range of sizes, mostly medium, upwards. Also a filter for sizes would be cool.

**Comment by tiekoetter** [comment]
Could you give an example URL or Screenshot?

**Comment by Shituation** [comment]
On the search:
![image](https://user-images.githubusercontent.com/43975882/154712225-194a0d79-2765-45d4-879f-4cdd169017f4.png)

After opening:
![image](https://user-images.githubusercontent.com/43975882/154712388-a08aabff-f574-4944-930d-31272857a7c3.png)

Following "Source"
![image](https://user-images.githubusercontent.com/43975882/154712673-75cae8d8-2ad1-41cd-8238-1b6d78fb3695.png)

**Comment by tiekoetter** [comment]
This seems to depend on which engine is used.

Example: Google Images
https://searx.tiekoetter.com/search?q=%21goi+land+%3Aen_us

Example: Bing Images
https://searx.tiekoetter.com/search?q=%21bii+land+%3Aen_us

I will take a look if there is an option to get a different size from google images.

**Comment by dalf** [comment]
Related to https://github.com/searxng/searxng/issues/898
