### ISSUE TITLE
Webapp.py line 54 no Searx module

### ISSUE THREAD

**Issue by baxterdmutt** [searxng/searxng#914]
After a fresh install I keep getting an error at line 54 of webapp.py. "No searx module" on import. I did run the requirements.txt package installation and didn't notice any errors. I switched to SEARX  (instead of SEARXNG) and the issue did not occur there. I did have searx installed before but I had deactivated the virtual environments, and deleted everything in the searxng directories. I removed everything that Searx installed so that shouldn’t be the issue. Any ideas?

**Comment by dalf** [comment]
I'm not sure how you start SearXNG, but if you have `python searx/webapp.py` try `python -m searx.webapp`, it should fix the issue.

**Comment by baxterdmutt** [comment]
Ok. Thanks. I’ll give that a try. I was starting with python searx/webapp.py like you thought. So what is the reason it doesn’t work the way I’m doing it?  Just trying to learn a bit.

**Comment by baxterdmutt** [comment]
Well that didn’t work. Showed a multitude of errors and now says it can’t find the httpx module.

**Comment by baxterdmutt** [comment]
Could this be that I had searx previously installed. I’ve removed everything from my usr/local/searx directory and didn’t manually place anything anywhere else. It feels like it’s conflicting with something else. Is that possible.

**Comment by return42** [comment]
Sorry that we couldn't help .. I'm going to close this issue .. if you have more information please ask to reopen.
