### ISSUE TITLE
Switch versioning format since SearXNG is rolling release

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#915]
**Is your feature request related to a problem? Please describe.**
Right now we use the shortened git commit SHA as version. This can be hard for people to know which version an instance is running on.

**Describe the solution you'd like**
Instad of displaying version 1.0.0-commit_sha we should do a version like this for example: `2022-02-20-1` This way its more straight forward what version and instance is running and how old this version is. The `1.0.0` is not really needed in rolling release IMO.

**Describe alternatives you've considered**
Use the shortened commit SHA as version but still drop the `1.0.0`.

**Additional context**

**Comment by unixfox** [comment]
That's a very good idea, in fact at invidious we have the date + the commit hash for the version.
See example: https://api.invidious.io/
