### ISSUE TITLE
Bug: startpage engine CAPTCHA

### ISSUE THREAD

**Issue by Myuriii** [searxng/searxng#923]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**
Search query doesn't return results, throws a CAPTCHA error every time

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 60
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 35
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

Checker
  * paging: `No result`,`results are identitical for pageno=2 and pageno=3 (query='news' lang='all' safesearch=0 time_range=None)`,
  * lang_fr: `No result`,`fr not found`,
  * lang_en: `No result`,`en not found`,

**Comment by return42** [comment]
Please fill out the bug report / did you updated your instance?  .. https://github.com/searxng/searxng/pull/695

**Comment by return42** [comment]
I close this issue in lack of feedback.
