### ISSUE TITLE
UI question: add help & donate links in the top right corner.

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#931]
The oscar theme provides some easy to see links to the help.
searx.be adds a link to a donation page.

How to add these links ?

A suggestion here:

## On desktop

![image](https://user-images.githubusercontent.com/1594191/156043356-44fdedca-1e4f-4020-9979-39352c425439.png)

![image](https://user-images.githubusercontent.com/1594191/156043548-654edd02-9175-4a94-b4bc-ab4cf594ace2.png)

### Alternative for the result page
![image](https://user-images.githubusercontent.com/1594191/156043626-7510870c-53f2-4583-a9d1-a0b409ea1a70.png)

## On tablet

![image](https://user-images.githubusercontent.com/1594191/156045788-ddb68ff7-e580-409f-afcf-f22994065610.png)

### Alternative for the result page
![image](https://user-images.githubusercontent.com/1594191/156045850-3fa36fd5-3bad-4666-a0ef-58fea66a327c.png)

### index page

| with labels| only icons|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1594191/156044217-6e9732ad-9262-4234-b489-b4fcedc4f71b.png) | ![image](https://user-images.githubusercontent.com/1594191/156044645-be17936d-dc9e-4975-99fc-ad662cbbc4ed.png) |

### result page
The result page remains the same
![image](https://user-images.githubusercontent.com/1594191/156044170-312113fe-b7c9-4d58-b759-9aeb31373180.png)

---

icons ( https://ionic.io/ionicons ):
* help-circle-outline : there is an issue with the SVG, two attributes are missing `stroke="currentColor" fill="currentColor"` on the `circle` element. They can be added by CSS (?) or we can provide our own version.
* heart-outline

**Comment by unixfox** [comment]
I like the idea of having the text with the icon on the desktop version and no text on the mobile version.

IMO this help in accessibility.
