### ISSUE TITLE
Add option to use CSS Selectors

### ISSUE THREAD

**Issue by allendema** [searxng/searxng#933]
**Is your feature request related to a problem? Please describe.**

When creaating a new engine you can choose between json, xpath expressions but not CSS Selctors.

**Describe the solution you'd like**

The solution would be to import a library which will allow the usage of CSS Selectors.

My favorite one tu use is BeautifulSoup (bs4).

[BeautifulSoup docs](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

Then similiar to xpath, an ```css_selector``` engine would be created.

Or CSS Selctors could be imported to other engines.

**Describe alternatives you've considered**

**There have been other alternative mentioned on Matrix room**
- https://github.com/Kozea/cssselect2
- https://github.com/gawel/pyquery
- requests-html
- [requests-html docs](https://docs.python-requests.org/projects/requests-html/en/latest/)

**Additional context**

- [From Matrix chat](https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$W-Uw5VV7fxpLcT4asPQe0pSdw59ekilghUl2wXZ9XsE?via=libera.chat&via=matrix.org&via=tchncs.de)

- [From Matrix chat](https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$IKmpSFFgetTM0rJ4NNF85BGTlyrP_HwNAn4N_iyqxbk?via=libera.chat&via=matrix.org&via=tchncs.de)

**Comment by return42** [comment]
Copied some notes from @dalf from matrix ..

About CSS selector, for simple user case, I don't know if https://github.com/Kozea/cssselect2 or https://github.com/gawel/pyquery can help to keep lxml (which is faster than BS)

**Comment by GreenLunar** [comment]
I'm only asking for knowledge.
Isn't XPath Query more accurate than CSS Selectors?

**Comment by allendema** [comment]
Xpath takes more time to write.

**Comment by return42** [comment]
> I'm only asking for knowledge.

XPath is a query language to select nodes from a XML document.  A structure of a XML document (aka application) is described by XSD (XML Schema Definition). HTML is such a XML application, tho there does not exists a XSD for, but HTML is XML and you can use the XML tools, like a XML parser and the XPath query language.

To parse and process XML we use the [lxml](https://lxml.de/) library.  This library is build on the [Libxml2 XML C parser](https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home) and the [libxslt XSLT C library](https://gitlab.gnome.org/GNOME/libxslt/-/wikis/home) from the GNOME project. Both libraries are known to be (ultra) fast.

With CSS a style of a XML (or HTML) document can be defined.  To select nodes, CSS uses "CSS selectors".

With [lxml.cssselect](https://lxml.de/cssselect.html) CSS3 selectors can be parsed and translated to XPath expressions.

**Comment by GreenLunar** [comment]
> Xpath takes more time to write.

CSS Selectors takes more time to write, to me ;)

> With lxml.cssselect CSS3 selectors can be parsed and translated to XPath expressions.

Sweet! Gotta love programming!Gotta

**Comment by return42** [comment]
As describe above in https://github.com/searxng/searxng/issues/933#issuecomment-1058388863 you can use CSS selectors in a python module.  Its not planned to implement a CSS-Engine that can be uses in the settings.yml like known from the [XPath-Engine](https://docs.searxng.org/admin/engines/searx.engines.xpath.html).
