### ISSUE TITLE
Bug: semantic scholar engine

### ISSUE THREAD

**Issue by spikespaz** [searxng/searxng#939]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.03.02-67fd4e13

Latest docker container

**Technical report**

Error
  * Error: KeyError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/semantic_scholar.py:40`
  * Function: `response`
  * Code: `'url': result['primaryPaperLink']['url'],`

**Comment by return42** [comment]
Do you have a query with we can reproduce the issue?

**Comment by spikespaz** [comment]
Unfortunately I don't remember what it was. I think it was something like "this is a test" because I was playing with it.

**Comment by spikespaz** [comment]
Ideally the error that fills out this markdown should have that in it. Your error handling is a little lackluster I've noticed.

**Comment by return42** [comment]
Any suggestions to improve?

**Comment by kvch** [comment]
@return42 I could reproduce the issue with `!se where you go`. Just pushed a fix to searx: https://github.com/searx/searx/commit/c56f2f1d6b877cb27ead2eb6bc11cc71f0bd19ce

**Comment by return42** [comment]
@kvch thanks for pointing out .. I made a review of the engine --> https://github.com/searxng/searxng/pull/944
