### ISSUE TITLE
Bing returns low quality results since a few days

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#941]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```
67fd4e139dd7a6d577c48df9af6a8aeb909189e9
2022.03.02-67fd4e13
```

**How did you install SearXNG?**

docker image

**What happened?**
Bing returns low quality results for a query.

**How To Reproduce**
search for something with bing for example `!bing time`: https://paulgo.io/search?q=%21bing%20time&language=en-US&time_range=None&safesearch=1&categories=none

**Expected behavior**
The same results as on bing frontend for the same search query: https://www.bing.com/search?q=time&pq=

**Screenshots & Logs**

**Additional context**

**Comment by dalf** [comment]
FWIW, I don't have the issue on my personal instance

**Comment by return42** [comment]
@dalf did you test different languages? When I use "en" I got low quality, when I use en-GB I got better results .. anyway I think bing needs a review .. I will pick up this issue as soon I have time for.

**Comment by dalf** [comment]
Still on my instance:

| :fr | :de |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1594191/156752384-4635e564-b55a-45a5-a3c3-3f071c38e3de.png) | ![image](https://user-images.githubusercontent.com/1594191/156752432-53210380-245e-42d9-b6e5-6ffb0bbb1616.png) |

But I've experienced some HTTP Connection Error

**Comment by mrpaulblack** [comment]
Actually looking at https://searx.tiekoetter.com/search?q=%21bing+time&language=en-US&time_range=&safesearch=0&theme=simple it seems to be only my instance, because results for Leons instance are also fine...

[EDIT] maybe its time for me to finally setup some HTTP proxys since I also had problems with qwant a few weeks ago -_-

**Comment by return42** [comment]
FYI: I tried to fix the issue but did not had luck. 

https://github.com/searxng/searxng/compare/master...return42:fix-bing

.. in the commit you can see up there on my branch I was able to clean up the implementation a bit, but the selectors for the results stayed the same (bing didn't change anything there).  My impression is rather that the request we send there is not so good ... sometimes it returns a blank page ... 

All I have right now is just a cleanup of the bing engine .. I don't know if it make sense to create a PR for the cleanup.

**Comment by mrpaulblack** [comment]
Yeah the issue seems to be exclusive to my instance/VPS IP... bing also works correctly in my local dev env...

**Comment by return42** [comment]
Just for reference: bing links are broken / https://github.com/searxng/searxng/discussions/1209

**Comment by return42** [comment]
> Yeah the issue seems to be exclusive to my instance/VPS IP... bing also works correctly in my local dev env...

Bing-web works on local dev instances but does not work on SearXNG servers ... on a server (IP) I see different behaviours I can't classify .. except that all bing-web results are poor ;-)

**Comment by return42** [comment]
bing behaves like a moving target and is hard to catch .. PR:

- https://github.com/searxng/searxng/pull/2269

implements bing (and its image, news .. search engines) new.  Overall the situation should be improved compared to what we had when this issue was opened.

I am going to close this issue ..

If we have problems with bing again, we should open a new issue, because the code base has changed a lot in the meantime and can't be compared to what we had when this issue was opened.
