### ISSUE TITLE
Preferences, cookies tab bug

### ISSUE THREAD

**Issue by MontyQI** [searxng/searxng#945]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.03.05-740e3bc9

**How did you install SearXNG?**
Didn't install, just saw on public instance.

**What happened?**
When going to preferences tab, it always opens on cookies tab.

**How To Reproduce**
Go to preferences tab. See that it opens on cookies tab

**Expected behavior**
Open on general tab because it is the first.

**Screenshots & Logs**

https://user-images.githubusercontent.com/79922836/156918100-fe6adc02-551f-4768-bc95-ced26ab503cd.mp4

**Additional context**

**Comment by return42** [comment]
Same problem with engines tab where "other" is active

![grafik](https://user-images.githubusercontent.com/554536/159130574-ee92f863-ae4c-4208-bff9-b138daba978b.png)

----

EDIT: I prepare a patch ..

**Comment by return42** [comment]
@MontyQI I prepared https://github.com/searxng/searxng/pull/989 to fix the issue, could you please test / thanks!
