### ISSUE TITLE
Add ability to disable RSS/JSON/CSV

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#95]
**Is your feature request related to a problem? Please describe.**
Bots are the only users of this feature on a public instance, and they abuse it too much that the engines rate limit pretty quickly the IP address of the instance.

**Describe the solution you'd like**
I would like to disable the results in RSS/JSON/CSV format.

**Describe alternatives you've considered**
Using filtron in order to block the use of the RSS/JSON/CSV.

**Additional context**

**Comment by return42** [comment]
@dalf what do you think, should we make the format configurable (on/off) .. or should we add an option to configure a kind of "secret key" parameter for each format? (hope I was clear)

**Comment by dalf** [comment]
A secret key is similar to the token the engines: we can imagine a token for different features / configuration / preferences. But I don't think there is a need for that ?

So, we can start with a simple on / off.

**Comment by return42** [comment]
@unixfox PR #99 is available .. if you have time to test & approve / thanks!
