### ISSUE TITLE
Please allow engines ( Wolfram Alpha) from "Other" category by default for search results

### ISSUE THREAD

**Issue by geckolinux** [searxng/searxng#966]
Hi there, I enjoy the improvements made to the SearXNG theme compared to the original SearX "oscar" theme. But I think that there is a usability/feature regression in SearXNG by moving some engines to the "Other" category and only making them accessible via bangs, especially Wolfram Alpha. I personally don't like bangs, and for many searches I need the excellent results that Wolfram Alpha gives. With the original SearX I always enabled the "Science" category by default and in that category disabled all the engines except for Wolfram Alpha. This always gave me a very informative and useful sidebar. With SearXNG it could be even better than that by allowing the "Other" category by default and keeping the "Science" category available when needed for actual scientific queries. Thanks for taking this into account!

![Screenshot from 2022-03-16 09-17-00](https://user-images.githubusercontent.com/2692138/158612638-fdb1695f-2f0e-4964-8ae7-ef9863d24878.png)

![Screenshot from 2022-03-16 09-18-07](https://user-images.githubusercontent.com/2692138/158612666-38ad6922-49a7-4200-b5b5-b9be3c9ad2c6.png)

![Screenshot from 2022-03-16 09-19-49](https://user-images.githubusercontent.com/2692138/158612680-26347833-718f-4f60-9977-7710ae0a9727.png)

![Screenshot from 2022-03-16 09-30-46](https://user-images.githubusercontent.com/2692138/158613523-3d452306-f95c-437a-b25c-7db6a71c27ed.png)

**Comment by geckolinux** [comment]
I'm not very good coding, but I could probably find a way to add Wolfram Alpha back to the Science category. If I could do that would a pull request even be considered? I'm just asking before I dedicate a lot of time to it. Thanks a lot.

**Comment by mrpaulblack** [comment]
Hi @geckolinux ,
First sorry for the long wait for an answer. You already read our reasoning for moving wolframalpha to the other "category" here: https://github.com/searxng/searxng/pull/813. But at the same time I also understand your argument of not wanting to use bangs for wolframalpha all the time.

Maybe we can find a compromise. Instead of moving it back to the science category we can move it to a different category or create a new one for the current other category. But whatever we do I would like to keep it disabled by default upstream since its really slow...

What you can do for now is move it to the science category in your instances settings.yml file :+1:

**Comment by geckolinux** [comment]
Hi there @mrpaulblack , appreciate the response, and thanks for taking into account this usage scenario!

I understand the reasoning for moving it and not enabling it by default, that seems like a sane default. So how about the suggestion in the first post of this issue about adding a simple user config switch somewhere (disabled by default) to enable querying "Other" category engines by default for all searches? That would seem to be the most simple and flexible solution.

If for some reason that isn't possible, then moving Wolfram Alpha to a new category (and even disabling Wolfram Alpha by default) would also be fine. Maybe the category could be called "Info" or "Instant". And it that case it would make sense to move there some other engines too that are also used more like reference sources rather than strict search engines, such as Wikidata and Wordnik.

I would just apply the quick fix of moving Wolfram Alpha back to the science category via the settings file, but the problem is that I only use public instances, so no access to it.

Thanks again!

**Comment by xieve** [comment]
You can also just add WolframAlpha to General like this:
```yml
engines:
  - name: wolframalpha
    categories: general
```
I would suggest that this would be the default config, with WolframAlpha disabled by default. This would mean every user could opt to use it for instant answers on any public instance while the default config would still be fast.

Would it be possible to lazy-load these results somehow? I'm guessing that that would require some changes to how engines work in general, but it'd be super cool if the results page could load before the instant answers were "known", and add them as soon as they would load. Should I write a new issue for that?

**Comment by return42** [comment]
> Would it be possible to lazy-load these results somehow?

Theoretical yes, but in practice SearXNG is made as static site / we have users that don't have JS on client side.

> I would suggest that this would be the default config, with WolframAlpha disabled by default. This would mean every user could opt to use it for instant answers on any public instance while the default config would still be fast.

I think this suggestion is a very good compromise of what @dalf posted https://github.com/searxng/searxng/pull/813#issuecomment-1020581765 and what the opener wants.

@geckolinux you can test it on my instanxce https://darmarit.org/searx

----

For all the others who come by: if you think this is a good solution, give your "thumbs up" or leave a comment .. / thanks!

**Comment by geckolinux** [comment]
Hi @return42 , thanks a lot for taking user preferences and requests into account!

> > I would suggest that this would be the default config, with WolframAlpha disabled by default. This would mean every user could opt to use it for instant answers on any public instance while the default config would still be fast.
> 
> I think this suggestion is a very good compromise of what @dalf posted [#813 (comment)](https://github.com/searxng/searxng/pull/813#issuecomment-1020581765) and what the opener wants.

Agreed!

> @geckolinux you can test it on my instanxce https://darmarit.org/searx

Works great! In fact I'm going to set your instance as my default search engine if you don't mind. I sure hope that this change can be pushed upstream so that all SearXNG instances will have it.
The only thing on your instance is that Wolfram Alpha has been categorized under "Science", not "General". Was that intended? Either way it works for what I need, as I don't usually do specific Science queries and I just disable all the other Science engines and set General and Science categories default for queries.  https://github.com/searxng/searxng/pull/813#issuecomment-1574851572 would be better still. 

Thanks again!

**Comment by geckolinux** [comment]
Thanks for accepting this suggestion!
